import { getLocale } from '../../locale';

const labels = {
    de: {
        'qlikSet.pageTitle': 'Qlik Set Analysis Generator',
        'qlikSet.pageLead': 'Erzeugt Child Measures, Variablen und Import-CSV aus einer Base Measure und Dimension-Wert-Listen.',
        'qlikSet.workbench.title': 'Formel-Workbench',
        'qlikSet.workbench.description': 'Katalog, Base Measures und Definitionen sind getrennte Arbeitsbereiche. Die Ausgabe darunter bleibt separat kopier- und exportierbar.',
        'qlikSet.workbench.controlTitle': 'Formel-Workbench',
        'qlikSet.workbench.controlHint': 'App-Kontext, Katalog, Base-Formeln, Filter und Hierarchie bearbeiten.',
        'qlikSet.workbench.show': 'Workbench anzeigen',
        'qlikSet.workbench.hide': 'Workbench ausblenden',
        'qlikSet.layout.catalog': 'Katalog',
        'qlikSet.layout.composer': 'Formel',
        'qlikSet.layout.builder': 'Filter & Baum',
        'qlikSet.layout.focusFormula': 'Fokus Formel',
        'qlikSet.layout.showAll': 'Alles anzeigen',
        'qlikSet.assets.title': 'App-Katalog',
        'qlikSet.assets.hint': 'Dimensionen per Drag and Drop verwenden. Measures und Variablen kannst du anklicken.',
        'qlikSet.catalog.dimension': 'Dimensionen',
        'qlikSet.catalog.measure': 'Measures',
        'qlikSet.catalog.date': 'Datum / Zeit',
        'qlikSet.catalog.other': 'Weitere Felder',
        'qlikSet.formula.title': 'Base Measure bauen',
        'qlikSet.formula.hint': 'Hier bearbeitest du die aktive Base Measure. Aus dieser Formel entstehen danach Child Measures, Variablen, CSV und Excel.',
        'qlikSet.formula.baseFlow': 'Neu starten setzt Name, Formel und Prefix auf Margin. Aktuelle speichern legt die Base in der App-Liste ab; Aus Liste laden holt eine vorhandene Base zur Bearbeitung zurueck.',
        'qlikSet.formula.current': 'Beispiel-Measure mit erstem Dim-Wert',
        'qlikSet.history.undo': 'Zurück',
        'qlikSet.history.redo': 'Vor',
        'qlikSet.palette.title': 'Bausteine',
        'qlikSet.palette.hint': 'Baustein wählen, um die Formel zu erweitern oder einen KPI-Modus zu setzen.',
        'qlikSet.palette.show': 'Bausteine anzeigen',
        'qlikSet.palette.hide': 'Bausteine ausblenden',
        'qlikSet.functions.title': 'Formel-Funktionen',
        'qlikSet.filter.title': 'Definition bauen',
        'qlikSet.filter.hint': 'Waehle eine Dimension und Werte. Daraus entsteht eine wiederverwendbare Set-Analysis-Definition, die danach mit Base Measures kombiniert wird.',
        'qlikSet.filter.drop': 'Dimension hier ablegen',
        'qlikSet.filter.dropTitle': 'Dimension hier ablegen',
        'qlikSet.filter.dropText': 'Ziehe eine Dimension aus dem App-Katalog hierher und waehle danach einen oder mehrere Werte im Feld darunter.',
        'qlikSet.tabs.filter': 'Definitionen',
        'qlikSet.tabs.hierarchy': 'Hierarchie',
        'qlikSet.tabs.extras': 'Extras',
        'qlikSet.kpis.title': 'KPI-Bloecke',
        'qlikSet.kpis.hint': 'KPI-Bloecke sind ein Modus: ein aktiver KPI wird ersetzt, nicht weiter verschachtelt. Der gleiche KPI ist gesperrt, bis du zurückgehst oder die Base Measure änderst.',
        'qlikSet.kpis.none': 'Kein KPI aktiv',
        'qlikSet.kpis.active': 'Aktiver KPI',
        'qlikSet.kpis.current': 'Current',
        'qlikSet.kpis.cy': 'Current Year',
        'qlikSet.kpis.py': 'Previous Year',
        'qlikSet.kpis.ytd': 'YTD',
        'qlikSet.kpis.mtd': 'MTD',
        'qlikSet.kpis.last12m': 'Last 12M',
        'qlikSet.kpis.yoy': 'YoY Delta',
        'qlikSet.kpis.yoyPct': 'YoY %',
        'qlikSet.hierarchy.title': 'Hierarchie bauen',
        'qlikSet.hierarchy.hint': 'Ziehe Dimensionen aus dem App-Katalog hierher. Sie werden unten an den Baum angehaengt und koennen danach im Baum umgehaengt werden.',
        'qlikSet.hierarchy.dropTitle': 'Dimension in Hierarchie ziehen',
        'qlikSet.hierarchy.dropText': 'Drop fuegt sie unten an. Fuer eine genaue Position direkt auf einen Slot im Baum ziehen.',
        'qlikSet.setVars.title': 'Set-Variable bauen',
        'qlikSet.setVars.hint': 'Erstellt eine Variable fuer Mehrfachselektionen und setzt sie direkt in die Set Analysis Formel ein.',
        'qlikSet.setVars.name': 'Set-Variablenname',
        'qlikSet.setVars.values': 'Mehrfachwerte',
        'qlikSet.setVars.add': 'Set-Variable hinzufügen',
        'qlikSet.setSearch.title': 'Formel im Set nutzen',
        'qlikSet.setSearch.hint': 'Erzeugt Such-Set-Analysis wie Customer={"=Sum(Sales)>1000"} aus der gewaehlten Dimension.',
        'qlikSet.setSearch.expression': 'Set-Suchformel',
        'qlikSet.setSearch.add': 'Suchdefinition hinzufügen',
        'qlikSet.tree.title': 'Measure-Child-Baum',
        'qlikSet.tree.hint': 'Auf Base ablegen erzeugt Dimensionen nebeneinander. Auf eine bestehende Dimension ablegen erzeugt eine Child-Ebene darunter.',
        'qlikSet.tree.currentDimension': 'Aktuelle Dimension',
        'qlikSet.tree.base': 'Base Measure',
        'qlikSet.tree.dropOnBase': 'Dimension auf erster Ebene ablegen',
        'qlikSet.tree.dropOnNode': 'Auf {level} ablegen, um darunter ein Child zu bauen',
        'qlikSet.tree.noValues': 'keine Werte importiert',
        'qlikSet.tree.moreValues': 'weitere',
        'qlikSet.tree.remove': 'Entfernen',
        'qlikSet.help.title': 'Qlik Set Analysis Hilfe',
        'qlikSet.help.lead': 'Workflow-Hilfe für Katalog, Definitionen, Base Measures, Hierarchie und Qlik-Master-Items.',
        'qlikSet.help.show': 'Hilfe anzeigen',
        'qlikSet.help.hide': 'Hilfe ausblenden',
        'qlikSet.howto.summary': 'Hilfe',
        'qlikSet.howto.intro': 'Der Generator arbeitet wie eine kleine Qlik-App-Schablone: Katalog pflegen, Base Measures bauen, Filter/Hierarchie anwenden und Ausgabe übernehmen.',
        'qlikSet.howto.step1': 'App oben speichern, damit Felder, Variablen, Dim-Werte, Base Measures, Beschreibungen und Hierarchie zusammen erhalten bleiben.',
        'qlikSet.howto.step2': 'Im App-Katalog Felder, Measures, Variablen und bereits generierte Formeln nutzen. Rohdaten und Dim-Werte bearbeitest du im Katalog-Modal.',
        'qlikSet.howto.step3': 'In der Workbench Base-Formeln bauen, Definitionen aus Mehrfachwerten speichern und dieselben Definitionen fuer mehrere Base Measures nutzen.',
        'qlikSet.howto.tip': 'Die Ausgabe ist bewusst Copy-Paste-freundlich. Vor produktiver Nutzung in Qlik immer gegen manuelle Selektionen und Master-Item-Konventionen testen.',
        'qlikSet.export.summary': 'Dimensionen aus Qlik exportieren',
        'qlikSet.export.intro': 'Schneller Weg ohne API: erstelle in Qlik eine Tabelle, exportiere sie als CSV/XLSX und speichere sie als CSV mit den Spalten dimension,value,label.',
        'qlikSet.export.step1': 'Lege ein temporäres Sheet an und erstelle eine Tabelle mit den relevanten Dimensionsfeldern.',
        'qlikSet.export.step2': 'Benenne die Spalten fuer den Export eindeutig, zum Beispiel dimension, value und label.',
        'qlikSet.export.step3': 'Exportiere die Tabelle aus Qlik als Datenexport und speichere sie als CSV.',
        'qlikSet.export.step4': 'Lade die CSV hier hoch oder kopiere die Zeilen in das Textfeld.',
        'qlikSet.masterItems.summary': 'Master Items und Variablen in Qlik anlegen',
        'qlikSet.masterItems.intro': 'Empfohlener Ablauf: erst Variablen anlegen, dann eine Base Master Measure, danach die generierten Child Measures als Master Measures speichern.',
        'qlikSet.masterItems.step1': 'App im Bearbeitungsmodus öffnen. Variablen können in der Variablenübersicht oder im Ladescript angelegt werden.',
        'qlikSet.masterItems.step2': 'Zeitvariablen aus der Ausgabe kopieren. Script-Variablen über den Data Load Editor anlegen; UI-Variablen über die Variablenübersicht anlegen.',
        'qlikSet.masterItems.step3': 'Base Measure als Master Measure anlegen, z.B. Sales = Sum(Sales). Beschreibung, Tags und Zahlenformat ergänzen.',
        'qlikSet.masterItems.step4': 'Child Measures aus der Ausgabe als weitere Master Measures anlegen. Namen, Beschreibung und Filterlogik dokumentieren.',
        'qlikSet.masterItems.step5': 'In einer Test-Tabelle je Child Measure gegen eine manuelle Selektion prüfen, bevor die Measures in produktive Sheets wandern.',
        'qlikSet.masterItems.tip': 'Wichtig: Variablen mit $(vName) werden per Dollar-Sign Expansion vor der Auswertung ersetzt. Variablen mit führendem = können anders aggregieren als reine Ausdrucksvariablen.',
        'qlikSet.useCases.summary': 'Typische Fälle und Stolperstellen',
        'qlikSet.useCases.intro': 'Diese Fälle deckt der Generator ab:',
        'qlikSet.useCases.case1': 'Segment-Measures: Sales für Region, Channel, Brand, Product Group oder Customer Type.',
        'qlikSet.useCases.case2': 'Kombinierte Filter: Sales für Region + Channel oder Markt + Produktgruppe.',
        'qlikSet.useCases.case3': 'Zeitvergleiche: Current Year, Previous Year, YTD, MTD und Last 12 Months über Standardvariablen.',
        'qlikSet.useCases.case4': 'Ausschlusslogik: Werte per -= aus dem aktuellen Kontext ausschließen.',
        'qlikSet.useCases.case5': 'Suchlogik: dynamische Search Strings wie {"=Sum(Sales)>0"} vorbereiten.',
        'qlikSet.useCases.case6': 'Migration von If-Logik: Nested If und Pick/Match als Vergleichsausgabe nutzen, Set Analysis als Zielausdruck prüfen.',
        'qlikSet.input.title': 'Set-Analysis-Eingaben',
        'qlikSet.input.description': 'Die Eingaben erzeugen gefilterte Measure-Varianten und optionale Variablen.',
        'qlikSet.input.measureName': 'Measure-Name',
        'qlikSet.input.baseDescription': 'Base-Beschreibung',
        'qlikSet.input.baseDescriptionDe': 'Base-Beschreibung DE',
        'qlikSet.input.baseDescriptionEn': 'Base-Beschreibung EN',
        'qlikSet.input.baseMeasure': 'Base Measure',
        'qlikSet.input.variablePrefix': 'Variablen-Prefix',
        'qlikSet.input.mode': 'Generator-Modus',
        'qlikSet.input.setIdentifier': 'Set Identifier',
        'qlikSet.input.assignment': 'Assignment Operator',
        'qlikSet.input.expressionStyle': 'Expression-Stil',
        'qlikSet.input.valueMode': 'Wert-/Suchmodus',
        'qlikSet.input.useVariables': 'Variablen nutzen',
        'qlikSet.input.csvUpload': 'Dimension/Wert CSV importieren',
        'qlikSet.input.dateField': 'Datumsfeld',
        'qlikSet.input.yearField': 'Jahresfeld',
        'qlikSet.input.rows': 'Dimension/Wert-Liste',
        'qlikSet.input.rowsHint': 'Diese Liste fuellt die Wert-Dropdowns. Daraus kannst du Definitionen erstellen. Erwartete Spalten: dimension, value, label, operator, assignment.',
        'qlikSet.input.advanced': 'Feinoptionen',
        'qlikSet.apps.name': 'App-Name',
        'qlikSet.apps.saved': 'Gespeicherte Apps',
        'qlikSet.apps.none': 'Keine App gewählt',
        'qlikSet.apps.save': 'App speichern',
        'qlikSet.apps.load': 'App laden',
        'qlikSet.apps.delete': 'App löschen',
        'qlikSet.apps.missingName': 'Bitte einen App-Namen eingeben.',
        'qlikSet.apps.missingSelection': 'Bitte eine gespeicherte App wählen.',
        'qlikSet.apps.savedMessage': 'App "{name}" gespeichert.',
        'qlikSet.apps.deletedMessage': 'App "{name}" gelöscht.',
        'qlikSet.baseList.title': 'Base Measures',
        'qlikSet.baseList.hint': 'Demo startet mit Sales und Costs. Margin kannst du als neue Base-Formel ergänzen und dieselbe Hierarchie wiederverwenden.',
        'qlikSet.baseList.show': 'Base Measures anzeigen',
        'qlikSet.baseList.hide': 'Base Measures ausblenden',
        'qlikSet.baseList.csv': 'Base-Measure-Liste',
        'qlikSet.baseList.active': 'Vorhandene Base Measure',
        'qlikSet.baseList.load': 'Aus Liste laden',
        'qlikSet.baseList.saveCurrent': 'Aktuelle speichern',
        'qlikSet.baseList.newBase': 'Neue Margin starten',
        'qlikSet.baseList.empty': 'Noch keine Base Measures',
        'qlikSet.baseList.rawHint': 'Optional: CSV direkt bearbeiten, wenn du viele Base Measures importierst. Spalten: name, expression, prefix, description_de, description_en.',
        'qlikSet.baseList.addCurrent': 'Aktuelle speichern',
        'qlikSet.baseList.useSingle': 'Nur aktuelle Formel nutzen',
        'qlikSet.catalog.title': 'App-Felder und Variablen',
        'qlikSet.catalog.description': 'Importiere Feldlisten und Variablen aus deiner App oder pflege sie hier manuell. Die Listen fuellen die Eingabehilfen und die generierten Scripts.',
        'qlikSet.catalog.fieldsUpload': 'Feldliste hochladen',
        'qlikSet.catalog.variableUpload': 'Variablenliste hochladen',
        'qlikSet.catalog.fields': 'Felder aus der App',
        'qlikSet.catalog.variables': 'Variablen',
        'qlikSet.catalog.values': 'Dim-Werte',
        'qlikSet.catalog.tabs.dimensions': 'Dims',
        'qlikSet.catalog.tabs.measures': 'Measures',
        'qlikSet.catalog.tabs.variables': 'Vars',
        'qlikSet.catalog.tabs.generated': 'Erstellt',
        'qlikSet.catalog.noGenerated': 'Noch keine generierten Formeln.',
        'qlikSet.catalog.rawData': 'Katalog bearbeiten',
        'qlikSet.catalog.rawDataHint': 'Pflege hier App-Felder, vorhandene Variablen und Dimension/Wert-Kombinationen. Definitionen rechts nutzen diese Werte direkt im Dropdown.',
        'qlikSet.modal.close': 'Schließen',
        'qlikSet.fields.summary': 'Felder importieren',
        'qlikSet.composer.aggregation': 'Aggregation',
        'qlikSet.composer.measureField': 'Measure-Feld',
        'qlikSet.composer.apply': 'Base Measure setzen',
        'qlikSet.builder.addRow': 'Werte bearbeiten',
        'qlikSet.builder.editValues': 'Werte bearbeiten',
        'qlikSet.builder.applySetFilter': 'Definition speichern',
        'qlikSet.builder.missingSetFilter': 'Bitte Dimension und mindestens einen Wert auswählen.',
        'qlikSet.builder.noValues': 'keine Werte',
        'qlikSet.builder.addVariable': 'Variable hinzufügen',
        'qlikSet.builder.duplicate': 'Schon vorhanden.',
        'qlikSet.builder.dimension': 'Dimension',
        'qlikSet.builder.value': 'Werte',
        'qlikSet.builder.label': 'Label',
        'qlikSet.definitions.title': 'Definitionen',
        'qlikSet.definitions.hint': 'Definitionen sind Set Modifier wie Region DACH oder Current Year. Sie bleiben getrennt von Base Measures und koennen als Variablen wiederverwendet werden.',
        'qlikSet.definitions.name': 'Definitionsname',
        'qlikSet.definitions.variable': 'Variable',
        'qlikSet.definitions.preview': 'Set Modifier Vorschau',
        'qlikSet.definitions.raw': 'Definitionen CSV',
        'qlikSet.definitions.rawSummary': 'Definitionen als CSV anzeigen',
        'qlikSet.definitions.empty': 'Noch keine Definitionen gespeichert. Ohne gespeicherte Definitionen werden Dim-Werte automatisch als Definitionen genutzt.',
        'qlikSet.definitions.saved': 'Definition gespeichert.',
        'qlikSet.definitions.noPreview': 'Dimension und Wert auswählen.',
        'qlikSet.values.editorTitle': 'Dim-Werte bearbeiten',
        'qlikSet.values.editorHint': 'Waehle eine Dimension aus dem Katalog, ergaenze Wert und optional ein Anzeigename. Die Roh-CSV darunter wird automatisch aktualisiert.',
        'qlikSet.values.value': 'Wert',
        'qlikSet.values.operator': 'Typ',
        'qlikSet.values.add': 'Wert hinzufügen',
        'qlikSet.values.added': 'Wert hinzugefügt.',
        'qlikSet.values.missing': 'Bitte Dimension und Wert ausfüllen.',
        'qlikSet.values.empty': 'Noch keine Dim-Werte gepflegt.',
        'qlikSet.values.rawSummary': 'Rohdaten / CSV anzeigen',
        'qlikSet.descriptions.summary': 'Beschreibung & Ausgabe-Sprache',
        'qlikSet.descriptions.hint': 'Texte bearbeiten, die in Measures, CSV und Excel ausgegeben werden.',
        'qlikSet.descriptions.show': 'Beschreibungen anzeigen',
        'qlikSet.descriptions.hide': 'Beschreibungen ausblenden',
        'qlikSet.descriptions.language': 'Ausgabe-Sprache',
        'qlikSet.descriptions.childTemplateDe': 'Child-Beschreibung Vorlage DE',
        'qlikSet.descriptions.childTemplateEn': 'Child-Beschreibung Vorlage EN',
        'qlikSet.descriptions.placeholders': 'Platzhalter: {baseDescription}, {measureName}, {baseMeasure}, {label}, {modifier}, {dimensions}, {values}. Diese Texte landen in der Measure-Ausgabe, CSV und Excel.',
        'qlikSet.output.measures': 'Measures',
        'qlikSet.output.variables': 'Vars',
        'qlikSet.output.timeVariables': 'Zeit Vars',
        'qlikSet.output.modifiers': 'Set',
        'qlikSet.output.nestedIf': 'If',
        'qlikSet.output.pickMatch': 'Pick',
        'qlikSet.output.csv': 'CSV',
        'qlikSet.download.measuresXlsx': 'Measures als Excel',
        'qlikSet.download.measuresCsv': 'Measures als CSV',
        'qlikSet.download.variablesXlsx': 'Variablen als Excel',
        'qlikSet.download.variablesCsv': 'Variablen als CSV',
        'qlikSet.copy': 'Kopieren',
        'shared.copied': 'Kopiert!',
    },
    en: {
        'qlikSet.pageTitle': 'Qlik Set Analysis Generator',
        'qlikSet.pageLead': 'Generates child measures, variables, and import CSV from a base measure and dimension value lists.',
        'qlikSet.workbench.title': 'Formula workbench',
        'qlikSet.workbench.description': 'Catalog, base measures, and definitions are separated work areas. Output below stays independent for copy and export.',
        'qlikSet.workbench.controlTitle': 'Formula workbench',
        'qlikSet.workbench.controlHint': 'Edit app context, catalog, base formulas, definitions, and hierarchy.',
        'qlikSet.workbench.show': 'Show workbench',
        'qlikSet.workbench.hide': 'Hide workbench',
        'qlikSet.layout.catalog': 'Catalog',
        'qlikSet.layout.composer': 'Formula',
        'qlikSet.layout.builder': 'Filters & tree',
        'qlikSet.layout.focusFormula': 'Focus formula',
        'qlikSet.layout.showAll': 'Show all',
        'qlikSet.assets.title': 'App catalog',
        'qlikSet.assets.hint': 'Use dimensions via drag and drop. Measures and variables can be clicked.',
        'qlikSet.catalog.dimension': 'Dimensions',
        'qlikSet.catalog.measure': 'Measures',
        'qlikSet.catalog.date': 'Date / time',
        'qlikSet.catalog.other': 'Other fields',
        'qlikSet.formula.title': 'Build base measure',
        'qlikSet.formula.hint': 'Edit the active base measure here. Child measures, variables, CSV, and Excel output are generated from this formula.',
        'qlikSet.formula.baseFlow': 'Start new prepares name, formula, and prefix for Margin. Save current stores the base in the app list; Load from list brings an existing base back for editing.',
        'qlikSet.formula.current': 'Example measure with first dimension value',
        'qlikSet.history.undo': 'Undo',
        'qlikSet.history.redo': 'Redo',
        'qlikSet.palette.title': 'Building blocks',
        'qlikSet.palette.hint': 'Choose a block to extend the formula or set a KPI mode.',
        'qlikSet.palette.show': 'Show blocks',
        'qlikSet.palette.hide': 'Hide blocks',
        'qlikSet.functions.title': 'Formula functions',
        'qlikSet.filter.title': 'Build definition',
        'qlikSet.filter.hint': 'Choose a dimension and values. This creates a reusable set-analysis definition that is later combined with base measures.',
        'qlikSet.filter.drop': 'Drop dimension here',
        'qlikSet.filter.dropTitle': 'Drop dimension here',
        'qlikSet.filter.dropText': 'Drag a dimension from the app catalog here, then choose one or more values below.',
        'qlikSet.tabs.filter': 'Definitions',
        'qlikSet.tabs.hierarchy': 'Hierarchy',
        'qlikSet.tabs.extras': 'Extras',
        'qlikSet.kpis.title': 'KPI blocks',
        'qlikSet.kpis.hint': 'KPI blocks behave like a mode: an active KPI is replaced, not nested again. The same KPI is locked until you undo or change the base measure.',
        'qlikSet.kpis.none': 'No active KPI',
        'qlikSet.kpis.active': 'Active KPI',
        'qlikSet.kpis.current': 'Current',
        'qlikSet.kpis.cy': 'Current year',
        'qlikSet.kpis.py': 'Previous year',
        'qlikSet.kpis.ytd': 'YTD',
        'qlikSet.kpis.mtd': 'MTD',
        'qlikSet.kpis.last12m': 'Last 12M',
        'qlikSet.kpis.yoy': 'YoY delta',
        'qlikSet.kpis.yoyPct': 'YoY %',
        'qlikSet.hierarchy.title': 'Build hierarchy',
        'qlikSet.hierarchy.hint': 'Drag dimensions from the app catalog here. They are appended to the tree and can be rearranged inside the tree.',
        'qlikSet.hierarchy.dropTitle': 'Drag dimension into hierarchy',
        'qlikSet.hierarchy.dropText': 'Drop appends it. For exact placement, drag directly onto a tree slot.',
        'qlikSet.setVars.title': 'Build set variable',
        'qlikSet.setVars.hint': 'Creates a variable for multiple selections and inserts it into the set analysis expression.',
        'qlikSet.setVars.name': 'Set variable name',
        'qlikSet.setVars.values': 'Multiple values',
        'qlikSet.setVars.add': 'Add set variable',
        'qlikSet.setSearch.title': 'Use formula in set analysis',
        'qlikSet.setSearch.hint': 'Creates search set analysis such as Customer={"=Sum(Sales)>1000"} from the selected dimension.',
        'qlikSet.setSearch.expression': 'Set search formula',
        'qlikSet.setSearch.add': 'Add search definition',
        'qlikSet.tree.title': 'Measure child tree',
        'qlikSet.tree.hint': 'Drop on Base to create sibling dimensions. Drop on an existing dimension to create a child level below it.',
        'qlikSet.tree.currentDimension': 'Current dimension',
        'qlikSet.tree.base': 'Base measure',
        'qlikSet.tree.dropOnBase': 'Drop dimension on first level',
        'qlikSet.tree.dropOnNode': 'Drop on {level} to create a child below it',
        'qlikSet.tree.noValues': 'no values imported',
        'qlikSet.tree.moreValues': 'more',
        'qlikSet.tree.remove': 'Remove',
        'qlikSet.help.title': 'Qlik Set Analysis help',
        'qlikSet.help.lead': 'Workflow help for catalog, definitions, base measures, hierarchy, and Qlik master items.',
        'qlikSet.help.show': 'Show help',
        'qlikSet.help.hide': 'Hide help',
        'qlikSet.howto.summary': 'Help',
        'qlikSet.howto.intro': 'The generator works like a small Qlik app template: maintain the catalog, build base measures, save definitions, and use the output.',
        'qlikSet.howto.step1': 'Save the app at the top so fields, variables, dimension values, base measures, descriptions, and hierarchy stay together.',
        'qlikSet.howto.step2': 'Use fields, measures, variables, and generated formulas in the app catalog. Edit raw catalog data and dimension values in the catalog modal.',
        'qlikSet.howto.step3': 'Build base formulas in the workbench, save definitions from multiple values, and reuse the same definitions for several base measures.',
        'qlikSet.howto.tip': 'The output is intentionally copy-paste friendly. Before production use in Qlik, validate it against manual selections and master-item conventions.',
        'qlikSet.export.summary': 'Export dimensions from Qlik',
        'qlikSet.export.intro': 'Quick route without an API: create a table in Qlik, export it as CSV/XLSX, and save it as CSV with dimension,value,label columns.',
        'qlikSet.export.step1': 'Create a temporary sheet and add a table with the relevant dimension fields.',
        'qlikSet.export.step2': 'Name the export columns clearly, for example dimension, value, and label.',
        'qlikSet.export.step3': 'Export the table from Qlik as a data export and save it as CSV.',
        'qlikSet.export.step4': 'Upload the CSV here or paste the rows into the text area.',
        'qlikSet.masterItems.summary': 'Create master items and variables in Qlik',
        'qlikSet.masterItems.intro': 'Recommended flow: create variables first, then one base master measure, then save the generated child measures as master measures.',
        'qlikSet.masterItems.step1': 'Open the app in edit mode. Variables can be created in the variables overview or in the load script.',
        'qlikSet.masterItems.step2': 'Copy the time variables output. Create script variables in the Data load editor; create UI variables in the variables overview.',
        'qlikSet.masterItems.step3': 'Create the base measure as a master measure, for example Sales = Sum(Sales). Add description, tags, and number formatting.',
        'qlikSet.masterItems.step4': 'Create the generated child measures as additional master measures. Document name, description, and filter logic.',
        'qlikSet.masterItems.step5': 'Validate every child measure in a test table against a manual selection before using it in production sheets.',
        'qlikSet.masterItems.tip': 'Important: variables called with $(vName) are expanded before evaluation. Variables starting with = can aggregate differently from plain expression variables.',
        'qlikSet.useCases.summary': 'Typical cases and pitfalls',
        'qlikSet.useCases.intro': 'The generator covers these cases:',
        'qlikSet.useCases.case1': 'Segment measures: Sales for region, channel, brand, product group, or customer type.',
        'qlikSet.useCases.case2': 'Combined filters: Sales for region + channel or market + product group.',
        'qlikSet.useCases.case3': 'Time comparisons: current year, previous year, YTD, MTD, and last 12 months via standard variables.',
        'qlikSet.useCases.case4': 'Exclusion logic: exclude values from the current context with -=.',
        'qlikSet.useCases.case5': 'Search logic: prepare dynamic search strings such as {"=Sum(Sales)>0"}.',
        'qlikSet.useCases.case6': 'Migrating If logic: use Nested If and Pick/Match as comparison outputs, then validate set analysis as the target expression.',
        'qlikSet.input.title': 'Set analysis inputs',
        'qlikSet.input.description': 'These inputs generate filtered measure variants and optional variables.',
        'qlikSet.input.measureName': 'Measure name',
        'qlikSet.input.baseDescription': 'Base description',
        'qlikSet.input.baseDescriptionDe': 'Base description DE',
        'qlikSet.input.baseDescriptionEn': 'Base description EN',
        'qlikSet.input.baseMeasure': 'Base measure',
        'qlikSet.input.variablePrefix': 'Variable prefix',
        'qlikSet.input.mode': 'Generator mode',
        'qlikSet.input.setIdentifier': 'Set identifier',
        'qlikSet.input.assignment': 'Assignment operator',
        'qlikSet.input.expressionStyle': 'Expression style',
        'qlikSet.input.valueMode': 'Value/search mode',
        'qlikSet.input.useVariables': 'Use variables',
        'qlikSet.input.csvUpload': 'Import dimension/value CSV',
        'qlikSet.input.dateField': 'Date field',
        'qlikSet.input.yearField': 'Year field',
        'qlikSet.input.rows': 'Dimension/value list',
        'qlikSet.input.rowsHint': 'This list feeds the value dropdowns. Use it to create definitions. Expected columns: dimension, value, label, operator, assignment.',
        'qlikSet.input.advanced': 'Fine options',
        'qlikSet.apps.name': 'App name',
        'qlikSet.apps.saved': 'Saved apps',
        'qlikSet.apps.none': 'No app selected',
        'qlikSet.apps.save': 'Save app',
        'qlikSet.apps.load': 'Load app',
        'qlikSet.apps.delete': 'Delete app',
        'qlikSet.apps.missingName': 'Please enter an app name.',
        'qlikSet.apps.missingSelection': 'Please choose a saved app.',
        'qlikSet.apps.savedMessage': 'App "{name}" saved.',
        'qlikSet.apps.deletedMessage': 'App "{name}" deleted.',
        'qlikSet.baseList.title': 'Base measures',
        'qlikSet.baseList.hint': 'The demo starts with Sales and Costs. Add Margin as a new base formula and reuse the same hierarchy.',
        'qlikSet.baseList.show': 'Show base measures',
        'qlikSet.baseList.hide': 'Hide base measures',
        'qlikSet.baseList.csv': 'Base measure list',
        'qlikSet.baseList.active': 'Existing base measure',
        'qlikSet.baseList.load': 'Load from list',
        'qlikSet.baseList.saveCurrent': 'Save current',
        'qlikSet.baseList.newBase': 'Start new Margin',
        'qlikSet.baseList.empty': 'No base measures yet',
        'qlikSet.baseList.rawHint': 'Optional: edit the CSV directly when importing many base measures. Columns: name, expression, prefix, description_de, description_en.',
        'qlikSet.baseList.addCurrent': 'Save current',
        'qlikSet.baseList.useSingle': 'Use current formula only',
        'qlikSet.catalog.title': 'App fields and variables',
        'qlikSet.catalog.description': 'Import field lists and variables from your app or maintain them here. The lists power the input helpers and generated scripts.',
        'qlikSet.catalog.fieldsUpload': 'Upload field list',
        'qlikSet.catalog.variableUpload': 'Upload variable list',
        'qlikSet.catalog.fields': 'Fields from the app',
        'qlikSet.catalog.variables': 'Variables',
        'qlikSet.catalog.values': 'Dim values',
        'qlikSet.catalog.tabs.dimensions': 'Dims',
        'qlikSet.catalog.tabs.measures': 'Measures',
        'qlikSet.catalog.tabs.variables': 'Vars',
        'qlikSet.catalog.tabs.generated': 'Generated',
        'qlikSet.catalog.noGenerated': 'No generated formulas yet.',
        'qlikSet.catalog.rawData': 'Edit catalog',
        'qlikSet.catalog.rawDataHint': 'Maintain app fields, existing variables, and dimension/value pairs here. Definitions on the right use these values directly in their dropdowns.',
        'qlikSet.modal.close': 'Close',
        'qlikSet.fields.summary': 'Import fields',
        'qlikSet.composer.aggregation': 'Aggregation',
        'qlikSet.composer.measureField': 'Measure field',
        'qlikSet.composer.apply': 'Set base measure',
        'qlikSet.builder.addRow': 'Edit values',
        'qlikSet.builder.editValues': 'Edit values',
        'qlikSet.builder.applySetFilter': 'Save definition',
        'qlikSet.builder.missingSetFilter': 'Please choose a dimension and at least one value.',
        'qlikSet.builder.noValues': 'no values',
        'qlikSet.builder.addVariable': 'Add variable',
        'qlikSet.builder.duplicate': 'Already exists.',
        'qlikSet.builder.dimension': 'Dimension',
        'qlikSet.builder.value': 'Values',
        'qlikSet.builder.label': 'Label',
        'qlikSet.definitions.title': 'Definitions',
        'qlikSet.definitions.hint': 'Definitions are set modifiers such as Region DACH or Current Year. They stay separate from base measures and can be reused as variables.',
        'qlikSet.definitions.name': 'Definition name',
        'qlikSet.definitions.variable': 'Variable',
        'qlikSet.definitions.preview': 'Set modifier preview',
        'qlikSet.definitions.raw': 'Definitions CSV',
        'qlikSet.definitions.rawSummary': 'Show definitions as CSV',
        'qlikSet.definitions.empty': 'No definitions saved yet. Without saved definitions, dimension values are used as automatic definitions.',
        'qlikSet.definitions.saved': 'Definition saved.',
        'qlikSet.definitions.noPreview': 'Choose dimension and value.',
        'qlikSet.values.editorTitle': 'Edit dimension values',
        'qlikSet.values.editorHint': 'Choose a dimension from the catalog, add the value, and optionally a display label. The raw CSV below is updated automatically.',
        'qlikSet.values.value': 'Value',
        'qlikSet.values.operator': 'Type',
        'qlikSet.values.add': 'Add value',
        'qlikSet.values.added': 'Value added.',
        'qlikSet.values.missing': 'Please fill dimension and value.',
        'qlikSet.values.empty': 'No dimension values yet.',
        'qlikSet.values.rawSummary': 'Show raw data / CSV',
        'qlikSet.descriptions.summary': 'Description & output language',
        'qlikSet.descriptions.hint': 'Edit texts used in measures, CSV, and Excel output.',
        'qlikSet.descriptions.show': 'Show descriptions',
        'qlikSet.descriptions.hide': 'Hide descriptions',
        'qlikSet.descriptions.language': 'Output language',
        'qlikSet.descriptions.childTemplateDe': 'Child description template DE',
        'qlikSet.descriptions.childTemplateEn': 'Child description template EN',
        'qlikSet.descriptions.placeholders': 'Placeholders: {baseDescription}, {measureName}, {baseMeasure}, {label}, {modifier}, {dimensions}, {values}. These texts are used in the measure output, CSV, and Excel.',
        'qlikSet.output.measures': 'Measures',
        'qlikSet.output.variables': 'Vars',
        'qlikSet.output.timeVariables': 'Time Vars',
        'qlikSet.output.modifiers': 'Set',
        'qlikSet.output.nestedIf': 'If',
        'qlikSet.output.pickMatch': 'Pick',
        'qlikSet.output.csv': 'CSV',
        'qlikSet.download.measuresXlsx': 'Measures as Excel',
        'qlikSet.download.measuresCsv': 'Measures as CSV',
        'qlikSet.download.variablesXlsx': 'Variables as Excel',
        'qlikSet.download.variablesCsv': 'Variables as CSV',
        'qlikSet.copy': 'Copy',
        'shared.copied': 'Copied!',
    },
};

export function t(locale, key) {
    return labels[locale]?.[key] ?? labels.en[key] ?? key;
}

export function applyQlikSetLabels() {
    const locale = getLocale();
    document.querySelectorAll('[data-i18n]').forEach((el) => {
        const key = el.getAttribute('data-i18n');
        if (!key?.startsWith('qlikSet.') && !key?.startsWith('shared.')) return;
        el.textContent = t(locale, key);
    });
}
