import { getLocale } from '../../locale';

const labels = {
    de: {
        'qlikSet.pageTitle': 'Qlik Set Analysis Generator',
        'qlikSet.pageLead': 'Erzeugt Child Measures, Variablen und Import-CSV aus einer Base Measure und Dimension-Wert-Listen.',
        'qlikSet.workbench.title': 'Formel-Workbench',
        'qlikSet.workbench.description': 'Dimensionen findest du im App-Katalog und im Filterbereich. Blende Spalten aus, wenn du mehr Platz zum Bearbeiten brauchst.',
        'qlikSet.layout.catalog': 'Katalog',
        'qlikSet.layout.composer': 'Formel',
        'qlikSet.layout.builder': 'Filter & Baum',
        'qlikSet.layout.focusFormula': 'Fokus Formel',
        'qlikSet.layout.showAll': 'Alles anzeigen',
        'qlikSet.assets.title': 'App-Katalog',
        'qlikSet.assets.hint': 'Felder und Variablen anklicken oder per Drag and Drop verwenden.',
        'qlikSet.catalog.dimension': 'Dimensionen',
        'qlikSet.catalog.measure': 'Measures',
        'qlikSet.catalog.date': 'Datum / Zeit',
        'qlikSet.catalog.other': 'Weitere Felder',
        'qlikSet.formula.title': 'Formel',
        'qlikSet.formula.hint': 'Hier entsteht die Qlik-Expression. KPI-Bloecke ersetzen die Formel, Felder und Variablen werden an der Cursor-Position eingefuegt.',
        'qlikSet.formula.current': 'Aktuelle Formel mit erstem Filter',
        'qlikSet.history.undo': 'Zurück',
        'qlikSet.history.redo': 'Vor',
        'qlikSet.palette.title': 'Bausteine',
        'qlikSet.palette.hint': 'Baustein wählen, um die Formel zu erweitern oder einen KPI-Modus zu setzen.',
        'qlikSet.palette.show': 'Bausteine anzeigen',
        'qlikSet.palette.hide': 'Bausteine ausblenden',
        'qlikSet.functions.title': 'Formel-Funktionen',
        'qlikSet.filter.title': 'Set-Filter bauen',
        'qlikSet.filter.hint': 'Die Dimension kommt rechts in diese Box. Danach Wert eintragen und Filter hinzufügen.',
        'qlikSet.filter.drop': 'Dimension hier ablegen',
        'qlikSet.filter.dropTitle': 'Dimension hier ablegen',
        'qlikSet.filter.dropText': 'Ziehe z.B. Region aus dem App-Katalog in diese Box. Danach unten DACH, Online usw. als Wert setzen.',
        'qlikSet.tabs.filter': 'Filter',
        'qlikSet.tabs.hierarchy': 'Hierarchie',
        'qlikSet.tabs.extras': 'Extras',
        'qlikSet.kpis.title': 'KPI-Bloecke',
        'qlikSet.kpis.hint': 'KPI-Bloecke sind ein Modus: ein aktiver KPI wird ersetzt, nicht weiter verschachtelt. Der gleiche KPI ist gesperrt, bis du zurückgehst oder die Base Measure änderst.',
        'qlikSet.kpis.none': 'Kein KPI aktiv',
        'qlikSet.kpis.active': 'Aktiver KPI',
        'qlikSet.kpis.current': 'Current',
        'qlikSet.kpis.cy': 'Current Year',
        'qlikSet.kpis.py': 'Previous Year',
        'qlikSet.kpis.ytd': 'YTD',
        'qlikSet.kpis.mtd': 'MTD',
        'qlikSet.kpis.last12m': 'Last 12M',
        'qlikSet.kpis.yoy': 'YoY Delta',
        'qlikSet.kpis.yoyPct': 'YoY %',
        'qlikSet.hierarchy.title': 'Hierarchie bauen',
        'qlikSet.hierarchy.hint': 'Ziehe Dimensionen aus dem App-Katalog hierher. Sie werden unten an den Baum angehaengt und koennen danach im Baum umgehaengt werden.',
        'qlikSet.hierarchy.dropTitle': 'Dimension in Hierarchie ziehen',
        'qlikSet.hierarchy.dropText': 'Drop fuegt sie unten an. Fuer eine genaue Position direkt auf einen Slot im Baum ziehen.',
        'qlikSet.setVars.title': 'Set-Variable bauen',
        'qlikSet.setVars.hint': 'Erstellt eine Variable fuer Mehrfachselektionen und setzt sie direkt in die Set Analysis Formel ein.',
        'qlikSet.setVars.name': 'Set-Variablenname',
        'qlikSet.setVars.values': 'Mehrfachwerte',
        'qlikSet.setVars.add': 'Set-Variable hinzufügen',
        'qlikSet.setSearch.title': 'Formel im Set nutzen',
        'qlikSet.setSearch.hint': 'Erzeugt Such-Set-Analysis wie Customer={"=Sum(Sales)>1000"} aus der gewaehlten Dimension.',
        'qlikSet.setSearch.expression': 'Set-Suchformel',
        'qlikSet.setSearch.add': 'Formel als Set-Filter hinzufügen',
        'qlikSet.tree.title': 'Measure-Child-Baum',
        'qlikSet.tree.hint': 'Dimensionen im Baum greifen und auf einen Slot ziehen, um sie umzuhaengen. Neue Dimensionen koennen direkt aus dem Katalog auf einen Slot gezogen werden.',
        'qlikSet.tree.currentDimension': 'Aktuelle Dimension',
        'qlikSet.tree.base': 'Base Measure',
        'qlikSet.tree.insertBetween': 'Zwischen {before} und {after} einfuegen',
        'qlikSet.tree.insertUnder': 'Unter {level} einfuegen',
        'qlikSet.tree.moveUp': 'Hoch',
        'qlikSet.tree.moveDown': 'Runter',
        'qlikSet.tree.remove': 'Entfernen',
        'qlikSet.help.title': 'Qlik Set Analysis Hilfe',
        'qlikSet.help.lead': 'Kurze Anleitung, Import-Hinweise und Master-Item-Schritte. Einklappen, wenn du nur bauen willst.',
        'qlikSet.help.show': 'Hilfe anzeigen',
        'qlikSet.help.hide': 'Hilfe ausblenden',
        'qlikSet.howto.summary': 'Hilfe',
        'qlikSet.howto.intro': 'Nutze den Generator, um aus einer Measure wie Sum(Sales) gefilterte Qlik-Expressions zu erzeugen.',
        'qlikSet.howto.step1': 'Base Measure, Measure-Name und optionalen Variablen-Prefix setzen.',
        'qlikSet.howto.step2': 'Dimensionen und Werte als CSV einfuegen oder eine CSV-Datei hochladen.',
        'qlikSet.howto.step3': 'Child Measures, Variablen oder CSV-Ausgabe kopieren und in Qlik Sense anlegen.',
        'qlikSet.howto.tip': 'Die Ausgabe ist ein Startpunkt. Feldnamen, Quotes, Master-Measure-Konventionen und Security-Regeln bitte final in der App pruefen.',
        'qlikSet.export.summary': 'Dimensionen aus Qlik exportieren',
        'qlikSet.export.intro': 'Schneller Weg ohne API: erstelle in Qlik eine Tabelle, exportiere sie als CSV/XLSX und speichere sie als CSV mit den Spalten dimension,value,label.',
        'qlikSet.export.step1': 'Lege ein temporäres Sheet an und erstelle eine Tabelle mit den relevanten Dimensionsfeldern.',
        'qlikSet.export.step2': 'Benenne die Spalten fuer den Export eindeutig, zum Beispiel dimension, value und label.',
        'qlikSet.export.step3': 'Exportiere die Tabelle aus Qlik als Datenexport und speichere sie als CSV.',
        'qlikSet.export.step4': 'Lade die CSV hier hoch oder kopiere die Zeilen in das Textfeld.',
        'qlikSet.masterItems.summary': 'Master Items und Variablen in Qlik anlegen',
        'qlikSet.masterItems.intro': 'Empfohlener Ablauf: erst Variablen anlegen, dann eine Base Master Measure, danach die generierten Child Measures als Master Measures speichern.',
        'qlikSet.masterItems.step1': 'App im Bearbeitungsmodus öffnen. Variablen können in der Variablenübersicht oder im Ladescript angelegt werden.',
        'qlikSet.masterItems.step2': 'Zeitvariablen aus der Ausgabe kopieren. Script-Variablen über den Data Load Editor anlegen; UI-Variablen über die Variablenübersicht anlegen.',
        'qlikSet.masterItems.step3': 'Base Measure als Master Measure anlegen, z.B. Sales = Sum(Sales). Beschreibung, Tags und Zahlenformat ergänzen.',
        'qlikSet.masterItems.step4': 'Child Measures aus der Ausgabe als weitere Master Measures anlegen. Namen, Beschreibung und Filterlogik dokumentieren.',
        'qlikSet.masterItems.step5': 'In einer Test-Tabelle je Child Measure gegen eine manuelle Selektion prüfen, bevor die Measures in produktive Sheets wandern.',
        'qlikSet.masterItems.tip': 'Wichtig: Variablen mit $(vName) werden per Dollar-Sign Expansion vor der Auswertung ersetzt. Variablen mit führendem = können anders aggregieren als reine Ausdrucksvariablen.',
        'qlikSet.useCases.summary': 'Typische Fälle und Stolperstellen',
        'qlikSet.useCases.intro': 'Diese Fälle deckt der Generator ab:',
        'qlikSet.useCases.case1': 'Segment-Measures: Sales für Region, Channel, Brand, Product Group oder Customer Type.',
        'qlikSet.useCases.case2': 'Kombinierte Filter: Sales für Region + Channel oder Markt + Produktgruppe.',
        'qlikSet.useCases.case3': 'Zeitvergleiche: Current Year, Previous Year, YTD, MTD und Last 12 Months über Standardvariablen.',
        'qlikSet.useCases.case4': 'Ausschlusslogik: Werte per -= aus dem aktuellen Kontext ausschließen.',
        'qlikSet.useCases.case5': 'Suchlogik: dynamische Search Strings wie {"=Sum(Sales)>0"} vorbereiten.',
        'qlikSet.useCases.case6': 'Migration von If-Logik: Nested If und Pick/Match als Vergleichsausgabe nutzen, Set Analysis als Zielausdruck prüfen.',
        'qlikSet.input.title': 'Set-Analysis-Eingaben',
        'qlikSet.input.description': 'Die Eingaben erzeugen gefilterte Measure-Varianten und optionale Variablen.',
        'qlikSet.input.measureName': 'Measure-Name',
        'qlikSet.input.baseDescription': 'Base-Beschreibung',
        'qlikSet.input.baseMeasure': 'Base Measure',
        'qlikSet.input.variablePrefix': 'Variablen-Prefix',
        'qlikSet.input.mode': 'Generator-Modus',
        'qlikSet.input.setIdentifier': 'Set Identifier',
        'qlikSet.input.assignment': 'Assignment Operator',
        'qlikSet.input.expressionStyle': 'Expression-Stil',
        'qlikSet.input.valueMode': 'Wert-/Suchmodus',
        'qlikSet.input.useVariables': 'Variablen nutzen',
        'qlikSet.input.csvUpload': 'CSV hochladen',
        'qlikSet.input.dateField': 'Datumsfeld',
        'qlikSet.input.yearField': 'Jahresfeld',
        'qlikSet.input.rows': 'Dimension/Wert-Liste',
        'qlikSet.input.advanced': 'Feinoptionen und CSV',
        'qlikSet.catalog.title': 'App-Felder und Variablen',
        'qlikSet.catalog.description': 'Importiere Feldlisten und Variablen aus deiner App oder pflege sie hier manuell. Die Listen fuellen die Eingabehilfen und die generierten Scripts.',
        'qlikSet.catalog.fieldsUpload': 'Feldliste hochladen',
        'qlikSet.catalog.variableUpload': 'Variablenliste hochladen',
        'qlikSet.catalog.fields': 'Felder aus der App',
        'qlikSet.catalog.variables': 'Variablen',
        'qlikSet.catalog.rawData': 'Importdaten bearbeiten',
        'qlikSet.catalog.rawDataHint': 'Bearbeite Feld- und Variablenlisten direkt als CSV. Die Chips im App-Katalog aktualisieren sich sofort.',
        'qlikSet.modal.close': 'Schließen',
        'qlikSet.fields.summary': 'Felder importieren',
        'qlikSet.composer.aggregation': 'Aggregation',
        'qlikSet.composer.measureField': 'Measure-Feld',
        'qlikSet.composer.variable': 'Variable als Base Measure',
        'qlikSet.composer.apply': 'Base Measure setzen',
        'qlikSet.composer.useVariable': 'Variable einsetzen',
        'qlikSet.builder.addRow': 'Dimension/Wert hinzufügen',
        'qlikSet.builder.addVariable': 'Variable hinzufügen',
        'qlikSet.builder.dimension': 'Dimension',
        'qlikSet.builder.value': 'Wert',
        'qlikSet.builder.label': 'Label',
        'qlikSet.output.measures': 'Child Measures',
        'qlikSet.output.variables': 'Qlik Variablen-Script',
        'qlikSet.output.hierarchy': 'Hierarchie / Drill-down Vorlage',
        'qlikSet.output.timeVariables': 'Standard-Zeitvariablen',
        'qlikSet.output.modifiers': 'Set Modifier Bibliothek',
        'qlikSet.output.nestedIf': 'Nested If Alternative',
        'qlikSet.output.pickMatch': 'Pick/Match Alternative',
        'qlikSet.output.csv': 'Measure Import CSV',
        'qlikSet.copy': 'Kopieren',
        'shared.copied': 'Kopiert!',
    },
    en: {
        'qlikSet.pageTitle': 'Qlik Set Analysis Generator',
        'qlikSet.pageLead': 'Generates child measures, variables, and import CSV from a base measure and dimension value lists.',
        'qlikSet.workbench.title': 'Formula workbench',
        'qlikSet.workbench.description': 'Dimensions are in the app catalog and filter area. Hide columns when you need more editing space.',
        'qlikSet.layout.catalog': 'Catalog',
        'qlikSet.layout.composer': 'Formula',
        'qlikSet.layout.builder': 'Filters & tree',
        'qlikSet.layout.focusFormula': 'Focus formula',
        'qlikSet.layout.showAll': 'Show all',
        'qlikSet.assets.title': 'App catalog',
        'qlikSet.assets.hint': 'Click fields and variables or use drag and drop.',
        'qlikSet.catalog.dimension': 'Dimensions',
        'qlikSet.catalog.measure': 'Measures',
        'qlikSet.catalog.date': 'Date / time',
        'qlikSet.catalog.other': 'Other fields',
        'qlikSet.formula.title': 'Formula',
        'qlikSet.formula.hint': 'This is where the Qlik expression is built. KPI blocks replace the formula; fields and variables are inserted at the cursor.',
        'qlikSet.formula.current': 'Current formula with first filter',
        'qlikSet.history.undo': 'Undo',
        'qlikSet.history.redo': 'Redo',
        'qlikSet.palette.title': 'Building blocks',
        'qlikSet.palette.hint': 'Choose a block to extend the formula or set a KPI mode.',
        'qlikSet.palette.show': 'Show blocks',
        'qlikSet.palette.hide': 'Hide blocks',
        'qlikSet.functions.title': 'Formula functions',
        'qlikSet.filter.title': 'Build set filters',
        'qlikSet.filter.hint': 'Drop the dimension into this box on the right. Then enter the value and add the filter.',
        'qlikSet.filter.drop': 'Drop dimension here',
        'qlikSet.filter.dropTitle': 'Drop dimension here',
        'qlikSet.filter.dropText': 'Drag Region from the app catalog into this box. Then enter DACH, Online, etc. as the value below.',
        'qlikSet.tabs.filter': 'Filters',
        'qlikSet.tabs.hierarchy': 'Hierarchy',
        'qlikSet.tabs.extras': 'Extras',
        'qlikSet.kpis.title': 'KPI blocks',
        'qlikSet.kpis.hint': 'KPI blocks behave like a mode: an active KPI is replaced, not nested again. The same KPI is locked until you undo or change the base measure.',
        'qlikSet.kpis.none': 'No active KPI',
        'qlikSet.kpis.active': 'Active KPI',
        'qlikSet.kpis.current': 'Current',
        'qlikSet.kpis.cy': 'Current year',
        'qlikSet.kpis.py': 'Previous year',
        'qlikSet.kpis.ytd': 'YTD',
        'qlikSet.kpis.mtd': 'MTD',
        'qlikSet.kpis.last12m': 'Last 12M',
        'qlikSet.kpis.yoy': 'YoY delta',
        'qlikSet.kpis.yoyPct': 'YoY %',
        'qlikSet.hierarchy.title': 'Build hierarchy',
        'qlikSet.hierarchy.hint': 'Drag dimensions from the app catalog here. They are appended to the tree and can be rearranged inside the tree.',
        'qlikSet.hierarchy.dropTitle': 'Drag dimension into hierarchy',
        'qlikSet.hierarchy.dropText': 'Drop appends it. For exact placement, drag directly onto a tree slot.',
        'qlikSet.setVars.title': 'Build set variable',
        'qlikSet.setVars.hint': 'Creates a variable for multiple selections and inserts it into the set analysis expression.',
        'qlikSet.setVars.name': 'Set variable name',
        'qlikSet.setVars.values': 'Multiple values',
        'qlikSet.setVars.add': 'Add set variable',
        'qlikSet.setSearch.title': 'Use formula in set analysis',
        'qlikSet.setSearch.hint': 'Creates search set analysis such as Customer={"=Sum(Sales)>1000"} from the selected dimension.',
        'qlikSet.setSearch.expression': 'Set search formula',
        'qlikSet.setSearch.add': 'Add formula as set filter',
        'qlikSet.tree.title': 'Measure child tree',
        'qlikSet.tree.hint': 'Grab dimensions in the tree and drop them onto a slot to rearrange them. New dimensions can be dragged from the catalog onto any slot.',
        'qlikSet.tree.currentDimension': 'Current dimension',
        'qlikSet.tree.base': 'Base measure',
        'qlikSet.tree.insertBetween': 'Insert between {before} and {after}',
        'qlikSet.tree.insertUnder': 'Insert under {level}',
        'qlikSet.tree.moveUp': 'Up',
        'qlikSet.tree.moveDown': 'Down',
        'qlikSet.tree.remove': 'Remove',
        'qlikSet.help.title': 'Qlik Set Analysis help',
        'qlikSet.help.lead': 'Quick guidance, import notes, and master item steps. Collapse it when you only want to build.',
        'qlikSet.help.show': 'Show help',
        'qlikSet.help.hide': 'Hide help',
        'qlikSet.howto.summary': 'Help',
        'qlikSet.howto.intro': 'Use the generator to turn a measure such as Sum(Sales) into filtered Qlik expressions.',
        'qlikSet.howto.step1': 'Set the base measure, measure name, and optional variable prefix.',
        'qlikSet.howto.step2': 'Paste dimension values as CSV or upload a CSV file.',
        'qlikSet.howto.step3': 'Copy child measures, variables, or CSV output and create them in Qlik Sense.',
        'qlikSet.howto.tip': 'The output is a starting point. Review field names, quotes, master measure conventions, and security rules in the app.',
        'qlikSet.export.summary': 'Export dimensions from Qlik',
        'qlikSet.export.intro': 'Quick route without an API: create a table in Qlik, export it as CSV/XLSX, and save it as CSV with dimension,value,label columns.',
        'qlikSet.export.step1': 'Create a temporary sheet and add a table with the relevant dimension fields.',
        'qlikSet.export.step2': 'Name the export columns clearly, for example dimension, value, and label.',
        'qlikSet.export.step3': 'Export the table from Qlik as a data export and save it as CSV.',
        'qlikSet.export.step4': 'Upload the CSV here or paste the rows into the text area.',
        'qlikSet.masterItems.summary': 'Create master items and variables in Qlik',
        'qlikSet.masterItems.intro': 'Recommended flow: create variables first, then one base master measure, then save the generated child measures as master measures.',
        'qlikSet.masterItems.step1': 'Open the app in edit mode. Variables can be created in the variables overview or in the load script.',
        'qlikSet.masterItems.step2': 'Copy the time variables output. Create script variables in the Data load editor; create UI variables in the variables overview.',
        'qlikSet.masterItems.step3': 'Create the base measure as a master measure, for example Sales = Sum(Sales). Add description, tags, and number formatting.',
        'qlikSet.masterItems.step4': 'Create the generated child measures as additional master measures. Document name, description, and filter logic.',
        'qlikSet.masterItems.step5': 'Validate every child measure in a test table against a manual selection before using it in production sheets.',
        'qlikSet.masterItems.tip': 'Important: variables called with $(vName) are expanded before evaluation. Variables starting with = can aggregate differently from plain expression variables.',
        'qlikSet.useCases.summary': 'Typical cases and pitfalls',
        'qlikSet.useCases.intro': 'The generator covers these cases:',
        'qlikSet.useCases.case1': 'Segment measures: Sales for region, channel, brand, product group, or customer type.',
        'qlikSet.useCases.case2': 'Combined filters: Sales for region + channel or market + product group.',
        'qlikSet.useCases.case3': 'Time comparisons: current year, previous year, YTD, MTD, and last 12 months via standard variables.',
        'qlikSet.useCases.case4': 'Exclusion logic: exclude values from the current context with -=.',
        'qlikSet.useCases.case5': 'Search logic: prepare dynamic search strings such as {"=Sum(Sales)>0"}.',
        'qlikSet.useCases.case6': 'Migrating If logic: use Nested If and Pick/Match as comparison outputs, then validate set analysis as the target expression.',
        'qlikSet.input.title': 'Set analysis inputs',
        'qlikSet.input.description': 'These inputs generate filtered measure variants and optional variables.',
        'qlikSet.input.measureName': 'Measure name',
        'qlikSet.input.baseDescription': 'Base description',
        'qlikSet.input.baseMeasure': 'Base measure',
        'qlikSet.input.variablePrefix': 'Variable prefix',
        'qlikSet.input.mode': 'Generator mode',
        'qlikSet.input.setIdentifier': 'Set identifier',
        'qlikSet.input.assignment': 'Assignment operator',
        'qlikSet.input.expressionStyle': 'Expression style',
        'qlikSet.input.valueMode': 'Value/search mode',
        'qlikSet.input.useVariables': 'Use variables',
        'qlikSet.input.csvUpload': 'Upload CSV',
        'qlikSet.input.dateField': 'Date field',
        'qlikSet.input.yearField': 'Year field',
        'qlikSet.input.rows': 'Dimension/value list',
        'qlikSet.input.advanced': 'Fine options and CSV',
        'qlikSet.catalog.title': 'App fields and variables',
        'qlikSet.catalog.description': 'Import field lists and variables from your app or maintain them here. The lists power the input helpers and generated scripts.',
        'qlikSet.catalog.fieldsUpload': 'Upload field list',
        'qlikSet.catalog.variableUpload': 'Upload variable list',
        'qlikSet.catalog.fields': 'Fields from the app',
        'qlikSet.catalog.variables': 'Variables',
        'qlikSet.catalog.rawData': 'Edit import data',
        'qlikSet.catalog.rawDataHint': 'Edit field and variable lists directly as CSV. The app catalog chips update immediately.',
        'qlikSet.modal.close': 'Close',
        'qlikSet.fields.summary': 'Import fields',
        'qlikSet.composer.aggregation': 'Aggregation',
        'qlikSet.composer.measureField': 'Measure field',
        'qlikSet.composer.variable': 'Variable as base measure',
        'qlikSet.composer.apply': 'Set base measure',
        'qlikSet.composer.useVariable': 'Use variable',
        'qlikSet.builder.addRow': 'Add dimension/value',
        'qlikSet.builder.addVariable': 'Add variable',
        'qlikSet.builder.dimension': 'Dimension',
        'qlikSet.builder.value': 'Value',
        'qlikSet.builder.label': 'Label',
        'qlikSet.output.measures': 'Child measures',
        'qlikSet.output.variables': 'Qlik variable script',
        'qlikSet.output.hierarchy': 'Hierarchy / drill-down template',
        'qlikSet.output.timeVariables': 'Standard time variables',
        'qlikSet.output.modifiers': 'Set modifier library',
        'qlikSet.output.nestedIf': 'Nested If alternative',
        'qlikSet.output.pickMatch': 'Pick/Match alternative',
        'qlikSet.output.csv': 'Measure import CSV',
        'qlikSet.copy': 'Copy',
        'shared.copied': 'Copied!',
    },
};

export function t(locale, key) {
    return labels[locale]?.[key] ?? labels.en[key] ?? key;
}

export function applyQlikSetLabels() {
    const locale = getLocale();
    document.querySelectorAll('[data-i18n]').forEach((el) => {
        const key = el.getAttribute('data-i18n');
        if (!key?.startsWith('qlikSet.') && !key?.startsWith('shared.')) return;
        el.textContent = t(locale, key);
    });
}
