export const labels = {
    de: {
        'tableauCalc.pageTitle': 'Tableau Calculation Generator',
        'tableauCalc.pageLead': 'Erzeuge Tableau Calculated Fields, LOD-Varianten und Dokumentations-CSV aus Base Measures plus wiederverwendbaren Definitionen.',
        'tableauCalc.help.summary': 'Kurzlogik',
        'tableauCalc.help.step1': 'Katalog pflegen: Dimensionen, Measures und verfügbare Werte aus deiner Tableau Workbook-Struktur eintragen.',
        'tableauCalc.help.step2': 'Definitionen bauen: Eine Definition ist eine wiederverwendbare Bedingung wie Region DACH oder Current Year.',
        'tableauCalc.help.step3': 'Base Measures pflegen: Sales, Costs, Margin usw. bleiben reine Tableau-Ausdrücke.',
        'tableauCalc.help.step4': 'Ausgabe kopieren: In Tableau links im Data Pane per Rechtsklick oder Menü ein Calculated Field anlegen und Formel einfügen.',
        'tableauCalc.apps.save': 'App speichern',
        'tableauCalc.apps.load': 'App laden',
        'tableauCalc.catalog.title': 'App-Katalog',
        'tableauCalc.catalog.fields': 'Felder',
        'tableauCalc.catalog.values': 'Dim-Werte',
        'tableauCalc.catalog.hint': 'CSV-Rohdaten für Beispiele und Copy-Paste-Importe. Werte werden für Definitionen genutzt.',
        'tableauCalc.definitions.title': 'Definitionen',
        'tableauCalc.definitions.dimension': 'Dimension',
        'tableauCalc.definitions.values': 'Werte',
        'tableauCalc.definitions.name': 'Name',
        'tableauCalc.definitions.add': 'Definition speichern',
        'tableauCalc.definitions.raw': 'Definitionen CSV',
        'tableauCalc.definitions.preview': 'Vorschau',
        'tableauCalc.base.title': 'Base Measures',
        'tableauCalc.base.raw': 'Base Measures CSV',
        'tableauCalc.description.title': 'Beschreibung',
        'tableauCalc.description.de': 'Template DE',
        'tableauCalc.description.en': 'Template EN',
        'tableauCalc.output.calcs': 'Calculated Fields',
        'tableauCalc.output.lod': 'LOD',
        'tableauCalc.output.defs': 'Definitionen',
        'tableauCalc.output.csv': 'CSV',
        'tableauCalc.copy': 'Kopieren',
        'tableauCalc.downloadCsv': 'CSV laden',
        'tableauCalc.saved': 'Definition gespeichert.',
    },
    en: {
        'tableauCalc.pageTitle': 'Tableau Calculation Generator',
        'tableauCalc.pageLead': 'Generate Tableau calculated fields, LOD variants and documentation CSV from base measures plus reusable definitions.',
        'tableauCalc.help.summary': 'Quick logic',
        'tableauCalc.help.step1': 'Maintain the catalog: add dimensions, measures and available values from your Tableau workbook structure.',
        'tableauCalc.help.step2': 'Build definitions: a definition is a reusable condition such as Region DACH or Current Year.',
        'tableauCalc.help.step3': 'Maintain base measures: Sales, Costs, Margin etc. stay clean Tableau expressions.',
        'tableauCalc.help.step4': 'Copy output: in Tableau, create a calculated field from the Data pane and paste the formula.',
        'tableauCalc.apps.save': 'Save app',
        'tableauCalc.apps.load': 'Load app',
        'tableauCalc.catalog.title': 'App catalog',
        'tableauCalc.catalog.fields': 'Fields',
        'tableauCalc.catalog.values': 'Dim values',
        'tableauCalc.catalog.hint': 'CSV raw data for examples and copy-paste imports. Values are used for definitions.',
        'tableauCalc.definitions.title': 'Definitions',
        'tableauCalc.definitions.dimension': 'Dimension',
        'tableauCalc.definitions.values': 'Values',
        'tableauCalc.definitions.name': 'Name',
        'tableauCalc.definitions.add': 'Save definition',
        'tableauCalc.definitions.raw': 'Definitions CSV',
        'tableauCalc.definitions.preview': 'Preview',
        'tableauCalc.base.title': 'Base measures',
        'tableauCalc.base.raw': 'Base measures CSV',
        'tableauCalc.description.title': 'Description',
        'tableauCalc.description.de': 'Template DE',
        'tableauCalc.description.en': 'Template EN',
        'tableauCalc.output.calcs': 'Calculated Fields',
        'tableauCalc.output.lod': 'LOD',
        'tableauCalc.output.defs': 'Definitions',
        'tableauCalc.output.csv': 'CSV',
        'tableauCalc.copy': 'Copy',
        'tableauCalc.downloadCsv': 'Download CSV',
        'tableauCalc.saved': 'Definition saved.',
    },
};

export function t(key) {
    const locale = document.documentElement.lang === 'en' ? 'en' : 'de';

    return labels[locale][key] ?? labels.de[key] ?? key;
}
