import { getLocale } from '../../locale.js';

export const labels = {
    de: {
        'tableauCalc.pageTitle': 'Tableau Calculation Generator',
        'tableauCalc.pageLead': 'Erzeuge Tableau Calculated Fields, LOD-Varianten und Dokumentations-CSV aus Base Measures plus wiederverwendbaren Definitionen.',
        'tableauCalc.help.title': 'Tableau Calculation Hilfe',
        'tableauCalc.help.lead': 'Workflow-Hilfe für Katalog, Definitionen, Base Measures, Hierarchie und Calculated Fields.',
        'tableauCalc.help.show': 'Hilfe anzeigen',
        'tableauCalc.help.hide': 'Hilfe ausblenden',
        'tableauCalc.help.productLink': 'Tableau Produktseite',
        'tableauCalc.help.productHelpLink': 'Tableau Hilfe-Portal',
        'tableauCalc.help.calculatedFieldsLink': 'Calculated Fields Dokumentation',
        'tableauCalc.help.lodLink': 'LOD Expressions Dokumentation',
        'tableauCalc.help.summary': 'Kurzlogik',
        'tableauCalc.help.step1': 'Katalog pflegen: Dimensionen, Measures und verfügbare Werte aus deiner Tableau Workbook-Struktur eintragen.',
        'tableauCalc.help.step2': 'Definitionen bauen: Eine Definition ist eine wiederverwendbare Bedingung wie Region DACH oder Current Year.',
        'tableauCalc.help.step3': 'Base Measures pflegen: Sales, Costs, Margin usw. bleiben reine Tableau-Ausdrücke.',
        'tableauCalc.help.step4': 'Ausgabe kopieren: In Tableau links im Data Pane per Rechtsklick oder Menü ein Calculated Field anlegen und Formel einfügen.',
        'tableauCalc.help.catalogTitle': '1. Katalog',
        'tableauCalc.help.definitionsTitle': '2. Definition',
        'tableauCalc.help.baseTitle': '3. Base Measures',
        'tableauCalc.help.outputTitle': '4. Ausgabe',
        'tableauCalc.help.whereTitle': 'Wo in Tableau?',
        'tableauCalc.help.whereBody': 'Calculated Fields kommen in Tableau Desktop in ein neues berechnetes Feld. Hierarchien werden im Data Pane angelegt, indem du Felder in der gewünschten Reihenfolge zu einer Hierarchie ziehst.',
        'tableauCalc.apps.save': 'App speichern',
        'tableauCalc.apps.load': 'App laden',
        'tableauCalc.apps.delete': 'App löschen',
        'tableauCalc.apps.name': 'App-Name',
        'tableauCalc.apps.saved': 'Gespeicherte Apps',
        'tableauCalc.apps.none': 'Keine App gewählt',
        'tableauCalc.apps.missingName': 'Bitte einen App-Namen eingeben.',
        'tableauCalc.apps.missingSelection': 'Bitte eine gespeicherte App wählen.',
        'tableauCalc.apps.savedMessage': 'App „{name}“ gespeichert.',
        'tableauCalc.apps.deletedMessage': 'App „{name}“ gelöscht.',
        'tableauCalc.workbench.title': 'Formel-Workbench',
        'tableauCalc.workbench.description': 'Katalog, Base Measures und Definitionen sind getrennte Arbeitsbereiche. Die Ausgabe darunter bleibt separat kopier- und exportierbar.',
        'tableauCalc.workbench.controlTitle': 'Formel-Workbench',
        'tableauCalc.workbench.controlHint': 'App-Kontext, Katalog, Base-Formeln, Filter und Hierarchie bearbeiten.',
        'tableauCalc.workbench.hide': 'Workbench ausblenden',
        'tableauCalc.workbench.show': 'Workbench anzeigen',
        'tableauCalc.layout.catalog': 'Katalog',
        'tableauCalc.layout.formula': 'Formel',
        'tableauCalc.layout.builder': 'Filter & Baum',
        'tableauCalc.layout.focusFormula': 'Fokus Formel',
        'tableauCalc.layout.showAll': 'Alles anzeigen',
        'tableauCalc.tabs.definitions': 'Definitionen',
        'tableauCalc.tabs.hierarchy': 'Hierarchie',
        'tableauCalc.tabs.extras': 'Extras',
        'tableauCalc.catalog.title': 'App-Katalog',
        'tableauCalc.catalog.fields': 'Felder',
        'tableauCalc.catalog.values': 'Dim-Werte',
        'tableauCalc.catalog.rawData': 'Rohdaten bearbeiten',
        'tableauCalc.catalog.rawDataHint': 'Fields und Values als CSV pflegen oder Dateien hochladen.',
        'tableauCalc.catalog.fieldsUpload': 'Fields CSV laden',
        'tableauCalc.catalog.valuesUpload': 'Values CSV laden',
        'tableauCalc.catalog.tabs.dimensions': 'Dimensionen',
        'tableauCalc.catalog.tabs.measures': 'Measures',
        'tableauCalc.catalog.hint': 'Chips ziehen oder anklicken. Rohdaten öffnest du über den Button darunter.',
        'tableauCalc.modal.close': 'Schließen',
        'tableauCalc.definitions.title': 'Definitionen',
        'tableauCalc.definitions.hint': 'Dimension und Werte wählen, speichern und als wiederverwendbare Bedingung nutzen.',
        'tableauCalc.definitions.dimension': 'Dimension',
        'tableauCalc.definitions.values': 'Werte',
        'tableauCalc.definitions.name': 'Name',
        'tableauCalc.definitions.add': 'Definition speichern',
        'tableauCalc.definitions.raw': 'Definitionen CSV',
        'tableauCalc.definitions.preview': 'Vorschau',
        'tableauCalc.definitions.dropTitle': 'Dimension hier ablegen',
        'tableauCalc.definitions.dropHint': 'Ziehe eine Dimension aus dem Katalog hierher, um daraus eine Definition zu bauen.',
        'tableauCalc.definitions.remove': 'Entfernen',
        'tableauCalc.formula.title': 'Formel',
        'tableauCalc.formula.hint': 'Hier baust und bearbeitest du die aktive Tableau Base Measure. Bausteine und Felder werden an der Cursor-Position eingefügt.',
        'tableauCalc.formula.current': 'Aktuelle Formel',
        'tableauCalc.formula.name': 'Measure Name',
        'tableauCalc.formula.field': 'Feld',
        'tableauCalc.formula.apply': 'Base Measure setzen',
        'tableauCalc.history.undo': 'Rückgängig',
        'tableauCalc.history.redo': 'Wiederholen',
        'tableauCalc.functions.title': 'Formel-Funktionen',
        'tableauCalc.functions.hint': 'Baustein anklicken, um die Formel zu erweitern.',
        'tableauCalc.baseList.title': 'Base Measures',
        'tableauCalc.baseList.hint': 'Aktive Base laden, speichern oder neu anlegen.',
        'tableauCalc.baseList.show': 'Anzeigen',
        'tableauCalc.baseList.hide': 'Ausblenden',
        'tableauCalc.baseList.active': 'Aktive Base',
        'tableauCalc.baseList.load': 'Base laden',
        'tableauCalc.baseList.saveCurrent': 'Current speichern',
        'tableauCalc.baseList.newBase': 'Neue Base',
        'tableauCalc.baseList.csv': 'Base Measures CSV',
        'tableauCalc.baseList.rawHint': 'CSV bleibt die Quelle für gespeicherte Base Measures.',
        'tableauCalc.description.title': 'Beschreibung',
        'tableauCalc.description.hint': 'Beschreibungstemplates werden für die generierten Tableau Calculated Fields genutzt.',
        'tableauCalc.description.de': 'Template DE',
        'tableauCalc.description.en': 'Template EN',
        'tableauCalc.extras.title': 'Extras',
        'tableauCalc.extras.hint': 'Generierungsmodus und LOD-Dimensionen für Fallback aus Values.',
        'tableauCalc.extras.mode': 'Generierungsmodus',
        'tableauCalc.extras.modeSingle': 'Ein Child pro Dimensionswert',
        'tableauCalc.extras.modeCombined': 'Dimensionen zu Varianten kombinieren',
        'tableauCalc.extras.modeDimensionGroup': 'Ein Child pro Dimension mit allen Werten',
        'tableauCalc.extras.lodDimensions': 'LOD FIXED Dimensionen',
        'tableauCalc.extras.lodHint': 'Kommagetrennt. Leer = Dimensions der jeweiligen Definition.',
        'tableauCalc.output.calcs': 'Calculated Fields',
        'tableauCalc.output.lod': 'LOD',
        'tableauCalc.output.hierarchy': 'Hierarchie',
        'tableauCalc.output.defs': 'Definitionen',
        'tableauCalc.output.csv': 'CSV',
        'tableauCalc.copy': 'Kopieren',
        'tableauCalc.downloadCsv': 'CSV laden',
        'tableauCalc.downloadXlsx': 'Excel laden',
        'tableauCalc.saved': 'Definition gespeichert.',
        'tableauCalc.hierarchy.title': 'Hierarchie',
        'tableauCalc.hierarchy.hint': 'Dimensionen ablegen oder eingerückte Ebenen pflegen. Der Child-Baum zeigt die Base Measure als Wurzel.',
        'tableauCalc.hierarchy.dropTitle': 'Hierarchie-Ebene hier ablegen',
        'tableauCalc.hierarchy.dropHint': 'Ziehe Dimensionen hierher. Sie werden an die Hierarchie angehängt.',
        'tableauCalc.tree.title': 'Measure-Child-Baum',
        'tableauCalc.tree.hint': 'Dimensionen auf die Base oder einen Knoten legen, um verschachtelte Pfade zu bauen.',
        'tableauCalc.tree.base': 'Base Measure',
        'tableauCalc.tree.dropOnBase': 'Dimension auf erster Ebene ablegen',
        'tableauCalc.tree.dropOnNode': 'Unter {level} ablegen',
        'tableauCalc.tree.remove': 'Entfernen',
    },
    en: {
        'tableauCalc.pageTitle': 'Tableau Calculation Generator',
        'tableauCalc.pageLead': 'Generate Tableau calculated fields, LOD variants and documentation CSV from base measures plus reusable definitions.',
        'tableauCalc.help.title': 'Tableau Calculation help',
        'tableauCalc.help.lead': 'Workflow help for catalog, definitions, base measures, hierarchy, and calculated fields.',
        'tableauCalc.help.show': 'Show help',
        'tableauCalc.help.hide': 'Hide help',
        'tableauCalc.help.productLink': 'Tableau product page',
        'tableauCalc.help.productHelpLink': 'Tableau help portal',
        'tableauCalc.help.calculatedFieldsLink': 'Calculated fields documentation',
        'tableauCalc.help.lodLink': 'LOD expressions documentation',
        'tableauCalc.help.summary': 'Quick logic',
        'tableauCalc.help.step1': 'Maintain the catalog: add dimensions, measures and available values from your Tableau workbook structure.',
        'tableauCalc.help.step2': 'Build definitions: a definition is a reusable condition such as Region DACH or Current Year.',
        'tableauCalc.help.step3': 'Maintain base measures: Sales, Costs, Margin etc. stay clean Tableau expressions.',
        'tableauCalc.help.step4': 'Copy output: in Tableau, create a calculated field from the Data pane and paste the formula.',
        'tableauCalc.help.catalogTitle': '1. Catalog',
        'tableauCalc.help.definitionsTitle': '2. Definition',
        'tableauCalc.help.baseTitle': '3. Base measures',
        'tableauCalc.help.outputTitle': '4. Output',
        'tableauCalc.help.whereTitle': 'Where in Tableau?',
        'tableauCalc.help.whereBody': 'Calculated fields go into a new calculated field in Tableau Desktop. Hierarchies are created in the Data pane by placing fields into a hierarchy in the desired order.',
        'tableauCalc.apps.save': 'Save app',
        'tableauCalc.apps.load': 'Load app',
        'tableauCalc.apps.delete': 'Delete app',
        'tableauCalc.apps.name': 'App name',
        'tableauCalc.apps.saved': 'Saved apps',
        'tableauCalc.apps.none': 'No app selected',
        'tableauCalc.apps.missingName': 'Please enter an app name.',
        'tableauCalc.apps.missingSelection': 'Please select a saved app.',
        'tableauCalc.apps.savedMessage': 'App “{name}” saved.',
        'tableauCalc.apps.deletedMessage': 'App “{name}” deleted.',
        'tableauCalc.workbench.title': 'Formula workbench',
        'tableauCalc.workbench.description': 'Catalog, base measures and definitions are separate work areas. The output below stays separate for copy and export.',
        'tableauCalc.workbench.controlTitle': 'Formula workbench',
        'tableauCalc.workbench.controlHint': 'Edit app context, catalog, base formulas, filters and hierarchy.',
        'tableauCalc.workbench.hide': 'Hide workbench',
        'tableauCalc.workbench.show': 'Show workbench',
        'tableauCalc.layout.catalog': 'Catalog',
        'tableauCalc.layout.formula': 'Formula',
        'tableauCalc.layout.builder': 'Filter & tree',
        'tableauCalc.layout.focusFormula': 'Focus formula',
        'tableauCalc.layout.showAll': 'Show all',
        'tableauCalc.tabs.definitions': 'Definitions',
        'tableauCalc.tabs.hierarchy': 'Hierarchy',
        'tableauCalc.tabs.extras': 'Extras',
        'tableauCalc.catalog.title': 'App catalog',
        'tableauCalc.catalog.fields': 'Fields',
        'tableauCalc.catalog.values': 'Dim values',
        'tableauCalc.catalog.rawData': 'Edit raw data',
        'tableauCalc.catalog.rawDataHint': 'Maintain fields and values as CSV or upload files.',
        'tableauCalc.catalog.fieldsUpload': 'Upload fields CSV',
        'tableauCalc.catalog.valuesUpload': 'Upload values CSV',
        'tableauCalc.catalog.tabs.dimensions': 'Dimensions',
        'tableauCalc.catalog.tabs.measures': 'Measures',
        'tableauCalc.catalog.hint': 'Drag or click chips. Open raw data with the button below.',
        'tableauCalc.modal.close': 'Close',
        'tableauCalc.definitions.title': 'Definitions',
        'tableauCalc.definitions.hint': 'Pick a dimension and values, save, and reuse as a condition.',
        'tableauCalc.definitions.dimension': 'Dimension',
        'tableauCalc.definitions.values': 'Values',
        'tableauCalc.definitions.name': 'Name',
        'tableauCalc.definitions.add': 'Save definition',
        'tableauCalc.definitions.raw': 'Definitions CSV',
        'tableauCalc.definitions.preview': 'Preview',
        'tableauCalc.definitions.dropTitle': 'Drop dimension here',
        'tableauCalc.definitions.dropHint': 'Drag a dimension from the catalog here to build a definition.',
        'tableauCalc.definitions.remove': 'Remove',
        'tableauCalc.formula.title': 'Formula',
        'tableauCalc.formula.hint': 'Build and edit the active Tableau base measure here. Blocks and fields are inserted at the cursor position.',
        'tableauCalc.formula.current': 'Current formula',
        'tableauCalc.formula.name': 'Measure name',
        'tableauCalc.formula.field': 'Field',
        'tableauCalc.formula.apply': 'Set base measure',
        'tableauCalc.history.undo': 'Undo',
        'tableauCalc.history.redo': 'Redo',
        'tableauCalc.functions.title': 'Formula functions',
        'tableauCalc.functions.hint': 'Click a block to extend the formula.',
        'tableauCalc.baseList.title': 'Base measures',
        'tableauCalc.baseList.hint': 'Load, save or create the active base measure.',
        'tableauCalc.baseList.show': 'Show',
        'tableauCalc.baseList.hide': 'Hide',
        'tableauCalc.baseList.active': 'Active base',
        'tableauCalc.baseList.load': 'Load base',
        'tableauCalc.baseList.saveCurrent': 'Save current',
        'tableauCalc.baseList.newBase': 'New base',
        'tableauCalc.baseList.csv': 'Base measures CSV',
        'tableauCalc.baseList.rawHint': 'CSV remains the source for saved base measures.',
        'tableauCalc.description.title': 'Description',
        'tableauCalc.description.hint': 'Description templates are used for the generated Tableau calculated fields.',
        'tableauCalc.description.de': 'Template DE',
        'tableauCalc.description.en': 'Template EN',
        'tableauCalc.extras.title': 'Extras',
        'tableauCalc.extras.hint': 'Generation mode and LOD dimensions for fallback from values.',
        'tableauCalc.extras.mode': 'Generation mode',
        'tableauCalc.extras.modeSingle': 'One child per dimension value',
        'tableauCalc.extras.modeCombined': 'Combine dimensions into variants',
        'tableauCalc.extras.modeDimensionGroup': 'One child per dimension with all values',
        'tableauCalc.extras.lodDimensions': 'LOD FIXED dimensions',
        'tableauCalc.extras.lodHint': 'Comma-separated. Empty uses each definition’s dimensions.',
        'tableauCalc.output.calcs': 'Calculated Fields',
        'tableauCalc.output.lod': 'LOD',
        'tableauCalc.output.hierarchy': 'Hierarchy',
        'tableauCalc.output.defs': 'Definitions',
        'tableauCalc.output.csv': 'CSV',
        'tableauCalc.copy': 'Copy',
        'tableauCalc.downloadCsv': 'Download CSV',
        'tableauCalc.downloadXlsx': 'Download Excel',
        'tableauCalc.saved': 'Definition saved.',
        'tableauCalc.hierarchy.title': 'Hierarchy',
        'tableauCalc.hierarchy.hint': 'Drop dimensions or edit indented levels. The child tree shows the base measure as root.',
        'tableauCalc.hierarchy.dropTitle': 'Drop hierarchy level here',
        'tableauCalc.hierarchy.dropHint': 'Drag dimensions here. They are appended to the hierarchy.',
        'tableauCalc.tree.title': 'Measure child tree',
        'tableauCalc.tree.hint': 'Drop dimensions on the base or a node to build nested paths.',
        'tableauCalc.tree.base': 'Base measure',
        'tableauCalc.tree.dropOnBase': 'Drop dimension on first level',
        'tableauCalc.tree.dropOnNode': 'Drop under {level}',
        'tableauCalc.tree.remove': 'Remove',
    },
};

export function t(key) {
    const locale = getLocale() === 'en' ? 'en' : 'de';

    return labels[locale][key] ?? labels.de[key] ?? key;
}
