<?php

namespace Tests\Feature\Governance;

use Tests\TestCase;

class GovernanceHubTest extends TestCase
{
    public function test_governance_hub_connects_existing_hubs_and_tools(): void
    {
        $response = $this->get('/governance');

        $response->assertOk();
        $response->assertSee('Governance Hub');
        $response->assertSee('governance-hub', false);
        $response->assertSee('Governance control hub');
        $response->assertSee('data-governance-advisor', false);
        $response->assertSee('data-governance-advisor-config', false);
        $response->assertSee('data-governance-top-controls', false);
        $response->assertSee('data-governance-drawer-toggle', false);
        $response->assertSee('governance-hub__panel-tabs', false);
        $response->assertSee('governance-hub__panel-tab--active', false);
        $response->assertSee('data-governance-panel-toggle="governance-help-panel"', false);
        $response->assertSee('data-governance-panel-toggle="governance-tools-panel"', false);
        $response->assertSee('data-governance-panel-toggle="governance-save-panel"', false);
        $response->assertSee('Workspace Report', false);
        $response->assertSee('Governance Radar', false);
        $response->assertSee('/governance/radar', false);
        $response->assertSee('data-governance-tabs', false);
        $response->assertSee('data-governance-tab-toggle="advisor"', false);
        $response->assertSee('data-governance-tab-toggle="workflows"', false);
        $response->assertSee('data-governance-tab-toggle="decisions"', false);
        $response->assertSee('data-governance-tab-toggle="tools"', false);
        $response->assertSee('role="tablist"', false);
        $response->assertSee('role="tab"', false);
        $response->assertSee('role="tabpanel"', false);
        $response->assertSee('data-governance-tab-panel="advisor"', false);
        $response->assertSee('data-governance-tab-panel="workflows"', false);
        $response->assertSee('data-governance-tab-panel="decisions"', false);
        $response->assertSee('data-governance-tab-panel="tools"', false);
        $response->assertSee('Interactive decision aid');
        $response->assertSee('Ich baue neu auf', false);
        $response->assertSee('Ich ergänze Bestehendes', false);
        $response->assertSee('Alles ist da, ich brauche Hilfe', false);
        $response->assertSee('Source type');
        $response->assertSee('Target stack');
        $response->assertSee('Next question');
        $response->assertSee('Refine DQ decision');
        $response->assertSee('DQ goal');
        $response->assertSee('Issue class');
        $response->assertSee('governance-advisor__helpbox', false);
        $response->assertDontSee('<details class="governance-advisor__helpbox" open>', false);
        $response->assertSee('So nutzt du den Advisor', false);
        $response->assertSee('Der Governance Hub ist keine Linkliste', false);
        $response->assertSee('Plan-Aufgabe', false);
        $response->assertSee('Zusammenspiel der Tools', false);
        $response->assertSee('Jedes Tool kann allein genutzt werden', false);
        $response->assertSee('governance-advisor__save-disclosure', false);
        $response->assertSee('governance-advisor__save-disclosure--hub', false);
        $response->assertSee('Session speichern oder Demo anlegen', false);
        $response->assertSee('Demo Workspace ansehen', false);
        $response->assertSee('/governance/demo-workspace', false);
        $response->assertSee('Beispiel-Report ansehen', false);
        $response->assertSee('/governance/demo-report', false);
        $response->assertSee('Aktive Pläne weiterführen', false);
        $response->assertSee('/sprint-planner?list=1', false);
        $response->assertSee('data-governance-view-report', false);
        $response->assertSee('Report ansehen', false);
        $response->assertSee('governance-advisor__save-primary', false);
        $response->assertSee('governance-advisor__save-secondary', false);
        $response->assertSee('data-governance-setup-workflows', false);
        $response->assertSee('Setup and reference workflows', false);
        $response->assertSee('data-governance-setup-workflow="governance-decision-support"', false);
        $response->assertSee('data-governance-setup-workflow="discovery-assessment"', false);
        $response->assertSee('data-governance-setup-workflow="dbt-pii-governance"', false);
        $response->assertSee('Security &amp; governance setup', false);
        $response->assertSee('Discovery &amp; assessment', false);
        $response->assertDontSee('Collect infos workflow');
        $response->assertSee('Entscheidungshilfen', false);
        $response->assertSee('Decision question');
        $response->assertSee('Helps with');
        $response->assertSee('Afterwards you have');
        $response->assertSee('Shortlist');
        $response->assertSee('Source scope');
        $response->assertSee('fact/dimension candidates');
        $response->assertSee('Risk backlog');
        $response->assertSee('Source Scope Builder');
        $response->assertSee('Governance Stack Advisor');
        $response->assertSee('PII/DSDR Readiness');
        $response->assertSee('KPI Definition Card');
        $response->assertSee('Supplier library');
        $response->assertSee('Supplier Library: wofür hilft sie?', false);
        $response->assertSee('CRM &amp; revenue', false);
        $response->assertSee('ERP, finance &amp; procurement', false);
        $response->assertSee('HCM &amp; workforce', false);
        $response->assertSee('Collaboration &amp; service', false);
        $response->assertSee('PII Policy');
        $response->assertSee('/tools/kpi-requirements-intake', false);
        $response->assertSee('/tools/source-scope-builder', false);
        $response->assertSee('/tools/mart-design-brief-generator', false);
        $response->assertSee('/tools/governance-stack-advisor', false);
        $response->assertSee('/tools/pii-dsdr-readiness-checker', false);
        $response->assertSee('/tools/decision-brief-generator', false);
        $response->assertSee('/tools/vendor-learning-path-builder', false);
        $response->assertSee('/tools/architecture-fit', false);
        $response->assertSee('/tools/meta-export-generator', false);
        $response->assertSee('/tools/dbt-dq-rules-generator', false);
        $response->assertSee('/tools/dbt-dq-macro-generator', false);
        $response->assertSee('/tools/dbt-dq-history-generator', false);
        $response->assertSee('/tools/fabric-pii-governance-pattern-generator', false);
        $response->assertSee('/tools/databricks-pii-governance-pattern-generator', false);
        $response->assertSee('/tools/unity-catalog-governance-generator', false);
        $response->assertSee('/resources', false);
        $response->assertSee('/suppliers', false);
        $response->assertSee('/tools/stakeholder-matrix', false);
        $response->assertSee('/tools/kpi-definition', false);
        $response->assertSee('/tools/pii-policy-generator', false);
        $response->assertSee('/compliance', false);
        $response->assertSee('data-text-de="Governance"', false);
        $response->assertSee('tools-sidenav__link--active', false);
        $response->assertSee('application/ld+json', false);
        $response->assertSee('"@context":"https://schema.org"', false);
        $response->assertDontSee('__contextArgs', false);
        $response->assertSee('Thomas Lindackers');
    }

    public function test_governance_radar_renders_sources_filters_and_seo(): void
    {
        $response = $this->get('/governance/radar');

        $response->assertOk();
        $response->assertSee('Governance Radar');
        $response->assertSee('tools-shell__main--overview', false);
        $response->assertSee('tools-overview-sticky-header', false);
        $response->assertSee('governance-radar-sticky', false);
        $response->assertSee('data-governance-radar', false);
        $response->assertSee('data-governance-radar-search', false);
        $response->assertSee('data-governance-radar-topic', false);
        $response->assertSee('data-governance-radar-type', false);
        $response->assertSee('data-governance-radar-stack', false);
        $response->assertSee('data-governance-radar-region', false);
        $response->assertSee('value="DE"', false);
        $response->assertSee('value="EU"', false);
        $response->assertSee('value="Global"', false);
        $response->assertSee('data-region=', false);
        $response->assertSee('governance-radar__item-row', false);
        $response->assertSee('governance-radar__item-icon', false);
        $response->assertSee('governance-radar__item-icon--security', false);
        $response->assertSee('fa-shield-halved', false);
        $response->assertSee('value="Datenschutz"', false);
        $response->assertSee('value="Security"', false);
        $response->assertSee('data-topic-types', false);
        $response->assertSee('data-topics=', false);
        $response->assertDontSee('value="datenschutz"', false);
        $response->assertDontSee('value="Alle Stacks"', false);
        $response->assertDontSee('governance-radar__type-chip', false);
        $response->assertSee('data-governance-radar-item', false);
        $response->assertSee('data-governance-radar-count', false);
        $response->assertSee('data-governance-radar-compact-toggle', false);
        $response->assertSee('data-governance-radar-intro', false);
        $response->assertSee('governance-radar__intro', false);
        $response->assertDontSee('Feed Registry');
        $response->assertDontSee('data-governance-radar-admin', false);
        $response->assertSee('governance-radar__item--security', false);
        $response->assertSee('governance-radar__impact', false);
        $response->assertSee('governance-radar__impact--critical', false);
        $response->assertSee('governance-radar__item-footer', false);
        $response->assertSee('governance-radar__item-bar', false);
        $response->assertSee('governance-radar__chip--stack', false);
        $response->assertSee('EDPB');
        $response->assertSee('BfDI');
        $response->assertSee('CNIL');
        $response->assertSee('DPC');
        $response->assertSee('IAPP');
        $response->assertSee('NOYB');
        $response->assertSee('Purview');
        $response->assertSee('Fabric');
        $response->assertSee('Power BI');
        $response->assertSee('Qlik');
        $response->assertSee('Tableau');
        $response->assertSee('BayLDA');
        $response->assertSee('BSI');
        $response->assertSee('CISA');
        $response->assertSee('Collibra');
        $response->assertSee('Alation');
        $response->assertSee('Security News');
        $response->assertDontSee('LfDI Baden-Württemberg', false);
        $response->assertSee('Snowflake: Clean Rooms');
        $response->assertSee('Databricks: Unity Catalog');
        $response->assertSee('BfDI: Datenschutzaufsicht nach dem Data Act');
        $response->assertSee('binom');
        $response->assertSee('Richtlinien');
        $response->assertSee('Vendor Update');
        $response->assertSee('Eigene News');
        $response->assertSee('data-governance-radar-advisor', false);
        $response->assertSee('data-impact="Orientierung"', false);
        $response->assertSee('data-impact="Handlungsbedarf"', false);
        $response->assertDontSee('/sprint-planner/create', false);
        $response->assertSee('/governance', false);
        $response->assertSee('application/ld+json', false);
        $response->assertSee('"@type":"CollectionPage"', false);
        $response->assertSee('Thomas Lindackers');

        $html = $response->getContent();
        $itemCount = substr_count($html, 'data-governance-radar-item');
        $advisorCount = substr_count($html, 'data-governance-radar-advisor');
        $this->assertGreaterThan(0, $advisorCount);
        $this->assertLessThan($itemCount, $advisorCount);
    }
}
