<?php

namespace Tests\Feature\Governance;

use Tests\TestCase;

class GovernanceHubTest extends TestCase
{
    public function test_governance_hub_connects_existing_hubs_and_tools(): void
    {
        $response = $this->get('/governance');

        $response->assertOk();
        $response->assertSee('data-phone-hide-tools', false);
        $response->assertSee('phone-hide-tools', false);
        $response->assertSee('data-phone-hide-advisor', false);
        $response->assertSee('phone-hide-advisor', false);
        $response->assertSee('governance-hub__phone-hint', false);
        $response->assertSee('data-phone-only', false);
        $response->assertSee('governance.phoneHintTitle', false);
        $response->assertSee('Governance Hub');
        $response->assertSee('governance-hub', false);
        $response->assertSee('Public online advisor');
        $response->assertSee('data-governance-advisor', false);
        $response->assertSee('data-governance-advisor-config', false);
        $response->assertSee(route('learning-paths.index'), false);
        $response->assertSee(route('roles.index'), false);
        $response->assertSee(route('sprint-planner.templates'), false);
        $response->assertSee('"learningPaths"', false);
        $response->assertSee('"roles"', false);
        $response->assertSee('"sprintPlanner"', false);
        $response->assertSee('data-governance-top-controls', false);
        $response->assertSee('data-governance-drawer-toggle', false);
        $response->assertSee('governance-hub__panel-tabs', false);
        $response->assertSee('governance-hub__panel-tab--active', false);
        $response->assertSee('data-governance-panel-toggle="governance-save-panel"', false);
        $response->assertSee('data-governance-panel-toggle="governance-filter-panel"', false);
        $response->assertSee('data-governance-panel-toggle="governance-help-panel"', false);
        $response->assertDontSee('data-governance-panel-toggle="governance-tools-panel"', false);
        $response->assertSee('Save / Filter / Help', false);
        $response->assertSee('>Reset filter</span>', false);
        $response->assertDontSee('Save & help', false);
        $response->assertDontSee('Help · FAQ', false);
        $response->assertDontSee('Tool info', false);
        $response->assertSee('Workspace Report', false);
        $response->assertSee('>Radar</span>', false);
        $response->assertSee('/governance/radar', false);
        $response->assertSee('data-shell-sidebar-button', false);
        $response->assertDontSee('/governance/berater', false);
        $response->assertDontSee('/governance/stacks', false);
        $response->assertDontSee('/governance/discovery-canvas', false);
        $response->assertDontSee('governance-www-tabs', false);
        $response->assertDontSee('governance-hub__cluster-links', false);
        $response->assertSee('FAQPage', false);
        $response->assertDontSee('governance-seo-guide', false);
        $response->assertSee('data-governance-tabs', false);
        $response->assertSee('data-governance-initial-tab="advisor"', false);
        $response->assertSee('data-governance-tab-toggle="advisor"', false);
        $response->assertSee('data-governance-tab-toggle="guides"', false);
        $response->assertSee('data-governance-tab-toggle="canvas"', false);
        $response->assertSee('data-governance-tab-toggle="tools"', false);
        $response->assertDontSee('data-governance-tab-toggle="hub"', false);
        $response->assertDontSee('data-governance-tab-toggle="workflows"', false);
        $response->assertDontSee('data-governance-tab-toggle="stacks"', false);
        $response->assertDontSee('data-governance-hub-tabs', false);
        $response->assertSee('role="tablist"', false);
        $response->assertSee('role="tab"', false);
        $response->assertSee('role="tabpanel"', false);
        $response->assertSee('data-governance-tab-panel="advisor"', false);
        $response->assertSee('data-governance-tab-panel="guides"', false);
        $response->assertSee('data-governance-tab-panel="canvas"', false);
        $response->assertSee('data-governance-tab-panel="tools"', false);
        $response->assertSee('data-governance-subtabs="guides"', false);
        $response->assertSee('data-governance-subtab-toggle="journeys"', false);
        $response->assertSee('data-governance-subtab-toggle="stacks"', false);
        $response->assertSee('data-governance-subtabs="tools"', false);
        $response->assertSee('data-governance-subtab-toggle="featured"', false);
        $response->assertSee('data-governance-subtab-toggle="workflows"', false);
        $response->assertSee('id="guides-journeys"', false);
        $response->assertSee('id="guides-stacks"', false);
        $response->assertSee('id="guides-kpi"', false);
        $response->assertSee('id="guides-supplier"', false);
        $response->assertSee('data-governance-persona="all"', false);
        $response->assertSee('data-governance-persona="steward"', false);
        $response->assertSee('data-governance-persona="owner"', false);
        $response->assertSee('data-governance-persona="product-owner"', false);
        $response->assertSee('data-governance-persona="architect"', false);
        $response->assertSee('data-governance-persona="custodian"', false);
        $response->assertSee('data-governance-persona="consumer"', false);
        $response->assertSee('Data Steward', false);
        $response->assertSee('Data Custodian', false);
        $response->assertSee('Data Consumer', false);
        $response->assertDontSee('data-governance-persona="analyst"', false);
        $response->assertDontSee('data-governance-persona="dpo"', false);
        $response->assertSee('data-governance-drawer-toggle', false);
        $response->assertSee('data-governance-panel-toggle="governance-filter-panel"', false);
        $response->assertSee('id="governance-filter-panel"', false);
        $response->assertSee('data-governance-hub-filter-clear', false);
        $response->assertSee('data-governance-header-filter-reset', false);
        $response->assertSee('data-governance-hub-filter-badge', false);
        $response->assertDontSee('governance-tool-info-panel', false);
        $response->assertSee('data-tool-id=', false);
        $response->assertSee('data-governance-stack-builder', false);
        $response->assertSee('value="custom"', false);
        $response->assertSee('/tools/custom-stack-builder', false);
        $response->assertSee('data-governance-discovery-canvas', false);
        $response->assertSee('Modern Data Stack', false);
        $response->assertSee('id="governance-faq"', false);
        $response->assertSee('What is the Governance Hub?', false);
        $response->assertSee('Interactive decision aid');
        $response->assertSee('name="orgContext"', false);
        $response->assertSee('data-governance-org-context', false);
        $response->assertSee('Organisation context');
        $response->assertSee('matching tools, evidence, and gaps');
        $response->assertSee('Ich baue neu auf', false);
        $response->assertSee('Ich ergänze Bestehendes', false);
        $response->assertSee('Alles ist da, ich brauche Hilfe', false);
        $response->assertSee('Source type');
        $response->assertSee('Target stack');
        $response->assertSee('Next question');
        $response->assertSee('Refine DQ decision');
        $response->assertSee('DQ goal');
        $response->assertSee('Issue class');
        $response->assertSee('governance-advisor__helpbox', false);
        $response->assertDontSee('<details class="governance-advisor__helpbox" open>', false);
        $response->assertSee('So nutzt du den Advisor', false);
        $response->assertSee('Der Governance Hub ist keine Linkliste', false);
        $response->assertSee('Plan-Aufgabe', false);
        $response->assertSee('Zusammenspiel der Tools', false);
        $response->assertSee('Jedes Tool kann allein genutzt werden', false);
        $response->assertSee('governance-advisor__save-disclosure', false);
        $response->assertSee('governance-advisor__save-disclosure--hub', false);
        $response->assertSee('Session speichern oder Demo anlegen', false);
        $response->assertSee('Demo Workspace ansehen', false);
        $response->assertSee('/governance/demo-workspace', false);
        $response->assertSee('Beispiel-Report ansehen', false);
        $response->assertSee('/governance/demo-report', false);
        $response->assertSee('Aktive Pläne weiterführen', false);
        $response->assertSee('/sprint-planner?list=1', false);
        $response->assertSee('data-governance-view-report', false);
        $response->assertSee('Report ansehen', false);
        $response->assertSee('governance-advisor__save-primary', false);
        $response->assertSee('governance-advisor__save-secondary', false);
        $response->assertSee('data-governance-setup-workflows', false);
        $response->assertSee('Clickable flowcharts', false);
        $response->assertSee('data-governance-setup-workflow="governance-decision-support"', false);
        $response->assertSee('data-governance-setup-workflow="discovery-assessment"', false);
        $response->assertSee('data-governance-setup-workflow="dbt-pii-governance"', false);
        $response->assertSee('Security &amp; governance setup', false);
        $response->assertSee('Discovery &amp; assessment', false);
        $response->assertDontSee('Collect infos workflow');
        $response->assertSee('Entscheidungshilfen', false);
        $response->assertSee('Decision question');
        $response->assertSee('Helps with');
        $response->assertSee('Afterwards you have');
        $response->assertSee('Shortlist');
        $response->assertSee('Source scope');
        $response->assertSee('fact/dimension candidates');
        $response->assertSee('Risk backlog');
        $response->assertSee('Source Scope Builder');
        $response->assertSee('Governance Stack Advisor');
        $response->assertSee('PII/DSDR Readiness');
        $response->assertSee('KPI Definition Card');
        $response->assertSee('Supplier library');
        $response->assertSee('Supplier Library: wofür hilft sie?', false);
        $response->assertSee('CRM &amp; revenue', false);
        $response->assertSee('ERP, finance &amp; procurement', false);
        $response->assertSee('HCM &amp; workforce', false);
        $response->assertSee('Collaboration &amp; service', false);
        $response->assertSee('PII Policy');
        $response->assertSee('/tools/kpi-requirements-intake', false);
        $response->assertSee('/tools/source-scope-builder', false);
        $response->assertSee('/tools/mart-design-brief-generator', false);
        $response->assertSee('/tools/governance-stack-advisor', false);
        $response->assertSee('/tools/pii-dsdr-readiness-checker', false);
        $response->assertSee('/tools/decision-brief-generator', false);
        $response->assertSee('/tools/vendor-learning-path-builder', false);
        $response->assertSee('/tools/architecture-fit', false);
        $response->assertSee('/tools/meta-export-generator', false);
        $response->assertSee('/tools/dbt-dq-rules-generator', false);
        $response->assertSee('/tools/dbt-dq-macro-generator', false);
        $response->assertSee('/tools/dbt-dq-history-generator', false);
        $response->assertSee('/tools/fabric-pii-governance-pattern-generator', false);
        $response->assertSee('/tools/databricks-pii-governance-pattern-generator', false);
        $response->assertSee('/tools/unity-catalog-governance-generator', false);
        $response->assertSee('/resources', false);
        $response->assertSee('/suppliers', false);
        $response->assertSee('/tools/stakeholder-matrix', false);
        $response->assertSee('/tools/kpi-definition', false);
        $response->assertSee('/tools/pii-policy-generator', false);
        $response->assertSee('/compliance', false);
        $response->assertSee('data-text-de="Governance"', false);
        $response->assertSee('tools-sidenav__link--active', false);
        $response->assertSee('application/ld+json', false);
        $response->assertSee('"@context":"https://schema.org"', false);
        $response->assertDontSee('__contextArgs', false);
        $response->assertSee('Thomas Lindackers');
        $response->assertSee('governance-hub__tool-grid', false);
        $response->assertSee('Related tools', false);
    }

    public function test_governance_radar_renders_sources_filters_and_seo(): void
    {
        $response = $this->get('/governance/radar');

        $response->assertOk();
        $response->assertSee('Governance Radar');
        $response->assertSee('tools-shell__main--overview', false);
        $response->assertSee('tools-overview-sticky-header', false);
        $response->assertSee('governance-radar-sticky', false);
        $response->assertSee('data-governance-radar', false);
        $response->assertSee('data-governance-radar-search', false);
        $response->assertSee('data-governance-radar-topic', false);
        $response->assertSee('data-governance-radar-type-multi', false);
        $response->assertSee('data-governance-radar-type-option', false);
        $response->assertSee('data-governance-radar-type-toggle', false);
        $response->assertSee('data-governance-radar-stack', false);
        $response->assertSee('data-governance-radar-region', false);
        $response->assertSee('value="DE"', false);
        $response->assertSee('value="EU"', false);
        $response->assertSee('value="Global"', false);
        $response->assertSee('data-region=', false);
        $response->assertSee('governance-radar__item-row', false);
        $response->assertSee('governance-radar__item-icon', false);
        $response->assertSee('governance-radar__item-icon--security', false);
        $response->assertSee('fa-shield-halved', false);
        $response->assertSee('value="Datenschutz"', false);
        $response->assertSee('value="Security"', false);
        $response->assertSee('data-topic-types', false);
        $response->assertSee('data-topics=', false);
        $response->assertDontSee('value="datenschutz"', false);
        $response->assertDontSee('value="Alle Stacks"', false);
        $response->assertDontSee('governance-radar__type-chip', false);
        $response->assertSee('data-governance-radar-item', false);
        $response->assertSee('data-governance-radar-count', false);
        $response->assertSee('data-governance-radar-hide-read', false);
        $response->assertSee('data-governance-radar-read-reset', false);
        $response->assertSee('data-governance-radar-mark-read', false);
        $response->assertSee('data-governance-radar-unread-empty', false);
        $response->assertSee('data-governance-radar-compact-toggle', false);
        $response->assertSee('data-governance-radar-intro', false);
        $response->assertSee('governance-radar__intro', false);
        $response->assertSee('data-origin="example"', false);
        $response->assertSee('data-origin="vendor"', false);
        $response->assertSee('data-language="en"', false);
        $response->assertSee('Snowflake Release Notes', false);
        $response->assertSee('Databricks Release Notes', false);
        $response->assertDontSee('data-governance-radar-enrich', false);
        $response->assertDontSee('data-radar-overlays-api-url', false);
        $response->assertDontSee('Feed Registry');
        $response->assertDontSee('data-governance-radar-admin', false);
        $response->assertSee('governance-radar__item--security', false);
        $response->assertSee('governance-radar__impact', false);
        $response->assertSee('governance-radar__impact--critical', false);
        $response->assertSee('governance-radar__item-footer', false);
        $response->assertSee('governance-radar__item-bar', false);
        $response->assertSee('governance-radar__chip--stack', false);
        $response->assertSee('EDPB');
        $response->assertSee('BfDI');
        $response->assertSee('CNIL');
        $response->assertSee('DPC');
        $response->assertSee('IAPP');
        $response->assertSee('NOYB');
        $response->assertSee('Purview');
        $response->assertSee('Fabric');
        $response->assertSee('Power BI');
        $response->assertSee('Qlik');
        $response->assertSee('Tableau');
        $response->assertSee('BayLDA');
        $response->assertSee('BSI');
        $response->assertSee('CISA');
        $response->assertSee('Collibra');
        $response->assertSee('Alation');
        $response->assertSee('Security News');
        $response->assertDontSee('LfDI Baden-Württemberg', false);
        $response->assertSee('Snowflake: Clean Rooms');
        $response->assertSee('Databricks: Unity Catalog');
        $response->assertSee('BfDI: Datenschutzaufsicht nach dem Data Act');
        $response->assertSee('binom');
        $response->assertSee('Richtlinien');
        $response->assertSee('Vendor Update');
        $response->assertSee('Binom News');
        $response->assertSee('data-governance-radar-advisor', false);
        $response->assertSee('data-impact="Orientierung"', false);
        $response->assertSee('data-impact="Handlungsbedarf"', false);
        $response->assertDontSee('/sprint-planner/create', false);
        $response->assertSee('/governance', false);
        $response->assertSee('application/ld+json', false);
        $response->assertSee('"@type":"CollectionPage"', false);
        $response->assertSee('Thomas Lindackers');

        $html = $response->getContent();
        $itemCount = substr_count($html, 'data-governance-radar-item');
        $advisorCount = substr_count($html, 'data-governance-radar-advisor');
        $this->assertGreaterThan(0, $advisorCount);
        $this->assertLessThan($itemCount, $advisorCount);
    }
}
