<?php

/**
 * Glossary buzzword wave 5 — quiz-friendly terms (distinct defs, clear categories).
 *
 * @return list<array<string, mixed>>
 */
return [
    [
        'id' => 'data-governance-manager',
        'order' => 61,
        'category' => 'roles',
        'term' => ['de' => 'Data Governance Manager', 'en' => 'Data Governance Manager'],
        'aliases' => ['DGM', 'Governance Manager'],
        'definition' => [
            'de' => 'Koordiniert Governance-Programm, Policies und Rollout — setzt Rahmen, owned nicht jedes Dataset einzeln.',
            'en' => 'Coordinates governance program, policies, and rollout — sets the frame, does not own every dataset personally.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'governance-lead', 'label' => ['de' => 'Governance Lead', 'en' => 'Governance Lead']],
            ['type' => 'glossary', 'id' => 'governance-coe', 'label' => ['de' => 'Governance CoE', 'en' => 'Governance CoE']],
            ['type' => 'glossary', 'id' => 'data-steward', 'label' => ['de' => 'Data Steward', 'en' => 'Data Steward']],
        ],
    ],
    [
        'id' => 'analytics-lead',
        'order' => 62,
        'category' => 'roles',
        'term' => ['de' => 'Analytics Lead', 'en' => 'Analytics Lead'],
        'aliases' => ['Head of Analytics', 'Analytics Manager'],
        'definition' => [
            'de' => 'Führt Analytics-Team und Prioritäten (Backlog, Qualität, Adoption) — Brücke zwischen BI/DS und Fachbereich.',
            'en' => 'Leads analytics team and priorities (backlog, quality, adoption) — bridge between BI/DS and business.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'analytics-translator', 'label' => ['de' => 'Analytics Translator', 'en' => 'Analytics Translator']],
            ['type' => 'glossary', 'id' => 'head-of-data', 'label' => ['de' => 'Head of Data', 'en' => 'Head of Data']],
            ['type' => 'glossary', 'id' => 'self-service-bi', 'label' => ['de' => 'Self-Service BI', 'en' => 'Self-Service BI']],
        ],
    ],
    [
        'id' => 'data-ops-engineer',
        'order' => 63,
        'category' => 'roles',
        'term' => ['de' => 'DataOps Engineer', 'en' => 'DataOps Engineer'],
        'aliases' => ['Data Ops Engineer', 'Pipeline Reliability Engineer'],
        'definition' => [
            'de' => 'Automatisiert und betreibt Datenpipelines (CI/CD, Monitoring, Recovery) — Ops für Daten, nicht nur Infra.',
            'en' => 'Automates and runs data pipelines (CI/CD, monitoring, recovery) — ops for data, not infra alone.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
            ['type' => 'glossary', 'id' => 'platform-engineer', 'label' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer']],
            ['type' => 'glossary', 'id' => 'data-observability', 'label' => ['de' => 'Data Observability', 'en' => 'Data Observability']],
        ],
    ],
    [
        'id' => 'compliance-analyst',
        'order' => 64,
        'category' => 'roles',
        'term' => ['de' => 'Compliance Analyst', 'en' => 'Compliance Analyst'],
        'aliases' => ['Privacy Analyst', 'Regulatory Analyst'],
        'definition' => [
            'de' => 'Übersetzt Regulierung in prüfbare Anforderungen für Daten/BI — nicht nur Checklisten ohne Technikbezug.',
            'en' => 'Translates regulation into auditable requirements for data/BI — not checklists without technical context.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'dpia', 'label' => ['de' => 'DPIA', 'en' => 'DPIA']],
            ['type' => 'glossary', 'id' => 'lawful-basis', 'label' => ['de' => 'Lawful Basis', 'en' => 'Lawful Basis']],
            ['type' => 'glossary', 'id' => 'data-steward', 'label' => ['de' => 'Data Steward', 'en' => 'Data Steward']],
        ],
    ],
    [
        'id' => 'data-mesh-principle',
        'order' => 251,
        'category' => 'data',
        'term' => ['de' => 'Data Mesh Principle', 'en' => 'Data Mesh Principle'],
        'aliases' => ['Mesh Principles', 'Domain-Oriented Decentralization'],
        'definition' => [
            'de' => 'Leitplanken für dezentrale Datenprodukte (Domain Ownership, Self-Serve, Federated Governance) — kein Tool-Produktname.',
            'en' => 'Guardrails for decentralized data products (domain ownership, self-serve, federated governance) — not a tool product name.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-mesh', 'label' => ['de' => 'Data Mesh', 'en' => 'Data Mesh']],
            ['type' => 'glossary', 'id' => 'domain-data-product', 'label' => ['de' => 'Domain Data Product', 'en' => 'Domain Data Product']],
            ['type' => 'glossary', 'id' => 'self-serve-platform', 'label' => ['de' => 'Self-Serve Platform', 'en' => 'Self-Serve Platform']],
        ],
    ],
    [
        'id' => 'data-contract-testing',
        'order' => 252,
        'category' => 'data',
        'term' => ['de' => 'Data Contract Testing', 'en' => 'Data Contract Testing'],
        'aliases' => ['Contract Test', 'Schema Contract Test'],
        'definition' => [
            'de' => 'Automatisierte Tests gegen den veröffentlichten Datenvertrag — bricht der Producer, fällt der Build, nicht das Dashboard.',
            'en' => 'Automated tests against the published data contract — if producer breaks, build fails, not the dashboard.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
            ['type' => 'glossary', 'id' => 'expectation-suite', 'label' => ['de' => 'Expectation Suite', 'en' => 'Expectation Suite']],
            ['type' => 'glossary', 'id' => 'write-audit-publish', 'label' => ['de' => 'WAP', 'en' => 'WAP']],
        ],
    ],
    [
        'id' => 'data-portability',
        'order' => 253,
        'category' => 'data',
        'term' => ['de' => 'Data Portability', 'en' => 'Data Portability'],
        'aliases' => ['Portability Right', 'Datenportabilität'],
        'definition' => [
            'de' => 'Betroffene können Daten in maschinenlesbarem Format erhalten/übertragen — technische Export-Pfade müssen existieren.',
            'en' => 'Data subjects can receive/transfer data in machine-readable form — technical export paths must exist.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-subject', 'label' => ['de' => 'Data Subject', 'en' => 'Data Subject']],
            ['type' => 'glossary', 'id' => 'right-to-erasure', 'label' => ['de' => 'Right to Erasure', 'en' => 'Right to Erasure']],
            ['type' => 'glossary', 'id' => 'consent', 'label' => ['de' => 'Consent', 'en' => 'Consent']],
        ],
    ],
    [
        'id' => 'data-product-specification',
        'order' => 254,
        'category' => 'data',
        'term' => ['de' => 'Data Product Specification', 'en' => 'Data Product Specification'],
        'aliases' => ['Product Spec', 'DPS'],
        'definition' => [
            'de' => 'Verbindliche Beschreibung von Interface, SLA, Schema und Owner — Canvas wird hier operationalisiert.',
            'en' => 'Binding description of interface, SLA, schema, and owner — where the canvas becomes operational.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-product-canvas', 'label' => ['de' => 'Data Product Canvas', 'en' => 'Data Product Canvas']],
            ['type' => 'glossary', 'id' => 'data-product', 'label' => ['de' => 'Data Product', 'en' => 'Data Product']],
            ['type' => 'glossary', 'id' => 'data-sla', 'label' => ['de' => 'Data SLA', 'en' => 'Data SLA']],
        ],
    ],
    [
        'id' => 'event-carried-state-transfer',
        'order' => 530,
        'category' => 'architecture',
        'term' => ['de' => 'Event-Carried State Transfer', 'en' => 'Event-Carried State Transfer'],
        'aliases' => ['ECST', 'Fat Event'],
        'definition' => [
            'de' => 'Event enthält genug Zustand, dass Consumer ohne Nachfrage am Producer arbeiten — Trade-off: größere Payloads.',
            'en' => 'Event carries enough state for consumers to work without querying the producer — trade-off: larger payloads.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'event-driven-architecture', 'label' => ['de' => 'EDA', 'en' => 'EDA']],
            ['type' => 'glossary', 'id' => 'event-sourcing', 'label' => ['de' => 'Event Sourcing', 'en' => 'Event Sourcing']],
            ['type' => 'glossary', 'id' => 'cqrs-read-model', 'label' => ['de' => 'CQRS Read Model', 'en' => 'CQRS Read Model']],
        ],
    ],
    [
        'id' => 'strangler-fig',
        'order' => 531,
        'category' => 'architecture',
        'term' => ['de' => 'Strangler Fig Pattern', 'en' => 'Strangler Fig Pattern'],
        'aliases' => ['Strangler Pattern', 'Strangler Fig'],
        'definition' => [
            'de' => 'Legacy schrittweise durch neues System ersetzen, Route für Route — Big-Bang-Migration vermeiden.',
            'en' => 'Replace legacy incrementally, route by route — avoid big-bang migration.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'canary-release', 'label' => ['de' => 'Canary Release', 'en' => 'Canary Release']],
            ['type' => 'glossary', 'id' => 'feature-flag', 'label' => ['de' => 'Feature Flag', 'en' => 'Feature Flag']],
            ['type' => 'glossary', 'id' => 'modern-data-warehouse', 'label' => ['de' => 'Modern DWH', 'en' => 'Modern DWH']],
        ],
    ],
    [
        'id' => 'bulkhead-pattern',
        'order' => 532,
        'category' => 'architecture',
        'term' => ['de' => 'Bulkhead Pattern', 'en' => 'Bulkhead Pattern'],
        'aliases' => ['Bulkhead', 'Isolation Bulkhead'],
        'definition' => [
            'de' => 'Ressourcen isolieren, damit ein Ausfall nicht alles mitreißt — z. B. separate Pools pro Tenant/Domain.',
            'en' => 'Isolate resources so one failure does not take everything down — e.g. separate pools per tenant/domain.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'circuit-breaker', 'label' => ['de' => 'Circuit Breaker', 'en' => 'Circuit Breaker']],
            ['type' => 'glossary', 'id' => 'saga-pattern', 'label' => ['de' => 'Saga Pattern', 'en' => 'Saga Pattern']],
            ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
        ],
    ],
    [
        'id' => 'sidecar-pattern',
        'order' => 533,
        'category' => 'architecture',
        'term' => ['de' => 'Sidecar Pattern', 'en' => 'Sidecar Pattern'],
        'aliases' => ['Sidecar Container', 'Sidecar Proxy'],
        'definition' => [
            'de' => 'Hilfsprozess läuft neben dem Hauptservice (Logging, Mesh, Auth) — entkoppelt Cross-Cutting von App-Code.',
            'en' => 'Helper process runs beside the main service (logging, mesh, auth) — decouples cross-cutting from app code.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'service-mesh', 'label' => ['de' => 'Service Mesh', 'en' => 'Service Mesh']],
            ['type' => 'glossary', 'id' => 'platform-engineer', 'label' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer']],
            ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
        ],
    ],
    [
        'id' => 'service-mesh',
        'order' => 534,
        'category' => 'architecture',
        'term' => ['de' => 'Service Mesh', 'en' => 'Service Mesh'],
        'aliases' => ['Mesh Layer', 'Istio/Linkerd Class'],
        'definition' => [
            'de' => 'Infrastrukturschicht für Service-zu-Service (mTLS, Routing, Observability) — Policy ohne App-Änderung.',
            'en' => 'Infrastructure layer for service-to-service (mTLS, routing, observability) — policy without app changes.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'sidecar-pattern', 'label' => ['de' => 'Sidecar Pattern', 'en' => 'Sidecar Pattern']],
            ['type' => 'glossary', 'id' => 'mutual-tls', 'label' => ['de' => 'mTLS', 'en' => 'mTLS']],
            ['type' => 'glossary', 'id' => 'api-gateway', 'label' => ['de' => 'API Gateway', 'en' => 'API Gateway']],
        ],
    ],
    [
        'id' => 'materialized-view',
        'order' => 535,
        'category' => 'architecture',
        'term' => ['de' => 'Materialized View', 'en' => 'Materialized View'],
        'aliases' => ['Mat View', 'Snapshot View'],
        'definition' => [
            'de' => 'Gespeicherte Query-Ergebnisse für schnelle Reads — Refresh-Strategie (incremental/full) ist Teil des Designs.',
            'en' => 'Stored query results for fast reads — refresh strategy (incremental/full) is part of the design.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'aggregation-table', 'label' => ['de' => 'Aggregation Table', 'en' => 'Aggregation Table']],
            ['type' => 'glossary', 'id' => 'incremental-refresh', 'label' => ['de' => 'Incremental Refresh', 'en' => 'Incremental Refresh']],
            ['type' => 'glossary', 'id' => 'read-replica', 'label' => ['de' => 'Read Replica', 'en' => 'Read Replica']],
        ],
    ],
    [
        'id' => 'read-replica',
        'order' => 536,
        'category' => 'architecture',
        'term' => ['de' => 'Read Replica', 'en' => 'Read Replica'],
        'aliases' => ['Replica', 'Read Copy'],
        'definition' => [
            'de' => 'Lesbare Kopie der Primary-DB — entlastet Analytics, Replication Lag muss kommuniziert werden.',
            'en' => 'Readable copy of the primary DB — offloads analytics; replication lag must be communicated.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-replication', 'label' => ['de' => 'Data Replication', 'en' => 'Data Replication']],
            ['type' => 'glossary', 'id' => 'directquery', 'label' => ['de' => 'DirectQuery', 'en' => 'DirectQuery']],
            ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
        ],
    ],
    [
        'id' => 'cold-storage',
        'order' => 537,
        'category' => 'architecture',
        'term' => ['de' => 'Cold Storage', 'en' => 'Cold Storage'],
        'aliases' => ['Archive Tier', 'Cold Tier'],
        'definition' => [
            'de' => 'Günstige, langsame Speicherschicht für selten genutzte Daten — Retrieval-Zeit gehört zum SLA.',
            'en' => 'Cheap, slow storage tier for rarely used data — retrieval time belongs in the SLA.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'retention-schedule', 'label' => ['de' => 'Retention Schedule', 'en' => 'Retention Schedule']],
            ['type' => 'glossary', 'id' => 'lakehouse', 'label' => ['de' => 'Lakehouse', 'en' => 'Lakehouse']],
            ['type' => 'glossary', 'id' => 'parquet', 'label' => ['de' => 'Parquet', 'en' => 'Parquet']],
        ],
    ],
    [
        'id' => 'additive-measure',
        'order' => 728,
        'category' => 'modeling',
        'term' => ['de' => 'Additive Measure', 'en' => 'Additive Measure'],
        'aliases' => ['Fully Additive', 'Summable Measure'],
        'definition' => [
            'de' => 'Kennzahl darf über Dimensionen summiert werden (Umsatz, Menge) — Durchschnitt ist oft nicht additiv.',
            'en' => 'Metric may be summed across dimensions (revenue, quantity) — averages are often not additive.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'semi-additive-measure', 'label' => ['de' => 'Semi-Additive', 'en' => 'Semi-Additive']],
            ['type' => 'glossary', 'id' => 'non-additive-measure', 'label' => ['de' => 'Non-Additive', 'en' => 'Non-Additive']],
            ['type' => 'glossary', 'id' => 'dax', 'label' => ['de' => 'DAX', 'en' => 'DAX']],
        ],
    ],
    [
        'id' => 'semi-additive-measure',
        'order' => 729,
        'category' => 'modeling',
        'term' => ['de' => 'Semi-Additive Measure', 'en' => 'Semi-Additive Measure'],
        'aliases' => ['Semi-Additive', 'Balance Measure'],
        'definition' => [
            'de' => 'Summierbar über manche Dimensionen, nicht über Zeit (Kontostand, Lagerbestand) — Grain entscheidet.',
            'en' => 'Summable across some dimensions, not time (balance, inventory) — grain decides.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'additive-measure', 'label' => ['de' => 'Additive Measure', 'en' => 'Additive Measure']],
            ['type' => 'glossary', 'id' => 'snapshot-fact', 'label' => ['de' => 'Snapshot Fact', 'en' => 'Snapshot Fact']],
            ['type' => 'glossary', 'id' => 'time-intelligence', 'label' => ['de' => 'Time Intelligence', 'en' => 'Time Intelligence']],
        ],
    ],
    [
        'id' => 'non-additive-measure',
        'order' => 730,
        'category' => 'modeling',
        'term' => ['de' => 'Non-Additive Measure', 'en' => 'Non-Additive Measure'],
        'aliases' => ['Non-Additive', 'Ratio Measure'],
        'definition' => [
            'de' => 'Darf nicht sinnvoll über Zeilen summiert werden (Quote, Ø-Preis) — Aggregation braucht Formel, nicht SUM.',
            'en' => 'Must not be naively summed across rows (ratio, avg price) — aggregation needs a formula, not SUM.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'additive-measure', 'label' => ['de' => 'Additive Measure', 'en' => 'Additive Measure']],
            ['type' => 'glossary', 'id' => 'calculation-group', 'label' => ['de' => 'Calculation Group', 'en' => 'Calculation Group']],
            ['type' => 'glossary', 'id' => 'metric-layer', 'label' => ['de' => 'Metric Layer', 'en' => 'Metric Layer']],
        ],
    ],
    [
        'id' => 'tombstone-record',
        'order' => 731,
        'category' => 'modeling',
        'term' => ['de' => 'Tombstone Record', 'en' => 'Tombstone Record'],
        'aliases' => ['Tombstone', 'Delete Marker'],
        'definition' => [
            'de' => 'Marker für gelöschte Einträge in Logs/Streams — Consumer müssen Deletes propagieren, nicht ignorieren.',
            'en' => 'Marker for deleted entries in logs/streams — consumers must propagate deletes, not ignore them.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
            ['type' => 'glossary', 'id' => 'hard-delete', 'label' => ['de' => 'Hard Delete', 'en' => 'Hard Delete']],
            ['type' => 'glossary', 'id' => 'compaction', 'label' => ['de' => 'Compaction', 'en' => 'Compaction']],
        ],
    ],
    [
        'id' => 'bookmark-state',
        'order' => 933,
        'category' => 'bi',
        'term' => ['de' => 'Bookmark State', 'en' => 'Bookmark State'],
        'aliases' => ['Report Bookmark', 'Saved View State'],
        'definition' => [
            'de' => 'Gespeicherte Filter/Sichten in Reports — persönlich vs. geteilt muss klar sein, sonst „falsche Wahrheit“.',
            'en' => 'Saved filters/views in reports — personal vs shared must be clear or “wrong truth” spreads.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'sync-slicer', 'label' => ['de' => 'Sync Slicer', 'en' => 'Sync Slicer']],
            ['type' => 'glossary', 'id' => 'visual-level-filter', 'label' => ['de' => 'Visual Filter', 'en' => 'Visual Filter']],
            ['type' => 'glossary', 'id' => 'self-service-bi', 'label' => ['de' => 'Self-Service BI', 'en' => 'Self-Service BI']],
        ],
    ],
    [
        'id' => 'report-theme',
        'order' => 934,
        'category' => 'bi',
        'term' => ['de' => 'Report Theme', 'en' => 'Report Theme'],
        'aliases' => ['Theme JSON', 'Corporate Theme'],
        'definition' => [
            'de' => 'Zentrale Farben/Schriften für Reports — ohne Theme wird jedes Dashboard ein Design-Experiment.',
            'en' => 'Central colors/fonts for reports — without a theme, every dashboard becomes a design experiment.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'embedded-analytics', 'label' => ['de' => 'Embedded Analytics', 'en' => 'Embedded Analytics']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
            ['type' => 'glossary', 'id' => 'headless-bi', 'label' => ['de' => 'Headless BI', 'en' => 'Headless BI']],
        ],
    ],
    [
        'id' => 'mobile-report',
        'order' => 935,
        'category' => 'bi',
        'term' => ['de' => 'Mobile Report', 'en' => 'Mobile Report'],
        'aliases' => ['Phone Layout', 'Mobile Layout'],
        'definition' => [
            'de' => 'Report-Layout für kleine Screens — andere Prioritäten als Desktop, nicht nur skaliertes Dashboard.',
            'en' => 'Report layout for small screens — different priorities than desktop, not just scaled dashboard.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'report-theme', 'label' => ['de' => 'Report Theme', 'en' => 'Report Theme']],
            ['type' => 'glossary', 'id' => 'embedded-analytics', 'label' => ['de' => 'Embedded Analytics', 'en' => 'Embedded Analytics']],
            ['type' => 'glossary', 'id' => 'paginated-report', 'label' => ['de' => 'Paginated Report', 'en' => 'Paginated Report']],
        ],
    ],
    [
        'id' => 'subscription-report',
        'order' => 936,
        'category' => 'bi',
        'term' => ['de' => 'Report Subscription', 'en' => 'Report Subscription'],
        'aliases' => ['Email Subscription', 'Scheduled Report'],
        'definition' => [
            'de' => 'Automatischer Versand von Report-Snapshots — Snapshot-Zeitpunkt und Filter müssen dokumentiert sein.',
            'en' => 'Automated delivery of report snapshots — snapshot time and filters must be documented.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'paginated-report', 'label' => ['de' => 'Paginated Report', 'en' => 'Paginated Report']],
            ['type' => 'glossary', 'id' => 'freshness-sla', 'label' => ['de' => 'Freshness SLA', 'en' => 'Freshness SLA']],
            ['type' => 'glossary', 'id' => 'embedded-analytics', 'label' => ['de' => 'Embedded Analytics', 'en' => 'Embedded Analytics']],
        ],
    ],
    [
        'id' => 'visual-cross-filter',
        'order' => 937,
        'category' => 'bi',
        'term' => ['de' => 'Visual Cross-Filter', 'en' => 'Visual Cross-Filter'],
        'aliases' => ['Cross-Filtering', 'Cross Highlight'],
        'definition' => [
            'de' => 'Klick in einem Visual filtert andere — mächtig für Exploration, leicht übersehen beim Debuggen.',
            'en' => 'Click in one visual filters others — powerful for exploration, easy to miss when debugging.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'visual-level-filter', 'label' => ['de' => 'Visual Filter', 'en' => 'Visual Filter']],
            ['type' => 'glossary', 'id' => 'page-level-filter', 'label' => ['de' => 'Page Filter', 'en' => 'Page Filter']],
            ['type' => 'glossary', 'id' => 'drillthrough', 'label' => ['de' => 'Drillthrough', 'en' => 'Drillthrough']],
        ],
    ],
    [
        'id' => 'accuracy-check',
        'order' => 1129,
        'category' => 'quality',
        'term' => ['de' => 'Accuracy Check', 'en' => 'Accuracy Check'],
        'aliases' => ['Correctness Check', 'Genauigkeitscheck'],
        'definition' => [
            'de' => 'Prüft, ob Werte fachlich stimmen (Abgleich mit Quelle/Golden Set) — technisch „grün“ reicht nicht.',
            'en' => 'Checks whether values are factually correct (reconcile with source/golden set) — technically “green” is not enough.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'reconciliation-check', 'label' => ['de' => 'Reconciliation', 'en' => 'Reconciliation']],
            ['type' => 'glossary', 'id' => 'data-diff', 'label' => ['de' => 'Data Diff', 'en' => 'Data Diff']],
            ['type' => 'glossary', 'id' => 'data-reliability', 'label' => ['de' => 'Data Reliability', 'en' => 'Data Reliability']],
        ],
    ],
    [
        'id' => 'consistency-check',
        'order' => 1130,
        'category' => 'quality',
        'term' => ['de' => 'Consistency Check', 'en' => 'Consistency Check'],
        'aliases' => ['Cross-System Consistency', 'Konsistenzcheck'],
        'definition' => [
            'de' => 'Gleiche Kennzahl/Entity stimmt über Systeme hinweg — Widersprüche zwischen DWH und CRM sind klassisch.',
            'en' => 'Same metric/entity aligns across systems — DWH vs CRM contradictions are classic.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'accuracy-check', 'label' => ['de' => 'Accuracy Check', 'en' => 'Accuracy Check']],
            ['type' => 'glossary', 'id' => 'golden-record', 'label' => ['de' => 'Golden Record', 'en' => 'Golden Record']],
            ['type' => 'glossary', 'id' => 'data-diff', 'label' => ['de' => 'Data Diff', 'en' => 'Data Diff']],
        ],
    ],
    [
        'id' => 'conformity-check',
        'order' => 1131,
        'category' => 'quality',
        'term' => ['de' => 'Conformity Check', 'en' => 'Conformity Check'],
        'aliases' => ['Format Conformity', 'Konformitätscheck'],
        'definition' => [
            'de' => 'Daten entsprechen Format/Standard (ISO-Datum, Währungscode) — Schema ok, Inhalt trotzdem unbrauchbar.',
            'en' => 'Data matches format/standard (ISO date, currency code) — schema ok, content still unusable.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'validity-rule', 'label' => ['de' => 'Validity Rule', 'en' => 'Validity Rule']],
            ['type' => 'glossary', 'id' => 'schema-drift', 'label' => ['de' => 'Schema Drift', 'en' => 'Schema Drift']],
            ['type' => 'glossary', 'id' => 'expectation-suite', 'label' => ['de' => 'Expectation Suite', 'en' => 'Expectation Suite']],
        ],
    ],
    [
        'id' => 'integrity-check',
        'order' => 1132,
        'category' => 'quality',
        'term' => ['de' => 'Integrity Check', 'en' => 'Integrity Check'],
        'aliases' => ['Referential Integrity Check', 'Integritätscheck'],
        'definition' => [
            'de' => 'Beziehungen zwischen Entitäten halten (FK, Kardinalität) — orphan rows sind ein Integrity-Fail.',
            'en' => 'Relationships between entities hold (FK, cardinality) — orphan rows are an integrity fail.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'orphan-record', 'label' => ['de' => 'Orphan Record', 'en' => 'Orphan Record']],
            ['type' => 'glossary', 'id' => 'uniqueness-check', 'label' => ['de' => 'Uniqueness Check', 'en' => 'Uniqueness Check']],
            ['type' => 'glossary', 'id' => 'completeness-check', 'label' => ['de' => 'Completeness Check', 'en' => 'Completeness Check']],
        ],
    ],
    [
        'id' => 'shift-left-quality',
        'order' => 1133,
        'category' => 'quality',
        'term' => ['de' => 'Shift-Left Quality', 'en' => 'Shift-Left Quality'],
        'aliases' => ['Quality Shift-Left', 'Frühe Qualität'],
        'definition' => [
            'de' => 'Qualitätsregeln und Tests möglichst früh in Pipeline/Dev — teure Fixes im Dashboard vermeiden.',
            'en' => 'Quality rules and tests as early as pipeline/dev — avoid expensive fixes in the dashboard.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-contract-testing', 'label' => ['de' => 'Contract Testing', 'en' => 'Contract Testing']],
            ['type' => 'glossary', 'id' => 'expectation-suite', 'label' => ['de' => 'Expectation Suite', 'en' => 'Expectation Suite']],
            ['type' => 'glossary', 'id' => 'definition-of-ready', 'label' => ['de' => 'Definition of Ready', 'en' => 'Definition of Ready']],
        ],
    ],
    [
        'id' => 'data-breach',
        'order' => 1230,
        'category' => 'privacy',
        'term' => ['de' => 'Data Breach', 'en' => 'Data Breach'],
        'aliases' => ['Security Breach', 'Datenpanne'],
        'definition' => [
            'de' => 'Unbefugte Offenlegung/Zugriff auf personenbezogene Daten — Meldefristen und Forensik sind Pflicht.',
            'en' => 'Unauthorized disclosure/access to personal data — notification deadlines and forensics are mandatory.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'breach-notification', 'label' => ['de' => 'Breach Notification', 'en' => 'Breach Notification']],
            ['type' => 'glossary', 'id' => 'dpia', 'label' => ['de' => 'DPIA', 'en' => 'DPIA']],
            ['type' => 'glossary', 'id' => 'incident-severity', 'label' => ['de' => 'Incident Severity', 'en' => 'Incident Severity']],
        ],
    ],
    [
        'id' => 'breach-notification',
        'order' => 1231,
        'category' => 'privacy',
        'term' => ['de' => 'Breach Notification', 'en' => 'Breach Notification'],
        'aliases' => ['72h Notification', 'Meldepflicht'],
        'definition' => [
            'de' => 'Pflicht, Aufsicht/Betroffene über relevante Vorfälle zu informieren — braucht Playbook und Nachweis.',
            'en' => 'Duty to inform authority/subjects about relevant incidents — needs playbook and evidence.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-breach', 'label' => ['de' => 'Data Breach', 'en' => 'Data Breach']],
            ['type' => 'glossary', 'id' => 'runbook', 'label' => ['de' => 'Runbook', 'en' => 'Runbook']],
            ['type' => 'glossary', 'id' => 'incident-commander', 'label' => ['de' => 'Incident Commander', 'en' => 'Incident Commander']],
        ],
    ],
    [
        'id' => 're-identification-risk',
        'order' => 1232,
        'category' => 'privacy',
        'term' => ['de' => 'Re-Identification Risk', 'en' => 'Re-Identification Risk'],
        'aliases' => ['Re-ID Risk', 'De-Anonymization Risk'],
        'definition' => [
            'de' => 'Risiko, pseudonymisierte/anonymisierte Daten wieder einer Person zuzuordnen — Quasi-Identifier beachten.',
            'en' => 'Risk of linking pseudonymized/anonymized data back to a person — watch quasi-identifiers.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'k-anonymity', 'label' => ['de' => 'k-Anonymity', 'en' => 'k-Anonymity']],
            ['type' => 'glossary', 'id' => 'differential-privacy', 'label' => ['de' => 'Differential Privacy', 'en' => 'Differential Privacy']],
            ['type' => 'glossary', 'id' => 'data-clean-room', 'label' => ['de' => 'Data Clean Room', 'en' => 'Data Clean Room']],
        ],
    ],
    [
        'id' => 'standard-contractual-clauses',
        'order' => 1233,
        'category' => 'privacy',
        'term' => ['de' => 'Standard Contractual Clauses', 'en' => 'Standard Contractual Clauses'],
        'aliases' => ['SCCs', 'EU Standardvertragsklauseln'],
        'definition' => [
            'de' => 'Vertragsbausteine für Drittlandtransfers — ergänzen TIA und technische Maßnahmen, ersetzen sie nicht.',
            'en' => 'Contract modules for third-country transfers — complement TIA and technical measures, do not replace them.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'cross-border-transfer', 'label' => ['de' => 'Cross-Border Transfer', 'en' => 'Cross-Border Transfer']],
            ['type' => 'glossary', 'id' => 'schrems-ii', 'label' => ['de' => 'Schrems II', 'en' => 'Schrems II']],
            ['type' => 'glossary', 'id' => 'data-processing-agreement', 'label' => ['de' => 'DPA', 'en' => 'DPA']],
        ],
    ],
    [
        'id' => 'data-processing-agreement',
        'order' => 1234,
        'category' => 'privacy',
        'term' => ['de' => 'Data Processing Agreement', 'en' => 'Data Processing Agreement'],
        'aliases' => ['DPA', 'AVV', 'Auftragsverarbeitungsvertrag'],
        'definition' => [
            'de' => 'Vertrag zwischen Controller und Processor zu Zweck, Subprozessoren und Löschung — Cloud ohne AVV ist rotes Flag.',
            'en' => 'Contract between controller and processor on purpose, subprocessors, deletion — cloud without DPA is a red flag.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'controller-processor', 'label' => ['de' => 'Controller vs Processor', 'en' => 'Controller vs Processor']],
            ['type' => 'glossary', 'id' => 'standard-contractual-clauses', 'label' => ['de' => 'SCCs', 'en' => 'SCCs']],
            ['type' => 'glossary', 'id' => 'lawful-basis', 'label' => ['de' => 'Lawful Basis', 'en' => 'Lawful Basis']],
        ],
    ],
    [
        'id' => 'oauth-client',
        'order' => 1327,
        'category' => 'security',
        'term' => ['de' => 'OAuth Client', 'en' => 'OAuth Client'],
        'aliases' => ['OAuth App', 'Client Registration'],
        'definition' => [
            'de' => 'Registrierte Anwendung mit Client-ID/Secret und Scopes — Rotation und Least-Privilege-Scopes sind Pflicht.',
            'en' => 'Registered app with client ID/secret and scopes — rotation and least-privilege scopes are mandatory.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'identity-provider', 'label' => ['de' => 'Identity Provider', 'en' => 'Identity Provider']],
            ['type' => 'glossary', 'id' => 'service-account', 'label' => ['de' => 'Service Account', 'en' => 'Service Account']],
            ['type' => 'glossary', 'id' => 'least-privilege', 'label' => ['de' => 'Least Privilege', 'en' => 'Least Privilege']],
        ],
    ],
    [
        'id' => 'api-gateway',
        'order' => 1328,
        'category' => 'security',
        'term' => ['de' => 'API Gateway', 'en' => 'API Gateway'],
        'aliases' => ['Gateway', 'Edge Gateway'],
        'definition' => [
            'de' => 'Zentraler Einstieg für APIs (Auth, Rate Limit, Routing) — Policies hier statt in jedem Microservice duplizieren.',
            'en' => 'Central entry for APIs (auth, rate limit, routing) — policies here instead of duplicating in every service.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
            ['type' => 'glossary', 'id' => 'service-mesh', 'label' => ['de' => 'Service Mesh', 'en' => 'Service Mesh']],
            ['type' => 'glossary', 'id' => 'mutual-tls', 'label' => ['de' => 'mTLS', 'en' => 'mTLS']],
        ],
    ],
    [
        'id' => 'mutual-tls',
        'order' => 1329,
        'category' => 'security',
        'term' => ['de' => 'Mutual TLS', 'en' => 'Mutual TLS'],
        'aliases' => ['mTLS', 'Two-Way TLS'],
        'definition' => [
            'de' => 'Client und Server authentifizieren sich per Zertifikat — stärker als TLS-only, braucht Rotation und CA-Governance.',
            'en' => 'Client and server authenticate via certificates — stronger than TLS-only; needs rotation and CA governance.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'service-mesh', 'label' => ['de' => 'Service Mesh', 'en' => 'Service Mesh']],
            ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
            ['type' => 'glossary', 'id' => 'secrets-rotation', 'label' => ['de' => 'Secrets Rotation', 'en' => 'Secrets Rotation']],
        ],
    ],
    [
        'id' => 'network-segmentation',
        'order' => 1330,
        'category' => 'security',
        'term' => ['de' => 'Network Segmentation', 'en' => 'Network Segmentation'],
        'aliases' => ['Segmentation', 'Micro-Segmentation'],
        'definition' => [
            'de' => 'Netz in Zonen teilen, Lateral Movement erschweren — Data-Plane und Admin getrennt halten.',
            'en' => 'Split network into zones to hinder lateral movement — keep data plane and admin separate.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
            ['type' => 'glossary', 'id' => 'privileged-access-management', 'label' => ['de' => 'PAM', 'en' => 'PAM']],
            ['type' => 'glossary', 'id' => 'security-posture', 'label' => ['de' => 'Security Posture', 'en' => 'Security Posture']],
        ],
    ],
    [
        'id' => 'security-posture',
        'order' => 1331,
        'category' => 'security',
        'term' => ['de' => 'Security Posture', 'en' => 'Security Posture'],
        'aliases' => ['Posture Management', 'Security Baseline'],
        'definition' => [
            'de' => 'Gesamtbild der Schutzmaßnahmen und Lücken — Score allein reicht nicht ohne priorisierte Remediation.',
            'en' => 'Overall picture of controls and gaps — score alone is not enough without prioritized remediation.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
            ['type' => 'glossary', 'id' => 'conditional-access', 'label' => ['de' => 'Conditional Access', 'en' => 'Conditional Access']],
            ['type' => 'glossary', 'id' => 'policy-as-code', 'label' => ['de' => 'Policy as Code', 'en' => 'Policy as Code']],
        ],
    ],
    [
        'id' => 'metadata-lineage',
        'order' => 1523,
        'category' => 'metadata',
        'term' => ['de' => 'Metadata Lineage', 'en' => 'Metadata Lineage'],
        'aliases' => ['Lineage Metadata', 'Provenance Metadata'],
        'definition' => [
            'de' => 'Metadaten über Herkunft und Transformation — unterscheidet sich von reinem Business-Glossary-Text.',
            'en' => 'Metadata about origin and transformation — distinct from business-glossary prose alone.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-lineage-graph', 'label' => ['de' => 'Lineage Graph', 'en' => 'Lineage Graph']],
            ['type' => 'glossary', 'id' => 'column-lineage', 'label' => ['de' => 'Column Lineage', 'en' => 'Column Lineage']],
            ['type' => 'glossary', 'id' => 'openlineage', 'label' => ['de' => 'OpenLineage', 'en' => 'OpenLineage']],
        ],
    ],
    [
        'id' => 'business-glossary-term',
        'order' => 1524,
        'category' => 'metadata',
        'term' => ['de' => 'Business Glossary Term', 'en' => 'Business Glossary Term'],
        'aliases' => ['Glossary Term', 'Business Term'],
        'definition' => [
            'de' => 'Fachlich definierter Begriff mit Owner und Status — verlinkt zu technischen Assets, ersetzt sie nicht.',
            'en' => 'Business-defined term with owner and status — links to technical assets, does not replace them.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'business-glossary', 'label' => ['de' => 'Business Glossary', 'en' => 'Business Glossary']],
            ['type' => 'glossary', 'id' => 'data-dictionary', 'label' => ['de' => 'Data Dictionary', 'en' => 'Data Dictionary']],
            ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
        ],
    ],
    [
        'id' => 'continuous-delivery',
        'order' => 1455,
        'category' => 'process',
        'term' => ['de' => 'Continuous Delivery', 'en' => 'Continuous Delivery'],
        'aliases' => ['CD', 'Continuous Deployment'],
        'definition' => [
            'de' => 'Software/Datenpipelines jederzeit release-fähig halten — manueller „Freitag-Deploy“ ist Anti-Pattern.',
            'en' => 'Keep software/data pipelines releasable at any time — manual “Friday deploy” is an anti-pattern.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'canary-release', 'label' => ['de' => 'Canary Release', 'en' => 'Canary Release']],
            ['type' => 'glossary', 'id' => 'blue-green-deployment', 'label' => ['de' => 'Blue-Green', 'en' => 'Blue-Green']],
            ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
        ],
    ],
    [
        'id' => 'change-advisory-board',
        'order' => 1456,
        'category' => 'process',
        'term' => ['de' => 'Change Advisory Board', 'en' => 'Change Advisory Board'],
        'aliases' => ['CAB', 'Change Board'],
        'definition' => [
            'de' => 'Gremium für riskante Changes (Prod, Schema) — soll Gatekeeping reduzieren, nicht jedes Ticket verzögern.',
            'en' => 'Forum for risky changes (prod, schema) — should reduce gatekeeping, not delay every ticket.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'runbook', 'label' => ['de' => 'Runbook', 'en' => 'Runbook']],
            ['type' => 'glossary', 'id' => 'incident-severity', 'label' => ['de' => 'Incident Severity', 'en' => 'Incident Severity']],
            ['type' => 'glossary', 'id' => 'definition-of-done', 'label' => ['de' => 'Definition of Done', 'en' => 'Definition of Done']],
        ],
    ],
    [
        'id' => 'rto',
        'order' => 1457,
        'category' => 'process',
        'term' => ['de' => 'RTO', 'en' => 'RTO'],
        'aliases' => ['Recovery Time Objective', 'Wiederherstellungszeit'],
        'definition' => [
            'de' => 'Maximale akzeptable Ausfallzeit bis Wiederherstellung — ohne RTO ist DR nur PowerPoint.',
            'en' => 'Maximum acceptable downtime until recovery — without RTO, DR is PowerPoint only.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'rpo', 'label' => ['de' => 'RPO', 'en' => 'RPO']],
            ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
            ['type' => 'glossary', 'id' => 'error-budget', 'label' => ['de' => 'Error Budget', 'en' => 'Error Budget']],
        ],
    ],
    [
        'id' => 'rpo',
        'order' => 1458,
        'category' => 'process',
        'term' => ['de' => 'RPO', 'en' => 'RPO'],
        'aliases' => ['Recovery Point Objective', 'Datenverlustfenster'],
        'definition' => [
            'de' => 'Maximal tolerierbarer Datenverlust in der Zeit — Backup-Frequenz muss dazu passen.',
            'en' => 'Maximum tolerable data loss in time — backup frequency must match.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'rto', 'label' => ['de' => 'RTO', 'en' => 'RTO']],
            ['type' => 'glossary', 'id' => 'backfill', 'label' => ['de' => 'Backfill', 'en' => 'Backfill']],
            ['type' => 'glossary', 'id' => 'replay', 'label' => ['de' => 'Replay', 'en' => 'Replay']],
        ],
    ],
    [
        'id' => 'speculative-decoding',
        'order' => 1701,
        'category' => 'ai',
        'term' => ['de' => 'Speculative Decoding', 'en' => 'Speculative Decoding'],
        'aliases' => ['Draft Model Decoding', 'Speculative Sampling'],
        'definition' => [
            'de' => 'Kleines Modell schlägt Tokens vor, großes prüft — senkt Latenz, braucht kompatible Model-Pairs.',
            'en' => 'Small model proposes tokens, large model verifies — cuts latency, needs compatible model pairs.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'model-routing', 'label' => ['de' => 'Model Routing', 'en' => 'Model Routing']],
            ['type' => 'glossary', 'id' => 'temperature', 'label' => ['de' => 'Temperature', 'en' => 'Temperature']],
            ['type' => 'glossary', 'id' => 'llm-gateway', 'label' => ['de' => 'LLM Gateway', 'en' => 'LLM Gateway']],
        ],
    ],
    [
        'id' => 'prompt-chaining',
        'order' => 1702,
        'category' => 'ai',
        'term' => ['de' => 'Prompt Chaining', 'en' => 'Prompt Chaining'],
        'aliases' => ['Chain Prompts', 'Multi-Step Prompt'],
        'definition' => [
            'de' => 'Ausgabe eines Prompt-Schritts wird Eingabe des nächsten — braucht klare Schnittstellen und Evals pro Schritt.',
            'en' => 'Output of one prompt step feeds the next — needs clear interfaces and per-step evals.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'agentic-workflow', 'label' => ['de' => 'Agentic Workflow', 'en' => 'Agentic Workflow']],
            ['type' => 'glossary', 'id' => 'prompt-template', 'label' => ['de' => 'Prompt Template', 'en' => 'Prompt Template']],
            ['type' => 'glossary', 'id' => 'eval-harness', 'label' => ['de' => 'Eval Harness', 'en' => 'Eval Harness']],
        ],
    ],
    [
        'id' => 'llm-gateway',
        'order' => 1703,
        'category' => 'ai',
        'term' => ['de' => 'LLM Gateway', 'en' => 'LLM Gateway'],
        'aliases' => ['Model Gateway', 'AI Gateway'],
        'definition' => [
            'de' => 'Zentraler Proxy für LLM-Calls (Auth, Routing, Logging, Limits) — Governance-Punkt vor dem Modell.',
            'en' => 'Central proxy for LLM calls (auth, routing, logging, limits) — governance point before the model.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'model-routing', 'label' => ['de' => 'Model Routing', 'en' => 'Model Routing']],
            ['type' => 'glossary', 'id' => 'ai-observability', 'label' => ['de' => 'AI Observability', 'en' => 'AI Observability']],
            ['type' => 'glossary', 'id' => 'ai-guardrails', 'label' => ['de' => 'AI Guardrails', 'en' => 'AI Guardrails']],
        ],
    ],
    [
        'id' => 'chunking-strategy',
        'order' => 1704,
        'category' => 'ai',
        'term' => ['de' => 'Chunking Strategy', 'en' => 'Chunking Strategy'],
        'aliases' => ['Document Chunking', 'RAG Chunking'],
        'definition' => [
            'de' => 'Wie Dokumente für RAG zerlegt werden (Größe, Overlap, Struktur) — schlechtes Chunking killt Retrieval.',
            'en' => 'How documents are split for RAG (size, overlap, structure) — bad chunking kills retrieval.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'rag', 'label' => ['de' => 'RAG', 'en' => 'RAG']],
            ['type' => 'glossary', 'id' => 'embedding', 'label' => ['de' => 'Embedding', 'en' => 'Embedding']],
            ['type' => 'glossary', 'id' => 'hybrid-search', 'label' => ['de' => 'Hybrid Search', 'en' => 'Hybrid Search']],
        ],
    ],
    [
        'id' => 'hybrid-search',
        'order' => 1705,
        'category' => 'ai',
        'term' => ['de' => 'Hybrid Search', 'en' => 'Hybrid Search'],
        'aliases' => ['Keyword + Vector Search', 'Blended Retrieval'],
        'definition' => [
            'de' => 'Kombiniert Keyword/BM25 und Vektor-Suche — besser bei exakten IDs und semantischen Paraphrasen.',
            'en' => 'Combines keyword/BM25 and vector search — better for exact IDs and semantic paraphrases.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'vector-search', 'label' => ['de' => 'Vector Search', 'en' => 'Vector Search']],
            ['type' => 'glossary', 'id' => 'reranker', 'label' => ['de' => 'Reranker', 'en' => 'Reranker']],
            ['type' => 'glossary', 'id' => 'chunking-strategy', 'label' => ['de' => 'Chunking Strategy', 'en' => 'Chunking Strategy']],
        ],
    ],
    [
        'id' => 'context-compression',
        'order' => 1706,
        'category' => 'ai',
        'term' => ['de' => 'Context Compression', 'en' => 'Context Compression'],
        'aliases' => ['Prompt Compression', 'Context Pruning'],
        'definition' => [
            'de' => 'Reduziert Kontext vor dem Modell (Summaries, Top-k) — spart Tokens, riskiert Informationsverlust.',
            'en' => 'Shrinks context before the model (summaries, top-k) — saves tokens, risks information loss.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'context-window', 'label' => ['de' => 'Context Window', 'en' => 'Context Window']],
            ['type' => 'glossary', 'id' => 'semantic-caching', 'label' => ['de' => 'Semantic Caching', 'en' => 'Semantic Caching']],
            ['type' => 'glossary', 'id' => 'rag', 'label' => ['de' => 'RAG', 'en' => 'RAG']],
        ],
    ],
];
