<?php

/**
 * Glossary buzzword wave 3 — quiz-friendly terms (distinct defs, clear categories).
 *
 * @return list<array<string, mixed>>
 */
return [
    [
        'id' => 'platform-engineer',
        'order' => 54,
        'category' => 'roles',
        'term' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer'],
        'aliases' => ['Internal Developer Platform', 'Platform Team'],
        'definition' => [
            'de' => 'Baut Self-Service-Pfade (CI, Environments, Observability) für Teams — reduziert Toil, schreibt nicht jedes Dashboard selbst.',
            'en' => 'Builds self-service paths (CI, environments, observability) for teams — cuts toil, does not own every dashboard.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'golden-path', 'label' => ['de' => 'Golden Path', 'en' => 'Golden Path']],
            ['type' => 'glossary', 'id' => 'toil', 'label' => ['de' => 'Toil', 'en' => 'Toil']],
            ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
        ],
    ],
    [
        'id' => 'data-scientist',
        'order' => 55,
        'category' => 'roles',
        'term' => ['de' => 'Data Scientist', 'en' => 'Data Scientist'],
        'aliases' => ['DS', 'Applied Scientist'],
        'definition' => [
            'de' => 'Findet Muster und Modelle aus Daten für Entscheidungen — experimentiert, ersetzt aber nicht Pipeline-Ownership der Platform.',
            'en' => 'Finds patterns and models from data for decisions — experiments, but does not replace platform pipeline ownership.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'ml-engineer', 'label' => ['de' => 'ML Engineer', 'en' => 'ML Engineer']],
            ['type' => 'glossary', 'id' => 'analytics-translator', 'label' => ['de' => 'Analytics Translator', 'en' => 'Analytics Translator']],
            ['type' => 'glossary', 'id' => 'feature-store', 'label' => ['de' => 'Feature Store', 'en' => 'Feature Store']],
        ],
    ],
    [
        'id' => 'prompt-engineer',
        'order' => 56,
        'category' => 'roles',
        'term' => ['de' => 'Prompt Engineer', 'en' => 'Prompt Engineer'],
        'aliases' => ['Prompt Designer', 'LLM Prompt Specialist'],
        'definition' => [
            'de' => 'Gestaltet Prompts, Evaluations und Guardrails für LLM-Nutzung — Fokus auf Verhalten, nicht auf Infrastruktur.',
            'en' => 'Designs prompts, evaluations, and guardrails for LLM use — focuses on behavior, not infrastructure.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'few-shot-prompting', 'label' => ['de' => 'Few-Shot Prompting', 'en' => 'Few-Shot Prompting']],
            ['type' => 'glossary', 'id' => 'ai-guardrails', 'label' => ['de' => 'AI Guardrails', 'en' => 'AI Guardrails']],
            ['type' => 'glossary', 'id' => 'prompt-injection', 'label' => ['de' => 'Prompt Injection', 'en' => 'Prompt Injection']],
        ],
    ],
    [
        'id' => 'ai-product-manager',
        'order' => 57,
        'category' => 'roles',
        'term' => ['de' => 'AI Product Manager', 'en' => 'AI Product Manager'],
        'aliases' => ['AI PM', 'ML Product Manager'],
        'definition' => [
            'de' => 'Priorisiert KI-Features nach Nutzen, Risiko und Messbarkeit — verbindet Business-Outcome mit Model-/Eval-Metriken.',
            'en' => 'Prioritizes AI features by value, risk, and measurability — ties business outcomes to model/eval metrics.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-product-owner', 'label' => ['de' => 'Data Product Owner', 'en' => 'Data Product Owner']],
            ['type' => 'glossary', 'id' => 'model-card', 'label' => ['de' => 'Model Card', 'en' => 'Model Card']],
            ['type' => 'glossary', 'id' => 'human-in-the-loop', 'label' => ['de' => 'Human-in-the-Loop', 'en' => 'Human-in-the-Loop']],
        ],
    ],
    [
        'id' => 'trusted-data-source',
        'order' => 242,
        'category' => 'data',
        'term' => ['de' => 'Trusted Data Source', 'en' => 'Trusted Data Source'],
        'aliases' => ['System of Record', 'Authoritative Source'],
        'definition' => [
            'de' => 'Autoritative Quelle für einen Geschäftsgegenstand — Downstream darf kopieren, nicht widersprechen ohne Contract.',
            'en' => 'Authoritative source for a business entity — downstream may copy, not contradict without a contract.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'golden-record', 'label' => ['de' => 'Golden Record', 'en' => 'Golden Record']],
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
            ['type' => 'glossary', 'id' => 'master-data-management', 'label' => ['de' => 'MDM', 'en' => 'MDM']],
        ],
    ],
    [
        'id' => 'master-data-management',
        'order' => 243,
        'category' => 'data',
        'term' => ['de' => 'Master Data Management', 'en' => 'Master Data Management'],
        'aliases' => ['MDM', 'Stammdatenmanagement'],
        'definition' => [
            'de' => 'Disziplin, Stammdaten (Kunde, Produkt, Ort) konsistent und versioniert bereitzustellen — kein reines Excel-Abgleich.',
            'en' => 'Discipline to provide consistent, versioned master data (customer, product, place) — not spreadsheet matching alone.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'golden-record', 'label' => ['de' => 'Golden Record', 'en' => 'Golden Record']],
            ['type' => 'glossary', 'id' => 'trusted-data-source', 'label' => ['de' => 'Trusted Data Source', 'en' => 'Trusted Data Source']],
            ['type' => 'glossary', 'id' => 'data-steward', 'label' => ['de' => 'Data Steward', 'en' => 'Data Steward']],
        ],
    ],
    [
        'id' => 'operational-data-store',
        'order' => 244,
        'category' => 'data',
        'term' => ['de' => 'Operational Data Store', 'en' => 'Operational Data Store'],
        'aliases' => ['ODS', 'Operational Store'],
        'definition' => [
            'de' => 'Nahe an Ops gehaltene, oft integrierte Kopie für operative Abfragen — kein historisches Warehouse und kein Lakehouse-Ersatz.',
            'en' => 'Near-ops, often integrated copy for operational queries — not a historical warehouse and not a lakehouse substitute.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'modern-data-warehouse', 'label' => ['de' => 'Modern Data Warehouse', 'en' => 'Modern Data Warehouse']],
            ['type' => 'glossary', 'id' => 'lakehouse', 'label' => ['de' => 'Lakehouse', 'en' => 'Lakehouse']],
            ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
        ],
    ],
    [
        'id' => 'metric-layer',
        'order' => 245,
        'category' => 'data',
        'term' => ['de' => 'Metric Layer', 'en' => 'Metric Layer'],
        'aliases' => ['Metrics Layer', 'Governed Metrics'],
        'definition' => [
            'de' => 'Zentrale Definition von Kennzahlen (Formel, Grain, Owner) — verhindert „Revenue“-Varianten je Tool.',
            'en' => 'Central definition of metrics (formula, grain, owner) — prevents per-tool “revenue” variants.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'metric-store', 'label' => ['de' => 'Metric Store', 'en' => 'Metric Store']],
            ['type' => 'glossary', 'id' => 'semantic-layer', 'label' => ['de' => 'Semantic Layer', 'en' => 'Semantic Layer']],
            ['type' => 'glossary', 'id' => 'headless-bi', 'label' => ['de' => 'Headless BI', 'en' => 'Headless BI']],
        ],
    ],
    [
        'id' => 'outbox-pattern',
        'order' => 520,
        'category' => 'architecture',
        'term' => ['de' => 'Outbox Pattern', 'en' => 'Outbox Pattern'],
        'aliases' => ['Transactional Outbox', 'Outbox Table'],
        'definition' => [
            'de' => 'Schreibt Domain-Event und DB-Änderung in einer Transaktion; ein Relayer publiziert asynchron — verhindert Lost Updates zwischen DB und Bus.',
            'en' => 'Writes domain event and DB change in one transaction; a relayer publishes async — avoids lost updates between DB and bus.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'event-sourcing', 'label' => ['de' => 'Event Sourcing', 'en' => 'Event Sourcing']],
            ['type' => 'glossary', 'id' => 'exactly-once', 'label' => ['de' => 'Exactly-Once', 'en' => 'Exactly-Once']],
            ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
        ],
    ],
    [
        'id' => 'saga-pattern',
        'order' => 521,
        'category' => 'architecture',
        'term' => ['de' => 'Saga Pattern', 'en' => 'Saga Pattern'],
        'aliases' => ['Distributed Saga', 'Compensation Saga'],
        'definition' => [
            'de' => 'Orchestriert verteilte Schritte mit Kompensationen statt einer globalen DB-Transaktion — Fehlerfall ist Teil des Designs.',
            'en' => 'Orchestrates distributed steps with compensations instead of one global DB transaction — failure is part of the design.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'event-driven-architecture', 'label' => ['de' => 'EDA', 'en' => 'EDA']],
            ['type' => 'glossary', 'id' => 'circuit-breaker', 'label' => ['de' => 'Circuit Breaker', 'en' => 'Circuit Breaker']],
            ['type' => 'glossary', 'id' => 'idempotency', 'label' => ['de' => 'Idempotency', 'en' => 'Idempotency']],
        ],
    ],
    [
        'id' => 'event-driven-architecture',
        'order' => 522,
        'category' => 'architecture',
        'term' => ['de' => 'Event-Driven Architecture', 'en' => 'Event-Driven Architecture'],
        'aliases' => ['EDA', 'Event-Driven'],
        'definition' => [
            'de' => 'Systeme reagieren auf Events statt synchroner Aufrufketten — entkoppelt Producer/Consumer, braucht klare Event-Verträge.',
            'en' => 'Systems react to events instead of sync call chains — decouples producers/consumers, needs clear event contracts.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'event-sourcing', 'label' => ['de' => 'Event Sourcing', 'en' => 'Event Sourcing']],
            ['type' => 'glossary', 'id' => 'streaming', 'label' => ['de' => 'Streaming', 'en' => 'Streaming']],
            ['type' => 'glossary', 'id' => 'outbox-pattern', 'label' => ['de' => 'Outbox Pattern', 'en' => 'Outbox Pattern']],
        ],
    ],
    [
        'id' => 'micro-batch',
        'order' => 523,
        'category' => 'architecture',
        'term' => ['de' => 'Micro-Batch', 'en' => 'Micro-Batch'],
        'aliases' => ['Mini-Batch', 'Near-Real-Time Batch'],
        'definition' => [
            'de' => 'Verarbeitet Events in kurzen Intervallen (Sekunden/Minuten) statt einzeln — Kompromiss zwischen Latenz und Throughput.',
            'en' => 'Processes events in short intervals (seconds/minutes) instead of one-by-one — trade-off between latency and throughput.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'batch-processing', 'label' => ['de' => 'Batch Processing', 'en' => 'Batch Processing']],
            ['type' => 'glossary', 'id' => 'streaming', 'label' => ['de' => 'Streaming', 'en' => 'Streaming']],
            ['type' => 'glossary', 'id' => 'watermark', 'label' => ['de' => 'Watermark', 'en' => 'Watermark']],
        ],
    ],
    [
        'id' => 'idempotency',
        'order' => 524,
        'category' => 'architecture',
        'term' => ['de' => 'Idempotency', 'en' => 'Idempotency'],
        'aliases' => ['Idempotent Write', 'Idempotent Consumer'],
        'definition' => [
            'de' => 'Gleicher Request/Event mehrfach angewandt liefert denselben Endzustand — Pflicht bei Retries und Exactly-/At-Least-Once.',
            'en' => 'Applying the same request/event multiple times yields the same end state — required with retries and exactly-/at-least-once.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'exactly-once', 'label' => ['de' => 'Exactly-Once', 'en' => 'Exactly-Once']],
            ['type' => 'glossary', 'id' => 'at-least-once', 'label' => ['de' => 'At-Least-Once', 'en' => 'At-Least-Once']],
            ['type' => 'glossary', 'id' => 'outbox-pattern', 'label' => ['de' => 'Outbox Pattern', 'en' => 'Outbox Pattern']],
        ],
    ],
    [
        'id' => 'snapshot-fact',
        'order' => 720,
        'category' => 'modeling',
        'term' => ['de' => 'Snapshot Fact', 'en' => 'Snapshot Fact'],
        'aliases' => ['Periodic Snapshot', 'Status Snapshot'],
        'definition' => [
            'de' => 'Fact-Tabelle misst Zustand zu festen Zeitpunkten (z. B. Tagesbestand) — nicht jeder Einzelvorgang.',
            'en' => 'Fact table measures state at fixed points in time (e.g. daily inventory) — not every individual transaction.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'accumulated-snapshot', 'label' => ['de' => 'Accumulating Snapshot', 'en' => 'Accumulating Snapshot']],
            ['type' => 'glossary', 'id' => 'star-schema', 'label' => ['de' => 'Star Schema', 'en' => 'Star Schema']],
            ['type' => 'glossary', 'id' => 'slowly-changing-dimension', 'label' => ['de' => 'SCD', 'en' => 'SCD']],
        ],
    ],
    [
        'id' => 'accumulated-snapshot',
        'order' => 721,
        'category' => 'modeling',
        'term' => ['de' => 'Accumulating Snapshot', 'en' => 'Accumulating Snapshot'],
        'aliases' => ['Pipeline Snapshot', 'Lifecycle Fact'],
        'definition' => [
            'de' => 'Fact-Zeile folgt einem Prozess über Meilensteine (Auftrag→Versand→Zahlung) und wird aktualisiert — typisch für Durchlaufzeiten.',
            'en' => 'Fact row follows a process across milestones (order→ship→pay) and is updated — typical for cycle times.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'snapshot-fact', 'label' => ['de' => 'Snapshot Fact', 'en' => 'Snapshot Fact']],
            ['type' => 'glossary', 'id' => 'star-schema', 'label' => ['de' => 'Star Schema', 'en' => 'Star Schema']],
            ['type' => 'glossary', 'id' => 'late-arriving-fact', 'label' => ['de' => 'Late-Arriving Fact', 'en' => 'Late-Arriving Fact']],
        ],
    ],
    [
        'id' => 'scd1',
        'order' => 722,
        'category' => 'modeling',
        'term' => ['de' => 'SCD Type 1', 'en' => 'SCD Type 1'],
        'aliases' => ['SCD1', 'Overwrite SCD'],
        'definition' => [
            'de' => 'Dimensionsattribut wird überschrieben — Historie geht verloren, geeignet für Korrekturen ohne Analysebedarf.',
            'en' => 'Dimension attribute is overwritten — history is lost, suitable for corrections with no analysis need.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'slowly-changing-dimension', 'label' => ['de' => 'SCD', 'en' => 'SCD']],
            ['type' => 'glossary', 'id' => 'scd2', 'label' => ['de' => 'SCD2', 'en' => 'SCD2']],
            ['type' => 'glossary', 'id' => 'surrogate-key', 'label' => ['de' => 'Surrogate Key', 'en' => 'Surrogate Key']],
        ],
    ],
    [
        'id' => 'late-arriving-fact',
        'order' => 723,
        'category' => 'modeling',
        'term' => ['de' => 'Late-Arriving Fact', 'en' => 'Late-Arriving Fact'],
        'aliases' => ['Delayed Fact', 'Late Fact'],
        'definition' => [
            'de' => 'Fact erscheint nach dem erwarteten Ladezeitpunkt — Pipelines müssen Backfill/Replay und Dimensions-Keys sauber handhaben.',
            'en' => 'Fact appears after the expected load time — pipelines must handle backfill/replay and dimension keys cleanly.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'late-arriving-dimension', 'label' => ['de' => 'Late-Arriving Dimension', 'en' => 'Late-Arriving Dimension']],
            ['type' => 'glossary', 'id' => 'backfill', 'label' => ['de' => 'Backfill', 'en' => 'Backfill']],
            ['type' => 'glossary', 'id' => 'replay', 'label' => ['de' => 'Replay', 'en' => 'Replay']],
        ],
    ],
    [
        'id' => 'aggregation-table',
        'order' => 920,
        'category' => 'bi',
        'term' => ['de' => 'Aggregation Table', 'en' => 'Aggregation Table'],
        'aliases' => ['Agg Table', 'Pre-Aggregation'],
        'definition' => [
            'de' => 'Vorberechnete Zusammenfassung auf höherem Grain — beschleunigt Reports, muss zur Detailquelle konsistent bleiben.',
            'en' => 'Precomputed summary at a coarser grain — speeds reports, must stay consistent with detail source.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'incremental-refresh', 'label' => ['de' => 'Incremental Refresh', 'en' => 'Incremental Refresh']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
            ['type' => 'glossary', 'id' => 'composite-model', 'label' => ['de' => 'Composite Model', 'en' => 'Composite Model']],
        ],
    ],
    [
        'id' => 'direct-lake',
        'order' => 921,
        'category' => 'bi',
        'term' => ['de' => 'Direct Lake', 'en' => 'Direct Lake'],
        'aliases' => ['Fabric Direct Lake', 'Lake Mode'],
        'definition' => [
            'de' => 'BI liest Parquet/Delta im Lake ohne klassischen Import — frisch wie DirectQuery, oft schneller als reiner Warehouse-Import.',
            'en' => 'BI reads Parquet/Delta in the lake without classic import — fresh like DirectQuery, often faster than pure warehouse import.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'directquery', 'label' => ['de' => 'DirectQuery', 'en' => 'DirectQuery']],
            ['type' => 'glossary', 'id' => 'import-mode', 'label' => ['de' => 'Import Mode', 'en' => 'Import Mode']],
            ['type' => 'glossary', 'id' => 'delta-lake', 'label' => ['de' => 'Delta Lake', 'en' => 'Delta Lake']],
        ],
    ],
    [
        'id' => 'object-level-security',
        'order' => 922,
        'category' => 'bi',
        'term' => ['de' => 'Object-Level Security', 'en' => 'Object-Level Security'],
        'aliases' => ['OLS', 'Table/Column Security'],
        'definition' => [
            'de' => 'Verbirgt Tabellen/Spalten/Measures vor Rollen — ergänzt RLS (Zeilen), ersetzt sie nicht.',
            'en' => 'Hides tables/columns/measures from roles — complements RLS (rows), does not replace it.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'row-level-security', 'label' => ['de' => 'RLS', 'en' => 'RLS']],
            ['type' => 'glossary', 'id' => 'rbac', 'label' => ['de' => 'RBAC', 'en' => 'RBAC']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
        ],
    ],
    [
        'id' => 'drillthrough',
        'order' => 923,
        'category' => 'bi',
        'term' => ['de' => 'Drillthrough', 'en' => 'Drillthrough'],
        'aliases' => ['Drill-Through', 'Detail Page'],
        'definition' => [
            'de' => 'Navigation von aggregierter Sicht zu Detailseite mit Kontextfiltern — kein Ersatz für saubere Grain-Definition.',
            'en' => 'Navigation from aggregated view to a detail page with context filters — not a substitute for clean grain definition.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'tooltip-page', 'label' => ['de' => 'Tooltip Page', 'en' => 'Tooltip Page']],
            ['type' => 'glossary', 'id' => 'self-service-bi', 'label' => ['de' => 'Self-Service BI', 'en' => 'Self-Service BI']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
        ],
    ],
    [
        'id' => 'tooltip-page',
        'order' => 924,
        'category' => 'bi',
        'term' => ['de' => 'Tooltip Page', 'en' => 'Tooltip Page'],
        'aliases' => ['Report Tooltip', 'Hover Detail'],
        'definition' => [
            'de' => 'Kleine Report-Seite als Hover-Detail — liefert Kontext ohne Seitenwechsel, sollte schlank bleiben.',
            'en' => 'Small report page as hover detail — gives context without page navigation, should stay lean.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'drillthrough', 'label' => ['de' => 'Drillthrough', 'en' => 'Drillthrough']],
            ['type' => 'glossary', 'id' => 'embedded-analytics', 'label' => ['de' => 'Embedded Analytics', 'en' => 'Embedded Analytics']],
        ],
    ],
    [
        'id' => 'what-if-parameter',
        'order' => 925,
        'category' => 'bi',
        'term' => ['de' => 'What-If Parameter', 'en' => 'What-If Parameter'],
        'aliases' => ['What If', 'Scenario Parameter'],
        'definition' => [
            'de' => 'Interaktiver Parameter für Szenarien (z. B. Preis ±10 %) — simuliert, speichert keine Fakten in der Quelle.',
            'en' => 'Interactive parameter for scenarios (e.g. price ±10%) — simulates, does not persist facts in the source.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'field-parameter', 'label' => ['de' => 'Field Parameter', 'en' => 'Field Parameter']],
            ['type' => 'glossary', 'id' => 'calculation-group', 'label' => ['de' => 'Calculation Group', 'en' => 'Calculation Group']],
            ['type' => 'glossary', 'id' => 'dax', 'label' => ['de' => 'DAX', 'en' => 'DAX']],
        ],
    ],
    [
        'id' => 'calculated-column',
        'order' => 926,
        'category' => 'bi',
        'term' => ['de' => 'Calculated Column', 'en' => 'Calculated Column'],
        'aliases' => ['Computed Column', 'Model Column'],
        'definition' => [
            'de' => 'Spalte wird im Modell materialisiert (Row Context) — anders als Measure (Filter Context); speicherintensiv bei großen Tabellen.',
            'en' => 'Column materialized in the model (row context) — unlike a measure (filter context); memory-heavy on large tables.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'dax', 'label' => ['de' => 'DAX', 'en' => 'DAX']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
            ['type' => 'glossary', 'id' => 'import-mode', 'label' => ['de' => 'Import Mode', 'en' => 'Import Mode']],
        ],
    ],
    [
        'id' => 'freshness-sla',
        'order' => 1120,
        'category' => 'quality',
        'term' => ['de' => 'Freshness SLA', 'en' => 'Freshness SLA'],
        'aliases' => ['Data Freshness SLA', 'Latency SLA'],
        'definition' => [
            'de' => 'Zugesicherte maximale Datenalterung bis Nutzung — ohne Messung bleibt „aktuell“ Marketing.',
            'en' => 'Promised maximum data age until use — without measurement, “fresh” is marketing.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-sla', 'label' => ['de' => 'Data SLA', 'en' => 'Data SLA']],
            ['type' => 'glossary', 'id' => 'data-observability', 'label' => ['de' => 'Data Observability', 'en' => 'Data Observability']],
            ['type' => 'glossary', 'id' => 'volume-anomaly', 'label' => ['de' => 'Volume Anomaly', 'en' => 'Volume Anomaly']],
        ],
    ],
    [
        'id' => 'null-rate',
        'order' => 1121,
        'category' => 'quality',
        'term' => ['de' => 'Null Rate', 'en' => 'Null Rate'],
        'aliases' => ['Null Ratio', 'Missingness Rate'],
        'definition' => [
            'de' => 'Anteil fehlender Werte in einer Spalte/Zeitfenster — Frühwarnung für Broken Feeds und Schema-Drift.',
            'en' => 'Share of missing values in a column/time window — early warning for broken feeds and schema drift.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'schema-drift', 'label' => ['de' => 'Schema Drift', 'en' => 'Schema Drift']],
            ['type' => 'glossary', 'id' => 'data-reliability', 'label' => ['de' => 'Data Reliability', 'en' => 'Data Reliability']],
            ['type' => 'glossary', 'id' => 'quarantine-zone', 'label' => ['de' => 'Quarantine Zone', 'en' => 'Quarantine Zone']],
        ],
    ],
    [
        'id' => 'data-diff',
        'order' => 1122,
        'category' => 'quality',
        'term' => ['de' => 'Data Diff', 'en' => 'Data Diff'],
        'aliases' => ['Dataset Diff', 'Row Diff'],
        'definition' => [
            'de' => 'Vergleicht zwei Datensätze/Versionen zeilen- oder aggregatweise — findet Drift nach Refactors und Migrationen.',
            'en' => 'Compares two datasets/versions at row or aggregate level — finds drift after refactors and migrations.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'reconciliation-check', 'label' => ['de' => 'Reconciliation Check', 'en' => 'Reconciliation Check']],
            ['type' => 'glossary', 'id' => 'dataset-versioning', 'label' => ['de' => 'Dataset Versioning', 'en' => 'Dataset Versioning']],
            ['type' => 'glossary', 'id' => 'backfill', 'label' => ['de' => 'Backfill', 'en' => 'Backfill']],
        ],
    ],
    [
        'id' => 'expectation-suite',
        'order' => 1123,
        'category' => 'quality',
        'term' => ['de' => 'Expectation Suite', 'en' => 'Expectation Suite'],
        'aliases' => ['Data Expectations', 'Quality Expectations'],
        'definition' => [
            'de' => 'Versionierte Menge deklarativer Qualitätsregeln (Range, Uniqueness, Referenzen) — Tests als Code, nicht als Ticket-Text.',
            'en' => 'Versioned set of declarative quality rules (range, uniqueness, references) — tests as code, not ticket prose.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
            ['type' => 'glossary', 'id' => 'data-observability', 'label' => ['de' => 'Data Observability', 'en' => 'Data Observability']],
            ['type' => 'glossary', 'id' => 'quarantine-zone', 'label' => ['de' => 'Quarantine Zone', 'en' => 'Quarantine Zone']],
        ],
    ],
    [
        'id' => 'privacy-by-design',
        'order' => 1220,
        'category' => 'privacy',
        'term' => ['de' => 'Privacy by Design', 'en' => 'Privacy by Design'],
        'aliases' => ['Data Protection by Design', 'PbD'],
        'definition' => [
            'de' => 'Datenschutz von Anfang an in Architektur und Prozesse einbauen — nicht als nachträglicher Filter vor dem Go-Live.',
            'en' => 'Build privacy into architecture and process from the start — not as a last filter before go-live.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'purpose-limitation', 'label' => ['de' => 'Purpose Limitation', 'en' => 'Purpose Limitation']],
            ['type' => 'glossary', 'id' => 'data-minimization', 'label' => ['de' => 'Data Minimization', 'en' => 'Data Minimization']],
            ['type' => 'glossary', 'id' => 'dpia', 'label' => ['de' => 'DPIA', 'en' => 'DPIA']],
        ],
    ],
    [
        'id' => 'data-masking',
        'order' => 1221,
        'category' => 'privacy',
        'term' => ['de' => 'Data Masking', 'en' => 'Data Masking'],
        'aliases' => ['Dynamic Masking', 'Static Masking'],
        'definition' => [
            'de' => 'Verdeckt sensible Werte in Nicht-Prod/Self-Service (Hash, Partial, Fake) — kein Ersatz für Zugriffskontrolle in Prod.',
            'en' => 'Obscures sensitive values in non-prod/self-service (hash, partial, fake) — not a substitute for prod access control.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'tokenization', 'label' => ['de' => 'Tokenization', 'en' => 'Tokenization']],
            ['type' => 'glossary', 'id' => 'pseudonymization', 'label' => ['de' => 'Pseudonymization', 'en' => 'Pseudonymization']],
            ['type' => 'glossary', 'id' => 'anonymization', 'label' => ['de' => 'Anonymization', 'en' => 'Anonymization']],
        ],
    ],
    [
        'id' => 'dpia',
        'order' => 1222,
        'category' => 'privacy',
        'term' => ['de' => 'DPIA', 'en' => 'DPIA'],
        'aliases' => ['Data Protection Impact Assessment', 'DSFA'],
        'definition' => [
            'de' => 'Strukturierte Risikoanalyse vor riskanten Verarbeitungen — dokumentiert Maßnahmen, ersetzt keine laufende Kontrolle.',
            'en' => 'Structured risk analysis before high-risk processing — documents mitigations, does not replace ongoing controls.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'privacy-by-design', 'label' => ['de' => 'Privacy by Design', 'en' => 'Privacy by Design']],
            ['type' => 'glossary', 'id' => 'lawful-basis', 'label' => ['de' => 'Lawful Basis', 'en' => 'Lawful Basis']],
            ['type' => 'glossary', 'id' => 'right-to-erasure', 'label' => ['de' => 'Right to Erasure', 'en' => 'Right to Erasure']],
        ],
    ],
    [
        'id' => 'consent-management',
        'order' => 1223,
        'category' => 'privacy',
        'term' => ['de' => 'Consent Management', 'en' => 'Consent Management'],
        'aliases' => ['Consent Platform', 'Einwilligungsverwaltung'],
        'definition' => [
            'de' => 'Erfasst, versioniert und propagiert Einwilligungen maschinenlesbar — Marketing-Opt-in allein reicht nicht als Nachweis.',
            'en' => 'Captures, versions, and propagates consent in machine-readable form — a marketing opt-in alone is not proof.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'consent', 'label' => ['de' => 'Consent', 'en' => 'Consent']],
            ['type' => 'glossary', 'id' => 'purpose-limitation', 'label' => ['de' => 'Purpose Limitation', 'en' => 'Purpose Limitation']],
            ['type' => 'glossary', 'id' => 'retention-schedule', 'label' => ['de' => 'Retention Schedule', 'en' => 'Retention Schedule']],
        ],
    ],
    [
        'id' => 'controller-processor',
        'order' => 1224,
        'category' => 'privacy',
        'term' => ['de' => 'Controller vs Processor', 'en' => 'Controller vs Processor'],
        'aliases' => ['Data Controller', 'Data Processor', 'Verantwortlicher vs Auftragsverarbeiter'],
        'definition' => [
            'de' => 'Controller bestimmt Zwecke/Mittel; Processor verarbeitet weisungsgebunden — Verwechslung kostet Verträge und Haftung.',
            'en' => 'Controller decides purposes/means; processor acts on instructions — mixing them up costs contracts and liability.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
            ['type' => 'glossary', 'id' => 'lawful-basis', 'label' => ['de' => 'Lawful Basis', 'en' => 'Lawful Basis']],
            ['type' => 'glossary', 'id' => 'dpia', 'label' => ['de' => 'DPIA', 'en' => 'DPIA']],
        ],
    ],
    [
        'id' => 'privileged-access-management',
        'order' => 1320,
        'category' => 'security',
        'term' => ['de' => 'Privileged Access Management', 'en' => 'Privileged Access Management'],
        'aliases' => ['PAM', 'Privileged Access'],
        'definition' => [
            'de' => 'Steuert und überwacht hochprivilegierte Konten (Admin, Break-Glass) — Just-in-Time statt Dauer-Admin.',
            'en' => 'Controls and monitors highly privileged accounts (admin, break-glass) — just-in-time instead of standing admin.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'jit-access', 'label' => ['de' => 'JIT Access', 'en' => 'JIT Access']],
            ['type' => 'glossary', 'id' => 'least-privilege', 'label' => ['de' => 'Least Privilege', 'en' => 'Least Privilege']],
            ['type' => 'glossary', 'id' => 'break-glass-access', 'label' => ['de' => 'Break-Glass', 'en' => 'Break-Glass']],
        ],
    ],
    [
        'id' => 'service-account',
        'order' => 1321,
        'category' => 'security',
        'term' => ['de' => 'Service Account', 'en' => 'Service Account'],
        'aliases' => ['Workload Identity', 'Tech User'],
        'definition' => [
            'de' => 'Nicht-menschliche Identität für Pipelines/Apps — braucht Rotation, Scope und Owner, kein geteiltes Passwort im Wiki.',
            'en' => 'Non-human identity for pipelines/apps — needs rotation, scope, and an owner, not a shared wiki password.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'secrets-management', 'label' => ['de' => 'Secrets Management', 'en' => 'Secrets Management']],
            ['type' => 'glossary', 'id' => 'least-privilege', 'label' => ['de' => 'Least Privilege', 'en' => 'Least Privilege']],
            ['type' => 'glossary', 'id' => 'mfa', 'label' => ['de' => 'MFA', 'en' => 'MFA']],
        ],
    ],
    [
        'id' => 'break-glass-access',
        'order' => 1322,
        'category' => 'security',
        'term' => ['de' => 'Break-Glass Access', 'en' => 'Break-Glass Access'],
        'aliases' => ['Emergency Access', 'Break Glass'],
        'definition' => [
            'de' => 'Zeitlich begrenzter Notfallzugriff mit Audit — Ausnahme, die danach reviewed wird, kein Alltagspfad.',
            'en' => 'Time-boxed emergency access with audit — an exception reviewed afterward, not an everyday path.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'jit-access', 'label' => ['de' => 'JIT Access', 'en' => 'JIT Access']],
            ['type' => 'glossary', 'id' => 'privileged-access-management', 'label' => ['de' => 'PAM', 'en' => 'PAM']],
            ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
        ],
    ],
    [
        'id' => 'blue-green-deployment',
        'order' => 1445,
        'category' => 'process',
        'term' => ['de' => 'Blue-Green Deployment', 'en' => 'Blue-Green Deployment'],
        'aliases' => ['Blue/Green', 'Blue Green Release'],
        'definition' => [
            'de' => 'Zwei parallele Environments; Traffic wechselt atomar — schneller Rollback als schrittweises Patchen live.',
            'en' => 'Two parallel environments; traffic switches atomically — faster rollback than patching live step by step.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'canary-release', 'label' => ['de' => 'Canary Release', 'en' => 'Canary Release']],
            ['type' => 'glossary', 'id' => 'shadow-deployment', 'label' => ['de' => 'Shadow Deployment', 'en' => 'Shadow Deployment']],
            ['type' => 'glossary', 'id' => 'feature-flag', 'label' => ['de' => 'Feature Flag', 'en' => 'Feature Flag']],
        ],
    ],
    [
        'id' => 'blameless-postmortem',
        'order' => 1446,
        'category' => 'process',
        'term' => ['de' => 'Blameless Postmortem', 'en' => 'Blameless Postmortem'],
        'aliases' => ['Blameless Retro', 'Incident Review'],
        'definition' => [
            'de' => 'Nach Incidents Ursachen und Systemfixücken analysieren ohne Schuldzuweisung — Fokus auf Fixes und Learning.',
            'en' => 'After incidents, analyze causes and system gaps without blame — focus on fixes and learning.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'runbook', 'label' => ['de' => 'Runbook', 'en' => 'Runbook']],
            ['type' => 'glossary', 'id' => 'error-budget', 'label' => ['de' => 'Error Budget', 'en' => 'Error Budget']],
            ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
        ],
    ],
    [
        'id' => 'runbook',
        'order' => 1447,
        'category' => 'process',
        'term' => ['de' => 'Runbook', 'en' => 'Runbook'],
        'aliases' => ['Playbook Ops', 'Ops Runbook'],
        'definition' => [
            'de' => 'Schrittte Schritte für Betrieb/Incident (Checks, Rollback, Kontakte) — lebendiges Dokument, kein einmaliges Wiki.',
            'en' => 'Concrete steps for ops/incident (checks, rollback, contacts) — a living document, not a one-off wiki page.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'blameless-postmortem', 'label' => ['de' => 'Blameless Postmortem', 'en' => 'Blameless Postmortem']],
            ['type' => 'glossary', 'id' => 'toil', 'label' => ['de' => 'Toil', 'en' => 'Toil']],
            ['type' => 'glossary', 'id' => 'golden-path', 'label' => ['de' => 'Golden Path', 'en' => 'Golden Path']],
        ],
    ],
    [
        'id' => 'wip-limit',
        'order' => 1448,
        'category' => 'process',
        'term' => ['de' => 'WIP Limit', 'en' => 'WIP Limit'],
        'aliases' => ['Work-in-Progress Limit', 'Kanban WIP'],
        'definition' => [
            'de' => 'Obergrenze paralleler Arbeit — schützt Durchsatz und Qualität, auch in Data/BI-Backlogs.',
            'en' => 'Cap on parallel work — protects throughput and quality, including in data/BI backlogs.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'value-stream-mapping', 'label' => ['de' => 'Value Stream Mapping', 'en' => 'Value Stream Mapping']],
            ['type' => 'glossary', 'id' => 'definition-of-done', 'label' => ['de' => 'Definition of Done', 'en' => 'Definition of Done']],
            ['type' => 'glossary', 'id' => 'toil', 'label' => ['de' => 'Toil', 'en' => 'Toil']],
        ],
    ],
    [
        'id' => 'definition-of-done',
        'order' => 1449,
        'category' => 'process',
        'term' => ['de' => 'Definition of Done', 'en' => 'Definition of Done'],
        'aliases' => ['DoD', 'Done Criteria'],
        'definition' => [
            'de' => 'Gemeinsame Fertig-Kriterien (Tests, Docs, Owner, Monitoring) — „fertig“ ohne DoD ist nur lokal „fertig“.',
            'en' => 'Shared done criteria (tests, docs, owner, monitoring) — “done” without a DoD is only locally done.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'wip-limit', 'label' => ['de' => 'WIP Limit', 'en' => 'WIP Limit']],
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
            ['type' => 'glossary', 'id' => 'runbook', 'label' => ['de' => 'Runbook', 'en' => 'Runbook']],
        ],
    ],
    [
        'id' => 'vector-database',
        'order' => 1687,
        'category' => 'ai',
        'term' => ['de' => 'Vector Database', 'en' => 'Vector Database'],
        'aliases' => ['Vector DB', 'Embedding Store'],
        'definition' => [
            'de' => 'Speichert Embeddings und sucht nach Ähnlichkeit — Basis für RAG, kein Ersatz für relationale Wahrheit.',
            'en' => 'Stores embeddings and searches by similarity — foundation for RAG, not a substitute for relational truth.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'embedding', 'label' => ['de' => 'Embedding', 'en' => 'Embedding']],
            ['type' => 'glossary', 'id' => 'rag', 'label' => ['de' => 'RAG', 'en' => 'RAG']],
            ['type' => 'glossary', 'id' => 'vector-search', 'label' => ['de' => 'Vector Search', 'en' => 'Vector Search']],
        ],
    ],
    [
        'id' => 'temperature',
        'order' => 1688,
        'category' => 'ai',
        'term' => ['de' => 'Temperature', 'en' => 'Temperature'],
        'aliases' => ['Sampling Temperature', 'LLM Temperature'],
        'definition' => [
            'de' => 'Steuert Zufälligkeit der Token-Auswahl — niedrig = deterministischer, hoch = kreativer/fehleranfälliger.',
            'en' => 'Controls randomness of token sampling — low = more deterministic, high = more creative/error-prone.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'hallucination', 'label' => ['de' => 'Hallucination', 'en' => 'Hallucination']],
            ['type' => 'glossary', 'id' => 'structured-output', 'label' => ['de' => 'Structured Output', 'en' => 'Structured Output']],
            ['type' => 'glossary', 'id' => 'few-shot-prompting', 'label' => ['de' => 'Few-Shot Prompting', 'en' => 'Few-Shot Prompting']],
        ],
    ],
    [
        'id' => 'ai-act',
        'order' => 1689,
        'category' => 'ai',
        'term' => ['de' => 'AI Act', 'en' => 'AI Act'],
        'aliases' => ['EU AI Act', 'Artificial Intelligence Act'],
        'definition' => [
            'de' => 'EU-Regulierung mit risikobasierten Pflichten für KI-Systeme — Governance und Dokumentation werden Pflicht, nicht Nice-to-have.',
            'en' => 'EU regulation with risk-based duties for AI systems — governance and documentation become mandatory, not optional.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'model-card', 'label' => ['de' => 'Model Card', 'en' => 'Model Card']],
            ['type' => 'glossary', 'id' => 'ai-guardrails', 'label' => ['de' => 'AI Guardrails', 'en' => 'AI Guardrails']],
            ['type' => 'glossary', 'id' => 'human-in-the-loop', 'label' => ['de' => 'Human-in-the-Loop', 'en' => 'Human-in-the-Loop']],
        ],
    ],
    [
        'id' => 'multi-agent-system',
        'order' => 1690,
        'category' => 'ai',
        'term' => ['de' => 'Multi-Agent System', 'en' => 'Multi-Agent System'],
        'aliases' => ['Multi-Agent', 'Agent Swarm'],
        'definition' => [
            'de' => 'Mehrere spezialisierte Agents koordinieren Aufgaben — braucht klare Rollen, Shared State und Abbruchregeln.',
            'en' => 'Multiple specialized agents coordinate tasks — needs clear roles, shared state, and stop rules.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'agentic-workflow', 'label' => ['de' => 'Agentic Workflow', 'en' => 'Agentic Workflow']],
            ['type' => 'glossary', 'id' => 'tool-calling', 'label' => ['de' => 'Tool Calling', 'en' => 'Tool Calling']],
            ['type' => 'glossary', 'id' => 'model-context-protocol', 'label' => ['de' => 'MCP', 'en' => 'MCP']],
        ],
    ],
    [
        'id' => 'eval-harness',
        'order' => 1691,
        'category' => 'ai',
        'term' => ['de' => 'Eval Harness', 'en' => 'Eval Harness'],
        'aliases' => ['Evaluation Harness', 'LLM Eval Suite'],
        'definition' => [
            'de' => 'Wiederholbare Testbatterie für LLM-/Agent-Qualität (Golden Sets, Scorer) — ohne Evals ist „besser“ nur Gefühl.',
            'en' => 'Repeatable test battery for LLM/agent quality (golden sets, scorers) — without evals, “better” is only a feeling.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'red-teaming', 'label' => ['de' => 'Red Teaming', 'en' => 'Red Teaming']],
            ['type' => 'glossary', 'id' => 'model-card', 'label' => ['de' => 'Model Card', 'en' => 'Model Card']],
            ['type' => 'glossary', 'id' => 'hallucination', 'label' => ['de' => 'Hallucination', 'en' => 'Hallucination']],
        ],
    ],
    [
        'id' => 'red-teaming',
        'order' => 1692,
        'category' => 'ai',
        'term' => ['de' => 'Red Teaming', 'en' => 'Red Teaming'],
        'aliases' => ['AI Red Team', 'Adversarial Testing'],
        'definition' => [
            'de' => 'Gezieltes Angreifen von Modellen/Agents (Jailbreak, Injection, Bias) — findet Lücken vor produktiven Nutzern.',
            'en' => 'Deliberately attacking models/agents (jailbreak, injection, bias) — finds gaps before production users do.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'jailbreak', 'label' => ['de' => 'Jailbreak', 'en' => 'Jailbreak']],
            ['type' => 'glossary', 'id' => 'prompt-injection', 'label' => ['de' => 'Prompt Injection', 'en' => 'Prompt Injection']],
            ['type' => 'glossary', 'id' => 'ai-guardrails', 'label' => ['de' => 'AI Guardrails', 'en' => 'AI Guardrails']],
        ],
    ],
];
