<?php

/**
 * Glossary buzzword wave 7 — quiz-friendly terms (distinct defs, clear categories).
 *
 * @return list<array<string, mixed>>
 */
return [
  [
    'id' => 'chief-analytics-officer',
    'order' => 69,
    'category' => 'roles',
    'term' => ['de' => 'Chief Analytics Officer', 'en' => 'Chief Analytics Officer'],
    'aliases' => ['CAO', 'Analytics Executive'],
    'definition' => [
      'de' => 'Executive für Analytics-Strategie und ROI — verantwortet Insights-Nutzung, nicht nur Tool-Budgets.',
      'en' => 'Executive for analytics strategy and ROI — owns insight adoption, not just tool budgets.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'chief-data-officer', 'label' => ['de' => 'CDO', 'en' => 'CDO']],
      ['type' => 'glossary', 'id' => 'data-product-owner', 'label' => ['de' => 'Data Product Owner', 'en' => 'Data Product Owner']],
      ['type' => 'glossary', 'id' => 'self-service-bi', 'label' => ['de' => 'Self-Service BI', 'en' => 'Self-Service BI']],
    ],
  ],
  [
    'id' => 'data-engineering-manager',
    'order' => 70,
    'category' => 'roles',
    'term' => ['de' => 'Data Engineering Manager', 'en' => 'Data Engineering Manager'],
    'aliases' => ['DE Manager', 'Pipeline Team Lead'],
    'definition' => [
      'de' => 'Führt Data-Engineering-Teams und priorisiert Plattform vs. Feature-Work — People + Delivery, weniger Hands-on-SQL.',
      'en' => 'Leads data engineering teams and prioritizes platform vs. feature work — people + delivery, less hands-on SQL.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-engineer', 'label' => ['de' => 'Data Engineer', 'en' => 'Data Engineer']],
      ['type' => 'glossary', 'id' => 'platform-engineer', 'label' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer']],
      ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
    ],
  ],
  [
    'id' => 'governance-analyst',
    'order' => 71,
    'category' => 'roles',
    'term' => ['de' => 'Governance Analyst', 'en' => 'Governance Analyst'],
    'aliases' => ['Data Governance Analyst', 'Policy Analyst'],
    'definition' => [
      'de' => 'Operationalisiert Policies, Workflows und Metadaten-Standards — Brücke zwischen Legal/Compliance und Engineering.',
      'en' => 'Operationalizes policies, workflows, and metadata standards — bridge between legal/compliance and engineering.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-steward', 'label' => ['de' => 'Data Steward', 'en' => 'Data Steward']],
      ['type' => 'glossary', 'id' => 'business-glossary', 'label' => ['de' => 'Business Glossary', 'en' => 'Business Glossary']],
      ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
    ],
  ],
  [
    'id' => 'privacy-engineer',
    'order' => 72,
    'category' => 'roles',
    'term' => ['de' => 'Privacy Engineer', 'en' => 'Privacy Engineer'],
    'aliases' => ['Privacy Tech Engineer', 'DPO Tech Partner'],
    'definition' => [
      'de' => 'Implementiert Privacy-by-Design in Pipelines und APIs — technische Umsetzung von Consent, Retention und Access.',
      'en' => 'Implements privacy-by-design in pipelines and APIs — technical execution of consent, retention, and access.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'privacy-by-design', 'label' => ['de' => 'Privacy by Design', 'en' => 'Privacy by Design']],
      ['type' => 'glossary', 'id' => 'gdpr', 'label' => ['de' => 'GDPR', 'en' => 'GDPR']],
      ['type' => 'glossary', 'id' => 'pii', 'label' => ['de' => 'PII', 'en' => 'PII']],
    ],
  ],
  [
    'id' => 'security-engineer',
    'order' => 73,
    'category' => 'roles',
    'term' => ['de' => 'Security Engineer', 'en' => 'Security Engineer'],
    'aliases' => ['AppSec Engineer', 'Data Security Engineer'],
    'definition' => [
      'de' => 'Baut sichere Defaults in Datenplattformen (IAM, Encryption, Secrets) — nicht nur Pen-Test-Tickets abarbeiten.',
      'en' => 'Builds secure defaults into data platforms (IAM, encryption, secrets) — not just closing pen-test tickets.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
      ['type' => 'glossary', 'id' => 'encryption', 'label' => ['de' => 'Encryption', 'en' => 'Encryption']],
      ['type' => 'glossary', 'id' => 'threat-modeling', 'label' => ['de' => 'Threat Modeling', 'en' => 'Threat Modeling']],
    ],
  ],
  [
    'id' => 'data-product-roadmap',
    'order' => 256,
    'category' => 'data',
    'term' => ['de' => 'Data Product Roadmap', 'en' => 'Data Product Roadmap'],
    'aliases' => ['Product Roadmap', 'Data Portfolio Plan'],
    'definition' => [
      'de' => 'Zeitplan für Data-Product-Features und Abhängigkeiten — verbindet Business Outcomes mit Pipeline-/Model-Work.',
      'en' => 'Timeline for data product features and dependencies — links business outcomes to pipeline/model work.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-product', 'label' => ['de' => 'Data Product', 'en' => 'Data Product']],
      ['type' => 'glossary', 'id' => 'data-product-owner', 'label' => ['de' => 'Data Product Owner', 'en' => 'Data Product Owner']],
      ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
    ],
  ],
  [
    'id' => 'data-usage-metrics',
    'order' => 257,
    'category' => 'data',
    'term' => ['de' => 'Data Usage Metrics', 'en' => 'Data Usage Metrics'],
    'aliases' => ['Consumption Metrics', 'Query Volume Metrics'],
    'definition' => [
      'de' => 'Kennzahlen zu Queries, Downloads und Dashboard-Nutzung — zeigt Wert und Hotspots, nicht nur Speichergröße.',
      'en' => 'Metrics on queries, downloads, and dashboard use — shows value and hotspots, not just storage size.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
      ['type' => 'glossary', 'id' => 'finops', 'label' => ['de' => 'FinOps', 'en' => 'FinOps']],
      ['type' => 'glossary', 'id' => 'data-product', 'label' => ['de' => 'Data Product', 'en' => 'Data Product']],
    ],
  ],
  [
    'id' => 'data-consumption-pattern',
    'order' => 258,
    'category' => 'data',
    'term' => ['de' => 'Data Consumption Pattern', 'en' => 'Data Consumption Pattern'],
    'aliases' => ['Access Pattern', 'Usage Pattern'],
    'definition' => [
      'de' => 'Typisches Lesemuster (Batch vs. Streaming, OLAP vs. API) — treibt Caching, Partitionierung und Kosten.',
      'en' => 'Typical read pattern (batch vs. streaming, OLAP vs. API) — drives caching, partitioning, and cost.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-lake', 'label' => ['de' => 'Data Lake', 'en' => 'Data Lake']],
      ['type' => 'glossary', 'id' => 'semantic-layer', 'label' => ['de' => 'Semantic Layer', 'en' => 'Semantic Layer']],
      ['type' => 'glossary', 'id' => 'api-gateway', 'label' => ['de' => 'API Gateway', 'en' => 'API Gateway']],
    ],
  ],
  [
    'id' => 'data-provenance',
    'order' => 259,
    'category' => 'data',
    'term' => ['de' => 'Data Provenance', 'en' => 'Data Provenance'],
    'aliases' => ['Origin Tracking', 'Source Provenance'],
    'definition' => [
      'de' => 'Nachverfolgung der Herkunft und Transformationen eines Datensatzes — Grundlage für Trust und Audit.',
      'en' => 'Tracking origin and transformations of a dataset — foundation for trust and audit.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'lineage', 'label' => ['de' => 'Lineage', 'en' => 'Lineage']],
      ['type' => 'glossary', 'id' => 'metadata', 'label' => ['de' => 'Metadata', 'en' => 'Metadata']],
      ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
    ],
  ],
  [
    'id' => 'data-provenance-chain',
    'order' => 260,
    'category' => 'data',
    'term' => ['de' => 'Data Provenance Chain', 'en' => 'Data Provenance Chain'],
    'aliases' => ['Provenance Trail', 'Chain of Custody'],
    'definition' => [
      'de' => 'Lückenlose Kette von Quellen, Jobs und Releases bis zum Report — stärker als einzelne Lineage-Snapshots.',
      'en' => 'Continuous chain of sources, jobs, and releases to the report — stronger than isolated lineage snapshots.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-provenance', 'label' => ['de' => 'Data Provenance', 'en' => 'Data Provenance']],
      ['type' => 'glossary', 'id' => 'lineage', 'label' => ['de' => 'Lineage', 'en' => 'Lineage']],
      ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
    ],
  ],
  [
    'id' => 'message-broker',
    'order' => 461,
    'category' => 'architecture',
    'term' => ['de' => 'Message Broker', 'en' => 'Message Broker'],
    'aliases' => ['Event Broker', 'Queue Broker'],
    'definition' => [
      'de' => 'Middleware für asynchrone Nachrichten (Topics/Queues) — entkoppelt Producer und Consumer in Event-Architekturen.',
      'en' => 'Middleware for async messages (topics/queues) — decouples producers and consumers in event architectures.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'event-sourcing', 'label' => ['de' => 'Event Sourcing', 'en' => 'Event Sourcing']],
      ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
      ['type' => 'glossary', 'id' => 'api-gateway', 'label' => ['de' => 'API Gateway', 'en' => 'API Gateway']],
    ],
  ],
  [
    'id' => 'event-choreography',
    'order' => 462,
    'category' => 'architecture',
    'term' => ['de' => 'Event Choreography', 'en' => 'Event Choreography'],
    'aliases' => ['Choreographed Events', 'Decentralized Saga'],
    'definition' => [
      'de' => 'Services reagieren auf Events ohne zentralen Orchestrator — flexibel, aber schwerer zu debuggen als Orchestration.',
      'en' => 'Services react to events without central orchestrator — flexible but harder to debug than orchestration.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'event-orchestration', 'label' => ['de' => 'Event Orchestration', 'en' => 'Event Orchestration']],
      ['type' => 'glossary', 'id' => 'saga-pattern', 'label' => ['de' => 'Saga Pattern', 'en' => 'Saga Pattern']],
      ['type' => 'glossary', 'id' => 'bounded-context', 'label' => ['de' => 'Bounded Context', 'en' => 'Bounded Context']],
    ],
  ],
  [
    'id' => 'event-orchestration',
    'order' => 463,
    'category' => 'architecture',
    'term' => ['de' => 'Event Orchestration', 'en' => 'Event Orchestration'],
    'aliases' => ['Orchestrated Workflow', 'Central Coordinator'],
    'definition' => [
      'de' => 'Zentraler Koordinator steuert Schritte und Retries über Services — einfacher zu überwachen als pure Choreography.',
      'en' => 'Central coordinator drives steps and retries across services — easier to monitor than pure choreography.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'event-choreography', 'label' => ['de' => 'Event Choreography', 'en' => 'Event Choreography']],
      ['type' => 'glossary', 'id' => 'saga-orchestrator', 'label' => ['de' => 'Saga Orchestrator', 'en' => 'Saga Orchestrator']],
      ['type' => 'glossary', 'id' => 'saga-pattern', 'label' => ['de' => 'Saga Pattern', 'en' => 'Saga Pattern']],
    ],
  ],
  [
    'id' => 'saga-orchestrator',
    'order' => 464,
    'category' => 'architecture',
    'term' => ['de' => 'Saga Orchestrator', 'en' => 'Saga Orchestrator'],
    'aliases' => ['Saga Coordinator', 'Workflow Orchestrator'],
    'definition' => [
      'de' => 'Komponente, die verteilte Transaktionen als Saga mit compensating actions ausführt — typisch in Microservice-Stacks.',
      'en' => 'Component running distributed transactions as sagas with compensating actions — common in microservice stacks.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'saga-pattern', 'label' => ['de' => 'Saga Pattern', 'en' => 'Saga Pattern']],
      ['type' => 'glossary', 'id' => 'event-orchestration', 'label' => ['de' => 'Event Orchestration', 'en' => 'Event Orchestration']],
      ['type' => 'glossary', 'id' => 'api-gateway', 'label' => ['de' => 'API Gateway', 'en' => 'API Gateway']],
    ],
  ],
  [
    'id' => 'warm-standby',
    'order' => 465,
    'category' => 'architecture',
    'term' => ['de' => 'Warm Standby', 'en' => 'Warm Standby'],
    'aliases' => ['Warm Standby Replica', 'Hot Standby Cousin'],
    'definition' => [
      'de' => 'Standby-System ist vorbereitet und schnell startbar — Balance zwischen Kosten und Recovery-Zeit vs. Cold Standby.',
      'en' => 'Standby system is prepared and quick to start — balance between cost and recovery time vs. cold standby.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'active-active', 'label' => ['de' => 'Active-Active', 'en' => 'Active-Active']],
      ['type' => 'glossary', 'id' => 'geo-replication', 'label' => ['de' => 'Geo-Replication', 'en' => 'Geo-Replication']],
      ['type' => 'glossary', 'id' => 'rto', 'label' => ['de' => 'RTO', 'en' => 'RTO']],
    ],
  ],
  [
    'id' => 'staging-area',
    'order' => 661,
    'category' => 'modeling',
    'term' => ['de' => 'Staging Area', 'en' => 'Staging Area'],
    'aliases' => ['Staging Zone', 'Landing Staging'],
    'definition' => [
      'de' => 'Zwischenbereich für Roh- oder leicht transformierte Daten vor dem Core Model — trennt Ingest von Business-Logik.',
      'en' => 'Intermediate zone for raw or lightly transformed data before core model — separates ingest from business logic.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'bronze-layer', 'label' => ['de' => 'Bronze Layer', 'en' => 'Bronze Layer']],
      ['type' => 'glossary', 'id' => 'persistent-staging', 'label' => ['de' => 'Persistent Staging', 'en' => 'Persistent Staging']],
      ['type' => 'glossary', 'id' => 'etl', 'label' => ['de' => 'ETL', 'en' => 'ETL']],
    ],
  ],
  [
    'id' => 'persistent-staging',
    'order' => 662,
    'category' => 'modeling',
    'term' => ['de' => 'Persistent Staging', 'en' => 'Persistent Staging'],
    'aliases' => ['PSA', 'Persistent Staging Area'],
    'definition' => [
      'de' => 'Staging bleibt historisiert erhalten — ermöglicht Rebuilds und Audit ohne erneuten Source-Pull.',
      'en' => 'Staging kept with history — enables rebuilds and audit without re-pulling sources.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'staging-area', 'label' => ['de' => 'Staging Area', 'en' => 'Staging Area']],
      ['type' => 'glossary', 'id' => 'data-vault', 'label' => ['de' => 'Data Vault', 'en' => 'Data Vault']],
      ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
    ],
  ],
  [
    'id' => 'incremental-pipeline',
    'order' => 663,
    'category' => 'modeling',
    'term' => ['de' => 'Incremental Pipeline', 'en' => 'Incremental Pipeline'],
    'aliases' => ['Incremental Load Pipeline', 'Delta Pipeline'],
    'definition' => [
      'de' => 'Verarbeitet nur neue/geänderte Daten seit letztem Run — Standard für Skalierung, braucht saubere Keys und Watermarks.',
      'en' => 'Processes only new/changed data since last run — standard for scale, needs clean keys and watermarks.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
      ['type' => 'glossary', 'id' => 'elt', 'label' => ['de' => 'ELT', 'en' => 'ELT']],
      ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
    ],
  ],
  [
    'id' => 'ragged-hierarchy',
    'order' => 664,
    'category' => 'modeling',
    'term' => ['de' => 'Ragged Hierarchy', 'en' => 'Ragged Hierarchy'],
    'aliases' => ['Unbalanced Hierarchy Path', 'Skipped Levels'],
    'definition' => [
      'de' => 'Hierarchie mit unterschiedlichen Tiefen (Level übersprungen) — z. B. Region ohne Zwischen-Country-Knoten.',
      'en' => 'Hierarchy with varying depths (levels skipped) — e.g. region without intermediate country node.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'unbalanced-hierarchy', 'label' => ['de' => 'Unbalanced Hierarchy', 'en' => 'Unbalanced Hierarchy']],
      ['type' => 'glossary', 'id' => 'parent-child-hierarchy', 'label' => ['de' => 'Parent-Child Hierarchy', 'en' => 'Parent-Child Hierarchy']],
      ['type' => 'glossary', 'id' => 'star-schema', 'label' => ['de' => 'Star Schema', 'en' => 'Star Schema']],
    ],
  ],
  [
    'id' => 'unbalanced-hierarchy',
    'order' => 665,
    'category' => 'modeling',
    'term' => ['de' => 'Unbalanced Hierarchy', 'en' => 'Unbalanced Hierarchy'],
    'aliases' => ['Uneven Hierarchy', 'Variable Depth Tree'],
    'definition' => [
      'de' => 'Knoten haben unterschiedliche Kinder-Tiefen — Reporting und Drill müssen Parent-Child-Pfade explizit modellieren.',
      'en' => 'Nodes have different child depths — reporting and drill must model parent-child paths explicitly.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'ragged-hierarchy', 'label' => ['de' => 'Ragged Hierarchy', 'en' => 'Ragged Hierarchy']],
      ['type' => 'glossary', 'id' => 'hierarchy-path', 'label' => ['de' => 'Hierarchy Path', 'en' => 'Hierarchy Path']],
      ['type' => 'glossary', 'id' => 'semantic-layer', 'label' => ['de' => 'Semantic Layer', 'en' => 'Semantic Layer']],
    ],
  ],
  [
    'id' => 'report-book',
    'order' => 861,
    'category' => 'bi',
    'term' => ['de' => 'Report Book', 'en' => 'Report Book'],
    'aliases' => ['Report Pack', 'Paginated Book'],
    'definition' => [
      'de' => 'Gebündelte Report-Sammlung mit gemeinsamer Navigation — typisch für PDF/Print-Compliance-Pakete.',
      'en' => 'Bundled report collection with shared navigation — typical for PDF/print compliance packs.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'paginated-report', 'label' => ['de' => 'Paginated Report', 'en' => 'Paginated Report']],
      ['type' => 'glossary', 'id' => 'dashboard', 'label' => ['de' => 'Dashboard', 'en' => 'Dashboard']],
      ['type' => 'glossary', 'id' => 'report-subscription-email', 'label' => ['de' => 'Report Subscription Email', 'en' => 'Report Subscription Email']],
    ],
  ],
  [
    'id' => 'mobile-bi',
    'order' => 862,
    'category' => 'bi',
    'term' => ['de' => 'Mobile BI', 'en' => 'Mobile BI'],
    'aliases' => ['Mobile Analytics', 'Mobile Dashboards'],
    'definition' => [
      'de' => 'BI für Smartphone/Tablet — Layout, Offline und Row-Level Security müssen für kleine Screens designt sein.',
      'en' => 'BI for phone/tablet — layout, offline, and RLS must be designed for small screens.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'embedded-report', 'label' => ['de' => 'Embedded Report', 'en' => 'Embedded Report']],
      ['type' => 'glossary', 'id' => 'self-service-bi', 'label' => ['de' => 'Self-Service BI', 'en' => 'Self-Service BI']],
      ['type' => 'glossary', 'id' => 'dashboard', 'label' => ['de' => 'Dashboard', 'en' => 'Dashboard']],
    ],
  ],
  [
    'id' => 'embedded-report',
    'order' => 863,
    'category' => 'bi',
    'term' => ['de' => 'Embedded Report', 'en' => 'Embedded Report'],
    'aliases' => ['Embedded Analytics', 'In-App Reporting'],
    'definition' => [
      'de' => 'Report/Dashboard in Produkt-UI eingebettet — braucht Embedding-API, Auth und konsistente Semantic Layer.',
      'en' => 'Report/dashboard embedded in product UI — needs embedding API, auth, and consistent semantic layer.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'semantic-layer', 'label' => ['de' => 'Semantic Layer', 'en' => 'Semantic Layer']],
      ['type' => 'glossary', 'id' => 'api-gateway', 'label' => ['de' => 'API Gateway', 'en' => 'API Gateway']],
      ['type' => 'glossary', 'id' => 'mobile-bi', 'label' => ['de' => 'Mobile BI', 'en' => 'Mobile BI']],
    ],
  ],
  [
    'id' => 'report-subscription-email',
    'order' => 864,
    'category' => 'bi',
    'term' => ['de' => 'Report Subscription Email', 'en' => 'Report Subscription Email'],
    'aliases' => ['Email Subscription', 'Scheduled Email Report'],
    'definition' => [
      'de' => 'Automatischer Report-Versand per E-Mail auf Schedule — Distribution-Layer, nicht Ersatz für interaktives BI.',
      'en' => 'Automated report delivery via email on schedule — distribution layer, not a substitute for interactive BI.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'scheduled-refresh', 'label' => ['de' => 'Scheduled Refresh', 'en' => 'Scheduled Refresh']],
      ['type' => 'glossary', 'id' => 'paginated-report', 'label' => ['de' => 'Paginated Report', 'en' => 'Paginated Report']],
      ['type' => 'glossary', 'id' => 'report-book', 'label' => ['de' => 'Report Book', 'en' => 'Report Book']],
    ],
  ],
  [
    'id' => 'scheduled-refresh',
    'order' => 865,
    'category' => 'bi',
    'term' => ['de' => 'Scheduled Refresh', 'en' => 'Scheduled Refresh'],
    'aliases' => ['Refresh Schedule', 'Dataset Refresh'],
    'definition' => [
      'de' => 'Zeitplan für Daten-Refresh im BI-Tool — SLA für „frische“ Dashboards, oft gekoppelt an Pipeline-SLA.',
      'en' => 'Schedule for data refresh in BI tool — SLA for “fresh” dashboards, often tied to pipeline SLA.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
      ['type' => 'glossary', 'id' => 'semantic-layer', 'label' => ['de' => 'Semantic Layer', 'en' => 'Semantic Layer']],
      ['type' => 'glossary', 'id' => 'report-subscription-email', 'label' => ['de' => 'Report Subscription Email', 'en' => 'Report Subscription Email']],
    ],
  ],
  [
    'id' => 'distribution-check',
    'order' => 1061,
    'category' => 'quality',
    'term' => ['de' => 'Distribution Check', 'en' => 'Distribution Check'],
    'aliases' => ['Distribution Test', 'Histogram Check'],
    'definition' => [
      'de' => 'Prüft, ob Werte-/Kategorie-Verteilung erwartbar ist — frühzeitiger Drift-Alarm vor harten Business-Rule-Fails.',
      'en' => 'Checks whether value/category distribution looks expected — early drift alarm before hard business-rule fails.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-quality', 'label' => ['de' => 'Data Quality', 'en' => 'Data Quality']],
      ['type' => 'glossary', 'id' => 'anomaly-detection-rule', 'label' => ['de' => 'Anomaly Detection Rule', 'en' => 'Anomaly Detection Rule']],
      ['type' => 'glossary', 'id' => 'profiling-job', 'label' => ['de' => 'Profiling Job', 'en' => 'Profiling Job']],
    ],
  ],
  [
    'id' => 'uniqueness-constraint',
    'order' => 1062,
    'category' => 'quality',
    'term' => ['de' => 'Uniqueness Constraint', 'en' => 'Uniqueness Constraint'],
    'aliases' => ['Unique Key Check', 'Duplicate Prevention'],
    'definition' => [
      'de' => 'Regel, dass Schlüssel oder Kombinationen eindeutig sein müssen — Basis für Referential Integrity und Aggregation.',
      'en' => 'Rule that keys or combinations must be unique — basis for referential integrity and aggregation.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'referential-check', 'label' => ['de' => 'Referential Check', 'en' => 'Referential Check']],
      ['type' => 'glossary', 'id' => 'data-quality', 'label' => ['de' => 'Data Quality', 'en' => 'Data Quality']],
      ['type' => 'glossary', 'id' => 'schema-validation', 'label' => ['de' => 'Schema Validation', 'en' => 'Schema Validation']],
    ],
  ],
  [
    'id' => 'referential-check',
    'order' => 1063,
    'category' => 'quality',
    'term' => ['de' => 'Referential Check', 'en' => 'Referential Check'],
    'aliases' => ['FK Check', 'Referential Integrity Check'],
    'definition' => [
      'de' => 'Validiert, dass Fremdschlüssel auf existierende Parent-Rows zeigen — verhindert orphaned Facts in Star Schemas.',
      'en' => 'Validates foreign keys point to existing parent rows — prevents orphaned facts in star schemas.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'uniqueness-constraint', 'label' => ['de' => 'Uniqueness Constraint', 'en' => 'Uniqueness Constraint']],
      ['type' => 'glossary', 'id' => 'star-schema', 'label' => ['de' => 'Star Schema', 'en' => 'Star Schema']],
      ['type' => 'glossary', 'id' => 'data-quality', 'label' => ['de' => 'Data Quality', 'en' => 'Data Quality']],
    ],
  ],
  [
    'id' => 'schema-validation',
    'order' => 1064,
    'category' => 'quality',
    'term' => ['de' => 'Schema Validation', 'en' => 'Schema Validation'],
    'aliases' => ['Schema Check', 'Contract Validation'],
    'definition' => [
      'de' => 'Prüft Spalten, Typen und Pflichtfelder gegen erwartetes Schema — oft Gate vor Lakehouse-Write.',
      'en' => 'Checks columns, types, and required fields against expected schema — often gate before lakehouse write.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
      ['type' => 'glossary', 'id' => 'quality-gate', 'label' => ['de' => 'Quality Gate', 'en' => 'Quality Gate']],
      ['type' => 'glossary', 'id' => 'data-quality', 'label' => ['de' => 'Data Quality', 'en' => 'Data Quality']],
    ],
  ],
  [
    'id' => 'anomaly-detection-rule',
    'order' => 1065,
    'category' => 'quality',
    'term' => ['de' => 'Anomaly Detection Rule', 'en' => 'Anomaly Detection Rule'],
    'aliases' => ['Anomaly Rule', 'Outlier Alert Rule'],
    'definition' => [
      'de' => 'Automatische Regel für ungewöhnliche Werte oder Counts — ergänzt statische Thresholds bei volatilen Metriken.',
      'en' => 'Automated rule for unusual values or counts — complements static thresholds on volatile metrics.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'distribution-check', 'label' => ['de' => 'Distribution Check', 'en' => 'Distribution Check']],
      ['type' => 'glossary', 'id' => 'observability-alert', 'label' => ['de' => 'Observability Alert', 'en' => 'Observability Alert']],
      ['type' => 'glossary', 'id' => 'data-quality', 'label' => ['de' => 'Data Quality', 'en' => 'Data Quality']],
    ],
  ],
  [
    'id' => 'data-subject-request',
    'order' => 1261,
    'category' => 'privacy',
    'term' => ['de' => 'Data Subject Request', 'en' => 'Data Subject Request'],
    'aliases' => ['DSR', 'Subject Access Request'],
    'definition' => [
      'de' => 'Anfrage einer Person zu Access, Löschung oder Berichtigung — muss über Systeme und Lineage nachverfolgbar sein.',
      'en' => 'Individual request for access, deletion, or correction — must be traceable across systems and lineage.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'dsr-workflow', 'label' => ['de' => 'DSR Workflow', 'en' => 'DSR Workflow']],
      ['type' => 'glossary', 'id' => 'gdpr', 'label' => ['de' => 'GDPR', 'en' => 'GDPR']],
      ['type' => 'glossary', 'id' => 'lineage', 'label' => ['de' => 'Lineage', 'en' => 'Lineage']],
    ],
  ],
  [
    'id' => 'dsr-workflow',
    'order' => 1262,
    'category' => 'privacy',
    'term' => ['de' => 'DSR Workflow', 'en' => 'DSR Workflow'],
    'aliases' => ['DSR Process', 'Privacy Request Workflow'],
    'definition' => [
      'de' => 'Standardprozess von Ticket bis Löschung/Export mit Deadlines — ohne Workflow bleiben Kopien in Backups.',
      'en' => 'Standard process from ticket to deletion/export with deadlines — without workflow, copies linger in backups.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-subject-request', 'label' => ['de' => 'Data Subject Request', 'en' => 'Data Subject Request']],
      ['type' => 'glossary', 'id' => 'consent-management', 'label' => ['de' => 'Consent Management', 'en' => 'Consent Management']],
      ['type' => 'glossary', 'id' => 'privacy-by-design', 'label' => ['de' => 'Privacy by Design', 'en' => 'Privacy by Design']],
    ],
  ],
  [
    'id' => 'opt-out',
    'order' => 1263,
    'category' => 'privacy',
    'term' => ['de' => 'Opt-out', 'en' => 'Opt-out'],
    'aliases' => ['Unsubscribe', 'Withdraw Consent'],
    'definition' => [
      'de' => 'Widerspruch gegen Nutzung (Marketing, Profiling) — muss technisch in Segmenten und Pipelines reflektiert werden.',
      'en' => 'Objection to use (marketing, profiling) — must be reflected technically in segments and pipelines.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'opt-in', 'label' => ['de' => 'Opt-in', 'en' => 'Opt-in']],
      ['type' => 'glossary', 'id' => 'consent-management', 'label' => ['de' => 'Consent Management', 'en' => 'Consent Management']],
      ['type' => 'glossary', 'id' => 'gdpr', 'label' => ['de' => 'GDPR', 'en' => 'GDPR']],
    ],
  ],
  [
    'id' => 'opt-in',
    'order' => 1264,
    'category' => 'privacy',
    'term' => ['de' => 'Opt-in', 'en' => 'Opt-in'],
    'aliases' => ['Explicit Consent', 'Consent Opt-in'],
    'definition' => [
      'de' => 'Nutzer willigt aktiv ein — Standard für viele Marketing- und Analytics-Use-Cases in der EU.',
      'en' => 'User actively consents — standard for many marketing and analytics use cases in the EU.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'opt-out', 'label' => ['de' => 'Opt-out', 'en' => 'Opt-out']],
      ['type' => 'glossary', 'id' => 'consent-management', 'label' => ['de' => 'Consent Management', 'en' => 'Consent Management']],
      ['type' => 'glossary', 'id' => 'privacy-by-design', 'label' => ['de' => 'Privacy by Design', 'en' => 'Privacy by Design']],
    ],
  ],
  [
    'id' => 'legitimate-interest-assessment',
    'order' => 1265,
    'category' => 'privacy',
    'term' => ['de' => 'Legitimate Interest Assessment', 'en' => 'Legitimate Interest Assessment'],
    'aliases' => ['LIA', 'Legitimate Interest Test'],
    'definition' => [
      'de' => 'Dokumentierte Abwägung für Verarbeitung ohne Consent — braucht Purpose, Necessity und Balancing.',
      'en' => 'Documented balancing for processing without consent — needs purpose, necessity, and balancing.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'gdpr', 'label' => ['de' => 'GDPR', 'en' => 'GDPR']],
      ['type' => 'glossary', 'id' => 'privacy-by-design', 'label' => ['de' => 'Privacy by Design', 'en' => 'Privacy by Design']],
      ['type' => 'glossary', 'id' => 'pii', 'label' => ['de' => 'PII', 'en' => 'PII']],
    ],
  ],
  [
    'id' => 'security-event',
    'order' => 1464,
    'category' => 'security',
    'term' => ['de' => 'Security Event', 'en' => 'Security Event'],
    'aliases' => ['Sec Event', 'Audit Security Event'],
    'definition' => [
      'de' => 'Protokollierter sicherheitsrelevanter Vorgang (Login, Policy Change) — Rohmaterial für SIEM und Forensics.',
      'en' => 'Logged security-relevant action (login, policy change) — raw material for SIEM and forensics.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'siem-alert', 'label' => ['de' => 'SIEM Alert', 'en' => 'SIEM Alert']],
      ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
      ['type' => 'glossary', 'id' => 'threat-modeling', 'label' => ['de' => 'Threat Modeling', 'en' => 'Threat Modeling']],
    ],
  ],
  [
    'id' => 'siem-alert',
    'order' => 1465,
    'category' => 'security',
    'term' => ['de' => 'SIEM Alert', 'en' => 'SIEM Alert'],
    'aliases' => ['Security Alert', 'Correlation Alert'],
    'definition' => [
      'de' => 'Alarm aus SIEM-Korrelation mehrerer Events — Qualität hängt von Parsing, Tuning und False-Positive-Management ab.',
      'en' => 'Alert from SIEM correlation of multiple events — quality depends on parsing, tuning, and false-positive handling.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'security-event', 'label' => ['de' => 'Security Event', 'en' => 'Security Event']],
      ['type' => 'glossary', 'id' => 'soc-analyst', 'label' => ['de' => 'SOC Analyst', 'en' => 'SOC Analyst']],
      ['type' => 'glossary', 'id' => 'incident-commander', 'label' => ['de' => 'Incident Commander', 'en' => 'Incident Commander']],
    ],
  ],
  [
    'id' => 'soc-analyst',
    'order' => 1466,
    'category' => 'security',
    'term' => ['de' => 'SOC Analyst', 'en' => 'SOC Analyst'],
    'aliases' => ['Security Operations Analyst', 'Tier 1 Analyst'],
    'definition' => [
      'de' => 'Triagiert Alerts, eskaliert Incidents und dokumentiert Playbooks — operatives Herz der Security Operations.',
      'en' => 'Triages alerts, escalates incidents, documents playbooks — operational heart of security operations.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'siem-alert', 'label' => ['de' => 'SIEM Alert', 'en' => 'SIEM Alert']],
      ['type' => 'glossary', 'id' => 'runbook', 'label' => ['de' => 'Runbook', 'en' => 'Runbook']],
      ['type' => 'glossary', 'id' => 'threat-modeling', 'label' => ['de' => 'Threat Modeling', 'en' => 'Threat Modeling']],
    ],
  ],
  [
    'id' => 'vulnerability-scan',
    'order' => 1467,
    'category' => 'security',
    'term' => ['de' => 'Vulnerability Scan', 'en' => 'Vulnerability Scan'],
    'aliases' => ['Vuln Scan', 'CVE Scan'],
    'definition' => [
      'de' => 'Automatisierte Suche für bekannte Schwachstellen in Images/Hosts — Findings brauchen Priorisierung und Patch-SLA.',
      'en' => 'Automated search for known weaknesses in images/hosts — findings need prioritization and patch SLA.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'penetration-test', 'label' => ['de' => 'Penetration Test', 'en' => 'Penetration Test']],
      ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
      ['type' => 'glossary', 'id' => 'platform-engineer', 'label' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer']],
    ],
  ],
  [
    'id' => 'penetration-test',
    'order' => 1468,
    'category' => 'security',
    'term' => ['de' => 'Penetration Test', 'en' => 'Penetration Test'],
    'aliases' => ['Pen Test', 'Pentest'],
    'definition' => [
      'de' => 'Simulierter Angriff auf Systeme mit Report — tiefer als Scan, aber punktuell und nicht Dauer-Monitoring.',
      'en' => 'Simulated attack on systems with report — deeper than scan but point-in-time, not continuous monitoring.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'vulnerability-scan', 'label' => ['de' => 'Vulnerability Scan', 'en' => 'Vulnerability Scan']],
      ['type' => 'glossary', 'id' => 'threat-modeling', 'label' => ['de' => 'Threat Modeling', 'en' => 'Threat Modeling']],
      ['type' => 'glossary', 'id' => 'mfa', 'label' => ['de' => 'MFA', 'en' => 'MFA']],
    ],
  ],
  [
    'id' => 'business-term-link',
    'order' => 1661,
    'category' => 'metadata',
    'term' => ['de' => 'Business Term Link', 'en' => 'Business Term Link'],
    'aliases' => ['Term Mapping', 'Glossary Link'],
    'definition' => [
      'de' => 'Verknüpfung Business-Begriff ↔ technisches Feld/Asset — macht Catalog für Nicht-Engineers verständlich.',
      'en' => 'Link business term ↔ technical field/asset — makes catalog understandable for non-engineers.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'business-glossary', 'label' => ['de' => 'Business Glossary', 'en' => 'Business Glossary']],
      ['type' => 'glossary', 'id' => 'technical-term', 'label' => ['de' => 'Technical Term', 'en' => 'Technical Term']],
      ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
    ],
  ],
  [
    'id' => 'technical-term',
    'order' => 1662,
    'category' => 'metadata',
    'term' => ['de' => 'Technical Term', 'en' => 'Technical Term'],
    'aliases' => ['Physical Term', 'Column Term'],
    'definition' => [
      'de' => 'Metadaten-Eintrag für Spalte, Topic oder API-Feld — oft mit Typ, Lineage und Owner im Catalog.',
      'en' => 'Metadata entry for column, topic, or API field — often with type, lineage, and owner in catalog.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'business-term-link', 'label' => ['de' => 'Business Term Link', 'en' => 'Business Term Link']],
      ['type' => 'glossary', 'id' => 'metadata', 'label' => ['de' => 'Metadata', 'en' => 'Metadata']],
      ['type' => 'glossary', 'id' => 'lineage', 'label' => ['de' => 'Lineage', 'en' => 'Lineage']],
    ],
  ],
  [
    'id' => 'catalog-search',
    'order' => 1663,
    'category' => 'metadata',
    'term' => ['de' => 'Catalog Search', 'en' => 'Catalog Search'],
    'aliases' => ['Metadata Search', 'Discovery Search'],
    'definition' => [
      'de' => 'Volltext/Semantic Search über Datasets, Terms und Dashboards — Qualität hängt von Tags und Business Links ab.',
      'en' => 'Full-text/semantic search across datasets, terms, and dashboards — quality depends on tags and business links.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
      ['type' => 'glossary', 'id' => 'semantic-search-index', 'label' => ['de' => 'Semantic Search Index', 'en' => 'Semantic Search Index']],
      ['type' => 'glossary', 'id' => 'metadata-api', 'label' => ['de' => 'Metadata API', 'en' => 'Metadata API']],
    ],
  ],
  [
    'id' => 'metadata-api',
    'order' => 1664,
    'category' => 'metadata',
    'term' => ['de' => 'Metadata API', 'en' => 'Metadata API'],
    'aliases' => ['Catalog API', 'Governance API'],
    'definition' => [
      'de' => 'API für Catalog-Metadaten (Assets, Lineage, Tags) — Basis für Automation und IDE-Integration.',
      'en' => 'API for catalog metadata (assets, lineage, tags) — basis for automation and IDE integration.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
      ['type' => 'glossary', 'id' => 'lineage-export', 'label' => ['de' => 'Lineage Export', 'en' => 'Lineage Export']],
      ['type' => 'glossary', 'id' => 'api-gateway', 'label' => ['de' => 'API Gateway', 'en' => 'API Gateway']],
    ],
  ],
  [
    'id' => 'lineage-export',
    'order' => 1665,
    'category' => 'metadata',
    'term' => ['de' => 'Lineage Export', 'en' => 'Lineage Export'],
    'aliases' => ['Lineage Dump', 'OpenLineage Export'],
    'definition' => [
      'de' => 'Export von Lineage-Graph für Audit, Impact Analysis oder externes Tool — nicht nur UI-Screenshot.',
      'en' => 'Export of lineage graph for audit, impact analysis, or external tool — not just UI screenshot.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'lineage', 'label' => ['de' => 'Lineage', 'en' => 'Lineage']],
      ['type' => 'glossary', 'id' => 'metadata-api', 'label' => ['de' => 'Metadata API', 'en' => 'Metadata API']],
      ['type' => 'glossary', 'id' => 'impact-report', 'label' => ['de' => 'Impact Report', 'en' => 'Impact Report']],
    ],
  ],
  [
    'id' => 'mob-programming',
    'order' => 1861,
    'category' => 'process',
    'term' => ['de' => 'Mob Programming', 'en' => 'Mob Programming'],
    'aliases' => ['Mobbing Session', 'Whole-Team Programming'],
    'definition' => [
      'de' => 'Gesamtes Team arbeitet gemeinsam an einem Problem (ein Driver) — stark für komplexe Pipeline-/Model-Themen.',
      'en' => 'Whole team works on one problem (one driver) — strong for complex pipeline/model topics.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'pair-programming', 'label' => ['de' => 'Pair Programming', 'en' => 'Pair Programming']],
      ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
      ['type' => 'glossary', 'id' => 'continuous-delivery', 'label' => ['de' => 'Continuous Delivery', 'en' => 'Continuous Delivery']],
    ],
  ],
  [
    'id' => 'incident-retrospective',
    'order' => 1862,
    'category' => 'process',
    'term' => ['de' => 'Incident Retrospective', 'en' => 'Incident Retrospective'],
    'aliases' => ['Postmortem Retro', 'Incident Review'],
    'definition' => [
      'de' => 'Strukturierte Nachbesprechung nach Incident — Fokus auf Systemverbesserung, nicht Schuld-Zuweisung.',
      'en' => 'Structured review after incident — focus on system improvement, not blame assignment.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'incident-commander', 'label' => ['de' => 'Incident Commander', 'en' => 'Incident Commander']],
      ['type' => 'glossary', 'id' => 'runbook', 'label' => ['de' => 'Runbook', 'en' => 'Runbook']],
      ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
    ],
  ],
  [
    'id' => 'sprint-review',
    'order' => 1863,
    'category' => 'process',
    'term' => ['de' => 'Sprint Review', 'en' => 'Sprint Review'],
    'aliases' => ['Iteration Review', 'Demo Sprint'],
    'definition' => [
      'de' => 'Demo und Feedback am Sprint-Ende — für Data Teams oft „zeig neue Dataset/Metric“, nicht nur Tickets.',
      'en' => 'Demo and feedback at sprint end — for data teams often “show new dataset/metric”, not just tickets.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-product-owner', 'label' => ['de' => 'Data Product Owner', 'en' => 'Data Product Owner']],
      ['type' => 'glossary', 'id' => 'continuous-delivery', 'label' => ['de' => 'Continuous Delivery', 'en' => 'Continuous Delivery']],
      ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
    ],
  ],
  [
    'id' => 'capacity-forecast',
    'order' => 1864,
    'category' => 'process',
    'term' => ['de' => 'Capacity Forecast', 'en' => 'Capacity Forecast'],
    'aliases' => ['Team Capacity Plan', 'Throughput Forecast'],
    'definition' => [
      'de' => 'Prognose verfügbarer Team-Kapazität vs. Backlog — verhindert überzogene Data-Roadmap-Versprechen.',
      'en' => 'Forecast of available team capacity vs. backlog — prevents overpromising on data roadmap.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-product-roadmap', 'label' => ['de' => 'Data Product Roadmap', 'en' => 'Data Product Roadmap']],
      ['type' => 'glossary', 'id' => 'finops', 'label' => ['de' => 'FinOps', 'en' => 'FinOps']],
      ['type' => 'glossary', 'id' => 'toil-reduction', 'label' => ['de' => 'Toil Reduction', 'en' => 'Toil Reduction']],
    ],
  ],
  [
    'id' => 'toil-reduction',
    'order' => 1865,
    'category' => 'process',
    'term' => ['de' => 'Toil Reduction', 'en' => 'Toil Reduction'],
    'aliases' => ['Reduce Toil', 'Automation of Repetitive Ops'],
    'definition' => [
      'de' => 'Automatisierung repetitiver Ops (manual reruns, ticket-driven fixes) — SRE-Prinzip für Data Platform Teams.',
      'en' => 'Automating repetitive ops (manual reruns, ticket-driven fixes) — SRE principle for data platform teams.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
      ['type' => 'glossary', 'id' => 'platform-engineer', 'label' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer']],
      ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
    ],
  ],
  [
    'id' => 'retrieval-pipeline',
    'order' => 2061,
    'category' => 'ai',
    'term' => ['de' => 'Retrieval Pipeline', 'en' => 'Retrieval Pipeline'],
    'aliases' => ['RAG Pipeline', 'Search Pipeline'],
    'definition' => [
      'de' => 'Kette Index → Retrieve → Rerank → Context für LLM — Qualität und Latenz hängen an jedem Schritt.',
      'en' => 'Chain index → retrieve → rerank → context for LLM — quality and latency depend on each step.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'rag', 'label' => ['de' => 'RAG', 'en' => 'RAG']],
      ['type' => 'glossary', 'id' => 'vector-database', 'label' => ['de' => 'Vector Database', 'en' => 'Vector Database']],
      ['type' => 'glossary', 'id' => 'reranker', 'label' => ['de' => 'Reranker', 'en' => 'Reranker']],
    ],
  ],
  [
    'id' => 'vector-chunk',
    'order' => 2062,
    'category' => 'ai',
    'term' => ['de' => 'Vector Chunk', 'en' => 'Vector Chunk'],
    'aliases' => ['Embedding Chunk', 'Indexed Chunk'],
    'definition' => [
      'de' => 'Textsegment plus Embedding im Vector Store — Chunk-Größe beeinflusst Recall und Halluzinations-Risiko.',
      'en' => 'Text segment plus embedding in vector store — chunk size affects recall and hallucination risk.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'chunking-strategy', 'label' => ['de' => 'Chunking Strategy', 'en' => 'Chunking Strategy']],
      ['type' => 'glossary', 'id' => 'embedding', 'label' => ['de' => 'Embedding', 'en' => 'Embedding']],
      ['type' => 'glossary', 'id' => 'vector-database', 'label' => ['de' => 'Vector Database', 'en' => 'Vector Database']],
    ],
  ],
  [
    'id' => 'semantic-search-index',
    'order' => 2063,
    'category' => 'ai',
    'term' => ['de' => 'Semantic Search Index', 'en' => 'Semantic Search Index'],
    'aliases' => ['Vector Index', 'Semantic Index'],
    'definition' => [
      'de' => 'Index für Ähnlichkeitssuche auf Embeddings — Kern von Catalog-Search und Enterprise RAG.',
      'en' => 'Index for similarity search on embeddings — core of catalog search and enterprise RAG.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'catalog-search', 'label' => ['de' => 'Catalog Search', 'en' => 'Catalog Search']],
      ['type' => 'glossary', 'id' => 'hybrid-search', 'label' => ['de' => 'Hybrid Search', 'en' => 'Hybrid Search']],
      ['type' => 'glossary', 'id' => 'index-rebuild', 'label' => ['de' => 'Index Rebuild', 'en' => 'Index Rebuild']],
    ],
  ],
  [
    'id' => 'query-expansion',
    'order' => 2064,
    'category' => 'ai',
    'term' => ['de' => 'Query Expansion', 'en' => 'Query Expansion'],
    'aliases' => ['Expanded Query', 'Synonym Expansion'],
    'definition' => [
      'de' => 'Erweitert User-Query (Synonyme, LLM) vor Retrieval — hilft bei domänenspezifischen Begriffen.',
      'en' => 'Broadens user query (synonyms, LLM) before retrieval — helps with domain-specific terms.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'hybrid-search', 'label' => ['de' => 'Hybrid Search', 'en' => 'Hybrid Search']],
      ['type' => 'glossary', 'id' => 'llm', 'label' => ['de' => 'LLM', 'en' => 'LLM']],
      ['type' => 'glossary', 'id' => 'retrieval-pipeline', 'label' => ['de' => 'Retrieval Pipeline', 'en' => 'Retrieval Pipeline']],
    ],
  ],
  [
    'id' => 'function-calling-api',
    'order' => 2065,
    'category' => 'ai',
    'term' => ['de' => 'Function Calling API', 'en' => 'Function Calling API'],
    'aliases' => ['Tool Calling API', 'Functions API'],
    'definition' => [
      'de' => 'LLM-API-Schicht für strukturierte Tool-Aufrufe — Basis für Agents mit Datenbank- und API-Actions.',
      'en' => 'LLM API layer for structured tool calls — basis for agents with database and API actions.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'tool-schema', 'label' => ['de' => 'Tool Schema', 'en' => 'Tool Schema']],
      ['type' => 'glossary', 'id' => 'agent-planner', 'label' => ['de' => 'Agent Planner', 'en' => 'Agent Planner']],
      ['type' => 'glossary', 'id' => 'llm', 'label' => ['de' => 'LLM', 'en' => 'LLM']],
    ],
  ],
  [
    'id' => 'active-active',
    'order' => 466,
    'category' => 'architecture',
    'term' => ['de' => 'Active-Active', 'en' => 'Active-Active'],
    'aliases' => ['Dual Active', 'Multi-Active'],
    'definition' => [
      'de' => 'Mehrere Standorte/Cluster nehmen Traffic parallel — höchste Verfügbarkeit, komplex bei Datenkonsistenz.',
      'en' => 'Multiple sites/clusters take traffic in parallel — highest availability, complex for data consistency.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'warm-standby', 'label' => ['de' => 'Warm Standby', 'en' => 'Warm Standby']],
      ['type' => 'glossary', 'id' => 'geo-replication', 'label' => ['de' => 'Geo-Replication', 'en' => 'Geo-Replication']],
      ['type' => 'glossary', 'id' => 'multi-region', 'label' => ['de' => 'Multi-Region', 'en' => 'Multi-Region']],
    ],
  ],
  [
    'id' => 'geo-replication',
    'order' => 467,
    'category' => 'architecture',
    'term' => ['de' => 'Geo-Replication', 'en' => 'Geo-Replication'],
    'aliases' => ['Geographic Replication', 'Cross-Region Replica'],
    'definition' => [
      'de' => 'Repliziert Daten zwischen Regionen für DR und Latenz — Kosten und Konsistenzmodell müssen passen.',
      'en' => 'Replicates data across regions for DR and latency — cost and consistency model must align.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'multi-region', 'label' => ['de' => 'Multi-Region', 'en' => 'Multi-Region']],
      ['type' => 'glossary', 'id' => 'active-active', 'label' => ['de' => 'Active-Active', 'en' => 'Active-Active']],
      ['type' => 'glossary', 'id' => 'rto', 'label' => ['de' => 'RTO', 'en' => 'RTO']],
    ],
  ],
  [
    'id' => 'multi-region',
    'order' => 468,
    'category' => 'architecture',
    'term' => ['de' => 'Multi-Region', 'en' => 'Multi-Region'],
    'aliases' => ['Multi-Region Deployment', 'Regional Topology'],
    'definition' => [
      'de' => 'Architektur über mehrere Cloud-Regionen — betrifft Datenresidenz, Failover und Compliance gleichzeitig.',
      'en' => 'Architecture across multiple cloud regions — affects data residency, failover, and compliance together.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'geo-replication', 'label' => ['de' => 'Geo-Replication', 'en' => 'Geo-Replication']],
      ['type' => 'glossary', 'id' => 'gdpr', 'label' => ['de' => 'GDPR', 'en' => 'GDPR']],
      ['type' => 'glossary', 'id' => 'platform-engineer', 'label' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer']],
    ],
  ],
  [
    'id' => 'parent-child-hierarchy',
    'order' => 666,
    'category' => 'modeling',
    'term' => ['de' => 'Parent-Child Hierarchy', 'en' => 'Parent-Child Hierarchy'],
    'aliases' => ['Adjacency Hierarchy', 'Recursive Hierarchy'],
    'definition' => [
      'de' => 'Hierarchie über Parent-ID pro Row — flexibel, aber Queries und BI-Drill oft teurer als Snowflake-Dims.',
      'en' => 'Hierarchy via parent ID per row — flexible but queries and BI drill often costlier than snowflake dims.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'hierarchy-path', 'label' => ['de' => 'Hierarchy Path', 'en' => 'Hierarchy Path']],
      ['type' => 'glossary', 'id' => 'ragged-hierarchy', 'label' => ['de' => 'Ragged Hierarchy', 'en' => 'Ragged Hierarchy']],
      ['type' => 'glossary', 'id' => 'star-schema', 'label' => ['de' => 'Star Schema', 'en' => 'Star Schema']],
    ],
  ],
  [
    'id' => 'hierarchy-path',
    'order' => 667,
    'category' => 'modeling',
    'term' => ['de' => 'Hierarchy Path', 'en' => 'Hierarchy Path'],
    'aliases' => ['Materialized Path', 'Hierarchy String'],
    'definition' => [
      'de' => 'Gespeicherter Pfad von Root bis Knoten — beschleunigt Drill und Filter in unbalancierten Hierarchien.',
      'en' => 'Stored path from root to node — speeds drill and filter in unbalanced hierarchies.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'parent-child-hierarchy', 'label' => ['de' => 'Parent-Child Hierarchy', 'en' => 'Parent-Child Hierarchy']],
      ['type' => 'glossary', 'id' => 'unbalanced-hierarchy', 'label' => ['de' => 'Unbalanced Hierarchy', 'en' => 'Unbalanced Hierarchy']],
      ['type' => 'glossary', 'id' => 'semantic-layer', 'label' => ['de' => 'Semantic Layer', 'en' => 'Semantic Layer']],
    ],
  ],
  [
    'id' => 'profiling-job',
    'order' => 1066,
    'category' => 'quality',
    'term' => ['de' => 'Profiling Job', 'en' => 'Profiling Job'],
    'aliases' => ['Data Profiling Job', 'Profile Run'],
    'definition' => [
      'de' => 'Scheduled Job für Null-Rates, Distinct Counts und Muster — Input für Quality Rules und Anomaly Detection.',
      'en' => 'Scheduled job for null rates, distinct counts, and patterns — input for quality rules and anomaly detection.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'data-quality', 'label' => ['de' => 'Data Quality', 'en' => 'Data Quality']],
      ['type' => 'glossary', 'id' => 'distribution-check', 'label' => ['de' => 'Distribution Check', 'en' => 'Distribution Check']],
      ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
    ],
  ],
  [
    'id' => 'quality-gate',
    'order' => 1067,
    'category' => 'quality',
    'term' => ['de' => 'Quality Gate', 'en' => 'Quality Gate'],
    'aliases' => ['DQ Gate', 'Pipeline Quality Gate'],
    'definition' => [
      'de' => 'Checkpoint in CI/CD/Pipeline — Deploy oder Promote nur wenn definierte DQ-Checks grün sind.',
      'en' => 'Checkpoint in CI/CD/pipeline — deploy or promote only when defined DQ checks pass.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'schema-validation', 'label' => ['de' => 'Schema Validation', 'en' => 'Schema Validation']],
      ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
      ['type' => 'glossary', 'id' => 'data-quality', 'label' => ['de' => 'Data Quality', 'en' => 'Data Quality']],
    ],
  ],
  [
    'id' => 'observability-alert',
    'order' => 1068,
    'category' => 'quality',
    'term' => ['de' => 'Observability Alert', 'en' => 'Observability Alert'],
    'aliases' => ['Pipeline Alert', 'SLO Alert'],
    'definition' => [
      'de' => 'Alert aus Metriken/Logs (Latency, Freshness, Error Rate) — verbindet Ops mit Data Quality sichtbar.',
      'en' => 'Alert from metrics/logs (latency, freshness, error rate) — connects ops visibility with data quality.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
      ['type' => 'glossary', 'id' => 'anomaly-detection-rule', 'label' => ['de' => 'Anomaly Detection Rule', 'en' => 'Anomaly Detection Rule']],
      ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
    ],
  ],
  [
    'id' => 'impact-report',
    'order' => 1666,
    'category' => 'metadata',
    'term' => ['de' => 'Impact Report', 'en' => 'Impact Report'],
    'aliases' => ['Downstream Impact', 'Change Impact Report'],
    'definition' => [
      'de' => 'Bericht welche Reports/Pipelines von Schema- oder Term-Änderung betroffen sind — aus Lineage/Catalog.',
      'en' => 'Report of which reports/pipelines are affected by schema or term change — from lineage/catalog.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'lineage', 'label' => ['de' => 'Lineage', 'en' => 'Lineage']],
      ['type' => 'glossary', 'id' => 'lineage-export', 'label' => ['de' => 'Lineage Export', 'en' => 'Lineage Export']],
      ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
    ],
  ],
  [
    'id' => 'index-rebuild',
    'order' => 2066,
    'category' => 'ai',
    'term' => ['de' => 'Index Rebuild', 'en' => 'Index Rebuild'],
    'aliases' => ['Vector Reindex', 'Full Index Refresh'],
    'definition' => [
      'de' => 'Vollständiger Neuaufbau des Search/Vector-Index — nötig bei Embedding-Model-Wechsel oder Chunk-Policy.',
      'en' => 'Full rebuild of search/vector index — needed on embedding model change or chunk policy shift.',
    ],
    'related' => [
      ['type' => 'glossary', 'id' => 'semantic-search-index', 'label' => ['de' => 'Semantic Search Index', 'en' => 'Semantic Search Index']],
      ['type' => 'glossary', 'id' => 'embedding-model', 'label' => ['de' => 'Embedding Model', 'en' => 'Embedding Model']],
      ['type' => 'glossary', 'id' => 'retrieval-pipeline', 'label' => ['de' => 'Retrieval Pipeline', 'en' => 'Retrieval Pipeline']],
    ],
  ],
];
