<?php

/**
 * Glossary buzzword wave 4 — quiz-friendly terms (distinct defs, clear categories).
 *
 * @return list<array<string, mixed>>
 */
return [
    [
        'id' => 'head-of-data',
        'order' => 58,
        'category' => 'roles',
        'term' => ['de' => 'Head of Data', 'en' => 'Head of Data'],
        'aliases' => ['HoD', 'Director of Data'],
        'definition' => [
            'de' => 'Führt das Data-Team operativ (Prioritäten, Delivery, People) — oft unter CDO, näher am Tagesgeschäft als reine Strategie.',
            'en' => 'Leads the data team operationally (priorities, delivery, people) — often under a CDO, closer to day-to-day than pure strategy.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'chief-data-officer', 'label' => ['de' => 'CDO', 'en' => 'CDO']],
            ['type' => 'glossary', 'id' => 'governance-lead', 'label' => ['de' => 'Governance Lead', 'en' => 'Governance Lead']],
            ['type' => 'glossary', 'id' => 'data-product-owner', 'label' => ['de' => 'Data Product Owner', 'en' => 'Data Product Owner']],
        ],
    ],
    [
        'id' => 'ai-engineer',
        'order' => 59,
        'category' => 'roles',
        'term' => ['de' => 'AI Engineer', 'en' => 'AI Engineer'],
        'aliases' => ['Applied AI Engineer', 'LLM Engineer'],
        'definition' => [
            'de' => 'Baut produktive KI-Features (RAG, Agents, Evals, Serving) — Brücke zwischen Research-Notebooks und Platform.',
            'en' => 'Builds production AI features (RAG, agents, evals, serving) — bridge between research notebooks and platform.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'ml-engineer', 'label' => ['de' => 'ML Engineer', 'en' => 'ML Engineer']],
            ['type' => 'glossary', 'id' => 'prompt-engineer', 'label' => ['de' => 'Prompt Engineer', 'en' => 'Prompt Engineer']],
            ['type' => 'glossary', 'id' => 'rag', 'label' => ['de' => 'RAG', 'en' => 'RAG']],
        ],
    ],
    [
        'id' => 'domain-owner',
        'order' => 60,
        'category' => 'roles',
        'term' => ['de' => 'Domain Owner', 'en' => 'Domain Owner'],
        'aliases' => ['Business Domain Owner', 'Domain Lead'],
        'definition' => [
            'de' => 'Verantwortet eine Fachdomäne inkl. Datenprodukte und Entscheidungen — nicht nur Ticket-Priorisierung.',
            'en' => 'Owns a business domain including data products and decisions — not ticket prioritization alone.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-owner', 'label' => ['de' => 'Data Owner', 'en' => 'Data Owner']],
            ['type' => 'glossary', 'id' => 'data-mesh', 'label' => ['de' => 'Data Mesh', 'en' => 'Data Mesh']],
            ['type' => 'glossary', 'id' => 'data-product-owner', 'label' => ['de' => 'Data Product Owner', 'en' => 'Data Product Owner']],
        ],
    ],
    [
        'id' => 'data-product-canvas',
        'order' => 246,
        'category' => 'data',
        'term' => ['de' => 'Data Product Canvas', 'en' => 'Data Product Canvas'],
        'aliases' => ['DPC', 'Produkt-Canvas Daten'],
        'definition' => [
            'de' => 'Einseitige Skizze für Nutzer, Nutzen, Interface, Qualität und Owner eines Datenprodukts — vor dem Pipeline-Bau.',
            'en' => 'One-page sketch of users, value, interface, quality, and owner for a data product — before building pipelines.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-product', 'label' => ['de' => 'Data Product', 'en' => 'Data Product']],
            ['type' => 'glossary', 'id' => 'data-as-a-product', 'label' => ['de' => 'Data as a Product', 'en' => 'Data as a Product']],
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
        ],
    ],
    [
        'id' => 'domain-data-product',
        'order' => 247,
        'category' => 'data',
        'term' => ['de' => 'Domain Data Product', 'en' => 'Domain Data Product'],
        'aliases' => ['Domain Product', 'Mesh Data Product'],
        'definition' => [
            'de' => 'Datenprodukt einer Fachdomäne mit klarem Vertrag — Cross-Domain-Konsum nur über veröffentlichte Interfaces.',
            'en' => 'Data product of a business domain with a clear contract — cross-domain use only via published interfaces.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-mesh', 'label' => ['de' => 'Data Mesh', 'en' => 'Data Mesh']],
            ['type' => 'glossary', 'id' => 'domain-owner', 'label' => ['de' => 'Domain Owner', 'en' => 'Domain Owner']],
            ['type' => 'glossary', 'id' => 'data-product', 'label' => ['de' => 'Data Product', 'en' => 'Data Product']],
        ],
    ],
    [
        'id' => 'data-sharing-agreement',
        'order' => 248,
        'category' => 'data',
        'term' => ['de' => 'Data Sharing Agreement', 'en' => 'Data Sharing Agreement'],
        'aliases' => ['DSA', 'Datenaustauschvertrag'],
        'definition' => [
            'de' => 'Regelt Zweck, Rechte, Qualität und Haftung beim Teilen von Daten zwischen Parteien — nicht nur ein SharePoint-Link.',
            'en' => 'Governs purpose, rights, quality, and liability when sharing data between parties — not just a SharePoint link.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
            ['type' => 'glossary', 'id' => 'data-clean-room', 'label' => ['de' => 'Data Clean Room', 'en' => 'Data Clean Room']],
            ['type' => 'glossary', 'id' => 'purpose-limitation', 'label' => ['de' => 'Purpose Limitation', 'en' => 'Purpose Limitation']],
        ],
    ],
    [
        'id' => 'platform-as-a-product',
        'order' => 249,
        'category' => 'data',
        'term' => ['de' => 'Platform as a Product', 'en' => 'Platform as a Product'],
        'aliases' => ['Internal Platform Product', 'PaaP'],
        'definition' => [
            'de' => 'Interne Plattform wird wie ein Produkt geführt (Roadmap, UX, SLAs für Teams) — nicht als Ticket-Hilfe.',
            'en' => 'Internal platform is run like a product (roadmap, UX, SLAs for teams) — not as ticket helpdesk.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'platform-engineer', 'label' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer']],
            ['type' => 'glossary', 'id' => 'golden-path', 'label' => ['de' => 'Golden Path', 'en' => 'Golden Path']],
            ['type' => 'glossary', 'id' => 'self-serve-platform', 'label' => ['de' => 'Self-Serve Platform', 'en' => 'Self-Serve Platform']],
        ],
    ],
    [
        'id' => 'self-serve-platform',
        'order' => 250,
        'category' => 'data',
        'term' => ['de' => 'Self-Serve Platform', 'en' => 'Self-Serve Platform'],
        'aliases' => ['Self-Service Data Platform', 'SSP'],
        'definition' => [
            'de' => 'Teams können Datenprodukte/Pipelines ohne Gatekeeper-Tickets provisionieren — Guardrails statt Freigabe-Warteschlange.',
            'en' => 'Teams can provision data products/pipelines without gatekeeper tickets — guardrails instead of approval queues.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'platform-as-a-product', 'label' => ['de' => 'Platform as a Product', 'en' => 'Platform as a Product']],
            ['type' => 'glossary', 'id' => 'golden-path', 'label' => ['de' => 'Golden Path', 'en' => 'Golden Path']],
            ['type' => 'glossary', 'id' => 'data-mesh', 'label' => ['de' => 'Data Mesh', 'en' => 'Data Mesh']],
        ],
    ],
    [
        'id' => 'write-audit-publish',
        'order' => 525,
        'category' => 'architecture',
        'term' => ['de' => 'Write-Audit-Publish', 'en' => 'Write-Audit-Publish'],
        'aliases' => ['WAP', 'WAP Pattern'],
        'definition' => [
            'de' => 'Daten zuerst schreiben und prüfen, erst danach für Konsumenten freigeben — verhindert „kaputt live“.',
            'en' => 'Write and audit data first, only then publish to consumers — prevents “broken goes live”.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
            ['type' => 'glossary', 'id' => 'quarantine-zone', 'label' => ['de' => 'Quarantine Zone', 'en' => 'Quarantine Zone']],
            ['type' => 'glossary', 'id' => 'expectation-suite', 'label' => ['de' => 'Expectation Suite', 'en' => 'Expectation Suite']],
        ],
    ],
    [
        'id' => 'cqrs-read-model',
        'order' => 526,
        'category' => 'architecture',
        'term' => ['de' => 'CQRS Read Model', 'en' => 'CQRS Read Model'],
        'aliases' => ['Read Side', 'Query Model'],
        'definition' => [
            'de' => 'Für Lesen optimiertes Modell, getrennt vom Write-Modell — oft denormalisiert und event-getrieben aktualisiert.',
            'en' => 'Read-optimized model separate from the write model — often denormalized and updated via events.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'cqrs', 'label' => ['de' => 'CQRS', 'en' => 'CQRS']],
            ['type' => 'glossary', 'id' => 'event-sourcing', 'label' => ['de' => 'Event Sourcing', 'en' => 'Event Sourcing']],
            ['type' => 'glossary', 'id' => 'event-driven-architecture', 'label' => ['de' => 'EDA', 'en' => 'EDA']],
        ],
    ],
    [
        'id' => 'data-replication',
        'order' => 527,
        'category' => 'architecture',
        'term' => ['de' => 'Data Replication', 'en' => 'Data Replication'],
        'aliases' => ['Replication', 'Replica Sync'],
        'definition' => [
            'de' => 'Kopiert Daten zwischen Systemen für Latenz, Ausfallsicherheit oder Isolation — braucht Konflikt- und Lag-Strategie.',
            'en' => 'Copies data between systems for latency, resilience, or isolation — needs conflict and lag strategy.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
            ['type' => 'glossary', 'id' => 'exactly-once', 'label' => ['de' => 'Exactly-Once', 'en' => 'Exactly-Once']],
            ['type' => 'glossary', 'id' => 'idempotency', 'label' => ['de' => 'Idempotency', 'en' => 'Idempotency']],
        ],
    ],
    [
        'id' => 'fan-out',
        'order' => 528,
        'category' => 'architecture',
        'term' => ['de' => 'Fan-Out', 'en' => 'Fan-Out'],
        'aliases' => ['Event Fan-Out', 'Publish Fan-Out'],
        'definition' => [
            'de' => 'Ein Event/Request wird an viele Consumer weitergereicht — skaliert Leselast, erhöht Observability-Bedarf.',
            'en' => 'One event/request is delivered to many consumers — scales read load, increases observability need.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'event-driven-architecture', 'label' => ['de' => 'EDA', 'en' => 'EDA']],
            ['type' => 'glossary', 'id' => 'streaming', 'label' => ['de' => 'Streaming', 'en' => 'Streaming']],
            ['type' => 'glossary', 'id' => 'outbox-pattern', 'label' => ['de' => 'Outbox Pattern', 'en' => 'Outbox Pattern']],
        ],
    ],
    [
        'id' => 'append-only',
        'order' => 529,
        'category' => 'architecture',
        'term' => ['de' => 'Append-Only', 'en' => 'Append-Only'],
        'aliases' => ['Append-Only Log', 'Immutable Log'],
        'definition' => [
            'de' => 'Neue Einträge werden nur angehängt, nie überschrieben — Audit und Replay werden einfacher, Korrekturen sind neue Events.',
            'en' => 'New entries are only appended, never overwritten — audit and replay get easier; corrections are new events.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'event-sourcing', 'label' => ['de' => 'Event Sourcing', 'en' => 'Event Sourcing']],
            ['type' => 'glossary', 'id' => 'hard-delete', 'label' => ['de' => 'Hard Delete', 'en' => 'Hard Delete']],
            ['type' => 'glossary', 'id' => 'watermark', 'label' => ['de' => 'Watermark', 'en' => 'Watermark']],
        ],
    ],
    [
        'id' => 'scd3',
        'order' => 724,
        'category' => 'modeling',
        'term' => ['de' => 'SCD Type 3', 'en' => 'SCD Type 3'],
        'aliases' => ['SCD3', 'Previous Value Column'],
        'definition' => [
            'de' => 'Hält aktuellen und vorherigen Attributwert in Spalten — begrenzte Historie, kein volles SCD2.',
            'en' => 'Keeps current and previous attribute values in columns — limited history, not full SCD2.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'slowly-changing-dimension', 'label' => ['de' => 'SCD', 'en' => 'SCD']],
            ['type' => 'glossary', 'id' => 'scd1', 'label' => ['de' => 'SCD1', 'en' => 'SCD1']],
            ['type' => 'glossary', 'id' => 'scd2', 'label' => ['de' => 'SCD2', 'en' => 'SCD2']],
        ],
    ],
    [
        'id' => 'galaxy-schema',
        'order' => 725,
        'category' => 'modeling',
        'term' => ['de' => 'Galaxy Schema', 'en' => 'Galaxy Schema'],
        'aliases' => ['Fact Constellation', 'Multi-Fact Schema'],
        'definition' => [
            'de' => 'Mehrere Fact-Tabellen teilen sich Dimensionen — typisch in großen DWHs, braucht Conformed Dimensions.',
            'en' => 'Multiple fact tables share dimensions — common in large DWHs, needs conformed dimensions.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'star-schema', 'label' => ['de' => 'Star Schema', 'en' => 'Star Schema']],
            ['type' => 'glossary', 'id' => 'snowflake-schema', 'label' => ['de' => 'Snowflake Schema', 'en' => 'Snowflake Schema']],
            ['type' => 'glossary', 'id' => 'conformed-dimension', 'label' => ['de' => 'Conformed Dimension', 'en' => 'Conformed Dimension']],
        ],
    ],
    [
        'id' => 'rapidly-changing-dimension',
        'order' => 726,
        'category' => 'modeling',
        'term' => ['de' => 'Rapidly Changing Dimension', 'en' => 'Rapidly Changing Dimension'],
        'aliases' => ['RCD', 'Fast Changing Dimension'],
        'definition' => [
            'de' => 'Dimensionsattribut ändert sich so oft, dass klassisches SCD2 explodiert — oft Mini-Dimension oder Outrigger statt voller Historie.',
            'en' => 'Dimension attribute changes so often that classic SCD2 explodes — often mini-dimension or outrigger instead of full history.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'slowly-changing-dimension', 'label' => ['de' => 'SCD', 'en' => 'SCD']],
            ['type' => 'glossary', 'id' => 'scd2', 'label' => ['de' => 'SCD2', 'en' => 'SCD2']],
            ['type' => 'glossary', 'id' => 'outrigger-dimension', 'label' => ['de' => 'Outrigger Dimension', 'en' => 'Outrigger Dimension']],
        ],
    ],
    [
        'id' => 'hard-delete',
        'order' => 727,
        'category' => 'modeling',
        'term' => ['de' => 'Hard Delete', 'en' => 'Hard Delete'],
        'aliases' => ['Physical Delete', 'Purge'],
        'definition' => [
            'de' => 'Datensatz wird physisch entfernt — irreversible, oft nötig für Erasure, problematisch für Historie/Audit.',
            'en' => 'Record is physically removed — irreversible; often needed for erasure, hard on history/audit.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'right-to-erasure', 'label' => ['de' => 'Right to Erasure', 'en' => 'Right to Erasure']],
            ['type' => 'glossary', 'id' => 'append-only', 'label' => ['de' => 'Append-Only', 'en' => 'Append-Only']],
            ['type' => 'glossary', 'id' => 'retention-schedule', 'label' => ['de' => 'Retention Schedule', 'en' => 'Retention Schedule']],
        ],
    ],
    [
        'id' => 'visual-level-filter',
        'order' => 927,
        'category' => 'bi',
        'term' => ['de' => 'Visual-Level Filter', 'en' => 'Visual-Level Filter'],
        'aliases' => ['Visual Filter', 'Chart Filter'],
        'definition' => [
            'de' => 'Filter gilt nur für ein Visual — nicht für die ganze Seite/Report; leicht übersehen bei Debugging.',
            'en' => 'Filter applies to one visual only — not the whole page/report; easy to miss when debugging.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'page-level-filter', 'label' => ['de' => 'Page-Level Filter', 'en' => 'Page-Level Filter']],
            ['type' => 'glossary', 'id' => 'report-level-filter', 'label' => ['de' => 'Report-Level Filter', 'en' => 'Report-Level Filter']],
            ['type' => 'glossary', 'id' => 'row-level-security', 'label' => ['de' => 'RLS', 'en' => 'RLS']],
        ],
    ],
    [
        'id' => 'page-level-filter',
        'order' => 928,
        'category' => 'bi',
        'term' => ['de' => 'Page-Level Filter', 'en' => 'Page-Level Filter'],
        'aliases' => ['Page Filter', 'Report Page Filter'],
        'definition' => [
            'de' => 'Filter für alle Visuals einer Report-Seite — Scope zwischen Visual- und Report-Level.',
            'en' => 'Filter for all visuals on a report page — scope between visual- and report-level.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'visual-level-filter', 'label' => ['de' => 'Visual-Level Filter', 'en' => 'Visual-Level Filter']],
            ['type' => 'glossary', 'id' => 'report-level-filter', 'label' => ['de' => 'Report-Level Filter', 'en' => 'Report-Level Filter']],
            ['type' => 'glossary', 'id' => 'sync-slicer', 'label' => ['de' => 'Sync Slicer', 'en' => 'Sync Slicer']],
        ],
    ],
    [
        'id' => 'report-level-filter',
        'order' => 929,
        'category' => 'bi',
        'term' => ['de' => 'Report-Level Filter', 'en' => 'Report-Level Filter'],
        'aliases' => ['Report Filter', 'All-Pages Filter'],
        'definition' => [
            'de' => 'Filter gilt report-weit über Seiten hinweg — stark, aber gefährlich wenn Nutzer den Scope nicht sehen.',
            'en' => 'Filter applies report-wide across pages — powerful, but risky when users do not see the scope.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'page-level-filter', 'label' => ['de' => 'Page-Level Filter', 'en' => 'Page-Level Filter']],
            ['type' => 'glossary', 'id' => 'visual-level-filter', 'label' => ['de' => 'Visual-Level Filter', 'en' => 'Visual-Level Filter']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
        ],
    ],
    [
        'id' => 'sync-slicer',
        'order' => 930,
        'category' => 'bi',
        'term' => ['de' => 'Sync Slicer', 'en' => 'Sync Slicer'],
        'aliases' => ['Synchronized Slicer', 'Synced Slicer'],
        'definition' => [
            'de' => 'Slicer-Auswahl wird über mehrere Seiten synchron gehalten — reduziert Klickaufwand, erhöht Kopplung.',
            'en' => 'Slicer selection stays synced across pages — less clicking, more coupling.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'page-level-filter', 'label' => ['de' => 'Page-Level Filter', 'en' => 'Page-Level Filter']],
            ['type' => 'glossary', 'id' => 'field-parameter', 'label' => ['de' => 'Field Parameter', 'en' => 'Field Parameter']],
            ['type' => 'glossary', 'id' => 'self-service-bi', 'label' => ['de' => 'Self-Service BI', 'en' => 'Self-Service BI']],
        ],
    ],
    [
        'id' => 'paginated-report',
        'order' => 931,
        'category' => 'bi',
        'term' => ['de' => 'Paginated Report', 'en' => 'Paginated Report'],
        'aliases' => ['Pixel-Perfect Report', 'RDL Report'],
        'definition' => [
            'de' => 'Druck-/PDF-orientierter Report mit festem Layout — anders als interaktive Dashboards.',
            'en' => 'Print/PDF-oriented report with fixed layout — unlike interactive dashboards.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'embedded-analytics', 'label' => ['de' => 'Embedded Analytics', 'en' => 'Embedded Analytics']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
            ['type' => 'glossary', 'id' => 'import-mode', 'label' => ['de' => 'Import Mode', 'en' => 'Import Mode']],
        ],
    ],
    [
        'id' => 'on-premises-gateway',
        'order' => 932,
        'category' => 'bi',
        'term' => ['de' => 'On-Premises Gateway', 'en' => 'On-Premises Data Gateway'],
        'aliases' => ['Data Gateway', 'Enterprise Gateway'],
        'definition' => [
            'de' => 'Brücke von Cloud-BI zu On-Prem-Quellen — braucht HA, Rechte und Monitoring wie produktive Infra.',
            'en' => 'Bridge from cloud BI to on-prem sources — needs HA, permissions, and monitoring like production infra.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'directquery', 'label' => ['de' => 'DirectQuery', 'en' => 'DirectQuery']],
            ['type' => 'glossary', 'id' => 'live-connection', 'label' => ['de' => 'Live Connection', 'en' => 'Live Connection']],
            ['type' => 'glossary', 'id' => 'service-account', 'label' => ['de' => 'Service Account', 'en' => 'Service Account']],
        ],
    ],
    [
        'id' => 'completeness-check',
        'order' => 1124,
        'category' => 'quality',
        'term' => ['de' => 'Completeness Check', 'en' => 'Completeness Check'],
        'aliases' => ['Completeness Rule', 'Vollständigkeitscheck'],
        'definition' => [
            'de' => 'Prüft, ob erwartete Felder/Zeilen vorhanden sind — fehlt etwas, ist „korrekt aber unvollständig“ trotzdem Fail.',
            'en' => 'Checks whether expected fields/rows are present — “correct but incomplete” still fails.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'null-rate', 'label' => ['de' => 'Null Rate', 'en' => 'Null Rate']],
            ['type' => 'glossary', 'id' => 'expectation-suite', 'label' => ['de' => 'Expectation Suite', 'en' => 'Expectation Suite']],
            ['type' => 'glossary', 'id' => 'data-reliability', 'label' => ['de' => 'Data Reliability', 'en' => 'Data Reliability']],
        ],
    ],
    [
        'id' => 'uniqueness-check',
        'order' => 1125,
        'category' => 'quality',
        'term' => ['de' => 'Uniqueness Check', 'en' => 'Uniqueness Check'],
        'aliases' => ['Unique Key Check', 'Dedup Check'],
        'definition' => [
            'de' => 'Stellt sicher, dass Schlüssel/Kombinationen eindeutig sind — Duplikate zerstören Joins und KPIs.',
            'en' => 'Ensures keys/combinations are unique — duplicates break joins and KPIs.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'duplicate-rate', 'label' => ['de' => 'Duplicate Rate', 'en' => 'Duplicate Rate']],
            ['type' => 'glossary', 'id' => 'reconciliation-check', 'label' => ['de' => 'Reconciliation Check', 'en' => 'Reconciliation Check']],
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
        ],
    ],
    [
        'id' => 'validity-rule',
        'order' => 1126,
        'category' => 'quality',
        'term' => ['de' => 'Validity Rule', 'en' => 'Validity Rule'],
        'aliases' => ['Domain Rule', 'Allowed Values Rule'],
        'definition' => [
            'de' => 'Wert muss in erlaubter Domäne liegen (Range, Enum, Format) — „nicht null“ allein reicht nicht.',
            'en' => 'Value must fall in an allowed domain (range, enum, format) — “not null” alone is not enough.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'expectation-suite', 'label' => ['de' => 'Expectation Suite', 'en' => 'Expectation Suite']],
            ['type' => 'glossary', 'id' => 'schema-drift', 'label' => ['de' => 'Schema Drift', 'en' => 'Schema Drift']],
            ['type' => 'glossary', 'id' => 'completeness-check', 'label' => ['de' => 'Completeness Check', 'en' => 'Completeness Check']],
        ],
    ],
    [
        'id' => 'duplicate-rate',
        'order' => 1127,
        'category' => 'quality',
        'term' => ['de' => 'Duplicate Rate', 'en' => 'Duplicate Rate'],
        'aliases' => ['Duplikatquote', 'Duplication Rate'],
        'definition' => [
            'de' => 'Anteil doppelter Keys/Zeilen in einem Fenster — Frühindikator für kaputte Upserts und CDC-Lücken.',
            'en' => 'Share of duplicate keys/rows in a window — early signal for broken upserts and CDC gaps.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'uniqueness-check', 'label' => ['de' => 'Uniqueness Check', 'en' => 'Uniqueness Check']],
            ['type' => 'glossary', 'id' => 'volume-anomaly', 'label' => ['de' => 'Volume Anomaly', 'en' => 'Volume Anomaly']],
            ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
        ],
    ],
    [
        'id' => 'orphan-record',
        'order' => 1128,
        'category' => 'quality',
        'term' => ['de' => 'Orphan Record', 'en' => 'Orphan Record'],
        'aliases' => ['Orphan Row', 'Dangling Reference'],
        'definition' => [
            'de' => 'Zeile ohne gültige Parent-/Dimensionsreferenz — Join liefert Lücken oder falsche „Unbekannt“-Eimer.',
            'en' => 'Row without a valid parent/dimension reference — joins yield gaps or wrong “unknown” buckets.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'late-arriving-dimension', 'label' => ['de' => 'Late-Arriving Dimension', 'en' => 'Late-Arriving Dimension']],
            ['type' => 'glossary', 'id' => 'reconciliation-check', 'label' => ['de' => 'Reconciliation Check', 'en' => 'Reconciliation Check']],
            ['type' => 'glossary', 'id' => 'quarantine-zone', 'label' => ['de' => 'Quarantine Zone', 'en' => 'Quarantine Zone']],
        ],
    ],
    [
        'id' => 'legitimate-interest',
        'order' => 1225,
        'category' => 'privacy',
        'term' => ['de' => 'Legitimate Interest', 'en' => 'Legitimate Interest'],
        'aliases' => ['Berechtigtes Interesse', 'Art. 6 (1) f'],
        'definition' => [
            'de' => 'Rechtsgrundlage nach Abwägung von Interesse und Betroffenenrechten — kein Freifahrtschein ohne Dokumentation.',
            'en' => 'Legal basis after balancing interest vs data-subject rights — not a free pass without documentation.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'lawful-basis', 'label' => ['de' => 'Lawful Basis', 'en' => 'Lawful Basis']],
            ['type' => 'glossary', 'id' => 'consent', 'label' => ['de' => 'Consent', 'en' => 'Consent']],
            ['type' => 'glossary', 'id' => 'dpia', 'label' => ['de' => 'DPIA', 'en' => 'DPIA']],
        ],
    ],
    [
        'id' => 'data-subject',
        'order' => 1226,
        'category' => 'privacy',
        'term' => ['de' => 'Data Subject', 'en' => 'Data Subject'],
        'aliases' => ['Betroffene Person', 'Data Principal'],
        'definition' => [
            'de' => 'Natürliche Person, auf die sich personenbezogene Daten beziehen — Träger von Auskunfts- und Löschrechten.',
            'en' => 'Natural person to whom personal data relate — holder of access and erasure rights.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'right-to-erasure', 'label' => ['de' => 'Right to Erasure', 'en' => 'Right to Erasure']],
            ['type' => 'glossary', 'id' => 'consent-management', 'label' => ['de' => 'Consent Management', 'en' => 'Consent Management']],
            ['type' => 'glossary', 'id' => 'controller-processor', 'label' => ['de' => 'Controller vs Processor', 'en' => 'Controller vs Processor']],
        ],
    ],
    [
        'id' => 'cross-border-transfer',
        'order' => 1227,
        'category' => 'privacy',
        'term' => ['de' => 'Cross-Border Transfer', 'en' => 'Cross-Border Transfer'],
        'aliases' => ['International Transfer', 'Drittlandtransfer'],
        'definition' => [
            'de' => 'Übermittlung personenbezogener Daten in andere Rechtsräume — braucht Transfermechanismus und Risikoanalyse.',
            'en' => 'Transfer of personal data to other jurisdictions — needs a transfer mechanism and risk analysis.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'schrems-ii', 'label' => ['de' => 'Schrems II', 'en' => 'Schrems II']],
            ['type' => 'glossary', 'id' => 'data-residency', 'label' => ['de' => 'Data Residency', 'en' => 'Data Residency']],
            ['type' => 'glossary', 'id' => 'dpia', 'label' => ['de' => 'DPIA', 'en' => 'DPIA']],
        ],
    ],
    [
        'id' => 'schrems-ii',
        'order' => 1228,
        'category' => 'privacy',
        'term' => ['de' => 'Schrems II', 'en' => 'Schrems II'],
        'aliases' => ['Schrems 2', 'CJEU Schrems II'],
        'definition' => [
            'de' => 'EuGH-Urteil zu US-Transfers: Privacy Shield ungültig — Transfer-Impact-Assessments und Zusatzmaßnahmen wurden zentral.',
            'en' => 'CJEU ruling on US transfers: Privacy Shield invalid — transfer impact assessments and supplementary measures became central.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'cross-border-transfer', 'label' => ['de' => 'Cross-Border Transfer', 'en' => 'Cross-Border Transfer']],
            ['type' => 'glossary', 'id' => 'data-residency', 'label' => ['de' => 'Data Residency', 'en' => 'Data Residency']],
            ['type' => 'glossary', 'id' => 'lawful-basis', 'label' => ['de' => 'Lawful Basis', 'en' => 'Lawful Basis']],
        ],
    ],
    [
        'id' => 'retention-policy',
        'order' => 1229,
        'category' => 'privacy',
        'term' => ['de' => 'Retention Policy', 'en' => 'Retention Policy'],
        'aliases' => ['Aufbewahrungsrichtlinie', 'Data Retention Policy'],
        'definition' => [
            'de' => 'Regeln, wie lange welche Daten wofür gehalten werden — ohne technische Durchsetzung bleibt Policy Folklore.',
            'en' => 'Rules for how long which data is kept for what purpose — without technical enforcement, policy is folklore.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'retention-schedule', 'label' => ['de' => 'Retention Schedule', 'en' => 'Retention Schedule']],
            ['type' => 'glossary', 'id' => 'hard-delete', 'label' => ['de' => 'Hard Delete', 'en' => 'Hard Delete']],
            ['type' => 'glossary', 'id' => 'purpose-limitation', 'label' => ['de' => 'Purpose Limitation', 'en' => 'Purpose Limitation']],
        ],
    ],
    [
        'id' => 'workload-identity',
        'order' => 1323,
        'category' => 'security',
        'term' => ['de' => 'Workload Identity', 'en' => 'Workload Identity'],
        'aliases' => ['Workload ID', 'Federated Workload Identity'],
        'definition' => [
            'de' => 'Identität für Workloads (Pods, Jobs) ohne langlebige Secrets — kurzlebige Tokens statt Passwort im Repo.',
            'en' => 'Identity for workloads (pods, jobs) without long-lived secrets — short-lived tokens instead of passwords in repos.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'service-account', 'label' => ['de' => 'Service Account', 'en' => 'Service Account']],
            ['type' => 'glossary', 'id' => 'secrets-management', 'label' => ['de' => 'Secrets Management', 'en' => 'Secrets Management']],
            ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
        ],
    ],
    [
        'id' => 'conditional-access',
        'order' => 1324,
        'category' => 'security',
        'term' => ['de' => 'Conditional Access', 'en' => 'Conditional Access'],
        'aliases' => ['CA Policy', 'Bedingter Zugriff'],
        'definition' => [
            'de' => 'Zugriff hängt von Signalen ab (Gerät, Ort, Risiko) — MFA allein ist oft zu grob.',
            'en' => 'Access depends on signals (device, location, risk) — MFA alone is often too coarse.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'mfa', 'label' => ['de' => 'MFA', 'en' => 'MFA']],
            ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
            ['type' => 'glossary', 'id' => 'jit-access', 'label' => ['de' => 'JIT Access', 'en' => 'JIT Access']],
        ],
    ],
    [
        'id' => 'secrets-rotation',
        'order' => 1325,
        'category' => 'security',
        'term' => ['de' => 'Secrets Rotation', 'en' => 'Secrets Rotation'],
        'aliases' => ['Credential Rotation', 'Key Rotation'],
        'definition' => [
            'de' => 'Regelmäßiges Austauschen von Keys/Passwörtern — ohne Automation bleiben Secrets „ewig gültig“.',
            'en' => 'Regular replacement of keys/passwords — without automation, secrets stay “valid forever”.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'secrets-management', 'label' => ['de' => 'Secrets Management', 'en' => 'Secrets Management']],
            ['type' => 'glossary', 'id' => 'workload-identity', 'label' => ['de' => 'Workload Identity', 'en' => 'Workload Identity']],
            ['type' => 'glossary', 'id' => 'service-account', 'label' => ['de' => 'Service Account', 'en' => 'Service Account']],
        ],
    ],
    [
        'id' => 'identity-provider',
        'order' => 1326,
        'category' => 'security',
        'term' => ['de' => 'Identity Provider', 'en' => 'Identity Provider'],
        'aliases' => ['IdP', 'SSO Provider'],
        'definition' => [
            'de' => 'Zentrale Instanz für Authentifizierung/SSO — Apps vertrauen Tokens statt eigener Passwort-DBs.',
            'en' => 'Central authority for authentication/SSO — apps trust tokens instead of their own password DBs.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'mfa', 'label' => ['de' => 'MFA', 'en' => 'MFA']],
            ['type' => 'glossary', 'id' => 'conditional-access', 'label' => ['de' => 'Conditional Access', 'en' => 'Conditional Access']],
            ['type' => 'glossary', 'id' => 'rbac', 'label' => ['de' => 'RBAC', 'en' => 'RBAC']],
        ],
    ],
    [
        'id' => 'column-profiling',
        'order' => 1520,
        'category' => 'metadata',
        'term' => ['de' => 'Column Profiling', 'en' => 'Column Profiling'],
        'aliases' => ['Data Profiling', 'Profilanalyse'],
        'definition' => [
            'de' => 'Statistiken über Spalten (Nulls, Cardinality, Patterns) — Grundlage für DQ und Catalog-Anreicherung.',
            'en' => 'Statistics about columns (nulls, cardinality, patterns) — basis for DQ and catalog enrichment.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-dictionary', 'label' => ['de' => 'Data Dictionary', 'en' => 'Data Dictionary']],
            ['type' => 'glossary', 'id' => 'null-rate', 'label' => ['de' => 'Null Rate', 'en' => 'Null Rate']],
            ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
        ],
    ],
    [
        'id' => 'data-lineage-graph',
        'order' => 1521,
        'category' => 'metadata',
        'term' => ['de' => 'Data Lineage Graph', 'en' => 'Data Lineage Graph'],
        'aliases' => ['Lineage Graph', 'Provenance Graph'],
        'definition' => [
            'de' => 'Graph von Quellen→Transformationen→Konsumenten — Impact-Analyse braucht Kanten, nicht nur Wiki-Text.',
            'en' => 'Graph from sources→transforms→consumers — impact analysis needs edges, not wiki prose alone.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'column-lineage', 'label' => ['de' => 'Column Lineage', 'en' => 'Column Lineage']],
            ['type' => 'glossary', 'id' => 'openlineage', 'label' => ['de' => 'OpenLineage', 'en' => 'OpenLineage']],
            ['type' => 'glossary', 'id' => 'impact-analysis', 'label' => ['de' => 'Impact Analysis', 'en' => 'Impact Analysis']],
        ],
    ],
    [
        'id' => 'open-metadata',
        'order' => 1522,
        'category' => 'metadata',
        'term' => ['de' => 'Open Metadata', 'en' => 'Open Metadata'],
        'aliases' => ['OpenMetadata', 'Metadata Platform'],
        'definition' => [
            'de' => 'Offene Plattform für Catalog, Lineage und Governance-Workflows — Metadaten als Produkt, nicht Side-Car.',
            'en' => 'Open platform for catalog, lineage, and governance workflows — metadata as a product, not a side-car.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
            ['type' => 'glossary', 'id' => 'active-metadata', 'label' => ['de' => 'Active Metadata', 'en' => 'Active Metadata']],
            ['type' => 'glossary', 'id' => 'openlineage', 'label' => ['de' => 'OpenLineage', 'en' => 'OpenLineage']],
        ],
    ],
    [
        'id' => 'definition-of-ready',
        'order' => 1450,
        'category' => 'process',
        'term' => ['de' => 'Definition of Ready', 'en' => 'Definition of Ready'],
        'aliases' => ['DoR', 'Ready Criteria'],
        'definition' => [
            'de' => 'Kriterien, wann Arbeit startklar ist (Scope, Owner, Datenverfügbarkeit) — verhindert Halbfertig-Starts.',
            'en' => 'Criteria for when work is start-ready (scope, owner, data availability) — prevents half-baked starts.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'definition-of-done', 'label' => ['de' => 'Definition of Done', 'en' => 'Definition of Done']],
            ['type' => 'glossary', 'id' => 'wip-limit', 'label' => ['de' => 'WIP Limit', 'en' => 'WIP Limit']],
            ['type' => 'glossary', 'id' => 'data-product-canvas', 'label' => ['de' => 'Data Product Canvas', 'en' => 'Data Product Canvas']],
        ],
    ],
    [
        'id' => 'incident-severity',
        'order' => 1451,
        'category' => 'process',
        'term' => ['de' => 'Incident Severity', 'en' => 'Incident Severity'],
        'aliases' => ['Sev Level', 'Severity Level'],
        'definition' => [
            'de' => 'Einstufung der Incident-Schwere (Sev1…n) steuert Response-Zeit und Kommandostruktur — ohne Severity wird alles „urgent“.',
            'en' => 'Incident severity rating (Sev1…n) drives response time and command structure — without it, everything is “urgent”.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'incident-commander', 'label' => ['de' => 'Incident Commander', 'en' => 'Incident Commander']],
            ['type' => 'glossary', 'id' => 'error-budget', 'label' => ['de' => 'Error Budget', 'en' => 'Error Budget']],
            ['type' => 'glossary', 'id' => 'runbook', 'label' => ['de' => 'Runbook', 'en' => 'Runbook']],
        ],
    ],
    [
        'id' => 'incident-commander',
        'order' => 1452,
        'category' => 'process',
        'term' => ['de' => 'Incident Commander', 'en' => 'Incident Commander'],
        'aliases' => ['IC', 'Incident Lead'],
        'definition' => [
            'de' => 'Koordiniert Response, Kommunikation und Entscheidungen im Incident — nicht zwingend der tiefste Debugger.',
            'en' => 'Coordinates response, communication, and decisions in an incident — not necessarily the deepest debugger.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'incident-severity', 'label' => ['de' => 'Incident Severity', 'en' => 'Incident Severity']],
            ['type' => 'glossary', 'id' => 'blameless-postmortem', 'label' => ['de' => 'Blameless Postmortem', 'en' => 'Blameless Postmortem']],
            ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
        ],
    ],
    [
        'id' => 'error-budget-policy',
        'order' => 1453,
        'category' => 'process',
        'term' => ['de' => 'Error Budget Policy', 'en' => 'Error Budget Policy'],
        'aliases' => ['EBP', 'Budget Policy'],
        'definition' => [
            'de' => 'Regelt, was passiert wenn das Error Budget aufgebraucht ist (Freeze, Fokus auf Reliability) — Policy ohne Konsequenz ist Theater.',
            'en' => 'Defines what happens when the error budget is spent (freeze, reliability focus) — policy without consequence is theater.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'error-budget', 'label' => ['de' => 'Error Budget', 'en' => 'Error Budget']],
            ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
            ['type' => 'glossary', 'id' => 'sla-slo', 'label' => ['de' => 'SLA/SLO', 'en' => 'SLA/SLO']],
        ],
    ],
    [
        'id' => 'pair-programming',
        'order' => 1454,
        'category' => 'process',
        'term' => ['de' => 'Pair Programming', 'en' => 'Pair Programming'],
        'aliases' => ['Pairing', 'Zwei-Personen-Coding'],
        'definition' => [
            'de' => 'Zwei Personen an einem Problem (Driver/Navigator) — Wissenstransfer und frühe Reviews, nicht „doppelt so teuer“.',
            'en' => 'Two people on one problem (driver/navigator) — knowledge transfer and early review, not “twice the cost”.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'definition-of-done', 'label' => ['de' => 'Definition of Done', 'en' => 'Definition of Done']],
            ['type' => 'glossary', 'id' => 'toil', 'label' => ['de' => 'Toil', 'en' => 'Toil']],
            ['type' => 'glossary', 'id' => 'golden-path', 'label' => ['de' => 'Golden Path', 'en' => 'Golden Path']],
        ],
    ],
    [
        'id' => 'zero-shot-prompting',
        'order' => 1693,
        'category' => 'ai',
        'term' => ['de' => 'Zero-Shot Prompting', 'en' => 'Zero-Shot Prompting'],
        'aliases' => ['Zero-Shot', 'No-Example Prompt'],
        'definition' => [
            'de' => 'Aufgabe ohne Beispiele im Prompt — sparsam am Context, oft schwächer als Few-Shot bei Formataufgaben.',
            'en' => 'Task with no examples in the prompt — cheap on context, often weaker than few-shot for format tasks.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'few-shot-prompting', 'label' => ['de' => 'Few-Shot Prompting', 'en' => 'Few-Shot Prompting']],
            ['type' => 'glossary', 'id' => 'prompt-template', 'label' => ['de' => 'Prompt Template', 'en' => 'Prompt Template']],
            ['type' => 'glossary', 'id' => 'structured-output', 'label' => ['de' => 'Structured Output', 'en' => 'Structured Output']],
        ],
    ],
    [
        'id' => 'system-prompt',
        'order' => 1694,
        'category' => 'ai',
        'term' => ['de' => 'System Prompt', 'en' => 'System Prompt'],
        'aliases' => ['System Message', 'Developer Prompt'],
        'definition' => [
            'de' => 'Steuernde Anweisung mit hoher Priorität (Rolle, Regeln) — gehört versioniert und reviewt wie Code.',
            'en' => 'High-priority steering instruction (role, rules) — should be versioned and reviewed like code.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'prompt-template', 'label' => ['de' => 'Prompt Template', 'en' => 'Prompt Template']],
            ['type' => 'glossary', 'id' => 'ai-guardrails', 'label' => ['de' => 'AI Guardrails', 'en' => 'AI Guardrails']],
            ['type' => 'glossary', 'id' => 'jailbreak', 'label' => ['de' => 'Jailbreak', 'en' => 'Jailbreak']],
        ],
    ],
    [
        'id' => 'prompt-template',
        'order' => 1695,
        'category' => 'ai',
        'term' => ['de' => 'Prompt Template', 'en' => 'Prompt Template'],
        'aliases' => ['Prompt Pattern', 'Templated Prompt'],
        'definition' => [
            'de' => 'Wiederverwendbare Prompt-Struktur mit Platzhaltern — zentral pflegen statt Copy-Paste in zehn Services.',
            'en' => 'Reusable prompt structure with placeholders — maintain centrally instead of copy-paste across ten services.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'system-prompt', 'label' => ['de' => 'System Prompt', 'en' => 'System Prompt']],
            ['type' => 'glossary', 'id' => 'few-shot-prompting', 'label' => ['de' => 'Few-Shot Prompting', 'en' => 'Few-Shot Prompting']],
            ['type' => 'glossary', 'id' => 'eval-harness', 'label' => ['de' => 'Eval Harness', 'en' => 'Eval Harness']],
        ],
    ],
    [
        'id' => 'semantic-caching',
        'order' => 1696,
        'category' => 'ai',
        'term' => ['de' => 'Semantic Caching', 'en' => 'Semantic Caching'],
        'aliases' => ['Embedding Cache', 'Similarity Cache'],
        'definition' => [
            'de' => 'Cached Antworten für semantisch ähnliche Queries — spart Tokens, riskiert stale/falsche Treffer ohne TTL/Policy.',
            'en' => 'Caches answers for semantically similar queries — saves tokens, risks stale/wrong hits without TTL/policy.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'embedding', 'label' => ['de' => 'Embedding', 'en' => 'Embedding']],
            ['type' => 'glossary', 'id' => 'vector-database', 'label' => ['de' => 'Vector Database', 'en' => 'Vector Database']],
            ['type' => 'glossary', 'id' => 'rag', 'label' => ['de' => 'RAG', 'en' => 'RAG']],
        ],
    ],
    [
        'id' => 'groundedness',
        'order' => 1697,
        'category' => 'ai',
        'term' => ['de' => 'Groundedness', 'en' => 'Groundedness'],
        'aliases' => ['Grounded Answer', 'Faithfulness'],
        'definition' => [
            'de' => 'Aussagen sind durch bereitgestellte Quellen gestützt — Messgröße gegen Halluzinationen in RAG.',
            'en' => 'Claims are supported by provided sources — a metric against hallucinations in RAG.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'rag', 'label' => ['de' => 'RAG', 'en' => 'RAG']],
            ['type' => 'glossary', 'id' => 'hallucination', 'label' => ['de' => 'Hallucination', 'en' => 'Hallucination']],
            ['type' => 'glossary', 'id' => 'eval-harness', 'label' => ['de' => 'Eval Harness', 'en' => 'Eval Harness']],
        ],
    ],
    [
        'id' => 'model-routing',
        'order' => 1698,
        'category' => 'ai',
        'term' => ['de' => 'Model Routing', 'en' => 'Model Routing'],
        'aliases' => ['LLM Router', 'Model Cascade'],
        'definition' => [
            'de' => 'Wählt je Request Modell/Route (klein/groß, spezialisiert) nach Kosten, Latenz und Risiko — Governance muss Routen whitelisten.',
            'en' => 'Chooses model/route per request (small/large, specialized) by cost, latency, and risk — governance must whitelist routes.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'ai-guardrails', 'label' => ['de' => 'AI Guardrails', 'en' => 'AI Guardrails']],
            ['type' => 'glossary', 'id' => 'ai-observability', 'label' => ['de' => 'AI Observability', 'en' => 'AI Observability']],
            ['type' => 'glossary', 'id' => 'temperature', 'label' => ['de' => 'Temperature', 'en' => 'Temperature']],
        ],
    ],
    [
        'id' => 'ai-observability',
        'order' => 1699,
        'category' => 'ai',
        'term' => ['de' => 'AI Observability', 'en' => 'AI Observability'],
        'aliases' => ['LLM Observability', 'GenAI Telemetry'],
        'definition' => [
            'de' => 'Traces, Metriken und Evals für Prompts/Agents (Latenz, Kosten, Quality, Safety) — ohne Telemetrie kein Betrieb.',
            'en' => 'Traces, metrics, and evals for prompts/agents (latency, cost, quality, safety) — without telemetry, no operations.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'eval-harness', 'label' => ['de' => 'Eval Harness', 'en' => 'Eval Harness']],
            ['type' => 'glossary', 'id' => 'model-routing', 'label' => ['de' => 'Model Routing', 'en' => 'Model Routing']],
            ['type' => 'glossary', 'id' => 'data-observability', 'label' => ['de' => 'Data Observability', 'en' => 'Data Observability']],
        ],
    ],
    [
        'id' => 'agent-memory',
        'order' => 1700,
        'category' => 'ai',
        'term' => ['de' => 'Agent Memory', 'en' => 'Agent Memory'],
        'aliases' => ['Long-Term Agent Memory', 'Conversation Memory'],
        'definition' => [
            'de' => 'Persistenter Kontext für Agents über Sessions hinweg — braucht Retention, Isolation und Löschpfade.',
            'en' => 'Persistent context for agents across sessions — needs retention, isolation, and deletion paths.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'agentic-workflow', 'label' => ['de' => 'Agentic Workflow', 'en' => 'Agentic Workflow']],
            ['type' => 'glossary', 'id' => 'context-window', 'label' => ['de' => 'Context Window', 'en' => 'Context Window']],
            ['type' => 'glossary', 'id' => 'retention-policy', 'label' => ['de' => 'Retention Policy', 'en' => 'Retention Policy']],
        ],
    ],
];
