<?php

/**
 * Glossary buzzword wave 6 — quiz-friendly terms (distinct defs, clear categories).
 *
 * @return list<array<string, mixed>>
 */
return [
    [
        'id' => 'finops-analyst',
        'order' => 65,
        'category' => 'roles',
        'term' => ['de' => 'FinOps Analyst', 'en' => 'FinOps Analyst'],
        'aliases' => ['Cloud Cost Analyst', 'FinOps Practitioner'],
        'definition' => [
            'de' => 'Analysiert und steuert Cloud-/Daten-Kosten (Showback, Rightsizing) — spart Geld, ersetzt keine Architektur.',
            'en' => 'Analyzes and steers cloud/data costs (showback, rightsizing) — saves money, does not replace architecture.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'finops', 'label' => ['de' => 'FinOps', 'en' => 'FinOps']],
            ['type' => 'glossary', 'id' => 'platform-engineer', 'label' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer']],
            ['type' => 'glossary', 'id' => 'data-product-owner', 'label' => ['de' => 'Data Product Owner', 'en' => 'Data Product Owner']],
        ],
    ],
    [
        'id' => 'information-architect',
        'order' => 66,
        'category' => 'roles',
        'term' => ['de' => 'Information Architect', 'en' => 'Information Architect'],
        'aliases' => ['IA', 'Content Architect'],
        'definition' => [
            'de' => 'Strukturiert Information und Taxonomien für Findability und Governance — Brücke zwischen Content und Data Catalog.',
            'en' => 'Structures information and taxonomies for findability and governance — bridge between content and data catalog.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-architect', 'label' => ['de' => 'Data Architect', 'en' => 'Data Architect']],
            ['type' => 'glossary', 'id' => 'business-glossary', 'label' => ['de' => 'Business Glossary', 'en' => 'Business Glossary']],
            ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
        ],
    ],
    [
        'id' => 'bi-analyst',
        'order' => 67,
        'category' => 'roles',
        'term' => ['de' => 'BI Analyst', 'en' => 'BI Analyst'],
        'aliases' => ['Reporting Analyst', 'Analytics Analyst'],
        'definition' => [
            'de' => 'Baut Reports/Dashboards und übersetzt Fragen in Modelle — näher am Business als reine Pipeline-Engineering-Rolle.',
            'en' => 'Builds reports/dashboards and translates questions into models — closer to business than pure pipeline engineering.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'analytics-engineer', 'label' => ['de' => 'Analytics Engineer', 'en' => 'Analytics Engineer']],
            ['type' => 'glossary', 'id' => 'self-service-bi', 'label' => ['de' => 'Self-Service BI', 'en' => 'Self-Service BI']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
        ],
    ],
    [
        'id' => 'reporting-analyst',
        'order' => 68,
        'category' => 'roles',
        'term' => ['de' => 'Reporting Analyst', 'en' => 'Reporting Analyst'],
        'aliases' => ['Report Developer', 'BI Report Analyst'],
        'definition' => [
            'de' => 'Spezialist für wiederkehrende, governance-konforme Reports — Fokus auf Konsistenz und Distribution, nicht Ad-hoc-Exploration.',
            'en' => 'Specialist for recurring, governed reports — focus on consistency and distribution, not ad-hoc exploration.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'bi-analyst', 'label' => ['de' => 'BI Analyst', 'en' => 'BI Analyst']],
            ['type' => 'glossary', 'id' => 'paginated-report', 'label' => ['de' => 'Paginated Report', 'en' => 'Paginated Report']],
            ['type' => 'glossary', 'id' => 'metric-layer', 'label' => ['de' => 'Metric Layer', 'en' => 'Metric Layer']],
        ],
    ],
    [
        'id' => 'data-democratization',
        'order' => 255,
        'category' => 'data',
        'term' => ['de' => 'Data Democratization', 'en' => 'Data Democratization'],
        'aliases' => ['Democratized Access', 'Data for Everyone'],
        'definition' => [
            'de' => 'Breiter, sicherer Datenzugang für Nicht-Engineers — braucht Guardrails, nicht nur „alle dürfen alles“.',
            'en' => 'Broader, safe data access for non-engineers — needs guardrails, not “everyone may access everything”.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'self-serve-platform', 'label' => ['de' => 'Self-Serve Platform', 'en' => 'Self-Serve Platform']],
            ['type' => 'glossary', 'id' => 'data-literacy', 'label' => ['de' => 'Data Literacy', 'en' => 'Data Literacy']],
            ['type' => 'glossary', 'id' => 'row-level-security', 'label' => ['de' => 'RLS', 'en' => 'RLS']],
        ],
    ],
    [
        'id' => 'data-entitlement',
        'order' => 256,
        'category' => 'data',
        'term' => ['de' => 'Data Entitlement', 'en' => 'Data Entitlement'],
        'aliases' => ['Entitlement', 'Access Entitlement'],
        'definition' => [
            'de' => 'Recht auf bestimmte Datensätze/Spalten für Rolle/Person — technisch durchsetzbar, nicht nur Policy-PDF.',
            'en' => 'Right to specific datasets/columns for role/person — enforceable technically, not policy PDF alone.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'rbac', 'label' => ['de' => 'RBAC', 'en' => 'RBAC']],
            ['type' => 'glossary', 'id' => 'abac', 'label' => ['de' => 'ABAC', 'en' => 'ABAC']],
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
        ],
    ],
    [
        'id' => 'data-monetization',
        'order' => 257,
        'category' => 'data',
        'term' => ['de' => 'Data Monetization', 'en' => 'Data Monetization'],
        'aliases' => ['Monetize Data', 'Data Revenue'],
        'definition' => [
            'de' => 'Daten gezielt in Umsatz/Effizienz übersetzen — braucht Rechtsgrundlage, Qualität und messbaren Nutzen.',
            'en' => 'Turns data deliberately into revenue/efficiency — needs legal basis, quality, and measurable value.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-as-a-product', 'label' => ['de' => 'Data as a Product', 'en' => 'Data as a Product']],
            ['type' => 'glossary', 'id' => 'data-marketplace', 'label' => ['de' => 'Data Marketplace', 'en' => 'Data Marketplace']],
            ['type' => 'glossary', 'id' => 'lawful-basis', 'label' => ['de' => 'Lawful Basis', 'en' => 'Lawful Basis']],
        ],
    ],
    [
        'id' => 'data-product-discovery',
        'order' => 258,
        'category' => 'data',
        'term' => ['de' => 'Data Product Discovery', 'en' => 'Data Product Discovery'],
        'aliases' => ['Product Discovery', 'Find Data Products'],
        'definition' => [
            'de' => 'Nutzer finden passende Datenprodukte im Catalog/Marketplace — ohne Discovery bleibt Mesh nur Architekturfolklore.',
            'en' => 'Users find fitting data products in catalog/marketplace — without discovery, mesh stays architecture folklore.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
            ['type' => 'glossary', 'id' => 'data-marketplace', 'label' => ['de' => 'Data Marketplace', 'en' => 'Data Marketplace']],
            ['type' => 'glossary', 'id' => 'domain-data-product', 'label' => ['de' => 'Domain Data Product', 'en' => 'Domain Data Product']],
        ],
    ],
    [
        'id' => 'federated-computational-governance',
        'order' => 259,
        'category' => 'data',
        'term' => ['de' => 'Federated Computational Governance', 'en' => 'Federated Computational Governance'],
        'aliases' => ['Computational Governance', 'Mesh Governance'],
        'definition' => [
            'de' => 'Globale Standards werden als automatisierte Checks/Policies durchgesetzt — Governance als Code, nicht nur CoE-Slides.',
            'en' => 'Global standards enforced as automated checks/policies — governance as code, not CoE slides alone.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-mesh', 'label' => ['de' => 'Data Mesh', 'en' => 'Data Mesh']],
            ['type' => 'glossary', 'id' => 'policy-as-code', 'label' => ['de' => 'Policy as Code', 'en' => 'Policy as Code']],
            ['type' => 'glossary', 'id' => 'governance-coe', 'label' => ['de' => 'Governance CoE', 'en' => 'Governance CoE']],
        ],
    ],
    [
        'id' => 'anti-corruption-layer',
        'order' => 538,
        'category' => 'architecture',
        'term' => ['de' => 'Anti-Corruption Layer', 'en' => 'Anti-Corruption Layer'],
        'aliases' => ['ACL', 'Translation Layer'],
        'definition' => [
            'de' => 'Übersetzt fremdes/legacy Modell ins eigene Domain-Modell — verhindert, dass Legacy-Sprache das Design infiziert.',
            'en' => 'Translates foreign/legacy model into your domain model — stops legacy language infecting the design.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'bounded-context', 'label' => ['de' => 'Bounded Context', 'en' => 'Bounded Context']],
            ['type' => 'glossary', 'id' => 'strangler-fig', 'label' => ['de' => 'Strangler Fig', 'en' => 'Strangler Fig']],
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
        ],
    ],
    [
        'id' => 'hexagonal-architecture',
        'order' => 539,
        'category' => 'architecture',
        'term' => ['de' => 'Hexagonal Architecture', 'en' => 'Hexagonal Architecture'],
        'aliases' => ['Ports and Adapters', 'Hexagonal'],
        'definition' => [
            'de' => 'Domain-Kern in der Mitte, I/O über Ports/Adapter — testbar und austauschbar ohne Kern zu verbiegen.',
            'en' => 'Domain core in the center, I/O via ports/adapters — testable and swappable without bending the core.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'ports-and-adapters', 'label' => ['de' => 'Ports and Adapters', 'en' => 'Ports and Adapters']],
            ['type' => 'glossary', 'id' => 'domain-driven-design', 'label' => ['de' => 'DDD', 'en' => 'DDD']],
            ['type' => 'glossary', 'id' => 'anti-corruption-layer', 'label' => ['de' => 'Anti-Corruption Layer', 'en' => 'Anti-Corruption Layer']],
        ],
    ],
    [
        'id' => 'ports-and-adapters',
        'order' => 540,
        'category' => 'architecture',
        'term' => ['de' => 'Ports and Adapters', 'en' => 'Ports and Adapters'],
        'aliases' => ['Port/Adapter', 'Hexagonal Ports'],
        'definition' => [
            'de' => 'Port definiert Schnittstelle, Adapter implementiert sie (DB, API, UI) — Kern kennt keine SQL-Details.',
            'en' => 'Port defines interface, adapter implements it (DB, API, UI) — core knows no SQL details.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'hexagonal-architecture', 'label' => ['de' => 'Hexagonal Architecture', 'en' => 'Hexagonal Architecture']],
            ['type' => 'glossary', 'id' => 'platform-engineer', 'label' => ['de' => 'Platform Engineer', 'en' => 'Platform Engineer']],
            ['type' => 'glossary', 'id' => 'data-contract', 'label' => ['de' => 'Data Contract', 'en' => 'Data Contract']],
        ],
    ],
    [
        'id' => 'event-backbone',
        'order' => 541,
        'category' => 'architecture',
        'term' => ['de' => 'Event Backbone', 'en' => 'Event Backbone'],
        'aliases' => ['Event Bus Backbone', 'Streaming Backbone'],
        'definition' => [
            'de' => 'Zentrale Event-Infrastruktur, an die Domains andocken — Skalierung und Schema-Governance sind gemeinsame Aufgabe.',
            'en' => 'Central event infrastructure domains plug into — scaling and schema governance are shared duties.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'event-driven-architecture', 'label' => ['de' => 'EDA', 'en' => 'EDA']],
            ['type' => 'glossary', 'id' => 'streaming', 'label' => ['de' => 'Streaming', 'en' => 'Streaming']],
            ['type' => 'glossary', 'id' => 'schema-registry', 'label' => ['de' => 'Schema Registry', 'en' => 'Schema Registry']],
        ],
    ],
    [
        'id' => 'log-shipping',
        'order' => 542,
        'category' => 'architecture',
        'term' => ['de' => 'Log Shipping', 'en' => 'Log Shipping'],
        'aliases' => ['Log Replication', 'Transaction Log Ship'],
        'definition' => [
            'de' => 'Transaction Logs an Standby/Replica senden — klassisch für DR, Latenz und Failover müssen geplant sein.',
            'en' => 'Ships transaction logs to standby/replica — classic for DR; latency and failover must be planned.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'read-replica', 'label' => ['de' => 'Read Replica', 'en' => 'Read Replica']],
            ['type' => 'glossary', 'id' => 'cdc', 'label' => ['de' => 'CDC', 'en' => 'CDC']],
            ['type' => 'glossary', 'id' => 'rpo', 'label' => ['de' => 'RPO', 'en' => 'RPO']],
        ],
    ],
    [
        'id' => 'hot-path',
        'order' => 543,
        'category' => 'architecture',
        'term' => ['de' => 'Hot Path', 'en' => 'Hot Path'],
        'aliases' => ['Hot Data Path', 'Latency-Critical Path'],
        'definition' => [
            'de' => 'Pfad für latenzkritische Verarbeitung (Realtime/Near-RT) — teurer, muss schlank bleiben.',
            'en' => 'Path for latency-critical processing (real-time/near-RT) — costlier, must stay lean.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'cold-path', 'label' => ['de' => 'Cold Path', 'en' => 'Cold Path']],
            ['type' => 'glossary', 'id' => 'streaming', 'label' => ['de' => 'Streaming', 'en' => 'Streaming']],
            ['type' => 'glossary', 'id' => 'lambda-architecture', 'label' => ['de' => 'Lambda Architecture', 'en' => 'Lambda Architecture']],
        ],
    ],
    [
        'id' => 'cold-path',
        'order' => 544,
        'category' => 'architecture',
        'term' => ['de' => 'Cold Path', 'en' => 'Cold Path'],
        'aliases' => ['Batch Path', 'Offline Path'],
        'definition' => [
            'de' => 'Pfad für Batch/Archiv-Verarbeitung mit höherer Latenz — günstiger, für Historie und schwere Aggregationen.',
            'en' => 'Path for batch/archive processing with higher latency — cheaper, for history and heavy aggregation.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'hot-path', 'label' => ['de' => 'Hot Path', 'en' => 'Hot Path']],
            ['type' => 'glossary', 'id' => 'batch-processing', 'label' => ['de' => 'Batch Processing', 'en' => 'Batch Processing']],
            ['type' => 'glossary', 'id' => 'cold-storage', 'label' => ['de' => 'Cold Storage', 'en' => 'Cold Storage']],
        ],
    ],
    [
        'id' => 'backpressure',
        'order' => 545,
        'category' => 'architecture',
        'term' => ['de' => 'Backpressure', 'en' => 'Backpressure'],
        'aliases' => ['Flow Control', 'Pressure Signal'],
        'definition' => [
            'de' => 'Downstream signalisiert „langsamer“, damit Upstream nicht überläuft — ohne Backpressure crasht Streaming.',
            'en' => 'Downstream signals “slow down” so upstream does not overflow — without backpressure, streaming crashes.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'streaming', 'label' => ['de' => 'Streaming', 'en' => 'Streaming']],
            ['type' => 'glossary', 'id' => 'circuit-breaker', 'label' => ['de' => 'Circuit Breaker', 'en' => 'Circuit Breaker']],
            ['type' => 'glossary', 'id' => 'watermark', 'label' => ['de' => 'Watermark', 'en' => 'Watermark']],
        ],
    ],
    [
        'id' => 'bronze-layer',
        'order' => 732,
        'category' => 'modeling',
        'term' => ['de' => 'Bronze Layer', 'en' => 'Bronze Layer'],
        'aliases' => ['Raw Layer', 'Landing Bronze'],
        'definition' => [
            'de' => 'Roh-/Landing-Zone mit minimaler Transformation — Audit und Replay, keine Business-Logik.',
            'en' => 'Raw/landing zone with minimal transformation — audit and replay, no business logic.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'silver-layer', 'label' => ['de' => 'Silver Layer', 'en' => 'Silver Layer']],
            ['type' => 'glossary', 'id' => 'medallion-architecture', 'label' => ['de' => 'Medallion', 'en' => 'Medallion']],
            ['type' => 'glossary', 'id' => 'landing-raw-layer', 'label' => ['de' => 'Landing Layer', 'en' => 'Landing Layer']],
        ],
    ],
    [
        'id' => 'silver-layer',
        'order' => 733,
        'category' => 'modeling',
        'term' => ['de' => 'Silver Layer', 'en' => 'Silver Layer'],
        'aliases' => ['Conformed Layer', 'Cleansed Layer'],
        'definition' => [
            'de' => 'Bereinigte, konforme Daten — Joins und Qualität, noch nicht mart-spezifisch.',
            'en' => 'Cleansed, conformed data — joins and quality, not yet mart-specific.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'bronze-layer', 'label' => ['de' => 'Bronze Layer', 'en' => 'Bronze Layer']],
            ['type' => 'glossary', 'id' => 'gold-layer', 'label' => ['de' => 'Gold Layer', 'en' => 'Gold Layer']],
            ['type' => 'glossary', 'id' => 'conform-layer', 'label' => ['de' => 'Conform Layer', 'en' => 'Conform Layer']],
        ],
    ],
    [
        'id' => 'gold-layer',
        'order' => 734,
        'category' => 'modeling',
        'term' => ['de' => 'Gold Layer', 'en' => 'Gold Layer'],
        'aliases' => ['Mart Layer', 'Consumption Layer'],
        'definition' => [
            'de' => 'Business-ready Marts/Metrics für Konsumenten — hier lebt Grain und KPI-Definition.',
            'en' => 'Business-ready marts/metrics for consumers — grain and KPI definition live here.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'silver-layer', 'label' => ['de' => 'Silver Layer', 'en' => 'Silver Layer']],
            ['type' => 'glossary', 'id' => 'mart-layer', 'label' => ['de' => 'Mart Layer', 'en' => 'Mart Layer']],
            ['type' => 'glossary', 'id' => 'metric-layer', 'label' => ['de' => 'Metric Layer', 'en' => 'Metric Layer']],
        ],
    ],
    [
        'id' => 'measure-group',
        'order' => 735,
        'category' => 'modeling',
        'term' => ['de' => 'Measure Group', 'en' => 'Measure Group'],
        'aliases' => ['Fact Group', 'Measure Table Group'],
        'definition' => [
            'de' => 'Gruppe verwandter Measures/Facts mit gemeinsamem Grain — falsches Grouping vermischt KPIs.',
            'en' => 'Group of related measures/facts sharing grain — wrong grouping mixes KPIs.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'additive-measure', 'label' => ['de' => 'Additive Measure', 'en' => 'Additive Measure']],
            ['type' => 'glossary', 'id' => 'star-schema', 'label' => ['de' => 'Star Schema', 'en' => 'Star Schema']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
        ],
    ],
    [
        'id' => 'domain-driven-design',
        'order' => 736,
        'category' => 'modeling',
        'term' => ['de' => 'Domain-Driven Design', 'en' => 'Domain-Driven Design'],
        'aliases' => ['DDD', 'Domain Design'],
        'definition' => [
            'de' => 'Modellierung entlang der Fachdomäne (Bounded Contexts, Ubiquitous Language) — nicht umgekehrt nach Tools.',
            'en' => 'Model around the business domain (bounded contexts, ubiquitous language) — not the other way around from tools.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'bounded-context', 'label' => ['de' => 'Bounded Context', 'en' => 'Bounded Context']],
            ['type' => 'glossary', 'id' => 'ubiquitous-language', 'label' => ['de' => 'Ubiquitous Language', 'en' => 'Ubiquitous Language']],
            ['type' => 'glossary', 'id' => 'context-map', 'label' => ['de' => 'Context Map', 'en' => 'Context Map']],
        ],
    ],
    [
        'id' => 'button-slicer',
        'order' => 938,
        'category' => 'bi',
        'term' => ['de' => 'Button Slicer', 'en' => 'Button Slicer'],
        'aliases' => ['Tile Slicer', 'Button Filter'],
        'definition' => [
            'de' => 'Filter als klickbare Buttons/Kacheln — UX-freundlich, aber begrenzte Kardinalität empfohlen.',
            'en' => 'Filter as clickable buttons/tiles — UX-friendly, but limited cardinality recommended.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'sync-slicer', 'label' => ['de' => 'Sync Slicer', 'en' => 'Sync Slicer']],
            ['type' => 'glossary', 'id' => 'field-parameter', 'label' => ['de' => 'Field Parameter', 'en' => 'Field Parameter']],
            ['type' => 'glossary', 'id' => 'self-service-bi', 'label' => ['de' => 'Self-Service BI', 'en' => 'Self-Service BI']],
        ],
    ],
    [
        'id' => 'relative-date-filter',
        'order' => 939,
        'category' => 'bi',
        'term' => ['de' => 'Relative Date Filter', 'en' => 'Relative Date Filter'],
        'aliases' => ['Rolling Date Filter', 'Relative Time Filter'],
        'definition' => [
            'de' => 'Filter wie „letzte 7 Tage“ relativ zum heutigen Datum — dynamisch, Timezone muss stimmen.',
            'en' => 'Filter like “last 7 days” relative to today — dynamic; timezone must be correct.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'time-intelligence', 'label' => ['de' => 'Time Intelligence', 'en' => 'Time Intelligence']],
            ['type' => 'glossary', 'id' => 'page-level-filter', 'label' => ['de' => 'Page Filter', 'en' => 'Page Filter']],
            ['type' => 'glossary', 'id' => 'dax', 'label' => ['de' => 'DAX', 'en' => 'DAX']],
        ],
    ],
    [
        'id' => 'top-n-filter',
        'order' => 940,
        'category' => 'bi',
        'term' => ['de' => 'Top N Filter', 'en' => 'Top N Filter'],
        'aliases' => ['Top/Bottom N', 'Rank Filter'],
        'definition' => [
            'de' => 'Zeigt nur Top/Bottom N nach Measure — Tie-Breaker und Filterkontext müssen dokumentiert sein.',
            'en' => 'Shows only top/bottom N by measure — tie-breaker and filter context must be documented.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'visual-level-filter', 'label' => ['de' => 'Visual Filter', 'en' => 'Visual Filter']],
            ['type' => 'glossary', 'id' => 'dax', 'label' => ['de' => 'DAX', 'en' => 'DAX']],
            ['type' => 'glossary', 'id' => 'semantic-model', 'label' => ['de' => 'Semantic Model', 'en' => 'Semantic Model']],
        ],
    ],
    [
        'id' => 'small-multiples',
        'order' => 941,
        'category' => 'bi',
        'term' => ['de' => 'Small Multiples', 'en' => 'Small Multiples'],
        'aliases' => ['Trellis Chart', 'Panel Chart'],
        'definition' => [
            'de' => 'Gleiche Visualisierung wiederholt pro Kategorie — vergleicht Muster, nicht absolute Skala allein.',
            'en' => 'Same chart repeated per category — compares patterns, not absolute scale alone.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'self-service-bi', 'label' => ['de' => 'Self-Service BI', 'en' => 'Self-Service BI']],
            ['type' => 'glossary', 'id' => 'field-parameter', 'label' => ['de' => 'Field Parameter', 'en' => 'Field Parameter']],
            ['type' => 'glossary', 'id' => 'embedded-analytics', 'label' => ['de' => 'Embedded Analytics', 'en' => 'Embedded Analytics']],
        ],
    ],
    [
        'id' => 'bookmark-navigation',
        'order' => 942,
        'category' => 'bi',
        'term' => ['de' => 'Bookmark Navigation', 'en' => 'Bookmark Navigation'],
        'aliases' => ['Bookmark Buttons', 'Saved View Nav'],
        'definition' => [
            'de' => 'Buttons springen zu gespeicherten Filter-/Seitenzuständen — Guided Analytics statt freier Exploration.',
            'en' => 'Buttons jump to saved filter/page states — guided analytics instead of free exploration.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'bookmark-state', 'label' => ['de' => 'Bookmark State', 'en' => 'Bookmark State']],
            ['type' => 'glossary', 'id' => 'drillthrough', 'label' => ['de' => 'Drillthrough', 'en' => 'Drillthrough']],
            ['type' => 'glossary', 'id' => 'embedded-analytics', 'label' => ['de' => 'Embedded Analytics', 'en' => 'Embedded Analytics']],
        ],
    ],
    [
        'id' => 'timeliness-check',
        'order' => 1134,
        'category' => 'quality',
        'term' => ['de' => 'Timeliness Check', 'en' => 'Timeliness Check'],
        'aliases' => ['Latency Check', 'Aktualitätscheck'],
        'definition' => [
            'de' => 'Prüft, ob Daten rechtzeitig ankommen — unterscheidet sich von Freshness-SLA (Alter seit letztem Load).',
            'en' => 'Checks whether data arrives on time — distinct from freshness SLA (age since last load).',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'freshness-sla', 'label' => ['de' => 'Freshness SLA', 'en' => 'Freshness SLA']],
            ['type' => 'glossary', 'id' => 'data-observability', 'label' => ['de' => 'Data Observability', 'en' => 'Data Observability']],
            ['type' => 'glossary', 'id' => 'sla-slo', 'label' => ['de' => 'SLA/SLO', 'en' => 'SLA/SLO']],
        ],
    ],
    [
        'id' => 'volume-check',
        'order' => 1135,
        'category' => 'quality',
        'term' => ['de' => 'Volume Check', 'en' => 'Volume Check'],
        'aliases' => ['Row Count Check', 'Volume Anomaly Check'],
        'definition' => [
            'de' => 'Überwacht erwartete Zeilenmenge pro Load — plötzliche Halbierung ist oft schlimmer als Schema-Fehler.',
            'en' => 'Monitors expected row volume per load — sudden halving is often worse than a schema error.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'volume-anomaly', 'label' => ['de' => 'Volume Anomaly', 'en' => 'Volume Anomaly']],
            ['type' => 'glossary', 'id' => 'completeness-check', 'label' => ['de' => 'Completeness Check', 'en' => 'Completeness Check']],
            ['type' => 'glossary', 'id' => 'data-observability', 'label' => ['de' => 'Data Observability', 'en' => 'Data Observability']],
        ],
    ],
    [
        'id' => 'range-check',
        'order' => 1136,
        'category' => 'quality',
        'term' => ['de' => 'Range Check', 'en' => 'Range Check'],
        'aliases' => ['Boundary Check', 'Min/Max Check'],
        'definition' => [
            'de' => 'Werte müssen in erlaubtem Intervall liegen — fängt Einheitenfehler und Overflow früh ab.',
            'en' => 'Values must fall in allowed interval — catches unit errors and overflow early.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'validity-rule', 'label' => ['de' => 'Validity Rule', 'en' => 'Validity Rule']],
            ['type' => 'glossary', 'id' => 'expectation-suite', 'label' => ['de' => 'Expectation Suite', 'en' => 'Expectation Suite']],
            ['type' => 'glossary', 'id' => 'conformity-check', 'label' => ['de' => 'Conformity Check', 'en' => 'Conformity Check']],
        ],
    ],
    [
        'id' => 'data-quality-scorecard',
        'order' => 1137,
        'category' => 'quality',
        'term' => ['de' => 'Data Quality Scorecard', 'en' => 'Data Quality Scorecard'],
        'aliases' => ['DQ Scorecard', 'Quality Dashboard'],
        'definition' => [
            'de' => 'Aggregierte Sicht auf DQ-Dimensionen pro Produkt — Score ohne Maßnahmenplan ist Dekoration.',
            'en' => 'Aggregated view of DQ dimensions per product — score without action plan is decoration.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-reliability', 'label' => ['de' => 'Data Reliability', 'en' => 'Data Reliability']],
            ['type' => 'glossary', 'id' => 'data-sla', 'label' => ['de' => 'Data SLA', 'en' => 'Data SLA']],
            ['type' => 'glossary', 'id' => 'shift-left-quality', 'label' => ['de' => 'Shift-Left Quality', 'en' => 'Shift-Left Quality']],
        ],
    ],
    [
        'id' => 'quality-dimension',
        'order' => 1138,
        'category' => 'quality',
        'term' => ['de' => 'Quality Dimension', 'en' => 'Quality Dimension'],
        'aliases' => ['DQ Dimension', 'Data Quality Axis'],
        'definition' => [
            'de' => 'Achse der Datenqualität (Accuracy, Completeness, Timeliness …) — gemeinsames Vokabular für Scorecards.',
            'en' => 'Axis of data quality (accuracy, completeness, timeliness …) — shared vocabulary for scorecards.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'accuracy-check', 'label' => ['de' => 'Accuracy Check', 'en' => 'Accuracy Check']],
            ['type' => 'glossary', 'id' => 'completeness-check', 'label' => ['de' => 'Completeness Check', 'en' => 'Completeness Check']],
            ['type' => 'glossary', 'id' => 'timeliness-check', 'label' => ['de' => 'Timeliness Check', 'en' => 'Timeliness Check']],
        ],
    ],
    [
        'id' => 'privacy-by-default',
        'order' => 1235,
        'category' => 'privacy',
        'term' => ['de' => 'Privacy by Default', 'en' => 'Privacy by Default'],
        'aliases' => ['Default Privacy', 'Datenschutz by Default'],
        'definition' => [
            'de' => 'Restriktivste Privatsphäre-Einstellung ist Standard — Nutzer müssen aktiv erweitern, nicht opt-out kämpfen.',
            'en' => 'Most restrictive privacy setting is default — users must actively expand, not fight opt-out.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'privacy-by-design', 'label' => ['de' => 'Privacy by Design', 'en' => 'Privacy by Design']],
            ['type' => 'glossary', 'id' => 'data-minimization', 'label' => ['de' => 'Data Minimization', 'en' => 'Data Minimization']],
            ['type' => 'glossary', 'id' => 'consent-management', 'label' => ['de' => 'Consent Management', 'en' => 'Consent Management']],
        ],
    ],
    [
        'id' => 'transfer-impact-assessment',
        'order' => 1236,
        'category' => 'privacy',
        'term' => ['de' => 'Transfer Impact Assessment', 'en' => 'Transfer Impact Assessment'],
        'aliases' => ['TIA', 'Transfer Risk Assessment'],
        'definition' => [
            'de' => 'Risikoanalyse für Drittlandtransfers nach Schrems II — ergänzt SCCs, ersetzt sie nicht.',
            'en' => 'Risk analysis for third-country transfers post-Schrems II — complements SCCs, does not replace them.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'schrems-ii', 'label' => ['de' => 'Schrems II', 'en' => 'Schrems II']],
            ['type' => 'glossary', 'id' => 'standard-contractual-clauses', 'label' => ['de' => 'SCCs', 'en' => 'SCCs']],
            ['type' => 'glossary', 'id' => 'cross-border-transfer', 'label' => ['de' => 'Cross-Border Transfer', 'en' => 'Cross-Border Transfer']],
        ],
    ],
    [
        'id' => 'sub-processor',
        'order' => 1237,
        'category' => 'privacy',
        'term' => ['de' => 'Sub-Processor', 'en' => 'Sub-Processor'],
        'aliases' => ['Subprocessor', 'Unterauftragsverarbeiter'],
        'definition' => [
            'de' => 'Processor beauftragt weiteren Dienstleister — Kette muss im DPA transparent und kontrollierbar sein.',
            'en' => 'Processor engages another vendor — chain must be transparent and controllable in the DPA.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-processing-agreement', 'label' => ['de' => 'DPA', 'en' => 'DPA']],
            ['type' => 'glossary', 'id' => 'controller-processor', 'label' => ['de' => 'Controller vs Processor', 'en' => 'Controller vs Processor']],
            ['type' => 'glossary', 'id' => 'cross-border-transfer', 'label' => ['de' => 'Cross-Border Transfer', 'en' => 'Cross-Border Transfer']],
        ],
    ],
    [
        'id' => 'consent-record',
        'order' => 1238,
        'category' => 'privacy',
        'term' => ['de' => 'Consent Record', 'en' => 'Consent Record'],
        'aliases' => ['Consent Log', 'Einwilligungsnachweis'],
        'definition' => [
            'de' => 'Nachweis wer wann wofür eingewilligt hat — muss an Downstream-Systeme propagierbar sein.',
            'en' => 'Proof of who consented to what and when — must propagate to downstream systems.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'consent-management', 'label' => ['de' => 'Consent Management', 'en' => 'Consent Management']],
            ['type' => 'glossary', 'id' => 'consent', 'label' => ['de' => 'Consent', 'en' => 'Consent']],
            ['type' => 'glossary', 'id' => 'purpose-limitation', 'label' => ['de' => 'Purpose Limitation', 'en' => 'Purpose Limitation']],
        ],
    ],
    [
        'id' => 'threat-modeling',
        'order' => 1332,
        'category' => 'security',
        'term' => ['de' => 'Threat Modeling', 'en' => 'Threat Modeling'],
        'aliases' => ['STRIDE Session', 'Threat Model'],
        'definition' => [
            'de' => 'Systematische Analyse von Bedrohungen und Mitigations — vor Go-Live, nicht nach dem Incident.',
            'en' => 'Systematic analysis of threats and mitigations — before go-live, not after the incident.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'attack-surface', 'label' => ['de' => 'Attack Surface', 'en' => 'Attack Surface']],
            ['type' => 'glossary', 'id' => 'zero-trust', 'label' => ['de' => 'Zero Trust', 'en' => 'Zero Trust']],
            ['type' => 'glossary', 'id' => 'dpia', 'label' => ['de' => 'DPIA', 'en' => 'DPIA']],
        ],
    ],
    [
        'id' => 'attack-surface',
        'order' => 1333,
        'category' => 'security',
        'term' => ['de' => 'Attack Surface', 'en' => 'Attack Surface'],
        'aliases' => ['Exposure Surface', 'Angriffsfläche'],
        'definition' => [
            'de' => 'Summe exponierter Entry Points (APIs, Accounts, Datenexports) — verkleinern schlägt mehr Alerts.',
            'en' => 'Sum of exposed entry points (APIs, accounts, data exports) — shrinking beats more alerts.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'threat-modeling', 'label' => ['de' => 'Threat Modeling', 'en' => 'Threat Modeling']],
            ['type' => 'glossary', 'id' => 'least-privilege', 'label' => ['de' => 'Least Privilege', 'en' => 'Least Privilege']],
            ['type' => 'glossary', 'id' => 'network-segmentation', 'label' => ['de' => 'Network Segmentation', 'en' => 'Network Segmentation']],
        ],
    ],
    [
        'id' => 'public-key-infrastructure',
        'order' => 1334,
        'category' => 'security',
        'term' => ['de' => 'Public Key Infrastructure', 'en' => 'Public Key Infrastructure'],
        'aliases' => ['PKI', 'Certificate Infrastructure'],
        'definition' => [
            'de' => 'Infrastruktur für Zertifikate und Trust Chains — Basis für mTLS und signierte Tokens.',
            'en' => 'Infrastructure for certificates and trust chains — foundation for mTLS and signed tokens.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'mutual-tls', 'label' => ['de' => 'mTLS', 'en' => 'mTLS']],
            ['type' => 'glossary', 'id' => 'secrets-management', 'label' => ['de' => 'Secrets Management', 'en' => 'Secrets Management']],
            ['type' => 'glossary', 'id' => 'service-mesh', 'label' => ['de' => 'Service Mesh', 'en' => 'Service Mesh']],
        ],
    ],
    [
        'id' => 'phishing-resistant-mfa',
        'order' => 1335,
        'category' => 'security',
        'term' => ['de' => 'Phishing-Resistant MFA', 'en' => 'Phishing-Resistant MFA'],
        'aliases' => ['FIDO2 MFA', 'Passkey MFA'],
        'definition' => [
            'de' => 'MFA, das Replay/Phishing erschwert (z. B. FIDO2) — SMS-Codes zählen nicht.',
            'en' => 'MFA that resists replay/phishing (e.g. FIDO2) — SMS codes do not count.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'mfa', 'label' => ['de' => 'MFA', 'en' => 'MFA']],
            ['type' => 'glossary', 'id' => 'conditional-access', 'label' => ['de' => 'Conditional Access', 'en' => 'Conditional Access']],
            ['type' => 'glossary', 'id' => 'identity-provider', 'label' => ['de' => 'Identity Provider', 'en' => 'Identity Provider']],
        ],
    ],
    [
        'id' => 'semantic-metadata',
        'order' => 1525,
        'category' => 'metadata',
        'term' => ['de' => 'Semantic Metadata', 'en' => 'Semantic Metadata'],
        'aliases' => ['Business Semantics', 'Semantic Layer Metadata'],
        'definition' => [
            'de' => 'Metadaten über Bedeutung (Begriffe, KPIs, Synonyme) — verbindet Glossary mit technischen Assets.',
            'en' => 'Metadata about meaning (terms, KPIs, synonyms) — links glossary to technical assets.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'business-glossary-term', 'label' => ['de' => 'Glossary Term', 'en' => 'Glossary Term']],
            ['type' => 'glossary', 'id' => 'semantic-layer', 'label' => ['de' => 'Semantic Layer', 'en' => 'Semantic Layer']],
            ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
        ],
    ],
    [
        'id' => 'catalog-ingestion',
        'order' => 1526,
        'category' => 'metadata',
        'term' => ['de' => 'Catalog Ingestion', 'en' => 'Catalog Ingestion'],
        'aliases' => ['Metadata Ingestion', 'Harvest to Catalog'],
        'definition' => [
            'de' => 'Automatisches Einspeisen technischer Metadaten in den Catalog — ohne Enrichment nur Inventar.',
            'en' => 'Automatic loading of technical metadata into the catalog — without enrichment, just inventory.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'data-catalog', 'label' => ['de' => 'Data Catalog', 'en' => 'Data Catalog']],
            ['type' => 'glossary', 'id' => 'column-profiling', 'label' => ['de' => 'Column Profiling', 'en' => 'Column Profiling']],
            ['type' => 'glossary', 'id' => 'openlineage', 'label' => ['de' => 'OpenLineage', 'en' => 'OpenLineage']],
        ],
    ],
    [
        'id' => 'ubiquitous-language',
        'order' => 1459,
        'category' => 'process',
        'term' => ['de' => 'Ubiquitous Language', 'en' => 'Ubiquitous Language'],
        'aliases' => ['Shared Language', 'Domain Language'],
        'definition' => [
            'de' => 'Gemeinsame, präzise Begriffe in Team und Code — verhindert „Umsatz“-Synonyme in SQL und Slides.',
            'en' => 'Shared, precise terms in team and code — prevents “revenue” synonyms in SQL and slides.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'domain-driven-design', 'label' => ['de' => 'DDD', 'en' => 'DDD']],
            ['type' => 'glossary', 'id' => 'business-glossary', 'label' => ['de' => 'Business Glossary', 'en' => 'Business Glossary']],
            ['type' => 'glossary', 'id' => 'bounded-context', 'label' => ['de' => 'Bounded Context', 'en' => 'Bounded Context']],
        ],
    ],
    [
        'id' => 'context-map',
        'order' => 1460,
        'category' => 'process',
        'term' => ['de' => 'Context Map', 'en' => 'Context Map'],
        'aliases' => ['DDD Context Map', 'Domain Map'],
        'definition' => [
            'de' => 'Visualisiert Beziehungen zwischen Bounded Contexts (upstream/downstream) — klärt Integration und Ownership.',
            'en' => 'Visualizes relationships between bounded contexts (upstream/downstream) — clarifies integration and ownership.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'bounded-context', 'label' => ['de' => 'Bounded Context', 'en' => 'Bounded Context']],
            ['type' => 'glossary', 'id' => 'domain-driven-design', 'label' => ['de' => 'DDD', 'en' => 'DDD']],
            ['type' => 'glossary', 'id' => 'data-mesh', 'label' => ['de' => 'Data Mesh', 'en' => 'Data Mesh']],
        ],
    ],
    [
        'id' => 'trunk-based-development',
        'order' => 1461,
        'category' => 'process',
        'term' => ['de' => 'Trunk-Based Development', 'en' => 'Trunk-Based Development'],
        'aliases' => ['Trunk-Based', 'Mainline Development'],
        'definition' => [
            'de' => 'Kurzlebige Branches, häufiger Merge in main — passt zu CI/CD und DataOps-Pipelines.',
            'en' => 'Short-lived branches, frequent merge to main — fits CI/CD and DataOps pipelines.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'continuous-delivery', 'label' => ['de' => 'Continuous Delivery', 'en' => 'Continuous Delivery']],
            ['type' => 'glossary', 'id' => 'dataops', 'label' => ['de' => 'DataOps', 'en' => 'DataOps']],
            ['type' => 'glossary', 'id' => 'feature-flag', 'label' => ['de' => 'Feature Flag', 'en' => 'Feature Flag']],
        ],
    ],
    [
        'id' => 'game-day',
        'order' => 1462,
        'category' => 'process',
        'term' => ['de' => 'Game Day', 'en' => 'Game Day'],
        'aliases' => ['DR Game Day', 'Resilience Exercise'],
        'definition' => [
            'de' => 'Geplanter Stresstest/Incident-Übung in Prod-ähnlicher Umgebung — findet Lücken vor echten Ausfällen.',
            'en' => 'Planned stress test/incident exercise in prod-like env — finds gaps before real outages.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'chaos-engineering', 'label' => ['de' => 'Chaos Engineering', 'en' => 'Chaos Engineering']],
            ['type' => 'glossary', 'id' => 'runbook', 'label' => ['de' => 'Runbook', 'en' => 'Runbook']],
            ['type' => 'glossary', 'id' => 'rto', 'label' => ['de' => 'RTO', 'en' => 'RTO']],
        ],
    ],
    [
        'id' => 'on-call-rotation',
        'order' => 1463,
        'category' => 'process',
        'term' => ['de' => 'On-Call Rotation', 'en' => 'On-Call Rotation'],
        'aliases' => ['Pager Rotation', 'Duty Rotation'],
        'definition' => [
            'de' => 'Plan, wer Alerts/Incidents wann trägt — ohne Rotation verbrennt ein Hero und Wissen bleibt siloed.',
            'en' => 'Schedule of who carries alerts/incidents when — without rotation, one hero burns out and knowledge silos.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'sre', 'label' => ['de' => 'SRE', 'en' => 'SRE']],
            ['type' => 'glossary', 'id' => 'incident-commander', 'label' => ['de' => 'Incident Commander', 'en' => 'Incident Commander']],
            ['type' => 'glossary', 'id' => 'runbook', 'label' => ['de' => 'Runbook', 'en' => 'Runbook']],
        ],
    ],
    [
        'id' => 'embedding-model',
        'order' => 1707,
        'category' => 'ai',
        'term' => ['de' => 'Embedding Model', 'en' => 'Embedding Model'],
        'aliases' => ['Embedding Encoder', 'Vector Model'],
        'definition' => [
            'de' => 'Modell, das Text in Vektoren abbildet — Wahl des Modells beeinflusst Retrieval-Qualität und Kosten.',
            'en' => 'Model that maps text to vectors — model choice affects retrieval quality and cost.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'embedding', 'label' => ['de' => 'Embedding', 'en' => 'Embedding']],
            ['type' => 'glossary', 'id' => 'vector-database', 'label' => ['de' => 'Vector Database', 'en' => 'Vector Database']],
            ['type' => 'glossary', 'id' => 'chunking-strategy', 'label' => ['de' => 'Chunking Strategy', 'en' => 'Chunking Strategy']],
        ],
    ],
    [
        'id' => 'cross-encoder',
        'order' => 1708,
        'category' => 'ai',
        'term' => ['de' => 'Cross-Encoder', 'en' => 'Cross-Encoder'],
        'aliases' => ['Cross Encoder', 'Pairwise Scorer'],
        'definition' => [
            'de' => 'Bewertet Query-Dokument-Paare gemeinsam — präziser als Bi-Encoder, teurer für große Kandidatenmengen.',
            'en' => 'Scores query-document pairs jointly — more precise than bi-encoder, costlier at large candidate sets.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'reranker', 'label' => ['de' => 'Reranker', 'en' => 'Reranker']],
            ['type' => 'glossary', 'id' => 'hybrid-search', 'label' => ['de' => 'Hybrid Search', 'en' => 'Hybrid Search']],
            ['type' => 'glossary', 'id' => 'rag', 'label' => ['de' => 'RAG', 'en' => 'RAG']],
        ],
    ],
    [
        'id' => 'tool-schema',
        'order' => 1709,
        'category' => 'ai',
        'term' => ['de' => 'Tool Schema', 'en' => 'Tool Schema'],
        'aliases' => ['Function Schema', 'JSON Schema for Tools'],
        'definition' => [
            'de' => 'Maschinenlesbare Beschreibung erlaubter Tool-Parameter — ohne Schema halluziniert das Modell Argumente.',
            'en' => 'Machine-readable description of allowed tool parameters — without schema, models hallucinate arguments.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'tool-calling', 'label' => ['de' => 'Tool Calling', 'en' => 'Tool Calling']],
            ['type' => 'glossary', 'id' => 'structured-output', 'label' => ['de' => 'Structured Output', 'en' => 'Structured Output']],
            ['type' => 'glossary', 'id' => 'model-context-protocol', 'label' => ['de' => 'MCP', 'en' => 'MCP']],
        ],
    ],
    [
        'id' => 'agent-planner',
        'order' => 1710,
        'category' => 'ai',
        'term' => ['de' => 'Agent Planner', 'en' => 'Agent Planner'],
        'aliases' => ['Planning Agent', 'Task Planner'],
        'definition' => [
            'de' => 'Komponente, die Schritte/Tools plant bevor ausgeführt wird — ohne Planner wird Agent zu ReAct-Roulette.',
            'en' => 'Component that plans steps/tools before execution — without planner, agent becomes ReAct roulette.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'agent-executor', 'label' => ['de' => 'Agent Executor', 'en' => 'Agent Executor']],
            ['type' => 'glossary', 'id' => 'agentic-workflow', 'label' => ['de' => 'Agentic Workflow', 'en' => 'Agentic Workflow']],
            ['type' => 'glossary', 'id' => 'ai-guardrails', 'label' => ['de' => 'AI Guardrails', 'en' => 'AI Guardrails']],
        ],
    ],
    [
        'id' => 'agent-executor',
        'order' => 1711,
        'category' => 'ai',
        'term' => ['de' => 'Agent Executor', 'en' => 'Agent Executor'],
        'aliases' => ['Execution Agent', 'Tool Runner'],
        'definition' => [
            'de' => 'Führt geplante Tool-Calls aus und sammelt Ergebnisse — braucht Timeouts, Retries und Audit-Log.',
            'en' => 'Runs planned tool calls and collects results — needs timeouts, retries, and audit log.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'agent-planner', 'label' => ['de' => 'Agent Planner', 'en' => 'Agent Planner']],
            ['type' => 'glossary', 'id' => 'tool-calling', 'label' => ['de' => 'Tool Calling', 'en' => 'Tool Calling']],
            ['type' => 'glossary', 'id' => 'ai-observability', 'label' => ['de' => 'AI Observability', 'en' => 'AI Observability']],
        ],
    ],
    [
        'id' => 'output-moderation',
        'order' => 1712,
        'category' => 'ai',
        'term' => ['de' => 'Output Moderation', 'en' => 'Output Moderation'],
        'aliases' => ['Response Moderation', 'Content Moderation'],
        'definition' => [
            'de' => 'Filter/Classifier auf Modell-Ausgabe (Toxicity, PII, Policy) — Input-Guard allein reicht nicht.',
            'en' => 'Filters/classifiers on model output (toxicity, PII, policy) — input guard alone is not enough.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'ai-guardrails', 'label' => ['de' => 'AI Guardrails', 'en' => 'AI Guardrails']],
            ['type' => 'glossary', 'id' => 'prompt-injection', 'label' => ['de' => 'Prompt Injection', 'en' => 'Prompt Injection']],
            ['type' => 'glossary', 'id' => 'human-in-the-loop', 'label' => ['de' => 'Human-in-the-Loop', 'en' => 'Human-in-the-Loop']],
        ],
    ],
    [
        'id' => 'human-feedback-loop',
        'order' => 1713,
        'category' => 'ai',
        'term' => ['de' => 'Human Feedback Loop', 'en' => 'Human Feedback Loop'],
        'aliases' => ['HITL Feedback', 'RLHF Loop'],
        'definition' => [
            'de' => 'Menschen bewerten/korrigieren Modell-Outputs für Training oder Live-Eskalation — braucht klare Rubrics.',
            'en' => 'Humans rate/correct model outputs for training or live escalation — needs clear rubrics.',
        ],
        'related' => [
            ['type' => 'glossary', 'id' => 'human-in-the-loop', 'label' => ['de' => 'Human-in-the-Loop', 'en' => 'Human-in-the-Loop']],
            ['type' => 'glossary', 'id' => 'rlhf', 'label' => ['de' => 'RLHF', 'en' => 'RLHF']],
            ['type' => 'glossary', 'id' => 'eval-harness', 'label' => ['de' => 'Eval Harness', 'en' => 'Eval Harness']],
        ],
    ],
];
