<?php

return [
    'sources' => [
        [
            'id' => 'edpb-news',
            'name' => 'European Data Protection Board',
            'short_name' => 'EDPB',
            'type' => 'Regulator',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'GDPR', 'AI Governance', 'Richtlinien'],
            'source_url' => 'https://www.edpb.europa.eu/news_en',
            'feed_url' => 'https://www.edpb.europa.eu/news_en',
            'note' => 'Offizielle News und Veröffentlichungen rund um GDPR, Leitlinien, nationale Aufsichtsbehörden und EDPB-Entscheidungen.',
            'priority' => 'high',
        ],
        [
            'id' => 'edps-newsletter',
            'name' => 'European Data Protection Supervisor',
            'short_name' => 'EDPS',
            'type' => 'Regulator',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'monthly',
            'topics' => ['Datenschutz', 'AI Act', 'EU Institutionen', 'Richtlinien'],
            'source_url' => 'https://www.edps.europa.eu/press-publications/publications/newsletters_en',
            'feed_url' => 'https://www.edps.europa.eu/press-publications/publications/newsletters_en',
            'note' => 'Newsletter und Positionsübersichten zu Datenschutz, AI Act, EU-Institutionen und Aufsichtspraxis.',
            'priority' => 'high',
        ],
        [
            'id' => 'ico-rss',
            'name' => 'Information Commissioner’s Office',
            'short_name' => 'ICO',
            'type' => 'Regulator',
            'region' => 'UK',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Enforcement', 'Decision Notices'],
            'source_url' => 'https://ico.org.uk/global/rss-feeds/',
            'feed_url' => 'https://ico.org.uk/global/rss-feeds/',
            'note' => 'RSS-Übersicht für News, Blogs, Enforcement und Decision Notices.',
            'priority' => 'medium',
        ],
        [
            'id' => 'lfdi-bw',
            'name' => 'LfDI Baden-Württemberg',
            'short_name' => 'LfDI BW',
            'type' => 'Regulator',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Informationsfreiheit', 'KI', 'Praxishilfen'],
            'source_url' => 'https://www.baden-wuerttemberg.datenschutz.de/newsfeeds/',
            'feed_url' => 'https://www.baden-wuerttemberg.datenschutz.de/newsfeeds/',
            'note' => 'Deutsche Datenschutz-Newsfeeds, Pressemitteilungen und Praxishilfen.',
            'priority' => 'high',
        ],
        [
            'id' => 'nist-frameworks',
            'name' => 'National Institute of Standards and Technology',
            'short_name' => 'NIST',
            'type' => 'Standard',
            'region' => 'US',
            'language' => 'en',
            'cadence' => 'monthly',
            'topics' => ['Privacy Framework', 'Cybersecurity', 'Risk Management', 'AI Governance'],
            'source_url' => 'https://www.nist.gov/frameworks',
            'feed_url' => 'https://www.nist.gov/frameworks',
            'note' => 'Standards und Frameworks für Privacy, Cybersecurity, AI Risk und Risk Management.',
            'priority' => 'high',
        ],
        [
            'id' => 'nist-csrc-news',
            'name' => 'NIST Computer Security Resource Center',
            'short_name' => 'NIST CSRC',
            'type' => 'Standard',
            'region' => 'US',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Cybersecurity', 'Privacy', 'Risk Management', 'Supplier Governance'],
            'source_url' => 'https://csrc.nist.gov/news/',
            'feed_url' => 'https://csrc.nist.gov/news/',
            'note' => 'News und Updates zu Security-, Privacy-, Supplier- und Risk-Management-Publikationen.',
            'priority' => 'high',
        ],
        [
            'id' => 'snowflake-release-notes',
            'name' => 'Snowflake Documentation',
            'short_name' => 'Snowflake',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Data Clean Rooms', 'Catalog', 'Security'],
            'source_url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'feed_url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'note' => 'Release Notes für Governance-relevante Features, Policy-Änderungen, Clean Rooms und Catalog-Funktionen.',
            'priority' => 'medium',
        ],
        [
            'id' => 'databricks-governance',
            'name' => 'Databricks Documentation',
            'short_name' => 'Databricks',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Unity Catalog', 'Lineage', 'Data Quality', 'AI Governance'],
            'source_url' => 'https://docs.databricks.com/aws/en/data-governance',
            'feed_url' => 'https://docs.databricks.com/aws/en/data-governance',
            'note' => 'Governance-Dokumentation zu Unity Catalog, Discovery, Classification, DQ Monitoring und AI Governance.',
            'priority' => 'medium',
        ],
        [
            'id' => 'binom-editorial',
            'name' => 'binom-tools Redaktion',
            'short_name' => 'binom',
            'type' => 'Eigene News',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'manual',
            'topics' => ['Eigene News', 'Best Practices', 'Playbooks'],
            'source_url' => '/governance/radar',
            'feed_url' => null,
            'note' => 'Eigene kuratierte Hinweise, Best Practices, Playbook-Updates und interne Governance-Notizen.',
            'priority' => 'high',
        ],
    ],
    'items' => [
        [
            'id' => 'edpb-ai-anonymisierung-blockchain',
            'source_id' => 'edpb-news',
            'title' => 'EDPB: Anonymisierung, Web Scraping und Blockchain-Leitlinien beobachten',
            'summary' => 'Für Governance-Projekte mit AI, Webdaten, Blockchain oder Analytics auf personenbezogenen Daten sollte diese Quelle regelmäßig geprüft werden.',
            'published_at' => '2026-07-08',
            'type' => 'Richtlinien',
            'impact' => 'Prüfen',
            'region' => 'EU',
            'topics' => ['Datenschutz', 'AI Governance', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Bei AI- oder Web-Scraping-Projekten als Review-Aufgabe in den Governance Plan übernehmen.',
        ],
        [
            'id' => 'edpb-cross-regulatory-sharing',
            'source_id' => 'edpb-news',
            'title' => 'EDPB: Cross-regulatory Information Sharing als Governance-Risiko verfolgen',
            'summary' => 'Relevant, wenn Daten zwischen Datenschutz, Wettbewerb, Finanzaufsicht, AML oder sektoralen Regulatoren bewertet werden müssen.',
            'published_at' => '2026-07-17',
            'type' => 'Richtlinien',
            'impact' => 'Relevant',
            'region' => 'EU',
            'topics' => ['Datenschutz', 'Compliance', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Als Legal-/Compliance-Abhängigkeit markieren, bevor Data Sharing oder Clean-Room-Szenarien freigegeben werden.',
        ],
        [
            'id' => 'nist-privacy-framework-11',
            'source_id' => 'nist-frameworks',
            'title' => 'NIST Privacy Framework 1.1 und CSF 2.0 Mapping einplanen',
            'summary' => 'Privacy, Cybersecurity und AI-Risk sollten im Governance Radar gemeinsam betrachtet werden, statt getrennte Checklisten zu pflegen.',
            'published_at' => '2025-04-14',
            'type' => 'Standard',
            'impact' => 'Prüfen',
            'region' => 'US',
            'topics' => ['Privacy Framework', 'Cybersecurity', 'AI Governance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.nist.gov/frameworks',
            'recommended_action' => 'Framework-Mapping als Lernplan oder Governance-Review-Aufgabe starten.',
        ],
        [
            'id' => 'edpb-annual-report-2025',
            'source_id' => 'edpb-news',
            'title' => 'EDPB Annual Report 2025 als Governance-Lagebild lesen',
            'summary' => 'Der Jahresbericht zeigt, welche Datenschutzthemen, Leitlinien und Abstimmungen für Governance-Programme in Europa wichtig bleiben.',
            'published_at' => '2026-05-04',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'EU',
            'topics' => ['Datenschutz', 'Operating Model', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Als Quartals-Review im Governance-Backlog aufnehmen und gegen eigene Policies spiegeln.',
        ],
        [
            'id' => 'edpb-dpia-template',
            'source_id' => 'edpb-news',
            'title' => 'EDPB DPIA Template für Risiko- und Datenschutzbewertungen aufnehmen',
            'summary' => 'Ein einheitlicher DPIA-Baustein hilft, neue Quellen, AI-Use-Cases, PII-Flüsse und Data-Sharing-Fragen konsistenter zu bewerten.',
            'published_at' => '2026-04-14',
            'type' => 'Governance News',
            'impact' => 'Prüfen',
            'region' => 'EU',
            'topics' => ['DPIA', 'PII', 'Risiko', 'Datenschutz'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'DPIA-Prüfung als Standard-Gate in PII/DSDR- und Source-Scope-Workflows ergänzen.',
        ],
        [
            'id' => 'edpb-transparency-enforcement',
            'source_id' => 'edpb-news',
            'title' => 'EDPB CEF 2026: Transparenz und Informationspflichten beobachten',
            'summary' => 'Transparenzpflichten betreffen nicht nur Legal-Texte, sondern auch Datenkatalog, Report-Kontext, Zweckbindung und Betroffenenkommunikation.',
            'published_at' => '2026-03-19',
            'type' => 'Governance News',
            'impact' => 'Handlungsbedarf',
            'region' => 'EU',
            'topics' => ['Transparenz', 'Katalog', 'PII', 'Compliance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Bei personenbezogenen Reports prüfen, ob Zweck, Datenherkunft, Owner und Löschlogik dokumentiert sind.',
        ],
        [
            'id' => 'nist-system-plans-privacy-scrm',
            'source_id' => 'nist-csrc-news',
            'title' => 'NIST SP 800-18r2: Security, Privacy und Supply Chain als verbundene Systempläne behandeln',
            'summary' => 'Systemplanung wird breiter gedacht: Security, Privacy und Cybersecurity Supply Chain Risk Management gehören in ein gemeinsames Planungsmodell.',
            'published_at' => '2026-06-30',
            'type' => 'Standard',
            'impact' => 'Architektur prüfen',
            'region' => 'US',
            'topics' => ['Risk Management', 'Supplier Governance', 'Privacy', 'Security'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://csrc.nist.gov/news/',
            'recommended_action' => 'Für neue Plattformen einen Hauptplan mit parallelem Supplier-/Security-/Privacy-Pfad vorbereiten.',
        ],
        [
            'id' => 'nist-supplier-due-diligence',
            'source_id' => 'nist-csrc-news',
            'title' => 'NIST Supplier Quick-Start Guide für Vendor- und Datenquellen-Checks berücksichtigen',
            'summary' => 'Supplier Governance braucht einen Mindeststandard für Recherche, Nachweise, Risiken und Entscheidungsvorlagen, bevor Quellen angebunden werden.',
            'published_at' => '2026-07-08',
            'type' => 'Governance News',
            'impact' => 'Handlungsbedarf',
            'region' => 'US',
            'topics' => ['Supplier Governance', 'Vendor Risk', 'Nachweise'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://csrc.nist.gov/news/',
            'recommended_action' => 'Als Checkliste in Supplier Library, Source Scope Builder und Decision Brief übernehmen.',
        ],
        [
            'id' => 'snowflake-clean-rooms-update',
            'source_id' => 'snowflake-release-notes',
            'title' => 'Snowflake: Clean Rooms, Catalog und Policy Release Notes monitoren',
            'summary' => 'Vendor-Änderungen können Auswirkungen auf Data Sharing, Clean Rooms, Governance Policies und Migrationen haben.',
            'published_at' => '2026-07-23',
            'type' => 'Vendor Update',
            'impact' => 'Handlungsbedarf',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Data Clean Rooms', 'Security'],
            'stack' => ['Snowflake', 'dbt'],
            'url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'recommended_action' => 'Bei Snowflake-Umgebungen als Change-Request-Kandidat prüfen.',
        ],
        [
            'id' => 'databricks-unity-catalog-governance',
            'source_id' => 'databricks-governance',
            'title' => 'Databricks: Unity Catalog Governance-Funktionen regelmäßig prüfen',
            'summary' => 'Lineage, Classification, Discovery, Quality Monitoring und AI Governance sind Kernsignale für Databricks-Governance-Entscheidungen.',
            'published_at' => '2026-07-22',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Unity Catalog', 'Lineage', 'Data Quality', 'AI Governance'],
            'stack' => ['Databricks'],
            'url' => 'https://docs.databricks.com/aws/en/data-governance',
            'recommended_action' => 'Mit Governance Stack Advisor und Vendor Learning Path Builder verbinden.',
        ],
        [
            'id' => 'lfdi-ki-praxishilfen',
            'source_id' => 'lfdi-bw',
            'title' => 'LfDI BW: Praxishilfen zu KI und Datenschutz als deutsche Referenz aufnehmen',
            'summary' => 'Für deutsche Workshops sind lokale Datenschutz-Praxishilfen oft verständlicher als rein internationale Frameworks.',
            'published_at' => '2026-06-11',
            'type' => 'Praxishilfe',
            'impact' => 'Relevant',
            'region' => 'DE',
            'topics' => ['Datenschutz', 'KI', 'Praxishilfen'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.baden-wuerttemberg.datenschutz.de/newsfeeds/',
            'recommended_action' => 'Als Nachweisquelle in PII/DSDR- und AI-Governance-Checks verlinken.',
        ],
        [
            'id' => 'binom-source-governance-watchlist',
            'source_id' => 'binom-editorial',
            'title' => 'Eigene Watchlist: Source, KPI, PII und DQ nicht getrennt entscheiden',
            'summary' => 'Neue Quellen sollten im Radar direkt mit KPI-Anforderungen, PII/DSDR, DQ-Regeln und Mart-Entscheidungen verbunden werden.',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Info',
            'region' => 'DE',
            'topics' => ['Eigene News', 'Best Practices', 'Data Quality'],
            'stack' => ['Alle Stacks'],
            'url' => '/governance',
            'recommended_action' => 'Als Standard-Hinweis im Governance Advisor und in Tool-Reports verwenden.',
        ],
        [
            'id' => 'binom-data-ownership-operating-model',
            'source_id' => 'binom-editorial',
            'title' => 'Data Ownership nicht als Organigramm, sondern als Entscheidungsrecht pflegen',
            'summary' => 'Owner, Steward, Approver und Konsument müssen wissen, welche Entscheidung sie treffen, freigeben oder nur prüfen.',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Best Practice',
            'region' => 'DE',
            'topics' => ['Data Ownership', 'RACI', 'Operating Model'],
            'stack' => ['Alle Stacks'],
            'url' => '/tools/stakeholder-matrix',
            'recommended_action' => 'Stakeholder Matrix und Decision Brief als Pflichtbausteine für kritische KPIs und Quellen nutzen.',
        ],
        [
            'id' => 'binom-dq-as-governance-signal',
            'source_id' => 'binom-editorial',
            'title' => 'Data Quality als Governance-Signal statt als reines Technik-Ticket behandeln',
            'summary' => 'DQ-Regeln sollten zeigen, welche Entscheidung gefährdet ist, welche Quelle betroffen ist und wer die Ausnahme freigeben darf.',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Best Practice',
            'region' => 'DE',
            'topics' => ['Data Quality', 'KPI', 'Owner', 'Workflow'],
            'stack' => ['Alle Stacks'],
            'url' => '/tools/dbt-dq-rules-generator',
            'recommended_action' => 'DQ Advisor, KPI Intake und dbt DQ Rules Generator zusammen nutzen, damit Regeln fachlich begründet sind.',
        ],
        [
            'id' => 'binom-metadata-minimum',
            'source_id' => 'binom-editorial',
            'title' => 'Metadata Minimum: Geschäftsfrage, Quelle, PII, DQ und Owner zuerst erfassen',
            'summary' => 'Viele Governance-Probleme entstehen, weil technische Tabellen vor der fachlichen Entscheidung dokumentiert werden.',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Best Practice',
            'region' => 'DE',
            'topics' => ['Metadata', 'Katalog', 'Source Scope', 'KPI'],
            'stack' => ['Alle Stacks'],
            'url' => '/tools/source-scope-builder',
            'recommended_action' => 'Collect-Info-Workflow starten, bevor Mart Design oder Reporting-Implementierung begonnen wird.',
        ],
    ],
];
