<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Radar type icons
    |--------------------------------------------------------------------------
    | Types keep a fixed order, icons, and light/dark-capable color tones.
    */
    'type_meta' => [
        'Security News' => [
            'icon' => 'fa-shield-halved',
            'tone' => 'security',
            'order' => 10,
            'label' => ['de' => 'Security News', 'en' => 'Security News'],
        ],
        'Vendor Update' => [
            'icon' => 'fa-cube',
            'tone' => 'vendor',
            'order' => 20,
            'label' => ['de' => 'Vendor Update', 'en' => 'Vendor Update'],
        ],
        'Richtlinien' => [
            'icon' => 'fa-scale-balanced',
            'tone' => 'policy',
            'order' => 30,
            'label' => ['de' => 'Richtlinien', 'en' => 'Guidelines'],
        ],
        'Standard' => [
            'icon' => 'fa-book',
            'tone' => 'standard',
            'order' => 40,
            'label' => ['de' => 'Standard', 'en' => 'Standard'],
        ],
        'Governance News' => [
            'icon' => 'fa-newspaper',
            'tone' => 'news',
            'order' => 50,
            'label' => ['de' => 'Governance News', 'en' => 'Governance News'],
        ],
        'Praxishilfe' => [
            'icon' => 'fa-lightbulb',
            'tone' => 'practice',
            'order' => 60,
            'label' => ['de' => 'Praxishilfe', 'en' => 'Practice guide'],
        ],
        'Eigene News' => [
            'icon' => 'fa-pen',
            'tone' => 'editorial',
            'order' => 70,
            'label' => ['de' => 'Eigene News', 'en' => 'Editorial'],
        ],
    ],
    'sources' => [
        [
            'id' => 'edpb-news',
            'name' => 'European Data Protection Board',
            'short_name' => 'EDPB',
            'type' => 'Regulator',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'GDPR', 'AI Governance', 'Richtlinien'],
            'source_url' => 'https://www.edpb.europa.eu/news_en',
            'feed_url' => 'https://www.edpb.europa.eu/news_en',
            'note' => 'Offizielle News und Veröffentlichungen rund um GDPR, Leitlinien, nationale Aufsichtsbehörden und EDPB-Entscheidungen.',
            'priority' => 'high',
        ],
        [
            'id' => 'edps-newsletter',
            'name' => 'European Data Protection Supervisor',
            'short_name' => 'EDPS',
            'type' => 'Regulator',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'monthly',
            'topics' => ['Datenschutz', 'AI Act', 'EU Institutionen', 'Richtlinien'],
            'source_url' => 'https://www.edps.europa.eu/press-publications/publications/newsletters_en',
            'feed_url' => 'https://www.edps.europa.eu/press-publications/publications/newsletters_en',
            'note' => 'Newsletter und Positionsübersichten zu Datenschutz, AI Act, EU-Institutionen und Aufsichtspraxis.',
            'priority' => 'high',
        ],
        [
            'id' => 'ico-rss',
            'name' => 'Information Commissioner’s Office',
            'short_name' => 'ICO',
            'type' => 'Regulator',
            'region' => 'UK',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Enforcement', 'Decision Notices'],
            'source_url' => 'https://ico.org.uk/global/rss-feeds/',
            'feed_url' => 'https://ico.org.uk/global/rss-feeds/',
            'note' => 'RSS-Übersicht für News, Blogs, Enforcement und Decision Notices.',
            'priority' => 'medium',
        ],
        [
            'id' => 'lfdi-bw',
            'name' => 'LfDI Baden-Württemberg',
            'short_name' => 'LfDI BW',
            'type' => 'Regulator',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Informationsfreiheit', 'KI', 'Praxishilfen'],
            'source_url' => 'https://www.baden-wuerttemberg.datenschutz.de/newsfeeds/',
            'feed_url' => 'https://www.baden-wuerttemberg.datenschutz.de/newsfeeds/',
            'note' => 'Deutsche Datenschutz-Newsfeeds, Pressemitteilungen und Praxishilfen.',
            'priority' => 'high',
        ],
        [
            'id' => 'nist-frameworks',
            'name' => 'National Institute of Standards and Technology',
            'short_name' => 'NIST',
            'type' => 'Standard',
            'region' => 'US',
            'language' => 'en',
            'cadence' => 'monthly',
            'topics' => ['Privacy Framework', 'Cybersecurity', 'Risk Management', 'AI Governance'],
            'source_url' => 'https://www.nist.gov/frameworks',
            'feed_url' => 'https://www.nist.gov/frameworks',
            'note' => 'Standards und Frameworks für Privacy, Cybersecurity, AI Risk und Risk Management.',
            'priority' => 'high',
        ],
        [
            'id' => 'nist-csrc-news',
            'name' => 'NIST Computer Security Resource Center',
            'short_name' => 'NIST CSRC',
            'type' => 'Standard',
            'region' => 'US',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Cybersecurity', 'Privacy', 'Risk Management', 'Supplier Governance'],
            'source_url' => 'https://csrc.nist.gov/news/',
            'feed_url' => 'https://csrc.nist.gov/news/',
            'note' => 'News und Updates zu Security-, Privacy-, Supplier- und Risk-Management-Publikationen.',
            'priority' => 'high',
        ],
        [
            'id' => 'snowflake-release-notes',
            'name' => 'Snowflake Documentation',
            'short_name' => 'Snowflake',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Data Clean Rooms', 'Catalog', 'Security'],
            'source_url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'feed_url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'note' => 'Release Notes für Governance-relevante Features, Policy-Änderungen, Clean Rooms und Catalog-Funktionen.',
            'priority' => 'medium',
        ],
        [
            'id' => 'databricks-governance',
            'name' => 'Databricks Documentation',
            'short_name' => 'Databricks',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Unity Catalog', 'Lineage', 'Data Quality', 'AI Governance'],
            'source_url' => 'https://docs.databricks.com/aws/en/data-governance',
            'feed_url' => 'https://docs.databricks.com/aws/en/data-governance',
            'note' => 'Governance-Dokumentation zu Unity Catalog, Discovery, Classification, DQ Monitoring und AI Governance.',
            'priority' => 'medium',
        ],
        [
            'id' => 'bfdi',
            'name' => 'Bundesbeauftragte für den Datenschutz und die Informationsfreiheit',
            'short_name' => 'BfDI',
            'type' => 'Regulator',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Data Act', 'Informationsfreiheit', 'KI'],
            'source_url' => 'https://www.bfdi.bund.de/DE/BfDI/Presse/Pressemitteilungen/pressemitteilungen_node.html',
            'feed_url' => 'https://www.bfdi.bund.de/DE/BfDI/Presse/Pressemitteilungen/pressemitteilungen_node.html',
            'note' => 'Nationale DE-Aufsicht: Pressemitteilungen zu Data Act, KI, Transparenz und Tätigkeitsberichten.',
            'priority' => 'high',
        ],
        [
            'id' => 'cnil',
            'name' => 'Commission Nationale de l’Informatique et des Libertés',
            'short_name' => 'CNIL',
            'type' => 'Regulator',
            'region' => 'FR',
            'language' => 'fr',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'AI Governance', 'Data Governance Act', 'Praxishilfen'],
            'source_url' => 'https://www.cnil.fr/en/news',
            'feed_url' => 'https://www.cnil.fr/en/rss.xml',
            'note' => 'Französische Aufsicht mit starken Praxisleitfäden zu AI, Transparenz und Data Governance.',
            'priority' => 'high',
        ],
        [
            'id' => 'dpc-ireland',
            'name' => 'Data Protection Commission Ireland',
            'short_name' => 'DPC',
            'type' => 'Regulator',
            'region' => 'IE',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Enforcement', 'AI Governance', 'Cross-border'],
            'source_url' => 'https://www.dataprotection.ie/en/news-media/latest-news',
            'feed_url' => 'https://www.dataprotection.ie/en/news-media/latest-news',
            'note' => 'Lead-Aufsicht für viele Big-Tech-/AI-Fälle und Cross-Border-Enforcement in der EU.',
            'priority' => 'high',
        ],
        [
            'id' => 'enisa',
            'name' => 'European Union Agency for Cybersecurity',
            'short_name' => 'ENISA',
            'type' => 'Standard',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Cybersecurity', 'NIS2', 'Risk Management', 'Supplier Governance'],
            'source_url' => 'https://www.enisa.europa.eu/news',
            'feed_url' => 'https://www.enisa.europa.eu/news',
            'note' => 'Cyber-/Risk-Guidance mit Schnittstellen zu NIS2, Supply Chain und Governance-Controls.',
            'priority' => 'medium',
        ],
        [
            'id' => 'eu-ai-office',
            'name' => 'European AI Office / Digital Strategy',
            'short_name' => 'EU AI',
            'type' => 'Regulator',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['AI Act', 'AI Governance', 'Data Act', 'Digital Markets'],
            'source_url' => 'https://digital-strategy.ec.europa.eu/en/news',
            'feed_url' => 'https://digital-strategy.ec.europa.eu/en/rss.xml',
            'note' => 'EU-Updates zu AI Act, Data Act und digitaler Regulierung mit Governance-Impact.',
            'priority' => 'high',
        ],
        [
            'id' => 'iapp',
            'name' => 'International Association of Privacy Professionals',
            'short_name' => 'IAPP',
            'type' => 'Community',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'daily',
            'topics' => ['Datenschutz', 'AI Governance', 'Compliance', 'Operating Model'],
            'source_url' => 'https://iapp.org/news/',
            'feed_url' => 'https://iapp.org/news/a/rss/',
            'note' => 'Kuratierte Privacy-/Governance-News und Analyse zu Enforcement und Cross-Regulatory-Themen.',
            'priority' => 'medium',
        ],
        [
            'id' => 'noyb',
            'name' => 'NOYB – European Center for Digital Rights',
            'short_name' => 'NOYB',
            'type' => 'Community',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Enforcement', 'Cookies', 'Complaints'],
            'source_url' => 'https://noyb.eu/en/news',
            'feed_url' => 'https://noyb.eu/en/rss.xml',
            'note' => 'Advocacy- und Complaint-Signale zu GDPR-Enforcement — klar als NGO/Community labeln.',
            'priority' => 'medium',
        ],
        [
            'id' => 'microsoft-purview',
            'name' => 'Microsoft Purview / Fabric Governance',
            'short_name' => 'Purview',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Catalog', 'Lineage', 'PII', 'Vendor Updates'],
            'source_url' => 'https://learn.microsoft.com/en-us/purview/',
            'feed_url' => 'https://learn.microsoft.com/api/search/rss?search=%22Microsoft+Purview%22&locale=en-us',
            'note' => 'Vendor-Docs zu Catalog, Classification, Data Loss Prevention und Fabric Governance.',
            'priority' => 'medium',
        ],
        [
            'id' => 'dbt-blog',
            'name' => 'dbt Labs Blog',
            'short_name' => 'dbt',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Data Quality', 'Metadata', 'Best Practices', 'Vendor Updates'],
            'source_url' => 'https://www.getdbt.com/blog',
            'feed_url' => 'https://www.getdbt.com/blog/rss.xml',
            'note' => 'Praxis zu Analytics Engineering, Tests, Docs und Governance-nahen Workflows.',
            'priority' => 'medium',
        ],
        [
            'id' => 'snowflake-security',
            'name' => 'Snowflake Trust Center / Security',
            'short_name' => 'Snowflake Sec',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Security', 'Vendor Updates', 'Authentication', 'Trust Center'],
            'source_url' => 'https://docs.snowflake.com/en/user-guide/trust-center',
            'feed_url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'note' => 'Security-, Auth- und Trust-Center-Updates parallel zu Feature Release Notes.',
            'priority' => 'high',
        ],
        [
            'id' => 'databricks-release-notes',
            'name' => 'Databricks Platform Release Notes',
            'short_name' => 'Databricks RN',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Security', 'Unity Catalog', 'AI Governance'],
            'source_url' => 'https://docs.databricks.com/aws/en/release-notes/',
            'feed_url' => 'https://docs.databricks.com/aws/en/release-notes/',
            'note' => 'Plattform-, Security- und Governance-Feature-Updates für Databricks Workspaces.',
            'priority' => 'high',
        ],
        [
            'id' => 'microsoft-fabric-whats-new',
            'name' => 'Microsoft Fabric What’s new',
            'short_name' => 'Fabric',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Catalog', 'Security', 'Semantic Models'],
            'source_url' => 'https://learn.microsoft.com/en-us/fabric/get-started/whats-new',
            'feed_url' => 'https://learn.microsoft.com/api/search/rss?search=%22Microsoft+Fabric%22&locale=en-us',
            'note' => 'Fabric Feature- und Governance-Updates inkl. Workspace-, Security- und Semantic-Model-Änderungen.',
            'priority' => 'high',
        ],
        [
            'id' => 'power-bi-blog',
            'name' => 'Power BI Blog / Service Updates',
            'short_name' => 'Power BI',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Security', 'Semantic Models', 'RLS'],
            'source_url' => 'https://powerbi.microsoft.com/en-us/blog/',
            'feed_url' => 'https://powerbi.microsoft.com/en-us/blog/feed/',
            'note' => 'Service Updates zu Security, Sharing, RLS und Governance-relevanten Report-Features.',
            'priority' => 'medium',
        ],
        [
            'id' => 'qlik-release-notes',
            'name' => 'Qlik Cloud Release Notes',
            'short_name' => 'Qlik',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Security', 'Catalog', 'Access Control'],
            'source_url' => 'https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Introduction/saas-change-log.htm',
            'feed_url' => 'https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Introduction/saas-change-log.htm',
            'note' => 'Qlik Cloud Change Log für Security, Spaces, Access Control und Catalog-nahe Änderungen.',
            'priority' => 'medium',
        ],
        [
            'id' => 'tableau-release-notes',
            'name' => 'Tableau Release Notes / Security',
            'short_name' => 'Tableau',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Security', 'Permissions', 'Catalog'],
            'source_url' => 'https://www.tableau.com/support/releases',
            'feed_url' => 'https://www.tableau.com/support/releases',
            'note' => 'Tableau Desktop/Server/Cloud Releases inkl. Security Fixes und Permission-Änderungen.',
            'priority' => 'medium',
        ],
        [
            'id' => 'oecd-privacy',
            'name' => 'OECD Digital / Privacy',
            'short_name' => 'OECD',
            'type' => 'Standard',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'monthly',
            'topics' => ['Privacy Framework', 'AI Governance', 'Data Governance', 'Policy'],
            'source_url' => 'https://www.oecd.org/en/topics/policy-issues/data-governance-and-privacy.html',
            'feed_url' => 'https://www.oecd.org/en/topics/policy-issues/data-governance-and-privacy.html',
            'note' => 'Policy-Frameworks zu Data Governance, Privacy und vertrauenswürdigem Datenaustausch.',
            'priority' => 'low',
        ],
        [
            'id' => 'binom-editorial',
            'name' => 'binom-tools Redaktion',
            'short_name' => 'binom',
            'type' => 'Eigene News',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'manual',
            'topics' => ['Eigene News', 'Best Practices', 'Playbooks'],
            'source_url' => '/governance/radar',
            'feed_url' => null,
            'note' => 'Eigene kuratierte Hinweise, Best Practices, Playbook-Updates und interne Governance-Notizen.',
            'priority' => 'high',
        ],
    ],
    'items' => [
        [
            'id' => 'edpb-ai-anonymisierung-blockchain',
            'source_id' => 'edpb-news',
            'title' => 'EDPB: Anonymisierung, Web Scraping und Blockchain-Leitlinien beobachten',
            'summary' => 'Für Governance-Projekte mit AI, Webdaten, Blockchain oder Analytics auf personenbezogenen Daten sollte diese Quelle regelmäßig geprüft werden.',
            'published_at' => '2026-07-08',
            'type' => 'Richtlinien',
            'impact' => 'Prüfen',
            'region' => 'EU',
            'topics' => ['Datenschutz', 'AI Governance', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Quelle lesen und bei AI-/Web-Scraping-Projekten gegen eigene Use Cases spiegeln.',
        ],
        [
            'id' => 'edpb-cross-regulatory-sharing',
            'source_id' => 'edpb-news',
            'title' => 'EDPB: Cross-regulatory Information Sharing als Governance-Risiko verfolgen',
            'summary' => 'Relevant, wenn Daten zwischen Datenschutz, Wettbewerb, Finanzaufsicht, AML oder sektoralen Regulatoren bewertet werden müssen.',
            'published_at' => '2026-07-17',
            'type' => 'Richtlinien',
            'impact' => 'Relevant',
            'region' => 'EU',
            'topics' => ['Datenschutz', 'Compliance', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Beobachten, wenn Data Sharing oder Clean-Room-Szenarien anstehen — ohne sofortigen Plan.',
        ],
        [
            'id' => 'nist-privacy-framework-11',
            'source_id' => 'nist-frameworks',
            'title' => 'NIST Privacy Framework 1.1 und CSF 2.0 Mapping einplanen',
            'summary' => 'Privacy, Cybersecurity und AI-Risk sollten im Governance Radar gemeinsam betrachtet werden, statt getrennte Checklisten zu pflegen.',
            'published_at' => '2025-04-14',
            'type' => 'Standard',
            'impact' => 'Prüfen',
            'region' => 'US',
            'topics' => ['Privacy Framework', 'Cybersecurity', 'AI Governance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.nist.gov/frameworks',
            'recommended_action' => 'Framework-Mapping prüfen und nur bei Lücken im eigenen Stack in den Advisor nehmen.',
        ],
        [
            'id' => 'edpb-annual-report-2025',
            'source_id' => 'edpb-news',
            'title' => 'EDPB Annual Report 2025 als Governance-Lagebild lesen',
            'summary' => 'Der Jahresbericht zeigt, welche Datenschutzthemen, Leitlinien und Abstimmungen für Governance-Programme in Europa wichtig bleiben.',
            'published_at' => '2026-05-04',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'EU',
            'topics' => ['Datenschutz', 'Operating Model', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Zum Lesen und Orientieren — gegen eigene Policies spiegeln, ohne neuen Plan zu starten.',
        ],
        [
            'id' => 'edpb-dpia-template',
            'source_id' => 'edpb-news',
            'title' => 'EDPB DPIA Template für Risiko- und Datenschutzbewertungen aufnehmen',
            'summary' => 'Ein einheitlicher DPIA-Baustein hilft, neue Quellen, AI-Use-Cases, PII-Flüsse und Data-Sharing-Fragen konsistenter zu bewerten.',
            'published_at' => '2026-04-14',
            'type' => 'Governance News',
            'impact' => 'Prüfen',
            'region' => 'EU',
            'topics' => ['DPIA', 'PII', 'Risiko', 'Datenschutz'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Template lesen und prüfen, ob PII/DSDR- und Source-Scope-Checks davon profitieren.',
        ],
        [
            'id' => 'edpb-transparency-enforcement',
            'source_id' => 'edpb-news',
            'title' => 'EDPB CEF 2026: Transparenz und Informationspflichten beobachten',
            'summary' => 'Transparenzpflichten betreffen nicht nur Legal-Texte, sondern auch Datenkatalog, Report-Kontext, Zweckbindung und Betroffenenkommunikation.',
            'published_at' => '2026-03-19',
            'type' => 'Governance News',
            'impact' => 'Handlungsbedarf',
            'region' => 'EU',
            'topics' => ['Transparenz', 'Katalog', 'PII', 'Compliance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Bei personenbezogenen Reports Zweck, Datenherkunft, Owner und Löschlogik im Advisor prüfen.',
        ],
        [
            'id' => 'nist-system-plans-privacy-scrm',
            'source_id' => 'nist-csrc-news',
            'title' => 'NIST SP 800-18r2: Security, Privacy und Supply Chain als verbundene Systempläne behandeln',
            'summary' => 'Systemplanung wird breiter gedacht: Security, Privacy und Cybersecurity Supply Chain Risk Management gehören in ein gemeinsames Planungsmodell.',
            'published_at' => '2026-06-30',
            'type' => 'Standard',
            'impact' => 'Architektur prüfen',
            'region' => 'US',
            'topics' => ['Risk Management', 'Supplier Governance', 'Privacy', 'Security'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://csrc.nist.gov/news/',
            'recommended_action' => 'Bei neuen Plattformen Security-/Privacy-/Supplier-Pfade im Advisor gegen die Architektur halten.',
        ],
        [
            'id' => 'nist-supplier-due-diligence',
            'source_id' => 'nist-csrc-news',
            'title' => 'NIST Supplier Quick-Start Guide für Vendor- und Datenquellen-Checks berücksichtigen',
            'summary' => 'Supplier Governance braucht einen Mindeststandard für Recherche, Nachweise, Risiken und Entscheidungsvorlagen, bevor Quellen angebunden werden.',
            'published_at' => '2026-07-08',
            'type' => 'Governance News',
            'impact' => 'Handlungsbedarf',
            'region' => 'US',
            'topics' => ['Supplier Governance', 'Vendor Risk', 'Nachweise'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://csrc.nist.gov/news/',
            'recommended_action' => 'Guide lesen und offene Vendor-/Quellen-Checks im Advisor nachziehen.',
        ],
        [
            'id' => 'snowflake-clean-rooms-update',
            'source_id' => 'snowflake-release-notes',
            'title' => 'Snowflake: Clean Rooms, Catalog und Policy Release Notes monitoren',
            'summary' => 'Vendor-Änderungen können Auswirkungen auf Data Sharing, Clean Rooms, Governance Policies und Migrationen haben.',
            'published_at' => '2026-07-23',
            'type' => 'Vendor Update',
            'impact' => 'Handlungsbedarf',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Data Clean Rooms', 'Security'],
            'stack' => ['Snowflake', 'dbt'],
            'url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'recommended_action' => 'Release Notes prüfen und bei Snowflake-Umgebungen betroffene Policies im Advisor bewerten.',
        ],
        [
            'id' => 'databricks-unity-catalog-governance',
            'source_id' => 'databricks-governance',
            'title' => 'Databricks: Unity Catalog Governance-Funktionen regelmäßig prüfen',
            'summary' => 'Lineage, Classification, Discovery, Quality Monitoring und AI Governance sind Kernsignale für Databricks-Governance-Entscheidungen.',
            'published_at' => '2026-07-22',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Unity Catalog', 'Lineage', 'Data Quality', 'AI Governance'],
            'stack' => ['Databricks'],
            'url' => 'https://docs.databricks.com/aws/en/data-governance',
            'recommended_action' => 'Dokumentation beobachten — bei neuen Features gegen den eigenen Databricks-Stack spiegeln.',
        ],
        [
            'id' => 'lfdi-ki-praxishilfen',
            'source_id' => 'lfdi-bw',
            'title' => 'LfDI BW: Praxishilfen zu KI und Datenschutz als deutsche Referenz aufnehmen',
            'summary' => 'Für deutsche Workshops sind lokale Datenschutz-Praxishilfen oft verständlicher als rein internationale Frameworks.',
            'published_at' => '2026-06-11',
            'type' => 'Praxishilfe',
            'impact' => 'Relevant',
            'region' => 'DE',
            'topics' => ['Datenschutz', 'KI', 'Praxishilfen'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.baden-wuerttemberg.datenschutz.de/newsfeeds/',
            'recommended_action' => 'Als Referenz lesen und bei Bedarf in Workshops oder Checks verlinken.',
        ],
        [
            'id' => 'binom-source-governance-watchlist',
            'source_id' => 'binom-editorial',
            'title' => 'Eigene Watchlist: Source, KPI, PII und DQ nicht getrennt entscheiden',
            'summary' => 'Neue Quellen sollten im Radar direkt mit KPI-Anforderungen, PII/DSDR, DQ-Regeln und Mart-Entscheidungen verbunden werden.',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Info',
            'region' => 'DE',
            'topics' => ['Eigene News', 'Best Practices', 'Data Quality'],
            'stack' => ['Alle Stacks'],
            'url' => '/governance',
            'recommended_action' => 'Als Merksatz behalten — nicht automatisch einen neuen Workflow starten.',
        ],
        [
            'id' => 'binom-data-ownership-operating-model',
            'source_id' => 'binom-editorial',
            'title' => 'Data Ownership nicht als Organigramm, sondern als Entscheidungsrecht pflegen',
            'summary' => 'Owner, Steward, Approver und Konsument müssen wissen, welche Entscheidung sie treffen, freigeben oder nur prüfen.',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Best Practice',
            'region' => 'DE',
            'topics' => ['Data Ownership', 'RACI', 'Operating Model'],
            'stack' => ['Alle Stacks'],
            'url' => '/tools/stakeholder-matrix',
            'recommended_action' => 'Bei kritischen KPIs und Quellen die Stakeholder Matrix als Hilfsmittel öffnen.',
        ],
        [
            'id' => 'binom-dq-as-governance-signal',
            'source_id' => 'binom-editorial',
            'title' => 'Data Quality als Governance-Signal statt als reines Technik-Ticket behandeln',
            'summary' => 'DQ-Regeln sollten zeigen, welche Entscheidung gefährdet ist, welche Quelle betroffen ist und wer die Ausnahme freigeben darf.',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Best Practice',
            'region' => 'DE',
            'topics' => ['Data Quality', 'KPI', 'Owner', 'Workflow'],
            'stack' => ['Alle Stacks'],
            'url' => '/tools/dbt-dq-rules-generator',
            'recommended_action' => 'DQ-Regeln fachlich begründen — Tools nur öffnen, wenn eine Regel ansteht.',
        ],
        [
            'id' => 'binom-metadata-minimum',
            'source_id' => 'binom-editorial',
            'title' => 'Metadata Minimum: Geschäftsfrage, Quelle, PII, DQ und Owner zuerst erfassen',
            'summary' => 'Viele Governance-Probleme entstehen, weil technische Tabellen vor der fachlichen Entscheidung dokumentiert werden.',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Best Practice',
            'region' => 'DE',
            'topics' => ['Metadata', 'Katalog', 'Source Scope', 'KPI'],
            'stack' => ['Alle Stacks'],
            'url' => '/tools/source-scope-builder',
            'recommended_action' => 'Vor Mart Design oder Reporting zuerst Scope und Ownership klären — bei Bedarf Source Scope Builder öffnen.',
        ],
        [
            'id' => 'bfdi-data-act-aufsicht',
            'source_id' => 'bfdi',
            'title' => 'BfDI: Datenschutzaufsicht nach dem Data Act beobachten',
            'summary' => 'Mit dem DADG überwacht die BfDI Data-Act-Anwendungen, soweit personenbezogene Daten betroffen sind — relevant für IoT-, Sharing- und Plattform-Szenarien.',
            'published_at' => '2026-05-29',
            'type' => 'Governance News',
            'impact' => 'Prüfen',
            'region' => 'DE',
            'topics' => ['Data Act', 'Datenschutz', 'Compliance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.bfdi.bund.de/SharedDocs/Pressemitteilungen/DE/2026/07_Data-Act-Datenschutzaufsicht.html',
            'recommended_action' => 'Prüfen, ob Data-Sharing- oder Geräte-Datenpfade personenbezogene Daten berühren und dokumentiert sind.',
        ],
        [
            'id' => 'bfdi-taetigkeitsbericht-2025',
            'source_id' => 'bfdi',
            'title' => 'BfDI Tätigkeitsbericht 2025 als DE-Lagebild lesen',
            'summary' => 'Der Bericht zeigt Kontrollschwerpunkte, KI-Themen und Transparenzfragen der Bundesaufsicht — hilfreich für deutsche Governance-Programme.',
            'published_at' => '2026-05-06',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'DE',
            'topics' => ['Datenschutz', 'KI', 'Informationsfreiheit'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.bfdi.bund.de/SharedDocs/Pressemitteilungen/DE/2026/06_TB34.html',
            'recommended_action' => 'Zum Orientieren lesen und gegen eigene DE-Policies spiegeln — ohne neuen Plan.',
        ],
        [
            'id' => 'cnil-ai-transparency-watch',
            'source_id' => 'cnil',
            'title' => 'CNIL: AI-, Transparenz- und Data-Governance-Leitlinien monitoren',
            'summary' => 'CNIL liefert praxisnahe Guidance zu AI und Datenverarbeitung — oft früher und konkreter als reine Framework-Texte.',
            'published_at' => '2026-04-15',
            'type' => 'Praxishilfe',
            'impact' => 'Relevant',
            'region' => 'FR',
            'topics' => ['AI Governance', 'Datenschutz', 'Praxishilfen'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.cnil.fr/en/news',
            'recommended_action' => 'News beobachten und bei AI-/Transparenz-Fragen als Praxisreferenz nutzen.',
        ],
        [
            'id' => 'dpc-annual-report-2025',
            'source_id' => 'dpc-ireland',
            'title' => 'DPC Ireland Annual Report 2025: Enforcement- und AI-Schwerpunkte lesen',
            'summary' => 'Die irische Aufsicht bleibt Lead für viele Cross-Border- und AI-Fälle — Jahresbericht zeigt Beschwerden, Bußgelder und Inquiry-Trends.',
            'published_at' => '2026-06-30',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'IE',
            'topics' => ['Enforcement', 'AI Governance', 'Cross-border'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.dataprotection.ie/en/news-media/latest-news',
            'recommended_action' => 'Als Lagebild lesen, besonders wenn Vendor oder AI-Training personenbezogene EU-Daten berührt.',
        ],
        [
            'id' => 'enisa-nis2-market-framework',
            'source_id' => 'enisa',
            'title' => 'ENISA: Cybersecurity Market Analysis und NIS2-nahe Guidance verfolgen',
            'summary' => 'ENISA-Updates helfen, Security-, Supplier- und Risk-Controls mit Data-Governance-Anforderungen zu koppeln.',
            'published_at' => '2026-04-01',
            'type' => 'Standard',
            'impact' => 'Relevant',
            'region' => 'EU',
            'topics' => ['Cybersecurity', 'NIS2', 'Supplier Governance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.enisa.europa.eu/news',
            'recommended_action' => 'Beobachten und bei Supplier-/Security-Reviews als Referenz ablegen.',
        ],
        [
            'id' => 'eu-ai-act-digital-strategy',
            'source_id' => 'eu-ai-office',
            'title' => 'EU Digital Strategy / AI Office: AI Act und Data Act News filtern',
            'summary' => 'Offizielle EU-Updates zu AI Act, Data Act und digitaler Regulierung — relevant für Ownership, Logging und Freigabeprozesse.',
            'published_at' => '2026-07-10',
            'type' => 'Richtlinien',
            'impact' => 'Prüfen',
            'region' => 'EU',
            'topics' => ['AI Act', 'Data Act', 'AI Governance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://digital-strategy.ec.europa.eu/en/news',
            'recommended_action' => 'Prüfen, ob AI-Use-Cases und Data-Sharing-Pfade den aktuellen EU-Anforderungen entsprechen.',
        ],
        [
            'id' => 'iapp-cross-regulatory-dublin',
            'source_id' => 'iapp',
            'title' => 'IAPP: EDPB Dublin Meeting zu Cross-Regulatory Cooperation einordnen',
            'summary' => 'Privacy sitzt zunehmend neben Wettbewerb, Consumer Law und Digital Markets — IAPP fasst die Enforcement-Kooperationssignale gut zusammen.',
            'published_at' => '2026-07-17',
            'type' => 'Governance News',
            'impact' => 'Relevant',
            'region' => 'EU',
            'topics' => ['Compliance', 'Datenschutz', 'Operating Model'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://iapp.org/news/a/edpb-high-level-meeting-in-dublin-further-deepens-consistency-and-enforcement-cooperation',
            'recommended_action' => 'Lesen und merken, wenn Data Sharing mehrere Regulierungsfelder gleichzeitig berührt.',
        ],
        [
            'id' => 'noyb-enforcement-signals',
            'source_id' => 'noyb',
            'title' => 'NOYB: Complaint- und Enforcement-Signale als Frühwarnung nutzen',
            'summary' => 'NOYB ist keine Aufsicht, aber ein starkes Signal für Cookie-, Consent- und Transfer-Themen, die später in Reviews landen.',
            'published_at' => '2026-07-01',
            'type' => 'Governance News',
            'impact' => 'Info',
            'region' => 'EU',
            'topics' => ['Enforcement', 'Datenschutz', 'Complaints'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://noyb.eu/en/news',
            'recommended_action' => 'Als Frühwarn-Feed beobachten — nicht als Rechtsberatung oder Pflichtplan behandeln.',
        ],
        [
            'id' => 'purview-fabric-governance-docs',
            'source_id' => 'microsoft-purview',
            'title' => 'Microsoft Purview / Fabric: Catalog-, Classification- und Policy-Docs monitoren',
            'summary' => 'Für Fabric-/Purview-Landschaften sind Catalog, Sensitivity Labels und DLP zentrale Governance-Hebel.',
            'published_at' => '2026-07-20',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Catalog', 'PII', 'Vendor Updates'],
            'stack' => ['Fabric', 'Power BI'],
            'url' => 'https://learn.microsoft.com/en-us/purview/',
            'recommended_action' => 'Dokumentation beobachten und bei Stack-Änderungen gegen den eigenen Fabric-/Purview-Stand spiegeln.',
        ],
        [
            'id' => 'dbt-governance-engineering',
            'source_id' => 'dbt-blog',
            'title' => 'dbt Blog: Tests, Docs und Analytics-Engineering-Governance mitlesen',
            'summary' => 'Viele Governance-Entscheidungen landen in dbt als Tests, Docs, Contracts oder Ownership-Konventionen.',
            'published_at' => '2026-07-15',
            'type' => 'Vendor Update',
            'impact' => 'Best Practice',
            'region' => 'Global',
            'topics' => ['Data Quality', 'Metadata', 'Best Practices'],
            'stack' => ['dbt'],
            'url' => 'https://www.getdbt.com/blog',
            'recommended_action' => 'Bei dbt-Stacks relevante Posts lesen — Tools nur öffnen, wenn eine konkrete Regel oder Doku ansteht.',
        ],
        [
            'id' => 'oecd-data-governance-privacy',
            'source_id' => 'oecd-privacy',
            'title' => 'OECD: Data Governance- und Privacy-Policy-Seiten als Framework-Referenz halten',
            'summary' => 'OECD-Material hilft bei Policy- und Operating-Model-Diskussionen über nationale Aufsicht hinaus.',
            'published_at' => '2026-03-01',
            'type' => 'Standard',
            'impact' => 'Orientierung',
            'region' => 'Global',
            'topics' => ['Data Governance', 'Privacy Framework', 'Policy'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.oecd.org/en/topics/policy-issues/data-governance-and-privacy.html',
            'recommended_action' => 'Als Policy-Hintergrund lesen, nicht als operativen Ticket-Trigger.',
        ],
        [
            'id' => 'ico-guidance-watch',
            'source_id' => 'ico-rss',
            'title' => 'ICO: Guidance-, Blog- und Enforcement-Feeds beobachten',
            'summary' => 'UK-Guidance bleibt auch für EU-Stack-Teams nützlich, wenn Vendor, Transfers oder Decision Notices den eigenen Scope berühren.',
            'published_at' => '2026-07-12',
            'type' => 'Praxishilfe',
            'impact' => 'Relevant',
            'region' => 'UK',
            'topics' => ['Datenschutz', 'Enforcement', 'Praxishilfen'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://ico.org.uk/global/rss-feeds/',
            'recommended_action' => 'Feeds beobachten und nur bei UK-/Transfer-Bezug vertiefen.',
        ],
        [
            'id' => 'edps-newsletter-watch',
            'source_id' => 'edps-newsletter',
            'title' => 'EDPS Newsletter: AI Act und Institutionen-Datenschutz mitverfolgen',
            'summary' => 'EDPS-Positionen zu AI Act und EU-Institutionen liefern Frühsignale für Aufsichtspraxis und Policy-Schnittstellen.',
            'published_at' => '2026-06-01',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'EU',
            'topics' => ['AI Act', 'Datenschutz', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edps.europa.eu/press-publications/publications/newsletters_en',
            'recommended_action' => 'Zum Orientieren abonnieren bzw. mitlesen — ohne sofortigen Advisor-Schritt.',
        ],
        [
            'id' => 'snowflake-oidc-trust-center',
            'source_id' => 'snowflake-security',
            'title' => 'Snowflake: OIDC, Trust Center und Security-Release Notes prüfen',
            'summary' => 'Auth-, Federation- und Trust-Center-Änderungen können Access Policies, MFA und Vendor-Risiken in Snowflake-Landschaften verschieben.',
            'published_at' => '2026-07-20',
            'type' => 'Security News',
            'impact' => 'Prüfen',
            'region' => 'Global',
            'topics' => ['Security', 'Authentication', 'Trust Center', 'Vendor Updates'],
            'stack' => ['Snowflake', 'dbt'],
            'url' => 'https://docs.snowflake.com/en/release-notes/2026/other/2026-07-17-oidc-federated-authentication-preview',
            'recommended_action' => 'Bei Snowflake-Umgebungen Auth-/Security-Notes lesen und gegen bestehende Integrationspfade prüfen.',
        ],
        [
            'id' => 'databricks-platform-security-updates',
            'source_id' => 'databricks-release-notes',
            'title' => 'Databricks Release Notes: Security- und Platform-Updates monitoren',
            'summary' => 'Workspace-, Unity-Catalog- und Security-Profile-Änderungen sollten parallel zur Governance-Doku beobachtet werden.',
            'published_at' => '2026-07-18',
            'type' => 'Security News',
            'impact' => 'Prüfen',
            'region' => 'Global',
            'topics' => ['Security', 'Unity Catalog', 'Vendor Updates'],
            'stack' => ['Databricks'],
            'url' => 'https://docs.databricks.com/aws/en/release-notes/',
            'recommended_action' => 'Release Notes scannen und nur bei Security-/Access-Impact im Advisor vertiefen.',
        ],
        [
            'id' => 'fabric-whats-new-governance',
            'source_id' => 'microsoft-fabric-whats-new',
            'title' => 'Microsoft Fabric What’s new: Governance- und Security-Features filtern',
            'summary' => 'Fabric-Updates zu Workspaces, Domains, Sensitivity und Semantic Models betreffen oft Ownership und Freigabeprozesse.',
            'published_at' => '2026-07-21',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Security', 'Semantic Models', 'Catalog'],
            'stack' => ['Fabric', 'Power BI'],
            'url' => 'https://learn.microsoft.com/en-us/fabric/get-started/whats-new',
            'recommended_action' => 'What’s-new-Liste nach Security/Governance filtern und gegen den eigenen Fabric-Stand spiegeln.',
        ],
        [
            'id' => 'power-bi-service-security',
            'source_id' => 'power-bi-blog',
            'title' => 'Power BI: Service-, Sharing- und Security-Updates beobachten',
            'summary' => 'Änderungen an Sharing, RLS, Apps und Admin-Settings können Report-Governance und Zugriffskontrolle betreffen.',
            'published_at' => '2026-07-16',
            'type' => 'Security News',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Security', 'RLS', 'Vendor Updates'],
            'stack' => ['Power BI', 'Fabric'],
            'url' => 'https://powerbi.microsoft.com/en-us/blog/',
            'recommended_action' => 'Blog/Service Updates mitlesen — bei Access-/RLS-Änderungen gegen Report-Freigaben prüfen.',
        ],
        [
            'id' => 'qlik-cloud-change-log',
            'source_id' => 'qlik-release-notes',
            'title' => 'Qlik Cloud Change Log: Security und Access Control monitoren',
            'summary' => 'Spaces, Roles und Security-Änderungen in Qlik Cloud beeinflussen Katalog-, App- und Section-Access-Governance.',
            'published_at' => '2026-07-14',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Security', 'Access Control', 'Vendor Updates'],
            'stack' => ['Qlik'],
            'url' => 'https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Introduction/saas-change-log.htm',
            'recommended_action' => 'Change Log auf Security/Access filtern und nur bei Treffern im eigenen Tenant vertiefen.',
        ],
        [
            'id' => 'tableau-releases-security',
            'source_id' => 'tableau-release-notes',
            'title' => 'Tableau Releases: Security Fixes und Permission-Änderungen prüfen',
            'summary' => 'Server-/Cloud-Releases können Security Patches, Auth- und Permission-Verhalten ändern — relevant für Catalog und Content Governance.',
            'published_at' => '2026-07-10',
            'type' => 'Security News',
            'impact' => 'Prüfen',
            'region' => 'Global',
            'topics' => ['Security', 'Permissions', 'Vendor Updates'],
            'stack' => ['Tableau'],
            'url' => 'https://www.tableau.com/support/releases',
            'recommended_action' => 'Release Notes auf Security/Permissions scannen und Patch-Bedarf gegen die eigene Tableau-Version prüfen.',
        ],
    ],
];
