<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Radar type icons
    |--------------------------------------------------------------------------
    | Types keep a fixed order, icons, and light/dark-capable color tones.
    */
    'type_meta' => [
        'Security News' => [
            'icon' => 'fa-shield-halved',
            'tone' => 'security',
            'order' => 10,
            'label' => ['de' => 'Security News', 'en' => 'Security News'],
        ],
        'Vendor Update' => [
            'icon' => 'fa-cube',
            'tone' => 'vendor',
            'order' => 20,
            'label' => ['de' => 'Vendor Update', 'en' => 'Vendor Update'],
        ],
        'Richtlinien' => [
            'icon' => 'fa-scale-balanced',
            'tone' => 'policy',
            'order' => 30,
            'label' => ['de' => 'Richtlinien', 'en' => 'Guidelines'],
        ],
        'Standard' => [
            'icon' => 'fa-book',
            'tone' => 'standard',
            'order' => 40,
            'label' => ['de' => 'Standard', 'en' => 'Standard'],
        ],
        'Governance News' => [
            'icon' => 'fa-newspaper',
            'tone' => 'news',
            'order' => 50,
            'label' => ['de' => 'Governance News', 'en' => 'Governance News'],
        ],
        'Praxishilfe' => [
            'icon' => 'fa-lightbulb',
            'tone' => 'practice',
            'order' => 60,
            'label' => ['de' => 'Praxishilfe', 'en' => 'Practice guide'],
        ],
        'Eigene News' => [
            'icon' => 'fa-pen',
            'tone' => 'editorial',
            'order' => 70,
            'label' => ['de' => 'Eigene News', 'en' => 'Editorial'],
        ],
    ],
    /*
    |--------------------------------------------------------------------------
    | Feed ingest
    |--------------------------------------------------------------------------
    | Only sources with ingest=true and a real RSS/Atom feed_url are fetched.
    */
    'ingest' => [
        'ttl_minutes' => 45,
        'timeout_seconds' => 12,
        // On page-load / ensureFresh only — keep well under request_budget_seconds.
        'request_timeout_seconds' => 3,
        // Soft cap: oversize feeds are truncated to the last complete item/entry.
        'max_bytes' => 2_097_152,
        'default_limit' => 8,
        'request_budget_seconds' => 4,
        'max_sources_per_request' => 2,
        // Do not retry failed feeds on every page open.
        'error_backoff_minutes' => 360,
        // Refresh stale feeds after the HTML response (terminating), not before.
        'on_request' => true,
        'default_keywords' => [
            'governance', 'catalog', 'security', 'privacy', 'compliance', 'policy',
            'access', 'unity catalog', 'purview', 'lineage', 'pii', 'rls', 'masking',
            'clean room', 'data quality', 'audit', 'iam', 'permission', 'release',
            'what\'s new', 'whats new', 'changelog', 'behavior change',
        ],
        'source_type_to_item_type' => [
            'Vendor' => 'Vendor Update',
            'Regulator' => 'Richtlinien',
            'Standard' => 'Standard',
            'Community' => 'Governance News',
            'Eigene News' => 'Eigene News',
            'Custom' => 'Governance News',
            'Eigene Quelle' => 'Eigene News',
        ],
    ],
    'sources' => [
        [
            'id' => 'edpb-news',
            'name' => 'European Data Protection Board',
            'short_name' => 'EDPB',
            'type' => 'Regulator',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'GDPR', 'AI Governance', 'Richtlinien'],
            'source_url' => 'https://www.edpb.europa.eu/news_en',
            'feed_url' => 'https://www.edpb.europa.eu/news_en',
            'note' => 'Offizielle News und Veröffentlichungen rund um GDPR, Leitlinien, nationale Aufsichtsbehörden und EDPB-Entscheidungen.',
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'edps-newsletter',
            'name' => 'European Data Protection Supervisor',
            'short_name' => 'EDPS',
            'type' => 'Regulator',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'monthly',
            'topics' => ['Datenschutz', 'AI Act', 'EU Institutionen', 'Richtlinien'],
            'source_url' => 'https://www.edps.europa.eu/press-publications/publications/newsletters_en',
            'feed_url' => 'https://www.edps.europa.eu/press-publications/publications/newsletters_en',
            'note' => 'Newsletter und Positionsübersichten zu Datenschutz, AI Act, EU-Institutionen und Aufsichtspraxis.',
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'ico-rss',
            'name' => 'Information Commissioner’s Office',
            'short_name' => 'ICO',
            'type' => 'Regulator',
            'region' => 'UK',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Enforcement', 'Decision Notices'],
            'source_url' => 'https://ico.org.uk/global/rss-feeds/',
            'feed_url' => 'https://ico.org.uk/global/rss-feeds/',
            'note' => 'RSS-Übersicht für News, Blogs, Enforcement und Decision Notices.',
            'ingest' => false,

            'priority' => 'medium',
        ],
        [
            'id' => 'lfdi-bw',
            'name' => 'LfDI Baden-Württemberg',
            'short_name' => 'LfDI BW',
            'type' => 'Regulator',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Informationsfreiheit', 'KI', 'Praxishilfen'],
            'source_url' => 'https://www.baden-wuerttemberg.datenschutz.de/newsfeeds/',
            'feed_url' => 'https://www.baden-wuerttemberg.datenschutz.de/newsfeeds/',
            'note' => 'Deutsche Datenschutz-Newsfeeds, Pressemitteilungen und Praxishilfen.',
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'nist-frameworks',
            'name' => 'National Institute of Standards and Technology',
            'short_name' => 'NIST',
            'type' => 'Standard',
            'region' => 'US',
            'language' => 'en',
            'cadence' => 'monthly',
            'topics' => ['Privacy Framework', 'Cybersecurity', 'Risk Management', 'AI Governance'],
            'source_url' => 'https://www.nist.gov/frameworks',
            'feed_url' => 'https://www.nist.gov/frameworks',
            'note' => 'Standards und Frameworks für Privacy, Cybersecurity, AI Risk und Risk Management.',
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'nist-csrc-news',
            'name' => 'NIST Computer Security Resource Center',
            'short_name' => 'NIST CSRC',
            'type' => 'Standard',
            'region' => 'US',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Cybersecurity', 'Privacy', 'Risk Management', 'Supplier Governance'],
            'source_url' => 'https://csrc.nist.gov/news/',
            'feed_url' => 'https://csrc.nist.gov/news/',
            'note' => 'News und Updates zu Security-, Privacy-, Supplier- und Risk-Management-Publikationen.',
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'snowflake-release-notes',
            'name' => 'Snowflake Documentation',
            'short_name' => 'Snowflake',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Data Clean Rooms', 'Catalog', 'Security'],
            'source_url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'feed_url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'note' => 'Release Notes für Governance-relevante Features, Policy-Änderungen, Clean Rooms und Catalog-Funktionen.',
            'ingest' => false,

            'priority' => 'medium',
        ],
        [
            'id' => 'databricks-governance',
            'name' => 'Databricks Documentation',
            'short_name' => 'Databricks',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Unity Catalog', 'Lineage', 'Data Quality', 'AI Governance'],
            'source_url' => 'https://docs.databricks.com/aws/en/data-governance',
            'feed_url' => 'https://docs.databricks.com/aws/en/data-governance',
            'note' => 'Governance-Dokumentation zu Unity Catalog, Discovery, Classification, DQ Monitoring und AI Governance.',
            'ingest' => false,

            'priority' => 'medium',
        ],
        [
            'id' => 'bfdi',
            'name' => 'Bundesbeauftragte für den Datenschutz und die Informationsfreiheit',
            'short_name' => 'BfDI',
            'type' => 'Regulator',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Data Act', 'Informationsfreiheit', 'KI'],
            'source_url' => 'https://www.bfdi.bund.de/DE/BfDI/Presse/Pressemitteilungen/pressemitteilungen_node.html',
            'feed_url' => 'https://www.bfdi.bund.de/DE/BfDI/Presse/Pressemitteilungen/pressemitteilungen_node.html',
            'note' => 'Nationale DE-Aufsicht: Pressemitteilungen zu Data Act, KI, Transparenz und Tätigkeitsberichten.',
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'cnil',
            'name' => 'Commission Nationale de l’Informatique et des Libertés',
            'short_name' => 'CNIL',
            'type' => 'Regulator',
            'region' => 'FR',
            'language' => 'fr',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'AI Governance', 'Data Governance Act', 'Praxishilfen'],
            'source_url' => 'https://www.cnil.fr/en/news',
            'feed_url' => 'https://www.cnil.fr/en/rss.xml',
            'note' => 'Französische Aufsicht mit starken Praxisleitfäden zu AI, Transparenz und Data Governance.',
            'ingest' => true,

            'priority' => 'high',
        ],
        [
            'id' => 'dpc-ireland',
            'name' => 'Data Protection Commission Ireland',
            'short_name' => 'DPC',
            'type' => 'Regulator',
            'region' => 'IE',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Enforcement', 'AI Governance', 'Cross-border'],
            'source_url' => 'https://www.dataprotection.ie/en/news-media/latest-news',
            'feed_url' => 'https://www.dataprotection.ie/en/news-media/latest-news',
            'note' => 'Lead-Aufsicht für viele Big-Tech-/AI-Fälle und Cross-Border-Enforcement in der EU.',
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'enisa',
            'name' => 'European Union Agency for Cybersecurity',
            'short_name' => 'ENISA',
            'type' => 'Standard',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Cybersecurity', 'NIS2', 'Risk Management', 'Supplier Governance'],
            'source_url' => 'https://www.enisa.europa.eu/news',
            'feed_url' => 'https://www.enisa.europa.eu/news',
            'note' => 'Cyber-/Risk-Guidance mit Schnittstellen zu NIS2, Supply Chain und Governance-Controls.',
            'ingest' => false,

            'priority' => 'medium',
        ],
        [
            'id' => 'eu-ai-office',
            'name' => 'European AI Office / Digital Strategy',
            'short_name' => 'EU AI',
            'type' => 'Regulator',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['AI Act', 'AI Governance', 'Data Act', 'Digital Markets'],
            'source_url' => 'https://digital-strategy.ec.europa.eu/en/news',
            'feed_url' => 'https://digital-strategy.ec.europa.eu/en/rss.xml',
            'note' => 'EU-Updates zu AI Act, Data Act und digitaler Regulierung mit Governance-Impact.',
            'ingest' => true,

            'priority' => 'high',
        ],
        [
            'id' => 'iapp',
            'name' => 'International Association of Privacy Professionals',
            'short_name' => 'IAPP',
            'type' => 'Community',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'daily',
            'topics' => ['Datenschutz', 'AI Governance', 'Compliance', 'Operating Model'],
            'source_url' => 'https://iapp.org/news/',
            'feed_url' => 'https://iapp.org/news/a/rss/',
            'note' => 'Kuratierte Privacy-/Governance-News und Analyse zu Enforcement und Cross-Regulatory-Themen.',
            // Public RSS endpoint currently 404 — keep as catalog source only.
            'ingest' => false,

            'priority' => 'medium',
        ],
        [
            'id' => 'noyb',
            'name' => 'NOYB – European Center for Digital Rights',
            'short_name' => 'NOYB',
            'type' => 'Community',
            'region' => 'EU',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Enforcement', 'Cookies', 'Complaints'],
            'source_url' => 'https://noyb.eu/en/news',
            'feed_url' => 'https://noyb.eu/en/rss.xml',
            'note' => 'Advocacy- und Complaint-Signale zu GDPR-Enforcement — klar als NGO/Community labeln.',
            'ingest' => true,

            'priority' => 'medium',
        ],
        [
            'id' => 'microsoft-purview',
            'name' => 'Microsoft Purview / Fabric Governance',
            'short_name' => 'Purview',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Catalog', 'Lineage', 'PII', 'Vendor Updates'],
            'source_url' => 'https://learn.microsoft.com/en-us/purview/',
            'feed_url' => 'https://learn.microsoft.com/api/search/rss?search=%22Microsoft+Purview%22&locale=en-us',
            'note' => 'Vendor-Docs zu Catalog, Classification, Data Loss Prevention und Fabric Governance.',
            'ingest' => true,
            'ingest_keywords' => ['purview', 'catalog', 'governance', 'classification', 'lineage', 'sensitivity', 'dlp', 'fabric'],
            'item_type' => 'Vendor Update',

            'priority' => 'medium',
        ],
        [
            'id' => 'dbt-blog',
            'name' => 'dbt Labs Blog',
            'short_name' => 'dbt',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Data Quality', 'Metadata', 'Best Practices', 'Vendor Updates'],
            'source_url' => 'https://www.getdbt.com/blog',
            'feed_url' => 'https://www.getdbt.com/blog/rss.xml',
            'note' => 'Praxis zu Analytics Engineering, Tests, Docs und Governance-nahen Workflows.',
            'ingest' => true,
            'ingest_keywords' => ['test', 'docs', 'governance', 'metadata', 'quality', 'semantic', 'mesh', 'discovery'],
            'item_type' => 'Vendor Update',

            'priority' => 'medium',
        ],
        [
            'id' => 'snowflake-security',
            'name' => 'Snowflake Trust Center / Security',
            'short_name' => 'Snowflake Sec',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Security', 'Vendor Updates', 'Authentication', 'Trust Center'],
            'source_url' => 'https://docs.snowflake.com/en/user-guide/trust-center',
            'feed_url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'note' => 'Security-, Auth- und Trust-Center-Updates parallel zu Feature Release Notes.',
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'databricks-release-notes',
            'name' => 'Databricks Platform Release Notes',
            'short_name' => 'Databricks RN',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Security', 'Unity Catalog', 'AI Governance'],
            'source_url' => 'https://docs.databricks.com/aws/en/release-notes/',
            'feed_url' => 'https://docs.databricks.com/aws/en/feed.xml',
            'note' => 'Plattform-, Security- und Governance-Feature-Updates für Databricks Workspaces.',
            'ingest' => true,
            'ingest_keywords' => ['unity catalog', 'governance', 'security', 'access', 'lineage', 'ai governance', 'permission', 'lakehouse'],
            'item_type' => 'Vendor Update',

            'priority' => 'high',
        ],
        [
            'id' => 'microsoft-fabric-whats-new',
            'name' => 'Microsoft Fabric What’s new',
            'short_name' => 'Fabric',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Catalog', 'Security', 'Semantic Models'],
            'source_url' => 'https://learn.microsoft.com/en-us/fabric/get-started/whats-new',
            'feed_url' => 'https://learn.microsoft.com/api/search/rss?search=%22Microsoft+Fabric%22&locale=en-us',
            'note' => 'Fabric Feature- und Governance-Updates inkl. Workspace-, Security- und Semantic-Model-Änderungen.',
            'ingest' => true,
            'ingest_keywords' => ['fabric', 'governance', 'security', 'catalog', 'workspace', 'oneLake', 'purview'],
            'item_type' => 'Vendor Update',

            'priority' => 'high',
        ],
        [
            'id' => 'power-bi-blog',
            'name' => 'Power BI Blog / Service Updates',
            'short_name' => 'Power BI',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Security', 'Semantic Models', 'RLS'],
            'source_url' => 'https://powerbi.microsoft.com/en-us/blog/',
            'feed_url' => 'https://powerbi.microsoft.com/en-us/blog/feed/',
            'note' => 'Service Updates zu Security, Sharing, RLS und Governance-relevanten Report-Features.',
            'ingest' => true,
            'ingest_keywords' => ['security', 'governance', 'rls', 'sharing', 'workspace', 'admin', 'compliance', 'sensitivity'],
            'item_type' => 'Vendor Update',

            'priority' => 'medium',
        ],
        [
            'id' => 'qlik-release-notes',
            'name' => 'Qlik Cloud Release Notes',
            'short_name' => 'Qlik',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Security', 'Catalog', 'Access Control'],
            'source_url' => 'https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Introduction/saas-change-log.htm',
            'feed_url' => 'https://qlik.dev/rss.xml',
            'note' => 'Qlik Cloud Change Log für Security, Spaces, Access Control und Catalog-nahe Änderungen.',
            'ingest' => true,
            'ingest_keywords' => ['security', 'access', 'space', 'catalog', 'governance', 'permission', 'admin'],
            'item_type' => 'Vendor Update',

            'priority' => 'medium',
        ],
        [
            'id' => 'tableau-release-notes',
            'name' => 'Tableau Release Notes / Security',
            'short_name' => 'Tableau',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Vendor Updates', 'Security', 'Permissions', 'Catalog'],
            'source_url' => 'https://www.tableau.com/support/releases',
            'feed_url' => 'https://www.tableau.com/support/releases',
            'note' => 'Tableau Desktop/Server/Cloud Releases inkl. Security Fixes und Permission-Änderungen.',
            'ingest' => false,

            'priority' => 'medium',
        ],
        [
            'id' => 'oecd-privacy',
            'name' => 'OECD Digital / Privacy',
            'short_name' => 'OECD',
            'type' => 'Standard',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'monthly',
            'topics' => ['Privacy Framework', 'AI Governance', 'Data Governance', 'Policy'],
            'source_url' => 'https://www.oecd.org/en/topics/policy-issues/data-governance-and-privacy.html',
            'feed_url' => 'https://www.oecd.org/en/topics/policy-issues/data-governance-and-privacy.html',
            'note' => 'Policy-Frameworks zu Data Governance, Privacy und vertrauenswürdigem Datenaustausch.',
            'ingest' => false,

            'priority' => 'low',
        ],
        [
            'id' => 'baylda',
            'name' => 'Bayerisches Landesamt für Datenschutzaufsicht',
            'short_name' => 'BayLDA',
            'type' => 'Regulator',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'KI', 'Cloud', 'Praxishilfen'],
            'source_url' => 'https://www.lda.bayern.de/de/aktuelles.html',
            'feed_url' => 'https://www.lda.bayern.de/de/aktuelles.html',
            'note' => 'Bayerische Aufsicht mit praxisnahen Hinweisen zu Cloud, KI und Unternehmensdatenschutz.',
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'blnbdi',
            'name' => 'Berliner Beauftragte für Datenschutz und Informationsfreiheit',
            'short_name' => 'BlnBDI',
            'type' => 'Regulator',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'weekly',
            'topics' => ['Datenschutz', 'Informationsfreiheit', 'Enforcement', 'Praxishilfen'],
            'source_url' => 'https://www.datenschutz-berlin.de/presse/',
            'feed_url' => 'https://www.datenschutz-berlin.de/presse/',
            'note' => 'Berliner Aufsicht: Pressemitteilungen, Tätigkeitsberichte und Praxisfragen für öffentliche und private Stellen.',
            'ingest' => false,

            'priority' => 'medium',
        ],
        [
            'id' => 'bsi',
            'name' => 'Bundesamt für Sicherheit in der Informationstechnik',
            'short_name' => 'BSI',
            'type' => 'Standard',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'weekly',
            'topics' => ['Cybersecurity', 'Cloud', 'Risk Management', 'Supplier Governance'],
            'source_url' => 'https://www.bsi.bund.de/DE/Service-Navi/Presse/presse_node.html',
            'feed_url' => 'https://www.bsi.bund.de/SiteGlobals/Functions/RSSFeed/RSSNewsfeed/RSSNewsfeed.xml',
            'note' => 'DE-Security-Standards, Cloud- und C5-nahe Hinweise mit Schnittstelle zu Data-/Vendor-Governance.',
            // Official RSS URL currently 404 — keep as catalog source only.
            'ingest' => false,

            'priority' => 'high',
        ],
        [
            'id' => 'cisa',
            'name' => 'Cybersecurity and Infrastructure Security Agency',
            'short_name' => 'CISA',
            'type' => 'Standard',
            'region' => 'US',
            'language' => 'en',
            'cadence' => 'daily',
            'topics' => ['Cybersecurity', 'Vendor Risk', 'Incident Response', 'Supplier Governance'],
            'source_url' => 'https://www.cisa.gov/news-events/news',
            'feed_url' => 'https://www.cisa.gov/news.xml',
            'note' => 'Security Alerts und Guidance zu Supply Chain, Incidents und kritischer Infrastruktur.',
            'ingest' => true,

            'priority' => 'medium',
        ],
        [
            'id' => 'aws-security',
            'name' => 'AWS Security Blog',
            'short_name' => 'AWS Sec',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Security', 'IAM', 'Vendor Updates', 'Cloud'],
            'source_url' => 'https://aws.amazon.com/blogs/security/',
            'feed_url' => 'https://aws.amazon.com/blogs/security/feed/',
            'note' => 'IAM-, Encryption-, Logging- und Control-Updates für AWS-Landschaften.',
            'ingest' => true,
            'ingest_keywords' => ['iam', 'governance', 'encryption', 'logging', 'access', 'policy', 'compliance', 'lake'],

            'priority' => 'medium',
        ],
        [
            'id' => 'gcp-security',
            'name' => 'Google Cloud Security Blog',
            'short_name' => 'GCP Sec',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Security', 'IAM', 'Vendor Updates', 'Cloud'],
            'source_url' => 'https://cloud.google.com/blog/products/identity-security',
            'feed_url' => 'https://cloudblog.withgoogle.com/rss',
            'note' => 'Identity-, Security- und Compliance-Updates rund um Google Cloud und BigQuery-Ökosysteme.',
            'ingest' => true,
            'ingest_keywords' => ['iam', 'governance', 'security', 'access', 'policy', 'compliance', 'bigquery'],

            'priority' => 'medium',
        ],
        [
            'id' => 'collibra-blog',
            'name' => 'Collibra Blog',
            'short_name' => 'Collibra',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Catalog', 'Data Quality', 'Operating Model', 'Vendor Updates'],
            'source_url' => 'https://www.collibra.com/us/en/blog',
            'feed_url' => 'https://www.collibra.com/us/en/blog',
            'note' => 'Catalog-, Stewardship- und Data-Quality-Praxis aus dem Data-Intelligence-Ökosystem.',
            'ingest' => false,

            'priority' => 'medium',
        ],
        [
            'id' => 'alation-blog',
            'name' => 'Alation Blog',
            'short_name' => 'Alation',
            'type' => 'Vendor',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'weekly',
            'topics' => ['Catalog', 'Data Literacy', 'Operating Model', 'Vendor Updates'],
            'source_url' => 'https://www.alation.com/blog/',
            'feed_url' => 'https://www.alation.com/blog/feed/',
            'note' => 'Data Catalog, Literacy und Governance-Operating-Model aus Alation-Perspektive.',
            // Blog feed currently 404 — keep as catalog source only.
            'ingest' => false,
            'ingest_keywords' => ['catalog', 'governance', 'literacy', 'steward', 'quality', 'lineage'],

            'priority' => 'low',
        ],
        [
            'id' => 'iso-news',
            'name' => 'ISO News / Standards',
            'short_name' => 'ISO',
            'type' => 'Standard',
            'region' => 'Global',
            'language' => 'en',
            'cadence' => 'monthly',
            'topics' => ['ISO 27001', 'AI Governance', 'Quality', 'Risk Management'],
            'source_url' => 'https://www.iso.org/news.html',
            'feed_url' => 'https://www.iso.org/rss/news.rss',
            'note' => 'Internationale Standards zu Security, Quality und AI — als Framework-Referenz, nicht als Tagesnews.',
            'ingest' => true,

            'priority' => 'low',
        ],
        [
            'id' => 'binom-editorial',
            'name' => 'binom-tools Redaktion',
            'short_name' => 'binom',
            'type' => 'Eigene News',
            'region' => 'DE',
            'language' => 'de',
            'cadence' => 'manual',
            'topics' => ['Eigene News', 'Best Practices', 'Playbooks'],
            'source_url' => '/governance/radar',
            'feed_url' => null,
            'note' => 'Eigene kuratierte Hinweise, Best Practices, Playbook-Updates und interne Governance-Notizen.',
            'ingest' => false,

            'priority' => 'high',
        ],
    ],
    'items' => [
        [
            'id' => 'edpb-ai-anonymisierung-blockchain',
            'source_id' => 'edpb-news',
            'title' => 'EDPB: Anonymisierung, Web Scraping und Blockchain-Leitlinien beobachten',
            'summary' => 'Für Governance-Projekte mit AI, Webdaten, Blockchain oder Analytics auf personenbezogenen Daten sollte diese Quelle regelmäßig geprüft werden. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu Datenschutz, AI Governance, Richtlinien kurz gegen den Use Case halten. Region EU und stackübergreifend bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2026-07-08',
            'type' => 'Richtlinien',
            'impact' => 'Prüfen',
            'region' => 'EU',
            'topics' => ['Datenschutz', 'AI Governance', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Quelle lesen und bei AI-/Web-Scraping-Projekten gegen eigene Use Cases spiegeln. Nur bei Abweichung nachziehen — sonst beobachten.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'edpb-cross-regulatory-sharing',
            'source_id' => 'edpb-news',
            'title' => 'EDPB: Cross-regulatory Information Sharing als Governance-Risiko verfolgen',
            'summary' => 'Relevant, wenn Daten zwischen Datenschutz, Wettbewerb, Finanzaufsicht, AML oder sektoralen Regulatoren bewertet werden müssen. Der Treffer bleibt auf der Watchlist, weil Datenschutz, Compliance, Richtlinien in EU zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für stackübergreifend, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-17',
            'type' => 'Richtlinien',
            'impact' => 'Relevant',
            'region' => 'EU',
            'topics' => ['Datenschutz', 'Compliance', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Beobachten, wenn Data Sharing oder Clean-Room-Szenarien anstehen — ohne sofortigen Plan. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'nist-privacy-framework-11',
            'source_id' => 'nist-frameworks',
            'title' => 'NIST Privacy Framework 1.1 und CSF 2.0 Mapping einplanen',
            'summary' => 'Privacy, Cybersecurity und AI-Risk sollten im Governance Radar gemeinsam betrachtet werden, statt getrennte Checklisten zu pflegen. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu Privacy Framework, Cybersecurity, AI Governance kurz gegen den Use Case halten. Region US und stackübergreifend bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2025-04-14',
            'type' => 'Standard',
            'impact' => 'Prüfen',
            'region' => 'US',
            'topics' => ['Privacy Framework', 'Cybersecurity', 'AI Governance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.nist.gov/frameworks',
            'recommended_action' => 'Framework-Mapping prüfen und nur bei Lücken im eigenen Stack in den Advisor nehmen. Privacy Framework gegen den Use Case spiegeln; nur bei Abweichung nachziehen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'edpb-annual-report-2025',
            'source_id' => 'edpb-news',
            'title' => 'EDPB Annual Report 2025 als Governance-Lagebild lesen',
            'summary' => 'Der Jahresbericht zeigt, welche Datenschutzthemen, Leitlinien und Abstimmungen für Governance-Programme in Europa wichtig bleiben. Gut als Lagebild: Governance News-Signale zu Datenschutz, Operating Model, Richtlinien helfen, Prioritäten und Sprachbilder in EU zu schärfen, ohne jedes Update in einen Ticket-Backlog zu übersetzen.',
            'published_at' => '2026-05-04',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'EU',
            'topics' => ['Datenschutz', 'Operating Model', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Zum Lesen und Orientieren — gegen eigene Policies spiegeln, ohne neuen Plan zu starten. Einordnen ohne neuen Workflow, außer der Scope ist klar betroffen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'edpb-dpia-template',
            'source_id' => 'edpb-news',
            'title' => 'EDPB DPIA Template für Risiko- und Datenschutzbewertungen aufnehmen',
            'summary' => 'Ein einheitlicher DPIA-Baustein hilft, neue Quellen, AI-Use-Cases, PII-Flüsse und Data-Sharing-Fragen konsistenter zu bewerten. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu DPIA, PII, Risiko kurz gegen den Use Case halten. Region EU und stackübergreifend bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2026-04-14',
            'type' => 'Governance News',
            'impact' => 'Prüfen',
            'region' => 'EU',
            'topics' => ['DPIA', 'PII', 'Risiko', 'Datenschutz'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Template lesen und prüfen, ob PII/DSDR- und Source-Scope-Checks davon profitieren. DPIA gegen den Use Case spiegeln; nur bei Abweichung nachziehen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'edpb-transparency-enforcement',
            'source_id' => 'edpb-news',
            'title' => 'EDPB CEF 2026: Transparenz und Informationspflichten beobachten',
            'summary' => 'Transparenzpflichten betreffen nicht nur Legal-Texte, sondern auch Datenkatalog, Report-Kontext, Zweckbindung und Betroffenenkommunikation. Für EU-Teams heißt das: laufende Freigaben, Access- oder Policy-Pfade zu Transparenz, Katalog, PII sollten zeitnah gegen den eigenen Stand gespiegelt werden, bevor Features oder Quellen produktiv werden (stackübergreifend).',
            'published_at' => '2026-03-19',
            'type' => 'Governance News',
            'impact' => 'Handlungsbedarf',
            'region' => 'EU',
            'topics' => ['Transparenz', 'Katalog', 'PII', 'Compliance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edpb.europa.eu/news_en',
            'recommended_action' => 'Bei personenbezogenen Reports Zweck, Datenherkunft, Owner und Löschlogik im Advisor prüfen. Bei Lücken Owner/Controls notieren und gezielt im Advisor spiegeln.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'nist-system-plans-privacy-scrm',
            'source_id' => 'nist-csrc-news',
            'title' => 'NIST SP 800-18r2: Security, Privacy und Supply Chain als verbundene Systempläne behandeln',
            'summary' => 'Systemplanung wird breiter gedacht: Security, Privacy und Cybersecurity Supply Chain Risk Management gehören in ein gemeinsames Planungsmodell. Das ist weniger ein Tages-Ticket als ein Architektur-Signal: Ownership, Controls und Integrationspfade zu Risk Management, Supplier Governance, Privacy müssen in US zum Zielbild passen — besonders in stackübergreifend-Landschaften.',
            'published_at' => '2026-06-30',
            'type' => 'Standard',
            'impact' => 'Architektur prüfen',
            'region' => 'US',
            'topics' => ['Risk Management', 'Supplier Governance', 'Privacy', 'Security'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://csrc.nist.gov/news/',
            'recommended_action' => 'Bei neuen Plattformen Security-/Privacy-/Supplier-Pfade im Advisor gegen die Architektur halten. Nur bei struktureller Lücke in den Advisor nehmen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'nist-supplier-due-diligence',
            'source_id' => 'nist-csrc-news',
            'title' => 'NIST Supplier Quick-Start Guide für Vendor- und Datenquellen-Checks berücksichtigen',
            'summary' => 'Supplier Governance braucht einen Mindeststandard für Recherche, Nachweise, Risiken und Entscheidungsvorlagen, bevor Quellen angebunden werden. Für US-Teams heißt das: laufende Freigaben, Access- oder Policy-Pfade zu Supplier Governance, Vendor Risk, Nachweise sollten zeitnah gegen den eigenen Stand gespiegelt werden, bevor Features oder Quellen produktiv werden (stackübergreifend).',
            'published_at' => '2026-07-08',
            'type' => 'Governance News',
            'impact' => 'Handlungsbedarf',
            'region' => 'US',
            'topics' => ['Supplier Governance', 'Vendor Risk', 'Nachweise'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://csrc.nist.gov/news/',
            'recommended_action' => 'Guide lesen und offene Vendor-/Quellen-Checks im Advisor nachziehen. Bei Lücken Owner/Controls notieren und gezielt im Advisor spiegeln.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'snowflake-clean-rooms-update',
            'source_id' => 'snowflake-release-notes',
            'title' => 'Snowflake: Clean Rooms, Catalog und Policy Release Notes monitoren',
            'summary' => 'Vendor-Änderungen können Auswirkungen auf Data Sharing, Clean Rooms, Governance Policies und Migrationen haben. Für Global-Teams heißt das: laufende Freigaben, Access- oder Policy-Pfade zu Vendor Updates, Data Clean Rooms, Security sollten zeitnah gegen den eigenen Stand gespiegelt werden, bevor Features oder Quellen produktiv werden (Snowflake, dbt).',
            'published_at' => '2026-07-23',
            'type' => 'Vendor Update',
            'impact' => 'Handlungsbedarf',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Data Clean Rooms', 'Security'],
            'stack' => ['Snowflake', 'dbt'],
            'url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'recommended_action' => 'Release Notes prüfen und bei Snowflake-Umgebungen betroffene Policies im Advisor bewerten. Bei Lücken Owner/Controls notieren und gezielt im Advisor spiegeln.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'databricks-unity-catalog-governance',
            'source_id' => 'databricks-governance',
            'title' => 'Databricks: Unity Catalog Governance-Funktionen regelmäßig prüfen',
            'summary' => 'Lineage, Classification, Discovery, Quality Monitoring und AI Governance sind Kernsignale für Databricks-Governance-Entscheidungen. Der Treffer bleibt auf der Watchlist, weil Unity Catalog, Lineage, Data Quality in Global zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für Databricks, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-22',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Unity Catalog', 'Lineage', 'Data Quality', 'AI Governance'],
            'stack' => ['Databricks'],
            'url' => 'https://docs.databricks.com/aws/en/data-governance',
            'recommended_action' => 'Dokumentation beobachten — bei neuen Features gegen den eigenen Databricks-Stack spiegeln. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'lfdi-ki-praxishilfen',
            'source_id' => 'lfdi-bw',
            'title' => 'LfDI BW: Praxishilfen zu KI und Datenschutz als deutsche Referenz aufnehmen',
            'summary' => 'Für deutsche Workshops sind lokale Datenschutz-Praxishilfen oft verständlicher als rein internationale Frameworks. Der Treffer bleibt auf der Watchlist, weil Datenschutz, KI, Praxishilfen in DE zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für stackübergreifend, ohne sofortigen Planzwang.',
            'published_at' => '2026-06-11',
            'type' => 'Praxishilfe',
            'impact' => 'Relevant',
            'region' => 'DE',
            'topics' => ['Datenschutz', 'KI', 'Praxishilfen'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.baden-wuerttemberg.datenschutz.de/newsfeeds/',
            'recommended_action' => 'Als Referenz lesen und bei Bedarf in Workshops oder Checks verlinken. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'binom-source-governance-watchlist',
            'source_id' => 'binom-editorial',
            'title' => 'Eigene Watchlist: Source, KPI, PII und DQ nicht getrennt entscheiden',
            'summary' => 'Neue Quellen sollten im Radar direkt mit KPI-Anforderungen, PII/DSDR, DQ-Regeln und Mart-Entscheidungen verbunden werden. Als Merksatz behalten: Eigene News, Best Practices, Data Quality hängt mit angrenzenden Entscheidungen zusammen — in DE oft sichtbarer in Katalog, Freigabe oder Vendor-Reviews (stackübergreifend).',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Info',
            'region' => 'DE',
            'topics' => ['Eigene News', 'Best Practices', 'Data Quality'],
            'stack' => ['Alle Stacks'],
            'url' => '/governance',
            'recommended_action' => 'Als Merksatz behalten — nicht automatisch einen neuen Workflow starten. Einordnen ohne neuen Workflow, außer der Scope ist klar betroffen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'binom-data-ownership-operating-model',
            'source_id' => 'binom-editorial',
            'title' => 'Data Ownership nicht als Organigramm, sondern als Entscheidungsrecht pflegen',
            'summary' => 'Owner, Steward, Approver und Konsument müssen wissen, welche Entscheidung sie treffen, freigeben oder nur prüfen. Als Praxisimpuls nützlich: Data Ownership, RACI, Operating Model nicht als isoliertes Tool-Feature denken, sondern als Entscheidungs-, Ownership- und Qualitätsfrage in DE-Kontexten (stackübergreifend).',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Best Practice',
            'region' => 'DE',
            'topics' => ['Data Ownership', 'RACI', 'Operating Model'],
            'stack' => ['Alle Stacks'],
            'url' => '/tools/stakeholder-matrix',
            'recommended_action' => 'Bei kritischen KPIs und Quellen die Stakeholder Matrix als Hilfsmittel öffnen. Als Referenz für die nächste verwandte Entscheidung behalten.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'binom-dq-as-governance-signal',
            'source_id' => 'binom-editorial',
            'title' => 'Data Quality als Governance-Signal statt als reines Technik-Ticket behandeln',
            'summary' => 'DQ-Regeln sollten zeigen, welche Entscheidung gefährdet ist, welche Quelle betroffen ist und wer die Ausnahme freigeben darf. Als Praxisimpuls nützlich: Data Quality, KPI, Owner nicht als isoliertes Tool-Feature denken, sondern als Entscheidungs-, Ownership- und Qualitätsfrage in DE-Kontexten (stackübergreifend).',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Best Practice',
            'region' => 'DE',
            'topics' => ['Data Quality', 'KPI', 'Owner', 'Workflow'],
            'stack' => ['Alle Stacks'],
            'url' => '/tools/dbt-dq-rules-generator',
            'recommended_action' => 'DQ-Regeln fachlich begründen — Tools nur öffnen, wenn eine Regel ansteht. Als Referenz für die nächste verwandte Entscheidung behalten.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'binom-metadata-minimum',
            'source_id' => 'binom-editorial',
            'title' => 'Metadata Minimum: Geschäftsfrage, Quelle, PII, DQ und Owner zuerst erfassen',
            'summary' => 'Viele Governance-Probleme entstehen, weil technische Tabellen vor der fachlichen Entscheidung dokumentiert werden. Als Praxisimpuls nützlich: Metadata, Katalog, Source Scope nicht als isoliertes Tool-Feature denken, sondern als Entscheidungs-, Ownership- und Qualitätsfrage in DE-Kontexten (stackübergreifend).',
            'published_at' => '2026-07-26',
            'type' => 'Eigene News',
            'impact' => 'Best Practice',
            'region' => 'DE',
            'topics' => ['Metadata', 'Katalog', 'Source Scope', 'KPI'],
            'stack' => ['Alle Stacks'],
            'url' => '/tools/source-scope-builder',
            'recommended_action' => 'Vor Mart Design oder Reporting zuerst Scope und Ownership klären — bei Bedarf Source Scope Builder öffnen. Als Referenz für die nächste verwandte Entscheidung behalten.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'bfdi-data-act-aufsicht',
            'source_id' => 'bfdi',
            'title' => 'BfDI: Datenschutzaufsicht nach dem Data Act beobachten',
            'summary' => 'Mit dem DADG überwacht die BfDI Data-Act-Anwendungen, soweit personenbezogene Daten betroffen sind — relevant für IoT-, Sharing- und Plattform-Szenarien. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu Data Act, Datenschutz, Compliance kurz gegen den Use Case halten. Region DE und stackübergreifend bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2026-05-29',
            'type' => 'Governance News',
            'impact' => 'Prüfen',
            'region' => 'DE',
            'topics' => ['Data Act', 'Datenschutz', 'Compliance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.bfdi.bund.de/SharedDocs/Pressemitteilungen/DE/2026/07_Data-Act-Datenschutzaufsicht.html',
            'recommended_action' => 'Prüfen, ob Data-Sharing- oder Geräte-Datenpfade personenbezogene Daten berühren und dokumentiert sind. Data Act gegen den Use Case spiegeln; nur bei Abweichung nachziehen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'bfdi-taetigkeitsbericht-2025',
            'source_id' => 'bfdi',
            'title' => 'BfDI Tätigkeitsbericht 2025 als DE-Lagebild lesen',
            'summary' => 'Der Bericht zeigt Kontrollschwerpunkte, KI-Themen und Transparenzfragen der Bundesaufsicht — hilfreich für deutsche Governance-Programme. Gut als Lagebild: Governance News-Signale zu Datenschutz, KI, Informationsfreiheit helfen, Prioritäten und Sprachbilder in DE zu schärfen, ohne jedes Update in einen Ticket-Backlog zu übersetzen.',
            'published_at' => '2026-05-06',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'DE',
            'topics' => ['Datenschutz', 'KI', 'Informationsfreiheit'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.bfdi.bund.de/SharedDocs/Pressemitteilungen/DE/2026/06_TB34.html',
            'recommended_action' => 'Zum Orientieren lesen und gegen eigene DE-Policies spiegeln — ohne neuen Plan. Einordnen ohne neuen Workflow, außer der Scope ist klar betroffen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'cnil-ai-transparency-watch',
            'source_id' => 'cnil',
            'title' => 'CNIL: AI-, Transparenz- und Data-Governance-Leitlinien monitoren',
            'summary' => 'CNIL liefert praxisnahe Guidance zu AI und Datenverarbeitung — oft früher und konkreter als reine Framework-Texte. Der Treffer bleibt auf der Watchlist, weil AI Governance, Datenschutz, Praxishilfen in FR zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für stackübergreifend, ohne sofortigen Planzwang.',
            'published_at' => '2026-04-15',
            'type' => 'Praxishilfe',
            'impact' => 'Relevant',
            'region' => 'FR',
            'topics' => ['AI Governance', 'Datenschutz', 'Praxishilfen'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.cnil.fr/en/news',
            'recommended_action' => 'News beobachten und bei AI-/Transparenz-Fragen als Praxisreferenz nutzen. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'dpc-annual-report-2025',
            'source_id' => 'dpc-ireland',
            'title' => 'DPC Ireland Annual Report 2025: Enforcement- und AI-Schwerpunkte lesen',
            'summary' => 'Die irische Aufsicht bleibt Lead für viele Cross-Border- und AI-Fälle — Jahresbericht zeigt Beschwerden, Bußgelder und Inquiry-Trends. Gut als Lagebild: Governance News-Signale zu Enforcement, AI Governance, Cross-border helfen, Prioritäten und Sprachbilder in IE zu schärfen, ohne jedes Update in einen Ticket-Backlog zu übersetzen.',
            'published_at' => '2026-06-30',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'IE',
            'topics' => ['Enforcement', 'AI Governance', 'Cross-border'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.dataprotection.ie/en/news-media/latest-news',
            'recommended_action' => 'Als Lagebild lesen, besonders wenn Vendor oder AI-Training personenbezogene EU-Daten berührt. Einordnen ohne neuen Workflow, außer der Scope ist klar betroffen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'enisa-nis2-market-framework',
            'source_id' => 'enisa',
            'title' => 'ENISA: Cybersecurity Market Analysis und NIS2-nahe Guidance verfolgen',
            'summary' => 'ENISA-Updates helfen, Security-, Supplier- und Risk-Controls mit Data-Governance-Anforderungen zu koppeln. Der Treffer bleibt auf der Watchlist, weil Cybersecurity, NIS2, Supplier Governance in EU zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für stackübergreifend, ohne sofortigen Planzwang.',
            'published_at' => '2026-04-01',
            'type' => 'Standard',
            'impact' => 'Relevant',
            'region' => 'EU',
            'topics' => ['Cybersecurity', 'NIS2', 'Supplier Governance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.enisa.europa.eu/news',
            'recommended_action' => 'Beobachten und bei Supplier-/Security-Reviews als Referenz ablegen. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'eu-ai-act-digital-strategy',
            'source_id' => 'eu-ai-office',
            'title' => 'EU Digital Strategy / AI Office: AI Act und Data Act News filtern',
            'summary' => 'Offizielle EU-Updates zu AI Act, Data Act und digitaler Regulierung — relevant für Ownership, Logging und Freigabeprozesse. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu AI Act, Data Act, AI Governance kurz gegen den Use Case halten. Region EU und stackübergreifend bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2026-07-10',
            'type' => 'Richtlinien',
            'impact' => 'Prüfen',
            'region' => 'EU',
            'topics' => ['AI Act', 'Data Act', 'AI Governance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://digital-strategy.ec.europa.eu/en/news',
            'recommended_action' => 'Prüfen, ob AI-Use-Cases und Data-Sharing-Pfade den aktuellen EU-Anforderungen entsprechen. AI Act gegen den Use Case spiegeln; nur bei Abweichung nachziehen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'iapp-cross-regulatory-dublin',
            'source_id' => 'iapp',
            'title' => 'IAPP: EDPB Dublin Meeting zu Cross-Regulatory Cooperation einordnen',
            'summary' => 'Privacy sitzt zunehmend neben Wettbewerb, Consumer Law und Digital Markets — IAPP fasst die Enforcement-Kooperationssignale gut zusammen. Der Treffer bleibt auf der Watchlist, weil Compliance, Datenschutz, Operating Model in EU zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für stackübergreifend, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-17',
            'type' => 'Governance News',
            'impact' => 'Relevant',
            'region' => 'EU',
            'topics' => ['Compliance', 'Datenschutz', 'Operating Model'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://iapp.org/news/a/edpb-high-level-meeting-in-dublin-further-deepens-consistency-and-enforcement-cooperation',
            'recommended_action' => 'Lesen und merken, wenn Data Sharing mehrere Regulierungsfelder gleichzeitig berührt. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'noyb-enforcement-signals',
            'source_id' => 'noyb',
            'title' => 'NOYB: Complaint- und Enforcement-Signale als Frühwarnung nutzen',
            'summary' => 'NOYB ist keine Aufsicht, aber ein starkes Signal für Cookie-, Consent- und Transfer-Themen, die später in Reviews landen. Als Merksatz behalten: Enforcement, Datenschutz, Complaints hängt mit angrenzenden Entscheidungen zusammen — in EU oft sichtbarer in Katalog, Freigabe oder Vendor-Reviews (stackübergreifend).',
            'published_at' => '2026-07-01',
            'type' => 'Governance News',
            'impact' => 'Info',
            'region' => 'EU',
            'topics' => ['Enforcement', 'Datenschutz', 'Complaints'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://noyb.eu/en/news',
            'recommended_action' => 'Als Frühwarn-Feed beobachten — nicht als Rechtsberatung oder Pflichtplan behandeln. Einordnen ohne neuen Workflow, außer der Scope ist klar betroffen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'purview-fabric-governance-docs',
            'source_id' => 'microsoft-purview',
            'title' => 'Microsoft Purview / Fabric: Catalog-, Classification- und Policy-Docs monitoren',
            'summary' => 'Für Fabric-/Purview-Landschaften sind Catalog, Sensitivity Labels und DLP zentrale Governance-Hebel. Der Treffer bleibt auf der Watchlist, weil Catalog, PII, Vendor Updates in Global zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für Fabric, Power BI, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-20',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Catalog', 'PII', 'Vendor Updates'],
            'stack' => ['Fabric', 'Power BI'],
            'url' => 'https://learn.microsoft.com/en-us/purview/',
            'recommended_action' => 'Dokumentation beobachten und bei Stack-Änderungen gegen den eigenen Fabric-/Purview-Stand spiegeln. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'dbt-governance-engineering',
            'source_id' => 'dbt-blog',
            'title' => 'dbt Blog: Tests, Docs und Analytics-Engineering-Governance mitlesen',
            'summary' => 'Viele Governance-Entscheidungen landen in dbt als Tests, Docs, Contracts oder Ownership-Konventionen. Als Praxisimpuls nützlich: Data Quality, Metadata, Best Practices nicht als isoliertes Tool-Feature denken, sondern als Entscheidungs-, Ownership- und Qualitätsfrage in Global-Kontexten (dbt).',
            'published_at' => '2026-07-15',
            'type' => 'Vendor Update',
            'impact' => 'Best Practice',
            'region' => 'Global',
            'topics' => ['Data Quality', 'Metadata', 'Best Practices'],
            'stack' => ['dbt'],
            'url' => 'https://www.getdbt.com/blog',
            'recommended_action' => 'Bei dbt-Stacks relevante Posts lesen — Tools nur öffnen, wenn eine konkrete Regel oder Doku ansteht. Als Referenz für die nächste verwandte Entscheidung behalten.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'oecd-data-governance-privacy',
            'source_id' => 'oecd-privacy',
            'title' => 'OECD: Data Governance- und Privacy-Policy-Seiten als Framework-Referenz halten',
            'summary' => 'OECD-Material hilft bei Policy- und Operating-Model-Diskussionen über nationale Aufsicht hinaus. Gut als Lagebild: Standard-Signale zu Data Governance, Privacy Framework, Policy helfen, Prioritäten und Sprachbilder in Global zu schärfen, ohne jedes Update in einen Ticket-Backlog zu übersetzen.',
            'published_at' => '2026-03-01',
            'type' => 'Standard',
            'impact' => 'Orientierung',
            'region' => 'Global',
            'topics' => ['Data Governance', 'Privacy Framework', 'Policy'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.oecd.org/en/topics/policy-issues/data-governance-and-privacy.html',
            'recommended_action' => 'Als Policy-Hintergrund lesen, nicht als operativen Ticket-Trigger. Einordnen ohne neuen Workflow, außer der Scope ist klar betroffen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'ico-guidance-watch',
            'source_id' => 'ico-rss',
            'title' => 'ICO: Guidance-, Blog- und Enforcement-Feeds beobachten',
            'summary' => 'UK-Guidance bleibt auch für EU-Stack-Teams nützlich, wenn Vendor, Transfers oder Decision Notices den eigenen Scope berühren. Der Treffer bleibt auf der Watchlist, weil Datenschutz, Enforcement, Praxishilfen in UK zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für stackübergreifend, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-12',
            'type' => 'Praxishilfe',
            'impact' => 'Relevant',
            'region' => 'UK',
            'topics' => ['Datenschutz', 'Enforcement', 'Praxishilfen'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://ico.org.uk/global/rss-feeds/',
            'recommended_action' => 'Feeds beobachten und nur bei UK-/Transfer-Bezug vertiefen. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'edps-newsletter-watch',
            'source_id' => 'edps-newsletter',
            'title' => 'EDPS Newsletter: AI Act und Institutionen-Datenschutz mitverfolgen',
            'summary' => 'EDPS-Positionen zu AI Act und EU-Institutionen liefern Frühsignale für Aufsichtspraxis und Policy-Schnittstellen. Gut als Lagebild: Governance News-Signale zu AI Act, Datenschutz, Richtlinien helfen, Prioritäten und Sprachbilder in EU zu schärfen, ohne jedes Update in einen Ticket-Backlog zu übersetzen.',
            'published_at' => '2026-06-01',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'EU',
            'topics' => ['AI Act', 'Datenschutz', 'Richtlinien'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.edps.europa.eu/press-publications/publications/newsletters_en',
            'recommended_action' => 'Zum Orientieren abonnieren bzw. Einordnen ohne neuen Workflow, außer der Scope ist klar betroffen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'snowflake-oidc-trust-center',
            'source_id' => 'snowflake-security',
            'title' => 'Snowflake: OIDC, Trust Center und Security-Release Notes prüfen',
            'summary' => 'Auth-, Federation- und Trust-Center-Änderungen können Access Policies, MFA und Vendor-Risiken in Snowflake-Landschaften verschieben. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu Security, Authentication, Trust Center kurz gegen den Use Case halten. Region Global und Snowflake, dbt bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2026-07-20',
            'type' => 'Security News',
            'impact' => 'Prüfen',
            'region' => 'Global',
            'topics' => ['Security', 'Authentication', 'Trust Center', 'Vendor Updates'],
            'stack' => ['Snowflake', 'dbt'],
            'url' => 'https://docs.snowflake.com/en/release-notes/2026/other/2026-07-17-oidc-federated-authentication-preview',
            'recommended_action' => 'Bei Snowflake-Umgebungen Auth-/Security-Notes lesen und gegen bestehende Integrationspfade prüfen. Security gegen den Use Case spiegeln; nur bei Abweichung nachziehen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'databricks-platform-security-updates',
            'source_id' => 'databricks-release-notes',
            'title' => 'Databricks Release Notes: Security- und Platform-Updates monitoren',
            'summary' => 'Workspace-, Unity-Catalog- und Security-Profile-Änderungen sollten parallel zur Governance-Doku beobachtet werden. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu Security, Unity Catalog, Vendor Updates kurz gegen den Use Case halten. Region Global und Databricks bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2026-07-18',
            'type' => 'Security News',
            'impact' => 'Prüfen',
            'region' => 'Global',
            'topics' => ['Security', 'Unity Catalog', 'Vendor Updates'],
            'stack' => ['Databricks'],
            'url' => 'https://docs.databricks.com/aws/en/release-notes/',
            'recommended_action' => 'Release Notes scannen und nur bei Security-/Access-Impact im Advisor vertiefen. Security gegen den Use Case spiegeln; nur bei Abweichung nachziehen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'fabric-whats-new-governance',
            'source_id' => 'microsoft-fabric-whats-new',
            'title' => 'Microsoft Fabric What’s new: Governance- und Security-Features filtern',
            'summary' => 'Fabric-Updates zu Workspaces, Domains, Sensitivity und Semantic Models betreffen oft Ownership und Freigabeprozesse. Der Treffer bleibt auf der Watchlist, weil Vendor Updates, Security, Semantic Models in Global zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für Fabric, Power BI, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-21',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Security', 'Semantic Models', 'Catalog'],
            'stack' => ['Fabric', 'Power BI'],
            'url' => 'https://learn.microsoft.com/en-us/fabric/get-started/whats-new',
            'recommended_action' => 'What’s-new-Liste nach Security/Governance filtern und gegen den eigenen Fabric-Stand spiegeln. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'power-bi-service-security',
            'source_id' => 'power-bi-blog',
            'title' => 'Power BI: Service-, Sharing- und Security-Updates beobachten',
            'summary' => 'Änderungen an Sharing, RLS, Apps und Admin-Settings können Report-Governance und Zugriffskontrolle betreffen. Der Treffer bleibt auf der Watchlist, weil Security, RLS, Vendor Updates in Global zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für Power BI, Fabric, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-16',
            'type' => 'Security News',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Security', 'RLS', 'Vendor Updates'],
            'stack' => ['Power BI', 'Fabric'],
            'url' => 'https://powerbi.microsoft.com/en-us/blog/',
            'recommended_action' => 'Blog/Service Updates mitlesen — bei Access-/RLS-Änderungen gegen Report-Freigaben prüfen. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'qlik-cloud-change-log',
            'source_id' => 'qlik-release-notes',
            'title' => 'Qlik Cloud Change Log: Security und Access Control monitoren',
            'summary' => 'Spaces, Roles und Security-Änderungen in Qlik Cloud beeinflussen Katalog-, App- und Section-Access-Governance. Der Treffer bleibt auf der Watchlist, weil Security, Access Control, Vendor Updates in Global zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für Qlik, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-14',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Security', 'Access Control', 'Vendor Updates'],
            'stack' => ['Qlik'],
            'url' => 'https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Introduction/saas-change-log.htm',
            'recommended_action' => 'Change Log auf Security/Access filtern und nur bei Treffern im eigenen Tenant vertiefen. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'tableau-releases-security',
            'source_id' => 'tableau-release-notes',
            'title' => 'Tableau Releases: Security Fixes und Permission-Änderungen prüfen',
            'summary' => 'Server-/Cloud-Releases können Security Patches, Auth- und Permission-Verhalten ändern — relevant für Catalog und Content Governance. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu Security, Permissions, Vendor Updates kurz gegen den Use Case halten. Region Global und Tableau bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2026-07-10',
            'type' => 'Security News',
            'impact' => 'Prüfen',
            'region' => 'Global',
            'topics' => ['Security', 'Permissions', 'Vendor Updates'],
            'stack' => ['Tableau'],
            'url' => 'https://www.tableau.com/support/releases',
            'recommended_action' => 'Release Notes auf Security/Permissions scannen und Patch-Bedarf gegen die eigene Tableau-Version prüfen. Security gegen den Use Case spiegeln; nur bei Abweichung nachziehen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'baylda-cloud-ki',
            'source_id' => 'baylda',
            'title' => 'BayLDA: Cloud-, KI- und Unternehmensdatenschutz-Hinweise mitlesen',
            'summary' => 'Bayerische Aufsichtspraxis liefert oft konkrete Checkfragen zu Cloud-Transfers, KI-Einsatz und Verantwortlichkeiten. Der Treffer bleibt auf der Watchlist, weil Datenschutz, Cloud, KI in DE zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für stackübergreifend, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-05',
            'type' => 'Praxishilfe',
            'impact' => 'Relevant',
            'region' => 'DE',
            'topics' => ['Datenschutz', 'Cloud', 'KI', 'Praxishilfen'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.lda.bayern.de/de/aktuelles.html',
            'recommended_action' => 'Aktuelles scannen und bei DE-Cloud-/KI-Projekten als Praxisreferenz ablegen. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'blnbdi-presse',
            'source_id' => 'blnbdi',
            'title' => 'BlnBDI: Presse und Tätigkeitsberichte als DE-Stadtstaaten-Signal nutzen',
            'summary' => 'Berliner Aufsichtsthemen zu Transparenz, öffentlichen Stellen und Enforcement ergänzen die Bundes- und Länderperspektive. Gut als Lagebild: Governance News-Signale zu Datenschutz, Informationsfreiheit, Enforcement helfen, Prioritäten und Sprachbilder in DE zu schärfen, ohne jedes Update in einen Ticket-Backlog zu übersetzen.',
            'published_at' => '2026-06-20',
            'type' => 'Governance News',
            'impact' => 'Orientierung',
            'region' => 'DE',
            'topics' => ['Datenschutz', 'Informationsfreiheit', 'Enforcement'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.datenschutz-berlin.de/presse/',
            'recommended_action' => 'Zum Orientieren mitlesen — vertiefen, wenn öffentliche oder Berliner Datenpfade betroffen sind. Einordnen ohne neuen Workflow, außer der Scope ist klar betroffen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'bsi-cloud-c5',
            'source_id' => 'bsi',
            'title' => 'BSI: Cloud-, C5- und Cybersecurity-Updates für Vendor Reviews nutzen',
            'summary' => 'BSI-Hinweise helfen, Cloud-Anbieter, Nachweise und Security Controls in Data-/Vendor-Governance einzubinden. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu Cybersecurity, Cloud, Supplier Governance kurz gegen den Use Case halten. Region DE und stackübergreifend bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2026-07-11',
            'type' => 'Security News',
            'impact' => 'Prüfen',
            'region' => 'DE',
            'topics' => ['Cybersecurity', 'Cloud', 'Supplier Governance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.bsi.bund.de/DE/Service-Navi/Presse/presse_node.html',
            'recommended_action' => 'Bei Cloud-/Vendor-Auswahl und C5-Nachweisen gegen aktuelle BSI-Hinweise prüfen. Cybersecurity gegen den Use Case spiegeln; nur bei Abweichung nachziehen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'cisa-supply-chain',
            'source_id' => 'cisa',
            'title' => 'CISA: Supply-Chain- und Incident-Guidance als Vendor-Risk-Signal beobachten',
            'summary' => 'CISA-Alerts zeigen früh, welche Vendor- und Infrastruktur-Risiken in Data-Plattformen und Integrationen landen können. Der Treffer bleibt auf der Watchlist, weil Cybersecurity, Vendor Risk, Supplier Governance in US zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für stackübergreifend, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-19',
            'type' => 'Security News',
            'impact' => 'Relevant',
            'region' => 'US',
            'topics' => ['Cybersecurity', 'Vendor Risk', 'Supplier Governance'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.cisa.gov/news-events/news',
            'recommended_action' => 'Feeds beobachten und bei betroffenen Vendor-/Cloud-Komponenten im Supplier-Review spiegeln. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'aws-security-iam',
            'source_id' => 'aws-security',
            'title' => 'AWS Security Blog: IAM-, Logging- und Control-Updates filtern',
            'summary' => 'IAM-, KMS- und Audit-Änderungen können Lakehouse-, Sharing- und Admin-Governance in AWS-Stacks verschieben. Kein Alarm, aber ein klarer Prüfpunkt: Zweck, Owner und vorhandene Controls zu Security, IAM, Cloud kurz gegen den Use Case halten. Region Global und AWS, Snowflake, dbt bestimmen, wie tief der Abgleich gehen muss.',
            'published_at' => '2026-07-18',
            'type' => 'Security News',
            'impact' => 'Prüfen',
            'region' => 'Global',
            'topics' => ['Security', 'IAM', 'Cloud', 'Vendor Updates'],
            'stack' => ['AWS', 'Snowflake', 'dbt'],
            'url' => 'https://aws.amazon.com/blogs/security/',
            'recommended_action' => 'Bei AWS-Landschaften Security-Posts zu IAM/Logging lesen und gegen Access Policies prüfen. Security gegen den Use Case spiegeln; nur bei Abweichung nachziehen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'gcp-security-identity',
            'source_id' => 'gcp-security',
            'title' => 'Google Cloud Security: Identity- und Compliance-Updates monitoren',
            'summary' => 'Identity-, VPC- und Compliance-Features beeinflussen Governance für BigQuery-, Dataplex- und AI-Workloads. Der Treffer bleibt auf der Watchlist, weil Security, IAM, Cloud in Global zunehmend in Reviews, Vendor-Updates oder Operating-Model-Fragen auftaucht — relevant für Google Cloud, BigQuery, ohne sofortigen Planzwang.',
            'published_at' => '2026-07-17',
            'type' => 'Security News',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Security', 'IAM', 'Cloud', 'Vendor Updates'],
            'stack' => ['Google Cloud', 'BigQuery'],
            'url' => 'https://cloud.google.com/blog/products/identity-security',
            'recommended_action' => 'Identity-/Security-Updates filtern und gegen den eigenen GCP-Stand spiegeln. Nur markieren, wenn der eigene Stack betroffen ist.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'collibra-catalog-ops',
            'source_id' => 'collibra-blog',
            'title' => 'Collibra: Catalog-, Stewardship- und DQ-Operating-Model mitlesen',
            'summary' => 'Catalog-Vendor-Praxis hilft, Ownership, Glossar und Data-Quality-Workflows als Operating Model statt Tool-Feature zu denken. Als Praxisimpuls nützlich: Catalog, Data Quality, Operating Model nicht als isoliertes Tool-Feature denken, sondern als Entscheidungs-, Ownership- und Qualitätsfrage in Global-Kontexten (stackübergreifend).',
            'published_at' => '2026-07-09',
            'type' => 'Vendor Update',
            'impact' => 'Best Practice',
            'region' => 'Global',
            'topics' => ['Catalog', 'Data Quality', 'Operating Model'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.collibra.com/us/en/blog',
            'recommended_action' => 'Als Operating-Model-Referenz lesen — nicht automatisch als Tool-Wechsel behandeln. Als Referenz für die nächste verwandte Entscheidung behalten.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'alation-data-literacy',
            'source_id' => 'alation-blog',
            'title' => 'Alation: Data Literacy und Catalog Governance als Adoption-Hebel sehen',
            'summary' => 'Catalog-Adoption hängt an Literacy, Search und Stewardship — nicht nur an technischen Metadatenfeldern. Als Praxisimpuls nützlich: Catalog, Data Literacy, Operating Model nicht als isoliertes Tool-Feature denken, sondern als Entscheidungs-, Ownership- und Qualitätsfrage in Global-Kontexten (stackübergreifend).',
            'published_at' => '2026-07-08',
            'type' => 'Vendor Update',
            'impact' => 'Best Practice',
            'region' => 'Global',
            'topics' => ['Catalog', 'Data Literacy', 'Operating Model'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.alation.com/blog/',
            'recommended_action' => 'Bei Catalog-Einführung Literacy- und Steward-Themen mitlesen. Als Referenz für die nächste verwandte Entscheidung behalten.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'iso-ai-security-standards',
            'source_id' => 'iso-news',
            'title' => 'ISO: Security-, Quality- und AI-Standards als Framework-Referenz halten',
            'summary' => 'ISO-Updates zu 27001-nahen und AI-bezogenen Standards helfen bei Policy-Mapping, nicht als Tages-Ticket. Gut als Lagebild: Standard-Signale zu ISO 27001, AI Governance, Risk Management helfen, Prioritäten und Sprachbilder in Global zu schärfen, ohne jedes Update in einen Ticket-Backlog zu übersetzen.',
            'published_at' => '2026-05-15',
            'type' => 'Standard',
            'impact' => 'Orientierung',
            'region' => 'Global',
            'topics' => ['ISO 27001', 'AI Governance', 'Risk Management'],
            'stack' => ['Alle Stacks'],
            'url' => 'https://www.iso.org/news.html',
            'recommended_action' => 'Als Framework-Hintergrund nutzen, wenn Policies oder Zertifizierungen anstehen. Einordnen ohne neuen Workflow, außer der Scope ist klar betroffen.',
            'origin' => 'example',
            'language' => 'de',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-snowflake-rn-latest',
            'source_id' => 'snowflake-release-notes',
            'title' => 'Snowflake Release Notes — latest platform updates',
            'summary' => 'Raw watch item for Snowflake release notes covering warehouse, security, governance and data-sharing changes. Open the source for the current changelog.',
            'published_at' => '2026-07-26',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Security', 'Catalog'],
            'stack' => ['Snowflake'],
            'url' => 'https://docs.snowflake.com/en/release-notes/all-release-notes',
            'recommended_action' => 'Scan the latest notes for security, policy and sharing changes in your Snowflake accounts.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-databricks-rn-latest',
            'source_id' => 'databricks-release-notes',
            'title' => 'Databricks Release Notes — platform and security updates',
            'summary' => 'Raw watch item for Databricks platform release notes, including Unity Catalog, workspace and security profile changes.',
            'published_at' => '2026-07-26',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Unity Catalog', 'Security'],
            'stack' => ['Databricks'],
            'url' => 'https://docs.databricks.com/aws/en/release-notes/',
            'recommended_action' => 'Review recent notes for access-control or catalog changes affecting your workspaces.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-fabric-whats-new-latest',
            'source_id' => 'microsoft-fabric-whats-new',
            'title' => 'Microsoft Fabric — What’s new',
            'summary' => 'Raw watch item for Fabric What’s new updates across workspaces, governance, security and semantic model features.',
            'published_at' => '2026-07-26',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Security', 'Semantic Models'],
            'stack' => ['Fabric', 'Power BI'],
            'url' => 'https://learn.microsoft.com/en-us/fabric/get-started/whats-new',
            'recommended_action' => 'Filter What’s new for governance and security entries relevant to your tenant.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-purview-docs-latest',
            'source_id' => 'microsoft-purview',
            'title' => 'Microsoft Purview documentation updates',
            'summary' => 'Raw watch item for Purview catalog, classification, DLP and Fabric governance documentation changes.',
            'published_at' => '2026-07-26',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Catalog', 'PII', 'Vendor Updates'],
            'stack' => ['Fabric', 'Power BI'],
            'url' => 'https://learn.microsoft.com/en-us/purview/',
            'recommended_action' => 'Check Purview docs when catalog or label policies change in your Microsoft stack.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-powerbi-blog-latest',
            'source_id' => 'power-bi-blog',
            'title' => 'Power BI Blog — service and security updates',
            'summary' => 'Raw watch item for Power BI service blog posts covering sharing, RLS, admin and security updates.',
            'published_at' => '2026-07-26',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Security', 'RLS'],
            'stack' => ['Power BI', 'Fabric'],
            'url' => 'https://powerbi.microsoft.com/en-us/blog/',
            'recommended_action' => 'Scan recent posts for sharing, RLS or admin setting changes.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-qlik-changelog-latest',
            'source_id' => 'qlik-release-notes',
            'title' => 'Qlik Cloud SaaS change log',
            'summary' => 'Raw watch item for the Qlik Cloud change log covering spaces, roles, security and catalog-related updates.',
            'published_at' => '2026-07-26',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Vendor Updates', 'Security', 'Access Control'],
            'stack' => ['Qlik'],
            'url' => 'https://help.qlik.com/en-US/cloud-services/Subsystems/Hub/Content/Sense_Hub/Introduction/saas-change-log.htm',
            'recommended_action' => 'Filter the change log for security and access-control entries in your tenant.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-tableau-releases-latest',
            'source_id' => 'tableau-release-notes',
            'title' => 'Tableau release notes and security updates',
            'summary' => 'Raw watch item for Tableau Desktop/Server/Cloud releases including security fixes and permission changes.',
            'published_at' => '2026-07-26',
            'type' => 'Security News',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Security', 'Permissions', 'Vendor Updates'],
            'stack' => ['Tableau'],
            'url' => 'https://www.tableau.com/support/releases',
            'recommended_action' => 'Check release notes for security patches matching your Tableau version.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-dbt-blog-latest',
            'source_id' => 'dbt-blog',
            'title' => 'dbt Labs Blog — latest posts',
            'summary' => 'Raw watch item for dbt Labs blog posts on analytics engineering, tests, docs and related governance practices.',
            'published_at' => '2026-07-26',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Data Quality', 'Metadata', 'Vendor Updates'],
            'stack' => ['dbt'],
            'url' => 'https://www.getdbt.com/blog',
            'recommended_action' => 'Open recent posts when evaluating dbt testing, docs or contract patterns.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-aws-security-latest',
            'source_id' => 'aws-security',
            'title' => 'AWS Security Blog — latest posts',
            'summary' => 'Raw watch item for AWS Security Blog updates on IAM, encryption, logging and control-plane changes.',
            'published_at' => '2026-07-26',
            'type' => 'Security News',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Security', 'IAM', 'Cloud'],
            'stack' => ['AWS'],
            'url' => 'https://aws.amazon.com/blogs/security/',
            'recommended_action' => 'Scan recent posts for IAM or audit changes affecting your AWS data paths.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-gcp-security-latest',
            'source_id' => 'gcp-security',
            'title' => 'Google Cloud identity & security updates',
            'summary' => 'Raw watch item for Google Cloud identity and security blog updates relevant to BigQuery and GCP governance.',
            'published_at' => '2026-07-26',
            'type' => 'Security News',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Security', 'IAM', 'Cloud'],
            'stack' => ['Google Cloud', 'BigQuery'],
            'url' => 'https://cloud.google.com/blog/products/identity-security',
            'recommended_action' => 'Review recent identity/security posts for GCP projects you operate.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-collibra-blog-latest',
            'source_id' => 'collibra-blog',
            'title' => 'Collibra Blog — latest posts',
            'summary' => 'Raw watch item for Collibra blog posts on catalog, stewardship and data-quality operating models.',
            'published_at' => '2026-07-26',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Catalog', 'Data Quality', 'Operating Model'],
            'stack' => [],
            'url' => 'https://www.collibra.com/us/en/blog',
            'recommended_action' => 'Use as an optional catalog/operating-model signal — not a mandatory translation task.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
        [
            'id' => 'vendor-alation-blog-latest',
            'source_id' => 'alation-blog',
            'title' => 'Alation Blog — latest posts',
            'summary' => 'Raw watch item for Alation blog posts on data literacy, catalog adoption and governance workflows.',
            'published_at' => '2026-07-26',
            'type' => 'Vendor Update',
            'impact' => 'Relevant',
            'region' => 'Global',
            'topics' => ['Catalog', 'Data Literacy', 'Operating Model'],
            'stack' => [],
            'url' => 'https://www.alation.com/blog/',
            'recommended_action' => 'Open when comparing catalog adoption or literacy practices.',
            'origin' => 'vendor',
            'language' => 'en',
            'ingest' => false,

        ],
    ],
];
