<?php

/**
 * Wave 2 quality overlays — ERP/HCM source-native DQ, MDM, metadata guides.
 *
 * @return array<string, array<string, mixed>>
 */

return [
    'sap-s4hana' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'sap-open-order-no-kunnr',
                    'priority' => 'high',
                    'title' => ['de' => 'Offener Auftrag ohne kunnr', 'en' => 'Open order without kunnr'],
                    'problem' => ['de' => 'VBAK ohne kunnr lässt Backlog und Order-Intake nicht nach Kunde/Region schneiden.', 'en' => 'VBAK without kunnr cannot slice backlog and order intake by customer/region.'],
                    'prevent' => ['de' => 'Auftragserfassung: Sold-to Party Pflicht; Customizing prüfen.', 'en' => 'Order entry: sold-to party required; review customizing.'],
                    'staffNeedToKnow' => ['de' => 'SD: Jeder Vertriebsauftrag braucht einen gültigen Debitor (kunnr).', 'en' => 'SD: Every sales order needs a valid customer (kunnr).'],
                    'checks' => ['de' => 'VBAK.kunnr IS NULL AND gbstk NOT IN (closed/cancelled codes)', 'en' => 'VBAK.kunnr IS NULL AND gbstk NOT IN (closed/cancelled codes)'],
                    'fixInSource' => ['de' => 'Mandatory sold-to in order type; block save without kunnr.', 'en' => 'Mandatory sold-to in order type; block save without kunnr.'],
                    'fixInWarehouse' => ['de' => 'Unknown-customer dim; exclude from customer KPIs.', 'en' => 'Unknown-customer dim; exclude from customer KPIs.'],
                ],
                [
                    'id' => 'sap-vbap-matnr-null',
                    'priority' => 'high',
                    'title' => ['de' => 'Position ohne matnr', 'en' => 'Line item without matnr'],
                    'problem' => ['de' => 'VBAP ohne matnr bricht Produktmix, Units und Materialgruppen-Reports.', 'en' => 'VBAP without matnr breaks product mix, units and material group reports.'],
                    'prevent' => ['de' => 'Materialnummer Pflicht für relevante Positionstypen; Textpositionen separat taggen.', 'en' => 'Material number required for relevant item categories; tag text items separately.'],
                    'staffNeedToKnow' => ['de' => 'SD: Produktzeilen brauchen matnr — Textpositionen nur bewusst nutzen.', 'en' => 'SD: Product lines need matnr — use text items deliberately only.'],
                    'checks' => ['de' => 'VBAP.matnr IS NULL AND pstyv NOT IN (text item types)', 'en' => 'VBAP.matnr IS NULL AND pstyv NOT IN (text item types)'],
                    'fixInSource' => ['de' => 'Item category rules; material required on product lines.', 'en' => 'Item category rules; material required on product lines.'],
                    'fixInWarehouse' => ['de' => 'Flag non-material lines; separate KPI.', 'en' => 'Flag non-material lines; separate KPI.'],
                ],
                [
                    'id' => 'sap-netwr-null-open',
                    'priority' => 'high',
                    'title' => ['de' => 'Offener Auftrag ohne netwr', 'en' => 'Open order without netwr'],
                    'problem' => ['de' => 'Offene VBAK/VBAP ohne netwr macht Backlog und Pipeline unbrauchbar.', 'en' => 'Open VBAK/VBAP without netwr makes backlog and pipeline unusable.'],
                    'prevent' => ['de' => 'Preisfindung vor Freigabe; netwr aus Konditionen ableiten lassen.', 'en' => 'Pricing before release; derive netwr from conditions.'],
                    'staffNeedToKnow' => ['de' => 'SD: Auftrag nicht freigeben, wenn Positionswerte fehlen.', 'en' => 'SD: Do not release order when line values are missing.'],
                    'checks' => ['de' => 'netwr IS NULL OR netwr = 0 on open order lines', 'en' => 'netwr IS NULL OR netwr = 0 on open order lines'],
                    'fixInSource' => ['de' => 'Pricing procedure; block release without values.', 'en' => 'Pricing procedure; block release without values.'],
                    'fixInWarehouse' => ['de' => 'Exclude from backlog or impute policy documented.', 'en' => 'Exclude from backlog or document impute policy.'],
                ],
                [
                    'id' => 'sap-fi-no-bukrs',
                    'priority' => 'medium',
                    'title' => ['de' => 'FI-Beleg ohne bukrs', 'en' => 'FI document without bukrs'],
                    'problem' => ['de' => 'BKPF/BSEG ohne bukrs verhindert Legal-Entity- und Währungs-Schnitte.', 'en' => 'BKPF/BSEG without bukrs prevents legal entity and currency slices.'],
                    'prevent' => ['de' => 'Buchungskreis immer aus Kontext; Integration schreibt bukrs mit.', 'en' => 'Company code always from context; integration always writes bukrs.'],
                    'staffNeedToKnow' => ['de' => 'FI: Kein Beleg ohne Buchungskreis — Mandant/Company Code prüfen.', 'en' => 'FI: No document without company code — check client/company code.'],
                    'checks' => ['de' => 'bukrs IS NULL on BKPF or BSEG', 'en' => 'bukrs IS NULL on BKPF or BSEG'],
                    'fixInSource' => ['de' => 'Mandatory bukrs in posting interface.', 'en' => 'Mandatory bukrs in posting interface.'],
                    'fixInWarehouse' => ['de' => 'Quarantine rows; exclude from P&L.', 'en' => 'Quarantine rows; exclude from P&L.'],
                ],
                [
                    'id' => 'sap-audat-before-erdat',
                    'priority' => 'medium',
                    'title' => ['de' => 'audat vor erdat', 'en' => 'audat before erdat'],
                    'problem' => ['de' => 'Auftragsdatum vor Erfassungsdatum verfälscht Order-Intake und Cycle-Metriken.', 'en' => 'Order date before created date distorts order intake and cycle metrics.'],
                    'prevent' => ['de' => 'Validation bei manueller Datumsänderung; Migrationen dokumentieren.', 'en' => 'Validation on manual date changes; document migrations.'],
                    'staffNeedToKnow' => ['de' => 'SD: audat = realer Auftragseingang — nicht rückdatiert ohne Prozess.', 'en' => 'SD: audat = real order receipt — no backdating without process.'],
                    'checks' => ['de' => 'audat < erdat on VBAK', 'en' => 'audat < erdat on VBAK'],
                    'fixInSource' => ['de' => 'User exit / validation on date fields.', 'en' => 'User exit / validation on date fields.'],
                    'fixInWarehouse' => ['de' => 'Flag invalid dates; use erdat fallback.', 'en' => 'Flag invalid dates; use erdat fallback.'],
                ],
                [
                    'id' => 'sap-duplicate-kunnr-email',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte kunnr mit gleicher E-Mail', 'en' => 'Duplicate kunnr with same email'],
                    'problem' => ['de' => 'Mehrere KNA1 mit gleicher smtp_addr verzerren Customer-Counts und DSDR.', 'en' => 'Multiple KNA1 with same smtp_addr distort customer counts and DSDR.'],
                    'prevent' => ['de' => 'Duplikat-Check bei Debitor-Anlage; MDM-Golden Record.', 'en' => 'Duplicate check on customer create; MDM golden record.'],
                    'staffNeedToKnow' => ['de' => 'Master Data: Vor Neuanlage bestehenden Debitor suchen.', 'en' => 'Master data: Search existing customer before create.'],
                    'checks' => ['de' => 'COUNT(DISTINCT kunnr) GROUP BY smtp_addr HAVING COUNT > 1', 'en' => 'COUNT(DISTINCT kunnr) GROUP BY smtp_addr HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Duplicate check program; MDM merge workflow.', 'en' => 'Duplicate check program; MDM merge workflow.'],
                    'fixInWarehouse' => ['de' => 'Golden customer id; merge map table.', 'en' => 'Golden customer id; merge map table.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'sap-customer-dup',
                    'entity' => 'KNA1',
                    'title' => ['de' => 'Doppelte Debitoren', 'en' => 'Duplicate customers'],
                    'matchKeys' => ['kunnr', 'smtp_addr', 'name1 + land1 + pstlz', 'External Id (Z-field)'],
                    'preventInSource' => ['de' => 'Duplikat-Prüfung bei Anlage; Business Partner Central wenn verfügbar.', 'en' => 'Duplicate check on create; Business Partner Central if available.'],
                    'resolveInWarehouse' => ['de' => 'Golden kunnr; merge map für Duplikate.', 'en' => 'Golden kunnr; merge map for duplicates.'],
                    'survivorship' => ['de' => 'External Id gewinnt; dann höchster Umsatz / neueste Activity.', 'en' => 'External id wins; then highest revenue / latest activity.'],
                ],
                [
                    'id' => 'sap-material-dup',
                    'entity' => 'MARA',
                    'title' => ['de' => 'Material-Duplikate / Legacy-Nummern', 'en' => 'Material duplicates / legacy numbers'],
                    'matchKeys' => ['matnr', 'ean11/gtin', 'External Id', 'Legacy material number'],
                    'preventInSource' => ['de' => 'Materialnummern-Intervall steuern; Cross-Reference Tables pflegen.', 'en' => 'Control material number ranges; maintain cross-reference tables.'],
                    'resolveInWarehouse' => ['de' => 'Canonical matnr via cross-ref; legacy map table.', 'en' => 'Canonical matnr via cross-ref; legacy map table.'],
                    'survivorship' => ['de' => 'Aktives Material mit GTIN gewinnt.', 'en' => 'Active material with GTIN wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'sap-se11-dict',
                    'area' => ['de' => 'SE11 Data Dictionary', 'en' => 'SE11 Data Dictionary'],
                    'setting' => ['de' => 'Tabellen/Felder für Load-Allowlist dokumentieren', 'en' => 'Document tables/fields for load allowlist'],
                    'why' => ['de' => 'Stabile Feld-Inventare für PII und DQ.', 'en' => 'Stable field inventories for PII and DQ.'],
                    'how' => ['de' => 'SE11 → Table/Field Display; Export für Data Catalog.', 'en' => 'SE11 → table/field display; export for data catalog.'],
                ],
                [
                    'id' => 'sap-order-type',
                    'area' => ['de' => 'Customizing → Sales Document Types', 'en' => 'Customizing → sales document types'],
                    'setting' => ['de' => 'Sold-to / Material Pflicht für relevante Auftragsarten', 'en' => 'Sold-to / material required for relevant order types'],
                    'why' => ['de' => 'Verhindert offene Aufträge ohne kunnr/matnr.', 'en' => 'Prevents open orders without kunnr/matnr.'],
                    'how' => ['de' => 'VOV8/VOFA prüfen; Mandatory Partner/Material pro Auftragsart.', 'en' => 'Review VOV8/VOFA; mandatory partner/material per order type.'],
                ],
                [
                    'id' => 'sap-cds-views',
                    'area' => ['de' => 'CDS Views / Fiori Analytical Apps', 'en' => 'CDS views / Fiori analytical apps'],
                    'setting' => ['de' => 'CDS-Expose-Liste als Extract-Quelle nutzen', 'en' => 'Use CDS expose list as extract source'],
                    'why' => ['de' => 'Vermeidet rohe Tabellen-Sync ohne Semantik.', 'en' => 'Avoids raw table sync without semantics.'],
                    'how' => ['de' => 'View Browser / IWFND — erlaubte Views whitelisten.', 'en' => 'View Browser / IWFND — allowlist permitted views.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'sap-se11',
                    'kind' => ['de' => 'Data Dictionary (SE11)', 'en' => 'Data Dictionary (SE11)'],
                    'where' => ['de' => 'SE11 → Table/Structure/Domain; DDIC in ADT', 'en' => 'SE11 → table/structure/domain; DDIC in ADT'],
                    'how' => ['de' => 'UI oder ADT Data Preview; DD03L/DD04T für Batch-Export.', 'en' => 'UI or ADT data preview; DD03L/DD04T for batch export.'],
                    'useFor' => ['de' => 'Feld-Inventar, PII-Tags, Load-Allowlist, DQ-Checks.', 'en' => 'Field inventory, PII tags, load allowlist, DQ checks.'],
                    'watchouts' => ['de' => 'Z-Felder und Customizing-Tabellen pro Mandant unterschiedlich.', 'en' => 'Z-fields and customizing tables differ per client.'],
                ],
                [
                    'id' => 'sap-cds',
                    'kind' => ['de' => 'CDS Views', 'en' => 'CDS views'],
                    'where' => ['de' => 'Eclipse ADT → CDS Views; Fiori View Browser', 'en' => 'Eclipse ADT → CDS views; Fiori View Browser'],
                    'how' => ['de' => 'View Browser, @Analytics.dataCategory Annotationen lesen.', 'en' => 'View Browser, read @Analytics.dataCategory annotations.'],
                    'useFor' => ['de' => 'Semantische Extracts, Fact/Dim-Kandidaten.', 'en' => 'Semantic extracts, fact/dim candidates.'],
                    'watchouts' => ['de' => 'Released vs. local CDS — Transport-Status prüfen.', 'en' => 'Released vs local CDS — check transport status.'],
                ],
                [
                    'id' => 'sap-idoc-segments',
                    'kind' => ['de' => 'IDoc segments / WE60', 'en' => 'IDoc segments / WE60'],
                    'where' => ['de' => 'WE60 → IDoc Types / Segments; BD64 Partner Profiles', 'en' => 'WE60 → IDoc types / segments; BD64 partner profiles'],
                    'how' => ['de' => 'Segment-Dokumentation für Integrations-Mapping.', 'en' => 'Segment documentation for integration mapping.'],
                    'useFor' => ['de' => 'Integrations-Feld-Mapping — nicht als Mart-Load missbrauchen.', 'en' => 'Integration field mapping — do not misuse as mart load.'],
                    'watchouts' => ['de' => 'Partner-Segmente können PII enthalten — skip default.', 'en' => 'Partner segments can contain PII — skip by default.'],
                ],
                [
                    'id' => 'sap-customizing',
                    'kind' => ['de' => 'Customizing tables (SPRO)', 'en' => 'Customizing tables (SPRO)'],
                    'where' => ['de' => 'SPRO → relevante IMG-Pfade; Tabellen TV*/T*', 'en' => 'SPRO → relevant IMG paths; tables TV*/T*'],
                    'how' => ['de' => 'Customizing-Transporte dokumentieren; Read-Only Extract für Dims.', 'en' => 'Document customizing transports; read-only extract for dims.'],
                    'useFor' => ['de' => 'Status-/Stage-Maps, Währungen, Auftragsarten.', 'en' => 'Status/stage maps, currencies, order types.'],
                    'watchouts' => ['de' => 'Mandantenübergreifende Unterschiede — nicht blind mergen.', 'en' => 'Cross-client differences — do not merge blindly.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'netsuite' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'ns-invoice-no-entity',
                    'priority' => 'high',
                    'title' => ['de' => 'Rechnung ohne Entity/Kunde', 'en' => 'Invoice without entity/customer'],
                    'problem' => ['de' => 'Transactions ohne entity schneiden AR/Revenue nicht nach Kunde.', 'en' => 'Transactions without entity cannot slice AR/revenue by customer.'],
                    'prevent' => ['de' => 'Required entity auf Invoice/SO Record Types; Workflow-Validation.', 'en' => 'Required entity on invoice/SO record types; workflow validation.'],
                    'staffNeedToKnow' => ['de' => 'Finance: Jede Rechnung braucht einen Customer/Vendor.', 'en' => 'Finance: Every invoice needs a customer/vendor.'],
                    'checks' => ['de' => 'entity IS NULL on transaction WHERE type IN (CustInvc, SalesOrd)', 'en' => 'entity IS NULL on transaction WHERE type IN (CustInvc, SalesOrd)'],
                    'fixInSource' => ['de' => 'Required field + workflow on save.', 'en' => 'Required field + workflow on save.'],
                    'fixInWarehouse' => ['de' => 'Unknown-entity dim; exclude from customer KPIs.', 'en' => 'Unknown-entity dim; exclude from customer KPIs.'],
                ],
                [
                    'id' => 'ns-line-no-item',
                    'priority' => 'high',
                    'title' => ['de' => 'Position ohne Item', 'en' => 'Line without item'],
                    'problem' => ['de' => 'Transaction lines ohne item brechen Produktmix und Units.', 'en' => 'Transaction lines without item break product mix and units.'],
                    'prevent' => ['de' => 'Item required auf Product Lines; Service/Description Lines taggen.', 'en' => 'Item required on product lines; tag service/description lines.'],
                    'staffNeedToKnow' => ['de' => 'Ops: Produktzeilen brauchen Item — Freitextzeilen separat.', 'en' => 'Ops: Product lines need item — separate free-text lines.'],
                    'checks' => ['de' => 'item IS NULL on transactionline WHERE itemtype = product', 'en' => 'item IS NULL on transactionline WHERE itemtype = product'],
                    'fixInSource' => ['de' => 'Required item on line types; custom line category.', 'en' => 'Required item on line types; custom line category.'],
                    'fixInWarehouse' => ['de' => 'Flag non-product lines.', 'en' => 'Flag non-product lines.'],
                ],
                [
                    'id' => 'ns-open-so-no-subsidiary',
                    'priority' => 'medium',
                    'title' => ['de' => 'Offene SO ohne subsidiary', 'en' => 'Open SO without subsidiary'],
                    'problem' => ['de' => 'Fehlende subsidiary verhindert Legal-Entity-Reporting in OneWorld.', 'en' => 'Missing subsidiary prevents legal entity reporting in OneWorld.'],
                    'prevent' => ['de' => 'Subsidiary Default aus User/Role; Required auf Transaction.', 'en' => 'Subsidiary default from user/role; required on transaction.'],
                    'staffNeedToKnow' => ['de' => 'OneWorld: Subsidiary immer setzen — nicht leer lassen.', 'en' => 'OneWorld: Always set subsidiary — never leave blank.'],
                    'checks' => ['de' => 'subsidiary IS NULL on open SalesOrd', 'en' => 'subsidiary IS NULL on open SalesOrd'],
                    'fixInSource' => ['de' => 'Default subsidiary; required field.', 'en' => 'Default subsidiary; required field.'],
                    'fixInWarehouse' => ['de' => 'Map to default subsidiary with flag.', 'en' => 'Map to default subsidiary with flag.'],
                ],
                [
                    'id' => 'ns-amount-null-posted',
                    'priority' => 'high',
                    'title' => ['de' => 'Gebuchte Transaktion ohne Amount', 'en' => 'Posted transaction without amount'],
                    'problem' => ['de' => 'Posted Invoices mit NULL/0 Amount verzerren Revenue.', 'en' => 'Posted invoices with NULL/0 amount distort revenue.'],
                    'prevent' => ['de' => 'Approval Workflow vor Posting; Line Amounts required.', 'en' => 'Approval workflow before posting; line amounts required.'],
                    'staffNeedToKnow' => ['de' => 'Finance: Nicht buchen ohne Line Amounts.', 'en' => 'Finance: Do not post without line amounts.'],
                    'checks' => ['de' => 'foreignamount IS NULL OR foreignamount = 0 on posted CustInvc', 'en' => 'foreignamount IS NULL OR foreignamount = 0 on posted CustInvc'],
                    'fixInSource' => ['de' => 'Workflow block posting; required amounts.', 'en' => 'Workflow block posting; required amounts.'],
                    'fixInWarehouse' => ['de' => 'Exclude from revenue or flag.', 'en' => 'Exclude from revenue or flag.'],
                ],
                [
                    'id' => 'ns-employee-no-dept',
                    'priority' => 'medium',
                    'title' => ['de' => 'Employee ohne Department', 'en' => 'Employee without department'],
                    'problem' => ['de' => 'Employees ohne department brechen Headcount- und Kosten-Schnitte.', 'en' => 'Employees without department break headcount and cost slices.'],
                    'prevent' => ['de' => 'Department required on Employee record; HR onboarding checklist.', 'en' => 'Department required on employee record; HR onboarding checklist.'],
                    'staffNeedToKnow' => ['de' => 'HR: Department bei Anlage Pflicht.', 'en' => 'HR: Department required on create.'],
                    'checks' => ['de' => 'department IS NULL on employee WHERE isinactive = F', 'en' => 'department IS NULL on employee WHERE isinactive = F'],
                    'fixInSource' => ['de' => 'Required field; onboarding workflow.', 'en' => 'Required field; onboarding workflow.'],
                    'fixInWarehouse' => ['de' => 'Unknown department bucket.', 'en' => 'Unknown department bucket.'],
                ],
                [
                    'id' => 'ns-trandate-future',
                    'priority' => 'low',
                    'title' => ['de' => 'trandate in der Zukunft', 'en' => 'trandate in the future'],
                    'problem' => ['de' => 'Zukünftige trandate verschiebt Perioden-KPIs.', 'en' => 'Future trandate shifts period KPIs.'],
                    'prevent' => ['de' => 'Validation: trandate ≤ today + grace window.', 'en' => 'Validation: trandate ≤ today + grace window.'],
                    'staffNeedToKnow' => ['de' => 'Finance: Buchungsdatum = realer Geschäftsvorfall.', 'en' => 'Finance: Transaction date = real business event.'],
                    'checks' => ['de' => 'trandate > CURRENT_DATE on posted transactions', 'en' => 'trandate > CURRENT_DATE on posted transactions'],
                    'fixInSource' => ['de' => 'User event / workflow validation.', 'en' => 'User event / workflow validation.'],
                    'fixInWarehouse' => ['de' => 'Cap to posting period or quarantine.', 'en' => 'Cap to posting period or quarantine.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'ns-customer-dup',
                    'entity' => 'customer',
                    'title' => ['de' => 'Doppelte Customers', 'en' => 'Duplicate customers'],
                    'matchKeys' => ['email', 'entityid', 'companyname + subsidiary', 'externalid'],
                    'preventInSource' => ['de' => 'Duplicate Detection (Bundle); Merge Customers tool.', 'en' => 'Duplicate detection (bundle); merge customers tool.'],
                    'resolveInWarehouse' => ['de' => 'Golden internalid; merge map.', 'en' => 'Golden internalid; merge map.'],
                    'survivorship' => ['de' => 'externalid gewinnt; dann höchster Lifetime Revenue.', 'en' => 'externalid wins; then highest lifetime revenue.'],
                ],
                [
                    'id' => 'ns-item-dup',
                    'entity' => 'item',
                    'title' => ['de' => 'Item-Duplikate / SKU-Split', 'en' => 'Item duplicates / SKU split'],
                    'matchKeys' => ['itemid', 'upccode', 'vendorname + vendorcode'],
                    'preventInSource' => ['de' => 'Unique itemid per subsidiary; SKU governance.', 'en' => 'Unique itemid per subsidiary; SKU governance.'],
                    'resolveInWarehouse' => ['de' => 'Canonical item internalid via upccode.', 'en' => 'Canonical item internalid via upccode.'],
                    'survivorship' => ['de' => 'Active item with UPC wins.', 'en' => 'Active item with UPC wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'ns-records-catalog',
                    'area' => ['de' => 'Customization → Records Catalog', 'en' => 'Customization → Records Catalog'],
                    'setting' => ['de' => 'Record Types und Custom Fields inventarisieren', 'en' => 'Inventory record types and custom fields'],
                    'why' => ['de' => 'Basis für Allowlist und PII-Scan.', 'en' => 'Basis for allowlist and PII scan.'],
                    'how' => ['de' => 'Records Catalog durchsuchen; Export für Data Catalog.', 'en' => 'Browse Records Catalog; export for data catalog.'],
                ],
                [
                    'id' => 'ns-suiteql',
                    'area' => ['de' => 'SuiteAnalytics → SuiteQL', 'en' => 'SuiteAnalytics → SuiteQL'],
                    'setting' => ['de' => 'SuiteQL-Queries als Extract-Contract dokumentieren', 'en' => 'Document SuiteQL queries as extract contract'],
                    'why' => ['de' => 'Stabile Semantik statt Ad-hoc Saved Search Sprawl.', 'en' => 'Stable semantics vs ad-hoc saved search sprawl.'],
                    'how' => ['de' => 'Query Library pflegen; Versionierung in Git.', 'en' => 'Maintain query library; version in Git.'],
                ],
                [
                    'id' => 'ns-workflow-validation',
                    'area' => ['de' => 'Customization → Workflow / Client Script', 'en' => 'Customization → workflow / client script'],
                    'setting' => ['de' => 'Required entity/amount vor Posting', 'en' => 'Required entity/amount before posting'],
                    'why' => ['de' => 'Schließt KPI-kritische Lücken an der Quelle.', 'en' => 'Closes KPI-critical gaps at source.'],
                    'how' => ['de' => 'Workflow on Before Submit; test in Sandbox.', 'en' => 'Workflow on before submit; test in sandbox.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'ns-records-catalog-meta',
                    'kind' => ['de' => 'Records Catalog', 'en' => 'Records catalog'],
                    'where' => ['de' => 'Customization → Records Catalog', 'en' => 'Customization → Records Catalog'],
                    'how' => ['de' => 'UI browse; SuiteAnalytics Connect schema optional.', 'en' => 'UI browse; SuiteAnalytics Connect schema optional.'],
                    'useFor' => ['de' => 'Record/Field-Inventar, Custom Field PII-Scan.', 'en' => 'Record/field inventory, custom field PII scan.'],
                    'watchouts' => ['de' => 'Custom Records pro Account unterschiedlich — Sandbox ≠ Prod.', 'en' => 'Custom records differ per account — sandbox ≠ prod.'],
                ],
                [
                    'id' => 'ns-suiteql-meta',
                    'kind' => ['de' => 'SuiteQL schema', 'en' => 'SuiteQL schema'],
                    'where' => ['de' => 'SuiteAnalytics → SuiteQL Query Tool / Connect Browser', 'en' => 'SuiteAnalytics → SuiteQL Query Tool / Connect Browser'],
                    'how' => ['de' => 'Schema Browser; INFORMATION_SCHEMA queries.', 'en' => 'Schema browser; INFORMATION_SCHEMA queries.'],
                    'useFor' => ['de' => 'Extract-Design, Join-Keys, DQ-SQL.', 'en' => 'Extract design, join keys, DQ SQL.'],
                    'watchouts' => ['de' => 'Role permissions filtern sichtbare Records.', 'en' => 'Role permissions filter visible records.'],
                ],
                [
                    'id' => 'ns-custom-fields',
                    'kind' => ['de' => 'Custom Fields / Records', 'en' => 'Custom fields / records'],
                    'where' => ['de' => 'Customization → Lists → Fields; Custom Record Types', 'en' => 'Customization → Lists → Fields; custom record types'],
                    'how' => ['de' => 'Field IDs (custentity_/custbody_) dokumentieren.', 'en' => 'Document field IDs (custentity_/custbody_).'],
                    'useFor' => ['de' => 'PII-Inventar, Load-Allowlist.', 'en' => 'PII inventory, load allowlist.'],
                    'watchouts' => ['de' => 'Formula fields abgeleitet — in Curated neu berechnen.', 'en' => 'Formula fields derived — recompute in Curated.'],
                ],
                [
                    'id' => 'ns-saved-searches',
                    'kind' => ['de' => 'Saved Searches', 'en' => 'Saved searches'],
                    'where' => ['de' => 'Lists → Search → Saved Searches', 'en' => 'Lists → Search → Saved Searches'],
                    'how' => ['de' => 'Search definition exportieren; SuiteQL-Äquivalent bauen.', 'en' => 'Export search definition; build SuiteQL equivalent.'],
                    'useFor' => ['de' => 'Business-Logik verstehen — nicht blind als Mart-Load.', 'en' => 'Understand business logic — do not blindly use as mart load.'],
                    'watchouts' => ['de' => 'Saved Search ≠ stabiler Extract — Versionierung fehlt.', 'en' => 'Saved search ≠ stable extract — no versioning.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'workday' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'wd-worker-no-hire-date',
                    'priority' => 'high',
                    'title' => ['de' => 'Worker ohne Hire Date', 'en' => 'Worker without hire date'],
                    'problem' => ['de' => 'Worker ohne hireDate brechen Tenure, Cohort und Headcount-Trends.', 'en' => 'Workers without hireDate break tenure, cohort and headcount trends.'],
                    'prevent' => ['de' => 'Hire Date Pflicht im Onboarding; Integration validiert.', 'en' => 'Hire date required in onboarding; integration validates.'],
                    'staffNeedToKnow' => ['de' => 'HR: Hire Date bei Anlage Pflicht — nicht nachträglich „schätzen“.', 'en' => 'HR: Hire date required on create — do not guess later.'],
                    'checks' => ['de' => 'hireDate IS NULL on active Worker', 'en' => 'hireDate IS NULL on active Worker'],
                    'fixInSource' => ['de' => 'Required field in business process; EIB validation.', 'en' => 'Required field in business process; EIB validation.'],
                    'fixInWarehouse' => ['de' => 'Exclude from tenure metrics or flag.', 'en' => 'Exclude from tenure metrics or flag.'],
                ],
                [
                    'id' => 'wd-active-no-cost-center',
                    'priority' => 'high',
                    'title' => ['de' => 'Aktiver Worker ohne Cost Center', 'en' => 'Active worker without cost center'],
                    'problem' => ['de' => 'Fehlende costCenter brechen Finance-Allokation und Headcount-by-CC.', 'en' => 'Missing costCenter breaks finance allocation and headcount-by-CC.'],
                    'prevent' => ['de' => 'Cost Center Assignment im Hire/Move BP Pflicht.', 'en' => 'Cost center assignment required in hire/move BP.'],
                    'staffNeedToKnow' => ['de' => 'HR/Finance: Jede aktive Position braucht Cost Center.', 'en' => 'HR/finance: Every active position needs cost center.'],
                    'checks' => ['de' => 'costCenter IS NULL on active Worker/Position', 'en' => 'costCenter IS NULL on active Worker/Position'],
                    'fixInSource' => ['de' => 'BP validation; integration feed.', 'en' => 'BP validation; integration feed.'],
                    'fixInWarehouse' => ['de' => 'Unknown CC bucket; separate KPI.', 'en' => 'Unknown CC bucket; separate KPI.'],
                ],
                [
                    'id' => 'wd-position-no-org',
                    'priority' => 'medium',
                    'title' => ['de' => 'Position ohne Org-Zuordnung', 'en' => 'Position without org assignment'],
                    'problem' => ['de' => 'Position ohne Supervisory Org verhindert Org-Hierarchie-Reports.', 'en' => 'Position without supervisory org prevents org hierarchy reports.'],
                    'prevent' => ['de' => 'Supervisory Organization required on Position.', 'en' => 'Supervisory organization required on position.'],
                    'staffNeedToKnow' => ['de' => 'HR: Position immer einer Org zuordnen.', 'en' => 'HR: Always assign position to an org.'],
                    'checks' => ['de' => 'supervisoryOrganization IS NULL on open Position', 'en' => 'supervisoryOrganization IS NULL on open Position'],
                    'fixInSource' => ['de' => 'Required on position create; org design review.', 'en' => 'Required on position create; org design review.'],
                    'fixInWarehouse' => ['de' => 'Orphan position flag.', 'en' => 'Orphan position flag.'],
                ],
                [
                    'id' => 'wd-termination-before-hire',
                    'priority' => 'high',
                    'title' => ['de' => 'Termination vor Hire Date', 'en' => 'Termination before hire date'],
                    'problem' => ['de' => 'terminationDate < hireDate macht Headcount- und Turnover-KPIs unglaubwürdig.', 'en' => 'terminationDate < hireDate makes headcount and turnover KPIs untrustworthy.'],
                    'prevent' => ['de' => 'BP Validation auf Datumsreihenfolge.', 'en' => 'BP validation on date ordering.'],
                    'staffNeedToKnow' => ['de' => 'HR: Termination Date nie vor Hire Date setzen.', 'en' => 'HR: Never set termination date before hire date.'],
                    'checks' => ['de' => 'terminationDate < hireDate', 'en' => 'terminationDate < hireDate'],
                    'fixInSource' => ['de' => 'Business process validation rule.', 'en' => 'Business process validation rule.'],
                    'fixInWarehouse' => ['de' => 'Quarantine row; null turnover metrics.', 'en' => 'Quarantine row; null turnover metrics.'],
                ],
                [
                    'id' => 'wd-duplicate-worker-email',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Worker-Email', 'en' => 'Duplicate worker email'],
                    'problem' => ['de' => 'Mehrere Worker mit gleicher Email verzerren Headcount und MDM.', 'en' => 'Multiple workers with same email distort headcount and MDM.'],
                    'prevent' => ['de' => 'Unique Email Policy; IdP als Source of Truth.', 'en' => 'Unique email policy; IdP as source of truth.'],
                    'staffNeedToKnow' => ['de' => 'HR/IAM: Eine Firmen-Email pro Worker.', 'en' => 'HR/IAM: One company email per worker.'],
                    'checks' => ['de' => 'COUNT(DISTINCT workerId) GROUP BY email HAVING COUNT > 1', 'en' => 'COUNT(DISTINCT workerId) GROUP BY email HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Duplicate detection; merge/rehire process.', 'en' => 'Duplicate detection; merge/rehire process.'],
                    'fixInWarehouse' => ['de' => 'Golden worker id; merge map.', 'en' => 'Golden worker id; merge map.'],
                ],
                [
                    'id' => 'wd-raas-column-drift',
                    'priority' => 'low',
                    'title' => ['de' => 'RaaS Spalten-Drift', 'en' => 'RaaS column drift'],
                    'problem' => ['de' => 'Geänderte RaaS-Reports brechen Downstream-Schema und DQ.', 'en' => 'Changed RaaS reports break downstream schema and DQ.'],
                    'prevent' => ['de' => 'Report Change Management; Versionierte Extract-Definition.', 'en' => 'Report change management; versioned extract definition.'],
                    'staffNeedToKnow' => ['de' => 'Report Owner: Spaltenänderungen mit Data Team abstimmen.', 'en' => 'Report owner: Align column changes with data team.'],
                    'checks' => ['de' => 'Schema diff vs. expected RaaS column list', 'en' => 'Schema diff vs expected RaaS column list'],
                    'fixInSource' => ['de' => 'Change ticket for RaaS; regression test.', 'en' => 'Change ticket for RaaS; regression test.'],
                    'fixInWarehouse' => ['de' => 'Schema evolution table; alert on drift.', 'en' => 'Schema evolution table; alert on drift.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'wd-worker-dup',
                    'entity' => 'Worker',
                    'title' => ['de' => 'Worker-Duplikate / Rehire', 'en' => 'Worker duplicates / rehire'],
                    'matchKeys' => ['workerId', 'employeeId', 'email', 'nationalId (hashed)'],
                    'preventInSource' => ['de' => 'Rehire process; duplicate check on hire.', 'en' => 'Rehire process; duplicate check on hire.'],
                    'resolveInWarehouse' => ['de' => 'Golden worker id; rehire chain map.', 'en' => 'Golden worker id; rehire chain map.'],
                    'survivorship' => ['de' => 'Aktueller Employment-Record gewinnt.', 'en' => 'Current employment record wins.'],
                ],
                [
                    'id' => 'wd-position-org',
                    'entity' => 'Position',
                    'title' => ['de' => 'Position vs Org Hierarchy', 'en' => 'Position vs org hierarchy'],
                    'matchKeys' => ['positionId', 'supervisoryOrganization', 'jobProfile'],
                    'preventInSource' => ['de' => 'Org design governance; position management BP.', 'en' => 'Org design governance; position management BP.'],
                    'resolveInWarehouse' => ['de' => 'SCD2 org hierarchy; resolve orphans.', 'en' => 'SCD2 org hierarchy; resolve orphans.'],
                    'survivorship' => ['de' => 'Aktuelle Supervisory Org aus Workday gewinnt.', 'en' => 'Current supervisory org from Workday wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'wd-bo-docs',
                    'area' => ['de' => 'Workday Business Object Documentation', 'en' => 'Workday business object documentation'],
                    'setting' => ['de' => 'Worker/Position/Org BO-Felder für Extract-Allowlist', 'en' => 'Worker/position/org BO fields for extract allowlist'],
                    'why' => ['de' => 'Semantische Extracts statt RaaS-Sprawl.', 'en' => 'Semantic extracts vs RaaS sprawl.'],
                    'how' => ['de' => 'Community → Business Object docs; Integration IDs notieren.', 'en' => 'Community → business object docs; note integration IDs.'],
                ],
                [
                    'id' => 'wd-raas-governance',
                    'area' => ['de' => 'Custom Reports (RaaS)', 'en' => 'Custom reports (RaaS)'],
                    'setting' => ['de' => 'Versionierte RaaS-Reports als Extract-Contract', 'en' => 'Versioned RaaS reports as extract contract'],
                    'why' => ['de' => 'Verhindert Spalten-Drift und versteckte PII.', 'en' => 'Prevents column drift and hidden PII.'],
                    'how' => ['de' => 'Report Owner + Change Ticket; Spalten-Allowlist.', 'en' => 'Report owner + change ticket; column allowlist.'],
                ],
                [
                    'id' => 'wd-isu-scopes',
                    'area' => ['de' => 'Integration System User (ISU)', 'en' => 'Integration system user (ISU)'],
                    'setting' => ['de' => 'ISU Domain Security minimal halten', 'en' => 'Keep ISU domain security minimal'],
                    'why' => ['de' => 'Breiter ISU-Zugriff ≠ Warehouse-Policy.', 'en' => 'Broad ISU access ≠ warehouse policy.'],
                    'how' => ['de' => 'Security Groups nur für benötigte BOs; regelmäßig reviewen.', 'en' => 'Security groups only for needed BOs; review regularly.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'wd-bo-docs-meta',
                    'kind' => ['de' => 'Business Object docs', 'en' => 'Business object docs'],
                    'where' => ['de' => 'Workday Community → Documentation → Business Objects', 'en' => 'Workday Community → Documentation → Business Objects'],
                    'how' => ['de' => 'BO-Referenz lesen; Integration IDs für API/RaaS.', 'en' => 'Read BO reference; integration IDs for API/RaaS.'],
                    'useFor' => ['de' => 'Extract-Grain, Join-Keys, Feld-Semantik.', 'en' => 'Extract grain, join keys, field semantics.'],
                    'watchouts' => ['de' => 'Tenant-spezifische Custom Objects ergänzen Standard-BOs.', 'en' => 'Tenant-specific custom objects extend standard BOs.'],
                ],
                [
                    'id' => 'wd-raas-meta',
                    'kind' => ['de' => 'RaaS (Report-as-a-Service)', 'en' => 'RaaS (Report-as-a-Service)'],
                    'where' => ['de' => 'Workday → Custom Reports → Advanced → Web Service', 'en' => 'Workday → Custom Reports → Advanced → Web Service'],
                    'how' => ['de' => 'Report Definition exportieren; WSDL/REST Endpoint testen.', 'en' => 'Export report definition; test WSDL/REST endpoint.'],
                    'useFor' => ['de' => 'Batch-Extracts — Spalten-Allowlist vor Prod.', 'en' => 'Batch extracts — column allowlist before prod.'],
                    'watchouts' => ['de' => 'Report-Änderungen ohne Versionierung brechen Pipeline.', 'en' => 'Report changes without versioning break pipeline.'],
                ],
                [
                    'id' => 'wd-isu-meta',
                    'kind' => ['de' => 'Integration System / ISU', 'en' => 'Integration system / ISU'],
                    'where' => ['de' => 'Workday → Integrations → Integration Systems', 'en' => 'Workday → Integrations → Integration Systems'],
                    'how' => ['de' => 'ISU Security Groups und Domain Policies dokumentieren.', 'en' => 'Document ISU security groups and domain policies.'],
                    'useFor' => ['de' => 'Welche Felder der Extract-User wirklich sieht.', 'en' => 'Which fields the extract user actually sees.'],
                    'watchouts' => ['de' => 'ISU sieht mehr als UI-Rollen — Allowlist trotzdem.', 'en' => 'ISU sees more than UI roles — allowlist anyway.'],
                ],
                [
                    'id' => 'wd-custom-fields-meta',
                    'kind' => ['de' => 'Custom Fields / Calculated Fields', 'en' => 'Custom fields / calculated fields'],
                    'where' => ['de' => 'Workday → Configure → Custom Fields', 'en' => 'Workday → Configure → Custom Fields'],
                    'how' => ['de' => 'Custom Field IDs und BO-Zuordnung inventarisieren.', 'en' => 'Inventory custom field IDs and BO mapping.'],
                    'useFor' => ['de' => 'PII-Scan, Extract-Erweiterungen.', 'en' => 'PII scan, extract extensions.'],
                    'watchouts' => ['de' => 'Calculated Fields abgeleitet — nicht blind syncen.', 'en' => 'Calculated fields derived — do not sync blindly.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'successfactors' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'sf-empjob-no-dept',
                    'priority' => 'high',
                    'title' => ['de' => 'EmpJob ohne Department', 'en' => 'EmpJob without department'],
                    'problem' => ['de' => 'EmpJob ohne department brechen Org- und Headcount-Reports.', 'en' => 'EmpJob without department breaks org and headcount reports.'],
                    'prevent' => ['de' => 'Department required on Job Info; EC workflow validation.', 'en' => 'Department required on job info; EC workflow validation.'],
                    'staffNeedToKnow' => ['de' => 'HR: Job Info immer mit Department pflegen.', 'en' => 'HR: Always maintain department on job info.'],
                    'checks' => ['de' => 'department IS NULL on active EmpJob', 'en' => 'department IS NULL on active EmpJob'],
                    'fixInSource' => ['de' => 'Required field in job info portlet; workflow.', 'en' => 'Required field in job info portlet; workflow.'],
                    'fixInWarehouse' => ['de' => 'Unknown department dim.', 'en' => 'Unknown department dim.'],
                ],
                [
                    'id' => 'sf-employment-no-person',
                    'priority' => 'high',
                    'title' => ['de' => 'EmpEmployment ohne personIdExternal', 'en' => 'EmpEmployment without personIdExternal'],
                    'problem' => ['de' => 'Employment ohne Person-Join verhindert konsistente Headcount-Grain.', 'en' => 'Employment without person join prevents consistent headcount grain.'],
                    'prevent' => ['de' => 'personIdExternal Pflicht bei Hire; Integration validiert.', 'en' => 'personIdExternal required on hire; integration validates.'],
                    'staffNeedToKnow' => ['de' => 'HR: Jede Employment braucht gültige Person.', 'en' => 'HR: Every employment needs valid person.'],
                    'checks' => ['de' => 'personIdExternal IS NULL on EmpEmployment', 'en' => 'personIdExternal IS NULL on EmpEmployment'],
                    'fixInSource' => ['de' => 'Hire workflow; required person link.', 'en' => 'Hire workflow; required person link.'],
                    'fixInWarehouse' => ['de' => 'Orphan employment flag; exclude from HC.', 'en' => 'Orphan employment flag; exclude from HC.'],
                ],
                [
                    'id' => 'sf-start-after-end',
                    'priority' => 'high',
                    'title' => ['de' => 'startDate nach endDate', 'en' => 'startDate after endDate'],
                    'problem' => ['de' => 'EmpEmployment startDate > endDate macht Tenure und Turnover falsch.', 'en' => 'EmpEmployment startDate > endDate makes tenure and turnover wrong.'],
                    'prevent' => ['de' => 'EC Validation auf Datumslogik.', 'en' => 'EC validation on date logic.'],
                    'staffNeedToKnow' => ['de' => 'HR: End Date nie vor Start Date.', 'en' => 'HR: End date never before start date.'],
                    'checks' => ['de' => 'startDate > endDate on EmpEmployment WHERE endDate IS NOT NULL', 'en' => 'startDate > endDate on EmpEmployment WHERE endDate IS NOT NULL'],
                    'fixInSource' => ['de' => 'Workflow validation rule.', 'en' => 'Workflow validation rule.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; null tenure.', 'en' => 'Quarantine; null tenure.'],
                ],
                [
                    'id' => 'sf-manager-self-loop',
                    'priority' => 'medium',
                    'title' => ['de' => 'Manager = Self', 'en' => 'Manager = self'],
                    'problem' => ['de' => 'EmpJob mit managerId = userId bricht Org-Hierarchie.', 'en' => 'EmpJob with managerId = userId breaks org hierarchy.'],
                    'prevent' => ['de' => 'Validation: managerId ≠ userId.', 'en' => 'Validation: managerId ≠ userId.'],
                    'staffNeedToKnow' => ['de' => 'HR: Manager nicht auf sich selbst setzen.', 'en' => 'HR: Do not set manager to self.'],
                    'checks' => ['de' => 'managerId = userId on EmpJob', 'en' => 'managerId = userId on EmpJob'],
                    'fixInSource' => ['de' => 'Business rule on save.', 'en' => 'Business rule on save.'],
                    'fixInWarehouse' => ['de' => 'Null manager link; flag for review.', 'en' => 'Null manager link; flag for review.'],
                ],
                [
                    'id' => 'sf-nationalid-missing',
                    'priority' => 'medium',
                    'title' => ['de' => 'PerPerson ohne nationalId (wo Pflicht)', 'en' => 'PerPerson without nationalId (where required)'],
                    'problem' => ['de' => 'Fehlende nationalId in Pflicht-Ländern bricht Compliance-Reports.', 'en' => 'Missing nationalId in mandatory countries breaks compliance reports.'],
                    'prevent' => ['de' => 'Country-specific required fields in EC.', 'en' => 'Country-specific required fields in EC.'],
                    'staffNeedToKnow' => ['de' => 'HR: Länder-Pflichtfelder bei Hire prüfen.', 'en' => 'HR: Check country mandatory fields on hire.'],
                    'checks' => ['de' => 'nationalId IS NULL WHERE country IN (mandatory list)', 'en' => 'nationalId IS NULL WHERE country IN (mandatory list)'],
                    'fixInSource' => ['de' => 'Country-specific validation.', 'en' => 'Country-specific validation.'],
                    'fixInWarehouse' => ['de' => 'Compliance flag — nicht in Analytics-Klartext.', 'en' => 'Compliance flag — not in analytics cleartext.'],
                ],
                [
                    'id' => 'sf-picklist-stale',
                    'priority' => 'low',
                    'title' => ['de' => 'Stale Picklist / BC Codes', 'en' => 'Stale picklist / BC codes'],
                    'problem' => ['de' => 'Inaktive Picklist-Werte in EmpJob erzeugen falsche Org-Dimensionen.', 'en' => 'Inactive picklist values on EmpJob create wrong org dimensions.'],
                    'prevent' => ['de' => 'Picklist Center Governance; inactive values blocken.', 'en' => 'Picklist Center governance; block inactive values.'],
                    'staffNeedToKnow' => ['de' => 'HR Admin: Picklists vor Go-Live harmonisieren.', 'en' => 'HR admin: Harmonize picklists before go-live.'],
                    'checks' => ['de' => 'department/status code NOT IN active picklist', 'en' => 'department/status code NOT IN active picklist'],
                    'fixInSource' => ['de' => 'Picklist Center review; deactivate obsolete.', 'en' => 'Picklist Center review; deactivate obsolete.'],
                    'fixInWarehouse' => ['de' => 'Map to unknown; refresh dim from BC export.', 'en' => 'Map to unknown; refresh dim from BC export.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'sf-person-dup',
                    'entity' => 'PerPerson',
                    'title' => ['de' => 'Person-Duplikate', 'en' => 'Person duplicates'],
                    'matchKeys' => ['personIdExternal', 'nationalId (hashed)', 'emailAddress', 'userId'],
                    'preventInSource' => ['de' => 'Duplicate check on hire; person merge process.', 'en' => 'Duplicate check on hire; person merge process.'],
                    'resolveInWarehouse' => ['de' => 'Golden personIdExternal; merge map.', 'en' => 'Golden personIdExternal; merge map.'],
                    'survivorship' => ['de' => 'Aktive Employment gewinnt; external id schlägt internal.', 'en' => 'Active employment wins; external id beats internal.'],
                ],
                [
                    'id' => 'sf-user-person',
                    'entity' => 'User ↔ PerPerson',
                    'title' => ['de' => 'User vs Person Mismatch', 'en' => 'User vs person mismatch'],
                    'matchKeys' => ['userId', 'personIdExternal', 'emailAddress'],
                    'preventInSource' => ['de' => 'Single source hire; IdP sync.', 'en' => 'Single source hire; IdP sync.'],
                    'resolveInWarehouse' => ['de' => 'Resolve via email hash; flag orphans.', 'en' => 'Resolve via email hash; flag orphans.'],
                    'survivorship' => ['de' => 'PerPerson aus EC gewinnt über User-Stub.', 'en' => 'PerPerson from EC wins over user stub.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'sf-odata-metadata',
                    'area' => ['de' => 'OData API → $metadata', 'en' => 'OData API → $metadata'],
                    'setting' => ['de' => '$select-Allowlist pro Entity dokumentieren', 'en' => 'Document $select allowlist per entity'],
                    'why' => ['de' => 'Verhindert PII-Sprawl via $expand.', 'en' => 'Prevents PII sprawl via $expand.'],
                    'how' => ['de' => '$metadata XML speichern; Felder taggen.', 'en' => 'Store $metadata XML; tag fields.'],
                ],
                [
                    'id' => 'sf-mdf-governance',
                    'area' => ['de' => 'Admin Center → MDF Objects', 'en' => 'Admin Center → MDF objects'],
                    'setting' => ['de' => 'MDF-Objekte für Load freigeben oder blocken', 'en' => 'Allow or block MDF objects for load'],
                    'why' => ['de' => 'MDF kann versteckte PII und Schema-Drift liefern.', 'en' => 'MDF can deliver hidden PII and schema drift.'],
                    'how' => ['de' => 'MDF Inventory; Owner pro Object.', 'en' => 'MDF inventory; owner per object.'],
                ],
                [
                    'id' => 'sf-picklist-center',
                    'area' => ['de' => 'Admin Center → Picklist Center', 'en' => 'Admin Center → Picklist Center'],
                    'setting' => ['de' => 'Aktive Picklists für Dimension-Maps pflegen', 'en' => 'Maintain active picklists for dimension maps'],
                    'why' => ['de' => 'Stale Codes verfälschen Org-/Status-Dims.', 'en' => 'Stale codes distort org/status dims.'],
                    'how' => ['de' => 'Export active picklists; sync to warehouse dim.', 'en' => 'Export active picklists; sync to warehouse dim.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'sf-odata-meta',
                    'kind' => ['de' => 'OData $metadata', 'en' => 'OData $metadata'],
                    'where' => ['de' => 'API Center → OData API Data Dictionary / $metadata endpoint', 'en' => 'API Center → OData API Data Dictionary / $metadata endpoint'],
                    'how' => ['de' => '$metadata abrufen; Entity/Navigation Properties parsen.', 'en' => 'Fetch $metadata; parse entity/navigation properties.'],
                    'useFor' => ['de' => 'Extract-Design, $select-Allowlist, Join-Pfade.', 'en' => 'Extract design, $select allowlist, join paths.'],
                    'watchouts' => ['de' => '$expand zieht PII — minimal $select.', 'en' => '$expand pulls PII — minimal $select.'],
                ],
                [
                    'id' => 'sf-mdf-meta',
                    'kind' => ['de' => 'MDF (Metadata Framework)', 'en' => 'MDF (Metadata Framework)'],
                    'where' => ['de' => 'Admin Center → Manage Data → MDF Object Definitions', 'en' => 'Admin Center → Manage Data → MDF Object Definitions'],
                    'how' => ['de' => 'MDF Object/export via OData oder Integration Center.', 'en' => 'MDF object/export via OData or Integration Center.'],
                    'useFor' => ['de' => 'Custom Objects, PII-Inventar.', 'en' => 'Custom objects, PII inventory.'],
                    'watchouts' => ['de' => 'Effective dating auf MDF — Grain klären.', 'en' => 'Effective dating on MDF — clarify grain.'],
                ],
                [
                    'id' => 'sf-picklist-meta',
                    'kind' => ['de' => 'Picklist Center', 'en' => 'Picklist Center'],
                    'where' => ['de' => 'Admin Center → Picklist Center', 'en' => 'Admin Center → Picklist Center'],
                    'how' => ['de' => 'Export active/inactive picklist values.', 'en' => 'Export active/inactive picklist values.'],
                    'useFor' => ['de' => 'Dimension-Maps für department, status, event reason.', 'en' => 'Dimension maps for department, status, event reason.'],
                    'watchouts' => ['de' => 'Legacy codes in historischen Rows bleiben — SCD2.', 'en' => 'Legacy codes remain in historical rows — SCD2.'],
                ],
                [
                    'id' => 'sf-bc-meta',
                    'kind' => ['de' => 'Business Configuration (BC)', 'en' => 'Business Configuration (BC)'],
                    'where' => ['de' => 'Admin Center → Manage Business Configuration', 'en' => 'Admin Center → Manage Business Configuration'],
                    'how' => ['de' => 'BC Export / OData where available.', 'en' => 'BC export / OData where available.'],
                    'useFor' => ['de' => 'Org units, pay components, event reasons.', 'en' => 'Org units, pay components, event reasons.'],
                    'watchouts' => ['de' => 'BC-Änderungen brauchen Dim-Refresh in Curated.', 'en' => 'BC changes need dim refresh in Curated.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],
];
