<?php

/**
 * Wave 7 quality overlays — Markets & Insurance source-native DQ, MDM, metadata guides.
 *
 * @return array<string, array<string, mixed>>
 */

return [
    'murex' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'murex-trade-no-book',
                    'priority' => 'high',
                    'title' => ['de' => 'Trade ohne Book', 'en' => 'Trade without book'],
                    'problem' => ['de' => 'Trades ohne bookId brechen Position- und P&L-Rollups je Desk.', 'en' => 'Trades without bookId break position and P&L rollups per desk.'],
                    'prevent' => ['de' => 'Front-Office Capture: Book Pflichtfeld vor Deal-Validation.', 'en' => 'Front-office capture: book required field before deal validation.'],
                    'staffNeedToKnow' => ['de' => 'Middle Office: Trade ohne Book vor EOD reparieren.', 'en' => 'Middle office: fix trades without a book before EOD.'],
                    'checks' => ['de' => 'trade.book_id IS NULL', 'en' => 'trade.book_id IS NULL'],
                    'fixInSource' => ['de' => 'Book in Murex nachtragen; Amend statt neuer Trade.', 'en' => 'Backfill book in Murex; amend instead of a new trade.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown-Book-Bucket bis Korrektur.', 'en' => 'Quarantine; unknown-book bucket until corrected.'],
                ],
                [
                    'id' => 'murex-position-no-instrument',
                    'priority' => 'high',
                    'title' => ['de' => 'Position ohne Instrument', 'en' => 'Position without instrument'],
                    'problem' => ['de' => 'Positionen ohne instrumentId verzerren Exposure- und MTM-Reports.', 'en' => 'Positions without instrumentId distort exposure and MTM reports.'],
                    'prevent' => ['de' => 'Static-Data-Sync vor Position-Keeping-Batch.', 'en' => 'Sync static data before the position-keeping batch.'],
                    'staffNeedToKnow' => ['de' => 'Static Data Team: Neue Instrumente vor Handelsstart anlegen.', 'en' => 'Static data team: create new instruments before trading starts.'],
                    'checks' => ['de' => 'position.instrument_id IS NULL OR instrument_id NOT IN dim_instrument', 'en' => 'position.instrument_id IS NULL OR instrument_id NOT IN dim_instrument'],
                    'fixInSource' => ['de' => 'Instrument static data nachpflegen; Position neu berechnen.', 'en' => 'Backfill instrument static data; recompute position.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown-Instrument-Dim.', 'en' => 'Quarantine; unknown-instrument dim.'],
                ],
                [
                    'id' => 'murex-cashflow-no-trade',
                    'priority' => 'medium',
                    'title' => ['de' => 'Cash Flow ohne Trade', 'en' => 'Cash flow without trade'],
                    'problem' => ['de' => 'Orphan Cash Flows verzerren Settlement- und Liquiditäts-Reports.', 'en' => 'Orphan cash flows distort settlement and liquidity reports.'],
                    'prevent' => ['de' => 'Cash-Flow-Generierung an Trade-Lifecycle koppeln.', 'en' => 'Couple cash flow generation to the trade lifecycle.'],
                    'staffNeedToKnow' => ['de' => 'Ops: Orphan Flows vor Settlement-Run bereinigen.', 'en' => 'Ops: clean up orphan flows before the settlement run.'],
                    'checks' => ['de' => 'cash_flow.trade_id IS NULL OR trade_id NOT IN dim_trade', 'en' => 'cash_flow.trade_id IS NULL OR trade_id NOT IN dim_trade'],
                    'fixInSource' => ['de' => 'Re-generate cash flows from trade lifecycle events.', 'en' => 'Re-generate cash flows from trade lifecycle events.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from settlement KPIs.', 'en' => 'Quarantine; exclude from settlement KPIs.'],
                ],
                [
                    'id' => 'murex-confirmation-mismatch-aging',
                    'priority' => 'high',
                    'title' => ['de' => 'Unmatched Confirmation über Aging-Schwelle', 'en' => 'Unmatched confirmation past aging threshold'],
                    'problem' => ['de' => 'Lange unmatched Confirmations sind ein Settlement-Fail-Frühindikator.', 'en' => 'Long-unmatched confirmations are a settlement-fail early indicator.'],
                    'prevent' => ['de' => 'Daily Matching-Run; Eskalation nach T+1.', 'en' => 'Daily matching run; escalate after T+1.'],
                    'staffNeedToKnow' => ['de' => 'Ops: Unmatched > 1 Tag sofort eskalieren.', 'en' => 'Ops: escalate unmatched > 1 day immediately.'],
                    'checks' => ['de' => "match_status <> 'matched' AND confirmed_at < CURRENT_DATE - 1", 'en' => "match_status <> 'matched' AND confirmed_at < CURRENT_DATE - 1"],
                    'fixInSource' => ['de' => 'Re-send/re-match confirmation with counterparty.', 'en' => 'Re-send/re-match confirmation with counterparty.'],
                    'fixInWarehouse' => ['de' => 'Flag settlement_risk; separate aging-bucket KPI.', 'en' => 'Flag settlement_risk; separate aging-bucket KPI.'],
                ],
                [
                    'id' => 'murex-counterparty-no-lei',
                    'priority' => 'medium',
                    'title' => ['de' => 'Counterparty ohne LEI', 'en' => 'Counterparty without LEI'],
                    'problem' => ['de' => 'Fehlende LEI blockiert regulatorisches Reporting (EMIR/MiFIR).', 'en' => 'Missing LEI blocks regulatory reporting (EMIR/MiFIR).'],
                    'prevent' => ['de' => 'LEI Pflichtfeld bei Counterparty-Onboarding.', 'en' => 'LEI required field at counterparty onboarding.'],
                    'staffNeedToKnow' => ['de' => 'Static Data: Kein Live-Trading ohne gültige LEI.', 'en' => 'Static data: no live trading without a valid LEI.'],
                    'checks' => ['de' => 'counterparty.lei IS NULL AND counterparty_type IN (\'Bank\', \'Corporate\')', 'en' => 'counterparty.lei IS NULL AND counterparty_type IN (\'Bank\', \'Corporate\')'],
                    'fixInSource' => ['de' => 'LEI von GLEIF nachtragen.', 'en' => 'Backfill LEI from GLEIF.'],
                    'fixInWarehouse' => ['de' => 'Flag missing_lei; exclude from regulatory reporting extract.', 'en' => 'Flag missing_lei; exclude from regulatory reporting extract.'],
                ],
                [
                    'id' => 'murex-duplicate-deal-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte dealId im Extract', 'en' => 'Duplicate dealId in extract'],
                    'problem' => ['de' => 'Doppelte dealId verzerren Notional- und Trade-Count-KPIs.', 'en' => 'Duplicate dealId distort notional and trade-count KPIs.'],
                    'prevent' => ['de' => 'Idempotent load; Amendment-Versionen korrekt taggen.', 'en' => 'Idempotent load; correctly tag amendment versions.'],
                    'staffNeedToKnow' => ['de' => 'Data: Natural Key = dealId + version.', 'en' => 'Data: Natural key = dealId + version.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY deal_id HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY deal_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate Datamart batch overlap.', 'en' => 'Re-extract; investigate Datamart batch overlap.'],
                    'fixInWarehouse' => ['de' => 'Dedup by deal_id + latest version; keep _loaded_at.', 'en' => 'Dedup by deal_id + latest version; keep _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'murex-counterparty-dup',
                    'entity' => 'Counterparty',
                    'title' => ['de' => 'Counterparty-Duplikate / Legal-Entity-Merger', 'en' => 'Counterparty duplicates / legal entity merger'],
                    'matchKeys' => ['counterpartyId', 'lei', 'name'],
                    'preventInSource' => ['de' => 'LEI as golden identifier; merger events via static data governance.', 'en' => 'LEI as golden identifier; merger events via static data governance.'],
                    'resolveInWarehouse' => ['de' => 'Golden counterpartyId; LEI-basierte Merge-Map.', 'en' => 'Golden counterpartyId; LEI-based merge map.'],
                    'survivorship' => ['de' => 'Aktive Legal Entity mit aktuellster LEI-Registrierung gewinnt.', 'en' => 'Active legal entity with the most current LEI registration wins.'],
                ],
                [
                    'id' => 'murex-instrument-isin-map',
                    'entity' => 'Instrument',
                    'title' => ['de' => 'Instrument / ISIN Mapping Drift', 'en' => 'Instrument / ISIN mapping drift'],
                    'matchKeys' => ['instrumentId', 'isin', 'instrumentType'],
                    'preventInSource' => ['de' => 'Static-Data-Governance; ISIN-Änderungen dokumentieren.', 'en' => 'Static data governance; document ISIN changes.'],
                    'resolveInWarehouse' => ['de' => 'Canonical instrumentId → ISIN SCD2-Mapping.', 'en' => 'Canonical instrumentId → ISIN SCD2 mapping.'],
                    'survivorship' => ['de' => 'Aktueller Static-Data-Stand gewinnt über Legacy-ISIN.', 'en' => 'Current static data state wins over legacy ISIN.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'murex-datamart-extract-config',
                    'area' => ['de' => 'Murex Datamart → Extract configuration', 'en' => 'Murex Datamart → Extract configuration'],
                    'setting' => ['de' => 'MxML-Extract-Scope auf Trade/Position/Risk begrenzen; Freitext-Felder ausschließen', 'en' => 'Limit MxML extract scope to trade/position/risk; exclude free-text fields'],
                    'why' => ['de' => 'Vermeidet unnötige Broker-Notes/Ticket-Freitext im Extract.', 'en' => 'Avoids unnecessary broker notes/ticket free text in the extract.'],
                    'how' => ['de' => 'Extract-Templates pflegen; Field Allowlist reviewen.', 'en' => 'Maintain extract templates; review field allowlist.'],
                ],
                [
                    'id' => 'murex-position-keeping-config',
                    'area' => ['de' => 'Front Office → Position Keeping', 'en' => 'Front office → Position keeping'],
                    'setting' => ['de' => 'Book-Pflichtfeld und Instrument-Static-Data-Sync vor EOD', 'en' => 'Book required field and instrument static-data sync before EOD'],
                    'why' => ['de' => 'Verhindert Trade-ohne-Book und Position-ohne-Instrument DQ-Failures.', 'en' => 'Prevents trade-without-book and position-without-instrument DQ failures.'],
                    'how' => ['de' => 'Validation Rules in Murex; Static Data Batch vor Position Run.', 'en' => 'Validation rules in Murex; static data batch before the position run.'],
                ],
                [
                    'id' => 'murex-static-data-governance',
                    'area' => ['de' => 'Static Data → Counterparty / LEI', 'en' => 'Static data → Counterparty / LEI'],
                    'setting' => ['de' => 'LEI Pflichtfeld für Bank/Corporate Counterparties', 'en' => 'LEI required field for bank/corporate counterparties'],
                    'why' => ['de' => 'Regulatorisches Reporting (EMIR/MiFIR) bleibt lückenlos.', 'en' => 'Regulatory reporting (EMIR/MiFIR) stays complete.'],
                    'how' => ['de' => 'Onboarding-Checklist; periodische GLEIF-Validierung.', 'en' => 'Onboarding checklist; periodic GLEIF validation.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'murex-datamart-schema',
                    'kind' => ['de' => 'Murex Datamart schema', 'en' => 'Murex Datamart schema'],
                    'where' => ['de' => 'Murex MxML Datamart Guide; Datamart table catalog', 'en' => 'Murex MxML Datamart guide; Datamart table catalog'],
                    'how' => ['de' => 'Trade/Position/Risk-Tabellen inventarisieren; Freitext-Felder markieren.', 'en' => 'Inventory trade/position/risk tables; flag free-text fields.'],
                    'useFor' => ['de' => 'Extract design, PII/Sensitive tags, Join-Keys.', 'en' => 'Extract design, PII/sensitive tags, join keys.'],
                    'watchouts' => ['de' => 'Ticket-Freitext-Felder — nie in Select-Allowlist aufnehmen.', 'en' => 'Ticket free-text fields — never include in the select allowlist.'],
                ],
                [
                    'id' => 'murex-mxml-message-catalog',
                    'kind' => ['de' => 'MxML message catalog', 'en' => 'MxML message catalog'],
                    'where' => ['de' => 'Murex MxML API Reference; confirmation/settlement message types', 'en' => 'Murex MxML API reference; confirmation/settlement message types'],
                    'how' => ['de' => 'Message-Typen und Status-Codes dokumentieren.', 'en' => 'Document message types and status codes.'],
                    'useFor' => ['de' => 'Confirmation-Status-Facts, Match-Rate-KPIs.', 'en' => 'Confirmation status facts, match-rate KPIs.'],
                    'watchouts' => ['de' => 'Keine vollständigen SWIFT/FpML-Payloads selektieren.', 'en' => 'Do not select full SWIFT/FpML payloads.'],
                ],
                [
                    'id' => 'murex-static-data-catalog',
                    'kind' => ['de' => 'Static data catalog', 'en' => 'Static data catalog'],
                    'where' => ['de' => 'Murex Front Office setup → Static Data (Counterparty, Instrument, Book)', 'en' => 'Murex Front Office setup → static data (counterparty, instrument, book)'],
                    'how' => ['de' => 'Entity-Hierarchie und Attribute inventarisieren.', 'en' => 'Inventory entity hierarchy and attributes.'],
                    'useFor' => ['de' => 'Dimension design, MDM-Keys, Reference-Joins.', 'en' => 'Dimension design, MDM keys, reference joins.'],
                    'watchouts' => ['de' => 'Legal-Entity-Namen als PII-adjacent behandeln.', 'en' => 'Treat legal entity names as PII-adjacent.'],
                ],
                [
                    'id' => 'murex-risk-engine-config',
                    'kind' => ['de' => 'Risk engine configuration', 'en' => 'Risk engine configuration'],
                    'where' => ['de' => 'Murex Datamart → Risk Results (VaR, Greeks, P&L)', 'en' => 'Murex Datamart → risk results (VaR, Greeks, P&L)'],
                    'how' => ['de' => 'Risk-Result-Granularität (Book/Trade/Portfolio) dokumentieren.', 'en' => 'Document risk result granularity (book/trade/portfolio).'],
                    'useFor' => ['de' => 'P&L/VaR-Facts, Aggregations-Ebene für Reports.', 'en' => 'P&L/VaR facts, aggregation level for reports.'],
                    'watchouts' => ['de' => 'Diversification-Effekte bei Cross-Book-Aggregation beachten.', 'en' => 'Account for diversification effects when aggregating across books.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'fis' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'fis-transaction-no-account',
                    'priority' => 'high',
                    'title' => ['de' => 'Transaction ohne Account', 'en' => 'Transaction without account'],
                    'problem' => ['de' => 'Postings ohne accountId brechen Balance-Reconciliation und Volumen-KPIs.', 'en' => 'Postings without accountId break balance reconciliation and volume KPIs.'],
                    'prevent' => ['de' => 'Core-Banking Extract: accountId immer mitschreiben; closed accounts tracken.', 'en' => 'Core-banking extract: always persist accountId; track closed accounts.'],
                    'staffNeedToKnow' => ['de' => 'Data: Posting ohne Account ist Extract-Fehler.', 'en' => 'Data: A posting without an account is an extract error.'],
                    'checks' => ['de' => 'transaction.account_id IS NULL OR account_id NOT IN dim_account', 'en' => 'transaction.account_id IS NULL OR account_id NOT IN dim_account'],
                    'fixInSource' => ['de' => 'Re-extract with account context; repair closed-account tombstones.', 'en' => 'Re-extract with account context; repair closed-account tombstones.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown-Account-Dim.', 'en' => 'Quarantine; unknown-account dim.'],
                ],
                [
                    'id' => 'fis-payment-no-beneficiary',
                    'priority' => 'high',
                    'title' => ['de' => 'Payment ohne Beneficiary Account', 'en' => 'Payment without beneficiary account'],
                    'problem' => ['de' => 'Payments ohne Beneficiary brechen AML-Screening und Payment-Count-KPIs.', 'en' => 'Payments without a beneficiary break AML screening and payment-count KPIs.'],
                    'prevent' => ['de' => 'Payments-Hub Validation: Beneficiary Pflichtfeld vor Submission.', 'en' => 'Payments Hub validation: beneficiary required field before submission.'],
                    'staffNeedToKnow' => ['de' => 'Ops: Payment ohne Beneficiary sofort blockieren.', 'en' => 'Ops: block a payment without a beneficiary immediately.'],
                    'checks' => ['de' => 'payment.beneficiary_account IS NULL AND status <> \'rejected\'', 'en' => 'payment.beneficiary_account IS NULL AND status <> \'rejected\''],
                    'fixInSource' => ['de' => 'Reject/re-submit payment instruction.', 'en' => 'Reject/re-submit the payment instruction.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from payment KPIs.', 'en' => 'Quarantine; exclude from payment KPIs.'],
                ],
                [
                    'id' => 'fis-card-no-account',
                    'priority' => 'medium',
                    'title' => ['de' => 'Card ohne Account-Link', 'en' => 'Card without account link'],
                    'problem' => ['de' => 'Cards ohne accountId machen Card-Utilization-Reports unbrauchbar.', 'en' => 'Cards without accountId make card-utilization reports unusable.'],
                    'prevent' => ['de' => 'Card-Issuance Workflow: Account-Link Pflicht bei Aktivierung.', 'en' => 'Card issuance workflow: account link required at activation.'],
                    'staffNeedToKnow' => ['de' => 'Ops: Kein aktives Card ohne verknüpftes Account.', 'en' => 'Ops: No active card without a linked account.'],
                    'checks' => ['de' => 'card.account_id IS NULL AND card_status = \'active\'', 'en' => 'card.account_id IS NULL AND card_status = \'active\''],
                    'fixInSource' => ['de' => 'Link card to account; suspend if unresolved.', 'en' => 'Link card to account; suspend if unresolved.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from card KPIs.', 'en' => 'Quarantine; exclude from card KPIs.'],
                ],
                [
                    'id' => 'fis-gl-imbalance',
                    'priority' => 'high',
                    'title' => ['de' => 'GL Entry Imbalance', 'en' => 'GL entry imbalance'],
                    'problem' => ['de' => 'Debit/Credit-Ungleichgewicht in der GL bricht Financial-Reconciliation.', 'en' => 'Debit/credit imbalance in the GL breaks financial reconciliation.'],
                    'prevent' => ['de' => 'Double-Entry-Validation im Posting-Engine; Batch-Reconciliation je EOD.', 'en' => 'Double-entry validation in the posting engine; batch reconciliation each EOD.'],
                    'staffNeedToKnow' => ['de' => 'Finance: EOD-Imbalance vor Reporting-Freigabe klären.', 'en' => 'Finance: resolve EOD imbalance before reporting sign-off.'],
                    'checks' => ['de' => 'SUM(debit_amount) <> SUM(credit_amount) GROUP BY posting_date, gl_code', 'en' => 'SUM(debit_amount) <> SUM(credit_amount) GROUP BY posting_date, gl_code'],
                    'fixInSource' => ['de' => 'Investigate posting engine batch; re-run EOD close.', 'en' => 'Investigate posting engine batch; re-run EOD close.'],
                    'fixInWarehouse' => ['de' => 'Flag imbalance_date; exclude from finalized GL marts.', 'en' => 'Flag imbalance_date; exclude from finalized GL marts.'],
                ],
                [
                    'id' => 'fis-customer-duplicate-taxid',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte taxId im Customer-Extract', 'en' => 'Duplicate taxId in customer extract'],
                    'problem' => ['de' => 'Doppelte Tax-ID verzerrt Customer-Counts und Household-KPIs.', 'en' => 'Duplicate tax ID distorts customer counts and household KPIs.'],
                    'prevent' => ['de' => 'CIF unique-Constraint auf taxId; Household-Merge statt Duplicate.', 'en' => 'CIF unique constraint on taxId; household merge instead of duplicate.'],
                    'staffNeedToKnow' => ['de' => 'Ops: taxId ist der primäre Dedup-Key.', 'en' => 'Ops: taxId is the primary dedup key.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY tax_id HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY tax_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Merge in CIF; re-extract.', 'en' => 'Merge in CIF; re-extract.'],
                    'fixInWarehouse' => ['de' => 'Golden customer id; tax-id-hash merge map.', 'en' => 'Golden customer id; tax-id-hash merge map.'],
                ],
                [
                    'id' => 'fis-loan-no-account',
                    'priority' => 'medium',
                    'title' => ['de' => 'Loan ohne Account', 'en' => 'Loan without account'],
                    'problem' => ['de' => 'Loans ohne accountId brechen Portfolio-Balance-Reports.', 'en' => 'Loans without accountId break portfolio balance reports.'],
                    'prevent' => ['de' => 'Loan-Origination: Account immer vor Disbursement anlegen.', 'en' => 'Loan origination: always create the account before disbursement.'],
                    'staffNeedToKnow' => ['de' => 'Lending Ops: Kein Disbursement ohne Account.', 'en' => 'Lending ops: No disbursement without an account.'],
                    'checks' => ['de' => 'loan.account_id IS NULL', 'en' => 'loan.account_id IS NULL'],
                    'fixInSource' => ['de' => 'Create/link account; re-run origination step.', 'en' => 'Create/link account; re-run origination step.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from loan-balance KPIs.', 'en' => 'Quarantine; exclude from loan-balance KPIs.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'fis-customer-dup',
                    'entity' => 'Customer',
                    'title' => ['de' => 'Customer-Duplikate / Household Merge', 'en' => 'Customer duplicates / household merge'],
                    'matchKeys' => ['customerId', 'taxId', 'dateOfBirth', 'fullName'],
                    'preventInSource' => ['de' => 'CIF as source of truth; unique taxId constraint.', 'en' => 'CIF as source of truth; unique taxId constraint.'],
                    'resolveInWarehouse' => ['de' => 'Golden customerId; taxId-hash merge map.', 'en' => 'Golden customerId; taxId-hash merge map.'],
                    'survivorship' => ['de' => 'Aktivster Customer mit vollständigstem KYC-Status gewinnt.', 'en' => 'Most active customer with the most complete KYC status wins.'],
                ],
                [
                    'id' => 'fis-account-product-map',
                    'entity' => 'Account / Product',
                    'title' => ['de' => 'Account-Product Mapping Drift', 'en' => 'Account-product mapping drift'],
                    'matchKeys' => ['accountId', 'productId', 'productType'],
                    'preventInSource' => ['de' => 'Product-Catalog-Governance; Repricing-Events dokumentieren.', 'en' => 'Product catalog governance; document repricing events.'],
                    'resolveInWarehouse' => ['de' => 'Canonical productId → accountId SCD2-Mapping.', 'en' => 'Canonical productId → accountId SCD2 mapping.'],
                    'survivorship' => ['de' => 'Aktueller Product-Stand gewinnt über Legacy-Rate-Plan.', 'en' => 'Current product state wins over legacy rate plan.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'fis-cif-settings',
                    'area' => ['de' => 'FIS Profile → Party / CIF configuration', 'en' => 'FIS Profile → Party / CIF configuration'],
                    'setting' => ['de' => 'Customer Information File unique constraints und Merge-Workflow', 'en' => 'Customer information file unique constraints and merge workflow'],
                    'why' => ['de' => 'Verhindert Customer-Duplikate ohne kontrollierten Merge.', 'en' => 'Prevents customer duplicates without a controlled merge.'],
                    'how' => ['de' => 'Unique taxId enforcement; household merge review queue.', 'en' => 'Unique taxId enforcement; household merge review queue.'],
                ],
                [
                    'id' => 'fis-payments-hub-screening',
                    'area' => ['de' => 'FIS Payments Hub → Sanction screening', 'en' => 'FIS Payments Hub → Sanction screening'],
                    'setting' => ['de' => 'Screening-Pflicht vor Payment-Release; Beneficiary-Pflichtfeld', 'en' => 'Screening required before payment release; beneficiary required field'],
                    'why' => ['de' => 'AML-Compliance ohne unvollständige Payment-Instructions.', 'en' => 'AML compliance without incomplete payment instructions.'],
                    'how' => ['de' => 'Sanction-List-Config; Reject-Workflow für fehlende Beneficiary.', 'en' => 'Sanction list config; reject workflow for missing beneficiary.'],
                ],
                [
                    'id' => 'fis-gl-mapping',
                    'area' => ['de' => 'Core Banking → GL mapping / chart of accounts', 'en' => 'Core banking → GL mapping / chart of accounts'],
                    'setting' => ['de' => 'GL-Code-Mapping und Double-Entry-Validation je Produkt', 'en' => 'GL code mapping and double-entry validation per product'],
                    'why' => ['de' => 'Verhindert GL-Imbalance und fehlerhafte Financial-Reports.', 'en' => 'Prevents GL imbalance and incorrect financial reports.'],
                    'how' => ['de' => 'Chart-of-Accounts-Review; Batch-Reconciliation je EOD.', 'en' => 'Chart-of-accounts review; batch reconciliation each EOD.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'fis-profile-cif-schema',
                    'kind' => ['de' => 'FIS Profile CIF schema', 'en' => 'FIS Profile CIF schema'],
                    'where' => ['de' => 'FIS Profile → Party / Customer Information File data dictionary', 'en' => 'FIS Profile → Party / Customer Information File data dictionary'],
                    'how' => ['de' => 'Party-Felder inventarisieren; PII-Allowlist für Extract.', 'en' => 'Inventory party fields; PII allowlist for extract.'],
                    'useFor' => ['de' => 'Customer dim, MDM-Keys, KYC-Status-Facts.', 'en' => 'Customer dim, MDM keys, KYC-status facts.'],
                    'watchouts' => ['de' => 'Tax-ID/DOB — nicht in öffentlichen Marts.', 'en' => 'Tax ID/DOB — not in public marts.'],
                ],
                [
                    'id' => 'fis-payments-hub-catalog',
                    'kind' => ['de' => 'Payments Hub message catalog (ISO 20022)', 'en' => 'Payments Hub message catalog (ISO 20022)'],
                    'where' => ['de' => 'FIS Payments Hub → ISO 20022 message reference', 'en' => 'FIS Payments Hub → ISO 20022 message reference'],
                    'how' => ['de' => 'Message-Typen (pain/pacs) und Status-Codes dokumentieren.', 'en' => 'Document message types (pain/pacs) and status codes.'],
                    'useFor' => ['de' => 'Payment-Status-Facts, AML-Screening-Coverage.', 'en' => 'Payment status facts, AML screening coverage.'],
                    'watchouts' => ['de' => 'Beneficiary-Details in Messages sind PII.', 'en' => 'Beneficiary details in messages are PII.'],
                ],
                [
                    'id' => 'fis-core-banking-product-catalog',
                    'kind' => ['de' => 'Core banking product catalog', 'en' => 'Core banking product catalog'],
                    'where' => ['de' => 'FIS Core Banking → Product / rate plan configuration', 'en' => 'FIS Core Banking → Product / rate plan configuration'],
                    'how' => ['de' => 'Produkttypen, Zins-/Gebührenstruktur exportieren.', 'en' => 'Export product types, interest/fee structure.'],
                    'useFor' => ['de' => 'Product dim, Rate-Change DQ, Balance-KPIs.', 'en' => 'Product dim, rate-change DQ, balance KPIs.'],
                    'watchouts' => ['de' => 'Rate-Änderungen — SCD2 empfohlen.', 'en' => 'Rate changes — SCD2 recommended.'],
                ],
                [
                    'id' => 'fis-batch-eod-schedule',
                    'kind' => ['de' => 'Batch / EOD job schedule', 'en' => 'Batch / EOD job schedule'],
                    'where' => ['de' => 'Core Banking Operations → Batch scheduler / EOD run documentation', 'en' => 'Core banking operations → batch scheduler / EOD run documentation'],
                    'how' => ['de' => 'Batch-Reihenfolge und Abhängigkeiten dokumentieren.', 'en' => 'Document batch order and dependencies.'],
                    'useFor' => ['de' => 'Load-Scheduling, GL-Reconciliation-Timing.', 'en' => 'Load scheduling, GL reconciliation timing.'],
                    'watchouts' => ['de' => 'Extract vor abgeschlossenem EOD führt zu Zwischenständen.', 'en' => 'Extracting before EOD completes yields intermediate states.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'guidewire' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'gw-claim-no-policy',
                    'priority' => 'high',
                    'title' => ['de' => 'Claim ohne Policy', 'en' => 'Claim without policy'],
                    'problem' => ['de' => 'Claims ohne policyNumber brechen Loss-Ratio- und Coverage-Joins.', 'en' => 'Claims without policyNumber break loss-ratio and coverage joins.'],
                    'prevent' => ['de' => 'ClaimCenter Intake: Policy-Lookup Pflicht vor FNOL-Abschluss.', 'en' => 'ClaimCenter intake: policy lookup required before FNOL completion.'],
                    'staffNeedToKnow' => ['de' => 'Claims Ops: Kein Claim ohne verifizierte Policy.', 'en' => 'Claims ops: no claim without a verified policy.'],
                    'checks' => ['de' => 'claim.policy_number IS NULL OR policy_number NOT IN dim_policy', 'en' => 'claim.policy_number IS NULL OR policy_number NOT IN dim_policy'],
                    'fixInSource' => ['de' => 'Re-link claim to policy; verify PolicyCenter sync.', 'en' => 'Re-link claim to policy; verify PolicyCenter sync.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown-Policy-Dim.', 'en' => 'Quarantine; unknown-policy dim.'],
                ],
                [
                    'id' => 'gw-policy-no-account',
                    'priority' => 'high',
                    'title' => ['de' => 'Policy ohne Account', 'en' => 'Policy without account'],
                    'problem' => ['de' => 'Policies ohne accountNumber brechen Insured-Rollups und DSDR-Matching.', 'en' => 'Policies without accountNumber break insured rollups and DSDR matching.'],
                    'prevent' => ['de' => 'PolicyCenter Submission: Account Pflicht vor Bind.', 'en' => 'PolicyCenter submission: account required before bind.'],
                    'staffNeedToKnow' => ['de' => 'Underwriting: Kein Bind ohne Account-Link.', 'en' => 'Underwriting: no bind without an account link.'],
                    'checks' => ['de' => 'policy.account_number IS NULL', 'en' => 'policy.account_number IS NULL'],
                    'fixInSource' => ['de' => 'Link policy to account; re-issue if unresolved.', 'en' => 'Link policy to account; re-issue if unresolved.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from in-force KPIs.', 'en' => 'Quarantine; exclude from in-force KPIs.'],
                ],
                [
                    'id' => 'gw-reserve-negative',
                    'priority' => 'high',
                    'title' => ['de' => 'Negative Reserve ohne Recovery-Begründung', 'en' => 'Negative reserve without recovery reason'],
                    'problem' => ['de' => 'Negative Reserves ohne recovery/salvage-Code verzerren Incurred-Berechnungen.', 'en' => 'Negative reserves without a recovery/salvage code distort incurred calculations.'],
                    'prevent' => ['de' => 'ClaimCenter Financials: Recovery-Typ Pflicht bei negativer Transaction.', 'en' => 'ClaimCenter financials: recovery type required for negative transactions.'],
                    'staffNeedToKnow' => ['de' => 'Claims Finance: Negative Beträge immer mit Recovery-Code buchen.', 'en' => 'Claims finance: always post negative amounts with a recovery code.'],
                    'checks' => ['de' => "claim_transaction.amount < 0 AND transaction_type <> 'recovery'", 'en' => "claim_transaction.amount < 0 AND transaction_type <> 'recovery'"],
                    'fixInSource' => ['de' => 'Correct transaction type in ClaimCenter.', 'en' => 'Correct transaction type in ClaimCenter.'],
                    'fixInWarehouse' => ['de' => 'Flag reserve_anomaly; exclude from incurred until fixed.', 'en' => 'Flag reserve_anomaly; exclude from incurred until fixed.'],
                ],
                [
                    'id' => 'gw-claim-reopened-no-reason',
                    'priority' => 'medium',
                    'title' => ['de' => 'Claim Reopened ohne Reason Code', 'en' => 'Claim reopened without reason code'],
                    'problem' => ['de' => 'Reopened Claims ohne Grund erschweren Root-Cause-Analyse und Backlog-KPIs.', 'en' => 'Reopened claims without a reason complicate root-cause analysis and backlog KPIs.'],
                    'prevent' => ['de' => 'Reopen-Workflow: Reason Code Pflichtfeld.', 'en' => 'Reopen workflow: reason code required field.'],
                    'staffNeedToKnow' => ['de' => 'Claims Ops: Kein Reopen ohne dokumentierten Grund.', 'en' => 'Claims ops: no reopen without a documented reason.'],
                    'checks' => ['de' => "claim_status = 'reopened' AND reopen_reason_code IS NULL", 'en' => "claim_status = 'reopened' AND reopen_reason_code IS NULL"],
                    'fixInSource' => ['de' => 'Backfill reason code; process training.', 'en' => 'Backfill reason code; process training.'],
                    'fixInWarehouse' => ['de' => 'Flag reopen_no_reason; separate from clean reopen KPI.', 'en' => 'Flag reopen_no_reason; separate from clean reopen KPI.'],
                ],
                [
                    'id' => 'gw-duplicate-claim-number',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte claimNumber im Extract', 'en' => 'Duplicate claimNumber in extract'],
                    'problem' => ['de' => 'Doppelte claimNumber verzerren Claims-Count und Incurred-Summen.', 'en' => 'Duplicate claimNumber distort claims count and incurred sums.'],
                    'prevent' => ['de' => 'Idempotent load; PublicID als stabiler Natural Key nutzen.', 'en' => 'Idempotent load; use PublicID as a stable natural key.'],
                    'staffNeedToKnow' => ['de' => 'Data: claimNumber+PublicID als Dedup-Key.', 'en' => 'Data: claimNumber+PublicID as the dedup key.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY claim_number HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY claim_number HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate REST pagination overlap.', 'en' => 'Re-extract; investigate REST pagination overlap.'],
                    'fixInWarehouse' => ['de' => 'Dedup by claim_number; keep latest _loaded_at.', 'en' => 'Dedup by claim_number; keep latest _loaded_at.'],
                ],
                [
                    'id' => 'gw-invoice-no-account',
                    'priority' => 'medium',
                    'title' => ['de' => 'Billing Invoice ohne Account', 'en' => 'Billing invoice without account'],
                    'problem' => ['de' => 'Invoices ohne accountNumber brechen Collections- und Aging-Reports.', 'en' => 'Invoices without accountNumber break collections and aging reports.'],
                    'prevent' => ['de' => 'BillingCenter Invoice-Generierung an Account-Validation koppeln.', 'en' => 'Couple BillingCenter invoice generation to account validation.'],
                    'staffNeedToKnow' => ['de' => 'Billing Ops: Kein Invoice ohne Account-Link.', 'en' => 'Billing ops: no invoice without an account link.'],
                    'checks' => ['de' => 'billing_invoice.account_number IS NULL', 'en' => 'billing_invoice.account_number IS NULL'],
                    'fixInSource' => ['de' => 'Re-link invoice to account.', 'en' => 'Re-link invoice to account.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from collections KPIs.', 'en' => 'Quarantine; exclude from collections KPIs.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'gw-account-dup',
                    'entity' => 'Account',
                    'title' => ['de' => 'Account/Party-Duplikate', 'en' => 'Account/party duplicates'],
                    'matchKeys' => ['accountNumber', 'insuredName', 'address', 'dateOfBirth'],
                    'preventInSource' => ['de' => 'PolicyCenter Party Search vor Account-Create nutzen.', 'en' => 'Use PolicyCenter party search before creating an account.'],
                    'resolveInWarehouse' => ['de' => 'Golden accountNumber; name+DOB-hash merge map.', 'en' => 'Golden accountNumber; name+DOB-hash merge map.'],
                    'survivorship' => ['de' => 'Account mit aktivster Policy/Claim-Historie gewinnt.', 'en' => 'Account with the most active policy/claim history wins.'],
                ],
                [
                    'id' => 'gw-producer-agency-map',
                    'entity' => 'Producer',
                    'title' => ['de' => 'Producer/Agency Mapping Drift', 'en' => 'Producer/agency mapping drift'],
                    'matchKeys' => ['producerCode', 'agencyId'],
                    'preventInSource' => ['de' => 'Distribution-Management-Governance; Agency-Merger dokumentieren.', 'en' => 'Distribution management governance; document agency mergers.'],
                    'resolveInWarehouse' => ['de' => 'Canonical producerCode → agencyId SCD2-Mapping.', 'en' => 'Canonical producerCode → agencyId SCD2 mapping.'],
                    'survivorship' => ['de' => 'Aktueller Agency-Stand gewinnt über Legacy-Producer-Code.', 'en' => 'Current agency state wins over legacy producer code.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'gw-studio-extract-config',
                    'area' => ['de' => 'Guidewire Studio → Data extract / PCF configuration', 'en' => 'Guidewire Studio → Data extract / PCF configuration'],
                    'setting' => ['de' => 'Extract-Scope auf strukturierte Financial/Policy-Felder begrenzen', 'en' => 'Limit extract scope to structured financial/policy fields'],
                    'why' => ['de' => 'Vermeidet versehentliches Laden von Notiz-/Attachment-Feldern.', 'en' => 'Avoids accidentally loading note/attachment fields.'],
                    'how' => ['de' => 'PCF/Rules Review; Field Allowlist pro Extract-Job.', 'en' => 'PCF/rules review; field allowlist per extract job.'],
                ],
                [
                    'id' => 'gw-claimcenter-reserve-config',
                    'area' => ['de' => 'ClaimCenter → Reserve line configuration', 'en' => 'ClaimCenter → Reserve line configuration'],
                    'setting' => ['de' => 'Reserve-Linien und Recovery-Codes konsistent konfigurieren', 'en' => 'Configure reserve lines and recovery codes consistently'],
                    'why' => ['de' => 'Verhindert Negative-Reserve-DQ-Failures und falsche Incurred-Werte.', 'en' => 'Prevents negative-reserve DQ failures and incorrect incurred values.'],
                    'how' => ['de' => 'Reserve-Line-Katalog pflegen; Recovery-Code Pflichtfeld.', 'en' => 'Maintain the reserve-line catalog; recovery code required field.'],
                ],
                [
                    'id' => 'gw-policycenter-product-model',
                    'area' => ['de' => 'PolicyCenter → Product model configuration', 'en' => 'PolicyCenter → Product model configuration'],
                    'setting' => ['de' => 'Coverage/Limit-Struktur je LOB dokumentieren', 'en' => 'Document coverage/limit structure per LOB'],
                    'why' => ['de' => 'Konsistente LOB-Dimension für Loss-Ratio-Reporting.', 'en' => 'Consistent LOB dimension for loss-ratio reporting.'],
                    'how' => ['de' => 'Product Model Review; Coverage-Katalog versionieren.', 'en' => 'Product model review; version the coverage catalog.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'gw-data-dictionary',
                    'kind' => ['de' => 'Guidewire data dictionary / entity schema', 'en' => 'Guidewire data dictionary / entity schema'],
                    'where' => ['de' => 'Guidewire Studio → Entity/Type List; gw data dictionary export', 'en' => 'Guidewire Studio → entity/type list; gw data dictionary export'],
                    'how' => ['de' => 'Entities/Typelists inventarisieren; PII-Felder taggen.', 'en' => 'Inventory entities/typelists; tag PII fields.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (PublicID).', 'en' => 'Extract design, PII tags, join keys (PublicID).'],
                    'watchouts' => ['de' => 'Notiz-/Activity-Entities nie in Select-Allowlist.', 'en' => 'Never include note/activity entities in the select allowlist.'],
                ],
                [
                    'id' => 'gw-claimcenter-financials-schema',
                    'kind' => ['de' => 'ClaimCenter reserve / financials schema', 'en' => 'ClaimCenter reserve / financials schema'],
                    'where' => ['de' => 'ClaimCenter → Reserve Line / Transaction data model', 'en' => 'ClaimCenter → reserve line / transaction data model'],
                    'how' => ['de' => 'Transaction-Typen und Reserve-Linien dokumentieren.', 'en' => 'Document transaction types and reserve lines.'],
                    'useFor' => ['de' => 'Incurred-Facts, Reserve-Development, Loss-Ratio.', 'en' => 'Incurred facts, reserve development, loss ratio.'],
                    'watchouts' => ['de' => 'Recovery/Salvage korrekt als negative Komponente behandeln.', 'en' => 'Correctly treat recovery/salvage as a negative component.'],
                ],
                [
                    'id' => 'gw-policycenter-product-catalog',
                    'kind' => ['de' => 'PolicyCenter product model catalog', 'en' => 'PolicyCenter product model catalog'],
                    'where' => ['de' => 'PolicyCenter → Product Designer / Product Model', 'en' => 'PolicyCenter → Product Designer / product model'],
                    'how' => ['de' => 'Coverage-, Limit- und Rating-Struktur exportieren.', 'en' => 'Export coverage, limit and rating structure.'],
                    'useFor' => ['de' => 'Coverage dim, LOB-Mapping, Premium-Facts.', 'en' => 'Coverage dim, LOB mapping, premium facts.'],
                    'watchouts' => ['de' => 'Produktversionen — SCD2 für Coverage-Änderungen.', 'en' => 'Product versions — SCD2 for coverage changes.'],
                ],
                [
                    'id' => 'gw-cloud-api-schema',
                    'kind' => ['de' => 'Guidewire Cloud API (REST) schema', 'en' => 'Guidewire Cloud API (REST) schema'],
                    'where' => ['de' => 'Guidewire Cloud API Docs → REST resource reference', 'en' => 'Guidewire Cloud API docs → REST resource reference'],
                    'how' => ['de' => 'Resource-Felder inventarisieren; Select-Allowlist für Extract.', 'en' => 'Inventory resource fields; select allowlist for extract.'],
                    'useFor' => ['de' => 'API-based extract design, incremental sync keys.', 'en' => 'API-based extract design, incremental sync keys.'],
                    'watchouts' => ['de' => 'Notes/Activities-Endpoints meiden.', 'en' => 'Avoid notes/activities endpoints.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'duck-creek' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'dc-policytxn-no-account',
                    'priority' => 'high',
                    'title' => ['de' => 'Policy Transaction ohne Account', 'en' => 'Policy transaction without account'],
                    'problem' => ['de' => 'Policy Transactions ohne accountNumber brechen Insured-Rollups und Premium-KPIs.', 'en' => 'Policy transactions without accountNumber break insured rollups and premium KPIs.'],
                    'prevent' => ['de' => 'Duck Creek Policy: Account-Link Pflicht vor Issue.', 'en' => 'Duck Creek Policy: account link required before issue.'],
                    'staffNeedToKnow' => ['de' => 'Underwriting: Kein Issue ohne Account.', 'en' => 'Underwriting: no issue without an account.'],
                    'checks' => ['de' => 'policy_transaction.account_number IS NULL', 'en' => 'policy_transaction.account_number IS NULL'],
                    'fixInSource' => ['de' => 'Link transaction to account; re-issue if unresolved.', 'en' => 'Link transaction to account; re-issue if unresolved.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from in-force/premium KPIs.', 'en' => 'Quarantine; exclude from in-force/premium KPIs.'],
                ],
                [
                    'id' => 'dc-claim-no-policy',
                    'priority' => 'high',
                    'title' => ['de' => 'Claim ohne Policy', 'en' => 'Claim without policy'],
                    'problem' => ['de' => 'Claims ohne policyNumber brechen Loss-Ratio-Joins.', 'en' => 'Claims without policyNumber break loss-ratio joins.'],
                    'prevent' => ['de' => 'Claims Intake: Policy-Lookup Pflicht vor FNOL-Abschluss.', 'en' => 'Claims intake: policy lookup required before FNOL completion.'],
                    'staffNeedToKnow' => ['de' => 'Claims Ops: Kein Claim ohne verifizierte Policy.', 'en' => 'Claims ops: no claim without a verified policy.'],
                    'checks' => ['de' => 'claim.policy_number IS NULL OR policy_number NOT IN dim_policy_transaction', 'en' => 'claim.policy_number IS NULL OR policy_number NOT IN dim_policy_transaction'],
                    'fixInSource' => ['de' => 'Re-link claim to policy; verify Policy sync.', 'en' => 'Re-link claim to policy; verify Policy sync.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown-Policy-Dim.', 'en' => 'Quarantine; unknown-policy dim.'],
                ],
                [
                    'id' => 'dc-rating-no-coverage',
                    'priority' => 'medium',
                    'title' => ['de' => 'Rating Detail ohne Coverage', 'en' => 'Rating detail without coverage'],
                    'problem' => ['de' => 'Rating-Details ohne Coverage-Bezug erschweren Premium-Zerlegung je Coverage.', 'en' => 'Rating details without a coverage reference complicate premium breakdown per coverage.'],
                    'prevent' => ['de' => 'Rating-Engine: Coverage-Referenz Pflicht je Rate-Faktor.', 'en' => 'Rating engine: coverage reference required per rate factor.'],
                    'staffNeedToKnow' => ['de' => 'Rating Team: Jeder Rate-Faktor braucht Coverage-Link.', 'en' => 'Rating team: every rate factor needs a coverage link.'],
                    'checks' => ['de' => 'rating_detail.coverage_id IS NULL', 'en' => 'rating_detail.coverage_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-run rating with coverage mapping fixed.', 'en' => 'Re-run rating with coverage mapping fixed.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from coverage-level premium KPIs.', 'en' => 'Quarantine; exclude from coverage-level premium KPIs.'],
                ],
                [
                    'id' => 'dc-negative-reserve',
                    'priority' => 'high',
                    'title' => ['de' => 'Negative Claim Activity ohne Recovery-Typ', 'en' => 'Negative claim activity without recovery type'],
                    'problem' => ['de' => 'Negative Beträge ohne recovery-Typ verzerren Incurred-Berechnungen.', 'en' => 'Negative amounts without a recovery type distort incurred calculations.'],
                    'prevent' => ['de' => 'Claims Financials: Recovery-Typ Pflicht bei negativer Activity.', 'en' => 'Claims financials: recovery type required for negative activity.'],
                    'staffNeedToKnow' => ['de' => 'Claims Finance: Negative Beträge immer mit Recovery-Code buchen.', 'en' => 'Claims finance: always post negative amounts with a recovery code.'],
                    'checks' => ['de' => "claim_activity.amount < 0 AND activity_type <> 'recovery'", 'en' => "claim_activity.amount < 0 AND activity_type <> 'recovery'"],
                    'fixInSource' => ['de' => 'Correct activity type in Duck Creek Claims.', 'en' => 'Correct activity type in Duck Creek Claims.'],
                    'fixInWarehouse' => ['de' => 'Flag reserve_anomaly; exclude from incurred until fixed.', 'en' => 'Flag reserve_anomaly; exclude from incurred until fixed.'],
                ],
                [
                    'id' => 'dc-duplicate-policy-number',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte policyNumber im Extract', 'en' => 'Duplicate policyNumber in extract'],
                    'problem' => ['de' => 'Doppelte policyNumber verzerren In-Force-Counts und Premium-Summen.', 'en' => 'Duplicate policyNumber distort in-force counts and premium sums.'],
                    'prevent' => ['de' => 'Idempotent load; Transaction-Effective-Date als Versionierung.', 'en' => 'Idempotent load; transaction effective date as versioning.'],
                    'staffNeedToKnow' => ['de' => 'Data: Neuste Transaction je policyNumber für Status nutzen.', 'en' => 'Data: Use the latest transaction per policyNumber for status.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY policy_number, effective_date HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY policy_number, effective_date HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate OnDemand batch overlap.', 'en' => 'Re-extract; investigate OnDemand batch overlap.'],
                    'fixInWarehouse' => ['de' => 'Dedup by policy_number+effective_date; keep _loaded_at.', 'en' => 'Dedup by policy_number+effective_date; keep _loaded_at.'],
                ],
                [
                    'id' => 'dc-billing-no-account',
                    'priority' => 'medium',
                    'title' => ['de' => 'Billing Transaction ohne Account', 'en' => 'Billing transaction without account'],
                    'problem' => ['de' => 'Billing Transactions ohne accountNumber brechen Collections-Reports.', 'en' => 'Billing transactions without accountNumber break collections reports.'],
                    'prevent' => ['de' => 'Billing-Generierung an Account-Validation koppeln.', 'en' => 'Couple billing generation to account validation.'],
                    'staffNeedToKnow' => ['de' => 'Billing Ops: Kein Billing ohne Account-Link.', 'en' => 'Billing ops: no billing without an account link.'],
                    'checks' => ['de' => 'billing_transaction.account_number IS NULL', 'en' => 'billing_transaction.account_number IS NULL'],
                    'fixInSource' => ['de' => 'Re-link transaction to account.', 'en' => 'Re-link transaction to account.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from collections KPIs.', 'en' => 'Quarantine; exclude from collections KPIs.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'dc-account-dup',
                    'entity' => 'Account',
                    'title' => ['de' => 'Account-Duplikate', 'en' => 'Account duplicates'],
                    'matchKeys' => ['accountNumber', 'insuredName', 'address', 'dateOfBirth'],
                    'preventInSource' => ['de' => 'Party-Search vor Account-Create nutzen.', 'en' => 'Use party search before creating an account.'],
                    'resolveInWarehouse' => ['de' => 'Golden accountNumber; name+DOB-hash merge map.', 'en' => 'Golden accountNumber; name+DOB-hash merge map.'],
                    'survivorship' => ['de' => 'Account mit aktivster Policy/Claim-Historie gewinnt.', 'en' => 'Account with the most active policy/claim history wins.'],
                ],
                [
                    'id' => 'dc-producer-map',
                    'entity' => 'Producer',
                    'title' => ['de' => 'Producer/Agency Mapping Drift', 'en' => 'Producer/agency mapping drift'],
                    'matchKeys' => ['producerCode', 'agencyId'],
                    'preventInSource' => ['de' => 'Distribution-Governance; Agency-Merger dokumentieren.', 'en' => 'Distribution governance; document agency mergers.'],
                    'resolveInWarehouse' => ['de' => 'Canonical producerCode → agencyId SCD2-Mapping.', 'en' => 'Canonical producerCode → agencyId SCD2 mapping.'],
                    'survivorship' => ['de' => 'Aktueller Agency-Stand gewinnt über Legacy-Producer-Code.', 'en' => 'Current agency state wins over legacy producer code.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'dc-author-rules-config',
                    'area' => ['de' => 'Duck Creek Author → Rules configuration', 'en' => 'Duck Creek Author → Rules configuration'],
                    'setting' => ['de' => 'Rules-Extract-Scope auf strukturierte Policy-/Rating-Felder begrenzen', 'en' => 'Limit rules extract scope to structured policy/rating fields'],
                    'why' => ['de' => 'Vermeidet versehentliches Laden von Correspondence-/Notiz-Feldern.', 'en' => 'Avoids accidentally loading correspondence/note fields.'],
                    'how' => ['de' => 'Rules-Review; Field Allowlist pro Extract-Job.', 'en' => 'Rules review; field allowlist per extract job.'],
                ],
                [
                    'id' => 'dc-insights-extract-mapping',
                    'area' => ['de' => 'Duck Creek Insights → Extract mapping', 'en' => 'Duck Creek Insights → Extract mapping'],
                    'setting' => ['de' => 'Insights-Datamart-Mapping auf Policy/Claim/Billing-Facts begrenzen', 'en' => 'Limit Insights datamart mapping to policy/claim/billing facts'],
                    'why' => ['de' => 'Konsistente Facts für Analytics ohne Dokument-Bodies.', 'en' => 'Consistent facts for analytics without document bodies.'],
                    'how' => ['de' => 'Mapping-Review je Release; Field Allowlist pflegen.', 'en' => 'Mapping review per release; maintain field allowlist.'],
                ],
                [
                    'id' => 'dc-ondemand-tenant-config',
                    'area' => ['de' => 'Duck Creek OnDemand → Tenant data extraction config', 'en' => 'Duck Creek OnDemand → Tenant data extraction config'],
                    'setting' => ['de' => 'Tenant-Extraction-Scope und Retention je Umgebung dokumentieren', 'en' => 'Document tenant extraction scope and retention per environment'],
                    'why' => ['de' => 'Verhindert Vermischung von Prod- und UAT-Tenants im Warehouse.', 'en' => 'Prevents mixing prod and UAT tenants in the warehouse.'],
                    'how' => ['de' => 'Tenant-Config-Review; getrennte Extract-Jobs je Environment.', 'en' => 'Tenant config review; separate extract jobs per environment.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'dc-example-app-schema',
                    'kind' => ['de' => 'Duck Creek Example App entity schema', 'en' => 'Duck Creek Example App entity schema'],
                    'where' => ['de' => 'Duck Creek Author → Example App data model reference', 'en' => 'Duck Creek Author → Example App data model reference'],
                    'how' => ['de' => 'Entities/Felder inventarisieren; PII-Felder taggen.', 'en' => 'Inventory entities/fields; tag PII fields.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys.', 'en' => 'Extract design, PII tags, join keys.'],
                    'watchouts' => ['de' => 'Correspondence-/Notiz-Entities nie in Select-Allowlist.', 'en' => 'Never include correspondence/note entities in the select allowlist.'],
                ],
                [
                    'id' => 'dc-insights-data-model',
                    'kind' => ['de' => 'Duck Creek Insights data model catalog', 'en' => 'Duck Creek Insights data model catalog'],
                    'where' => ['de' => 'Duck Creek Insights → Data model / semantic layer documentation', 'en' => 'Duck Creek Insights → data model / semantic layer documentation'],
                    'how' => ['de' => 'Fact/Dimension-Struktur des Insights-Datamarts dokumentieren.', 'en' => 'Document the Insights datamart fact/dimension structure.'],
                    'useFor' => ['de' => 'Premium-/Loss-Ratio-Facts, Coverage-Dimension.', 'en' => 'Premium/loss-ratio facts, coverage dimension.'],
                    'watchouts' => ['de' => 'Insights-Facts können bereits aggregiert sein — Doppelzählung vermeiden.', 'en' => 'Insights facts may already be aggregated — avoid double-counting.'],
                ],
                [
                    'id' => 'dc-policy-claims-xsd',
                    'kind' => ['de' => 'Policy / Claims XSD schema', 'en' => 'Policy / Claims XSD schema'],
                    'where' => ['de' => 'Duck Creek Policy/Claims → XSD / message schema reference', 'en' => 'Duck Creek Policy/Claims → XSD / message schema reference'],
                    'how' => ['de' => 'Message-Elemente inventarisieren; Freitext-Elemente markieren.', 'en' => 'Inventory message elements; flag free-text elements.'],
                    'useFor' => ['de' => 'Extract design für Policy-/Claims-Integrationen.', 'en' => 'Extract design for policy/claims integrations.'],
                    'watchouts' => ['de' => 'Correspondence-/Document-Elemente meiden.', 'en' => 'Avoid correspondence/document elements.'],
                ],
                [
                    'id' => 'dc-rest-api-catalog',
                    'kind' => ['de' => 'Duck Creek REST API catalog', 'en' => 'Duck Creek REST API catalog'],
                    'where' => ['de' => 'Duck Creek OnDemand → REST API reference', 'en' => 'Duck Creek OnDemand → REST API reference'],
                    'how' => ['de' => 'Resource-Felder inventarisieren; Select-Allowlist für Extract.', 'en' => 'Inventory resource fields; select allowlist for extract.'],
                    'useFor' => ['de' => 'API-based extract design, incremental sync keys.', 'en' => 'API-based extract design, incremental sync keys.'],
                    'watchouts' => ['de' => 'Document-/Attachment-Endpoints meiden.', 'en' => 'Avoid document/attachment endpoints.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],
];
