<?php

/**
 * Wave 4 quality overlays — Finance/Spend source-native DQ, MDM, metadata guides.
 *
 * @return array<string, array<string, mixed>>
 */

return [
    'stripe' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'stripe-payment-no-amount',
                    'priority' => 'high',
                    'title' => ['de' => 'Payment succeeded ohne Amount/Currency', 'en' => 'Payment succeeded without amount/currency'],
                    'problem' => ['de' => 'Succeeded Payments ohne amount/currency machen Revenue und FX-Reports unbrauchbar.', 'en' => 'Succeeded payments without amount/currency make revenue and FX reports unusable.'],
                    'prevent' => ['de' => 'API Create: amount + currency Pflicht; Webhook-Handler validieren.', 'en' => 'API create: amount + currency required; validate webhook handler.'],
                    'staffNeedToKnow' => ['de' => 'Engineering: Kein succeeded ohne amount/currency.', 'en' => 'Engineering: No succeeded without amount/currency.'],
                    'checks' => ['de' => 'status = succeeded AND (amount IS NULL OR currency IS NULL)', 'en' => 'status = succeeded AND (amount IS NULL OR currency IS NULL)'],
                    'fixInSource' => ['de' => 'Stripe API validation; block incomplete PaymentIntent create.', 'en' => 'Stripe API validation; block incomplete PaymentIntent create.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from revenue KPIs.', 'en' => 'Quarantine; exclude from revenue KPIs.'],
                ],
                [
                    'id' => 'stripe-charge-no-customer',
                    'priority' => 'high',
                    'title' => ['de' => 'Charge ohne Customer (wenn Pflicht)', 'en' => 'Charge without customer when required'],
                    'problem' => ['de' => 'Charges ohne customer_id brechen Customer Lifetime und Cohort-Joins.', 'en' => 'Charges without customer_id break customer lifetime and cohort joins.'],
                    'prevent' => ['de' => 'Checkout/Policy: Customer Pflicht für B2B/Subscription Flows.', 'en' => 'Checkout/policy: customer required for B2B/subscription flows.'],
                    'staffNeedToKnow' => ['de' => 'Product: Guest Checkout vs. Customer-Pflicht dokumentieren.', 'en' => 'Product: Document guest checkout vs customer-required policy.'],
                    'checks' => ['de' => 'customer_id IS NULL AND requires_customer = TRUE', 'en' => 'customer_id IS NULL AND requires_customer = TRUE'],
                    'fixInSource' => ['de' => 'Attach Customer on PaymentIntent; update orphan charges.', 'en' => 'Attach customer on PaymentIntent; update orphan charges.'],
                    'fixInWarehouse' => ['de' => 'Unknown-customer dim; exclude from customer KPIs.', 'en' => 'Unknown-customer dim; exclude from customer KPIs.'],
                ],
                [
                    'id' => 'stripe-refund-gt-charge',
                    'priority' => 'high',
                    'title' => ['de' => 'Refund größer als Charge', 'en' => 'Refund greater than charge'],
                    'problem' => ['de' => 'Refund amount > charge amount verzerrt Net Revenue.', 'en' => 'Refund amount > charge amount distorts net revenue.'],
                    'prevent' => ['de' => 'Refund API Limits respektieren; Partial Refund Summen prüfen.', 'en' => 'Respect refund API limits; validate partial refund sums.'],
                    'staffNeedToKnow' => ['de' => 'Finance Ops: Refunds nie über Charge-Amount.', 'en' => 'Finance ops: Never refund above charge amount.'],
                    'checks' => ['de' => 'SUM(refund.amount) > charge.amount GROUP BY charge_id', 'en' => 'SUM(refund.amount) > charge.amount GROUP BY charge_id'],
                    'fixInSource' => ['de' => 'Investigate in Dashboard; correct via Stripe support if needed.', 'en' => 'Investigate in Dashboard; correct via Stripe support if needed.'],
                    'fixInWarehouse' => ['de' => 'Flag over-refund; cap net revenue with audit flag.', 'en' => 'Flag over-refund; cap net revenue with audit flag.'],
                ],
                [
                    'id' => 'stripe-test-in-prod',
                    'priority' => 'medium',
                    'title' => ['de' => 'Test-Mode in Prod Marts', 'en' => 'Test mode in prod marts'],
                    'problem' => ['de' => 'livemode = false in Prod-Revenue verzerrt Finance-KPIs.', 'en' => 'livemode = false in prod revenue distorts finance KPIs.'],
                    'prevent' => ['de' => 'Extract-Filter livemode = true; separate test warehouse.', 'en' => 'Extract filter livemode = true; separate test warehouse.'],
                    'staffNeedToKnow' => ['de' => 'Data: Test Charges nie in Prod-Finance-Marts.', 'en' => 'Data: Never put test charges in prod finance marts.'],
                    'checks' => ['de' => 'livemode = false AND included_in_prod_mart = true', 'en' => 'livemode = false AND included_in_prod_mart = true'],
                    'fixInSource' => ['de' => 'Use live API keys for prod extract only.', 'en' => 'Use live API keys for prod extract only.'],
                    'fixInWarehouse' => ['de' => 'Exclude livemode false from prod revenue.', 'en' => 'Exclude livemode false from prod revenue.'],
                ],
                [
                    'id' => 'stripe-currency-mismatch',
                    'priority' => 'medium',
                    'title' => ['de' => 'Currency Mismatch Charge vs Balance', 'en' => 'Currency mismatch charge vs balance'],
                    'problem' => ['de' => 'Charge currency ≠ settlement currency ohne FX-Felder bricht Multi-Currency Reporting.', 'en' => 'Charge currency ≠ settlement currency without FX fields breaks multi-currency reporting.'],
                    'prevent' => ['de' => 'Balance Transaction Felder (exchange_rate, amount) mitladen.', 'en' => 'Load balance transaction fields (exchange_rate, amount).'],
                    'staffNeedToKnow' => ['de' => 'Finance: Presentment vs Settlement Currency trennen.', 'en' => 'Finance: Separate presentment vs settlement currency.'],
                    'checks' => ['de' => 'charge.currency <> balance_transaction.currency AND exchange_rate IS NULL', 'en' => 'charge.currency <> balance_transaction.currency AND exchange_rate IS NULL'],
                    'fixInSource' => ['de' => 'Expand balance_transaction on Charge retrieve.', 'en' => 'Expand balance_transaction on Charge retrieve.'],
                    'fixInWarehouse' => ['de' => 'Store both currencies; convert via FX table.', 'en' => 'Store both currencies; convert via FX table.'],
                ],
                [
                    'id' => 'stripe-duplicate-idempotency',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Charges bei Idempotency Drift', 'en' => 'Duplicate charges from idempotency drift'],
                    'problem' => ['de' => 'Doppelte charge.id / PaymentIntent verzerren GMV und Counts.', 'en' => 'Duplicate charge.id / PaymentIntent distort GMV and counts.'],
                    'prevent' => ['de' => 'Idempotency-Key Policy; Dedup auf charge.id.', 'en' => 'Idempotency-key policy; dedup on charge.id.'],
                    'staffNeedToKnow' => ['de' => 'Integrationen: Idempotency Keys stabil halten.', 'en' => 'Integrations: Keep idempotency keys stable.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY charge_id HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY charge_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Review API retries; merge duplicates in Stripe where possible.', 'en' => 'Review API retries; merge duplicates in Stripe where possible.'],
                    'fixInWarehouse' => ['de' => 'Dedup by charge_id; keep latest _loaded_at.', 'en' => 'Dedup by charge_id; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'stripe-customer-dup',
                    'entity' => 'Customer',
                    'title' => ['de' => 'Customer-Duplikate / Email', 'en' => 'Customer duplicates / email'],
                    'matchKeys' => ['customer.id', 'email', 'metadata.external_id'],
                    'preventInSource' => ['de' => 'Customer Create mit unique email/external_id; Search before create.', 'en' => 'Customer create with unique email/external_id; search before create.'],
                    'resolveInWarehouse' => ['de' => 'Golden customer.id; email-hash merge map.', 'en' => 'Golden customer.id; email-hash merge map.'],
                    'survivorship' => ['de' => 'Aktiver Customer mit neuester Charge gewinnt.', 'en' => 'Active customer with latest charge wins.'],
                ],
                [
                    'id' => 'stripe-payment-intent-charge',
                    'entity' => 'PaymentIntent / Charge',
                    'title' => ['de' => 'PaymentIntent vs Charge Mapping', 'en' => 'PaymentIntent vs charge mapping'],
                    'matchKeys' => ['payment_intent.id', 'charge.id', 'idempotency_key'],
                    'preventInSource' => ['de' => 'Stable Idempotency Keys; one PI per checkout attempt.', 'en' => 'Stable idempotency keys; one PI per checkout attempt.'],
                    'resolveInWarehouse' => ['de' => 'Canonical payment_intent_id → charge_id map.', 'en' => 'Canonical payment_intent_id → charge_id map.'],
                    'survivorship' => ['de' => 'Succeeded Charge gewinnt über incomplete PI.', 'en' => 'Succeeded charge wins over incomplete PI.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'stripe-radar-rules',
                    'area' => ['de' => 'Radar → Rules', 'en' => 'Radar → Rules'],
                    'setting' => ['de' => 'Radar Rules und Block/Review Outcomes dokumentieren', 'en' => 'Document Radar rules and block/review outcomes'],
                    'why' => ['de' => 'Fraud Outcomes beeinflussen GMV und Dispute Rates.', 'en' => 'Fraud outcomes affect GMV and dispute rates.'],
                    'how' => ['de' => 'Radar settings export; map outcomes to fact flags.', 'en' => 'Radar settings export; map outcomes to fact flags.'],
                ],
                [
                    'id' => 'stripe-webhook-allowlist',
                    'area' => ['de' => 'Developers → Webhooks', 'en' => 'Developers → Webhooks'],
                    'setting' => ['de' => 'Event-Allowlist statt alle Events speichern', 'en' => 'Event allowlist instead of storing all events'],
                    'why' => ['de' => 'Reduziert PII-Duplikate und Webhook-Noise.', 'en' => 'Reduces PII duplicates and webhook noise.'],
                    'how' => ['de' => 'Subscribe only payment/invoice events needed for analytics.', 'en' => 'Subscribe only payment/invoice events needed for analytics.'],
                ],
                [
                    'id' => 'stripe-tax-settings',
                    'area' => ['de' => 'Settings → Tax / Stripe Tax', 'en' => 'Settings → Tax / Stripe Tax'],
                    'setting' => ['de' => 'Tax Collection und Reporting Currencies klären', 'en' => 'Clarify tax collection and reporting currencies'],
                    'why' => ['de' => 'Tax und Presentment Currency müssen zu Finance-Marts passen.', 'en' => 'Tax and presentment currency must match finance marts.'],
                    'how' => ['de' => 'Tax settings review; document inclusive vs exclusive amounts.', 'en' => 'Tax settings review; document inclusive vs exclusive amounts.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'stripe-dashboard-api',
                    'kind' => ['de' => 'Dashboard data / API objects', 'en' => 'Dashboard data / API objects'],
                    'where' => ['de' => 'Stripe Dashboard → Developers / API; object docs (Customer, Charge, PaymentIntent)', 'en' => 'Stripe Dashboard → Developers / API; object docs (Customer, Charge, PaymentIntent)'],
                    'how' => ['de' => 'Object fields inventarisieren; Expand-Allowlist für Extract.', 'en' => 'Inventory object fields; expand allowlist for extract.'],
                    'useFor' => ['de' => 'Extract-Design, PII-Tags, Join-Keys (customer, charge, PI).', 'en' => 'Extract design, PII tags, join keys (customer, charge, PI).'],
                    'watchouts' => ['de' => 'Nested billing_details und payment_method — PCI/PII beachten.', 'en' => 'Nested billing_details and payment_method — watch PCI/PII.'],
                ],
                [
                    'id' => 'stripe-events',
                    'kind' => ['de' => 'Events', 'en' => 'Events'],
                    'where' => ['de' => 'Developers → Events / Webhooks; event types catalog', 'en' => 'Developers → Events / Webhooks; event types catalog'],
                    'how' => ['de' => 'Event types Allowlist; Payload-Felder dokumentieren.', 'en' => 'Allowlist event types; document payload fields.'],
                    'useFor' => ['de' => 'CDC-ähnlich Extract, Status Transitions, Dispute Signals.', 'en' => 'CDC-like extract, status transitions, dispute signals.'],
                    'watchouts' => ['de' => 'Full event.data.object verdoppelt PII — Metadata bevorzugen.', 'en' => 'Full event.data.object duplicates PII — prefer metadata.'],
                ],
                [
                    'id' => 'stripe-sigma',
                    'kind' => ['de' => 'Sigma / SQL', 'en' => 'Sigma / SQL'],
                    'where' => ['de' => 'Stripe Sigma → SQL editor / datasets', 'en' => 'Stripe Sigma → SQL editor / datasets'],
                    'how' => ['de' => 'Sigma Schema als Referenz; Warehouse-Models nicht 1:1 klonen ohne Allowlist.', 'en' => 'Use Sigma schema as reference; do not clone 1:1 into warehouse without allowlist.'],
                    'useFor' => ['de' => 'Field discovery, sanity checks, finance report prototypes.', 'en' => 'Field discovery, sanity checks, finance report prototypes.'],
                    'watchouts' => ['de' => 'Sigma ≠ Warehouse Landing — Retention und PII separat steuern.', 'en' => 'Sigma ≠ warehouse landing — control retention and PII separately.'],
                ],
                [
                    'id' => 'stripe-tax-radar',
                    'kind' => ['de' => 'Tax / Radar settings', 'en' => 'Tax / Radar settings'],
                    'where' => ['de' => 'Settings → Tax; Radar → Rules / Lists', 'en' => 'Settings → Tax; Radar → Rules / Lists'],
                    'how' => ['de' => 'Tax und Radar Config exportieren; Outcome Codes mappen.', 'en' => 'Export tax and Radar config; map outcome codes.'],
                    'useFor' => ['de' => 'Tax flags, fraud outcome dims, dispute readiness.', 'en' => 'Tax flags, fraud outcome dims, dispute readiness.'],
                    'watchouts' => ['de' => 'Radar Evidence nicht als Analytics-Default laden.', 'en' => 'Do not load Radar evidence as analytics default.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'sap-concur' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'concur-approved-no-allocation',
                    'priority' => 'high',
                    'title' => ['de' => 'Approved Report ohne Cost Center/Allocation', 'en' => 'Approved report without cost center/allocation'],
                    'problem' => ['de' => 'Freigegebene Reports ohne Allocation lassen Spend nicht nach Cost Center schneiden.', 'en' => 'Approved reports without allocation cannot slice spend by cost center.'],
                    'prevent' => ['de' => 'Policy: Allocation Pflicht vor Submit/Approve; Form Validation.', 'en' => 'Policy: allocation required before submit/approve; form validation.'],
                    'staffNeedToKnow' => ['de' => 'Employees: Kein Submit ohne Cost Center/Allocation.', 'en' => 'Employees: Do not submit without cost center/allocation.'],
                    'checks' => ['de' => 'ApprovalStatus = Approved AND (cost_center IS NULL OR allocation_pct IS NULL)', 'en' => 'ApprovalStatus = Approved AND (cost_center IS NULL OR allocation_pct IS NULL)'],
                    'fixInSource' => ['de' => 'Form / policy config; return report for allocation.', 'en' => 'Form / policy config; return report for allocation.'],
                    'fixInWarehouse' => ['de' => 'Unknown cost center dim; exclude from CC KPIs.', 'en' => 'Unknown cost center dim; exclude from CC KPIs.'],
                ],
                [
                    'id' => 'concur-entry-no-expense-type',
                    'priority' => 'high',
                    'title' => ['de' => 'Entry ohne Expense Type', 'en' => 'Entry without expense type'],
                    'problem' => ['de' => 'Entries ohne Expense Type brechen Category- und Policy-Reports.', 'en' => 'Entries without expense type break category and policy reports.'],
                    'prevent' => ['de' => 'Expense Type required on entry create; API validate.', 'en' => 'Expense type required on entry create; API validate.'],
                    'staffNeedToKnow' => ['de' => 'Users: Jede Position braucht einen Expense Type.', 'en' => 'Users: Every line needs an expense type.'],
                    'checks' => ['de' => 'expense_type_code IS NULL on entry', 'en' => 'expense_type_code IS NULL on entry'],
                    'fixInSource' => ['de' => 'Required field; correct via Expense API.', 'en' => 'Required field; correct via Expense API.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown expense type bucket.', 'en' => 'Quarantine; Unknown expense type bucket.'],
                ],
                [
                    'id' => 'concur-allocation-pct-ne-100',
                    'priority' => 'high',
                    'title' => ['de' => 'Allocation Summe ≠ 100%', 'en' => 'Allocation sum ≠ 100%'],
                    'problem' => ['de' => 'Allocation % ≠ 100 verzerrt Cost-Center-Spend und Ledger-Feeds.', 'en' => 'Allocation % ≠ 100 distorts cost-center spend and ledger feeds.'],
                    'prevent' => ['de' => 'Concur Allocation Validation; Submit block if sum ≠ 100.', 'en' => 'Concur allocation validation; block submit if sum ≠ 100.'],
                    'staffNeedToKnow' => ['de' => 'Employees: Allocations müssen 100% ergeben.', 'en' => 'Employees: Allocations must total 100%.'],
                    'checks' => ['de' => 'SUM(allocation_pct) <> 100 GROUP BY entry_id', 'en' => 'SUM(allocation_pct) <> 100 GROUP BY entry_id'],
                    'fixInSource' => ['de' => 'Return for correction; policy enforcement.', 'en' => 'Return for correction; policy enforcement.'],
                    'fixInWarehouse' => ['de' => 'Flag invalid allocation; exclude from CC rollups.', 'en' => 'Flag invalid allocation; exclude from CC rollups.'],
                ],
                [
                    'id' => 'concur-approved-before-submitted',
                    'priority' => 'medium',
                    'title' => ['de' => 'Approved vor Submitted', 'en' => 'Approved before submitted'],
                    'problem' => ['de' => 'approved_at < submitted_at macht Cycle-Time und SLA unbrauchbar.', 'en' => 'approved_at < submitted_at makes cycle time and SLA unusable.'],
                    'prevent' => ['de' => 'Keine manuellen Datum-Overrides; Migration Timestamps prüfen.', 'en' => 'No manual date overrides; validate migration timestamps.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Status-Timestamps konsistent halten.', 'en' => 'Admins: Keep status timestamps consistent.'],
                    'checks' => ['de' => 'approved_at < submitted_at', 'en' => 'approved_at < submitted_at'],
                    'fixInSource' => ['de' => 'Re-sync report history; fix source timestamps.', 'en' => 'Re-sync report history; fix source timestamps.'],
                    'fixInWarehouse' => ['de' => 'Flag invalid dates; null cycle metrics.', 'en' => 'Flag invalid dates; null cycle metrics.'],
                ],
                [
                    'id' => 'concur-amount-null-approved',
                    'priority' => 'high',
                    'title' => ['de' => 'Approved Entry ohne Amount', 'en' => 'Approved entry without amount'],
                    'problem' => ['de' => 'Freigegebene Entries ohne Amount verzerren Total Spend.', 'en' => 'Approved entries without amount distort total spend.'],
                    'prevent' => ['de' => 'Amount Pflicht vor Submit; Soft-Delete Zero-Drafts.', 'en' => 'Amount required before submit; soft-delete zero drafts.'],
                    'staffNeedToKnow' => ['de' => 'Users: Keine Freigabe ohne Betrag.', 'en' => 'Users: No approval without amount.'],
                    'checks' => ['de' => 'ApprovalStatus = Approved AND (amount IS NULL OR amount = 0) AND NOT mileage_exception', 'en' => 'ApprovalStatus = Approved AND (amount IS NULL OR amount = 0) AND NOT mileage_exception'],
                    'fixInSource' => ['de' => 'Return report; required amount policy.', 'en' => 'Return report; required amount policy.'],
                    'fixInWarehouse' => ['de' => 'Exclude from spend totals; quarantine.', 'en' => 'Exclude from spend totals; quarantine.'],
                ],
                [
                    'id' => 'concur-duplicate-report-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Report IDs im Extract', 'en' => 'Duplicate report ids in extract'],
                    'problem' => ['de' => 'Doppelte ReportID verzerren Spend Counts und Joins.', 'en' => 'Duplicate ReportID distort spend counts and joins.'],
                    'prevent' => ['de' => 'Incremental Extract Dedup; Idempotent Load Key.', 'en' => 'Incremental extract dedup; idempotent load key.'],
                    'staffNeedToKnow' => ['de' => 'Data: ReportID eindeutig halten.', 'en' => 'Data: Keep ReportID unique.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY report_id HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY report_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate API pagination overlaps.', 'en' => 'Re-extract; investigate API pagination overlaps.'],
                    'fixInWarehouse' => ['de' => 'Dedup by report_id; keep latest _loaded_at.', 'en' => 'Dedup by report_id; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'concur-employee-dup',
                    'entity' => 'Employee',
                    'title' => ['de' => 'Employee-Duplikate / Rehire', 'en' => 'Employee duplicates / rehire'],
                    'matchKeys' => ['EmployeeID', 'EmailAddress', 'LoginID'],
                    'preventInSource' => ['de' => 'HR feed as source of truth; deactivate instead of recreate.', 'en' => 'HR feed as source of truth; deactivate instead of recreate.'],
                    'resolveInWarehouse' => ['de' => 'Golden EmployeeID; email-hash merge map.', 'en' => 'Golden EmployeeID; email-hash merge map.'],
                    'survivorship' => ['de' => 'Aktiver Employee mit neuester Report Activity gewinnt.', 'en' => 'Active employee with latest report activity wins.'],
                ],
                [
                    'id' => 'concur-cost-center-map',
                    'entity' => 'Cost center / allocation',
                    'title' => ['de' => 'Cost Center vs ERP Mapping', 'en' => 'Cost center vs ERP mapping'],
                    'matchKeys' => ['cost_center_code', 'ERP cost object', 'org unit'],
                    'preventInSource' => ['de' => 'List sync from ERP; controlled cost center vocabulary.', 'en' => 'List sync from ERP; controlled cost center vocabulary.'],
                    'resolveInWarehouse' => ['de' => 'Canonical cost_center_code via ERP map.', 'en' => 'Canonical cost_center_code via ERP map.'],
                    'survivorship' => ['de' => 'ERP code gewinnt über lokale Concur-Listenwerte.', 'en' => 'ERP code wins over local Concur list values.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'concur-expense-types',
                    'area' => ['de' => 'Expense → Expense Types', 'en' => 'Expense → Expense Types'],
                    'setting' => ['de' => 'Expense Type Catalog pflegen und required machen', 'en' => 'Maintain expense type catalog and make required'],
                    'why' => ['de' => 'Category Spend bleibt analysierbar.', 'en' => 'Category spend stays analyzable.'],
                    'how' => ['de' => 'Admin config; deactivate unused types; form required.', 'en' => 'Admin config; deactivate unused types; form required.'],
                ],
                [
                    'id' => 'concur-allocation-policy',
                    'area' => ['de' => 'Forms / Policies → Allocations', 'en' => 'Forms / Policies → Allocations'],
                    'setting' => ['de' => 'Allocation 100% Validation vor Submit', 'en' => 'Allocation 100% validation before submit'],
                    'why' => ['de' => 'Cost-Center-Rollups bleiben korrekt.', 'en' => 'Cost-center rollups stay correct.'],
                    'how' => ['de' => 'Policy rule; test in sandbox company.', 'en' => 'Policy rule; test in sandbox company.'],
                ],
                [
                    'id' => 'concur-api-clients',
                    'area' => ['de' => 'Authentication → API clients', 'en' => 'Authentication → API clients'],
                    'setting' => ['de' => 'Least Privilege Scopes für Analytics Extract', 'en' => 'Least privilege scopes for analytics extract'],
                    'why' => ['de' => 'Verhindert Receipt-Binary und unnötige PII im Load.', 'en' => 'Prevents receipt binary and unnecessary PII in the load.'],
                    'how' => ['de' => 'App review; omit imaging scopes unless required.', 'en' => 'App review; omit imaging scopes unless required.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'concur-expense-types-meta',
                    'kind' => ['de' => 'Expense types config', 'en' => 'Expense types config'],
                    'where' => ['de' => 'Expense Admin → Expense Types', 'en' => 'Expense Admin → Expense Types'],
                    'how' => ['de' => 'Expense Type Codes und Policies exportieren.', 'en' => 'Export expense type codes and policies.'],
                    'useFor' => ['de' => 'Category dims, DQ required-type checks, policy flags.', 'en' => 'Category dims, DQ required-type checks, policy flags.'],
                    'watchouts' => ['de' => 'Codes unterscheiden sich pro Entity/Company Group.', 'en' => 'Codes differ by entity/company group.'],
                ],
                [
                    'id' => 'concur-allocation-fields',
                    'kind' => ['de' => 'Allocation fields', 'en' => 'Allocation fields'],
                    'where' => ['de' => 'Forms → Allocation fields / connected lists', 'en' => 'Forms → Allocation fields / connected lists'],
                    'how' => ['de' => 'Cost Center / Project Field IDs und Listenquellen dokumentieren.', 'en' => 'Document cost center / project field IDs and list sources.'],
                    'useFor' => ['de' => 'Spend by CC, ERP join keys, allocation DQ.', 'en' => 'Spend by CC, ERP join keys, allocation DQ.'],
                    'watchouts' => ['de' => 'Connected Lists können veralten — Sync mit ERP prüfen.', 'en' => 'Connected lists can go stale — check ERP sync.'],
                ],
                [
                    'id' => 'concur-api-clients-meta',
                    'kind' => ['de' => 'API clients', 'en' => 'API clients'],
                    'where' => ['de' => 'Company Admin → Authentication / Application management', 'en' => 'Company Admin → Authentication / Application management'],
                    'how' => ['de' => 'Client scopes und grant types inventarisieren.', 'en' => 'Inventory client scopes and grant types.'],
                    'useFor' => ['de' => 'Extract design, least privilege, PII allowlist.', 'en' => 'Extract design, least privilege, PII allowlist.'],
                    'watchouts' => ['de' => 'Imaging/Receipt scopes ziehen Binaries — default avoid.', 'en' => 'Imaging/receipt scopes pull binaries — avoid by default.'],
                ],
                [
                    'id' => 'concur-reporting-config',
                    'kind' => ['de' => 'Reporting config', 'en' => 'Reporting config'],
                    'where' => ['de' => 'Analysis / Intelligence reporting configuration', 'en' => 'Analysis / Intelligence reporting configuration'],
                    'how' => ['de' => 'Standard Reports und Data Warehouse Feeds als Feld-Referenz nutzen.', 'en' => 'Use standard reports and data warehouse feeds as field reference.'],
                    'useFor' => ['de' => 'Field discovery, spend grain, status maps.', 'en' => 'Field discovery, spend grain, status maps.'],
                    'watchouts' => ['de' => 'Reporting ≠ RAW Landing — Warehouse Models selbst designen.', 'en' => 'Reporting ≠ RAW landing — design warehouse models yourself.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'sap-ariba' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'ariba-po-no-supplier',
                    'priority' => 'high',
                    'title' => ['de' => 'PO ohne Supplier', 'en' => 'PO without supplier'],
                    'problem' => ['de' => 'Purchase Orders ohne Supplier brechen Spend-by-Vendor und Contract Compliance.', 'en' => 'Purchase orders without supplier break spend-by-vendor and contract compliance.'],
                    'prevent' => ['de' => 'PO Create: Supplier Pflicht; Catalog/Non-Catalog Policy.', 'en' => 'PO create: supplier required; catalog/non-catalog policy.'],
                    'staffNeedToKnow' => ['de' => 'Buyers: Keine PO ohne Supplier.', 'en' => 'Buyers: No PO without supplier.'],
                    'checks' => ['de' => 'supplier_system_id IS NULL on PO WHERE status NOT IN (\'Composing\',\'Canceled\')', 'en' => 'supplier_system_id IS NULL on PO WHERE status NOT IN (\'Composing\',\'Canceled\')'],
                    'fixInSource' => ['de' => 'Return / change PO; supplier master match.', 'en' => 'Return / change PO; supplier master match.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown supplier dim.', 'en' => 'Quarantine; Unknown supplier dim.'],
                ],
                [
                    'id' => 'ariba-invoice-po-amount-mismatch',
                    'priority' => 'high',
                    'title' => ['de' => 'Invoice Amount ≠ PO Amount', 'en' => 'Invoice amount mismatch vs PO'],
                    'problem' => ['de' => 'Invoice amount stark abweichend von PO verzerrt Accrual und Match Rates.', 'en' => 'Invoice amount far from PO distorts accrual and match rates.'],
                    'prevent' => ['de' => 'Tolerance Rules; 3-way Match Policy.', 'en' => 'Tolerance rules; 3-way match policy.'],
                    'staffNeedToKnow' => ['de' => 'AP: Abweichungen über Tolerance eskalieren.', 'en' => 'AP: Escalate variances above tolerance.'],
                    'checks' => ['de' => 'ABS(invoice_amount - po_amount) / NULLIF(po_amount,0) > tolerance_pct', 'en' => 'ABS(invoice_amount - po_amount) / NULLIF(po_amount,0) > tolerance_pct'],
                    'fixInSource' => ['de' => 'Exception handling in Ariba; change order or credit.', 'en' => 'Exception handling in Ariba; change order or credit.'],
                    'fixInWarehouse' => ['de' => 'Flag mismatch; separate matched vs exception KPIs.', 'en' => 'Flag mismatch; separate matched vs exception KPIs.'],
                ],
                [
                    'id' => 'ariba-invoice-no-po',
                    'priority' => 'high',
                    'title' => ['de' => 'Invoice ohne PO (wenn Policy Pflicht)', 'en' => 'Invoice without PO when policy requires'],
                    'problem' => ['de' => 'Non-PO Invoices trotz Policy erhöhen Maverick Spend und Audit-Risiko.', 'en' => 'Non-PO invoices despite policy increase maverick spend and audit risk.'],
                    'prevent' => ['de' => 'Invoice Exception Types steuern; Non-PO Allowlist eng halten.', 'en' => 'Control invoice exception types; keep non-PO allowlist tight.'],
                    'staffNeedToKnow' => ['de' => 'AP/Buyers: PO-first Policy einhalten.', 'en' => 'AP/buyers: Follow PO-first policy.'],
                    'checks' => ['de' => 'po_number IS NULL AND non_po_allowed = FALSE', 'en' => 'po_number IS NULL AND non_po_allowed = FALSE'],
                    'fixInSource' => ['de' => 'Reject or route exception; create PO retrospectively if allowed.', 'en' => 'Reject or route exception; create PO retrospectively if allowed.'],
                    'fixInWarehouse' => ['de' => 'Flag maverick; exclude from compliant spend.', 'en' => 'Flag maverick; exclude from compliant spend.'],
                ],
                [
                    'id' => 'ariba-commodity-missing',
                    'priority' => 'medium',
                    'title' => ['de' => 'Line ohne Commodity Code', 'en' => 'Line without commodity code'],
                    'problem' => ['de' => 'Fehlende Commodity Codes brechen Category Spend und Taxonomy Reports.', 'en' => 'Missing commodity codes break category spend and taxonomy reports.'],
                    'prevent' => ['de' => 'Commodity required on line; catalog mapping.', 'en' => 'Commodity required on line; catalog mapping.'],
                    'staffNeedToKnow' => ['de' => 'Buyers: Commodity immer setzen.', 'en' => 'Buyers: Always set commodity.'],
                    'checks' => ['de' => 'commodity_code IS NULL on PO/invoice line', 'en' => 'commodity_code IS NULL on PO/invoice line'],
                    'fixInSource' => ['de' => 'Catalog enrichment; required field on requisition.', 'en' => 'Catalog enrichment; required field on requisition.'],
                    'fixInWarehouse' => ['de' => 'Unknown commodity bucket; refresh taxonomy dim.', 'en' => 'Unknown commodity bucket; refresh taxonomy dim.'],
                ],
                [
                    'id' => 'ariba-status-date-invalid',
                    'priority' => 'medium',
                    'title' => ['de' => 'Document Status Date ungültig', 'en' => 'Invalid document status date'],
                    'problem' => ['de' => 'ordered_at > invoiced_at oder NULL Status Dates machen Cycle-Time kaputt.', 'en' => 'ordered_at > invoiced_at or NULL status dates break cycle time.'],
                    'prevent' => ['de' => 'Document Status Flows dokumentieren; keine manuellen Timestamp Hacks.', 'en' => 'Document status flows; no manual timestamp hacks.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Status Flows und Timestamps konsistent halten.', 'en' => 'Admins: Keep status flows and timestamps consistent.'],
                    'checks' => ['de' => 'invoiced_at < ordered_at OR ordered_at IS NULL on Ordered docs', 'en' => 'invoiced_at < ordered_at OR ordered_at IS NULL on Ordered docs'],
                    'fixInSource' => ['de' => 'Review document history; correct in Ariba.', 'en' => 'Review document history; correct in Ariba.'],
                    'fixInWarehouse' => ['de' => 'Flag invalid dates; null cycle metrics.', 'en' => 'Flag invalid dates; null cycle metrics.'],
                ],
                [
                    'id' => 'ariba-duplicate-supplier',
                    'priority' => 'medium',
                    'title' => ['de' => 'Supplier-Duplikate im Master', 'en' => 'Duplicate suppliers in master'],
                    'problem' => ['de' => 'Mehrere Supplier System IDs für denselben Vendor verzerren Spend Consolidation.', 'en' => 'Multiple supplier system ids for the same vendor distort spend consolidation.'],
                    'prevent' => ['de' => 'Supplier Master Governance; ERP vendor id unique.', 'en' => 'Supplier master governance; unique ERP vendor id.'],
                    'staffNeedToKnow' => ['de' => 'Master Data: Vor Neuanlage bestehenden Supplier suchen.', 'en' => 'Master data: Search existing supplier before create.'],
                    'checks' => ['de' => 'COUNT(DISTINCT supplier_system_id) GROUP BY erp_vendor_id HAVING COUNT > 1', 'en' => 'COUNT(DISTINCT supplier_system_id) GROUP BY erp_vendor_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Merge / deactivate duplicates in Supplier Management.', 'en' => 'Merge / deactivate duplicates in Supplier Management.'],
                    'fixInWarehouse' => ['de' => 'Golden supplier_system_id; merge map.', 'en' => 'Golden supplier_system_id; merge map.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'ariba-supplier-dup',
                    'entity' => 'Supplier',
                    'title' => ['de' => 'Supplier-Duplikate / ERP Link', 'en' => 'Supplier duplicates / ERP link'],
                    'matchKeys' => ['supplier_system_id', 'erp_vendor_id', 'tax_id hash', 'name'],
                    'preventInSource' => ['de' => 'SM as governed master; unique ERP vendor link.', 'en' => 'SM as governed master; unique ERP vendor link.'],
                    'resolveInWarehouse' => ['de' => 'Golden supplier_system_id; ERP vendor merge map.', 'en' => 'Golden supplier_system_id; ERP vendor merge map.'],
                    'survivorship' => ['de' => 'Aktiver Supplier mit ERP Link und neuester PO gewinnt.', 'en' => 'Active supplier with ERP link and latest PO wins.'],
                ],
                [
                    'id' => 'ariba-commodity-tax',
                    'entity' => 'Commodity',
                    'title' => ['de' => 'Commodity Taxonomy Drift', 'en' => 'Commodity taxonomy drift'],
                    'matchKeys' => ['commodity_code', 'UNSPSC', 'internal category'],
                    'preventInSource' => ['de' => 'Controlled taxonomy; catalog mapping governance.', 'en' => 'Controlled taxonomy; catalog mapping governance.'],
                    'resolveInWarehouse' => ['de' => 'Canonical commodity_code; SCD2 taxonomy.', 'en' => 'Canonical commodity_code; SCD2 taxonomy.'],
                    'survivorship' => ['de' => 'Aktueller Taxonomy-Stand gewinnt über Legacy Codes.', 'en' => 'Current taxonomy wins over legacy codes.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'ariba-match-tolerance',
                    'area' => ['de' => 'Invoice → Tolerances / Matching', 'en' => 'Invoice → Tolerances / Matching'],
                    'setting' => ['de' => 'PO-Invoice Tolerance und 3-way Match Rules', 'en' => 'PO-invoice tolerance and 3-way match rules'],
                    'why' => ['de' => 'Match Rates und Exception KPIs werden steuerbar.', 'en' => 'Match rates and exception KPIs become controllable.'],
                    'how' => ['de' => 'Configure tolerances; document exception types.', 'en' => 'Configure tolerances; document exception types.'],
                ],
                [
                    'id' => 'ariba-supplier-master',
                    'area' => ['de' => 'Supplier Management → Supplier master', 'en' => 'Supplier Management → Supplier master'],
                    'setting' => ['de' => 'Unique ERP Vendor Link und Duplicate Prevention', 'en' => 'Unique ERP vendor link and duplicate prevention'],
                    'why' => ['de' => 'Spend Consolidation bleibt möglich.', 'en' => 'Spend consolidation stays possible.'],
                    'how' => ['de' => 'SM duplicate checks; deactivate orphans.', 'en' => 'SM duplicate checks; deactivate orphans.'],
                ],
                [
                    'id' => 'ariba-commodity-required',
                    'area' => ['de' => 'Commodity codes / catalog', 'en' => 'Commodity codes / catalog'],
                    'setting' => ['de' => 'Commodity required on requisition/PO lines', 'en' => 'Commodity required on requisition/PO lines'],
                    'why' => ['de' => 'Category Spend und Taxonomy Reports bleiben nutzbar.', 'en' => 'Category spend and taxonomy reports stay usable.'],
                    'how' => ['de' => 'Field required; catalog default commodity.', 'en' => 'Field required; catalog default commodity.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'ariba-realm-config',
                    'kind' => ['de' => 'Realm config', 'en' => 'Realm config'],
                    'where' => ['de' => 'Ariba Admin → Realm parameters / site configuration', 'en' => 'Ariba Admin → Realm parameters / site configuration'],
                    'how' => ['de' => 'Realm Parameters und Feature Toggles dokumentieren.', 'en' => 'Document realm parameters and feature toggles.'],
                    'useFor' => ['de' => 'Governance baseline, extract scope, status definitions.', 'en' => 'Governance baseline, extract scope, status definitions.'],
                    'watchouts' => ['de' => 'Sandbox vs Prod Realm — Config nicht blind mergen.', 'en' => 'Sandbox vs prod realm — do not merge config blindly.'],
                ],
                [
                    'id' => 'ariba-commodity-taxonomy',
                    'kind' => ['de' => 'Commodity taxonomy', 'en' => 'Commodity taxonomy'],
                    'where' => ['de' => 'Commodity code hierarchy / catalog commodity mapping', 'en' => 'Commodity code hierarchy / catalog commodity mapping'],
                    'how' => ['de' => 'Taxonomy export; map UNSPSC/internal codes.', 'en' => 'Taxonomy export; map UNSPSC/internal codes.'],
                    'useFor' => ['de' => 'Category dims, spend classification, DQ.', 'en' => 'Category dims, spend classification, DQ.'],
                    'watchouts' => ['de' => 'Custom Codes drift ohne Governance.', 'en' => 'Custom codes drift without governance.'],
                ],
                [
                    'id' => 'ariba-supplier-master-meta',
                    'kind' => ['de' => 'Supplier master', 'en' => 'Supplier master'],
                    'where' => ['de' => 'Supplier Management / Supplier data enrichment', 'en' => 'Supplier Management / Supplier data enrichment'],
                    'how' => ['de' => 'Supplier fields und ERP links inventarisieren; Contacts PII taggen.', 'en' => 'Inventory supplier fields and ERP links; tag contact PII.'],
                    'useFor' => ['de' => 'Vendor dim, MDM match keys, PII allowlist.', 'en' => 'Vendor dim, MDM match keys, PII allowlist.'],
                    'watchouts' => ['de' => 'Contact emails — nicht in öffentlichen Marts.', 'en' => 'Contact emails — not in public marts.'],
                ],
                [
                    'id' => 'ariba-document-status',
                    'kind' => ['de' => 'Document status flows', 'en' => 'Document status flows'],
                    'where' => ['de' => 'Document types → status / approval flows (PO, Invoice, Contract)', 'en' => 'Document types → status / approval flows (PO, Invoice, Contract)'],
                    'how' => ['de' => 'Status Maps und Transition Rules exportieren.', 'en' => 'Export status maps and transition rules.'],
                    'useFor' => ['de' => 'Cycle-time definition, open vs closed filters, DQ dates.', 'en' => 'Cycle-time definition, open vs closed filters, DQ dates.'],
                    'watchouts' => ['de' => 'Status Labels unterscheiden sich je Document Type.', 'en' => 'Status labels differ by document type.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'coupa' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'coupa-invoice-no-po-policy',
                    'priority' => 'high',
                    'title' => ['de' => 'Invoice ohne PO trotz Policy', 'en' => 'Invoice without PO when policy requires'],
                    'problem' => ['de' => 'Invoices ohne PO trotz Policy sind Maverick Spend und Audit-Risiko.', 'en' => 'Invoices without PO despite policy are maverick spend and audit risk.'],
                    'prevent' => ['de' => 'Invoice Policy: PO required; Exception Types eng allowlisten.', 'en' => 'Invoice policy: PO required; tightly allowlist exception types.'],
                    'staffNeedToKnow' => ['de' => 'AP: PO-first — Non-PO nur mit Freigabe.', 'en' => 'AP: PO-first — non-PO only with approval.'],
                    'checks' => ['de' => 'po_id IS NULL AND requires_po = TRUE AND status NOT IN (\'draft\',\'voided\')', 'en' => 'po_id IS NULL AND requires_po = TRUE AND status NOT IN (\'draft\',\'voided\')'],
                    'fixInSource' => ['de' => 'Reject / hold invoice; create PO if process allows.', 'en' => 'Reject / hold invoice; create PO if process allows.'],
                    'fixInWarehouse' => ['de' => 'Flag maverick_spend; separate compliant KPI.', 'en' => 'Flag maverick_spend; separate compliant KPI.'],
                ],
                [
                    'id' => 'coupa-maverick-spend',
                    'priority' => 'high',
                    'title' => ['de' => 'Maverick Spend Indikatoren', 'en' => 'Maverick spend indicators'],
                    'problem' => ['de' => 'Off-contract / Non-Catalog Spend ohne Flag verzerrt Compliance Rates.', 'en' => 'Off-contract / non-catalog spend without flags distorts compliance rates.'],
                    'prevent' => ['de' => 'Catalog-first Policy; Contract Link required where applicable.', 'en' => 'Catalog-first policy; contract link required where applicable.'],
                    'staffNeedToKnow' => ['de' => 'Buyers: Catalog/Contract bevorzugen — Maverick tracken.', 'en' => 'Buyers: Prefer catalog/contract — track maverick.'],
                    'checks' => ['de' => '(is_non_catalog = TRUE OR contract_id IS NULL) AND spend_amount > 0 AND status = approved', 'en' => '(is_non_catalog = TRUE OR contract_id IS NULL) AND spend_amount > 0 AND status = approved'],
                    'fixInSource' => ['de' => 'Guided buying; contract compliance rules.', 'en' => 'Guided buying; contract compliance rules.'],
                    'fixInWarehouse' => ['de' => 'maverick_flag; compliance rate denominator documented.', 'en' => 'maverick_flag; compliance rate denominator documented.'],
                ],
                [
                    'id' => 'coupa-invoice-amount-mismatch',
                    'priority' => 'high',
                    'title' => ['de' => 'Invoice vs PO Amount Mismatch', 'en' => 'Invoice vs PO amount mismatch'],
                    'problem' => ['de' => 'Invoice totals außerhalb Tolerance brechen Match und Accrual.', 'en' => 'Invoice totals outside tolerance break match and accrual.'],
                    'prevent' => ['de' => 'Matching Tolerances; change order process.', 'en' => 'Matching tolerances; change order process.'],
                    'staffNeedToKnow' => ['de' => 'AP: Variances über Tolerance klären vor Payment.', 'en' => 'AP: Resolve variances above tolerance before payment.'],
                    'checks' => ['de' => 'ABS(invoice_total - po_total) / NULLIF(po_total,0) > tolerance_pct', 'en' => 'ABS(invoice_total - po_total) / NULLIF(po_total,0) > tolerance_pct'],
                    'fixInSource' => ['de' => 'Coupa matching exceptions; credit / change order.', 'en' => 'Coupa matching exceptions; credit / change order.'],
                    'fixInWarehouse' => ['de' => 'Flag mismatch; split matched vs exception facts.', 'en' => 'Flag mismatch; split matched vs exception facts.'],
                ],
                [
                    'id' => 'coupa-po-no-account',
                    'priority' => 'high',
                    'title' => ['de' => 'PO Line ohne Chart of Accounts', 'en' => 'PO line without chart of accounts'],
                    'problem' => ['de' => 'Lines ohne Account/Segment lassen Spend nicht nach GL schneiden.', 'en' => 'Lines without account/segment cannot slice spend by GL.'],
                    'prevent' => ['de' => 'Account required on line; default from commodity/requester.', 'en' => 'Account required on line; default from commodity/requester.'],
                    'staffNeedToKnow' => ['de' => 'Requesters: Account Coding immer setzen.', 'en' => 'Requesters: Always set account coding.'],
                    'checks' => ['de' => 'account_code IS NULL on approved PO line', 'en' => 'account_code IS NULL on approved PO line'],
                    'fixInSource' => ['de' => 'Form validation; return for coding.', 'en' => 'Form validation; return for coding.'],
                    'fixInWarehouse' => ['de' => 'Unknown account dim; exclude from GL KPIs.', 'en' => 'Unknown account dim; exclude from GL KPIs.'],
                ],
                [
                    'id' => 'coupa-approval-orphan',
                    'priority' => 'medium',
                    'title' => ['de' => 'Approved Doc ohne Approver Chain', 'en' => 'Approved doc without approver chain'],
                    'problem' => ['de' => 'Approved ohne Approver History schwächt Audit und Cycle-Time.', 'en' => 'Approved without approver history weakens audit and cycle time.'],
                    'prevent' => ['de' => 'Approval Chains konfigurieren; Auto-Approve eng limitieren.', 'en' => 'Configure approval chains; tightly limit auto-approve.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Approval Chains für Spend Limits pflegen.', 'en' => 'Admins: Maintain approval chains for spend limits.'],
                    'checks' => ['de' => 'status = approved AND approver_count = 0 AND NOT auto_approve_policy', 'en' => 'status = approved AND approver_count = 0 AND NOT auto_approve_policy'],
                    'fixInSource' => ['de' => 'Fix approval chain config; re-route open docs.', 'en' => 'Fix approval chain config; re-route open docs.'],
                    'fixInWarehouse' => ['de' => 'Flag missing approval; null SLA metrics.', 'en' => 'Flag missing approval; null SLA metrics.'],
                ],
                [
                    'id' => 'coupa-commodity-missing',
                    'priority' => 'medium',
                    'title' => ['de' => 'Line ohne Commodity', 'en' => 'Line without commodity'],
                    'problem' => ['de' => 'Fehlende Commodity bricht Category Spend.', 'en' => 'Missing commodity breaks category spend.'],
                    'prevent' => ['de' => 'Commodity required; catalog defaults.', 'en' => 'Commodity required; catalog defaults.'],
                    'staffNeedToKnow' => ['de' => 'Buyers: Commodity auf jeder Line.', 'en' => 'Buyers: Commodity on every line.'],
                    'checks' => ['de' => 'commodity_id IS NULL on approved line', 'en' => 'commodity_id IS NULL on approved line'],
                    'fixInSource' => ['de' => 'Required field; catalog enrichment.', 'en' => 'Required field; catalog enrichment.'],
                    'fixInWarehouse' => ['de' => 'Unknown commodity; refresh taxonomy.', 'en' => 'Unknown commodity; refresh taxonomy.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'coupa-supplier-dup',
                    'entity' => 'Supplier',
                    'title' => ['de' => 'Supplier-Duplikate', 'en' => 'Supplier duplicates'],
                    'matchKeys' => ['supplier id', 'number', 'tax-id hash', 'name'],
                    'preventInSource' => ['de' => 'Supplier create governance; unique number/tax id.', 'en' => 'Supplier create governance; unique number/tax id.'],
                    'resolveInWarehouse' => ['de' => 'Golden supplier id; merge map.', 'en' => 'Golden supplier id; merge map.'],
                    'survivorship' => ['de' => 'Aktiver Supplier mit neuesster Invoice gewinnt.', 'en' => 'Active supplier with latest invoice wins.'],
                ],
                [
                    'id' => 'coupa-user-dup',
                    'entity' => 'User',
                    'title' => ['de' => 'User-Duplikate / Deactivated', 'en' => 'User duplicates / deactivated'],
                    'matchKeys' => ['user id', 'login', 'email', 'employee-number'],
                    'preventInSource' => ['de' => 'HR/SSO as source of truth; deactivate instead of recreate.', 'en' => 'HR/SSO as source of truth; deactivate instead of recreate.'],
                    'resolveInWarehouse' => ['de' => 'Golden user id; email-hash merge map.', 'en' => 'Golden user id; email-hash merge map.'],
                    'survivorship' => ['de' => 'Aktiver User mit neuester Activity gewinnt.', 'en' => 'Active user with latest activity wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'coupa-invoice-po-policy',
                    'area' => ['de' => 'Setup → Policies / Invoice', 'en' => 'Setup → Policies / Invoice'],
                    'setting' => ['de' => 'PO required Policy und Non-PO Exceptions', 'en' => 'PO required policy and non-PO exceptions'],
                    'why' => ['de' => 'Maverick Spend wird messbar und steuerbar.', 'en' => 'Maverick spend becomes measurable and controllable.'],
                    'how' => ['de' => 'Policy config; exception allowlist; train AP.', 'en' => 'Policy config; exception allowlist; train AP.'],
                ],
                [
                    'id' => 'coupa-approval-chains',
                    'area' => ['de' => 'Setup → Approvals', 'en' => 'Setup → Approvals'],
                    'setting' => ['de' => 'Approval Chains nach Amount / Commodity', 'en' => 'Approval chains by amount / commodity'],
                    'why' => ['de' => 'Audit Trail und Cycle-Time bleiben belastbar.', 'en' => 'Audit trail and cycle time stay reliable.'],
                    'how' => ['de' => 'Configure chains; limit auto-approve.', 'en' => 'Configure chains; limit auto-approve.'],
                ],
                [
                    'id' => 'coupa-coa-required',
                    'area' => ['de' => 'Setup → Chart of Accounts', 'en' => 'Setup → Chart of Accounts'],
                    'setting' => ['de' => 'Account Segments required on transactional lines', 'en' => 'Account segments required on transactional lines'],
                    'why' => ['de' => 'GL Spend Schnitte bleiben möglich.', 'en' => 'GL spend slices stay possible.'],
                    'how' => ['de' => 'COA validation; defaults from commodity/user.', 'en' => 'COA validation; defaults from commodity/user.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'coupa-coa',
                    'kind' => ['de' => 'Chart of accounts', 'en' => 'Chart of accounts'],
                    'where' => ['de' => 'Setup → Chart of Accounts / Account segments', 'en' => 'Setup → Chart of Accounts / Account segments'],
                    'how' => ['de' => 'COA Segments und Validierungen exportieren.', 'en' => 'Export COA segments and validations.'],
                    'useFor' => ['de' => 'GL dims, coding DQ, ERP join keys.', 'en' => 'GL dims, coding DQ, ERP join keys.'],
                    'watchouts' => ['de' => 'Segment Combos können ERP-Constraints haben.', 'en' => 'Segment combos may have ERP constraints.'],
                ],
                [
                    'id' => 'coupa-approval-chains-meta',
                    'kind' => ['de' => 'Approval chains', 'en' => 'Approval chains'],
                    'where' => ['de' => 'Setup → Approvals / Approval chains', 'en' => 'Setup → Approvals / Approval chains'],
                    'how' => ['de' => 'Chains und Conditions dokumentieren; User-IDs nicht in klaren Marts.', 'en' => 'Document chains and conditions; keep user ids out of cleartext marts.'],
                    'useFor' => ['de' => 'SLA defs, approver counts, audit readiness.', 'en' => 'SLA defs, approver counts, audit readiness.'],
                    'watchouts' => ['de' => 'Approval Comments sind PII — Bodies default skip.', 'en' => 'Approval comments are PII — skip bodies by default.'],
                ],
                [
                    'id' => 'coupa-commodity-taxonomy',
                    'kind' => ['de' => 'Commodity taxonomy', 'en' => 'Commodity taxonomy'],
                    'where' => ['de' => 'Setup → Commodities', 'en' => 'Setup → Commodities'],
                    'how' => ['de' => 'Commodity Hierarchy exportieren; map to UNSPSC if used.', 'en' => 'Export commodity hierarchy; map to UNSPSC if used.'],
                    'useFor' => ['de' => 'Category spend dims, guided buying, DQ.', 'en' => 'Category spend dims, guided buying, DQ.'],
                    'watchouts' => ['de' => 'Inactive Commodities in historischen Lines behalten.', 'en' => 'Keep inactive commodities on historical lines.'],
                ],
                [
                    'id' => 'coupa-api-oauth',
                    'kind' => ['de' => 'API / OAuth apps', 'en' => 'API / OAuth apps'],
                    'where' => ['de' => 'Setup → Integrations → OAuth2 / API clients', 'en' => 'Setup → Integrations → OAuth2 / API clients'],
                    'how' => ['de' => 'Scopes inventarisieren; Extract Allowlist versionieren.', 'en' => 'Inventory scopes; version extract allowlist.'],
                    'useFor' => ['de' => 'Extract design, least privilege, PII scan.', 'en' => 'Extract design, least privilege, PII scan.'],
                    'watchouts' => ['de' => 'Attachment scopes ziehen Binaries — default avoid.', 'en' => 'Attachment scopes pull binaries — avoid by default.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],
];
