<?php

/**
 * Wave 3 quality overlays — Collab source-native DQ, MDM, metadata guides.
 *
 * @return array<string, array<string, mixed>>
 */

return [
    'jira' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'jira-issue-no-assignee',
                    'priority' => 'high',
                    'title' => ['de' => 'Offenes Issue ohne Assignee', 'en' => 'Open issue without assignee'],
                    'problem' => ['de' => 'Offene Issues ohne assignee lassen Workload und Cycle-Time nicht nach Owner schneiden.', 'en' => 'Open issues without assignee cannot slice workload and cycle time by owner.'],
                    'prevent' => ['de' => 'Workflow: Assignee Pflicht vor In Progress; Board-Policy.', 'en' => 'Workflow: assignee required before In Progress; board policy.'],
                    'staffNeedToKnow' => ['de' => 'Delivery: Kein Start ohne Assignee — Ownership klären.', 'en' => 'Delivery: Do not start without assignee — clarify ownership.'],
                    'checks' => ['de' => 'assignee IS NULL AND statusCategory != Done', 'en' => 'assignee IS NULL AND statusCategory != Done'],
                    'fixInSource' => ['de' => 'Workflow validator; required assignee on transition.', 'en' => 'Workflow validator; required assignee on transition.'],
                    'fixInWarehouse' => ['de' => 'Unknown-assignee dim; exclude from owner KPIs.', 'en' => 'Unknown-assignee dim; exclude from owner KPIs.'],
                ],
                [
                    'id' => 'jira-issue-no-project',
                    'priority' => 'high',
                    'title' => ['de' => 'Issue ohne Project', 'en' => 'Issue without project'],
                    'problem' => ['de' => 'Issues ohne projectKey brechen Portfolio- und Team-Reports.', 'en' => 'Issues without projectKey break portfolio and team reports.'],
                    'prevent' => ['de' => 'Create Screen: Project immer gesetzt; API Create validieren.', 'en' => 'Create screen: project always set; validate API create.'],
                    'staffNeedToKnow' => ['de' => 'Jira: Jedes Issue gehört zu einem Project.', 'en' => 'Jira: Every issue belongs to a project.'],
                    'checks' => ['de' => 'projectKey IS NULL OR projectId IS NULL', 'en' => 'projectKey IS NULL OR projectId IS NULL'],
                    'fixInSource' => ['de' => 'Required project on create; block API without project.', 'en' => 'Required project on create; block API without project.'],
                    'fixInWarehouse' => ['de' => 'Quarantine rows; exclude from portfolio KPIs.', 'en' => 'Quarantine rows; exclude from portfolio KPIs.'],
                ],
                [
                    'id' => 'jira-resolved-before-created',
                    'priority' => 'high',
                    'title' => ['de' => 'Resolution vor Created', 'en' => 'Resolution before created'],
                    'problem' => ['de' => 'resolved < created macht Lead-/Cycle-Time unbrauchbar.', 'en' => 'resolved < created makes lead/cycle time unusable.'],
                    'prevent' => ['de' => 'Keine manuellen Datum-Overrides ohne Prozess; Migration dokumentieren.', 'en' => 'No manual date overrides without process; document migrations.'],
                    'staffNeedToKnow' => ['de' => 'Ops: Resolution Date nie vor Created setzen.', 'en' => 'Ops: Never set resolution date before created.'],
                    'checks' => ['de' => 'resolutiondate < created', 'en' => 'resolutiondate < created'],
                    'fixInSource' => ['de' => 'Automation / validator on resolution fields.', 'en' => 'Automation / validator on resolution fields.'],
                    'fixInWarehouse' => ['de' => 'Flag invalid dates; null cycle metrics.', 'en' => 'Flag invalid dates; null cycle metrics.'],
                ],
                [
                    'id' => 'jira-done-no-resolution',
                    'priority' => 'medium',
                    'title' => ['de' => 'Done ohne Resolution', 'en' => 'Done without resolution'],
                    'problem' => ['de' => 'Status Done ohne resolution verzerrt Throughput und Outcome-Schnitte.', 'en' => 'Status Done without resolution distorts throughput and outcome slices.'],
                    'prevent' => ['de' => 'Workflow: Resolution Pflicht beim Done-Transition.', 'en' => 'Workflow: resolution required on Done transition.'],
                    'staffNeedToKnow' => ['de' => 'Delivery: Done immer mit Resolution (Done/Won\'t Do/…).', 'en' => 'Delivery: Done always with resolution (Done/Won\'t Do/…).'],
                    'checks' => ['de' => 'statusCategory = Done AND resolution IS NULL', 'en' => 'statusCategory = Done AND resolution IS NULL'],
                    'fixInSource' => ['de' => 'Post-function / validator sets resolution.', 'en' => 'Post-function / validator sets resolution.'],
                    'fixInWarehouse' => ['de' => 'Map to Unknown resolution; separate KPI.', 'en' => 'Map to Unknown resolution; separate KPI.'],
                ],
                [
                    'id' => 'jira-story-points-null-sprint',
                    'priority' => 'medium',
                    'title' => ['de' => 'Sprint-Issue ohne Story Points', 'en' => 'Sprint issue without story points'],
                    'problem' => ['de' => 'Aktive Sprint-Items ohne Story Points brechen Velocity und Commitment.', 'en' => 'Active sprint items without story points break velocity and commitment.'],
                    'prevent' => ['de' => 'Definition of Ready: Story Points vor Sprint Start.', 'en' => 'Definition of Ready: story points before sprint start.'],
                    'staffNeedToKnow' => ['de' => 'Scrum: Keine Commitment-Items ohne Schätzung.', 'en' => 'Scrum: No commitment items without estimate.'],
                    'checks' => ['de' => 'storyPoints IS NULL AND sprint IS NOT NULL AND statusCategory != Done', 'en' => 'storyPoints IS NULL AND sprint IS NOT NULL AND statusCategory != Done'],
                    'fixInSource' => ['de' => 'Board filter / automation alert; required field on issue type.', 'en' => 'Board filter / automation alert; required field on issue type.'],
                    'fixInWarehouse' => ['de' => 'Exclude from velocity or flag unestimated.', 'en' => 'Exclude from velocity or flag unestimated.'],
                ],
                [
                    'id' => 'jira-duplicate-external-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte External Id Custom Field', 'en' => 'Duplicate external id custom field'],
                    'problem' => ['de' => 'Mehrere Issues mit gleicher External Id verzerren Cross-System-Joins und DSDR.', 'en' => 'Multiple issues with same external id distort cross-system joins and DSDR.'],
                    'prevent' => ['de' => 'Unique External Id Policy; Import-Dedup.', 'en' => 'Unique external id policy; import dedup.'],
                    'staffNeedToKnow' => ['de' => 'Integrationen: External Id eindeutig halten.', 'en' => 'Integrations: Keep external id unique.'],
                    'checks' => ['de' => 'COUNT(DISTINCT issue_key) GROUP BY external_id HAVING COUNT > 1', 'en' => 'COUNT(DISTINCT issue_key) GROUP BY external_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Automation uniqueness check; merge workflow.', 'en' => 'Automation uniqueness check; merge workflow.'],
                    'fixInWarehouse' => ['de' => 'Golden issue key; merge map table.', 'en' => 'Golden issue key; merge map table.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'jira-user-dup',
                    'entity' => 'User / accountId',
                    'title' => ['de' => 'User-Duplikate / Site-Transfers', 'en' => 'User duplicates / site transfers'],
                    'matchKeys' => ['accountId', 'emailAddress', 'displayName + site'],
                    'preventInSource' => ['de' => 'Atlassian Account als Source of Truth; keine lokalen Doppel-Accounts.', 'en' => 'Atlassian account as source of truth; no local duplicate accounts.'],
                    'resolveInWarehouse' => ['de' => 'Golden accountId; merge map für Legacy-User-Keys.', 'en' => 'Golden accountId; merge map for legacy user keys.'],
                    'survivorship' => ['de' => 'Aktiver accountId mit neuester Activity gewinnt.', 'en' => 'Active accountId with latest activity wins.'],
                ],
                [
                    'id' => 'jira-issue-external',
                    'entity' => 'Issue',
                    'title' => ['de' => 'Issue vs External Ticket Id', 'en' => 'Issue vs external ticket id'],
                    'matchKeys' => ['issue key', 'custom external id', 'project + summary hash'],
                    'preventInSource' => ['de' => 'Unique custom field; import governance.', 'en' => 'Unique custom field; import governance.'],
                    'resolveInWarehouse' => ['de' => 'Canonical issue_key via external id map.', 'en' => 'Canonical issue_key via external id map.'],
                    'survivorship' => ['de' => 'Prod-Project Issue gewinnt über Import-Stub.', 'en' => 'Prod-project issue wins over import stub.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'jira-required-assignee',
                    'area' => ['de' => 'Project settings → Workflows', 'en' => 'Project settings → Workflows'],
                    'setting' => ['de' => 'Assignee Pflicht vor In Progress', 'en' => 'Assignee required before In Progress'],
                    'why' => ['de' => 'Schließt Owner-Lücken für Workload-KPIs.', 'en' => 'Closes owner gaps for workload KPIs.'],
                    'how' => ['de' => 'Workflow validator auf Transition; test in Sandbox.', 'en' => 'Workflow validator on transition; test in sandbox.'],
                ],
                [
                    'id' => 'jira-field-config',
                    'area' => ['de' => 'Issues → Custom fields / Field configuration', 'en' => 'Issues → Custom fields / Field configuration'],
                    'setting' => ['de' => 'Story Points / External Id für relevante Issue Types', 'en' => 'Story points / external id for relevant issue types'],
                    'why' => ['de' => 'Stabilisiert Velocity und Cross-System-Joins.', 'en' => 'Stabilizes velocity and cross-system joins.'],
                    'how' => ['de' => 'Field configuration scheme; required where needed.', 'en' => 'Field configuration scheme; required where needed.'],
                ],
                [
                    'id' => 'jira-api-field-allowlist',
                    'area' => ['de' => 'REST API → /rest/api/3/field', 'en' => 'REST API → /rest/api/3/field'],
                    'setting' => ['de' => 'Field-Allowlist für Extract dokumentieren', 'en' => 'Document field allowlist for extract'],
                    'why' => ['de' => 'Verhindert PII-Sprawl und Schema-Drift.', 'en' => 'Prevents PII sprawl and schema drift.'],
                    'how' => ['de' => 'Field catalog exportieren; IDs in Git versionieren.', 'en' => 'Export field catalog; version IDs in Git.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'jira-issue-fields-admin',
                    'kind' => ['de' => 'Issue fields admin', 'en' => 'Issue fields admin'],
                    'where' => ['de' => 'Jira Settings → Issues → Custom fields / Field configurations', 'en' => 'Jira Settings → Issues → Custom fields / Field configurations'],
                    'how' => ['de' => 'UI browse; Field IDs und Screens dokumentieren.', 'en' => 'UI browse; document field IDs and screens.'],
                    'useFor' => ['de' => 'Feld-Inventar, PII-Tags, Load-Allowlist, DQ-Checks.', 'en' => 'Field inventory, PII tags, load allowlist, DQ checks.'],
                    'watchouts' => ['de' => 'Custom Field IDs (customfield_*) unterscheiden sich pro Site.', 'en' => 'Custom field IDs (customfield_*) differ per site.'],
                ],
                [
                    'id' => 'jira-workflows',
                    'kind' => ['de' => 'Workflows', 'en' => 'Workflows'],
                    'where' => ['de' => 'Project settings → Workflows; Jira Settings → Workflows', 'en' => 'Project settings → Workflows; Jira Settings → Workflows'],
                    'how' => ['de' => 'Status/Transitions und Validatoren exportieren.', 'en' => 'Export statuses/transitions and validators.'],
                    'useFor' => ['de' => 'Status-Maps, Cycle-Time Definition, Required-Field Rules.', 'en' => 'Status maps, cycle-time definition, required-field rules.'],
                    'watchouts' => ['de' => 'Mehrere Schemes pro Project — nicht blind mergen.', 'en' => 'Multiple schemes per project — do not merge blindly.'],
                ],
                [
                    'id' => 'jira-jql',
                    'kind' => ['de' => 'JQL', 'en' => 'JQL'],
                    'where' => ['de' => 'Filters / Advanced search; saved filters', 'en' => 'Filters / Advanced search; saved filters'],
                    'how' => ['de' => 'JQL für Extract-Scopes dokumentieren; nicht als Mart-SQL missbrauchen.', 'en' => 'Document JQL for extract scopes; do not misuse as mart SQL.'],
                    'useFor' => ['de' => 'Extract-Filter, Scope-Definition, Sanity Checks.', 'en' => 'Extract filters, scope definition, sanity checks.'],
                    'watchouts' => ['de' => 'Saved Filters ändern sich ohne Versionierung.', 'en' => 'Saved filters change without versioning.'],
                ],
                [
                    'id' => 'jira-rest-field',
                    'kind' => ['de' => 'REST API /rest/api/3/field', 'en' => 'REST API /rest/api/3/field'],
                    'where' => ['de' => 'GET /rest/api/3/field (+ createmeta where needed)', 'en' => 'GET /rest/api/3/field (+ createmeta where needed)'],
                    'how' => ['de' => 'Field catalog JSON speichern; custom vs system taggen.', 'en' => 'Store field catalog JSON; tag custom vs system.'],
                    'useFor' => ['de' => 'Extract-Design, Schema-Allowlist, PII-Scan.', 'en' => 'Extract design, schema allowlist, PII scan.'],
                    'watchouts' => ['de' => 'Permission-scoped fields — Extract-User sieht ggf. mehr/weniger.', 'en' => 'Permission-scoped fields — extract user may see more/less.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'confluence' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'conf-page-no-space',
                    'priority' => 'high',
                    'title' => ['de' => 'Page ohne Space', 'en' => 'Page without space'],
                    'problem' => ['de' => 'Pages ohne spaceId lassen Knowledge-KPIs nicht nach Space/Team schneiden.', 'en' => 'Pages without spaceId cannot slice knowledge KPIs by space/team.'],
                    'prevent' => ['de' => 'Create immer in Space-Kontext; API Create validieren.', 'en' => 'Always create in space context; validate API create.'],
                    'staffNeedToKnow' => ['de' => 'Autoren: Jede Page braucht einen Space.', 'en' => 'Authors: Every page needs a space.'],
                    'checks' => ['de' => 'spaceId IS NULL OR spaceKey IS NULL on page', 'en' => 'spaceId IS NULL OR spaceKey IS NULL on page'],
                    'fixInSource' => ['de' => 'Required space on create; block orphan content.', 'en' => 'Required space on create; block orphan content.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from space KPIs.', 'en' => 'Quarantine; exclude from space KPIs.'],
                ],
                [
                    'id' => 'conf-page-no-author',
                    'priority' => 'high',
                    'title' => ['de' => 'Page ohne Author', 'en' => 'Page without author'],
                    'problem' => ['de' => 'Content ohne authorId bricht Ownership- und Contribution-Reports.', 'en' => 'Content without authorId breaks ownership and contribution reports.'],
                    'prevent' => ['de' => 'Author aus Session/API-User; Import mit Mapping.', 'en' => 'Author from session/API user; import with mapping.'],
                    'staffNeedToKnow' => ['de' => 'Imports: Author immer mappen — nicht anonym lassen.', 'en' => 'Imports: Always map author — do not leave anonymous.'],
                    'checks' => ['de' => 'authorId IS NULL on current page version', 'en' => 'authorId IS NULL on current page version'],
                    'fixInSource' => ['de' => 'Import mapping; required creator on API.', 'en' => 'Import mapping; required creator on API.'],
                    'fixInWarehouse' => ['de' => 'Unknown-author dim; exclude from contribution KPIs.', 'en' => 'Unknown-author dim; exclude from contribution KPIs.'],
                ],
                [
                    'id' => 'conf-updated-before-created',
                    'priority' => 'medium',
                    'title' => ['de' => 'lastModified vor created', 'en' => 'lastModified before created'],
                    'problem' => ['de' => 'lastModified < created verfälscht Freshness und Edit-Cycle.', 'en' => 'lastModified < created distorts freshness and edit cycle.'],
                    'prevent' => ['de' => 'Migration Timestamps prüfen; keine manuellen Overrides.', 'en' => 'Validate migration timestamps; no manual overrides.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Created/Modified bei Migrationen konsistent halten.', 'en' => 'Admins: Keep created/modified consistent on migrations.'],
                    'checks' => ['de' => 'lastModified < created', 'en' => 'lastModified < created'],
                    'fixInSource' => ['de' => 'Fix on re-import; version history review.', 'en' => 'Fix on re-import; version history review.'],
                    'fixInWarehouse' => ['de' => 'Flag invalid dates; use created fallback.', 'en' => 'Flag invalid dates; use created fallback.'],
                ],
                [
                    'id' => 'conf-archived-still-current',
                    'priority' => 'medium',
                    'title' => ['de' => 'Archived Space mit „current“ Pages', 'en' => 'Archived space with current pages'],
                    'problem' => ['de' => 'Aktive Content-Counts aus archived Spaces verzerren Knowledge-Inventory.', 'en' => 'Active content counts from archived spaces distort knowledge inventory.'],
                    'prevent' => ['de' => 'Archive-Policy: Space Status pflegen; Content Status syncen.', 'en' => 'Archive policy: maintain space status; sync content status.'],
                    'staffNeedToKnow' => ['de' => 'Space Admins: Archive bedeutet out of active inventory.', 'en' => 'Space admins: Archive means out of active inventory.'],
                    'checks' => ['de' => 'spaceStatus = archived AND pageStatus = current', 'en' => 'spaceStatus = archived AND pageStatus = current'],
                    'fixInSource' => ['de' => 'Archive workflow updates content status.', 'en' => 'Archive workflow updates content status.'],
                    'fixInWarehouse' => ['de' => 'Exclude archived spaces from active inventory KPIs.', 'en' => 'Exclude archived spaces from active inventory KPIs.'],
                ],
                [
                    'id' => 'conf-orphan-label',
                    'priority' => 'low',
                    'title' => ['de' => 'Label ohne Taxonomy', 'en' => 'Label outside taxonomy'],
                    'problem' => ['de' => 'Freie Labels ohne Governance brechen Topic-Dimensionen.', 'en' => 'Free labels without governance break topic dimensions.'],
                    'prevent' => ['de' => 'Label Taxonomy / controlled vocabulary.', 'en' => 'Label taxonomy / controlled vocabulary.'],
                    'staffNeedToKnow' => ['de' => 'Autoren: Nur freigegebene Labels nutzen.', 'en' => 'Authors: Use approved labels only.'],
                    'checks' => ['de' => 'label NOT IN approved taxonomy list', 'en' => 'label NOT IN approved taxonomy list'],
                    'fixInSource' => ['de' => 'Label macros / governance page; automation cleanup.', 'en' => 'Label macros / governance page; automation cleanup.'],
                    'fixInWarehouse' => ['de' => 'Map to Unknown topic; refresh dim.', 'en' => 'Map to Unknown topic; refresh dim.'],
                ],
                [
                    'id' => 'conf-duplicate-title-space',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Page Titles im Space', 'en' => 'Duplicate page titles in space'],
                    'problem' => ['de' => 'Gleiche Titles im Space erschweren Search und MDM für Knowledge-Assets.', 'en' => 'Same titles in a space hinder search and MDM for knowledge assets.'],
                    'prevent' => ['de' => 'Naming Convention; Duplicate Check vor Create.', 'en' => 'Naming convention; duplicate check before create.'],
                    'staffNeedToKnow' => ['de' => 'Autoren: Vor Neuanlage bestehende Page suchen.', 'en' => 'Authors: Search existing page before create.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY spaceId, lower(title) HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY spaceId, lower(title) HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Rename / merge pages; redirect macros.', 'en' => 'Rename / merge pages; redirect macros.'],
                    'fixInWarehouse' => ['de' => 'Canonical contentId; merge map.', 'en' => 'Canonical contentId; merge map.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'conf-space-dup',
                    'entity' => 'Space',
                    'title' => ['de' => 'Space-Duplikate / Rename', 'en' => 'Space duplicates / rename'],
                    'matchKeys' => ['spaceId', 'spaceKey', 'name'],
                    'preventInSource' => ['de' => 'Space Key Governance; keine Parallel-Spaces für gleiches Team.', 'en' => 'Space key governance; no parallel spaces for same team.'],
                    'resolveInWarehouse' => ['de' => 'Golden spaceId; key history map.', 'en' => 'Golden spaceId; key history map.'],
                    'survivorship' => ['de' => 'Aktiver Space mit mehr Current Pages gewinnt.', 'en' => 'Active space with more current pages wins.'],
                ],
                [
                    'id' => 'conf-page-dup',
                    'entity' => 'Page',
                    'title' => ['de' => 'Page-Duplikate / Forks', 'en' => 'Page duplicates / forks'],
                    'matchKeys' => ['contentId', 'spaceId + title', 'content property external id'],
                    'preventInSource' => ['de' => 'Single source page; use Include/Excerpt statt Copy.', 'en' => 'Single source page; use include/excerpt instead of copy.'],
                    'resolveInWarehouse' => ['de' => 'Canonical contentId; redirect map.', 'en' => 'Canonical contentId; redirect map.'],
                    'survivorship' => ['de' => 'Neueste lastModified in kanonischem Space gewinnt.', 'en' => 'Latest lastModified in canonical space wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'conf-space-permissions',
                    'area' => ['de' => 'Space settings → Permissions', 'en' => 'Space settings → Permissions'],
                    'setting' => ['de' => 'Space Access und Anonymous/Guest Policy klären', 'en' => 'Clarify space access and anonymous/guest policy'],
                    'why' => ['de' => 'Permissions bestimmen Extract-Sicht und PII-Fläche.', 'en' => 'Permissions determine extract visibility and PII surface.'],
                    'how' => ['de' => 'Permissions review; document extract service account scopes.', 'en' => 'Permissions review; document extract service account scopes.'],
                ],
                [
                    'id' => 'conf-content-status',
                    'area' => ['de' => 'Space / Content lifecycle', 'en' => 'Space / content lifecycle'],
                    'setting' => ['de' => 'Archive und Current Status konsistent pflegen', 'en' => 'Maintain archive and current status consistently'],
                    'why' => ['de' => 'Active Inventory KPIs brauchen saubere Status.', 'en' => 'Active inventory KPIs need clean status.'],
                    'how' => ['de' => 'Archive playbook; periodic stale-content review.', 'en' => 'Archive playbook; periodic stale-content review.'],
                ],
                [
                    'id' => 'conf-label-governance',
                    'area' => ['de' => 'Labels / taxonomy', 'en' => 'Labels / taxonomy'],
                    'setting' => ['de' => 'Controlled Label Vocabulary', 'en' => 'Controlled label vocabulary'],
                    'why' => ['de' => 'Topic-Dimensionen bleiben analysierbar.', 'en' => 'Topic dimensions stay analyzable.'],
                    'how' => ['de' => 'Taxonomy page; automation to flag unknown labels.', 'en' => 'Taxonomy page; automation to flag unknown labels.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'conf-space-permissions-meta',
                    'kind' => ['de' => 'Space permissions', 'en' => 'Space permissions'],
                    'where' => ['de' => 'Space settings → Permissions; Admin → Space permissions', 'en' => 'Space settings → Permissions; Admin → Space permissions'],
                    'how' => ['de' => 'Permission tables exportieren; Group vs User Principals taggen.', 'en' => 'Export permission tables; tag group vs user principals.'],
                    'useFor' => ['de' => 'Access inventory, extract scope, workforce graph caution.', 'en' => 'Access inventory, extract scope, workforce graph caution.'],
                    'watchouts' => ['de' => 'Permissions enthalten Workforce-IDs — nicht in öffentlichen Marts.', 'en' => 'Permissions contain workforce IDs — not in public marts.'],
                ],
                [
                    'id' => 'conf-content-properties',
                    'kind' => ['de' => 'Content properties', 'en' => 'Content properties'],
                    'where' => ['de' => 'REST content properties; apps storing metadata on pages', 'en' => 'REST content properties; apps storing metadata on pages'],
                    'how' => ['de' => 'Property keys inventarisieren; Allowlist für Extract.', 'en' => 'Inventory property keys; allowlist for extract.'],
                    'useFor' => ['de' => 'External ids, app metadata, PII scan.', 'en' => 'External ids, app metadata, PII scan.'],
                    'watchouts' => ['de' => 'Apps speichern oft unerwartete PII in properties.', 'en' => 'Apps often store unexpected PII in properties.'],
                ],
                [
                    'id' => 'conf-rest-content',
                    'kind' => ['de' => 'REST content', 'en' => 'REST content'],
                    'where' => ['de' => 'Confluence Cloud REST (content / pages / spaces)', 'en' => 'Confluence Cloud REST (content / pages / spaces)'],
                    'how' => ['de' => 'Content endpoints mit expand-Allowlist; Bodies default weglassen.', 'en' => 'Content endpoints with expand allowlist; omit bodies by default.'],
                    'useFor' => ['de' => 'Extract-Design, Join-Keys (spaceId, contentId), status fields.', 'en' => 'Extract design, join keys (spaceId, contentId), status fields.'],
                    'watchouts' => ['de' => 'body.storage expand zieht Klartext — nur mit Use Case.', 'en' => 'body.storage expand pulls cleartext — only with use case.'],
                ],
                [
                    'id' => 'conf-labels',
                    'kind' => ['de' => 'Labels', 'en' => 'Labels'],
                    'where' => ['de' => 'Page labels UI; REST labels on content', 'en' => 'Page labels UI; REST labels on content'],
                    'how' => ['de' => 'Label inventory export; map to taxonomy.', 'en' => 'Label inventory export; map to taxonomy.'],
                    'useFor' => ['de' => 'Topic dimensions, content classification.', 'en' => 'Topic dimensions, content classification.'],
                    'watchouts' => ['de' => 'Freie Labels drift — Governance nötig.', 'en' => 'Free labels drift — governance required.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'slack' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'slack-channel-no-purpose',
                    'priority' => 'medium',
                    'title' => ['de' => 'Channel ohne Purpose', 'en' => 'Channel without purpose'],
                    'problem' => ['de' => 'Channels ohne purpose erschweren Ownership und Inventory-Qualität.', 'en' => 'Channels without purpose hinder ownership and inventory quality.'],
                    'prevent' => ['de' => 'Channel Create Checklist: Purpose Pflicht; Naming Convention.', 'en' => 'Channel create checklist: purpose required; naming convention.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Jeder Channel braucht einen Purpose.', 'en' => 'Admins: Every channel needs a purpose.'],
                    'checks' => ['de' => 'purpose IS NULL OR purpose = \'\' on public channels WHERE is_archived = false', 'en' => 'purpose IS NULL OR purpose = \'\' on public channels WHERE is_archived = false'],
                    'fixInSource' => ['de' => 'Admin policy; bot remind on create.', 'en' => 'Admin policy; bot remind on create.'],
                    'fixInWarehouse' => ['de' => 'Unknown-purpose bucket; exclude from governed inventory.', 'en' => 'Unknown-purpose bucket; exclude from governed inventory.'],
                ],
                [
                    'id' => 'slack-channel-no-creator',
                    'priority' => 'high',
                    'title' => ['de' => 'Channel ohne Creator', 'en' => 'Channel without creator'],
                    'problem' => ['de' => 'Channels ohne creator_id brechen Ownership- und Lifecycle-KPIs.', 'en' => 'Channels without creator_id break ownership and lifecycle KPIs.'],
                    'prevent' => ['de' => 'Create API immer mit User-Kontext; Import mit Mapping.', 'en' => 'Create API always with user context; import with mapping.'],
                    'staffNeedToKnow' => ['de' => 'Integrationen: Creator mappen — nicht anonym.', 'en' => 'Integrations: Map creator — not anonymous.'],
                    'checks' => ['de' => 'creator_id IS NULL on channel', 'en' => 'creator_id IS NULL on channel'],
                    'fixInSource' => ['de' => 'Fix via Admin API where possible; document orphans.', 'en' => 'Fix via Admin API where possible; document orphans.'],
                    'fixInWarehouse' => ['de' => 'Unknown-owner dim.', 'en' => 'Unknown-owner dim.'],
                ],
                [
                    'id' => 'slack-archived-still-active-kpi',
                    'priority' => 'medium',
                    'title' => ['de' => 'Archived Channel in Active KPIs', 'en' => 'Archived channel in active KPIs'],
                    'problem' => ['de' => 'Archived Channels in Active Inventory verzerren Adoption-Metriken.', 'en' => 'Archived channels in active inventory distort adoption metrics.'],
                    'prevent' => ['de' => 'Archive-Flag in allen Extracts; KPI-Definition dokumentieren.', 'en' => 'Archive flag in all extracts; document KPI definition.'],
                    'staffNeedToKnow' => ['de' => 'Analysten: is_archived filtern — nicht alle Channels zählen.', 'en' => 'Analysts: Filter is_archived — do not count all channels.'],
                    'checks' => ['de' => 'is_archived = true AND included_in_active_inventory = true', 'en' => 'is_archived = true AND included_in_active_inventory = true'],
                    'fixInSource' => ['de' => 'Consistent archive process; naming for temporary channels.', 'en' => 'Consistent archive process; naming for temporary channels.'],
                    'fixInWarehouse' => ['de' => 'Exclude archived from active channel count.', 'en' => 'Exclude archived from active channel count.'],
                ],
                [
                    'id' => 'slack-message-body-in-warehouse',
                    'priority' => 'high',
                    'title' => ['de' => 'Message Body im Warehouse', 'en' => 'Message body in warehouse'],
                    'problem' => ['de' => 'Klartext-Messages im Warehouse erzeugen DSDR-/Retention-Risiko ohne KPI-Nutzen.', 'en' => 'Cleartext messages in the warehouse create DSDR/retention risk without KPI value.'],
                    'prevent' => ['de' => 'Extract-Allowlist: nur Metadata + counts; conversations.history default off.', 'en' => 'Extract allowlist: metadata + counts only; conversations.history off by default.'],
                    'staffNeedToKnow' => ['de' => 'Data: Message Text nicht laden — Activity aggregates nutzen.', 'en' => 'Data: Do not load message text — use activity aggregates.'],
                    'checks' => ['de' => 'EXISTS columns text/blocks in curated OR raw message body tables without legal flag', 'en' => 'EXISTS columns text/blocks in curated OR raw message body tables without legal flag'],
                    'fixInSource' => ['de' => 'Disable history export for analytics app; Admin Analytics APIs.', 'en' => 'Disable history export for analytics app; Admin Analytics APIs.'],
                    'fixInWarehouse' => ['de' => 'Drop body columns; rebuild as message_count facts.', 'en' => 'Drop body columns; rebuild as message_count facts.'],
                ],
                [
                    'id' => 'slack-retention-mismatch',
                    'priority' => 'high',
                    'title' => ['de' => 'Retention Policy Mismatch', 'en' => 'Retention policy mismatch'],
                    'problem' => ['de' => 'Warehouse hält Message-Metadata länger als Slack Retention — Compliance-Gap.', 'en' => 'Warehouse keeps message metadata longer than Slack retention — compliance gap.'],
                    'prevent' => ['de' => 'Warehouse Retention ≤ Slack Policy; documented exception process.', 'en' => 'Warehouse retention ≤ Slack policy; documented exception process.'],
                    'staffNeedToKnow' => ['de' => 'Legal/Data: Retention aligned — keine stillen Langzeitkopien.', 'en' => 'Legal/data: Retention aligned — no silent long-term copies.'],
                    'checks' => ['de' => 'max(event_date) - min(event_date) > slack_retention_days on activity facts', 'en' => 'max(event_date) - min(event_date) > slack_retention_days on activity facts'],
                    'fixInSource' => ['de' => 'Workspace retention settings review.', 'en' => 'Workspace retention settings review.'],
                    'fixInWarehouse' => ['de' => 'TTL jobs; purge older activity grain.', 'en' => 'TTL jobs; purge older activity grain.'],
                ],
                [
                    'id' => 'slack-member-count-null',
                    'priority' => 'low',
                    'title' => ['de' => 'Channel ohne Member Count', 'en' => 'Channel without member count'],
                    'problem' => ['de' => 'Fehlende num_members verhindert Adoption- und Size-Schnitte.', 'en' => 'Missing num_members prevents adoption and size slices.'],
                    'prevent' => ['de' => 'conversations.info regelmäßig syncen; Admin Analytics nutzen.', 'en' => 'Sync conversations.info regularly; use Admin Analytics.'],
                    'staffNeedToKnow' => ['de' => 'Extract: Member Counts nicht weglassen.', 'en' => 'Extract: Do not omit member counts.'],
                    'checks' => ['de' => 'num_members IS NULL on non-archived public channels', 'en' => 'num_members IS NULL on non-archived public channels'],
                    'fixInSource' => ['de' => 'Refresh channel metadata job.', 'en' => 'Refresh channel metadata job.'],
                    'fixInWarehouse' => ['de' => 'Impute 0 with flag or exclude from size KPIs.', 'en' => 'Impute 0 with flag or exclude from size KPIs.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'slack-user-dup',
                    'entity' => 'User',
                    'title' => ['de' => 'User-Duplikate / Deactivated', 'en' => 'User duplicates / deactivated'],
                    'matchKeys' => ['user_id', 'profile.email', 'enterprise_user.id'],
                    'preventInSource' => ['de' => 'SCIM/IdP as source of truth; deactivate instead of recreate.', 'en' => 'SCIM/IdP as source of truth; deactivate instead of recreate.'],
                    'resolveInWarehouse' => ['de' => 'Golden user_id; email-hash merge map.', 'en' => 'Golden user_id; email-hash merge map.'],
                    'survivorship' => ['de' => 'Aktiver User mit neuester Activity gewinnt.', 'en' => 'Active user with latest activity wins.'],
                ],
                [
                    'id' => 'slack-channel-rename',
                    'entity' => 'Channel',
                    'title' => ['de' => 'Channel Rename / Archive Reuse', 'en' => 'Channel rename / archive reuse'],
                    'matchKeys' => ['channel_id', 'name', 'purpose'],
                    'preventInSource' => ['de' => 'Stable channel_id as key; naming convention for renames.', 'en' => 'Stable channel_id as key; naming convention for renames.'],
                    'resolveInWarehouse' => ['de' => 'SCD2 channel name; keep channel_id canonical.', 'en' => 'SCD2 channel name; keep channel_id canonical.'],
                    'survivorship' => ['de' => 'channel_id gewinnt über Name.', 'en' => 'channel_id wins over name.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'slack-workspace-retention',
                    'area' => ['de' => 'Workspace settings → Message & file retention', 'en' => 'Workspace settings → Message & file retention'],
                    'setting' => ['de' => 'Retention Policy dokumentieren und Warehouse angleichen', 'en' => 'Document retention policy and align warehouse'],
                    'why' => ['de' => 'Verhindert Compliance-Gaps durch Langzeitkopien.', 'en' => 'Prevents compliance gaps from long-lived copies.'],
                    'how' => ['de' => 'Admin settings review; TTL in warehouse jobs.', 'en' => 'Admin settings review; TTL in warehouse jobs.'],
                ],
                [
                    'id' => 'slack-analytics-apis',
                    'area' => ['de' => 'Admin Analytics APIs', 'en' => 'Admin Analytics APIs'],
                    'setting' => ['de' => 'Analytics APIs statt conversations.history für KPIs', 'en' => 'Analytics APIs instead of conversations.history for KPIs'],
                    'why' => ['de' => 'Activity ohne Message-Klartext.', 'en' => 'Activity without message cleartext.'],
                    'how' => ['de' => 'Admin scopes minimal; aggregate extracts only.', 'en' => 'Minimal admin scopes; aggregate extracts only.'],
                ],
                [
                    'id' => 'slack-channel-governance',
                    'area' => ['de' => 'Channel management / naming', 'en' => 'Channel management / naming'],
                    'setting' => ['de' => 'Purpose + Naming Convention enforced', 'en' => 'Purpose + naming convention enforced'],
                    'why' => ['de' => 'Inventory-Qualität und Ownership.', 'en' => 'Inventory quality and ownership.'],
                    'how' => ['de' => 'Create guidelines; archive stale channels.', 'en' => 'Create guidelines; archive stale channels.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'slack-conversations-api',
                    'kind' => ['de' => 'Conversations API', 'en' => 'Conversations API'],
                    'where' => ['de' => 'Slack API → conversations.list / info / members', 'en' => 'Slack API → conversations.list / info / members'],
                    'how' => ['de' => 'Channel metadata sync; history endpoints default skip.', 'en' => 'Channel metadata sync; skip history endpoints by default.'],
                    'useFor' => ['de' => 'Channel inventory, membership counts, archive flags.', 'en' => 'Channel inventory, membership counts, archive flags.'],
                    'watchouts' => ['de' => 'conversations.history liefert Klartext — nicht für Standard-Analytics.', 'en' => 'conversations.history returns cleartext — not for standard analytics.'],
                ],
                [
                    'id' => 'slack-admin-analytics',
                    'kind' => ['de' => 'Admin analytics APIs', 'en' => 'Admin analytics APIs'],
                    'where' => ['de' => 'Slack Admin → Analytics APIs / admin.analytics', 'en' => 'Slack Admin → Analytics APIs / admin.analytics'],
                    'how' => ['de' => 'Aggregate member/channel activity extracts.', 'en' => 'Aggregate member/channel activity extracts.'],
                    'useFor' => ['de' => 'Adoption KPIs ohne Message Bodies.', 'en' => 'Adoption KPIs without message bodies.'],
                    'watchouts' => ['de' => 'Admin scopes sind mächtig — Least Privilege.', 'en' => 'Admin scopes are powerful — least privilege.'],
                ],
                [
                    'id' => 'slack-workspace-settings',
                    'kind' => ['de' => 'Workspace settings', 'en' => 'Workspace settings'],
                    'where' => ['de' => 'Slack Admin → Settings & permissions / Retention', 'en' => 'Slack Admin → Settings & permissions / Retention'],
                    'how' => ['de' => 'Retention, guest access, app approvals dokumentieren.', 'en' => 'Document retention, guest access, app approvals.'],
                    'useFor' => ['de' => 'Governance baseline, warehouse TTL policy.', 'en' => 'Governance baseline, warehouse TTL policy.'],
                    'watchouts' => ['de' => 'Enterprise Grid kann Workspace-Policies überschreiben.', 'en' => 'Enterprise Grid can override workspace policies.'],
                ],
                [
                    'id' => 'slack-enterprise-grid',
                    'kind' => ['de' => 'Enterprise Grid discovery', 'en' => 'Enterprise Grid discovery'],
                    'where' => ['de' => 'Enterprise Grid Admin → Discovery / Org-wide search (compliance)', 'en' => 'Enterprise Grid Admin → Discovery / Org-wide search (compliance)'],
                    'how' => ['de' => 'Discovery nur für Compliance — nicht Analytics-Load.', 'en' => 'Discovery for compliance only — not analytics load.'],
                    'useFor' => ['de' => 'Legal hold awareness — separate from marts.', 'en' => 'Legal hold awareness — separate from marts.'],
                    'watchouts' => ['de' => 'Discovery Exports sind volle Message-Kopien — DSDR.', 'en' => 'Discovery exports are full message copies — DSDR.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'microsoft-teams' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'teams-chat-no-context',
                    'priority' => 'high',
                    'title' => ['de' => 'Chat ohne Team/Channel-Kontext', 'en' => 'Chat without team/channel context'],
                    'problem' => ['de' => 'Activity ohne teamId/channelId lässt Collaboration nicht nach Team schneiden.', 'en' => 'Activity without teamId/channelId cannot slice collaboration by team.'],
                    'prevent' => ['de' => 'Channel Messages bevorzugen; Chat-Exports für Analytics skip.', 'en' => 'Prefer channel messages; skip chat exports for analytics.'],
                    'staffNeedToKnow' => ['de' => 'Data: Channel Activity ≠ private Chat — Kontext-Keys Pflicht.', 'en' => 'Data: Channel activity ≠ private chat — context keys required.'],
                    'checks' => ['de' => 'teamId IS NULL AND channelId IS NULL on channel_activity grain', 'en' => 'teamId IS NULL AND channelId IS NULL on channel_activity grain'],
                    'fixInSource' => ['de' => 'Extract only team/channel scoped Graph calls.', 'en' => 'Extract only team/channel scoped Graph calls.'],
                    'fixInWarehouse' => ['de' => 'Quarantine orphan activity; exclude from team KPIs.', 'en' => 'Quarantine orphan activity; exclude from team KPIs.'],
                ],
                [
                    'id' => 'teams-team-no-owner',
                    'priority' => 'high',
                    'title' => ['de' => 'Team ohne Owner', 'en' => 'Team without owner'],
                    'problem' => ['de' => 'Teams ohne Owner brechen Lifecycle- und Governance-KPIs.', 'en' => 'Teams without owner break lifecycle and governance KPIs.'],
                    'prevent' => ['de' => 'Team Create Policy: mindestens ein Owner; Guest ≠ Owner.', 'en' => 'Team create policy: at least one owner; guest ≠ owner.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Jedes Team braucht einen Owner.', 'en' => 'Admins: Every team needs an owner.'],
                    'checks' => ['de' => 'owner_count = 0 on team WHERE isArchived = false', 'en' => 'owner_count = 0 on team WHERE isArchived = false'],
                    'fixInSource' => ['de' => 'Teams admin center policy; Graph ownership fix.', 'en' => 'Teams admin center policy; Graph ownership fix.'],
                    'fixInWarehouse' => ['de' => 'Unknown-owner dim; flag orphan teams.', 'en' => 'Unknown-owner dim; flag orphan teams.'],
                ],
                [
                    'id' => 'teams-message-body-in-warehouse',
                    'priority' => 'high',
                    'title' => ['de' => 'Message Body im Warehouse', 'en' => 'Message body in warehouse'],
                    'problem' => ['de' => 'Klartext-Bodies im Warehouse erzeugen DSDR-/Retention-Risiko.', 'en' => 'Cleartext bodies in the warehouse create DSDR/retention risk.'],
                    'prevent' => ['de' => 'Graph Extract: nur Counts/Metadata; body.content default skip.', 'en' => 'Graph extract: counts/metadata only; skip body.content by default.'],
                    'staffNeedToKnow' => ['de' => 'Data: Keine Message Bodies — message_count Facts.', 'en' => 'Data: No message bodies — message_count facts.'],
                    'checks' => ['de' => 'EXISTS body.content in curated OR raw without legal flag', 'en' => 'EXISTS body.content in curated OR raw without legal flag'],
                    'fixInSource' => ['de' => 'App permission review; remove ChannelMessage.Read for analytics if unused.', 'en' => 'App permission review; remove ChannelMessage.Read for analytics if unused.'],
                    'fixInWarehouse' => ['de' => 'Drop body columns; rebuild activity aggregates.', 'en' => 'Drop body columns; rebuild activity aggregates.'],
                ],
                [
                    'id' => 'teams-archived-still-active',
                    'priority' => 'medium',
                    'title' => ['de' => 'Archived Team in Active KPIs', 'en' => 'Archived team in active KPIs'],
                    'problem' => ['de' => 'Archived Teams in Active Counts verzerren Adoption.', 'en' => 'Archived teams in active counts distort adoption.'],
                    'prevent' => ['de' => 'isArchived in Extract und KPI-Definition.', 'en' => 'isArchived in extract and KPI definition.'],
                    'staffNeedToKnow' => ['de' => 'Analysten: Archived Teams aus Active Inventory filtern.', 'en' => 'Analysts: Filter archived teams from active inventory.'],
                    'checks' => ['de' => 'isArchived = true AND included_in_active_inventory = true', 'en' => 'isArchived = true AND included_in_active_inventory = true'],
                    'fixInSource' => ['de' => 'Archive playbook in Teams admin center.', 'en' => 'Archive playbook in Teams admin center.'],
                    'fixInWarehouse' => ['de' => 'Exclude archived from active team count.', 'en' => 'Exclude archived from active team count.'],
                ],
                [
                    'id' => 'teams-purview-retention-mismatch',
                    'priority' => 'high',
                    'title' => ['de' => 'Purview Retention Mismatch', 'en' => 'Purview retention mismatch'],
                    'problem' => ['de' => 'Warehouse hält Activity länger als Purview Retention — Compliance-Gap.', 'en' => 'Warehouse keeps activity longer than Purview retention — compliance gap.'],
                    'prevent' => ['de' => 'Warehouse TTL ≤ Purview Labels; Exceptions dokumentieren.', 'en' => 'Warehouse TTL ≤ Purview labels; document exceptions.'],
                    'staffNeedToKnow' => ['de' => 'Legal/Data: Retention aligned mit Purview.', 'en' => 'Legal/data: Retention aligned with Purview.'],
                    'checks' => ['de' => 'activity fact age > purview_retention_days', 'en' => 'activity fact age > purview_retention_days'],
                    'fixInSource' => ['de' => 'Purview retention label review.', 'en' => 'Purview retention label review.'],
                    'fixInWarehouse' => ['de' => 'TTL purge jobs on activity grain.', 'en' => 'TTL purge jobs on activity grain.'],
                ],
                [
                    'id' => 'teams-channel-no-team',
                    'priority' => 'medium',
                    'title' => ['de' => 'Channel ohne Team', 'en' => 'Channel without team'],
                    'problem' => ['de' => 'Channels ohne teamId sind orphaned — Hierarchy-Reports brechen.', 'en' => 'Channels without teamId are orphaned — hierarchy reports break.'],
                    'prevent' => ['de' => 'Graph Create Channel immer unter Team; Import validieren.', 'en' => 'Graph create channel always under team; validate import.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Channel gehört immer zu einem Team.', 'en' => 'Admins: Channel always belongs to a team.'],
                    'checks' => ['de' => 'teamId IS NULL on channel', 'en' => 'teamId IS NULL on channel'],
                    'fixInSource' => ['de' => 'Repair via Graph; delete orphans.', 'en' => 'Repair via Graph; delete orphans.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from hierarchy KPIs.', 'en' => 'Quarantine; exclude from hierarchy KPIs.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'teams-user-dup',
                    'entity' => 'User / Entra ID',
                    'title' => ['de' => 'User-Duplikate / Guest', 'en' => 'User duplicates / guest'],
                    'matchKeys' => ['id', 'userPrincipalName', 'mail'],
                    'preventInSource' => ['de' => 'Entra ID as source of truth; guest lifecycle policy.', 'en' => 'Entra ID as source of truth; guest lifecycle policy.'],
                    'resolveInWarehouse' => ['de' => 'Golden user id; UPN-hash merge map.', 'en' => 'Golden user id; UPN-hash merge map.'],
                    'survivorship' => ['de' => 'Member Account gewinnt über Guest bei gleichem Mail-Hash.', 'en' => 'Member account wins over guest on same mail hash.'],
                ],
                [
                    'id' => 'teams-team-rename',
                    'entity' => 'Team',
                    'title' => ['de' => 'Team Rename / Archive', 'en' => 'Team rename / archive'],
                    'matchKeys' => ['teamId', 'displayName', 'mailNickname'],
                    'preventInSource' => ['de' => 'Stable teamId as key; naming convention for renames.', 'en' => 'Stable teamId as key; naming convention for renames.'],
                    'resolveInWarehouse' => ['de' => 'SCD2 team name; teamId canonical.', 'en' => 'SCD2 team name; teamId canonical.'],
                    'survivorship' => ['de' => 'teamId gewinnt über displayName.', 'en' => 'teamId wins over displayName.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'teams-admin-center',
                    'area' => ['de' => 'Teams admin center', 'en' => 'Teams admin center'],
                    'setting' => ['de' => 'Team/Channel Policies und Archive-Regeln', 'en' => 'Team/channel policies and archive rules'],
                    'why' => ['de' => 'Ownership und Active Inventory bleiben steuerbar.', 'en' => 'Ownership and active inventory stay controllable.'],
                    'how' => ['de' => 'Policies review; owner required; archive playbook.', 'en' => 'Policies review; owner required; archive playbook.'],
                ],
                [
                    'id' => 'teams-purview-retention',
                    'area' => ['de' => 'Microsoft Purview retention', 'en' => 'Microsoft Purview retention'],
                    'setting' => ['de' => 'Retention Labels mit Warehouse TTL alignen', 'en' => 'Align retention labels with warehouse TTL'],
                    'why' => ['de' => 'Keine längeren Analytics-Kopien als Compliance erlaubt.', 'en' => 'No analytics copies longer than compliance allows.'],
                    'how' => ['de' => 'Purview labels dokumentieren; TTL jobs konfigurieren.', 'en' => 'Document Purview labels; configure TTL jobs.'],
                ],
                [
                    'id' => 'teams-graph-scopes',
                    'area' => ['de' => 'Microsoft Graph app permissions', 'en' => 'Microsoft Graph app permissions'],
                    'setting' => ['de' => 'Least Privilege — keine Message-Read ohne Use Case', 'en' => 'Least privilege — no message-read without use case'],
                    'why' => ['de' => 'Verhindert Klartext-Bodies im Extract.', 'en' => 'Prevents cleartext bodies in extract.'],
                    'how' => ['de' => 'App registration review; ChannelMessage.Read nur wenn nötig.', 'en' => 'App registration review; ChannelMessage.Read only if needed.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'teams-graph-metadata',
                    'kind' => ['de' => 'Microsoft Graph $metadata', 'en' => 'Microsoft Graph $metadata'],
                    'where' => ['de' => 'https://graph.microsoft.com/v1.0/$metadata (Teams entities)', 'en' => 'https://graph.microsoft.com/v1.0/$metadata (Teams entities)'],
                    'how' => ['de' => '$metadata parsen; Team/Channel/Chat Entities und Properties taggen.', 'en' => 'Parse $metadata; tag team/channel/chat entities and properties.'],
                    'useFor' => ['de' => 'Extract-Design, Allowlist, Join-Keys.', 'en' => 'Extract design, allowlist, join keys.'],
                    'watchouts' => ['de' => 'Message body properties leicht verfügbar — default exclude.', 'en' => 'Message body properties easily available — exclude by default.'],
                ],
                [
                    'id' => 'teams-admin-center-meta',
                    'kind' => ['de' => 'Teams admin center', 'en' => 'Teams admin center'],
                    'where' => ['de' => 'Microsoft Teams admin center → Teams / Users / Policies', 'en' => 'Microsoft Teams admin center → Teams / Users / Policies'],
                    'how' => ['de' => 'Policies und Team Inventory exportieren.', 'en' => 'Export policies and team inventory.'],
                    'useFor' => ['de' => 'Governance baseline, archive status, owner inventory.', 'en' => 'Governance baseline, archive status, owner inventory.'],
                    'watchouts' => ['de' => 'Admin center ≠ vollständiges Graph-Schema.', 'en' => 'Admin center ≠ full Graph schema.'],
                ],
                [
                    'id' => 'teams-purview-meta',
                    'kind' => ['de' => 'Purview retention', 'en' => 'Purview retention'],
                    'where' => ['de' => 'Microsoft Purview → Data lifecycle management / Retention', 'en' => 'Microsoft Purview → Data lifecycle management / Retention'],
                    'how' => ['de' => 'Retention Labels und Locations für Teams dokumentieren.', 'en' => 'Document retention labels and locations for Teams.'],
                    'useFor' => ['de' => 'Warehouse TTL, compliance alignment.', 'en' => 'Warehouse TTL, compliance alignment.'],
                    'watchouts' => ['de' => 'eDiscovery Exports nicht als Analytics-Source nutzen.', 'en' => 'Do not use eDiscovery exports as analytics source.'],
                ],
                [
                    'id' => 'teams-change-notifications',
                    'kind' => ['de' => 'Graph change notifications', 'en' => 'Graph change notifications'],
                    'where' => ['de' => 'Microsoft Graph subscriptions / change notifications', 'en' => 'Microsoft Graph subscriptions / change notifications'],
                    'how' => ['de' => 'Subscriptions auf Metadata-Events; Message Content nicht speichern.', 'en' => 'Subscriptions on metadata events; do not store message content.'],
                    'useFor' => ['de' => 'Near-real-time activity signals without bodies.', 'en' => 'Near-real-time activity signals without bodies.'],
                    'watchouts' => ['de' => 'Notifications können Bodies enthalten — Payload-Allowlist.', 'en' => 'Notifications can include bodies — payload allowlist.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],
];
