<?php

/**
 * Wave 6 quality overlays — Banking Core source-native DQ, MDM, metadata guides.
 *
 * @return array<string, array<string, mixed>>
 */

return [
    'temenos' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'temenos-account-no-customer',
                    'priority' => 'high',
                    'title' => ['de' => 'Account ohne Customer', 'en' => 'Account without customer'],
                    'problem' => ['de' => 'Accounts ohne aufgelösten CUSTOMER brechen Customer-360 Joins und Balance-Rollups.', 'en' => 'Accounts without a resolvable CUSTOMER break customer-360 joins and balance rollups.'],
                    'prevent' => ['de' => 'Extract: CUSTOMER immer mitladen; Joint/Internal Accounts separat kennzeichnen.', 'en' => 'Extract: always load CUSTOMER; flag joint/internal accounts separately.'],
                    'staffNeedToKnow' => ['de' => 'Data: Account ohne Customer ist Extract-/Migrations-Artefakt.', 'en' => 'Data: Account without customer is an extract/migration artifact.'],
                    'checks' => ['de' => 'account.CUSTOMER IS NULL OR CUSTOMER NOT IN dim_customer', 'en' => 'account.CUSTOMER IS NULL OR CUSTOMER NOT IN dim_customer'],
                    'fixInSource' => ['de' => 'Re-extract; repair CIF link in T24.', 'en' => 'Re-extract; repair CIF link in T24.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown customer dim.', 'en' => 'Quarantine; Unknown customer dim.'],
                ],
                [
                    'id' => 'temenos-negative-balance-no-limit',
                    'priority' => 'high',
                    'title' => ['de' => 'Negativer Saldo ohne Limit', 'en' => 'Negative balance without limit'],
                    'problem' => ['de' => 'Overdrafts ohne verknüpftes LIMIT verzerren Credit-Risk- und Utilization-KPIs.', 'en' => 'Overdrafts without a linked LIMIT distort credit-risk and utilization KPIs.'],
                    'prevent' => ['de' => 'Overdraft-Facility Pflicht vor Freigabe; Limit-Check im Account-Opening-Workflow.', 'en' => 'Require overdraft facility before approval; limit check in account-opening workflow.'],
                    'staffNeedToKnow' => ['de' => 'Credit Risk: Unauthorized Overdrafts separat tracken.', 'en' => 'Credit risk: track unauthorized overdrafts separately.'],
                    'checks' => ['de' => 'account.WORKING.BALANCE < 0 AND NOT EXISTS (SELECT 1 FROM limit WHERE limit.CUSTOMER = account.CUSTOMER)', 'en' => 'account.WORKING.BALANCE < 0 AND NOT EXISTS (SELECT 1 FROM limit WHERE limit.CUSTOMER = account.CUSTOMER)'],
                    'fixInSource' => ['de' => 'Assign limit or block further debits.', 'en' => 'Assign limit or block further debits.'],
                    'fixInWarehouse' => ['de' => 'Flag unauthorized_overdraft; exclude from authorized utilization KPI.', 'en' => 'Flag unauthorized_overdraft; exclude from authorized utilization KPI.'],
                ],
                [
                    'id' => 'temenos-arrangement-no-product',
                    'priority' => 'medium',
                    'title' => ['de' => 'Arrangement ohne Product', 'en' => 'Arrangement without product'],
                    'problem' => ['de' => 'Arrangements ohne PRODUCT-Link brechen Product-Mix-Reports.', 'en' => 'Arrangements without a PRODUCT link break product-mix reports.'],
                    'prevent' => ['de' => 'AA.PRODUCT Pflichtfeld bei Arrangement Creation.', 'en' => 'Require AA.PRODUCT field on arrangement creation.'],
                    'staffNeedToKnow' => ['de' => 'Product Team: Kein Arrangement ohne Product-Zuordnung.', 'en' => 'Product team: No arrangement without a product assignment.'],
                    'checks' => ['de' => 'arrangement.PRODUCT IS NULL', 'en' => 'arrangement.PRODUCT IS NULL'],
                    'fixInSource' => ['de' => 'Re-map product in AA; correct product designer config.', 'en' => 'Re-map product in AA; correct product designer config.'],
                    'fixInWarehouse' => ['de' => 'Unknown product dim; exclude from product-mix KPI.', 'en' => 'Unknown product dim; exclude from product-mix KPI.'],
                ],
                [
                    'id' => 'temenos-stmt-entry-orphan-account',
                    'priority' => 'high',
                    'title' => ['de' => 'Statement Entry ohne Account', 'en' => 'Statement entry without account'],
                    'problem' => ['de' => 'Postings ohne auflösbaren ACCOUNT.NUMBER brechen Ledger-Fact-Joins.', 'en' => 'Postings without a resolvable ACCOUNT.NUMBER break ledger fact joins.'],
                    'prevent' => ['de' => 'Extract: ACCOUNT.NUMBER Pflichtfeld; closed/archived accounts separat behandeln.', 'en' => 'Extract: ACCOUNT.NUMBER required field; handle closed/archived accounts separately.'],
                    'staffNeedToKnow' => ['de' => 'Data: Orphan Postings vs. Archived Accounts trennen.', 'en' => 'Data: Separate orphan postings vs archived accounts.'],
                    'checks' => ['de' => 'statement_entry.ACCOUNT.NUMBER IS NULL OR ACCOUNT.NUMBER NOT IN dim_account', 'en' => 'statement_entry.ACCOUNT.NUMBER IS NULL OR ACCOUNT.NUMBER NOT IN dim_account'],
                    'fixInSource' => ['de' => 'Re-extract with account history; widen archived account lookback.', 'en' => 'Re-extract with account history; widen archived account lookback.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown account dim.', 'en' => 'Quarantine; Unknown account dim.'],
                ],
                [
                    'id' => 'temenos-limit-expired-still-used',
                    'priority' => 'medium',
                    'title' => ['de' => 'Abgelaufenes Limit noch in Nutzung', 'en' => 'Expired limit still in use'],
                    'problem' => ['de' => 'Accounts nutzen Limits nach EXPIRY.DATE weiter — Credit-Risk-Exposure ungetrackt.', 'en' => 'Accounts continue using limits past EXPIRY.DATE — untracked credit-risk exposure.'],
                    'prevent' => ['de' => 'Limit renewal workflow; auto-block bei Expiry ohne Renewal.', 'en' => 'Limit renewal workflow; auto-block on expiry without renewal.'],
                    'staffNeedToKnow' => ['de' => 'Credit Risk: Expired Limits vor Nutzung reviewen.', 'en' => 'Credit risk: Review expired limits before use.'],
                    'checks' => ['de' => 'limit.EXPIRY.DATE < CURRENT_DATE AND linked_account.WORKING.BALANCE < 0', 'en' => 'limit.EXPIRY.DATE < CURRENT_DATE AND linked_account.WORKING.BALANCE < 0'],
                    'fixInSource' => ['de' => 'Renew or revoke limit; enforce block.', 'en' => 'Renew or revoke limit; enforce block.'],
                    'fixInWarehouse' => ['de' => 'Flag expired_limit_in_use; separate exposure KPI.', 'en' => 'Flag expired_limit_in_use; separate exposure KPI.'],
                ],
                [
                    'id' => 'temenos-duplicate-customer-legal-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte LEGAL.ID über mehrere Customer', 'en' => 'Duplicate LEGAL.ID across multiple customers'],
                    'problem' => ['de' => 'Mehrere CUSTOMER.NO mit gleicher LEGAL.ID verzerren Customer-Counts und KYC-Reviews.', 'en' => 'Multiple CUSTOMER.NO with the same LEGAL.ID distort customer counts and KYC reviews.'],
                    'prevent' => ['de' => 'Uniqueness-Check auf LEGAL.ID bei Customer Creation.', 'en' => 'Uniqueness check on LEGAL.ID at customer creation.'],
                    'staffNeedToKnow' => ['de' => 'Onboarding: LEGAL.ID vor Neuanlage prüfen.', 'en' => 'Onboarding: Check LEGAL.ID before creating a new record.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY LEGAL.ID HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY LEGAL.ID HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Merge duplicate CIF records; investigate onboarding gap.', 'en' => 'Merge duplicate CIF records; investigate onboarding gap.'],
                    'fixInWarehouse' => ['de' => 'Golden customer id; LEGAL.ID-hash merge map.', 'en' => 'Golden customer id; LEGAL.ID-hash merge map.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'temenos-customer-dup',
                    'entity' => 'Customer',
                    'title' => ['de' => 'Customer-Duplikate', 'en' => 'Customer duplicates'],
                    'matchKeys' => ['CUSTOMER.NO', 'LEGAL.ID', 'MNEMONIC', 'DATE.OF.BIRTH'],
                    'preventInSource' => ['de' => 'CIF uniqueness check on LEGAL.ID; merge workflow for re-onboarding.', 'en' => 'CIF uniqueness check on LEGAL.ID; merge workflow for re-onboarding.'],
                    'resolveInWarehouse' => ['de' => 'Golden customer id; LEGAL.ID-hash merge map.', 'en' => 'Golden customer id; LEGAL.ID-hash merge map.'],
                    'survivorship' => ['de' => 'Customer mit aktivsten Accounts/Arrangements gewinnt.', 'en' => 'Customer with the most active accounts/arrangements wins.'],
                ],
                [
                    'id' => 'temenos-arrangement-product-map',
                    'entity' => 'Arrangement / Product',
                    'title' => ['de' => 'Arrangement-Product Mapping Drift', 'en' => 'Arrangement-product mapping drift'],
                    'matchKeys' => ['ARRANGEMENT.ID', 'PRODUCT.ID', 'PRODUCT.LINE'],
                    'preventInSource' => ['de' => 'Stable product designer config; controlled product line changes.', 'en' => 'Stable product designer config; controlled product line changes.'],
                    'resolveInWarehouse' => ['de' => 'Canonical product id; SCD2 product line.', 'en' => 'Canonical product id; SCD2 product line.'],
                    'survivorship' => ['de' => 'Aktuelle Product-Zuordnung gewinnt über Legacy-Mapping.', 'en' => 'Current product mapping wins over legacy mapping.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'temenos-limit-renewal-policy',
                    'area' => ['de' => 'Credit → Limits & Facilities', 'en' => 'Credit → Limits & facilities'],
                    'setting' => ['de' => 'Limit Renewal Workflow und Auto-Block bei Expiry', 'en' => 'Limit renewal workflow and auto-block on expiry'],
                    'why' => ['de' => 'Verhindert Expired-Limit-Still-In-Use DQ Failures.', 'en' => 'Prevents expired-limit-still-in-use DQ failures.'],
                    'how' => ['de' => 'Configure renewal reminders; enforce block on lapse.', 'en' => 'Configure renewal reminders; enforce block on lapse.'],
                ],
                [
                    'id' => 'temenos-cif-dedup',
                    'area' => ['de' => 'Customer → CIF creation', 'en' => 'Customer → CIF creation'],
                    'setting' => ['de' => 'LEGAL.ID Uniqueness Check bei Onboarding', 'en' => 'LEGAL.ID uniqueness check at onboarding'],
                    'why' => ['de' => 'Reduziert Customer-Duplikate und KYC-Review-Aufwand.', 'en' => 'Reduces customer duplicates and KYC review effort.'],
                    'how' => ['de' => 'Enable duplicate-check screen; enforce merge before create.', 'en' => 'Enable duplicate-check screen; enforce merge before create.'],
                ],
                [
                    'id' => 'temenos-payment-message-retention',
                    'area' => ['de' => 'Payments → Message archive', 'en' => 'Payments → Message archive'],
                    'setting' => ['de' => 'Kurze Retention für Zahlungsnachrichten; keine Message-Exports ins Warehouse', 'en' => 'Short retention for payment messages; no message exports into the warehouse'],
                    'why' => ['de' => 'Ledger-KPIs ohne Klartext-Zahlungspayloads.', 'en' => 'Ledger KPIs without cleartext payment payloads.'],
                    'how' => ['de' => 'Archive policy on message store; extract status/reference fields only.', 'en' => 'Archive policy on message store; extract status/reference fields only.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'temenos-data-dictionary',
                    'kind' => ['de' => 'T24 Data Dictionary (DD)', 'en' => 'T24 Data Dictionary (DD)'],
                    'where' => ['de' => 'T24 → Application Designer / Data Dictionary; TAFC/TAFJ metadata', 'en' => 'T24 → Application Designer / Data Dictionary; TAFC/TAFJ metadata'],
                    'how' => ['de' => 'Field/Table Definitionen inventarisieren; Multi-Value-Felder dokumentieren.', 'en' => 'Inventory field/table definitions; document multi-value fields.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (CUSTOMER.NO, ACCOUNT.NUMBER).', 'en' => 'Extract design, PII tags, join keys (CUSTOMER.NO, ACCOUNT.NUMBER).'],
                    'watchouts' => ['de' => 'Multi-Value/Multi-Multi-Felder korrekt flatten — sonst Duplicate Rows.', 'en' => 'Flatten multi-value/multi-multi fields correctly — otherwise duplicate rows.'],
                ],
                [
                    'id' => 'temenos-aa-product-designer',
                    'kind' => ['de' => 'Arrangement Architecture product designer', 'en' => 'Arrangement Architecture product designer'],
                    'where' => ['de' => 'T24 → AA.PRODUCT.DESIGNER; Product-Line-Konfiguration', 'en' => 'T24 → AA.PRODUCT.DESIGNER; product-line configuration'],
                    'how' => ['de' => 'Product Bundles und Feature-Konfiguration dokumentieren.', 'en' => 'Document product bundles and feature configuration.'],
                    'useFor' => ['de' => 'Product dim, product-mix KPIs, arrangement joins.', 'en' => 'Product dim, product-mix KPIs, arrangement joins.'],
                    'watchouts' => ['de' => 'Product Line Renames — SCD2 empfohlen.', 'en' => 'Product line renames — SCD2 recommended.'],
                ],
                [
                    'id' => 'temenos-eod-batch-schema',
                    'kind' => ['de' => 'End-of-day batch schema', 'en' => 'End-of-day batch schema'],
                    'where' => ['de' => 'T24 → COB (Close of Business) job configuration; batch extract files', 'en' => 'T24 → COB (close of business) job configuration; batch extract files'],
                    'how' => ['de' => 'Extract Files/Fields je COB-Stage dokumentieren.', 'en' => 'Document extract files/fields per COB stage.'],
                    'useFor' => ['de' => 'Ledger facts, EOD balance snapshots, reconciliation.', 'en' => 'Ledger facts, EOD balance snapshots, reconciliation.'],
                    'watchouts' => ['de' => 'COB-Reruns können Duplicate Extracts erzeugen — idempotent laden.', 'en' => 'COB reruns can produce duplicate extracts — load idempotently.'],
                ],
                [
                    'id' => 'temenos-reference-tables',
                    'kind' => ['de' => 'Reference / enum tables', 'en' => 'Reference / enum tables'],
                    'where' => ['de' => 'T24 → CATEGORY, SECTOR, CURRENCY reference tables', 'en' => 'T24 → CATEGORY, SECTOR, CURRENCY reference tables'],
                    'how' => ['de' => 'Code-zu-Beschreibung-Mappings exportieren.', 'en' => 'Export code-to-description mappings.'],
                    'useFor' => ['de' => 'Dimension enrichment (account category, sector labels).', 'en' => 'Dimension enrichment (account category, sector labels).'],
                    'watchouts' => ['de' => 'Reference-Codes können sich per Company/Region unterscheiden.', 'en' => 'Reference codes can differ per company/region.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'avaloq' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'avaloq-contract-no-bp',
                    'priority' => 'high',
                    'title' => ['de' => 'Contract ohne Business Partner', 'en' => 'Contract without business partner'],
                    'problem' => ['de' => 'Contracts ohne aufgelösten BP_ID brechen Customer-360 Joins.', 'en' => 'Contracts without a resolvable BP_ID break customer-360 joins.'],
                    'prevent' => ['de' => 'Extract: BP_ID immer mitladen; Joint Contracts separat kennzeichnen.', 'en' => 'Extract: always load BP_ID; flag joint contracts separately.'],
                    'staffNeedToKnow' => ['de' => 'Data: Contract ohne BP ist Extract-Fehler.', 'en' => 'Data: Contract without BP is an extract error.'],
                    'checks' => ['de' => 'contract.BP_ID IS NULL OR BP_ID NOT IN dim_business_partner', 'en' => 'contract.BP_ID IS NULL OR BP_ID NOT IN dim_business_partner'],
                    'fixInSource' => ['de' => 'Re-extract; repair BP link in Avaloq.', 'en' => 'Re-extract; repair BP link in Avaloq.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown BP dim.', 'en' => 'Quarantine; Unknown BP dim.'],
                ],
                [
                    'id' => 'avaloq-negative-balance-no-limit',
                    'priority' => 'high',
                    'title' => ['de' => 'Negativer Saldo ohne Limit', 'en' => 'Negative balance without limit'],
                    'problem' => ['de' => 'Overdrafts ohne LIMIT verzerren Credit-Risk- und Utilization-KPIs.', 'en' => 'Overdrafts without a LIMIT distort credit-risk and utilization KPIs.'],
                    'prevent' => ['de' => 'Overdraft-Facility Pflicht vor Freigabe.', 'en' => 'Require overdraft facility before approval.'],
                    'staffNeedToKnow' => ['de' => 'Credit Risk: Unauthorized Overdrafts separat tracken.', 'en' => 'Credit risk: track unauthorized overdrafts separately.'],
                    'checks' => ['de' => 'balance.BALANCE_AMOUNT < 0 AND NOT EXISTS (SELECT 1 FROM limit WHERE limit.BP_ID = contract.BP_ID)', 'en' => 'balance.BALANCE_AMOUNT < 0 AND NOT EXISTS (SELECT 1 FROM limit WHERE limit.BP_ID = contract.BP_ID)'],
                    'fixInSource' => ['de' => 'Assign limit or block further debits.', 'en' => 'Assign limit or block further debits.'],
                    'fixInWarehouse' => ['de' => 'Flag unauthorized_overdraft; exclude from authorized utilization KPI.', 'en' => 'Flag unauthorized_overdraft; exclude from authorized utilization KPI.'],
                ],
                [
                    'id' => 'avaloq-booking-no-contract',
                    'priority' => 'high',
                    'title' => ['de' => 'Booking ohne Contract', 'en' => 'Booking without contract'],
                    'problem' => ['de' => 'Bookings ohne CONTRACT_ID brechen Ledger-Fact-Joins.', 'en' => 'Bookings without CONTRACT_ID break ledger fact joins.'],
                    'prevent' => ['de' => 'Extract: CONTRACT_ID Pflichtfeld; closed contracts separat behandeln.', 'en' => 'Extract: CONTRACT_ID required field; handle closed contracts separately.'],
                    'staffNeedToKnow' => ['de' => 'Data: Orphan Bookings vs. Closed Contracts trennen.', 'en' => 'Data: Separate orphan bookings vs closed contracts.'],
                    'checks' => ['de' => 'booking.CONTRACT_ID IS NULL OR CONTRACT_ID NOT IN dim_contract', 'en' => 'booking.CONTRACT_ID IS NULL OR CONTRACT_ID NOT IN dim_contract'],
                    'fixInSource' => ['de' => 'Re-extract with contract history.', 'en' => 'Re-extract with contract history.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown contract dim.', 'en' => 'Quarantine; Unknown contract dim.'],
                ],
                [
                    'id' => 'avaloq-contract-type-product-mismatch',
                    'priority' => 'medium',
                    'title' => ['de' => 'Contract Type / Product Line Mismatch', 'en' => 'Contract type / product line mismatch'],
                    'problem' => ['de' => 'CONTRACT_TYPE weicht von PRODUCT_LINE des zugeordneten Products ab — Reporting-Widerspruch.', 'en' => 'CONTRACT_TYPE diverges from the assigned product PRODUCT_LINE — reporting contradiction.'],
                    'prevent' => ['de' => 'Product-Contract-Type Mapping Validierung bei Contract Creation.', 'en' => 'Validate product-contract-type mapping at contract creation.'],
                    'staffNeedToKnow' => ['de' => 'Product Team: Mapping-Tabelle pflegen und reviewen.', 'en' => 'Product team: maintain and review the mapping table.'],
                    'checks' => ['de' => 'contract.CONTRACT_TYPE <> product.PRODUCT_LINE (per mapping table)', 'en' => 'contract.CONTRACT_TYPE <> product.PRODUCT_LINE (per mapping table)'],
                    'fixInSource' => ['de' => 'Correct product assignment or contract type.', 'en' => 'Correct product assignment or contract type.'],
                    'fixInWarehouse' => ['de' => 'Flag type_mismatch; exclude from product-mix KPI until resolved.', 'en' => 'Flag type_mismatch; exclude from product-mix KPI until resolved.'],
                ],
                [
                    'id' => 'avaloq-duplicate-bp-tax-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte TAX_ID über mehrere Business Partner', 'en' => 'Duplicate TAX_ID across multiple business partners'],
                    'problem' => ['de' => 'Mehrere BP_ID mit gleicher TAX_ID verzerren Customer-Counts und KYC-Reviews.', 'en' => 'Multiple BP_ID with the same TAX_ID distort customer counts and KYC reviews.'],
                    'prevent' => ['de' => 'Uniqueness-Check auf TAX_ID bei BP Creation.', 'en' => 'Uniqueness check on TAX_ID at BP creation.'],
                    'staffNeedToKnow' => ['de' => 'Onboarding: TAX_ID vor Neuanlage prüfen.', 'en' => 'Onboarding: Check TAX_ID before creating a new record.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY TAX_ID HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY TAX_ID HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Merge duplicate BP records.', 'en' => 'Merge duplicate BP records.'],
                    'fixInWarehouse' => ['de' => 'Golden BP id; TAX_ID-hash merge map.', 'en' => 'Golden BP id; TAX_ID-hash merge map.'],
                ],
                [
                    'id' => 'avaloq-stale-balance-snapshot',
                    'priority' => 'medium',
                    'title' => ['de' => 'Veralteter Balance Snapshot', 'en' => 'Stale balance snapshot'],
                    'problem' => ['de' => 'Contracts ohne aktuellen Balance Snapshot verzerren Average-Balance-KPIs.', 'en' => 'Contracts without a current balance snapshot distort average-balance KPIs.'],
                    'prevent' => ['de' => 'Tägliches Balance-Snapshot-Batch je aktivem Contract sicherstellen.', 'en' => 'Ensure a daily balance-snapshot batch for every active contract.'],
                    'staffNeedToKnow' => ['de' => 'Batch Ops: Snapshot-Job-Failures sofort untersuchen.', 'en' => 'Batch ops: Investigate snapshot job failures immediately.'],
                    'checks' => ['de' => "contract.STATUS = 'active' AND latest_balance.BALANCE_DATE < CURRENT_DATE - 1", 'en' => "contract.STATUS = 'active' AND latest_balance.BALANCE_DATE < CURRENT_DATE - 1"],
                    'fixInSource' => ['de' => 'Re-run balance snapshot batch.', 'en' => 'Re-run balance snapshot batch.'],
                    'fixInWarehouse' => ['de' => 'Flag stale_balance; exclude from average-balance KPI until refreshed.', 'en' => 'Flag stale_balance; exclude from average-balance KPI until refreshed.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'avaloq-bp-dup',
                    'entity' => 'Business partner',
                    'title' => ['de' => 'Business-Partner-Duplikate', 'en' => 'Business partner duplicates'],
                    'matchKeys' => ['BP_ID', 'TAX_ID', 'NAME', 'DATE_OF_BIRTH'],
                    'preventInSource' => ['de' => 'BP uniqueness check on TAX_ID; merge workflow for re-onboarding.', 'en' => 'BP uniqueness check on TAX_ID; merge workflow for re-onboarding.'],
                    'resolveInWarehouse' => ['de' => 'Golden BP id; TAX_ID-hash merge map.', 'en' => 'Golden BP id; TAX_ID-hash merge map.'],
                    'survivorship' => ['de' => 'BP mit aktivsten Contracts gewinnt.', 'en' => 'BP with the most active contracts wins.'],
                ],
                [
                    'id' => 'avaloq-contract-type-map',
                    'entity' => 'Contract / Product',
                    'title' => ['de' => 'Contract Type / Product Mapping Drift', 'en' => 'Contract type / product mapping drift'],
                    'matchKeys' => ['CONTRACT_ID', 'PRODUCT_ID', 'CONTRACT_TYPE'],
                    'preventInSource' => ['de' => 'Stable product catalog; controlled contract type changes.', 'en' => 'Stable product catalog; controlled contract type changes.'],
                    'resolveInWarehouse' => ['de' => 'Canonical product id; SCD2 contract type.', 'en' => 'Canonical product id; SCD2 contract type.'],
                    'survivorship' => ['de' => 'Aktuelle Product-Zuordnung gewinnt über Legacy-Mapping.', 'en' => 'Current product mapping wins over legacy mapping.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'avaloq-limit-renewal-policy',
                    'area' => ['de' => 'Credit → Limits', 'en' => 'Credit → Limits'],
                    'setting' => ['de' => 'Limit Renewal Workflow und Auto-Block bei Expiry', 'en' => 'Limit renewal workflow and auto-block on expiry'],
                    'why' => ['de' => 'Verhindert Expired-Limit-Still-In-Use DQ Failures.', 'en' => 'Prevents expired-limit-still-in-use DQ failures.'],
                    'how' => ['de' => 'Configure renewal reminders; enforce block on lapse.', 'en' => 'Configure renewal reminders; enforce block on lapse.'],
                ],
                [
                    'id' => 'avaloq-bp-dedup',
                    'area' => ['de' => 'Business partner → Onboarding', 'en' => 'Business partner → Onboarding'],
                    'setting' => ['de' => 'TAX_ID Uniqueness Check bei Onboarding', 'en' => 'TAX_ID uniqueness check at onboarding'],
                    'why' => ['de' => 'Reduziert BP-Duplikate und KYC-Review-Aufwand.', 'en' => 'Reduces BP duplicates and KYC review effort.'],
                    'how' => ['de' => 'Enable duplicate-check screen; enforce merge before create.', 'en' => 'Enable duplicate-check screen; enforce merge before create.'],
                ],
                [
                    'id' => 'avaloq-balance-snapshot-batch',
                    'area' => ['de' => 'Batch → Balance snapshot job', 'en' => 'Batch → Balance snapshot job'],
                    'setting' => ['de' => 'Tägliches Balance-Snapshot-Monitoring und Retry-Policy', 'en' => 'Daily balance-snapshot monitoring and retry policy'],
                    'why' => ['de' => 'Verhindert veraltete Balance Snapshots in Average-Balance-KPIs.', 'en' => 'Prevents stale balance snapshots in average-balance KPIs.'],
                    'how' => ['de' => 'Alert on job failure; auto-retry; escalate after 2 failures.', 'en' => 'Alert on job failure; auto-retry; escalate after 2 failures.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'avaloq-data-dictionary',
                    'kind' => ['de' => 'Avaloq data dictionary', 'en' => 'Avaloq data dictionary'],
                    'where' => ['de' => 'Avaloq Script / Business Data Model documentation', 'en' => 'Avaloq Script / Business Data Model documentation'],
                    'how' => ['de' => 'Field/Table Definitionen inventarisieren; Business Data Model Views dokumentieren.', 'en' => 'Inventory field/table definitions; document Business Data Model views.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (BP_ID, CONTRACT_ID).', 'en' => 'Extract design, PII tags, join keys (BP_ID, CONTRACT_ID).'],
                    'watchouts' => ['de' => 'Business Data Model Views können sich per Release ändern.', 'en' => 'Business Data Model views can change per release.'],
                ],
                [
                    'id' => 'avaloq-product-catalog',
                    'kind' => ['de' => 'Product catalog', 'en' => 'Product catalog'],
                    'where' => ['de' => 'Avaloq → Product Management module', 'en' => 'Avaloq → Product Management module'],
                    'how' => ['de' => 'Product Bundles und Contract-Type-Mapping dokumentieren.', 'en' => 'Document product bundles and contract-type mapping.'],
                    'useFor' => ['de' => 'Product dim, product-mix KPIs, contract joins.', 'en' => 'Product dim, product-mix KPIs, contract joins.'],
                    'watchouts' => ['de' => 'Product Line Renames — SCD2 empfohlen.', 'en' => 'Product line renames — SCD2 recommended.'],
                ],
                [
                    'id' => 'avaloq-bi-layer-schema',
                    'kind' => ['de' => 'Business Intelligence layer schema', 'en' => 'Business Intelligence layer schema'],
                    'where' => ['de' => 'Avaloq → BI Layer / Reporting Database views', 'en' => 'Avaloq → BI layer / reporting database views'],
                    'how' => ['de' => 'Reporting Views als Field-Referenz nutzen — Content-Freitext meiden.', 'en' => 'Use reporting views as field reference — avoid content free text.'],
                    'useFor' => ['de' => 'Extract allowlist, join keys, dimension enrichment.', 'en' => 'Extract allowlist, join keys, dimension enrichment.'],
                    'watchouts' => ['de' => 'BI-Layer-Views können bereits aggregierte PII enthalten — prüfen.', 'en' => 'BI-layer views may already contain aggregated PII — check.'],
                ],
                [
                    'id' => 'avaloq-reference-tables',
                    'kind' => ['de' => 'Reference / enum tables', 'en' => 'Reference / enum tables'],
                    'where' => ['de' => 'Avaloq → SEGMENT, CONTRACT_TYPE, CURRENCY reference tables', 'en' => 'Avaloq → SEGMENT, CONTRACT_TYPE, CURRENCY reference tables'],
                    'how' => ['de' => 'Code-zu-Beschreibung-Mappings exportieren.', 'en' => 'Export code-to-description mappings.'],
                    'useFor' => ['de' => 'Dimension enrichment (segment, contract type labels).', 'en' => 'Dimension enrichment (segment, contract type labels).'],
                    'watchouts' => ['de' => 'Reference-Codes können sich per Instance/Region unterscheiden.', 'en' => 'Reference codes can differ per instance/region.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'thought-machine' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'vault-account-no-customer',
                    'priority' => 'high',
                    'title' => ['de' => 'Account ohne Customer', 'en' => 'Account without customer'],
                    'problem' => ['de' => 'Accounts ohne auflösbaren customer_id brechen Customer-360 Joins.', 'en' => 'Accounts without a resolvable customer_id break customer-360 joins.'],
                    'prevent' => ['de' => 'Core API: customer_id/stakeholder_ids Pflichtfeld bei Account Creation.', 'en' => 'Core API: customer_id/stakeholder_ids required field at account creation.'],
                    'staffNeedToKnow' => ['de' => 'Data: Account ohne Customer ist Integrations-Fehler.', 'en' => 'Data: Account without customer is an integration error.'],
                    'checks' => ['de' => 'account.customer_id IS NULL OR customer_id NOT IN dim_customer', 'en' => 'account.customer_id IS NULL OR customer_id NOT IN dim_customer'],
                    'fixInSource' => ['de' => 'Re-extract; repair stakeholder link via Core API.', 'en' => 'Re-extract; repair stakeholder link via Core API.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown customer dim.', 'en' => 'Quarantine; Unknown customer dim.'],
                ],
                [
                    'id' => 'vault-posting-unbalanced',
                    'priority' => 'high',
                    'title' => ['de' => 'Posting Instruction Batch nicht ausgeglichen', 'en' => 'Posting instruction batch not balanced'],
                    'problem' => ['de' => 'Nicht ausgeglichene Postings (Debit ≠ Credit je Denomination) brechen Ledger-Integrität.', 'en' => 'Unbalanced postings (debit ≠ credit per denomination) break ledger integrity.'],
                    'prevent' => ['de' => 'Vault erzwingt Double-Entry — Reject/Alert bei fehlgeschlagener Validierung überwachen.', 'en' => 'Vault enforces double-entry — monitor reject/alert on failed validation.'],
                    'staffNeedToKnow' => ['de' => 'Ledger Ops: Rejected PIBs sofort untersuchen.', 'en' => 'Ledger ops: Investigate rejected PIBs immediately.'],
                    'checks' => ['de' => 'SUM(amount) PER pib_id, denomination <> 0', 'en' => 'SUM(amount) PER pib_id, denomination <> 0'],
                    'fixInSource' => ['de' => 'Investigate contract logic; resubmit corrected PIB.', 'en' => 'Investigate contract logic; resubmit corrected PIB.'],
                    'fixInWarehouse' => ['de' => 'Quarantine unbalanced batch; exclude from ledger facts.', 'en' => 'Quarantine unbalanced batch; exclude from ledger facts.'],
                ],
                [
                    'id' => 'vault-restriction-no-account',
                    'priority' => 'medium',
                    'title' => ['de' => 'Restriction ohne Account', 'en' => 'Restriction without account'],
                    'problem' => ['de' => 'Restrictions ohne account_id verzerren Hold/Block-Coverage-KPIs.', 'en' => 'Restrictions without account_id distort hold/block coverage KPIs.'],
                    'prevent' => ['de' => 'Restriction API: account_id Pflichtfeld.', 'en' => 'Restriction API: account_id required field.'],
                    'staffNeedToKnow' => ['de' => 'Compliance: Orphan Restrictions sofort reviewen.', 'en' => 'Compliance: Review orphan restrictions immediately.'],
                    'checks' => ['de' => 'restriction.account_id IS NULL', 'en' => 'restriction.account_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-apply restriction with correct account context.', 'en' => 'Re-apply restriction with correct account context.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from coverage KPI.', 'en' => 'Quarantine; exclude from coverage KPI.'],
                ],
                [
                    'id' => 'vault-account-closed-with-postings',
                    'priority' => 'high',
                    'title' => ['de' => 'Geschlossener Account mit neuen Postings', 'en' => 'Closed account with new postings'],
                    'problem' => ['de' => 'Postings nach Account-Closure sind ein Integritätsverstoß und verzerren Ledger-KPIs.', 'en' => 'Postings after account closure are an integrity violation and distort ledger KPIs.'],
                    'prevent' => ['de' => 'Vault Contract-Logic: Reject Postings auf CLOSED Accounts.', 'en' => 'Vault contract logic: reject postings on CLOSED accounts.'],
                    'staffNeedToKnow' => ['de' => 'Ledger Ops: Post-Closure Postings sofort eskalieren.', 'en' => 'Ledger ops: Escalate post-closure postings immediately.'],
                    'checks' => ['de' => "account.status = 'ACCOUNT_STATUS_CLOSED' AND posting.value_timestamp > account.closure_timestamp", 'en' => "account.status = 'ACCOUNT_STATUS_CLOSED' AND posting.value_timestamp > account.closure_timestamp"],
                    'fixInSource' => ['de' => 'Investigate contract/workflow bug; reverse erroneous postings.', 'en' => 'Investigate contract/workflow bug; reverse erroneous postings.'],
                    'fixInWarehouse' => ['de' => 'Flag post_closure_posting; exclude from active ledger facts.', 'en' => 'Flag post_closure_posting; exclude from active ledger facts.'],
                ],
                [
                    'id' => 'vault-duplicate-client-transaction-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte client_transaction_id im Extract', 'en' => 'Duplicate client_transaction_id in extract'],
                    'problem' => ['de' => 'Doppelte client_transaction_id verzerren Posting Counts und Idempotenz-Annahmen.', 'en' => 'Duplicate client_transaction_id distort posting counts and idempotency assumptions.'],
                    'prevent' => ['de' => 'Idempotent load key; API pagination overlap prüfen.', 'en' => 'Idempotent load key; check API pagination overlap.'],
                    'staffNeedToKnow' => ['de' => 'Data: Natural Key = client_transaction_id.', 'en' => 'Data: Natural key = client_transaction_id.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY client_transaction_id HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY client_transaction_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate Postings API pagination.', 'en' => 'Re-extract; investigate Postings API pagination.'],
                    'fixInWarehouse' => ['de' => 'Dedup by client_transaction_id; keep latest _loaded_at.', 'en' => 'Dedup by client_transaction_id; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'vault-customer-dup',
                    'entity' => 'Customer',
                    'title' => ['de' => 'Customer-Duplikate', 'en' => 'Customer duplicates'],
                    'matchKeys' => ['id', 'given_name+family_name+date_of_birth', 'contact_details.emails (hashed)'],
                    'preventInSource' => ['de' => 'Upstream CRM/KYC as source of truth; dedup before Vault customer create.', 'en' => 'Upstream CRM/KYC as source of truth; dedup before Vault customer create.'],
                    'resolveInWarehouse' => ['de' => 'Golden customer id; email-hash merge map.', 'en' => 'Golden customer id; email-hash merge map.'],
                    'survivorship' => ['de' => 'Customer mit aktivsten Accounts gewinnt.', 'en' => 'Customer with the most active accounts wins.'],
                ],
                [
                    'id' => 'vault-product-version-map',
                    'entity' => 'Product version',
                    'title' => ['de' => 'Product Version Lineage Drift', 'en' => 'Product version lineage drift'],
                    'matchKeys' => ['product_id', 'product_version_id'],
                    'preventInSource' => ['de' => 'Controlled Smart Contract deployment; version migration plans.', 'en' => 'Controlled smart contract deployment; version migration plans.'],
                    'resolveInWarehouse' => ['de' => 'Canonical product id; SCD2 product_version_id lineage.', 'en' => 'Canonical product id; SCD2 product_version_id lineage.'],
                    'survivorship' => ['de' => 'Aktuellste Product Version je Account gewinnt für Reporting.', 'en' => 'Latest product version per account wins for reporting.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'vault-contract-reject-alerts',
                    'area' => ['de' => 'Ops Dashboard → Posting rejections', 'en' => 'Ops Dashboard → Posting rejections'],
                    'setting' => ['de' => 'Alerting auf Rejected/Unbalanced Posting Instruction Batches', 'en' => 'Alerting on rejected/unbalanced posting instruction batches'],
                    'why' => ['de' => 'Verhindert unentdeckte Ledger-Integritätsverletzungen.', 'en' => 'Prevents undetected ledger integrity violations.'],
                    'how' => ['de' => 'Configure ops dashboard alerts; escalate on threshold.', 'en' => 'Configure ops dashboard alerts; escalate on threshold.'],
                ],
                [
                    'id' => 'vault-restriction-governance',
                    'area' => ['de' => 'Compliance → Restrictions framework', 'en' => 'Compliance → Restrictions framework'],
                    'setting' => ['de' => 'Restriction Definition Versioning und Account-Context-Pflicht', 'en' => 'Restriction definition versioning and mandatory account context'],
                    'why' => ['de' => 'Hold/Block-Coverage-KPIs bleiben verlässlich.', 'en' => 'Hold/block coverage KPIs stay reliable.'],
                    'how' => ['de' => 'Enforce account_id on restriction apply; review orphan restrictions.', 'en' => 'Enforce account_id on restriction apply; review orphan restrictions.'],
                ],
                [
                    'id' => 'vault-payment-device-tokenization',
                    'area' => ['de' => 'Payments → Payment device / tokenization', 'en' => 'Payments → Payment device / tokenization'],
                    'setting' => ['de' => 'Tokenization-Service statt PAN-Storage; kein Token-Export ins Warehouse', 'en' => 'Tokenization service instead of PAN storage; no token export into the warehouse'],
                    'why' => ['de' => 'Device-KPIs ohne Kartendaten im Warehouse.', 'en' => 'Device KPIs without card data in the warehouse.'],
                    'how' => ['de' => 'Integrate tokenization vault; extract device status only.', 'en' => 'Integrate tokenization vault; extract device status only.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'vault-core-api-schema',
                    'kind' => ['de' => 'Vault Core API schema', 'en' => 'Vault Core API schema'],
                    'where' => ['de' => 'Thought Machine Docs → Core API reference (Customer, Account, Postings)', 'en' => 'Thought Machine Docs → Core API reference (Customer, Account, Postings)'],
                    'how' => ['de' => 'Object Fields inventarisieren; Select-Allowlist für Extract.', 'en' => 'Inventory object fields; select allowlist for extract.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (customer_id, account_id).', 'en' => 'Extract design, PII tags, join keys (customer_id, account_id).'],
                    'watchouts' => ['de' => 'Keine Payment Device Tokens/PAN selektieren.', 'en' => 'Do not select payment device tokens/PAN.'],
                ],
                [
                    'id' => 'vault-smart-contract-metadata',
                    'kind' => ['de' => 'Smart Contract product library metadata', 'en' => 'Smart Contract product library metadata'],
                    'where' => ['de' => 'Vault → Product Library; Contract Version Registry', 'en' => 'Vault → Product Library; contract version registry'],
                    'how' => ['de' => 'Product/Version Metadata dokumentieren — keinen Contract-Code exportieren.', 'en' => 'Document product/version metadata — do not export contract code.'],
                    'useFor' => ['de' => 'Product version dim, lineage, product-mix KPIs.', 'en' => 'Product version dim, lineage, product-mix KPIs.'],
                    'watchouts' => ['de' => 'Contract-Code ≠ Analytics-Metadata — strikt trennen.', 'en' => 'Contract code ≠ analytics metadata — strictly separate.'],
                ],
                [
                    'id' => 'vault-balance-definitions',
                    'kind' => ['de' => 'Balance definitions', 'en' => 'Balance definitions'],
                    'where' => ['de' => 'Vault → Balance Definition configuration (per product version)', 'en' => 'Vault → balance definition configuration (per product version)'],
                    'how' => ['de' => 'Balance Definition IDs und Phasen dokumentieren.', 'en' => 'Document balance definition IDs and phases.'],
                    'useFor' => ['de' => 'Balance facts, average-balance KPIs, overdraft detection.', 'en' => 'Balance facts, average-balance KPIs, overdraft detection.'],
                    'watchouts' => ['de' => 'Verschiedene Balance Definitions pro Product Version nicht mischen.', 'en' => 'Do not mix different balance definitions per product version.'],
                ],
                [
                    'id' => 'vault-streaming-schema',
                    'kind' => ['de' => 'Streaming API schema (Kafka topics)', 'en' => 'Streaming API schema (Kafka topics)'],
                    'where' => ['de' => 'Vault → Streaming API topics (account, posting, customer events)', 'en' => 'Vault → Streaming API topics (account, posting, customer events)'],
                    'how' => ['de' => 'Event Schema Registry als Field-Referenz nutzen.', 'en' => 'Use event schema registry as field reference.'],
                    'useFor' => ['de' => 'Near-real-time fact loads, event-driven dimension enrichment.', 'en' => 'Near-real-time fact loads, event-driven dimension enrichment.'],
                    'watchouts' => ['de' => 'Event Payloads können Full Object State enthalten — Field Allowlist.', 'en' => 'Event payloads can contain full object state — field allowlist.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'finastra' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'finastra-account-no-cif',
                    'priority' => 'high',
                    'title' => ['de' => 'Account ohne CIF', 'en' => 'Account without CIF'],
                    'problem' => ['de' => 'Accounts ohne aufgelöste CIFNumber brechen Customer-360 Joins.', 'en' => 'Accounts without a resolvable CIFNumber break customer-360 joins.'],
                    'prevent' => ['de' => 'Extract: CIFNumber immer mitladen; Joint Accounts separat kennzeichnen.', 'en' => 'Extract: always load CIFNumber; flag joint accounts separately.'],
                    'staffNeedToKnow' => ['de' => 'Data: Account ohne CIF ist Extract-/Migrations-Artefakt.', 'en' => 'Data: Account without CIF is an extract/migration artifact.'],
                    'checks' => ['de' => 'account.CIFNumber IS NULL OR CIFNumber NOT IN dim_customer', 'en' => 'account.CIFNumber IS NULL OR CIFNumber NOT IN dim_customer'],
                    'fixInSource' => ['de' => 'Re-extract; repair CIF link in Fusion.', 'en' => 'Re-extract; repair CIF link in Fusion.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown customer dim.', 'en' => 'Quarantine; Unknown customer dim.'],
                ],
                [
                    'id' => 'finastra-gl-entry-unbalanced',
                    'priority' => 'high',
                    'title' => ['de' => 'GL Entry Batch nicht ausgeglichen', 'en' => 'GL entry batch not balanced'],
                    'problem' => ['de' => 'Nicht ausgeglichene Dr/Cr Batches brechen Ledger-Integrität und Reconciliation.', 'en' => 'Unbalanced Dr/Cr batches break ledger integrity and reconciliation.'],
                    'prevent' => ['de' => 'Double-Entry-Validation im Posting-Engine erzwingen.', 'en' => 'Enforce double-entry validation in the posting engine.'],
                    'staffNeedToKnow' => ['de' => 'Ledger Ops: Rejected Batches sofort untersuchen.', 'en' => 'Ledger ops: Investigate rejected batches immediately.'],
                    'checks' => ['de' => "SUM(CASE WHEN DrCrIndicator = 'D' THEN Amount ELSE -Amount END) PER batch_id <> 0", 'en' => "SUM(CASE WHEN DrCrIndicator = 'D' THEN Amount ELSE -Amount END) PER batch_id <> 0"],
                    'fixInSource' => ['de' => 'Investigate posting engine logic; resubmit corrected batch.', 'en' => 'Investigate posting engine logic; resubmit corrected batch.'],
                    'fixInWarehouse' => ['de' => 'Quarantine unbalanced batch; exclude from ledger facts.', 'en' => 'Quarantine unbalanced batch; exclude from ledger facts.'],
                ],
                [
                    'id' => 'finastra-facility-no-product',
                    'priority' => 'medium',
                    'title' => ['de' => 'Facility ohne Product', 'en' => 'Facility without product'],
                    'problem' => ['de' => 'Facilities ohne ProductCode-Link brechen Product-Mix-Reports.', 'en' => 'Facilities without a ProductCode link break product-mix reports.'],
                    'prevent' => ['de' => 'ProductCode Pflichtfeld bei Facility Creation.', 'en' => 'Require ProductCode field on facility creation.'],
                    'staffNeedToKnow' => ['de' => 'Product Team: Keine Facility ohne Product-Zuordnung.', 'en' => 'Product team: No facility without a product assignment.'],
                    'checks' => ['de' => 'facility.ProductCode IS NULL', 'en' => 'facility.ProductCode IS NULL'],
                    'fixInSource' => ['de' => 'Re-map product; correct product configuration.', 'en' => 'Re-map product; correct product configuration.'],
                    'fixInWarehouse' => ['de' => 'Unknown product dim; exclude from product-mix KPI.', 'en' => 'Unknown product dim; exclude from product-mix KPI.'],
                ],
                [
                    'id' => 'finastra-limit-expired-still-used',
                    'priority' => 'medium',
                    'title' => ['de' => 'Abgelaufenes Limit noch in Nutzung', 'en' => 'Expired limit still in use'],
                    'problem' => ['de' => 'Accounts nutzen Limits nach ExpiryDate weiter — Credit-Risk-Exposure ungetrackt.', 'en' => 'Accounts continue using limits past ExpiryDate — untracked credit-risk exposure.'],
                    'prevent' => ['de' => 'Limit renewal workflow; auto-block bei Expiry ohne Renewal.', 'en' => 'Limit renewal workflow; auto-block on expiry without renewal.'],
                    'staffNeedToKnow' => ['de' => 'Credit Risk: Expired Limits vor Nutzung reviewen.', 'en' => 'Credit risk: Review expired limits before use.'],
                    'checks' => ['de' => 'limit.ExpiryDate < CURRENT_DATE AND linked_account.Balance < 0', 'en' => 'limit.ExpiryDate < CURRENT_DATE AND linked_account.Balance < 0'],
                    'fixInSource' => ['de' => 'Renew or revoke limit; enforce block.', 'en' => 'Renew or revoke limit; enforce block.'],
                    'fixInWarehouse' => ['de' => 'Flag expired_limit_in_use; separate exposure KPI.', 'en' => 'Flag expired_limit_in_use; separate exposure KPI.'],
                ],
                [
                    'id' => 'finastra-duplicate-cif-tax-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte TaxId über mehrere CIF', 'en' => 'Duplicate TaxId across multiple CIFs'],
                    'problem' => ['de' => 'Mehrere CIFNumber mit gleicher TaxId verzerren Customer-Counts und KYC-Reviews.', 'en' => 'Multiple CIFNumber with the same TaxId distort customer counts and KYC reviews.'],
                    'prevent' => ['de' => 'Uniqueness-Check auf TaxId bei CIF Creation.', 'en' => 'Uniqueness check on TaxId at CIF creation.'],
                    'staffNeedToKnow' => ['de' => 'Onboarding: TaxId vor Neuanlage prüfen.', 'en' => 'Onboarding: Check TaxId before creating a new record.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY TaxId HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY TaxId HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Merge duplicate CIF records.', 'en' => 'Merge duplicate CIF records.'],
                    'fixInWarehouse' => ['de' => 'Golden customer id; TaxId-hash merge map.', 'en' => 'Golden customer id; TaxId-hash merge map.'],
                ],
                [
                    'id' => 'finastra-gl-entry-orphan-account',
                    'priority' => 'high',
                    'title' => ['de' => 'GL Entry ohne Account', 'en' => 'GL entry without account'],
                    'problem' => ['de' => 'Postings ohne auflösbaren AccountNumber brechen Ledger-Fact-Joins.', 'en' => 'Postings without a resolvable AccountNumber break ledger fact joins.'],
                    'prevent' => ['de' => 'Extract: AccountNumber Pflichtfeld; closed accounts separat behandeln.', 'en' => 'Extract: AccountNumber required field; handle closed accounts separately.'],
                    'staffNeedToKnow' => ['de' => 'Data: Orphan GL Entries vs. Closed Accounts trennen.', 'en' => 'Data: Separate orphan GL entries vs closed accounts.'],
                    'checks' => ['de' => 'gl_entry.AccountNumber IS NULL OR AccountNumber NOT IN dim_account', 'en' => 'gl_entry.AccountNumber IS NULL OR AccountNumber NOT IN dim_account'],
                    'fixInSource' => ['de' => 'Re-extract with account history.', 'en' => 'Re-extract with account history.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown account dim.', 'en' => 'Quarantine; Unknown account dim.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'finastra-customer-dup',
                    'entity' => 'Customer (CIF)',
                    'title' => ['de' => 'Customer-Duplikate', 'en' => 'Customer duplicates'],
                    'matchKeys' => ['CIFNumber', 'TaxId', 'ShortName', 'DateOfBirth'],
                    'preventInSource' => ['de' => 'CIF uniqueness check on TaxId; merge workflow for re-onboarding.', 'en' => 'CIF uniqueness check on TaxId; merge workflow for re-onboarding.'],
                    'resolveInWarehouse' => ['de' => 'Golden customer id; TaxId-hash merge map.', 'en' => 'Golden customer id; TaxId-hash merge map.'],
                    'survivorship' => ['de' => 'Customer mit aktivsten Accounts/Facilities gewinnt.', 'en' => 'Customer with the most active accounts/facilities wins.'],
                ],
                [
                    'id' => 'finastra-facility-product-map',
                    'entity' => 'Facility / Product',
                    'title' => ['de' => 'Facility-Product Mapping Drift', 'en' => 'Facility-product mapping drift'],
                    'matchKeys' => ['FacilityId', 'ProductCode', 'ProductLine'],
                    'preventInSource' => ['de' => 'Stable product configuration; controlled product line changes.', 'en' => 'Stable product configuration; controlled product line changes.'],
                    'resolveInWarehouse' => ['de' => 'Canonical product id; SCD2 product line.', 'en' => 'Canonical product id; SCD2 product line.'],
                    'survivorship' => ['de' => 'Aktuelle Product-Zuordnung gewinnt über Legacy-Mapping.', 'en' => 'Current product mapping wins over legacy mapping.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'finastra-limit-renewal-policy',
                    'area' => ['de' => 'Credit → Limits & facilities', 'en' => 'Credit → Limits & facilities'],
                    'setting' => ['de' => 'Limit Renewal Workflow und Auto-Block bei Expiry', 'en' => 'Limit renewal workflow and auto-block on expiry'],
                    'why' => ['de' => 'Verhindert Expired-Limit-Still-In-Use DQ Failures.', 'en' => 'Prevents expired-limit-still-in-use DQ failures.'],
                    'how' => ['de' => 'Configure renewal reminders; enforce block on lapse.', 'en' => 'Configure renewal reminders; enforce block on lapse.'],
                ],
                [
                    'id' => 'finastra-cif-dedup',
                    'area' => ['de' => 'Customer → CIF creation', 'en' => 'Customer → CIF creation'],
                    'setting' => ['de' => 'TaxId Uniqueness Check bei Onboarding', 'en' => 'TaxId uniqueness check at onboarding'],
                    'why' => ['de' => 'Reduziert Customer-Duplikate und KYC-Review-Aufwand.', 'en' => 'Reduces customer duplicates and KYC review effort.'],
                    'how' => ['de' => 'Enable duplicate-check screen; enforce merge before create.', 'en' => 'Enable duplicate-check screen; enforce merge before create.'],
                ],
                [
                    'id' => 'finastra-payment-message-retention',
                    'area' => ['de' => 'Payments → Message archive', 'en' => 'Payments → Message archive'],
                    'setting' => ['de' => 'Kurze Retention für Zahlungsnachrichten; keine Message-Exports ins Warehouse', 'en' => 'Short retention for payment messages; no message exports into the warehouse'],
                    'why' => ['de' => 'Ledger-KPIs ohne Klartext-Zahlungspayloads.', 'en' => 'Ledger KPIs without cleartext payment payloads.'],
                    'how' => ['de' => 'Archive policy on message store; extract status/reference fields only.', 'en' => 'Archive policy on message store; extract status/reference fields only.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'finastra-fusion-data-model',
                    'kind' => ['de' => 'Fusion data model documentation', 'en' => 'Fusion data model documentation'],
                    'where' => ['de' => 'Finastra Docs → Fusion Essence/Phoenix Data Model reference', 'en' => 'Finastra Docs → Fusion Essence/Phoenix data model reference'],
                    'how' => ['de' => 'Field/Table Definitionen inventarisieren; CIF/Account-Schema dokumentieren.', 'en' => 'Inventory field/table definitions; document CIF/account schema.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (CIFNumber, AccountNumber).', 'en' => 'Extract design, PII tags, join keys (CIFNumber, AccountNumber).'],
                    'watchouts' => ['de' => 'Feldnamen können sich zwischen Fusion-Editionen unterscheiden.', 'en' => 'Field names can differ between Fusion editions.'],
                ],
                [
                    'id' => 'finastra-product-catalog',
                    'kind' => ['de' => 'Product definition catalog', 'en' => 'Product definition catalog'],
                    'where' => ['de' => 'Finastra → Product Management module', 'en' => 'Finastra → Product Management module'],
                    'how' => ['de' => 'ProductCode/ProductLine Mapping dokumentieren.', 'en' => 'Document ProductCode/ProductLine mapping.'],
                    'useFor' => ['de' => 'Product dim, product-mix KPIs, facility joins.', 'en' => 'Product dim, product-mix KPIs, facility joins.'],
                    'watchouts' => ['de' => 'Product Line Renames — SCD2 empfohlen.', 'en' => 'Product line renames — SCD2 recommended.'],
                ],
                [
                    'id' => 'finastra-gl-chart-of-accounts',
                    'kind' => ['de' => 'GL chart of accounts', 'en' => 'GL chart of accounts'],
                    'where' => ['de' => 'Finastra → General Ledger → Chart of accounts configuration', 'en' => 'Finastra → General Ledger → chart of accounts configuration'],
                    'how' => ['de' => 'GL-Kontenrahmen und Dr/Cr-Konventionen dokumentieren.', 'en' => 'Document GL chart of accounts and Dr/Cr conventions.'],
                    'useFor' => ['de' => 'Ledger facts, reconciliation, GL-Entry-Dimensionen.', 'en' => 'Ledger facts, reconciliation, GL entry dimensions.'],
                    'watchouts' => ['de' => 'Kontenrahmen kann sich je Company/Region unterscheiden.', 'en' => 'Chart of accounts can differ per company/region.'],
                ],
                [
                    'id' => 'finastra-reference-tables',
                    'kind' => ['de' => 'Reference / enum tables', 'en' => 'Reference / enum tables'],
                    'where' => ['de' => 'Finastra → Segment, ProductLine, Currency reference tables', 'en' => 'Finastra → Segment, ProductLine, Currency reference tables'],
                    'how' => ['de' => 'Code-zu-Beschreibung-Mappings exportieren.', 'en' => 'Export code-to-description mappings.'],
                    'useFor' => ['de' => 'Dimension enrichment (segment, product line labels).', 'en' => 'Dimension enrichment (segment, product line labels).'],
                    'watchouts' => ['de' => 'Reference-Codes können sich per Deployment unterscheiden.', 'en' => 'Reference codes can differ per deployment.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],
];
