<?php

/**
 * Wave 5 quality overlays — Workplace/Identity source-native DQ, MDM, metadata guides.
 *
 * @return array<string, array<string, mixed>>
 */

return [
    'entra-id' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'entra-disabled-user-in-groups',
                    'priority' => 'high',
                    'title' => ['de' => 'Disabled User noch in Groups/Roles', 'en' => 'Disabled user still in groups/roles'],
                    'problem' => ['de' => 'Deaktivierte User in Groups/Directory Roles verzerren Access Reviews und Privilege Counts.', 'en' => 'Disabled users in groups/directory roles distort access reviews and privilege counts.'],
                    'prevent' => ['de' => 'Lifecycle Workflow: Group/Role Cleanup bei accountEnabled=false.', 'en' => 'Lifecycle workflow: group/role cleanup when accountEnabled=false.'],
                    'staffNeedToKnow' => ['de' => 'IAM: Disable ≠ Membership Cleanup — Reviews pflegen.', 'en' => 'IAM: Disable ≠ membership cleanup — maintain reviews.'],
                    'checks' => ['de' => 'accountEnabled = FALSE AND (group_membership_count > 0 OR role_assignment_count > 0)', 'en' => 'accountEnabled = FALSE AND (group_membership_count > 0 OR role_assignment_count > 0)'],
                    'fixInSource' => ['de' => 'Remove memberships; Access Reviews; lifecycle automation.', 'en' => 'Remove memberships; access reviews; lifecycle automation.'],
                    'fixInWarehouse' => ['de' => 'Flag stale_membership; exclude disabled from active entitlement KPIs.', 'en' => 'Flag stale_membership; exclude disabled from active entitlement KPIs.'],
                ],
                [
                    'id' => 'entra-user-no-upn',
                    'priority' => 'high',
                    'title' => ['de' => 'User ohne UPN', 'en' => 'User without UPN'],
                    'problem' => ['de' => 'Users ohne userPrincipalName brechen Sign-in Joins und Identity Matching.', 'en' => 'Users without userPrincipalName break sign-in joins and identity matching.'],
                    'prevent' => ['de' => 'Provisioning: UPN Pflicht; Sync-Fehler queue monitoren.', 'en' => 'Provisioning: UPN required; monitor sync error queues.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Kein User Create ohne UPN.', 'en' => 'Admins: No user create without UPN.'],
                    'checks' => ['de' => 'userPrincipalName IS NULL AND userType IS NOT NULL', 'en' => 'userPrincipalName IS NULL AND userType IS NOT NULL'],
                    'fixInSource' => ['de' => 'Fix in Entra / HR feed; re-sync.', 'en' => 'Fix in Entra / HR feed; re-sync.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown UPN bucket.', 'en' => 'Quarantine; Unknown UPN bucket.'],
                ],
                [
                    'id' => 'entra-guest-no-sponsor',
                    'priority' => 'medium',
                    'title' => ['de' => 'Guest ohne Sponsor / Invitation Status', 'en' => 'Guest without sponsor / invitation status'],
                    'problem' => ['de' => 'Guests ohne Sponsor oder hängende Invites schwächen B2B Governance.', 'en' => 'Guests without sponsor or pending invites weaken B2B governance.'],
                    'prevent' => ['de' => 'B2B Guest policies; sponsor required; invitation expiry.', 'en' => 'B2B guest policies; sponsor required; invitation expiry.'],
                    'staffNeedToKnow' => ['de' => 'IAM: Guests brauchen Sponsor und Redeem-SLA.', 'en' => 'IAM: Guests need sponsor and redeem SLA.'],
                    'checks' => ['de' => 'userType = \'Guest\' AND (sponsor_id IS NULL OR invitation_state = \'PendingAcceptance\' AND invited_at < CURRENT_DATE - 30)', 'en' => 'userType = \'Guest\' AND (sponsor_id IS NULL OR invitation_state = \'PendingAcceptance\' AND invited_at < CURRENT_DATE - 30)'],
                    'fixInSource' => ['de' => 'Assign sponsor; cancel stale invites.', 'en' => 'Assign sponsor; cancel stale invites.'],
                    'fixInWarehouse' => ['de' => 'Flag guest_governance_gap; separate pending invite KPI.', 'en' => 'Flag guest_governance_gap; separate pending invite KPI.'],
                ],
                [
                    'id' => 'entra-app-secret-expired',
                    'priority' => 'high',
                    'title' => ['de' => 'App Registration Secret/Cert abgelaufen oder bald fällig', 'en' => 'App registration secret/cert expired or near expiry'],
                    'problem' => ['de' => 'Abgelaufene Credentials brechen Integrationen; Secret Values dürfen trotzdem nie landen.', 'en' => 'Expired credentials break integrations; secret values must still never land.'],
                    'prevent' => ['de' => 'Credential expiry alerts; prefer certs/managed identities; rotate before endDateTime.', 'en' => 'Credential expiry alerts; prefer certs/managed identities; rotate before endDateTime.'],
                    'staffNeedToKnow' => ['de' => 'App Owners: Expiry Metadata tracken — nie Secret-Werte exportieren.', 'en' => 'App owners: Track expiry metadata — never export secret values.'],
                    'checks' => ['de' => 'credential_end_at < CURRENT_TIMESTAMP OR credential_end_at < CURRENT_TIMESTAMP + INTERVAL \'30 days\'', 'en' => 'credential_end_at < CURRENT_TIMESTAMP OR credential_end_at < CURRENT_TIMESTAMP + INTERVAL \'30 days\''],
                    'fixInSource' => ['de' => 'Rotate in App registrations; remove expired keys.', 'en' => 'Rotate in App registrations; remove expired keys.'],
                    'fixInWarehouse' => ['de' => 'Flag expiry from metadata only; never store secret material.', 'en' => 'Flag expiry from metadata only; never store secret material.'],
                ],
                [
                    'id' => 'entra-signin-no-user',
                    'priority' => 'medium',
                    'title' => ['de' => 'Sign-in Event ohne User Object', 'en' => 'Sign-in event without user object'],
                    'problem' => ['de' => 'Sign-ins ohne auflösbaren userId brechen Identity Activity Joins.', 'en' => 'Sign-ins without resolvable userId break identity activity joins.'],
                    'prevent' => ['de' => 'Graph extract: userId + correlation; soft-deleted users tracken.', 'en' => 'Graph extract: userId + correlation; track soft-deleted users.'],
                    'staffNeedToKnow' => ['de' => 'Security: Orphan Sign-ins vs Deleted Users trennen.', 'en' => 'Security: Separate orphan sign-ins vs deleted users.'],
                    'checks' => ['de' => 'signin.user_id IS NULL OR user_id NOT IN dim_user', 'en' => 'signin.user_id IS NULL OR user_id NOT IN dim_user'],
                    'fixInSource' => ['de' => 'Re-sync directory; include soft-deleted window if needed.', 'en' => 'Re-sync directory; include soft-deleted window if needed.'],
                    'fixInWarehouse' => ['de' => 'Unknown-user dim; exclude from per-user KPIs.', 'en' => 'Unknown-user dim; exclude from per-user KPIs.'],
                ],
                [
                    'id' => 'entra-ca-policy-orphan',
                    'priority' => 'medium',
                    'title' => ['de' => 'Conditional Access Policy ohne Assignments', 'en' => 'Conditional Access policy without assignments'],
                    'problem' => ['de' => 'CA Policies ohne Users/Groups/Applications Assignment sind toter Security-Config-Ballast.', 'en' => 'CA policies without users/groups/applications assignment are dead security config ballast.'],
                    'prevent' => ['de' => 'CA Review Cadence; report-only vor enforce; assignments Pflicht.', 'en' => 'CA review cadence; report-only before enforce; assignments required.'],
                    'staffNeedToKnow' => ['de' => 'Security: Keine leeren CA Policies in Prod.', 'en' => 'Security: No empty CA policies in prod.'],
                    'checks' => ['de' => 'state IN (\'enabled\',\'enabledForReportingButNotEnforced\') AND assignment_count = 0', 'en' => 'state IN (\'enabled\',\'enabledForReportingButNotEnforced\') AND assignment_count = 0'],
                    'fixInSource' => ['de' => 'Assign targets or disable policy.', 'en' => 'Assign targets or disable policy.'],
                    'fixInWarehouse' => ['de' => 'Flag orphan_ca_policy; exclude from coverage KPIs.', 'en' => 'Flag orphan_ca_policy; exclude from coverage KPIs.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'entra-user-dup',
                    'entity' => 'User',
                    'title' => ['de' => 'User-Duplikate / Rehire', 'en' => 'User duplicates / rehire'],
                    'matchKeys' => ['id', 'userPrincipalName', 'mail', 'employeeId', 'onPremisesImmutableId'],
                    'preventInSource' => ['de' => 'HR/Entra as source of truth; soft-delete instead of recreate.', 'en' => 'HR/Entra as source of truth; soft-delete instead of recreate.'],
                    'resolveInWarehouse' => ['de' => 'Golden object id; UPN-hash merge map.', 'en' => 'Golden object id; UPN-hash merge map.'],
                    'survivorship' => ['de' => 'Aktiver User (accountEnabled) mit neuester Sign-in Activity gewinnt.', 'en' => 'Active user (accountEnabled) with latest sign-in activity wins.'],
                ],
                [
                    'id' => 'entra-app-sp-map',
                    'entity' => 'Application / ServicePrincipal',
                    'title' => ['de' => 'App Registration vs Service Principal Mapping', 'en' => 'App registration vs service principal mapping'],
                    'matchKeys' => ['appId', 'application object id', 'servicePrincipal id'],
                    'preventInSource' => ['de' => 'Stable appId; one SP per tenant app instance.', 'en' => 'Stable appId; one SP per tenant app instance.'],
                    'resolveInWarehouse' => ['de' => 'Canonical appId → application_id / service_principal_id map.', 'en' => 'Canonical appId → application_id / service_principal_id map.'],
                    'survivorship' => ['de' => 'Enabled SP mit App Registration Link gewinnt.', 'en' => 'Enabled SP with app registration link wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'entra-lifecycle-workflows',
                    'area' => ['de' => 'Identity Governance → Lifecycle workflows', 'en' => 'Identity Governance → Lifecycle workflows'],
                    'setting' => ['de' => 'Joiner/Mover/Leaver: Group/Role Cleanup bei Disable', 'en' => 'Joiner/mover/leaver: group/role cleanup on disable'],
                    'why' => ['de' => 'Verhindert Disabled-User-in-Groups DQ Failures.', 'en' => 'Prevents disabled-user-in-groups DQ failures.'],
                    'how' => ['de' => 'Configure workflows; test in sandbox tenant.', 'en' => 'Configure workflows; test in sandbox tenant.'],
                ],
                [
                    'id' => 'entra-ca-review',
                    'area' => ['de' => 'Protection → Conditional Access', 'en' => 'Protection → Conditional Access'],
                    'setting' => ['de' => 'CA Policy Review Cadence und Assignment Coverage', 'en' => 'CA policy review cadence and assignment coverage'],
                    'why' => ['de' => 'Orphan Policies und Coverage Gaps werden steuerbar.', 'en' => 'Orphan policies and coverage gaps become controllable.'],
                    'how' => ['de' => 'Report-only first; document include/exclude; quarterly review.', 'en' => 'Report-only first; document include/exclude; quarterly review.'],
                ],
                [
                    'id' => 'entra-app-credential-hygiene',
                    'area' => ['de' => 'App registrations → Certificates & secrets', 'en' => 'App registrations → Certificates & secrets'],
                    'setting' => ['de' => 'Expiry Alerts; keine Secret-Exports ins Warehouse', 'en' => 'Expiry alerts; no secret exports into warehouse'],
                    'why' => ['de' => 'Integrationen bleiben live ohne Secret-Landung.', 'en' => 'Integrations stay live without landing secrets.'],
                    'how' => ['de' => 'Prefer managed identity/certs; alert on endDateTime metadata only.', 'en' => 'Prefer managed identity/certs; alert on endDateTime metadata only.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'entra-graph-metadata',
                    'kind' => ['de' => 'Graph $metadata / directory objects', 'en' => 'Graph $metadata / directory objects'],
                    'where' => ['de' => 'Microsoft Graph → $metadata; users, groups, applications, servicePrincipals', 'en' => 'Microsoft Graph → $metadata; users, groups, applications, servicePrincipals'],
                    'how' => ['de' => 'Entity/Property inventarisieren; Select-Allowlist für Extract.', 'en' => 'Inventory entities/properties; select allowlist for extract.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (id, appId, UPN).', 'en' => 'Extract design, PII tags, join keys (id, appId, UPN).'],
                    'watchouts' => ['de' => 'passwordCredentials/keyCredentials — nie Secret-Material selektieren.', 'en' => 'passwordCredentials/keyCredentials — never select secret material.'],
                ],
                [
                    'id' => 'entra-conditional-access',
                    'kind' => ['de' => 'Conditional Access policies', 'en' => 'Conditional Access policies'],
                    'where' => ['de' => 'Entra → Protection → Conditional Access; Graph identity/conditionalAccess', 'en' => 'Entra → Protection → Conditional Access; Graph identity/conditionalAccess'],
                    'how' => ['de' => 'Policy State, Assignments und Grant Controls dokumentieren.', 'en' => 'Document policy state, assignments and grant controls.'],
                    'useFor' => ['de' => 'Coverage dims, orphan-policy DQ, security posture KPIs.', 'en' => 'Coverage dims, orphan-policy DQ, security posture KPIs.'],
                    'watchouts' => ['de' => 'Include/Exclude Listen ändern sich — SCD2 empfohlen.', 'en' => 'Include/exclude lists change — SCD2 recommended.'],
                ],
                [
                    'id' => 'entra-audit-signin-schema',
                    'kind' => ['de' => 'Audit / Sign-in logs schema', 'en' => 'Audit / Sign-in logs schema'],
                    'where' => ['de' => 'Entra → Monitoring → Sign-in / Audit logs; Graph auditLogs', 'en' => 'Entra → Monitoring → Sign-in / Audit logs; Graph auditLogs'],
                    'how' => ['de' => 'Field Allowlist; Retention und Sensitivity labeln.', 'en' => 'Field allowlist; label retention and sensitivity.'],
                    'useFor' => ['de' => 'Activity facts, auth failure rates, actor/target joins.', 'en' => 'Activity facts, auth failure rates, actor/target joins.'],
                    'watchouts' => ['de' => 'IP/UPN cleartext — restrict; short retention.', 'en' => 'IP/UPN cleartext — restrict; short retention.'],
                ],
                [
                    'id' => 'entra-app-registrations',
                    'kind' => ['de' => 'App registrations', 'en' => 'App registrations'],
                    'where' => ['de' => 'Entra → Applications → App registrations / Enterprise applications', 'en' => 'Entra → Applications → App registrations / Enterprise applications'],
                    'how' => ['de' => 'appId, owners, API permissions, credential expiry Metadata inventarisieren.', 'en' => 'Inventory appId, owners, API permissions, credential expiry metadata.'],
                    'useFor' => ['de' => 'App dim, credential hygiene DQ, least-privilege extract scopes.', 'en' => 'App dim, credential hygiene DQ, least-privilege extract scopes.'],
                    'watchouts' => ['de' => 'Nie Secrets/Cert Blobs exportieren — nur endDateTime/keyId.', 'en' => 'Never export secrets/cert blobs — endDateTime/keyId only.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'github' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'github-pr-no-repo',
                    'priority' => 'high',
                    'title' => ['de' => 'PR ohne Repository', 'en' => 'PR without repository'],
                    'problem' => ['de' => 'Pull Requests ohne repo_id brechen Delivery Joins und Throughput-KPIs.', 'en' => 'Pull requests without repo_id break delivery joins and throughput KPIs.'],
                    'prevent' => ['de' => 'API extract: repository immer mitladen; Soft-deleted Repos tracken.', 'en' => 'API extract: always load repository; track soft-deleted repos.'],
                    'staffNeedToKnow' => ['de' => 'Data: PR ohne Repo ist Extract-/Delete-Artefakt.', 'en' => 'Data: PR without repo is an extract/delete artifact.'],
                    'checks' => ['de' => 'pull_request.repo_id IS NULL OR repo_id NOT IN dim_repository', 'en' => 'pull_request.repo_id IS NULL OR repo_id NOT IN dim_repository'],
                    'fixInSource' => ['de' => 'Re-extract; include transferred/deleted repo tombstones.', 'en' => 'Re-extract; include transferred/deleted repo tombstones.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown repo dim.', 'en' => 'Quarantine; Unknown repo dim.'],
                ],
                [
                    'id' => 'github-pr-merged-no-sha',
                    'priority' => 'high',
                    'title' => ['de' => 'Merged PR ohne Merge Commit SHA', 'en' => 'Merged PR without merge commit SHA'],
                    'problem' => ['de' => 'Merged ohne merge_commit_sha macht Change Tracking und Deploy Joins unbrauchbar.', 'en' => 'Merged without merge_commit_sha makes change tracking and deploy joins unusable.'],
                    'prevent' => ['de' => 'GraphQL/REST fields mergeCommit/oid requesten; Squash/Rebase Cases dokumentieren.', 'en' => 'Request GraphQL/REST mergeCommit/oid fields; document squash/rebase cases.'],
                    'staffNeedToKnow' => ['de' => 'Engineering: Merge Method und SHA-Felder im Extract prüfen.', 'en' => 'Engineering: Check merge method and SHA fields in extract.'],
                    'checks' => ['de' => 'merged = TRUE AND merge_commit_sha IS NULL', 'en' => 'merged = TRUE AND merge_commit_sha IS NULL'],
                    'fixInSource' => ['de' => 'Re-fetch PR; verify merge method metadata.', 'en' => 'Re-fetch PR; verify merge method metadata.'],
                    'fixInWarehouse' => ['de' => 'Flag missing_merge_sha; exclude from SHA-based joins.', 'en' => 'Flag missing_merge_sha; exclude from SHA-based joins.'],
                ],
                [
                    'id' => 'github-workflow-no-repo',
                    'priority' => 'high',
                    'title' => ['de' => 'Workflow Run ohne Repository', 'en' => 'Workflow run without repository'],
                    'problem' => ['de' => 'Actions Runs ohne repo_id verzerren CI Success Rates.', 'en' => 'Actions runs without repo_id distort CI success rates.'],
                    'prevent' => ['de' => 'Actions API: repository immer joinen; archived repos separat.', 'en' => 'Actions API: always join repository; separate archived repos.'],
                    'staffNeedToKnow' => ['de' => 'Platform: Run Metadata ohne Repo nicht in Prod-Marts.', 'en' => 'Platform: Do not put run metadata without repo into prod marts.'],
                    'checks' => ['de' => 'workflow_run.repo_id IS NULL', 'en' => 'workflow_run.repo_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-extract Actions runs with repository.', 'en' => 'Re-extract Actions runs with repository.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from CI KPIs.', 'en' => 'Quarantine; exclude from CI KPIs.'],
                ],
                [
                    'id' => 'github-member-outside-collaborator-drift',
                    'priority' => 'medium',
                    'title' => ['de' => 'Member / Outside Collaborator Drift', 'en' => 'Member / outside collaborator drift'],
                    'problem' => ['de' => 'Outside Collaborators ohne Org Membership verzerren Access und Contributor Counts.', 'en' => 'Outside collaborators without org membership distort access and contributor counts.'],
                    'prevent' => ['de' => 'Org policy: prefer org members; periodic collaborator review.', 'en' => 'Org policy: prefer org members; periodic collaborator review.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Outside Collaborators reviewen und befristen.', 'en' => 'Admins: Review and time-box outside collaborators.'],
                    'checks' => ['de' => 'is_outside_collaborator = TRUE AND org_member = FALSE AND last_activity_at < CURRENT_DATE - 90', 'en' => 'is_outside_collaborator = TRUE AND org_member = FALSE AND last_activity_at < CURRENT_DATE - 90'],
                    'fixInSource' => ['de' => 'Convert to member or remove collaborator access.', 'en' => 'Convert to member or remove collaborator access.'],
                    'fixInWarehouse' => ['de' => 'Flag stale_collaborator; separate access KPI.', 'en' => 'Flag stale_collaborator; separate access KPI.'],
                ],
                [
                    'id' => 'github-secret-alert-without-repo',
                    'priority' => 'medium',
                    'title' => ['de' => 'Secret Scanning Alert ohne Repo', 'en' => 'Secret scanning alert without repo'],
                    'problem' => ['de' => 'Alerts ohne repo_id brechen Security Coverage; Secret Values dürfen nie landen.', 'en' => 'Alerts without repo_id break security coverage; secret values must never land.'],
                    'prevent' => ['de' => 'Security alerts extract mit repository; never select secret field.', 'en' => 'Security alerts extract with repository; never select secret field.'],
                    'staffNeedToKnow' => ['de' => 'Security: Alert Metadata only — keine Secret Payloads.', 'en' => 'Security: Alert metadata only — no secret payloads.'],
                    'checks' => ['de' => 'alert.repo_id IS NULL AND state <> \'resolved\'', 'en' => 'alert.repo_id IS NULL AND state <> \'resolved\''],
                    'fixInSource' => ['de' => 'Re-fetch alert list with repository context.', 'en' => 'Re-fetch alert list with repository context.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; never persist secret values.', 'en' => 'Quarantine; never persist secret values.'],
                ],
                [
                    'id' => 'github-duplicate-pr-number',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte PR Number je Repo im Extract', 'en' => 'Duplicate PR number per repo in extract'],
                    'problem' => ['de' => 'Doppelte (repo_id, number) verzerren PR Counts und Cycle-Time.', 'en' => 'Duplicate (repo_id, number) distort PR counts and cycle time.'],
                    'prevent' => ['de' => 'Idempotent load key; pagination overlap prüfen.', 'en' => 'Idempotent load key; check pagination overlap.'],
                    'staffNeedToKnow' => ['de' => 'Data: Natural Key = repo_id + number.', 'en' => 'Data: Natural key = repo_id + number.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY repo_id, number HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY repo_id, number HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate API pagination.', 'en' => 'Re-extract; investigate API pagination.'],
                    'fixInWarehouse' => ['de' => 'Dedup by repo_id+number; keep latest _loaded_at.', 'en' => 'Dedup by repo_id+number; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'github-user-dup',
                    'entity' => 'User',
                    'title' => ['de' => 'User-Duplikate / Login Rename', 'en' => 'User duplicates / login rename'],
                    'matchKeys' => ['id', 'login', 'email (hashed)', 'node_id'],
                    'preventInSource' => ['de' => 'Prefer numeric id over login; track login renames.', 'en' => 'Prefer numeric id over login; track login renames.'],
                    'resolveInWarehouse' => ['de' => 'Golden user id; login SCD2 map.', 'en' => 'Golden user id; login SCD2 map.'],
                    'survivorship' => ['de' => 'Aktiver User mit neuester Org Activity gewinnt.', 'en' => 'Active user with latest org activity wins.'],
                ],
                [
                    'id' => 'github-repo-transfer',
                    'entity' => 'Repository',
                    'title' => ['de' => 'Repository Transfer / Rename', 'en' => 'Repository transfer / rename'],
                    'matchKeys' => ['repo id', 'node_id', 'full_name', 'owner+name'],
                    'preventInSource' => ['de' => 'Stable repo id; capture rename/transfer events.', 'en' => 'Stable repo id; capture rename/transfer events.'],
                    'resolveInWarehouse' => ['de' => 'Canonical repo id; full_name SCD2.', 'en' => 'Canonical repo id; full_name SCD2.'],
                    'survivorship' => ['de' => 'Aktuelles full_name gewinnt; historische Namen als aliases.', 'en' => 'Current full_name wins; historical names as aliases.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'github-org-audit-log',
                    'area' => ['de' => 'Organization → Settings → Audit log', 'en' => 'Organization → Settings → Audit log'],
                    'setting' => ['de' => 'Audit Log Streaming / Export für Governance Events', 'en' => 'Audit log streaming / export for governance events'],
                    'why' => ['de' => 'Member/Repo Changes werden analytisch nachvollziehbar.', 'en' => 'Member/repo changes become analytically traceable.'],
                    'how' => ['de' => 'Enable streaming; allowlist event types; short retention for sensitive fields.', 'en' => 'Enable streaming; allowlist event types; short retention for sensitive fields.'],
                ],
                [
                    'id' => 'github-secret-scanning',
                    'area' => ['de' => 'Code security → Secret scanning', 'en' => 'Code security → Secret scanning'],
                    'setting' => ['de' => 'Secret Scanning + Push Protection; Alert Metadata only in Warehouse', 'en' => 'Secret scanning + push protection; alert metadata only in warehouse'],
                    'why' => ['de' => 'Security Coverage ohne Secret-Landung.', 'en' => 'Security coverage without landing secrets.'],
                    'how' => ['de' => 'Enable org-wide; extract state/severity/repo — never secret value.', 'en' => 'Enable org-wide; extract state/severity/repo — never secret value.'],
                ],
                [
                    'id' => 'github-actions-retention',
                    'area' => ['de' => 'Actions → General / Artifact retention', 'en' => 'Actions → General / Artifact retention'],
                    'setting' => ['de' => 'Artifact/Log Retention kurz; Warehouse nur Run Metadata', 'en' => 'Keep artifact/log retention short; warehouse run metadata only'],
                    'why' => ['de' => 'CI KPIs ohne Log/Artifact Binaries.', 'en' => 'CI KPIs without log/artifact binaries.'],
                    'how' => ['de' => 'Org retention defaults; omit logs/artifacts from extract.', 'en' => 'Org retention defaults; omit logs/artifacts from extract.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'github-rest-graphql-schema',
                    'kind' => ['de' => 'REST / GraphQL schema', 'en' => 'REST / GraphQL schema'],
                    'where' => ['de' => 'GitHub Docs → REST API / GraphQL schema reference', 'en' => 'GitHub Docs → REST API / GraphQL schema reference'],
                    'how' => ['de' => 'Object fields inventarisieren; Select/Fragment Allowlist für Extract.', 'en' => 'Inventory object fields; select/fragment allowlist for extract.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (repo, PR, user).', 'en' => 'Extract design, PII tags, join keys (repo, PR, user).'],
                    'watchouts' => ['de' => 'Keine patches/blobs/secret fields selektieren.', 'en' => 'Do not select patches/blobs/secret fields.'],
                ],
                [
                    'id' => 'github-org-audit-log-meta',
                    'kind' => ['de' => 'Org audit log', 'en' => 'Org audit log'],
                    'where' => ['de' => 'Org Settings → Audit log; audit log API / streaming', 'en' => 'Org Settings → Audit log; audit log API / streaming'],
                    'how' => ['de' => 'Event Actions Allowlist; Actor/Repo Keys dokumentieren.', 'en' => 'Allowlist event actions; document actor/repo keys.'],
                    'useFor' => ['de' => 'Governance facts, member changes, repo transfers.', 'en' => 'Governance facts, member changes, repo transfers.'],
                    'watchouts' => ['de' => 'Audit Payloads können Emails enthalten — hashen/drop.', 'en' => 'Audit payloads can contain emails — hash/drop.'],
                ],
                [
                    'id' => 'github-repo-settings',
                    'kind' => ['de' => 'Repository settings', 'en' => 'Repository settings'],
                    'where' => ['de' => 'Repo → Settings (branches, visibility, security); Org repo policies', 'en' => 'Repo → Settings (branches, visibility, security); Org repo policies'],
                    'how' => ['de' => 'Default Branch, Visibility, Required Checks exportieren.', 'en' => 'Export default branch, visibility, required checks.'],
                    'useFor' => ['de' => 'Repo dim, compliance flags, delivery baselines.', 'en' => 'Repo dim, compliance flags, delivery baselines.'],
                    'watchouts' => ['de' => 'Private Repo Metadata — Zugriff restriktiv.', 'en' => 'Private repo metadata — restrict access.'],
                ],
                [
                    'id' => 'github-actions-metadata',
                    'kind' => ['de' => 'Actions metadata', 'en' => 'Actions metadata'],
                    'where' => ['de' => 'Actions → Workflows / Runs API; workflow YAML locations (not bodies in WH)', 'en' => 'Actions → Workflows / Runs API; workflow YAML locations (not bodies in WH)'],
                    'how' => ['de' => 'Run Status, Conclusion, Timing, Workflow Name inventarisieren.', 'en' => 'Inventory run status, conclusion, timing, workflow name.'],
                    'useFor' => ['de' => 'CI success rate, duration KPIs, flaky-job signals.', 'en' => 'CI success rate, duration KPIs, flaky-job signals.'],
                    'watchouts' => ['de' => 'Logs/Artifacts default skip — Metadata only.', 'en' => 'Logs/artifacts default skip — metadata only.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'sharepoint' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'spo-item-no-site',
                    'priority' => 'high',
                    'title' => ['de' => 'DriveItem / ListItem ohne Site', 'en' => 'DriveItem / ListItem without site'],
                    'problem' => ['de' => 'Items ohne site_id brechen Collaboration Joins und Site Activity KPIs.', 'en' => 'Items without site_id break collaboration joins and site activity KPIs.'],
                    'prevent' => ['de' => 'Graph extract: parentReference.siteId immer mitschreiben.', 'en' => 'Graph extract: always persist parentReference.siteId.'],
                    'staffNeedToKnow' => ['de' => 'Data: Item ohne Site ist Extract-Fehler.', 'en' => 'Data: Item without site is an extract error.'],
                    'checks' => ['de' => 'item.site_id IS NULL OR site_id NOT IN dim_site', 'en' => 'item.site_id IS NULL OR site_id NOT IN dim_site'],
                    'fixInSource' => ['de' => 'Re-extract with site context; repair deleted site tombstones.', 'en' => 'Re-extract with site context; repair deleted site tombstones.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown site dim.', 'en' => 'Quarantine; Unknown site dim.'],
                ],
                [
                    'id' => 'spo-sharing-anon-link',
                    'priority' => 'high',
                    'title' => ['de' => 'Anonymous Sharing Links ohne Expiry', 'en' => 'Anonymous sharing links without expiry'],
                    'problem' => ['de' => 'Anon Links ohne Expiry erhöhen Leak-Risiko; volle URLs dürfen nie landen.', 'en' => 'Anon links without expiry raise leak risk; full URLs must never land.'],
                    'prevent' => ['de' => 'Sharing Policy: anonymous links require expiry; prefer specific people.', 'en' => 'Sharing policy: anonymous links require expiry; prefer specific people.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Anon Sharing einschränken und Expiry erzwingen.', 'en' => 'Admins: Restrict anon sharing and enforce expiry.'],
                    'checks' => ['de' => 'link_scope = \'anonymous\' AND (expiry_at IS NULL OR expiry_at < CURRENT_TIMESTAMP)', 'en' => 'link_scope = \'anonymous\' AND (expiry_at IS NULL OR expiry_at < CURRENT_TIMESTAMP)'],
                    'fixInSource' => ['de' => 'Tenant sharing settings; revoke stale links.', 'en' => 'Tenant sharing settings; revoke stale links.'],
                    'fixInWarehouse' => ['de' => 'Flag anon_sharing_risk; store type/scope only — no URL.', 'en' => 'Flag anon_sharing_risk; store type/scope only — no URL.'],
                ],
                [
                    'id' => 'spo-item-no-sensitivity-label',
                    'priority' => 'medium',
                    'title' => ['de' => 'Item ohne Sensitivity Label (wenn Policy Pflicht)', 'en' => 'Item without sensitivity label when policy requires'],
                    'problem' => ['de' => 'Fehlende Labels trotz Policy schwächen Purview Coverage.', 'en' => 'Missing labels despite policy weaken Purview coverage.'],
                    'prevent' => ['de' => 'Auto-labeling; default label on libraries; required for classified sites.', 'en' => 'Auto-labeling; default label on libraries; required for classified sites.'],
                    'staffNeedToKnow' => ['de' => 'Owners: Labels auf Libraries mit Pflicht-Policy setzen.', 'en' => 'Owners: Set labels on libraries with required policy.'],
                    'checks' => ['de' => 'requires_sensitivity_label = TRUE AND sensitivity_label_id IS NULL', 'en' => 'requires_sensitivity_label = TRUE AND sensitivity_label_id IS NULL'],
                    'fixInSource' => ['de' => 'Apply label / auto-label policy.', 'en' => 'Apply label / auto-label policy.'],
                    'fixInWarehouse' => ['de' => 'Flag unlabeled; exclude from compliant coverage numerator.', 'en' => 'Flag unlabeled; exclude from compliant coverage numerator.'],
                ],
                [
                    'id' => 'spo-drive-no-site',
                    'priority' => 'high',
                    'title' => ['de' => 'Drive ohne Site', 'en' => 'Drive without site'],
                    'problem' => ['de' => 'Drives ohne site_id machen Storage- und Activity-Rollups kaputt.', 'en' => 'Drives without site_id break storage and activity rollups.'],
                    'prevent' => ['de' => 'Graph sites/drives hierarchy vollständig extrahieren.', 'en' => 'Fully extract Graph sites/drives hierarchy.'],
                    'staffNeedToKnow' => ['de' => 'Data: Drive immer an Site hängen.', 'en' => 'Data: Always attach drive to site.'],
                    'checks' => ['de' => 'drive.site_id IS NULL', 'en' => 'drive.site_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-sync site → drives.', 'en' => 'Re-sync site → drives.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown site.', 'en' => 'Quarantine; Unknown site.'],
                ],
                [
                    'id' => 'spo-orphan-permission',
                    'priority' => 'medium',
                    'title' => ['de' => 'Permission Grant ohne Item/Site', 'en' => 'Permission grant without item/site'],
                    'problem' => ['de' => 'Orphan Permissions verzerren Sharing Coverage und Access Reviews.', 'en' => 'Orphan permissions distort sharing coverage and access reviews.'],
                    'prevent' => ['de' => 'Permission extract mit parent item/site keys; soft-delete handling.', 'en' => 'Permission extract with parent item/site keys; soft-delete handling.'],
                    'staffNeedToKnow' => ['de' => 'Governance: Broken Inheritance und Orphans reviewen.', 'en' => 'Governance: Review broken inheritance and orphans.'],
                    'checks' => ['de' => 'permission.item_id IS NULL AND permission.site_id IS NULL', 'en' => 'permission.item_id IS NULL AND permission.site_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-extract permissions with parents; revoke orphans.', 'en' => 'Re-extract permissions with parents; revoke orphans.'],
                    'fixInWarehouse' => ['de' => 'Flag orphan_permission; exclude from coverage.', 'en' => 'Flag orphan_permission; exclude from coverage.'],
                ],
                [
                    'id' => 'spo-duplicate-item-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Item IDs im Extract', 'en' => 'Duplicate item ids in extract'],
                    'problem' => ['de' => 'Doppelte item_id verzerren Activity Counts und Storage Facts.', 'en' => 'Duplicate item_id distort activity counts and storage facts.'],
                    'prevent' => ['de' => 'Idempotent load; delta token overlap prüfen.', 'en' => 'Idempotent load; check delta token overlap.'],
                    'staffNeedToKnow' => ['de' => 'Data: item_id je drive eindeutig halten.', 'en' => 'Data: Keep item_id unique per drive.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY drive_id, item_id HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY drive_id, item_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate Graph delta pagination.', 'en' => 'Re-extract; investigate Graph delta pagination.'],
                    'fixInWarehouse' => ['de' => 'Dedup by drive_id+item_id; keep latest _loaded_at.', 'en' => 'Dedup by drive_id+item_id; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'spo-site-dup',
                    'entity' => 'Site',
                    'title' => ['de' => 'Site-Duplikate / URL Rename', 'en' => 'Site duplicates / URL rename'],
                    'matchKeys' => ['site id', 'webUrl', 'siteCollection hostname+path'],
                    'preventInSource' => ['de' => 'Stable site id; capture URL changes via Graph.', 'en' => 'Stable site id; capture URL changes via Graph.'],
                    'resolveInWarehouse' => ['de' => 'Golden site id; webUrl SCD2.', 'en' => 'Golden site id; webUrl SCD2.'],
                    'survivorship' => ['de' => 'Aktive Site mit neuester Activity gewinnt.', 'en' => 'Active site with latest activity wins.'],
                ],
                [
                    'id' => 'spo-label-taxonomy',
                    'entity' => 'Sensitivity label',
                    'title' => ['de' => 'Sensitivity Label Taxonomy Drift', 'en' => 'Sensitivity label taxonomy drift'],
                    'matchKeys' => ['label id', 'name', 'parent policy'],
                    'preventInSource' => ['de' => 'Purview label governance; controlled rename.', 'en' => 'Purview label governance; controlled rename.'],
                    'resolveInWarehouse' => ['de' => 'Canonical label id; SCD2 label name.', 'en' => 'Canonical label id; SCD2 label name.'],
                    'survivorship' => ['de' => 'Aktueller Purview Label-Stand gewinnt über Legacy Namen.', 'en' => 'Current Purview label wins over legacy names.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'spo-sharing-policy',
                    'area' => ['de' => 'SharePoint Admin → Sharing', 'en' => 'SharePoint Admin → Sharing'],
                    'setting' => ['de' => 'External/Anonymous Sharing Limits und Link Expiry', 'en' => 'External/anonymous sharing limits and link expiry'],
                    'why' => ['de' => 'Sharing Risk KPIs werden steuerbar ohne Link-URLs zu speichern.', 'en' => 'Sharing risk KPIs become controllable without storing link URLs.'],
                    'how' => ['de' => 'Tenant sharing settings; default link type; expiry required.', 'en' => 'Tenant sharing settings; default link type; expiry required.'],
                ],
                [
                    'id' => 'spo-purview-labels',
                    'area' => ['de' => 'Microsoft Purview → Sensitivity labels', 'en' => 'Microsoft Purview → Sensitivity labels'],
                    'setting' => ['de' => 'Label Publishing und Auto-Labeling für Sites/Libraries', 'en' => 'Label publishing and auto-labeling for sites/libraries'],
                    'why' => ['de' => 'Label Coverage bleibt messbar — ohne Document Bodies.', 'en' => 'Label coverage stays measurable — without document bodies.'],
                    'how' => ['de' => 'Publish labels; default library label; extract label ids only.', 'en' => 'Publish labels; default library label; extract label ids only.'],
                ],
                [
                    'id' => 'spo-site-lifecycle',
                    'area' => ['de' => 'SharePoint Admin → Sites / Lifecycle', 'en' => 'SharePoint Admin → Sites / Lifecycle'],
                    'setting' => ['de' => 'Site Lifecycle / Inactive Site Policies', 'en' => 'Site lifecycle / inactive site policies'],
                    'why' => ['de' => 'Orphan Sites und Storage Growth bleiben beherrschbar.', 'en' => 'Orphan sites and storage growth stay manageable.'],
                    'how' => ['de' => 'Inactive site detection; archive/delete cadence.', 'en' => 'Inactive site detection; archive/delete cadence.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'spo-graph-sites-drives',
                    'kind' => ['de' => 'Graph sites / drives', 'en' => 'Graph sites / drives'],
                    'where' => ['de' => 'Microsoft Graph → sites, drives, driveItems (metadata select)', 'en' => 'Microsoft Graph → sites, drives, driveItems (metadata select)'],
                    'how' => ['de' => 'Site/Drive/Item Metadata Allowlist; Content-Select vermeiden.', 'en' => 'Site/drive/item metadata allowlist; avoid content select.'],
                    'useFor' => ['de' => 'Activity facts, storage dims, Join-Keys.', 'en' => 'Activity facts, storage dims, join keys.'],
                    'watchouts' => ['de' => 'Nie /content oder Version Streams laden.', 'en' => 'Never load /content or version streams.'],
                ],
                [
                    'id' => 'spo-site-columns-ctypes',
                    'kind' => ['de' => 'Site columns / content types', 'en' => 'Site columns / content types'],
                    'where' => ['de' => 'Site Settings → Site columns / Content types; Graph list columns', 'en' => 'Site Settings → Site columns / Content types; Graph list columns'],
                    'how' => ['de' => 'Column Types inventarisieren; Person/Email Columns als PII taggen.', 'en' => 'Inventory column types; tag person/email columns as PII.'],
                    'useFor' => ['de' => 'Extract allowlist, PII scan, content type dims.', 'en' => 'Extract allowlist, PII scan, content type dims.'],
                    'watchouts' => ['de' => 'Custom Person Columns — Default drop in marts.', 'en' => 'Custom person columns — default drop in marts.'],
                ],
                [
                    'id' => 'spo-sharing-purview',
                    'kind' => ['de' => 'Sharing / Purview labels', 'en' => 'Sharing / Purview labels'],
                    'where' => ['de' => 'Sharing Admin Center; Purview sensitivity labels; Graph permissions', 'en' => 'Sharing Admin Center; Purview sensitivity labels; Graph permissions'],
                    'how' => ['de' => 'Link Types, Scopes, Label IDs dokumentieren — keine URLs.', 'en' => 'Document link types, scopes, label ids — no URLs.'],
                    'useFor' => ['de' => 'Sharing risk KPIs, label coverage, permission counts.', 'en' => 'Sharing risk KPIs, label coverage, permission counts.'],
                    'watchouts' => ['de' => 'Sharing Link Tokens nie speichern.', 'en' => 'Never store sharing link tokens.'],
                ],
                [
                    'id' => 'spo-search-schema',
                    'kind' => ['de' => 'Search schema', 'en' => 'Search schema'],
                    'where' => ['de' => 'SharePoint Admin → More features → Search → Manage search schema', 'en' => 'SharePoint Admin → More features → Search → Manage search schema'],
                    'how' => ['de' => 'Managed/Crawled Properties als Feld-Referenz — Bodies nicht exportieren.', 'en' => 'Managed/crawled properties as field reference — do not export bodies.'],
                    'useFor' => ['de' => 'Field discovery, classification signals, metadata coverage.', 'en' => 'Field discovery, classification signals, metadata coverage.'],
                    'watchouts' => ['de' => 'Search ≠ RAW Landing — keine indexed document bodies.', 'en' => 'Search ≠ RAW landing — no indexed document bodies.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'google-workspace' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'gws-user-no-org-unit',
                    'priority' => 'high',
                    'title' => ['de' => 'User ohne Org Unit', 'en' => 'User without org unit'],
                    'problem' => ['de' => 'Users ohne orgUnitPath brechen Policy Inheritance und Directory Rollups.', 'en' => 'Users without orgUnitPath break policy inheritance and directory rollups.'],
                    'prevent' => ['de' => 'Provisioning: Org Unit Pflicht; default OU für neue User.', 'en' => 'Provisioning: org unit required; default OU for new users.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Jeder User braucht eine Org Unit.', 'en' => 'Admins: Every user needs an org unit.'],
                    'checks' => ['de' => 'org_unit_path IS NULL AND suspended = FALSE', 'en' => 'org_unit_path IS NULL AND suspended = FALSE'],
                    'fixInSource' => ['de' => 'Assign OU in Admin Console / Directory API.', 'en' => 'Assign OU in Admin Console / Directory API.'],
                    'fixInWarehouse' => ['de' => 'Unknown OU dim; exclude from OU KPIs.', 'en' => 'Unknown OU dim; exclude from OU KPIs.'],
                ],
                [
                    'id' => 'gws-suspended-still-in-groups',
                    'priority' => 'high',
                    'title' => ['de' => 'Suspended User noch in Groups', 'en' => 'Suspended user still in groups'],
                    'problem' => ['de' => 'Suspended Users in Groups verzerren Access und Distribution Lists.', 'en' => 'Suspended users in groups distort access and distribution lists.'],
                    'prevent' => ['de' => 'Lifecycle: Group Cleanup bei Suspend; Archive instead of orphan.', 'en' => 'Lifecycle: group cleanup on suspend; archive instead of orphan.'],
                    'staffNeedToKnow' => ['de' => 'IAM: Suspend ≠ Membership Cleanup.', 'en' => 'IAM: Suspend ≠ membership cleanup.'],
                    'checks' => ['de' => 'suspended = TRUE AND group_membership_count > 0', 'en' => 'suspended = TRUE AND group_membership_count > 0'],
                    'fixInSource' => ['de' => 'Remove group memberships; automate leaver workflow.', 'en' => 'Remove group memberships; automate leaver workflow.'],
                    'fixInWarehouse' => ['de' => 'Flag stale_membership; exclude from active entitlement KPIs.', 'en' => 'Flag stale_membership; exclude from active entitlement KPIs.'],
                ],
                [
                    'id' => 'gws-login-no-user',
                    'priority' => 'medium',
                    'title' => ['de' => 'Login Activity ohne User', 'en' => 'Login activity without user'],
                    'problem' => ['de' => 'Login Events ohne auflösbaren user_id brechen Security Joins.', 'en' => 'Login events without resolvable user_id break security joins.'],
                    'prevent' => ['de' => 'Reports API: actor email/id mappen; deleted users window.', 'en' => 'Reports API: map actor email/id; deleted users window.'],
                    'staffNeedToKnow' => ['de' => 'Security: Orphan Logins vs Deleted Users trennen.', 'en' => 'Security: Separate orphan logins vs deleted users.'],
                    'checks' => ['de' => 'login.user_id IS NULL OR user_id NOT IN dim_user', 'en' => 'login.user_id IS NULL OR user_id NOT IN dim_user'],
                    'fixInSource' => ['de' => 'Re-sync Directory; widen soft-delete lookback.', 'en' => 'Re-sync Directory; widen soft-delete lookback.'],
                    'fixInWarehouse' => ['de' => 'Unknown-user dim; exclude from per-user KPIs.', 'en' => 'Unknown-user dim; exclude from per-user KPIs.'],
                ],
                [
                    'id' => 'gws-drive-activity-no-file',
                    'priority' => 'medium',
                    'title' => ['de' => 'Drive Activity ohne File Target', 'en' => 'Drive activity without file target'],
                    'problem' => ['de' => 'Activity ohne file_id macht Collaboration Facts unbrauchbar — Bodies trotzdem nie laden.', 'en' => 'Activity without file_id makes collaboration facts unusable — still never load bodies.'],
                    'prevent' => ['de' => 'Drive Activity API: target driveItem id persistieren.', 'en' => 'Drive Activity API: persist target driveItem id.'],
                    'staffNeedToKnow' => ['de' => 'Data: Activity Metadata only — keine File Exports.', 'en' => 'Data: Activity metadata only — no file exports.'],
                    'checks' => ['de' => 'activity.file_id IS NULL AND activity_type IN (\'edit\',\'create\',\'share\')', 'en' => 'activity.file_id IS NULL AND activity_type IN (\'edit\',\'create\',\'share\')'],
                    'fixInSource' => ['de' => 'Re-fetch activity with targets.', 'en' => 'Re-fetch activity with targets.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from file-level KPIs.', 'en' => 'Quarantine; exclude from file-level KPIs.'],
                ],
                [
                    'id' => 'gws-group-no-owner',
                    'priority' => 'medium',
                    'title' => ['de' => 'Group ohne Owner', 'en' => 'Group without owner'],
                    'problem' => ['de' => 'Groups ohne Owner schwächen Access Governance und Ownership Reviews.', 'en' => 'Groups without owner weaken access governance and ownership reviews.'],
                    'prevent' => ['de' => 'Group create: owner required; periodic owner attestation.', 'en' => 'Group create: owner required; periodic owner attestation.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Jede Group braucht mindestens einen Owner.', 'en' => 'Admins: Every group needs at least one owner.'],
                    'checks' => ['de' => 'owner_count = 0 AND is_deleted = FALSE', 'en' => 'owner_count = 0 AND is_deleted = FALSE'],
                    'fixInSource' => ['de' => 'Assign owners in Admin Console.', 'en' => 'Assign owners in Admin Console.'],
                    'fixInWarehouse' => ['de' => 'Flag ownerless_group; exclude from healthy coverage.', 'en' => 'Flag ownerless_group; exclude from healthy coverage.'],
                ],
                [
                    'id' => 'gws-duplicate-user-email',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte primaryEmail im Extract', 'en' => 'Duplicate primaryEmail in extract'],
                    'problem' => ['de' => 'Doppelte primaryEmail verzerren Directory Counts und Joins.', 'en' => 'Duplicate primaryEmail distort directory counts and joins.'],
                    'prevent' => ['de' => 'Directory unique email; alias vs primary trennen.', 'en' => 'Directory unique email; separate alias vs primary.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Aliases nicht als zweite primaryEmail führen.', 'en' => 'Admins: Do not treat aliases as a second primaryEmail.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY primary_email HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY primary_email HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Merge/fix in Directory; re-extract.', 'en' => 'Merge/fix in Directory; re-extract.'],
                    'fixInWarehouse' => ['de' => 'Golden user id; email-hash merge map.', 'en' => 'Golden user id; email-hash merge map.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'gws-user-dup',
                    'entity' => 'User',
                    'title' => ['de' => 'User-Duplikate / Rehire', 'en' => 'User duplicates / rehire'],
                    'matchKeys' => ['id', 'primaryEmail', 'employeeId', 'externalIds'],
                    'preventInSource' => ['de' => 'HR feed as source of truth; suspend instead of recreate.', 'en' => 'HR feed as source of truth; suspend instead of recreate.'],
                    'resolveInWarehouse' => ['de' => 'Golden user id; email-hash merge map.', 'en' => 'Golden user id; email-hash merge map.'],
                    'survivorship' => ['de' => 'Aktiver (nicht suspended) User mit neuester Login Activity gewinnt.', 'en' => 'Active (not suspended) user with latest login activity wins.'],
                ],
                [
                    'id' => 'gws-org-unit-map',
                    'entity' => 'Org unit',
                    'title' => ['de' => 'Org Unit Hierarchy Drift', 'en' => 'Org unit hierarchy drift'],
                    'matchKeys' => ['orgUnitId', 'orgUnitPath', 'parentOrgUnitPath'],
                    'preventInSource' => ['de' => 'Controlled OU moves; document rename policy.', 'en' => 'Controlled OU moves; document rename policy.'],
                    'resolveInWarehouse' => ['de' => 'Canonical orgUnitId; SCD2 orgUnitPath.', 'en' => 'Canonical orgUnitId; SCD2 orgUnitPath.'],
                    'survivorship' => ['de' => 'Aktueller OU-Pfad gewinnt; historische Pfade als aliases.', 'en' => 'Current OU path wins; historical paths as aliases.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'gws-ou-policies',
                    'area' => ['de' => 'Admin Console → Organizational units', 'en' => 'Admin Console → Organizational units'],
                    'setting' => ['de' => 'OU Hierarchy und Policy Inheritance dokumentieren', 'en' => 'Document OU hierarchy and policy inheritance'],
                    'why' => ['de' => 'Directory Rollups und User-ohne-OU DQ bleiben steuerbar.', 'en' => 'Directory rollups and user-without-OU DQ stay controllable.'],
                    'how' => ['de' => 'Maintain OU tree; default OU for provisioning.', 'en' => 'Maintain OU tree; default OU for provisioning.'],
                ],
                [
                    'id' => 'gws-reports-api-retention',
                    'area' => ['de' => 'Reports → Login / Audit', 'en' => 'Reports → Login / Audit'],
                    'setting' => ['de' => 'Reports API Extract Allowlist; kurze Retention für IPs', 'en' => 'Reports API extract allowlist; short retention for IPs'],
                    'why' => ['de' => 'Login Activity KPIs ohne unnötige Security-PII.', 'en' => 'Login activity KPIs without unnecessary security PII.'],
                    'how' => ['de' => 'Allowlist event fields; hash IPs; omit mail/drive bodies.', 'en' => 'Allowlist event fields; hash IPs; omit mail/drive bodies.'],
                ],
                [
                    'id' => 'gws-drive-sharing',
                    'area' => ['de' => 'Drive → Sharing settings', 'en' => 'Drive → Sharing settings'],
                    'setting' => ['de' => 'External Sharing Limits; Activity Metadata only in Warehouse', 'en' => 'External sharing limits; activity metadata only in warehouse'],
                    'why' => ['de' => 'Collaboration KPIs ohne File/Mail Bodies.', 'en' => 'Collaboration KPIs without file/mail bodies.'],
                    'how' => ['de' => 'OU sharing policies; extract Drive Activity targets only.', 'en' => 'OU sharing policies; extract Drive Activity targets only.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'gws-admin-sdk-directory',
                    'kind' => ['de' => 'Admin SDK Directory', 'en' => 'Admin SDK Directory'],
                    'where' => ['de' => 'Admin SDK → Directory API (users, groups, orgunits)', 'en' => 'Admin SDK → Directory API (users, groups, orgunits)'],
                    'how' => ['de' => 'User/Group/OU fields inventarisieren; PII Allowlist.', 'en' => 'Inventory user/group/OU fields; PII allowlist.'],
                    'useFor' => ['de' => 'Directory dims, MDM keys, entitlement facts.', 'en' => 'Directory dims, MDM keys, entitlement facts.'],
                    'watchouts' => ['de' => 'primaryEmail/phones — nicht in öffentlichen Marts.', 'en' => 'primaryEmail/phones — not in public marts.'],
                ],
                [
                    'id' => 'gws-reports-api',
                    'kind' => ['de' => 'Reports API', 'en' => 'Reports API'],
                    'where' => ['de' => 'Admin SDK → Reports API (login, admin, drive activity usage)', 'en' => 'Admin SDK → Reports API (login, admin, drive activity usage)'],
                    'how' => ['de' => 'Event Types Allowlist; Sensitive Fields taggen.', 'en' => 'Allowlist event types; tag sensitive fields.'],
                    'useFor' => ['de' => 'Login facts, admin audit, usage KPIs.', 'en' => 'Login facts, admin audit, usage KPIs.'],
                    'watchouts' => ['de' => 'IP/email cleartext — restrict; short retention.', 'en' => 'IP/email cleartext — restrict; short retention.'],
                ],
                [
                    'id' => 'gws-drive-activity-api',
                    'kind' => ['de' => 'Drive Activity API', 'en' => 'Drive Activity API'],
                    'where' => ['de' => 'Google Drive Activity API → activity records', 'en' => 'Google Drive Activity API → activity records'],
                    'how' => ['de' => 'Actor/Target/Action Metadata dokumentieren — keine File Bodies.', 'en' => 'Document actor/target/action metadata — no file bodies.'],
                    'useFor' => ['de' => 'Collaboration activity facts, sharing change signals.', 'en' => 'Collaboration activity facts, sharing change signals.'],
                    'watchouts' => ['de' => 'Nie Drive file export/content in Warehouse.', 'en' => 'Never put Drive file export/content in warehouse.'],
                ],
                [
                    'id' => 'gws-org-units-meta',
                    'kind' => ['de' => 'Org units', 'en' => 'Org units'],
                    'where' => ['de' => 'Admin Console → Directory → Organizational units', 'en' => 'Admin Console → Directory → Organizational units'],
                    'how' => ['de' => 'OU Tree und Policy Bindings exportieren.', 'en' => 'Export OU tree and policy bindings.'],
                    'useFor' => ['de' => 'OU dims, user-without-OU DQ, policy coverage.', 'en' => 'OU dims, user-without-OU DQ, policy coverage.'],
                    'watchouts' => ['de' => 'OU Renames — SCD2; historische Pfade behalten.', 'en' => 'OU renames — SCD2; keep historical paths.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],
];
