<?php

/**
 * Wave 9 quality overlays — ERP/Finance/HCM source-native DQ, MDM, metadata guides.
 *
 * @return array<string, array<string, mixed>>
 */

return [
    'datev' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'datev-booking-unbalanced',
                    'priority' => 'high',
                    'title' => ['de' => 'Buchungssatz nicht ausgeglichen (Soll ≠ Haben)', 'en' => 'Booking record not balanced (debit ≠ credit)'],
                    'problem' => ['de' => 'Unausgeglichene Buchungssätze brechen GL-Reports und Bilanzsummen.', 'en' => 'Unbalanced booking records break GL reports and balance sheet totals.'],
                    'prevent' => ['de' => 'DATEV-Export-Validierung vor Import; EXTF-Prüfsummen nutzen.', 'en' => 'Validate the DATEV export before import; use EXTF checksums.'],
                    'staffNeedToKnow' => ['de' => 'Finance: Kein Import ohne Ausgleichsprüfung.', 'en' => 'Finance: No import without balance validation.'],
                    'checks' => ['de' => 'SUM(amount) GROUP BY mandant, period != 0', 'en' => 'SUM(amount) GROUP BY mandant, period != 0'],
                    'fixInSource' => ['de' => 'Re-export aus DATEV nach Korrekturbuchung.', 'en' => 'Re-export from DATEV after correcting the posting.'],
                    'fixInWarehouse' => ['de' => 'Quarantine period until balanced; flag import batch.', 'en' => 'Quarantine period until balanced; flag import batch.'],
                ],
                [
                    'id' => 'datev-debtor-no-tax-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Debitor ohne Steuer-ID (B2B)', 'en' => 'Debtor without tax ID (B2B)'],
                    'problem' => ['de' => 'B2B-Debitoren ohne USt-IdNr. erschweren Reverse-Charge-Reporting.', 'en' => 'B2B debtors without VAT ID complicate reverse-charge reporting.'],
                    'prevent' => ['de' => 'Stammdaten-Pflichtfeld für B2B-Kunden im Vorsystem.', 'en' => 'Make it a required master-data field for B2B customers upstream.'],
                    'staffNeedToKnow' => ['de' => 'Debitorenbuchhaltung: USt-IdNr. bei Anlage prüfen.', 'en' => 'AR team: verify VAT ID at account creation.'],
                    'checks' => ['de' => "customer_segment = 'B2B' AND tax_id IS NULL", 'en' => "customer_segment = 'B2B' AND tax_id IS NULL"],
                    'fixInSource' => ['de' => 'Stammdaten in DATEV Rewe nachpflegen.', 'en' => 'Update master data in DATEV Rewe.'],
                    'fixInWarehouse' => ['de' => 'Flag missing_tax_id; exclude from reverse-charge KPI.', 'en' => 'Flag missing_tax_id; exclude from reverse-charge KPI.'],
                ],
                [
                    'id' => 'datev-open-item-no-clearing',
                    'priority' => 'high',
                    'title' => ['de' => 'Offener Posten ohne Ausgleichsbuchung nach Fälligkeit+90', 'en' => 'Open item without clearing posting 90+ days past due'],
                    'problem' => ['de' => 'Lange offene Posten verzerren DSO und Bonitätsrisiko.', 'en' => 'Long-open items distort DSO and credit risk.'],
                    'prevent' => ['de' => 'Mahnlauf-Cadence; automatisiertes OPOS-Monitoring.', 'en' => 'Dunning run cadence; automated OPOS monitoring.'],
                    'staffNeedToKnow' => ['de' => 'Debitorenbuchhaltung: 90+ Tage offene Posten eskalieren.', 'en' => 'AR team: escalate items open 90+ days.'],
                    'checks' => ['de' => 'is_cleared = FALSE AND due_date < CURRENT_DATE - 90', 'en' => 'is_cleared = FALSE AND due_date < CURRENT_DATE - 90'],
                    'fixInSource' => ['de' => 'Mahnverfahren einleiten oder Ausbuchung prüfen.', 'en' => 'Initiate dunning or review write-off.'],
                    'fixInWarehouse' => ['de' => 'Flag aged_open_item; separate collections KPI.', 'en' => 'Flag aged_open_item; separate collections KPI.'],
                ],
                [
                    'id' => 'datev-account-not-in-skr',
                    'priority' => 'medium',
                    'title' => ['de' => 'Kontonummer außerhalb des SKR03/SKR04-Bereichs', 'en' => 'Account number outside the SKR03/SKR04 range'],
                    'problem' => ['de' => 'Konten außerhalb des Kontenrahmens brechen Kontenart-Mapping (Erlös/Aufwand/Bestand).', 'en' => 'Accounts outside the chart of accounts break account-type mapping (revenue/expense/balance).'],
                    'prevent' => ['de' => 'Kontenrahmen-Erweiterungen dokumentieren; Custom-Range-Mapping pflegen.', 'en' => 'Document chart-of-accounts extensions; maintain a custom-range mapping.'],
                    'staffNeedToKnow' => ['de' => 'Finance: Custom-Konten im Mapping nachpflegen.', 'en' => 'Finance: Update custom accounts in the mapping.'],
                    'checks' => ['de' => 'account_number NOT IN (known SKR03/SKR04 ranges)', 'en' => 'account_number NOT IN (known SKR03/SKR04 ranges)'],
                    'fixInSource' => ['de' => 'Kontenplan-Review mit Steuerberater.', 'en' => 'Chart-of-accounts review with the tax advisor.'],
                    'fixInWarehouse' => ['de' => 'Unknown account_type bucket; exclude from GL rollups until mapped.', 'en' => 'Unknown account_type bucket; exclude from GL rollups until mapped.'],
                ],
                [
                    'id' => 'datev-duplicate-beleg',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Belegnummer im Export', 'en' => 'Duplicate document number in export'],
                    'problem' => ['de' => 'Doppelte Belegfeld1-Werte verzerren Umsatz- und Aufwandssummen.', 'en' => 'Duplicate document-field-1 values distort revenue and expense totals.'],
                    'prevent' => ['de' => 'Idempotenter EXTF-Import; Batch-Overlap prüfen.', 'en' => 'Idempotent EXTF import; check batch overlap.'],
                    'staffNeedToKnow' => ['de' => 'Data: Natural Key = Mandant + Belegfeld1 + Buchungsdatum.', 'en' => 'Data: Natural key = client + document field 1 + booking date.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY mandant, beleg_feld1 HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY mandant, beleg_feld1 HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-export prüfen; Überlappung im Exportzeitraum korrigieren.', 'en' => 'Review re-export; correct overlap in the export period.'],
                    'fixInWarehouse' => ['de' => 'Dedup by mandant+beleg_feld1+booking_date; keep latest _loaded_at.', 'en' => 'Dedup by mandant+beleg_feld1+booking_date; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'datev-debtor-dup',
                    'entity' => 'Debtor',
                    'title' => ['de' => 'Debitor-Duplikate', 'en' => 'Debtor duplicates'],
                    'matchKeys' => ['debtor_number', 'tax_id (hashed)', 'iban (hashed)', 'name+address fuzzy'],
                    'preventInSource' => ['de' => 'Stammdaten-Anlage nur nach Dublettenprüfung.', 'en' => 'Only create master data after a duplicate check.'],
                    'resolveInWarehouse' => ['de' => 'Golden debtor_number; hashed tax_id merge map.', 'en' => 'Golden debtor_number; hashed tax_id merge map.'],
                    'survivorship' => ['de' => 'Debitor mit jüngster Buchung und vollständigen Stammdaten gewinnt.', 'en' => 'Debtor with the most recent posting and complete master data wins.'],
                ],
                [
                    'id' => 'datev-account-mapping',
                    'entity' => 'Account',
                    'title' => ['de' => 'SKR03 vs. SKR04 Kontenmapping bei Kontenrahmen-Wechsel', 'en' => 'SKR03 vs SKR04 account mapping on chart-of-accounts change'],
                    'matchKeys' => ['account_number', 'skr_type', 'account_type'],
                    'preventInSource' => ['de' => 'Kontenrahmen-Wechsel dokumentieren; Übergangsmapping pflegen.', 'en' => 'Document chart-of-accounts changes; maintain a transition mapping.'],
                    'resolveInWarehouse' => ['de' => 'Canonical account_type map über beide Kontenrahmen.', 'en' => 'Canonical account_type map spanning both charts of accounts.'],
                    'survivorship' => ['de' => 'Aktueller Kontenrahmen gewinnt; historische Zuordnung als Mapping-Tabelle.', 'en' => 'Current chart of accounts wins; historical mapping kept as a lookup table.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'datev-extf-export',
                    'area' => ['de' => 'DATEV Rewe → Datenexport → EXTF/ASCII', 'en' => 'DATEV Rewe → data export → EXTF/ASCII'],
                    'setting' => ['de' => 'Feld-Allowlist und Prüfsummen im EXTF-Export', 'en' => 'Field allowlist and checksums in the EXTF export'],
                    'why' => ['de' => 'Unausgeglichene Importe und Feld-Drift werden vermeidbar.', 'en' => 'Unbalanced imports and field drift become avoidable.'],
                    'how' => ['de' => 'Standard-Kategorien exportieren; Prüfsumme vor Import validieren.', 'en' => 'Export standard categories; validate checksum before import.'],
                ],
                [
                    'id' => 'datev-opos-mahnwesen',
                    'area' => ['de' => 'DATEV → Rechnungswesen → OPOS/Mahnwesen', 'en' => 'DATEV → accounting → OPOS/dunning'],
                    'setting' => ['de' => 'OPOS-Kennzeichen konsequent pflegen', 'en' => 'Consistently maintain the OPOS flag'],
                    'why' => ['de' => 'Verlässliche Open-Items- und DSO-KPIs.', 'en' => 'Reliable open-items and DSO KPIs.'],
                    'how' => ['de' => 'Ausgleichsbuchungen zeitnah erfassen; Mahnlauf-Cadence festlegen.', 'en' => 'Record clearing postings promptly; set a dunning-run cadence.'],
                ],
                [
                    'id' => 'datev-payroll-separation',
                    'area' => ['de' => 'DATEV Lohn und Gehalt → Datenschutz', 'en' => 'DATEV Lohn und Gehalt → data protection'],
                    'setting' => ['de' => 'Getrennte Datenhaltung von Rewe (Finance) und Lohn (Payroll)', 'en' => 'Separate data storage for Rewe (finance) and Lohn (payroll)'],
                    'why' => ['de' => 'Verhindert versehentliche Gehalts-Landung im Finance-Warehouse.', 'en' => 'Prevents accidentally landing salary data in the finance warehouse.'],
                    'how' => ['de' => 'Separate Extract-Pipelines und Zugriffsrollen je Modul.', 'en' => 'Separate extract pipelines and access roles per module.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'datev-extf-format-doc',
                    'kind' => ['de' => 'EXTF/ASCII Format-Dokumentation', 'en' => 'EXTF/ASCII format documentation'],
                    'where' => ['de' => 'DATEV Hilfe-Center → Schnittstellen → Buchungsstapel/Stammdaten', 'en' => 'DATEV Help Center → interfaces → posting batch/master data'],
                    'how' => ['de' => 'Kategorie- und Feld-Referenz für Buchungsstapel/Debitoren/Kreditoren inventarisieren.', 'en' => 'Inventory category and field reference for posting batch/debtors/creditors.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (Belegfeld1, Debitoren-/Kreditorennummer).', 'en' => 'Extract design, PII tags, join keys (document field 1, debtor/creditor number).'],
                    'watchouts' => ['de' => 'Feldpositionen sind versionsabhängig — Format-Version dokumentieren.', 'en' => 'Field positions are version-dependent — document the format version.'],
                ],
                [
                    'id' => 'datev-kontenrahmen',
                    'kind' => ['de' => 'SKR03/SKR04 Kontenrahmen', 'en' => 'SKR03/SKR04 chart of accounts'],
                    'where' => ['de' => 'DATEV/Steuerberater → Kontenrahmen-Referenz', 'en' => 'DATEV/tax advisor → chart-of-accounts reference'],
                    'how' => ['de' => 'Kontonummer-Ranges zu Kontoart (Aktiv/Passiv/Erlös/Aufwand) mappen.', 'en' => 'Map account-number ranges to account type (asset/liability/revenue/expense).'],
                    'useFor' => ['de' => 'GL-Dimension, Erlös-/Aufwands-Measures.', 'en' => 'GL dimension, revenue/expense measures.'],
                    'watchouts' => ['de' => 'Individualkonten außerhalb Standard-Range separat mappen.', 'en' => 'Map custom accounts outside the standard range separately.'],
                ],
                [
                    'id' => 'datev-steuerschluessel',
                    'kind' => ['de' => 'BU-Schlüssel / Steuerschlüssel-Tabelle', 'en' => 'Automatic posting key / tax key table'],
                    'where' => ['de' => 'DATEV Hilfe-Center → Steuerschlüssel-Referenz', 'en' => 'DATEV Help Center → tax key reference'],
                    'how' => ['de' => 'BU-Schlüssel zu USt-Satz und Meldepflicht (z. B. Reverse Charge) mappen.', 'en' => 'Map automatic posting keys to VAT rate and reporting obligation (e.g. reverse charge).'],
                    'useFor' => ['de' => 'VAT-liability measure, Reverse-Charge-Reporting.', 'en' => 'VAT-liability measure, reverse-charge reporting.'],
                    'watchouts' => ['de' => 'Schlüssel ändern sich bei Steuersatz-Änderungen — SCD2 empfohlen.', 'en' => 'Keys change with tax-rate changes — SCD2 recommended.'],
                ],
                [
                    'id' => 'datev-mandantenstruktur',
                    'kind' => ['de' => 'Mandantenstruktur', 'en' => 'Client (Mandant) structure'],
                    'where' => ['de' => 'DATEV Arbeitsplatz → Mandantenverwaltung', 'en' => 'DATEV workstation → client management'],
                    'how' => ['de' => 'Mandantennummern und Beraternummer dokumentieren.', 'en' => 'Document client numbers and consultant number.'],
                    'useFor' => ['de' => 'Tenant-Dimension bei Multi-Mandanten-Setups.', 'en' => 'Tenant dimension for multi-client setups.'],
                    'watchouts' => ['de' => 'Test-Mandanten klar von Produktiv-Mandanten trennen.', 'en' => 'Clearly separate test clients from production clients.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'sage' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'sage-journal-unbalanced',
                    'priority' => 'high',
                    'title' => ['de' => 'Journal Entry nicht ausgeglichen', 'en' => 'Journal entry not balanced'],
                    'problem' => ['de' => 'SUM(debit) ≠ SUM(credit) je Journal bricht GL-Reports.', 'en' => 'SUM(debit) ≠ SUM(credit) per journal breaks GL reports.'],
                    'prevent' => ['de' => 'Posting-Validierung vor Journal-Freigabe im Quellsystem.', 'en' => 'Posting validation before journal release in the source system.'],
                    'staffNeedToKnow' => ['de' => 'Finance: Kein Import ohne Balance-Check je Journal.', 'en' => 'Finance: No import without a per-journal balance check.'],
                    'checks' => ['de' => 'SUM(debit_amount) - SUM(credit_amount) GROUP BY journal_id != 0', 'en' => 'SUM(debit_amount) - SUM(credit_amount) GROUP BY journal_id != 0'],
                    'fixInSource' => ['de' => 'Journal korrigieren und erneut posten.', 'en' => 'Correct and re-post the journal.'],
                    'fixInWarehouse' => ['de' => 'Quarantine journal_id until balanced.', 'en' => 'Quarantine journal_id until balanced.'],
                ],
                [
                    'id' => 'sage-invoice-no-customer',
                    'priority' => 'high',
                    'title' => ['de' => 'Sales Invoice ohne Customer', 'en' => 'Sales invoice without customer'],
                    'problem' => ['de' => 'Invoices ohne customer_id brechen Revenue-by-Customer und AR-KPIs.', 'en' => 'Invoices without customer_id break revenue-by-customer and AR KPIs.'],
                    'prevent' => ['de' => 'Pflichtfeld customer_id im Order-to-Cash-Prozess.', 'en' => 'Required customer_id field in the order-to-cash process.'],
                    'staffNeedToKnow' => ['de' => 'Billing: Keine Invoice ohne Customer-Zuordnung.', 'en' => 'Billing: No invoice without a customer assignment.'],
                    'checks' => ['de' => 'sales_invoice.customer_id IS NULL', 'en' => 'sales_invoice.customer_id IS NULL'],
                    'fixInSource' => ['de' => 'Invoice im Quellsystem korrigieren/zuordnen.', 'en' => 'Correct/assign the invoice in the source system.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown customer dim.', 'en' => 'Quarantine; unknown customer dim.'],
                ],
                [
                    'id' => 'sage-overdue-no-followup',
                    'priority' => 'medium',
                    'title' => ['de' => 'Überfällige Invoice ohne Follow-up-Status', 'en' => 'Overdue invoice without follow-up status'],
                    'problem' => ['de' => 'Überfällige Rechnungen ohne Collection-Status verzerren AR-Aging.', 'en' => 'Overdue invoices without collection status distort AR aging.'],
                    'prevent' => ['de' => 'Collections-Workflow mit Pflicht-Statuswechsel.', 'en' => 'Collections workflow with mandatory status transitions.'],
                    'staffNeedToKnow' => ['de' => 'Credit Control: Überfällige Invoices aktiv nachverfolgen.', 'en' => 'Credit control: actively follow up on overdue invoices.'],
                    'checks' => ['de' => "due_date < CURRENT_DATE AND status = 'open' AND days_overdue > 30", 'en' => "due_date < CURRENT_DATE AND status = 'open' AND days_overdue > 30"],
                    'fixInSource' => ['de' => 'Collections-Aktivität im Quellsystem erfassen.', 'en' => 'Record collections activity in the source system.'],
                    'fixInWarehouse' => ['de' => 'Flag aged_receivable; separate collections KPI.', 'en' => 'Flag aged_receivable; separate collections KPI.'],
                ],
                [
                    'id' => 'sage-supplier-no-bank',
                    'priority' => 'medium',
                    'title' => ['de' => 'Supplier ohne Bankverbindung bei fälliger Zahlung', 'en' => 'Supplier without bank details when payment is due'],
                    'problem' => ['de' => 'Fehlende Bankdaten blockieren Zahlungsläufe.', 'en' => 'Missing bank details block payment runs.'],
                    'prevent' => ['de' => 'Supplier-Onboarding: Bankdaten-Pflichtfeld vor erster Zahlung.', 'en' => 'Supplier onboarding: bank-details required field before first payment.'],
                    'staffNeedToKnow' => ['de' => 'AP-Team: Bankdaten vor Freigabe prüfen.', 'en' => 'AP team: verify bank details before release.'],
                    'checks' => ['de' => 'ap_invoice.due_date <= CURRENT_DATE + 3 AND supplier.bank_details IS NULL', 'en' => 'ap_invoice.due_date <= CURRENT_DATE + 3 AND supplier.bank_details IS NULL'],
                    'fixInSource' => ['de' => 'Supplier-Stammdaten ergänzen.', 'en' => 'Complete supplier master data.'],
                    'fixInWarehouse' => ['de' => 'Flag payment_blocked; exclude from on-time payment KPI numerator.', 'en' => 'Flag payment_blocked; exclude from on-time payment KPI numerator.'],
                ],
                [
                    'id' => 'sage-duplicate-invoice-number',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Invoice-Nummer je Supplier/Customer', 'en' => 'Duplicate invoice number per supplier/customer'],
                    'problem' => ['de' => 'Doppelte Invoice-IDs verzerren AP/AR-Summen und Zahlungshistorie.', 'en' => 'Duplicate invoice IDs distort AP/AR totals and payment history.'],
                    'prevent' => ['de' => 'Idempotenter Sync; API-Pagination-Overlap prüfen.', 'en' => 'Idempotent sync; check API pagination overlap.'],
                    'staffNeedToKnow' => ['de' => 'Data: Natural Key = supplier_id/customer_id + invoice number.', 'en' => 'Data: Natural key = supplier_id/customer_id + invoice number.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY supplier_id, invoice_number HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY supplier_id, invoice_number HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-sync; API-Pagination untersuchen.', 'en' => 'Re-sync; investigate API pagination.'],
                    'fixInWarehouse' => ['de' => 'Dedup by supplier_id+invoice_number; keep latest _loaded_at.', 'en' => 'Dedup by supplier_id+invoice_number; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'sage-supplier-dup',
                    'entity' => 'Supplier',
                    'title' => ['de' => 'Supplier-Duplikate', 'en' => 'Supplier duplicates'],
                    'matchKeys' => ['supplier_id', 'tax_registration_number (hashed)', 'bank_details (hashed)', 'name fuzzy'],
                    'preventInSource' => ['de' => 'Dublettenprüfung bei Supplier-Onboarding.', 'en' => 'Duplicate check during supplier onboarding.'],
                    'resolveInWarehouse' => ['de' => 'Golden supplier_id; hashed tax id merge map.', 'en' => 'Golden supplier_id; hashed tax id merge map.'],
                    'survivorship' => ['de' => 'Supplier mit aktivstem Zahlungsverlauf gewinnt.', 'en' => 'Supplier with the most active payment history wins.'],
                ],
                [
                    'id' => 'sage-gl-account-map',
                    'entity' => 'GL Account',
                    'title' => ['de' => 'Chart-of-Accounts Mapping bei Multi-Company', 'en' => 'Chart-of-accounts mapping across multiple companies'],
                    'matchKeys' => ['account_code', 'account_type', 'company/legal entity'],
                    'preventInSource' => ['de' => 'Konzernweiten Kontenrahmen-Standard pflegen.', 'en' => 'Maintain a group-wide chart-of-accounts standard.'],
                    'resolveInWarehouse' => ['de' => 'Canonical account_type map über alle Companies.', 'en' => 'Canonical account_type map across all companies.'],
                    'survivorship' => ['de' => 'Konzernstandard-Mapping gewinnt über lokale Abweichungen.', 'en' => 'Group-standard mapping wins over local deviations.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'sage-approval-workflow',
                    'area' => ['de' => 'Sage → Settings → Approval workflows', 'en' => 'Sage → Settings → Approval workflows'],
                    'setting' => ['de' => 'Journal- und Invoice-Freigabe-Workflow mit Balance-Check', 'en' => 'Journal and invoice approval workflow with balance check'],
                    'why' => ['de' => 'Unausgeglichene Journals werden vor Posting verhindert.', 'en' => 'Unbalanced journals get prevented before posting.'],
                    'how' => ['de' => 'Mandatory approval step; validation rule on debit=credit.', 'en' => 'Mandatory approval step; validation rule on debit=credit.'],
                ],
                [
                    'id' => 'sage-collections-cadence',
                    'area' => ['de' => 'Sage → Accounts Receivable → Collections', 'en' => 'Sage → Accounts Receivable → Collections'],
                    'setting' => ['de' => 'Collections-Cadence und Status-Pflege für überfällige Invoices', 'en' => 'Collections cadence and status maintenance for overdue invoices'],
                    'why' => ['de' => 'Verlässliches AR-Aging und Follow-up-Tracking.', 'en' => 'Reliable AR aging and follow-up tracking.'],
                    'how' => ['de' => 'Automated reminders; status transitions logged.', 'en' => 'Automated reminders; status transitions logged.'],
                ],
                [
                    'id' => 'sage-supplier-onboarding',
                    'area' => ['de' => 'Sage → Accounts Payable → Supplier onboarding', 'en' => 'Sage → Accounts Payable → Supplier onboarding'],
                    'setting' => ['de' => 'Pflichtfelder für Bankdaten und Tax Registration vor erster Zahlung', 'en' => 'Required fields for bank details and tax registration before first payment'],
                    'why' => ['de' => 'Zahlungsblockaden und fehlende Compliance-Daten werden vermeidbar.', 'en' => 'Payment blocks and missing compliance data become avoidable.'],
                    'how' => ['de' => 'Onboarding checklist; hard-stop validation on missing fields.', 'en' => 'Onboarding checklist; hard-stop validation on missing fields.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'sage-api-schema',
                    'kind' => ['de' => 'Sage API / Intacct object schema', 'en' => 'Sage API / Intacct object schema'],
                    'where' => ['de' => 'Sage Developer Hub → API reference (Business Cloud / Intacct / X3)', 'en' => 'Sage Developer Hub → API reference (Business Cloud / Intacct / X3)'],
                    'how' => ['de' => 'Object-Felder für GL Account, Journal, Customer, Supplier, Invoices inventarisieren.', 'en' => 'Inventory object fields for GL account, journal, customer, supplier, invoices.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys.', 'en' => 'Extract design, PII tags, join keys.'],
                    'watchouts' => ['de' => 'Produktvariante (Business Cloud vs. Intacct vs. X3) hat unterschiedliche Objektnamen.', 'en' => 'Product variant (Business Cloud vs Intacct vs X3) has different object names.'],
                ],
                [
                    'id' => 'sage-coa-structure',
                    'kind' => ['de' => 'Chart of accounts structure', 'en' => 'Chart of accounts structure'],
                    'where' => ['de' => 'Sage → General Ledger → Chart of accounts setup', 'en' => 'Sage → General Ledger → Chart of accounts setup'],
                    'how' => ['de' => 'Account-Ranges zu Kontoart mappen; Multi-Company-Struktur dokumentieren.', 'en' => 'Map account ranges to account type; document multi-company structure.'],
                    'useFor' => ['de' => 'GL-Dimension, Opex/Revenue-Measures.', 'en' => 'GL dimension, opex/revenue measures.'],
                    'watchouts' => ['de' => 'Company-spezifische Custom-Konten separat mappen.', 'en' => 'Map company-specific custom accounts separately.'],
                ],
                [
                    'id' => 'sage-tax-codes',
                    'kind' => ['de' => 'Tax code configuration', 'en' => 'Tax code configuration'],
                    'where' => ['de' => 'Sage → Settings → Tax → Tax codes', 'en' => 'Sage → Settings → Tax → Tax codes'],
                    'how' => ['de' => 'Tax Codes zu Rate und Jurisdiktion mappen.', 'en' => 'Map tax codes to rate and jurisdiction.'],
                    'useFor' => ['de' => 'VAT/Sales-Tax-Measures, Compliance-Reporting.', 'en' => 'VAT/sales-tax measures, compliance reporting.'],
                    'watchouts' => ['de' => 'Rate-Änderungen versionieren (SCD2).', 'en' => 'Version rate changes (SCD2).'],
                ],
                [
                    'id' => 'sage-approval-audit-trail',
                    'kind' => ['de' => 'Approval / audit trail', 'en' => 'Approval / audit trail'],
                    'where' => ['de' => 'Sage → Settings → Approval workflows / Audit trail', 'en' => 'Sage → Settings → Approval workflows / Audit trail'],
                    'how' => ['de' => 'Approval-Status und Change-Events als Feld-Referenz dokumentieren.', 'en' => 'Document approval status and change events as a field reference.'],
                    'useFor' => ['de' => 'DQ-Checks für Balance/Approval, Compliance-Nachweis.', 'en' => 'DQ checks for balance/approval, compliance evidence.'],
                    'watchouts' => ['de' => 'Volle Audit-Trail-Dumps nicht als Analytics-RAW laden.', 'en' => 'Do not load full audit-trail dumps as analytics RAW.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'oracle-fusion' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'fusion-journal-unbalanced',
                    'priority' => 'high',
                    'title' => ['de' => 'GL Journal nicht ausgeglichen je Ledger', 'en' => 'GL journal not balanced per ledger'],
                    'problem' => ['de' => 'SUM(entered_dr) ≠ SUM(entered_cr) bricht Trial-Balance-Reports.', 'en' => 'SUM(entered_dr) ≠ SUM(entered_cr) breaks trial-balance reports.'],
                    'prevent' => ['de' => 'Journal-Posting-Validierung vor Approval in Fusion GL.', 'en' => 'Journal posting validation before approval in Fusion GL.'],
                    'staffNeedToKnow' => ['de' => 'Finance: Kein Posting ohne Balance-Validierung je Ledger.', 'en' => 'Finance: No posting without a per-ledger balance validation.'],
                    'checks' => ['de' => 'SUM(entered_dr) - SUM(entered_cr) GROUP BY journal_id != 0', 'en' => 'SUM(entered_dr) - SUM(entered_cr) GROUP BY journal_id != 0'],
                    'fixInSource' => ['de' => 'Journal in Fusion GL korrigieren und neu posten.', 'en' => 'Correct and re-post the journal in Fusion GL.'],
                    'fixInWarehouse' => ['de' => 'Quarantine journal_id until balanced.', 'en' => 'Quarantine journal_id until balanced.'],
                ],
                [
                    'id' => 'fusion-worker-no-assignment',
                    'priority' => 'high',
                    'title' => ['de' => 'Worker ohne aktives Assignment', 'en' => 'Worker without active assignment'],
                    'problem' => ['de' => 'Worker ohne Assignment verzerren Headcount und Org-Rollups.', 'en' => 'Workers without an assignment distort headcount and org rollups.'],
                    'prevent' => ['de' => 'HCM-Extract: primary assignment immer mitladen.', 'en' => 'HCM extract: always load the primary assignment.'],
                    'staffNeedToKnow' => ['de' => 'HR-IT: Worker ohne Assignment ist Extract-Fehler oder Datenlücke.', 'en' => 'HR IT: Worker without assignment is an extract error or data gap.'],
                    'checks' => ['de' => 'worker.person_id NOT IN (SELECT person_id FROM assignment WHERE assignment_status = \'active\')', 'en' => 'worker.person_id NOT IN (SELECT person_id FROM assignment WHERE assignment_status = \'active\')'],
                    'fixInSource' => ['de' => 'Re-extract HCM assignments; check termination timing.', 'en' => 'Re-extract HCM assignments; check termination timing.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from headcount until resolved.', 'en' => 'Quarantine; exclude from headcount until resolved.'],
                ],
                [
                    'id' => 'fusion-ap-invoice-no-supplier',
                    'priority' => 'high',
                    'title' => ['de' => 'AP Invoice ohne Supplier', 'en' => 'AP invoice without supplier'],
                    'problem' => ['de' => 'Invoices ohne supplier_id brechen AP-Liability- und Spend-KPIs.', 'en' => 'Invoices without supplier_id break AP-liability and spend KPIs.'],
                    'prevent' => ['de' => 'Payables-Validierung: supplier_id Pflichtfeld vor Invoice-Import.', 'en' => 'Payables validation: supplier_id required field before invoice import.'],
                    'staffNeedToKnow' => ['de' => 'AP-Team: Keine Invoice ohne Supplier-Zuordnung freigeben.', 'en' => 'AP team: do not release an invoice without a supplier assignment.'],
                    'checks' => ['de' => 'ap_invoice.supplier_id IS NULL', 'en' => 'ap_invoice.supplier_id IS NULL'],
                    'fixInSource' => ['de' => 'Invoice in Fusion Payables korrigieren.', 'en' => 'Correct the invoice in Fusion Payables.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown supplier dim.', 'en' => 'Quarantine; unknown supplier dim.'],
                ],
                [
                    'id' => 'fusion-compensation-field-selected',
                    'priority' => 'high',
                    'title' => ['de' => 'Compensation-Klartextfeld versehentlich im Extract selektiert', 'en' => 'Compensation cleartext field accidentally selected in extract'],
                    'problem' => ['de' => 'Gehaltsbeträge im Standard-Extract verletzen die Workforce-PII-Policy.', 'en' => 'Salary amounts in the standard extract violate the workforce-PII policy.'],
                    'prevent' => ['de' => 'OTBI/FBDI Select-Allowlist ohne Compensation-Felder pflegen.', 'en' => 'Maintain an OTBI/FBDI select allowlist without compensation fields.'],
                    'staffNeedToKnow' => ['de' => 'Data Engineering: Compensation-Felder nie in Standard-Pipelines selektieren.', 'en' => 'Data engineering: never select compensation fields in standard pipelines.'],
                    'checks' => ['de' => "extract_field_name IN ('base_salary','bonus_amount','element_entry_value')", 'en' => "extract_field_name IN ('base_salary','bonus_amount','element_entry_value')"],
                    'fixInSource' => ['de' => 'Extract-Definition korrigieren; betroffene Landung löschen.', 'en' => 'Correct the extract definition; purge the affected landing.'],
                    'fixInWarehouse' => ['de' => 'Immediate purge; incident review; tighten allowlist.', 'en' => 'Immediate purge; incident review; tighten allowlist.'],
                ],
                [
                    'id' => 'fusion-duplicate-person-number',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte person_number im Extract', 'en' => 'Duplicate person_number in extract'],
                    'problem' => ['de' => 'Doppelte person_number verzerren Headcount und Turnover.', 'en' => 'Duplicate person_number distorts headcount and turnover.'],
                    'prevent' => ['de' => 'Idempotenter HCM-Extract; Effective-Dated-Records korrekt handhaben.', 'en' => 'Idempotent HCM extract; correctly handle effective-dated records.'],
                    'staffNeedToKnow' => ['de' => 'Data: Effective-Dating (SCD2) statt Duplikate erwarten.', 'en' => 'Data: Expect effective-dating (SCD2), not duplicates.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY person_number, effective_date HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY person_number, effective_date HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; effective-dated view korrekt verwenden.', 'en' => 'Re-extract; use the effective-dated view correctly.'],
                    'fixInWarehouse' => ['de' => 'Dedup by person_number+effective_date; keep latest _loaded_at.', 'en' => 'Dedup by person_number+effective_date; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'fusion-worker-dup',
                    'entity' => 'Worker',
                    'title' => ['de' => 'Worker-Duplikate / Rehire', 'en' => 'Worker duplicates / rehire'],
                    'matchKeys' => ['person_id', 'person_number', 'national_identifier (hashed)'],
                    'preventInSource' => ['de' => 'HCM als Source of Truth; Rehire statt Neuanlage.', 'en' => 'HCM as source of truth; rehire instead of recreating.'],
                    'resolveInWarehouse' => ['de' => 'Golden person_id; person_number SCD2.', 'en' => 'Golden person_id; person_number SCD2.'],
                    'survivorship' => ['de' => 'Aktiver Worker mit neuestem Assignment gewinnt.', 'en' => 'Active worker with the latest assignment wins.'],
                ],
                [
                    'id' => 'fusion-supplier-customer-map',
                    'entity' => 'Supplier / Customer',
                    'title' => ['de' => 'Supplier vs. Customer Doppelrolle (Trading Partner)', 'en' => 'Supplier vs customer dual role (trading partner)'],
                    'matchKeys' => ['tax_registration_number (hashed)', 'trading partner id'],
                    'preventInSource' => ['de' => 'Trading-Partner-Modell konsequent nutzen statt getrennter Anlage.', 'en' => 'Consistently use the trading-partner model instead of separate creation.'],
                    'resolveInWarehouse' => ['de' => 'Canonical trading_partner_id → supplier_id/customer_id map.', 'en' => 'Canonical trading_partner_id → supplier_id/customer_id map.'],
                    'survivorship' => ['de' => 'Aktiver Trading-Partner-Datensatz gewinnt über Legacy-Duplikate.', 'en' => 'Active trading-partner record wins over legacy duplicates.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'fusion-otbi-allowlist',
                    'area' => ['de' => 'Oracle Fusion → OTBI / BI Publisher → Subject Areas', 'en' => 'Oracle Fusion → OTBI / BI Publisher → Subject areas'],
                    'setting' => ['de' => 'Select-Allowlist ohne Compensation-/National-Identifier-Felder', 'en' => 'Select allowlist without compensation/national-identifier fields'],
                    'why' => ['de' => 'Verhindert versehentliche PII-/Compensation-Landung im Warehouse.', 'en' => 'Prevents accidental PII/compensation landing in the warehouse.'],
                    'how' => ['de' => 'Subject-Area-Felder reviewen; sensitive Felder aus Standard-Reports entfernen.', 'en' => 'Review subject-area fields; remove sensitive fields from standard reports.'],
                ],
                [
                    'id' => 'fusion-fbdi-extract-scope',
                    'area' => ['de' => 'Oracle Fusion → FBDI / BI Cloud Connector → Extract definitions', 'en' => 'Oracle Fusion → FBDI / BI Cloud Connector → Extract definitions'],
                    'setting' => ['de' => 'Extract-Definitionen mit minimalem Feld-Scope je Pillar (ERP/HCM/CX)', 'en' => 'Extract definitions with minimal field scope per pillar (ERP/HCM/CX)'],
                    'why' => ['de' => 'Cross-Pillar-PII-Leaks werden vermeidbar.', 'en' => 'Cross-pillar PII leaks become avoidable.'],
                    'how' => ['de' => 'Separate Extracts je Pillar; Review vor Aktivierung.', 'en' => 'Separate extracts per pillar; review before activation.'],
                ],
                [
                    'id' => 'fusion-hcm-security-profiles',
                    'area' => ['de' => 'Oracle Fusion HCM → Security → Person Security Profiles', 'en' => 'Oracle Fusion HCM → Security → Person security profiles'],
                    'setting' => ['de' => 'Security-Profile für Compensation- und Sensitive-Data-Zugriff', 'en' => 'Security profiles for compensation and sensitive-data access'],
                    'why' => ['de' => 'Least-Privilege-Zugriff auf Worker-PII und Compensation.', 'en' => 'Least-privilege access to worker PII and compensation.'],
                    'how' => ['de' => 'Rollenbasierte Profile; periodische Access-Reviews.', 'en' => 'Role-based profiles; periodic access reviews.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'fusion-erp-cloud-schema',
                    'kind' => ['de' => 'ERP Cloud REST API schema', 'en' => 'ERP Cloud REST API schema'],
                    'where' => ['de' => 'Oracle Fusion ERP Cloud → REST API for Financials', 'en' => 'Oracle Fusion ERP Cloud → REST API for Financials'],
                    'how' => ['de' => 'Object-Felder für GL Journals, Payables/Receivables Invoices inventarisieren.', 'en' => 'Inventory object fields for GL journals, Payables/Receivables invoices.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys.', 'en' => 'Extract design, PII tags, join keys.'],
                    'watchouts' => ['de' => 'Descriptive Flexfields können sensible Custom-Daten enthalten.', 'en' => 'Descriptive flexfields can contain sensitive custom data.'],
                ],
                [
                    'id' => 'fusion-hcm-cloud-schema',
                    'kind' => ['de' => 'HCM Cloud REST API schema', 'en' => 'HCM Cloud REST API schema'],
                    'where' => ['de' => 'Oracle Fusion HCM Cloud → REST API for HCM (Workers, Assignments)', 'en' => 'Oracle Fusion HCM Cloud → REST API for HCM (workers, assignments)'],
                    'how' => ['de' => 'Worker-/Assignment-Felder inventarisieren; Compensation-Felder explizit ausschließen.', 'en' => 'Inventory worker/assignment fields; explicitly exclude compensation fields.'],
                    'useFor' => ['de' => 'Employee-master dims, headcount/turnover measures.', 'en' => 'Employee-master dims, headcount/turnover measures.'],
                    'watchouts' => ['de' => 'Nie national_identifier oder Payroll-Element-Werte selektieren.', 'en' => 'Never select national_identifier or payroll element values.'],
                ],
                [
                    'id' => 'fusion-chart-of-accounts',
                    'kind' => ['de' => 'Chart of accounts / value sets', 'en' => 'Chart of accounts / value sets'],
                    'where' => ['de' => 'Fusion GL → Setup and Maintenance → Manage Chart of Accounts', 'en' => 'Fusion GL → Setup and Maintenance → Manage Chart of Accounts'],
                    'how' => ['de' => 'Segment-Struktur (Company/Cost Center/Account) dokumentieren.', 'en' => 'Document the segment structure (company/cost center/account).'],
                    'useFor' => ['de' => 'GL-Dimension, Business-Unit-Rollups.', 'en' => 'GL dimension, business-unit rollups.'],
                    'watchouts' => ['de' => 'Segment-Werte-Sets ändern sich pro Ledger — Mapping pro Ledger pflegen.', 'en' => 'Segment value sets differ per ledger — maintain mapping per ledger.'],
                ],
                [
                    'id' => 'fusion-otbi-subject-areas',
                    'kind' => ['de' => 'OTBI subject areas', 'en' => 'OTBI subject areas'],
                    'where' => ['de' => 'Fusion → Reports and Analytics → OTBI Subject Area catalog', 'en' => 'Fusion → Reports and Analytics → OTBI subject area catalog'],
                    'how' => ['de' => 'Verfügbare Felder je Subject Area als Referenz für Allowlists nutzen.', 'en' => 'Use available fields per subject area as a reference for allowlists.'],
                    'useFor' => ['de' => 'Extract design ohne Custom-API-Entwicklung.', 'en' => 'Extract design without custom API development.'],
                    'watchouts' => ['de' => 'Manche Subject Areas exponieren Compensation standardmäßig — prüfen.', 'en' => 'Some subject areas expose compensation by default — review carefully.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'personio' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'personio-employee-no-department',
                    'priority' => 'high',
                    'title' => ['de' => 'Employee ohne Department', 'en' => 'Employee without department'],
                    'problem' => ['de' => 'Employees ohne Department brechen Org-Rollups und Headcount-by-Department.', 'en' => 'Employees without a department break org rollups and headcount-by-department.'],
                    'prevent' => ['de' => 'Onboarding-Workflow: Department Pflichtfeld vor Aktivierung.', 'en' => 'Onboarding workflow: department required field before activation.'],
                    'staffNeedToKnow' => ['de' => 'HR-Ops: Kein aktiver Employee ohne Department.', 'en' => 'HR ops: no active employee without a department.'],
                    'checks' => ['de' => "status = 'active' AND department IS NULL", 'en' => "status = 'active' AND department IS NULL"],
                    'fixInSource' => ['de' => 'Department in Personio nachpflegen.', 'en' => 'Update department in Personio.'],
                    'fixInWarehouse' => ['de' => 'Unknown department bucket; exclude from department rollups.', 'en' => 'Unknown department bucket; exclude from department rollups.'],
                ],
                [
                    'id' => 'personio-absence-no-employee',
                    'priority' => 'high',
                    'title' => ['de' => 'Absence ohne gültige Employee-Referenz', 'en' => 'Absence without a valid employee reference'],
                    'problem' => ['de' => 'Absences ohne employee_id brechen Absence-Days-Measures.', 'en' => 'Absences without employee_id break absence-days measures.'],
                    'prevent' => ['de' => 'API-Extract: employee_id immer mitladen; Soft-deleted Employees tracken.', 'en' => 'API extract: always load employee_id; track soft-deleted employees.'],
                    'staffNeedToKnow' => ['de' => 'Data: Absence ohne Employee ist Extract-Fehler.', 'en' => 'Data: Absence without employee is an extract error.'],
                    'checks' => ['de' => 'absence.employee_id IS NULL OR employee_id NOT IN dim_employee', 'en' => 'absence.employee_id IS NULL OR employee_id NOT IN dim_employee'],
                    'fixInSource' => ['de' => 'Re-extract mit Employee-Kontext; gelöschte Employees berücksichtigen.', 'en' => 'Re-extract with employee context; account for deleted employees.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown employee dim.', 'en' => 'Quarantine; unknown employee dim.'],
                ],
                [
                    'id' => 'personio-compensation-cleartext-in-mart',
                    'priority' => 'high',
                    'title' => ['de' => 'Compensation-Klartext in einem Mart-Modell gefunden', 'en' => 'Compensation cleartext found in a mart model'],
                    'problem' => ['de' => 'Gehaltsbetrag im Mart verletzt die Workforce-PII-Policy und Mitbestimmungsrecht.', 'en' => 'Salary amount in a mart violates the workforce-PII policy and works-council rights.'],
                    'prevent' => ['de' => 'CI-Check: amount-Spalten aus compensation nie in Mart-Selects.', 'en' => 'CI check: never select compensation amount columns in mart models.'],
                    'staffNeedToKnow' => ['de' => 'Analytics Engineering: Compensation-Betrag ist Mart-Tabu.', 'en' => 'Analytics engineering: compensation amount is a mart taboo.'],
                    'checks' => ['de' => "model_layer = 'mart' AND column_name = 'amount' AND source_table = 'compensation'", 'en' => "model_layer = 'mart' AND column_name = 'amount' AND source_table = 'compensation'"],
                    'fixInSource' => ['de' => 'Mart-Modell korrigieren; nur Bänder/Counts exponieren.', 'en' => 'Correct the mart model; expose only bands/counts.'],
                    'fixInWarehouse' => ['de' => 'Immediate model fix; incident review; add CI guard.', 'en' => 'Immediate model fix; incident review; add CI guard.'],
                ],
                [
                    'id' => 'personio-negative-absence-days',
                    'priority' => 'medium',
                    'title' => ['de' => 'Negative oder null Abwesenheitstage', 'en' => 'Negative or zero absence days'],
                    'problem' => ['de' => 'days_count <= 0 verzerrt Absence-Days-Summen.', 'en' => 'days_count <= 0 distorts absence-days totals.'],
                    'prevent' => ['de' => 'Validierung bei Absence-Antrag: end_date >= start_date.', 'en' => 'Validation at absence request: end_date >= start_date.'],
                    'staffNeedToKnow' => ['de' => 'HR-Ops: Datumsfehler bei Antragsstellung korrigieren.', 'en' => 'HR ops: correct date errors at request time.'],
                    'checks' => ['de' => 'days_count <= 0', 'en' => 'days_count <= 0'],
                    'fixInSource' => ['de' => 'Absence-Antrag in Personio korrigieren.', 'en' => 'Correct the absence request in Personio.'],
                    'fixInWarehouse' => ['de' => 'Flag invalid_absence; exclude from absence-days KPI.', 'en' => 'Flag invalid_absence; exclude from absence-days KPI.'],
                ],
                [
                    'id' => 'personio-duplicate-employee-number',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte employee_number im Extract', 'en' => 'Duplicate employee_number in extract'],
                    'problem' => ['de' => 'Doppelte employee_number verzerren Headcount und Turnover.', 'en' => 'Duplicate employee_number distorts headcount and turnover.'],
                    'prevent' => ['de' => 'Idempotenter API-Sync; Pagination-Overlap prüfen.', 'en' => 'Idempotent API sync; check pagination overlap.'],
                    'staffNeedToKnow' => ['de' => 'Data: employee_number ist der stabile Business-Key.', 'en' => 'Data: employee_number is the stable business key.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY employee_number HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY employee_number HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-sync; API-Pagination untersuchen.', 'en' => 'Re-sync; investigate API pagination.'],
                    'fixInWarehouse' => ['de' => 'Dedup by employee_number; keep latest _loaded_at.', 'en' => 'Dedup by employee_number; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'personio-employee-dup',
                    'entity' => 'Employee',
                    'title' => ['de' => 'Employee-Duplikate / Rehire', 'en' => 'Employee duplicates / rehire'],
                    'matchKeys' => ['employee_id', 'employee_number', 'tax_id (hashed)', 'email'],
                    'preventInSource' => ['de' => 'Personio als Source of Truth; Rehire statt Neuanlage.', 'en' => 'Personio as source of truth; rehire instead of recreating.'],
                    'resolveInWarehouse' => ['de' => 'Golden employee_id; employee_number SCD2.', 'en' => 'Golden employee_id; employee_number SCD2.'],
                    'survivorship' => ['de' => 'Aktiver Employee mit neuestem hire_date gewinnt.', 'en' => 'Active employee with the most recent hire_date wins.'],
                ],
                [
                    'id' => 'personio-department-taxonomy',
                    'entity' => 'Position / Department',
                    'title' => ['de' => 'Department-Taxonomie-Drift', 'en' => 'Department taxonomy drift'],
                    'matchKeys' => ['department id', 'department name'],
                    'preventInSource' => ['de' => 'Zentrale Org-Struktur-Pflege statt Freitext-Departments.', 'en' => 'Central org-structure maintenance instead of free-text departments.'],
                    'resolveInWarehouse' => ['de' => 'Canonical department id; SCD2 department name.', 'en' => 'Canonical department id; SCD2 department name.'],
                    'survivorship' => ['de' => 'Aktueller Department-Name gewinnt; historische Namen als Aliase.', 'en' => 'Current department name wins; historical names kept as aliases.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'personio-onboarding-required-fields',
                    'area' => ['de' => 'Personio → Settings → Employee attributes', 'en' => 'Personio → Settings → Employee attributes'],
                    'setting' => ['de' => 'Department/Position als Pflichtfeld im Onboarding', 'en' => 'Department/position as a required onboarding field'],
                    'why' => ['de' => 'Verhindert Employee-ohne-Department DQ-Failures.', 'en' => 'Prevents employee-without-department DQ failures.'],
                    'how' => ['de' => 'Required attribute configuration; onboarding checklist.', 'en' => 'Required attribute configuration; onboarding checklist.'],
                ],
                [
                    'id' => 'personio-api-scopes',
                    'area' => ['de' => 'Personio → Settings → API credentials', 'en' => 'Personio → Settings → API credentials'],
                    'setting' => ['de' => 'API-Scopes ohne Compensation-Read für Analytics-Integration', 'en' => 'API scopes without compensation read for the analytics integration'],
                    'why' => ['de' => 'Technische Kontrolle gegen versehentliche Gehalts-Landung.', 'en' => 'Technical control against accidentally landing salary data.'],
                    'how' => ['de' => 'Separate API credential für Analytics ohne Compensation-Scope.', 'en' => 'Separate API credential for analytics without a compensation scope.'],
                ],
                [
                    'id' => 'personio-absence-approval',
                    'area' => ['de' => 'Personio → Time off → Approval workflow', 'en' => 'Personio → Time off → Approval workflow'],
                    'setting' => ['de' => 'Approval-Pflicht und Datumsvalidierung für Absence-Anträge', 'en' => 'Mandatory approval and date validation for absence requests'],
                    'why' => ['de' => 'Verlässliche Absence-Days-KPIs ohne negative/invalide Werte.', 'en' => 'Reliable absence-days KPIs without negative/invalid values.'],
                    'how' => ['de' => 'Enforce end_date >= start_date; require manager approval.', 'en' => 'Enforce end_date >= start_date; require manager approval.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'personio-api-schema',
                    'kind' => ['de' => 'Personio API schema', 'en' => 'Personio API schema'],
                    'where' => ['de' => 'Personio Developer Hub → API reference (Employees, Absences, Attendances)', 'en' => 'Personio Developer Hub → API reference (Employees, Absences, Attendances)'],
                    'how' => ['de' => 'Employee-/Absence-Felder inventarisieren; Compensation-Endpoint separat behandeln.', 'en' => 'Inventory employee/absence fields; handle the compensation endpoint separately.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (employee_id, employee_number).', 'en' => 'Extract design, PII tags, join keys (employee_id, employee_number).'],
                    'watchouts' => ['de' => 'Custom Attributes können beliebige PII enthalten — Schema-Review vor Load.', 'en' => 'Custom attributes can contain arbitrary PII — schema review before load.'],
                ],
                [
                    'id' => 'personio-custom-attributes',
                    'kind' => ['de' => 'Custom attributes / HR data fields', 'en' => 'Custom attributes / HR data fields'],
                    'where' => ['de' => 'Personio → Settings → Employee attributes → Custom attributes', 'en' => 'Personio → Settings → Employee attributes → Custom attributes'],
                    'how' => ['de' => 'Attribut-Typen inventarisieren; jedes neue Attribut auf PII prüfen.', 'en' => 'Inventory attribute types; review every new attribute for PII.'],
                    'useFor' => ['de' => 'PII scan, extract allowlist.', 'en' => 'PII scan, extract allowlist.'],
                    'watchouts' => ['de' => 'Standardmäßig als PII behandeln bis gegenteilig geprüft.', 'en' => 'Treat as PII by default until proven otherwise.'],
                ],
                [
                    'id' => 'personio-absence-types',
                    'kind' => ['de' => 'Absence type configuration', 'en' => 'Absence type configuration'],
                    'where' => ['de' => 'Personio → Settings → Time off → Absence types', 'en' => 'Personio → Settings → Time off → Absence types'],
                    'how' => ['de' => 'Absence-Type-Katalog dokumentieren; Health-related Types kennzeichnen.', 'en' => 'Document the absence-type catalog; flag health-related types.'],
                    'useFor' => ['de' => 'Absence-Dimension, Sick-vs-Vacation-Reporting.', 'en' => 'Absence dimension, sick-vs-vacation reporting.'],
                    'watchouts' => ['de' => 'Diagnose-/Freitext-Notizen nie über absence_type hinaus laden.', 'en' => 'Never load diagnosis/free-text notes beyond absence_type.'],
                ],
                [
                    'id' => 'personio-compensation-schema',
                    'kind' => ['de' => 'Compensation schema', 'en' => 'Compensation schema'],
                    'where' => ['de' => 'Personio → Compensation module → Field reference', 'en' => 'Personio → Compensation module → Field reference'],
                    'how' => ['de' => 'Compensation-Felder als Referenz für Zugriffs-Policy dokumentieren, nicht für Standard-Extracts.', 'en' => 'Document compensation fields as a reference for the access policy, not for standard extracts.'],
                    'useFor' => ['de' => 'Access-Policy-Design, Band-/Aggregat-Definition.', 'en' => 'Access-policy design, band/aggregate definition.'],
                    'watchouts' => ['de' => 'Kein Standard-dbt-Modell darf amount direkt selektieren.', 'en' => 'No standard dbt model may select amount directly.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],
];
