<?php

/**
 * Wave 10 quality overlays — Workplace/Collab/Learning/Marketing source-native DQ, MDM, metadata guides.
 *
 * @return array<string, array<string, mixed>>
 */

return [
    'exchange' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'exchange-mailitem-no-mailbox',
                    'priority' => 'high',
                    'title' => ['de' => 'Mail Item Meta ohne Mailbox', 'en' => 'Mail item meta without mailbox'],
                    'problem' => ['de' => 'Message-Meta ohne mailbox_id bricht Mail-Volume-Joins und Reach-KPIs.', 'en' => 'Message meta without mailbox_id breaks mail-volume joins and reach KPIs.'],
                    'prevent' => ['de' => 'Graph extract: mailbox context immer mitschreiben.', 'en' => 'Graph extract: always persist mailbox context.'],
                    'staffNeedToKnow' => ['de' => 'Data: Message ohne Mailbox ist Extract-Fehler.', 'en' => 'Data: Message without mailbox is an extract error.'],
                    'checks' => ['de' => 'mail_item.mailbox_id IS NULL OR mailbox_id NOT IN dim_mailbox', 'en' => 'mail_item.mailbox_id IS NULL OR mailbox_id NOT IN dim_mailbox'],
                    'fixInSource' => ['de' => 'Re-extract with mailbox context; verify delegate/shared mailbox scope.', 'en' => 'Re-extract with mailbox context; verify delegate/shared mailbox scope.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown mailbox dim.', 'en' => 'Quarantine; Unknown mailbox dim.'],
                ],
                [
                    'id' => 'exchange-event-no-organizer',
                    'priority' => 'medium',
                    'title' => ['de' => 'Calendar Event ohne Organizer', 'en' => 'Calendar event without organizer'],
                    'problem' => ['de' => 'Events ohne organizer.emailAddress verzerren Meeting-Load-Analysen.', 'en' => 'Events without organizer.emailAddress distort meeting-load analysis.'],
                    'prevent' => ['de' => 'Graph events endpoint: organizer field required in select.', 'en' => 'Graph events endpoint: organizer field required in select.'],
                    'staffNeedToKnow' => ['de' => 'Data: Organizer-Feld nie aus dem Select entfernen.', 'en' => 'Data: Never drop organizer field from the select.'],
                    'checks' => ['de' => 'calendar_event.organizer_id IS NULL', 'en' => 'calendar_event.organizer_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-fetch event; check delegated calendar permissions.', 'en' => 'Re-fetch event; check delegated calendar permissions.'],
                    'fixInWarehouse' => ['de' => 'Flag missing_organizer; exclude from per-organizer KPIs.', 'en' => 'Flag missing_organizer; exclude from per-organizer KPIs.'],
                ],
                [
                    'id' => 'exchange-mailbox-no-directory-match',
                    'priority' => 'high',
                    'title' => ['de' => 'Mailbox ohne Directory-Match', 'en' => 'Mailbox without directory match'],
                    'problem' => ['de' => 'Mailboxes ohne Entra User Match brechen Department/Org-Dimension-Joins.', 'en' => 'Mailboxes without an Entra user match break department/org dimension joins.'],
                    'prevent' => ['de' => 'Directory sync vor Mailbox extract; shared/room mailboxes separat mappen.', 'en' => 'Directory sync before mailbox extract; map shared/room mailboxes separately.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Mailbox-Provisioning und Directory-Sync synchron halten.', 'en' => 'Admins: Keep mailbox provisioning and directory sync in step.'],
                    'checks' => ['de' => "mailbox.recipientTypeDetails = 'UserMailbox' AND mailbox.id NOT IN dim_entra_user", 'en' => "mailbox.recipientTypeDetails = 'UserMailbox' AND mailbox.id NOT IN dim_entra_user"],
                    'fixInSource' => ['de' => 'Re-sync directory; investigate provisioning delay.', 'en' => 'Re-sync directory; investigate provisioning delay.'],
                    'fixInWarehouse' => ['de' => 'Unknown-department bucket; exclude from org rollups.', 'en' => 'Unknown-department bucket; exclude from org rollups.'],
                ],
                [
                    'id' => 'exchange-mail-flow-rule-orphan',
                    'priority' => 'medium',
                    'title' => ['de' => 'Mail Flow Rule ohne Match-Statistik', 'en' => 'Mail flow rule without match statistics'],
                    'problem' => ['de' => 'Rules ohne Stats machen Compliance-Coverage-KPIs unmöglich.', 'en' => 'Rules without stats make compliance coverage KPIs impossible.'],
                    'prevent' => ['de' => 'Message trace / rule reporting regelmäßig extrahieren.', 'en' => 'Extract message trace / rule reporting regularly.'],
                    'staffNeedToKnow' => ['de' => 'Compliance: Rule-Reporting-Feed nicht abschalten.', 'en' => 'Compliance: Do not disable rule reporting feed.'],
                    'checks' => ['de' => 'mail_flow_rule.id NOT IN mail_flow_rule_stats', 'en' => 'mail_flow_rule.id NOT IN mail_flow_rule_stats'],
                    'fixInSource' => ['de' => 'Verify rule reporting export schedule.', 'en' => 'Verify rule reporting export schedule.'],
                    'fixInWarehouse' => ['de' => 'Flag stats_missing; exclude from hit-rate KPIs.', 'en' => 'Flag stats_missing; exclude from hit-rate KPIs.'],
                ],
                [
                    'id' => 'exchange-device-stale-sync',
                    'priority' => 'medium',
                    'title' => ['de' => 'Mobile Device ohne aktuellen Sync', 'en' => 'Mobile device without recent sync'],
                    'problem' => ['de' => 'Geräte ohne Sync seit langem sind Compliance-Risiko und verzerren Device-Coverage.', 'en' => 'Devices without a sync for a long time are a compliance risk and distort device coverage.'],
                    'prevent' => ['de' => 'Conditional Access + Intune compliance policies für Mobile Devices.', 'en' => 'Conditional access + Intune compliance policies for mobile devices.'],
                    'staffNeedToKnow' => ['de' => 'Security: Stale Devices reviewen und ggf. wipen/blocken.', 'en' => 'Security: Review stale devices and wipe/block if needed.'],
                    'checks' => ['de' => "lastSyncAttemptTime < CURRENT_DATE - 90 AND deviceAccessState = 'Allowed'", 'en' => "lastSyncAttemptTime < CURRENT_DATE - 90 AND deviceAccessState = 'Allowed'"],
                    'fixInSource' => ['de' => 'Block/quarantine stale device; contact owner.', 'en' => 'Block/quarantine stale device; contact owner.'],
                    'fixInWarehouse' => ['de' => 'Flag stale_device; exclude from active device KPIs.', 'en' => 'Flag stale_device; exclude from active device KPIs.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'exchange-mailbox-dup',
                    'entity' => 'Mailbox',
                    'title' => ['de' => 'Mailbox-Duplikate / Alias Drift', 'en' => 'Mailbox duplicates / alias drift'],
                    'matchKeys' => ['id', 'primarySmtpAddress', 'aliasAddresses'],
                    'preventInSource' => ['de' => 'Directory as source of truth; controlled alias changes.', 'en' => 'Directory as source of truth; controlled alias changes.'],
                    'resolveInWarehouse' => ['de' => 'Golden mailbox id; SCD2 primarySmtpAddress.', 'en' => 'Golden mailbox id; SCD2 primarySmtpAddress.'],
                    'survivorship' => ['de' => 'Aktive Mailbox mit neuester Mail-Aktivität gewinnt.', 'en' => 'Active mailbox with latest mail activity wins.'],
                ],
                [
                    'id' => 'exchange-shared-mailbox-owner-map',
                    'entity' => 'Mailbox / Group',
                    'title' => ['de' => 'Shared Mailbox Owner Mapping Drift', 'en' => 'Shared mailbox owner mapping drift'],
                    'matchKeys' => ['mailbox id', 'delegate user id', 'distribution group id'],
                    'preventInSource' => ['de' => 'Owner-Register für Shared Mailboxes pflegen; Delegation-Changes tracken.', 'en' => 'Maintain owner register for shared mailboxes; track delegation changes.'],
                    'resolveInWarehouse' => ['de' => 'Canonical mailbox id → owner SCD2 map.', 'en' => 'Canonical mailbox id → owner SCD2 map.'],
                    'survivorship' => ['de' => 'Aktuellster Delegation-Eintrag gewinnt.', 'en' => 'Most recent delegation entry wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'exchange-retention-policies',
                    'area' => ['de' => 'Compliance → Retention policies', 'en' => 'Compliance → Retention policies'],
                    'setting' => ['de' => 'Retention Tags konsequent auf Mailboxen anwenden', 'en' => 'Apply retention tags consistently across mailboxes'],
                    'why' => ['de' => 'Retention-Coverage wird messbar ohne Mail-Bodies zu speichern.', 'en' => 'Retention coverage becomes measurable without storing mail bodies.'],
                    'how' => ['de' => 'Default retention policy assignment; audit unassigned mailboxes.', 'en' => 'Default retention policy assignment; audit unassigned mailboxes.'],
                ],
                [
                    'id' => 'exchange-mail-flow-rules-review',
                    'area' => ['de' => 'Mail flow → Rules', 'en' => 'Mail flow → Rules'],
                    'setting' => ['de' => 'Regelmäßige Review von Transport/DLP Rules', 'en' => 'Regular review of transport/DLP rules'],
                    'why' => ['de' => 'Verhindert tote Rules und macht Compliance-Coverage-KPIs verlässlich.', 'en' => 'Prevents dead rules and keeps compliance coverage KPIs reliable.'],
                    'how' => ['de' => 'Quarterly rule audit; disable zero-hit rules after review.', 'en' => 'Quarterly rule audit; disable zero-hit rules after review.'],
                ],
                [
                    'id' => 'exchange-device-access-policy',
                    'area' => ['de' => 'Mobile → Device access policies', 'en' => 'Mobile → Device access policies'],
                    'setting' => ['de' => 'ActiveSync/Intune Device Compliance Policies durchsetzen', 'en' => 'Enforce ActiveSync/Intune device compliance policies'],
                    'why' => ['de' => 'Stale/Non-compliant Devices werden sichtbar und blockierbar.', 'en' => 'Stale/non-compliant devices become visible and blockable.'],
                    'how' => ['de' => 'Conditional Access + quarantine rules; periodic stale-device sweep.', 'en' => 'Conditional access + quarantine rules; periodic stale-device sweep.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'exchange-graph-mail-metadata',
                    'kind' => ['de' => 'Graph mail / calendar $metadata', 'en' => 'Graph mail / calendar $metadata'],
                    'where' => ['de' => 'Microsoft Graph → $metadata; messages, events, mailFolders', 'en' => 'Microsoft Graph → $metadata; messages, events, mailFolders'],
                    'how' => ['de' => 'Header-Felder inventarisieren; Body/bodyPreview vom Select ausschließen.', 'en' => 'Inventory header fields; exclude body/bodyPreview from the select.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (mailbox id, message id).', 'en' => 'Extract design, PII tags, join keys (mailbox id, message id).'],
                    'watchouts' => ['de' => 'attachments-Feld nie mit $expand laden.', 'en' => 'Never load the attachments field with $expand.'],
                ],
                [
                    'id' => 'exchange-transport-rules-meta',
                    'kind' => ['de' => 'Transport / mail flow rules', 'en' => 'Transport / mail flow rules'],
                    'where' => ['de' => 'Exchange Admin Center → Mail flow → Rules; EXO PowerShell Get-TransportRule', 'en' => 'Exchange Admin Center → Mail flow → Rules; EXO PowerShell Get-TransportRule'],
                    'how' => ['de' => 'Rule Name, Priority, Conditions dokumentieren — keine Content-Matches speichern.', 'en' => 'Document rule name, priority, conditions — do not store content matches.'],
                    'useFor' => ['de' => 'Compliance dims, hit-rate KPIs, DLP coverage.', 'en' => 'Compliance dims, hit-rate KPIs, DLP coverage.'],
                    'watchouts' => ['de' => 'Rule Conditions können Keyword-Listen enthalten — sensibel behandeln.', 'en' => 'Rule conditions may contain keyword lists — treat sensitively.'],
                ],
                [
                    'id' => 'exchange-retention-tags-meta',
                    'kind' => ['de' => 'Retention tags / policies', 'en' => 'Retention tags / policies'],
                    'where' => ['de' => 'Purview Compliance → Retention; EXO Get-RetentionPolicyTag', 'en' => 'Purview Compliance → Retention; EXO Get-RetentionPolicyTag'],
                    'how' => ['de' => 'Tag-Namen, Actions und Policy-Zuordnungen exportieren.', 'en' => 'Export tag names, actions and policy assignments.'],
                    'useFor' => ['de' => 'Retention coverage dims, compliance reporting.', 'en' => 'Retention coverage dims, compliance reporting.'],
                    'watchouts' => ['de' => 'Retention Actions ändern sich — SCD2 empfohlen.', 'en' => 'Retention actions change — SCD2 recommended.'],
                ],
                [
                    'id' => 'exchange-mobile-device-schema',
                    'kind' => ['de' => 'Mobile device / ActiveSync schema', 'en' => 'Mobile device / ActiveSync schema'],
                    'where' => ['de' => 'EXO Get-MobileDevice / Get-MobileDeviceStatistics', 'en' => 'EXO Get-MobileDevice / Get-MobileDeviceStatistics'],
                    'how' => ['de' => 'Device Type, Sync-Status und Access-State inventarisieren.', 'en' => 'Inventory device type, sync status and access state.'],
                    'useFor' => ['de' => 'Device coverage dims, stale-device DQ.', 'en' => 'Device coverage dims, stale-device DQ.'],
                    'watchouts' => ['de' => 'DeviceUserAgent kann Re-Identifikationsrisiko bergen — restriktiv halten.', 'en' => 'DeviceUserAgent can carry re-identification risk — keep restricted.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'monday' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'monday-item-no-board',
                    'priority' => 'high',
                    'title' => ['de' => 'Item ohne Board', 'en' => 'Item without board'],
                    'problem' => ['de' => 'Items ohne board_id brechen Delivery-Joins und Board-Level-KPIs.', 'en' => 'Items without board_id break delivery joins and board-level KPIs.'],
                    'prevent' => ['de' => 'GraphQL extract: board.id immer mitladen; moved/duplicated items tracken.', 'en' => 'GraphQL extract: always load board.id; track moved/duplicated items.'],
                    'staffNeedToKnow' => ['de' => 'Data: Item ohne Board ist Extract-Fehler.', 'en' => 'Data: Item without board is an extract error.'],
                    'checks' => ['de' => 'item.board_id IS NULL OR board_id NOT IN dim_board', 'en' => 'item.board_id IS NULL OR board_id NOT IN dim_board'],
                    'fixInSource' => ['de' => 'Re-extract; check board archive/delete tombstones.', 'en' => 'Re-extract; check board archive/delete tombstones.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown board dim.', 'en' => 'Quarantine; Unknown board dim.'],
                ],
                [
                    'id' => 'monday-status-label-unmapped',
                    'priority' => 'high',
                    'title' => ['de' => 'Status-Label ohne Mapping', 'en' => 'Status label without mapping'],
                    'problem' => ['de' => 'Board-spezifische Status-Labels ohne Mapping verzerren Cross-Board Completion-KPIs.', 'en' => 'Board-specific status labels without mapping distort cross-board completion KPIs.'],
                    'prevent' => ['de' => 'Status-Mapping-Tabelle je Board pflegen; neue Labels bei Board-Create reviewen.', 'en' => 'Maintain a status-mapping table per board; review new labels at board creation.'],
                    'staffNeedToKnow' => ['de' => 'Board Owners: Neue Status-Labels im Mapping registrieren.', 'en' => 'Board owners: Register new status labels in the mapping.'],
                    'checks' => ['de' => 'column_value.type = \'status\' AND column_value.text NOT IN status_label_map', 'en' => 'column_value.type = \'status\' AND column_value.text NOT IN status_label_map'],
                    'fixInSource' => ['de' => 'Standardize labels or extend mapping table.', 'en' => 'Standardize labels or extend mapping table.'],
                    'fixInWarehouse' => ['de' => 'Flag unmapped_status; exclude from done-rate rollups.', 'en' => 'Flag unmapped_status; exclude from done-rate rollups.'],
                ],
                [
                    'id' => 'monday-update-no-item',
                    'priority' => 'medium',
                    'title' => ['de' => 'Update ohne Item', 'en' => 'Update without item'],
                    'problem' => ['de' => 'Updates ohne item_id brechen Engagement-Joins.', 'en' => 'Updates without item_id break engagement joins.'],
                    'prevent' => ['de' => 'GraphQL updates query: item_id immer mitladen.', 'en' => 'GraphQL updates query: always load item_id.'],
                    'staffNeedToKnow' => ['de' => 'Data: Update ohne Item ist Extract-Artefakt.', 'en' => 'Data: Update without item is an extract artifact.'],
                    'checks' => ['de' => 'update.item_id IS NULL', 'en' => 'update.item_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-extract updates with item context.', 'en' => 'Re-extract updates with item context.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from item-level engagement KPIs.', 'en' => 'Quarantine; exclude from item-level engagement KPIs.'],
                ],
                [
                    'id' => 'monday-deactivated-user-owns-items',
                    'priority' => 'medium',
                    'title' => ['de' => 'Deaktivierter User besitzt noch Items', 'en' => 'Deactivated user still owns items'],
                    'problem' => ['de' => 'Deaktivierte Owner verzerren Ownership-Coverage und Reassignment-Bedarf.', 'en' => 'Deactivated owners distort ownership coverage and reassignment needs.'],
                    'prevent' => ['de' => 'Offboarding-Workflow: Item-Reassignment vor User-Deaktivierung.', 'en' => 'Offboarding workflow: reassign items before user deactivation.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Deactivate ≠ Reassignment.', 'en' => 'Admins: Deactivate ≠ reassignment.'],
                    'checks' => ['de' => 'user.enabled = FALSE AND owned_item_count > 0', 'en' => 'user.enabled = FALSE AND owned_item_count > 0'],
                    'fixInSource' => ['de' => 'Reassign items; run offboarding checklist.', 'en' => 'Reassign items; run offboarding checklist.'],
                    'fixInWarehouse' => ['de' => 'Flag stale_ownership; exclude from active-owner KPIs.', 'en' => 'Flag stale_ownership; exclude from active-owner KPIs.'],
                ],
                [
                    'id' => 'monday-duplicate-item-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Item IDs im Extract', 'en' => 'Duplicate item ids in extract'],
                    'problem' => ['de' => 'Doppelte item_id verzerren Created/Completed-Counts.', 'en' => 'Duplicate item_id distort created/completed counts.'],
                    'prevent' => ['de' => 'Idempotent load key; pagination cursor overlap prüfen.', 'en' => 'Idempotent load key; check pagination cursor overlap.'],
                    'staffNeedToKnow' => ['de' => 'Data: item_id global eindeutig halten.', 'en' => 'Data: Keep item_id globally unique.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY item_id HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY item_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate GraphQL pagination.', 'en' => 'Re-extract; investigate GraphQL pagination.'],
                    'fixInWarehouse' => ['de' => 'Dedup by item_id; keep latest _loaded_at.', 'en' => 'Dedup by item_id; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'monday-user-dup',
                    'entity' => 'User',
                    'title' => ['de' => 'User-Duplikate / Email Change', 'en' => 'User duplicates / email change'],
                    'matchKeys' => ['id', 'email', 'account role'],
                    'preventInSource' => ['de' => 'Account as source of truth; track email changes via admin log.', 'en' => 'Account as source of truth; track email changes via admin log.'],
                    'resolveInWarehouse' => ['de' => 'Golden user id; email-hash SCD2.', 'en' => 'Golden user id; email-hash SCD2.'],
                    'survivorship' => ['de' => 'Enabled User mit neuester Activity gewinnt.', 'en' => 'Enabled user with latest activity wins.'],
                ],
                [
                    'id' => 'monday-status-taxonomy',
                    'entity' => 'Status label',
                    'title' => ['de' => 'Status Taxonomy Drift über Boards', 'en' => 'Status taxonomy drift across boards'],
                    'matchKeys' => ['board id', 'column id', 'status label text'],
                    'preventInSource' => ['de' => 'Board Templates mit Standard-Status-Set; Label-Changes reviewen.', 'en' => 'Board templates with a standard status set; review label changes.'],
                    'resolveInWarehouse' => ['de' => 'Canonical status bucket (Todo/Doing/Done) → Label-Mapping.', 'en' => 'Canonical status bucket (Todo/Doing/Done) → label mapping.'],
                    'survivorship' => ['de' => 'Aktuellstes Mapping je Board gewinnt.', 'en' => 'Latest mapping per board wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'monday-board-templates',
                    'area' => ['de' => 'Boards → Templates', 'en' => 'Boards → Templates'],
                    'setting' => ['de' => 'Standard-Board-Templates mit einheitlichem Status-Set', 'en' => 'Standard board templates with a unified status set'],
                    'why' => ['de' => 'Reduziert Status-Taxonomy-Drift und Mapping-Aufwand.', 'en' => 'Reduces status taxonomy drift and mapping effort.'],
                    'how' => ['de' => 'Publish approved templates; restrict ad-hoc status label creation.', 'en' => 'Publish approved templates; restrict ad-hoc status label creation.'],
                ],
                [
                    'id' => 'monday-automation-governance',
                    'area' => ['de' => 'Automations → Recipes', 'en' => 'Automations → Recipes'],
                    'setting' => ['de' => 'Automation-Recipes reviewen; keine Secrets in Webhook-Configs', 'en' => 'Review automation recipes; no secrets in webhook configs'],
                    'why' => ['de' => 'Verhindert Secret-Leaks und tote Automations.', 'en' => 'Prevents secret leaks and dead automations.'],
                    'how' => ['de' => 'Periodic automation audit; secrets in vault, not board columns.', 'en' => 'Periodic automation audit; secrets in vault, not board columns.'],
                ],
                [
                    'id' => 'monday-user-offboarding',
                    'area' => ['de' => 'Admin → User management', 'en' => 'Admin → User management'],
                    'setting' => ['de' => 'Offboarding-Checklist mit Item-Reassignment vor Deaktivierung', 'en' => 'Offboarding checklist with item reassignment before deactivation'],
                    'why' => ['de' => 'Ownership-Coverage bleibt aktuell und Reassignment-Bedarf sichtbar.', 'en' => 'Ownership coverage stays current and reassignment needs stay visible.'],
                    'how' => ['de' => 'Reassign owned items; disable account; audit orphaned ownership.', 'en' => 'Reassign owned items; disable account; audit orphaned ownership.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'monday-graphql-schema',
                    'kind' => ['de' => 'GraphQL schema', 'en' => 'GraphQL schema'],
                    'where' => ['de' => 'monday.com Developers → API Reference / GraphQL schema explorer', 'en' => 'monday.com Developers → API reference / GraphQL schema explorer'],
                    'how' => ['de' => 'Query-Felder inventarisieren; Select-Allowlist für Extract.', 'en' => 'Inventory query fields; select allowlist for extract.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (board, item, user).', 'en' => 'Extract design, PII tags, join keys (board, item, user).'],
                    'watchouts' => ['de' => 'assets/files Felder nie mit Binary-Content selektieren.', 'en' => 'Never select assets/files fields with binary content.'],
                ],
                [
                    'id' => 'monday-column-types',
                    'kind' => ['de' => 'Column types', 'en' => 'Column types'],
                    'where' => ['de' => 'monday.com Developers → Column types reference', 'en' => 'monday.com Developers → Column types reference'],
                    'how' => ['de' => 'Column-Type-Katalog gegen Board-Columns abgleichen; PII-Typen taggen.', 'en' => 'Match the column-type catalog against board columns; tag PII types.'],
                    'useFor' => ['de' => 'Extract allowlist, PII scan, dimension mapping.', 'en' => 'Extract allowlist, PII scan, dimension mapping.'],
                    'watchouts' => ['de' => 'Person-/Email-Columns als Workforce-PII behandeln.', 'en' => 'Treat person/email columns as workforce PII.'],
                ],
                [
                    'id' => 'monday-webhooks',
                    'kind' => ['de' => 'Webhooks / integrations', 'en' => 'Webhooks / integrations'],
                    'where' => ['de' => 'monday.com Developers → Webhooks; Admin → Integrations', 'en' => 'monday.com Developers → Webhooks; Admin → Integrations'],
                    'how' => ['de' => 'Event-Typen und Payload-Schema dokumentieren — Secrets nie speichern.', 'en' => 'Document event types and payload schema — never store secrets.'],
                    'useFor' => ['de' => 'Near-real-time item change facts, integration coverage.', 'en' => 'Near-real-time item change facts, integration coverage.'],
                    'watchouts' => ['de' => 'Webhook URLs können Tokens enthalten — redigieren.', 'en' => 'Webhook URLs may contain tokens — redact.'],
                ],
                [
                    'id' => 'monday-activity-log-schema',
                    'kind' => ['de' => 'Activity log schema', 'en' => 'Activity log schema'],
                    'where' => ['de' => 'monday.com Developers → Activity logs API', 'en' => 'monday.com Developers → Activity logs API'],
                    'how' => ['de' => 'Event-Type-Allowlist definieren; verbose payloads meiden.', 'en' => 'Define an event-type allowlist; avoid verbose payloads.'],
                    'useFor' => ['de' => 'Governance facts, change tracking, board activity KPIs.', 'en' => 'Governance facts, change tracking, board activity KPIs.'],
                    'watchouts' => ['de' => 'Activity Payloads können Update-Text enthalten — Meta only.', 'en' => 'Activity payloads may contain update text — meta only.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'moodle' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'moodle-enrollment-no-course',
                    'priority' => 'high',
                    'title' => ['de' => 'Enrollment ohne Course', 'en' => 'Enrollment without course'],
                    'problem' => ['de' => 'Enrollments ohne course_id brechen Completion- und Grade-Joins.', 'en' => 'Enrollments without course_id break completion and grade joins.'],
                    'prevent' => ['de' => 'Web Services extract: course context immer mitladen; deleted courses tombstonen.', 'en' => 'Web services extract: always load course context; tombstone deleted courses.'],
                    'staffNeedToKnow' => ['de' => 'Data: Enrollment ohne Course ist Extract-Fehler.', 'en' => 'Data: Enrollment without course is an extract error.'],
                    'checks' => ['de' => 'enrollment.course_id IS NULL OR course_id NOT IN dim_course', 'en' => 'enrollment.course_id IS NULL OR course_id NOT IN dim_course'],
                    'fixInSource' => ['de' => 'Re-extract with course context; repair deleted course tombstones.', 'en' => 'Re-extract with course context; repair deleted course tombstones.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown course dim.', 'en' => 'Quarantine; Unknown course dim.'],
                ],
                [
                    'id' => 'moodle-grade-exceeds-max',
                    'priority' => 'high',
                    'title' => ['de' => 'Grade über grademax', 'en' => 'Grade exceeding grademax'],
                    'problem' => ['de' => 'finalgrade > grademax verzerrt Average-Grade- und Pass-Rate-KPIs.', 'en' => 'finalgrade > grademax distorts average-grade and pass-rate KPIs.'],
                    'prevent' => ['de' => 'Gradebook validation rules; extra credit klar als separates Item führen.', 'en' => 'Gradebook validation rules; run extra credit as a clearly separate item.'],
                    'staffNeedToKnow' => ['de' => 'Instructors: Extra Credit nicht in Standard-Grade-Item mischen.', 'en' => 'Instructors: Do not mix extra credit into the standard grade item.'],
                    'checks' => ['de' => 'grade_grade.finalgrade > grade_item.grademax', 'en' => 'grade_grade.finalgrade > grade_item.grademax'],
                    'fixInSource' => ['de' => 'Review gradebook setup; separate extra-credit item.', 'en' => 'Review gradebook setup; separate extra-credit item.'],
                    'fixInWarehouse' => ['de' => 'Flag grade_anomaly; exclude from average until reviewed.', 'en' => 'Flag grade_anomaly; exclude from average until reviewed.'],
                ],
                [
                    'id' => 'moodle-suspended-still-enrolled-active',
                    'priority' => 'medium',
                    'title' => ['de' => 'Suspended User mit Status active in Enrollment', 'en' => 'Suspended user with active enrollment status'],
                    'problem' => ['de' => 'Widerspruch zwischen User-Suspension und aktivem Enrollment verzerrt Active-Learner-KPI.', 'en' => 'A mismatch between user suspension and an active enrollment distorts the active-learner KPI.'],
                    'prevent' => ['de' => 'Lifecycle sync zwischen User-Suspension und Enrollment-Status.', 'en' => 'Lifecycle sync between user suspension and enrollment status.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Suspend User löst nicht automatisch Enrollment-Suspend aus.', 'en' => 'Admins: Suspending a user does not automatically suspend enrollments.'],
                    'checks' => ['de' => "user.suspended = TRUE AND enrollment.status = 'active'", 'en' => "user.suspended = TRUE AND enrollment.status = 'active'"],
                    'fixInSource' => ['de' => 'Sync enrollment status on user suspension.', 'en' => 'Sync enrollment status on user suspension.'],
                    'fixInWarehouse' => ['de' => 'Flag inconsistent_enrollment; exclude from active learner count.', 'en' => 'Flag inconsistent_enrollment; exclude from active learner count.'],
                ],
                [
                    'id' => 'moodle-quiz-attempt-no-user',
                    'priority' => 'medium',
                    'title' => ['de' => 'Quiz Attempt ohne User', 'en' => 'Quiz attempt without user'],
                    'problem' => ['de' => 'Attempts ohne resolvable user_id brechen Pass-Rate- und Cohort-Joins.', 'en' => 'Attempts without a resolvable user_id break pass-rate and cohort joins.'],
                    'prevent' => ['de' => 'Web Services extract: userid Pflichtfeld im Select.', 'en' => 'Web services extract: userid required in the select.'],
                    'staffNeedToKnow' => ['de' => 'Data: Attempt ohne User ist Extract-Artefakt.', 'en' => 'Data: Attempt without user is an extract artifact.'],
                    'checks' => ['de' => 'quiz_attempt.user_id IS NULL OR user_id NOT IN dim_user', 'en' => 'quiz_attempt.user_id IS NULL OR user_id NOT IN dim_user'],
                    'fixInSource' => ['de' => 'Re-extract; check deleted user tombstones.', 'en' => 'Re-extract; check deleted user tombstones.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from per-user pass-rate KPIs.', 'en' => 'Quarantine; exclude from per-user pass-rate KPIs.'],
                ],
                [
                    'id' => 'moodle-duplicate-enrollment',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Enrollment (user, course, method)', 'en' => 'Duplicate enrollment (user, course, method)'],
                    'problem' => ['de' => 'Doppelte Enrollments über mehrere enrol-Methoden verzerren Enrollment-Counts.', 'en' => 'Duplicate enrollments via multiple enrol methods distort enrollment counts.'],
                    'prevent' => ['de' => 'Enrollment-Method-Governance; Manual + Cohort nicht doppelt anwenden.', 'en' => 'Enrollment-method governance; do not apply manual + cohort redundantly.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Enrollment-Methode je User/Course dokumentieren.', 'en' => 'Admins: Document the enrollment method per user/course.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY user_id, course_id HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY user_id, course_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Consolidate to single enrol method; unenrol duplicates.', 'en' => 'Consolidate to a single enrol method; unenrol duplicates.'],
                    'fixInWarehouse' => ['de' => 'Dedup by user_id+course_id; prefer earliest enrollment date.', 'en' => 'Dedup by user_id+course_id; prefer earliest enrollment date.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'moodle-user-dup',
                    'entity' => 'User',
                    'title' => ['de' => 'User-Duplikate / Re-enrollment', 'en' => 'User duplicates / re-enrollment'],
                    'matchKeys' => ['id', 'email', 'idnumber', 'username'],
                    'preventInSource' => ['de' => 'SIS/HR feed as source of truth; suspend instead of recreate account.', 'en' => 'SIS/HR feed as source of truth; suspend instead of recreating the account.'],
                    'resolveInWarehouse' => ['de' => 'Golden user id; idnumber/email-hash merge map.', 'en' => 'Golden user id; idnumber/email-hash merge map.'],
                    'survivorship' => ['de' => 'Aktiver User mit neuester Enrollment-Aktivität gewinnt.', 'en' => 'Active user with latest enrollment activity wins.'],
                ],
                [
                    'id' => 'moodle-course-category-map',
                    'entity' => 'Course category',
                    'title' => ['de' => 'Course Category Hierarchy Drift', 'en' => 'Course category hierarchy drift'],
                    'matchKeys' => ['category id', 'category path', 'parent category id'],
                    'preventInSource' => ['de' => 'Controlled category moves; document faculty/program mapping.', 'en' => 'Controlled category moves; document faculty/program mapping.'],
                    'resolveInWarehouse' => ['de' => 'Canonical category id; SCD2 category path.', 'en' => 'Canonical category id; SCD2 category path.'],
                    'survivorship' => ['de' => 'Aktueller Category-Pfad gewinnt; historische Pfade als aliases.', 'en' => 'Current category path wins; historical paths as aliases.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'moodle-completion-tracking',
                    'area' => ['de' => 'Course administration → Completion tracking', 'en' => 'Course administration → Completion tracking'],
                    'setting' => ['de' => 'Completion Tracking konsequent für alle Kurse aktivieren', 'en' => 'Consistently enable completion tracking for all courses'],
                    'why' => ['de' => 'Ohne Completion Tracking bleibt course-completions Measure leer.', 'en' => 'Without completion tracking the course-completions measure stays empty.'],
                    'how' => ['de' => 'Site-wide default; course template mit Activity Completion vorkonfiguriert.', 'en' => 'Site-wide default; course template pre-configured with activity completion.'],
                ],
                [
                    'id' => 'moodle-gradebook-validation',
                    'area' => ['de' => 'Grades → Gradebook setup', 'en' => 'Grades → Gradebook setup'],
                    'setting' => ['de' => 'Grade-Range-Validation und Extra-Credit-Konventionen', 'en' => 'Grade-range validation and extra-credit conventions'],
                    'why' => ['de' => 'Verhindert Grade-Anomalien und macht Average-Grade-KPI verlässlich.', 'en' => 'Prevents grade anomalies and keeps the average-grade KPI reliable.'],
                    'how' => ['de' => 'Enforce grademax bounds; separate extra-credit grade items.', 'en' => 'Enforce grademax bounds; use separate extra-credit grade items.'],
                ],
                [
                    'id' => 'moodle-privacy-data-registry',
                    'area' => ['de' => 'Privacy → Data registry', 'en' => 'Privacy → Data registry'],
                    'setting' => ['de' => 'Moodle Privacy API Data Registry für Bildungsdaten pflegen', 'en' => 'Maintain the Moodle Privacy API data registry for educational records'],
                    'why' => ['de' => 'Grundlage für Retention und DSAR-Prozesse rund um Grades/Enrollments.', 'en' => 'Foundation for retention and DSAR processes around grades/enrollments.'],
                    'how' => ['de' => 'Review plugin privacy providers; document retention periods.', 'en' => 'Review plugin privacy providers; document retention periods.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'moodle-web-services-schema',
                    'kind' => ['de' => 'Web services API schema', 'en' => 'Web services API schema'],
                    'where' => ['de' => 'Site administration → Server → Web services; core_course/core_enrol/core_grades functions', 'en' => 'Site administration → Server → Web services; core_course/core_enrol/core_grades functions'],
                    'how' => ['de' => 'Function-Parameter und Response-Felder inventarisieren; PII taggen.', 'en' => 'Inventory function parameters and response fields; tag PII.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (user, course, enrollment).', 'en' => 'Extract design, PII tags, join keys (user, course, enrollment).'],
                    'watchouts' => ['de' => 'mod_assign_get_submissions nie für Content-Extract nutzen.', 'en' => 'Never use mod_assign_get_submissions for content extraction.'],
                ],
                [
                    'id' => 'moodle-gradebook-schema',
                    'kind' => ['de' => 'Gradebook schema', 'en' => 'Gradebook schema'],
                    'where' => ['de' => 'Grades → Setup → Gradebook setup; grade_items/grade_grades tables reference', 'en' => 'Grades → Setup → Gradebook setup; grade_items/grade_grades tables reference'],
                    'how' => ['de' => 'Item-Typen und Aggregation-Methoden dokumentieren.', 'en' => 'Document item types and aggregation methods.'],
                    'useFor' => ['de' => 'Grade facts, average-grade KPI, pass-rate definitions.', 'en' => 'Grade facts, average-grade KPI, pass-rate definitions.'],
                    'watchouts' => ['de' => 'finalgrade nur aggregiert in breiten Marts verwenden.', 'en' => 'Use finalgrade only in aggregated form in broad marts.'],
                ],
                [
                    'id' => 'moodle-logstore-schema',
                    'kind' => ['de' => 'Logstore schema', 'en' => 'Logstore schema'],
                    'where' => ['de' => 'Site administration → Reports → Logs; logstore_standard_log table reference', 'en' => 'Site administration → Reports → Logs; logstore_standard_log table reference'],
                    'how' => ['de' => 'Event-Name-Allowlist definieren; verbose Felder ausschließen.', 'en' => 'Define an event-name allowlist; exclude verbose fields.'],
                    'useFor' => ['de' => 'Activity facts, engagement KPIs, last-access signals.', 'en' => 'Activity facts, engagement KPIs, last-access signals.'],
                    'watchouts' => ['de' => 'Ultra-hohes Volumen — sampeln/aggregieren vor Landing.', 'en' => 'Very high volume — sample/aggregate before landing.'],
                ],
                [
                    'id' => 'moodle-privacy-api-plugins',
                    'kind' => ['de' => 'Privacy API plugin providers', 'en' => 'Privacy API plugin providers'],
                    'where' => ['de' => 'Moodle Developer Docs → Privacy API; plugin privacy/provider.php files', 'en' => 'Moodle Developer Docs → Privacy API; plugin privacy/provider.php files'],
                    'how' => ['de' => 'Provider-Klassen je Plugin dokumentieren, welche Bildungsdaten sie halten.', 'en' => 'Document provider classes per plugin and which educational records they hold.'],
                    'useFor' => ['de' => 'PII scan coverage, DSAR scoping, retention design.', 'en' => 'PII scan coverage, DSAR scoping, retention design.'],
                    'watchouts' => ['de' => 'Third-Party-Plugins können zusätzliche Bildungsdaten halten — separat prüfen.', 'en' => 'Third-party plugins may hold additional educational records — review separately.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'adobe-experience-cloud' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'aec-event-no-profile',
                    'priority' => 'high',
                    'title' => ['de' => 'Experience Event ohne Profile', 'en' => 'Experience event without profile'],
                    'problem' => ['de' => 'Events ohne _id_profile brechen Journey- und Segment-Joins.', 'en' => 'Events without _id_profile break journey and segment joins.'],
                    'prevent' => ['de' => 'Edge/Analytics extract: Identity stitching vor Landing sicherstellen.', 'en' => 'Edge/Analytics extract: ensure identity stitching happens before landing.'],
                    'staffNeedToKnow' => ['de' => 'Data: Event ohne Profile-Link ist Stitching-Fehler.', 'en' => 'Data: Event without a profile link is a stitching error.'],
                    'checks' => ['de' => 'experience_event._id_profile IS NULL', 'en' => 'experience_event._id_profile IS NULL'],
                    'fixInSource' => ['de' => 'Re-run identity resolution; verify ECID sync.', 'en' => 'Re-run identity resolution; verify ECID sync.'],
                    'fixInWarehouse' => ['de' => 'Quarantine anonymous-unresolved events; exclude from per-profile KPIs.', 'en' => 'Quarantine anonymous-unresolved events; exclude from per-profile KPIs.'],
                ],
                [
                    'id' => 'aec-profile-no-consent-record',
                    'priority' => 'high',
                    'title' => ['de' => 'Profile ohne Consent Record', 'en' => 'Profile without consent record'],
                    'problem' => ['de' => 'Profile ohne Consent-Eintrag dürfen nicht für Marketing-Aktivierung genutzt werden.', 'en' => 'Profiles without a consent entry must not be used for marketing activation.'],
                    'prevent' => ['de' => 'Consent-Capture bei jedem Identity-Onboarding erzwingen.', 'en' => 'Enforce consent capture at every identity onboarding.'],
                    'staffNeedToKnow' => ['de' => 'Marketing: Kein Segment-Export ohne Consent-Check.', 'en' => 'Marketing: No segment export without a consent check.'],
                    'checks' => ['de' => 'profile.id NOT IN (SELECT profile_id FROM consent)', 'en' => 'profile.id NOT IN (SELECT profile_id FROM consent)'],
                    'fixInSource' => ['de' => 'Backfill consent capture; suppress activation until resolved.', 'en' => 'Backfill consent capture; suppress activation until resolved.'],
                    'fixInWarehouse' => ['de' => 'Flag consent_missing; exclude from activatable-segment counts.', 'en' => 'Flag consent_missing; exclude from activatable-segment counts.'],
                ],
                [
                    'id' => 'aec-segment-membership-no-profile',
                    'priority' => 'medium',
                    'title' => ['de' => 'Segment Membership ohne auflösbares Profile', 'en' => 'Segment membership without resolvable profile'],
                    'problem' => ['de' => 'Memberships ohne gültiges Profile verzerren Segment-Größen.', 'en' => 'Memberships without a valid profile distort segment sizes.'],
                    'prevent' => ['de' => 'Segment evaluation job: profile existence check vor Qualification.', 'en' => 'Segment evaluation job: check profile existence before qualification.'],
                    'staffNeedToKnow' => ['de' => 'Data: Stale Profile-Referenzen in Segment-Jobs bereinigen.', 'en' => 'Data: Clean up stale profile references in segment jobs.'],
                    'checks' => ['de' => 'segment_membership.profile_id NOT IN dim_profile', 'en' => 'segment_membership.profile_id NOT IN dim_profile'],
                    'fixInSource' => ['de' => 'Re-run segment evaluation; purge merged/deleted profile refs.', 'en' => 'Re-run segment evaluation; purge merged/deleted profile refs.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from segment-size KPIs.', 'en' => 'Quarantine; exclude from segment-size KPIs.'],
                ],
                [
                    'id' => 'aec-duplicate-identity-fragment',
                    'priority' => 'high',
                    'title' => ['de' => 'Doppelte Identity Fragments (Profile Fragmentation)', 'en' => 'Duplicate identity fragments (profile fragmentation)'],
                    'problem' => ['de' => 'Unresolved Identities erzeugen mehrere Profile für dieselbe Person — verzerrt Reach und Frequency.', 'en' => 'Unresolved identities create multiple profiles for the same person — distorts reach and frequency.'],
                    'prevent' => ['de' => 'Identity graph namespaces konsistent taggen; primary identity festlegen.', 'en' => 'Tag identity graph namespaces consistently; define a primary identity.'],
                    'staffNeedToKnow' => ['de' => 'Data/Marketing: Neue Identity-Quellen vor Onboarding im Identity Graph reviewen.', 'en' => 'Data/marketing: Review new identity sources in the identity graph before onboarding.'],
                    'checks' => ['de' => 'COUNT(DISTINCT profile_id) GROUP BY hashed_email HAVING COUNT > 1', 'en' => 'COUNT(DISTINCT profile_id) GROUP BY hashed_email HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Fix identity namespace config; re-run identity resolution.', 'en' => 'Fix identity namespace config; re-run identity resolution.'],
                    'fixInWarehouse' => ['de' => 'Merge map by hashed email; golden profile id.', 'en' => 'Merge map by hashed email; golden profile id.'],
                ],
                [
                    'id' => 'aec-campaign-send-no-consent-check',
                    'priority' => 'high',
                    'title' => ['de' => 'Campaign Send ohne Consent-Check', 'en' => 'Campaign send without consent check'],
                    'problem' => ['de' => 'Sends an nicht-consented Profile sind Compliance-Verstoß.', 'en' => 'Sends to non-consented profiles are a compliance violation.'],
                    'prevent' => ['de' => 'Suppression list / consent gate vor jedem Activation-Export.', 'en' => 'Suppression list / consent gate before every activation export.'],
                    'staffNeedToKnow' => ['de' => 'Marketing Ops: Consent-Gate darf nie umgangen werden.', 'en' => 'Marketing ops: Never bypass the consent gate.'],
                    'checks' => ['de' => "event.eventType = 'directMarketing.emailSent' AND profile_id NOT IN consented_profiles", 'en' => "event.eventType = 'directMarketing.emailSent' AND profile_id NOT IN consented_profiles"],
                    'fixInSource' => ['de' => 'Fix activation audience suppression config.', 'en' => 'Fix activation audience suppression config.'],
                    'fixInWarehouse' => ['de' => 'Flag compliance_violation; escalate to privacy team.', 'en' => 'Flag compliance_violation; escalate to privacy team.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'aec-profile-dup',
                    'entity' => 'Profile',
                    'title' => ['de' => 'Profile-Duplikate / Identity Fragmentation', 'en' => 'Profile duplicates / identity fragmentation'],
                    'matchKeys' => ['ECID', 'hashed email', 'CRM id', 'loyalty id'],
                    'preventInSource' => ['de' => 'Identity namespace governance; primary identity per source.', 'en' => 'Identity namespace governance; primary identity per source.'],
                    'resolveInWarehouse' => ['de' => 'Golden profile id; identity-hash merge map.', 'en' => 'Golden profile id; identity-hash merge map.'],
                    'survivorship' => ['de' => 'Profile mit vollständigstem Identity Graph und aktuellster Activity gewinnt.', 'en' => 'Profile with the most complete identity graph and latest activity wins.'],
                ],
                [
                    'id' => 'aec-segment-definition-drift',
                    'entity' => 'Segment',
                    'title' => ['de' => 'Segment Definition Drift', 'en' => 'Segment definition drift'],
                    'matchKeys' => ['segment id', 'segment name', 'segment definition version'],
                    'preventInSource' => ['de' => 'Change-controlled segment definitions; versioning bei Änderung.', 'en' => 'Change-controlled segment definitions; version on change.'],
                    'resolveInWarehouse' => ['de' => 'Canonical segment id; SCD2 definition version.', 'en' => 'Canonical segment id; SCD2 definition version.'],
                    'survivorship' => ['de' => 'Aktuelle Segment-Definition gewinnt; historische Größen bleiben nachvollziehbar.', 'en' => 'Current segment definition wins; historical sizes remain traceable.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'aec-consent-gate',
                    'area' => ['de' => 'Privacy → Consent & preferences', 'en' => 'Privacy → Consent & preferences'],
                    'setting' => ['de' => 'Consent Gate für alle Activation Destinations erzwingen', 'en' => 'Enforce a consent gate for all activation destinations'],
                    'why' => ['de' => 'Verhindert Sends/Aktivierung an nicht-consented Profile.', 'en' => 'Prevents sends/activation to non-consented profiles.'],
                    'how' => ['de' => 'Suppression list per purpose; audit activation jobs.', 'en' => 'Suppression list per purpose; audit activation jobs.'],
                ],
                [
                    'id' => 'aec-identity-namespace-governance',
                    'area' => ['de' => 'Identities → Namespaces', 'en' => 'Identities → Namespaces'],
                    'setting' => ['de' => 'Identity Namespace Standards und Primary-Identity-Regeln', 'en' => 'Identity namespace standards and primary-identity rules'],
                    'why' => ['de' => 'Reduziert Profile-Fragmentation und Merge-Aufwand.', 'en' => 'Reduces profile fragmentation and merge effort.'],
                    'how' => ['de' => 'Document namespace per source; review before onboarding new sources.', 'en' => 'Document namespace per source; review before onboarding new sources.'],
                ],
                [
                    'id' => 'aec-dataset-retention',
                    'area' => ['de' => 'Datasets → Data lifecycle', 'en' => 'Datasets → Data lifecycle'],
                    'setting' => ['de' => 'Retention/TTL Policies je Dataset; keine Raw-Event-Bulk-Retention default', 'en' => 'Retention/TTL policies per dataset; no raw-event bulk retention by default'],
                    'why' => ['de' => 'Reduziert PII-Exposure-Fenster und Storage-Kosten.', 'en' => 'Reduces PII exposure window and storage costs.'],
                    'how' => ['de' => 'Configure dataset expiration; document exceptions.', 'en' => 'Configure dataset expiration; document exceptions.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'aec-xdm-schema-registry',
                    'kind' => ['de' => 'XDM schema registry', 'en' => 'XDM schema registry'],
                    'where' => ['de' => 'Adobe Experience Platform → Schemas / Schema Registry API', 'en' => 'Adobe Experience Platform → Schemas / Schema Registry API'],
                    'how' => ['de' => 'Field Groups und Mixins inventarisieren; PII-Felder taggen.', 'en' => 'Inventory field groups and mixins; tag PII fields.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (profile, event).', 'en' => 'Extract design, PII tags, join keys (profile, event).'],
                    'watchouts' => ['de' => 'Custom Field Groups können zusätzliche PII enthalten — Schema Review Pflicht.', 'en' => 'Custom field groups may contain additional PII — schema review is mandatory.'],
                ],
                [
                    'id' => 'aec-segmentation-service',
                    'kind' => ['de' => 'Segmentation service', 'en' => 'Segmentation service'],
                    'where' => ['de' => 'AEP → Audiences → Segment Builder / Segmentation API', 'en' => 'AEP → Audiences → Segment Builder / Segmentation API'],
                    'how' => ['de' => 'Segment-Definitionen und Evaluation-Modus (streaming/batch) dokumentieren.', 'en' => 'Document segment definitions and evaluation mode (streaming/batch).'],
                    'useFor' => ['de' => 'Segment-size KPIs, reach measures, activation eligibility.', 'en' => 'Segment-size KPIs, reach measures, activation eligibility.'],
                    'watchouts' => ['de' => 'Segment Refresh-Frequenz beachten für Trend-Interpretation.', 'en' => 'Account for segment refresh frequency when interpreting trends.'],
                ],
                [
                    'id' => 'aec-consent-preferences-api',
                    'kind' => ['de' => 'Consent & preferences API', 'en' => 'Consent & preferences API'],
                    'where' => ['de' => 'AEP → Privacy Service / Consent & Preferences API', 'en' => 'AEP → Privacy Service / Consent & Preferences API'],
                    'how' => ['de' => 'Purpose-Katalog und Consent-Status-Codes dokumentieren.', 'en' => 'Document the purpose catalog and consent status codes.'],
                    'useFor' => ['de' => 'Consent rate KPIs, activation gating, DSAR scoping.', 'en' => 'Consent rate KPIs, activation gating, DSAR scoping.'],
                    'watchouts' => ['de' => 'Purpose-Codes können je Rechtsraum abweichen — Mapping pflegen.', 'en' => 'Purpose codes can differ per jurisdiction — maintain a mapping.'],
                ],
                [
                    'id' => 'aec-destinations-catalog',
                    'kind' => ['de' => 'Destinations catalog', 'en' => 'Destinations catalog'],
                    'where' => ['de' => 'AEP → Destinations → Catalog / Activation', 'en' => 'AEP → Destinations → Catalog / Activation'],
                    'how' => ['de' => 'Aktivierte Destinations und Export-Frequenz dokumentieren.', 'en' => 'Document activated destinations and export frequency.'],
                    'useFor' => ['de' => 'Activation coverage, campaign-send facts, reach reconciliation.', 'en' => 'Activation coverage, campaign-send facts, reach reconciliation.'],
                    'watchouts' => ['de' => 'Jede Destination verdoppelt Profile-PII extern — Consent-Gate prüfen.', 'en' => 'Each destination duplicates profile PII externally — verify the consent gate.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],
];
