<?php

/**
 * Wave 11 quality overlays — Service/BPM/Healthcare source-native DQ, MDM, metadata guides.
 *
 * @return array<string, array<string, mixed>>
 */

return [
    'freshdesk' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'freshdesk-ticket-no-requester',
                    'priority' => 'high',
                    'title' => ['de' => 'Ticket ohne Requester', 'en' => 'Ticket without requester'],
                    'problem' => ['de' => 'Tickets ohne requester_id brechen Contact-Joins und Reach-KPIs.', 'en' => 'Tickets without requester_id break contact joins and reach KPIs.'],
                    'prevent' => ['de' => 'REST extract: requester_id Pflichtfeld im Select; anonyme Tickets tracken.', 'en' => 'REST extract: requester_id required in the select; track anonymous tickets.'],
                    'staffNeedToKnow' => ['de' => 'Data: Ticket ohne Requester ist Extract-Fehler.', 'en' => 'Data: Ticket without requester is an extract error.'],
                    'checks' => ['de' => 'ticket.requester_id IS NULL', 'en' => 'ticket.requester_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-extract; check deleted contact tombstones.', 'en' => 'Re-extract; check deleted contact tombstones.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown contact dim.', 'en' => 'Quarantine; Unknown contact dim.'],
                ],
                [
                    'id' => 'freshdesk-resolved-before-created',
                    'priority' => 'high',
                    'title' => ['de' => 'Resolved-Zeitpunkt vor Created-Zeitpunkt', 'en' => 'Resolved timestamp before created timestamp'],
                    'problem' => ['de' => 'resolved_at < created_at macht Cycle-Time-Berechnungen unbrauchbar.', 'en' => 'resolved_at < created_at makes cycle-time calculations unusable.'],
                    'prevent' => ['de' => 'Timezone-Normalisierung im Extract; API-Feld-Mapping validieren.', 'en' => 'Normalize time zones in the extract; validate the API field mapping.'],
                    'staffNeedToKnow' => ['de' => 'Data: Timestamp-Felder konsistent in UTC extrahieren.', 'en' => 'Data: Extract timestamp fields consistently in UTC.'],
                    'checks' => ['de' => 'ticket.resolved_at < ticket.created_at', 'en' => 'ticket.resolved_at < ticket.created_at'],
                    'fixInSource' => ['de' => 'Fix timezone conversion; re-extract affected records.', 'en' => 'Fix timezone conversion; re-extract affected records.'],
                    'fixInWarehouse' => ['de' => 'Flag timestamp_anomaly; exclude from cycle-time average.', 'en' => 'Flag timestamp_anomaly; exclude from cycle-time average.'],
                ],
                [
                    'id' => 'freshdesk-agent-deactivated-open-tickets',
                    'priority' => 'medium',
                    'title' => ['de' => 'Deaktivierter Agent mit offenen Tickets', 'en' => 'Deactivated agent with open tickets'],
                    'problem' => ['de' => 'Offene Tickets bei deaktivierten Agents verzerren Workload und SLA-Risiko.', 'en' => 'Open tickets on deactivated agents distort workload and SLA risk.'],
                    'prevent' => ['de' => 'Offboarding-Workflow: Ticket-Reassignment vor Agent-Deaktivierung.', 'en' => 'Offboarding workflow: reassign tickets before agent deactivation.'],
                    'staffNeedToKnow' => ['de' => 'Team Leads: Deactivate ≠ Reassignment.', 'en' => 'Team leads: Deactivate ≠ reassignment.'],
                    'checks' => ['de' => "agent.active = FALSE AND open_ticket_count > 0", 'en' => "agent.active = FALSE AND open_ticket_count > 0"],
                    'fixInSource' => ['de' => 'Reassign tickets; complete offboarding checklist.', 'en' => 'Reassign tickets; complete offboarding checklist.'],
                    'fixInWarehouse' => ['de' => 'Flag stale_ownership; exclude from active-agent workload KPIs.', 'en' => 'Flag stale_ownership; exclude from active-agent workload KPIs.'],
                ],
                [
                    'id' => 'freshdesk-duplicate-contact-email',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Contact-E-Mail im Extract', 'en' => 'Duplicate contact email in extract'],
                    'problem' => ['de' => 'Doppelte Contact-Records verzerren Customer-Counts und Ticket-Reach.', 'en' => 'Duplicate contact records distort customer counts and ticket reach.'],
                    'prevent' => ['de' => 'Deduplication rules in Freshdesk; merge on creation conflict.', 'en' => 'Deduplication rules in Freshdesk; merge on creation conflict.'],
                    'staffNeedToKnow' => ['de' => 'Support Ops: Contact-Merge bei Duplikat-Erkennung nutzen.', 'en' => 'Support ops: Use contact merge when duplicates are detected.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY email HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY email HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Merge contacts in Freshdesk; re-extract.', 'en' => 'Merge contacts in Freshdesk; re-extract.'],
                    'fixInWarehouse' => ['de' => 'Golden contact id; email-hash merge map.', 'en' => 'Golden contact id; email-hash merge map.'],
                ],
                [
                    'id' => 'freshdesk-sla-policy-orphan',
                    'priority' => 'medium',
                    'title' => ['de' => 'Ticket ohne zuordenbare SLA Policy', 'en' => 'Ticket without an assignable SLA policy'],
                    'problem' => ['de' => 'Tickets ohne SLA-Policy-Match machen Breach-Rate-KPIs unvollständig.', 'en' => 'Tickets without an SLA policy match make breach-rate KPIs incomplete.'],
                    'prevent' => ['de' => 'Default SLA Policy für alle Ticket-Typen/Prioritäten definieren.', 'en' => 'Define a default SLA policy for all ticket types/priorities.'],
                    'staffNeedToKnow' => ['de' => 'Admins: Jede Priority-Kombination braucht eine SLA Policy.', 'en' => 'Admins: Every priority combination needs an SLA policy.'],
                    'checks' => ['de' => 'ticket.sla_policy_id IS NULL', 'en' => 'ticket.sla_policy_id IS NULL'],
                    'fixInSource' => ['de' => 'Configure default/fallback SLA policy.', 'en' => 'Configure default/fallback SLA policy.'],
                    'fixInWarehouse' => ['de' => 'Flag sla_unassigned; exclude from breach-rate denominator.', 'en' => 'Flag sla_unassigned; exclude from breach-rate denominator.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'freshdesk-contact-dup',
                    'entity' => 'Contact',
                    'title' => ['de' => 'Contact-Duplikate / Merge', 'en' => 'Contact duplicates / merge'],
                    'matchKeys' => ['id', 'email', 'phone', 'company_id'],
                    'preventInSource' => ['de' => 'Enable duplicate detection on contact create; encourage merge workflow.', 'en' => 'Enable duplicate detection on contact create; encourage the merge workflow.'],
                    'resolveInWarehouse' => ['de' => 'Golden contact id; email-hash merge map.', 'en' => 'Golden contact id; email-hash merge map.'],
                    'survivorship' => ['de' => 'Contact mit meisten Tickets und aktuellster Activity gewinnt.', 'en' => 'Contact with the most tickets and latest activity wins.'],
                ],
                [
                    'id' => 'freshdesk-company-domain-map',
                    'entity' => 'Company',
                    'title' => ['de' => 'Company Domain Mapping Drift', 'en' => 'Company domain mapping drift'],
                    'matchKeys' => ['company id', 'domains', 'name'],
                    'preventInSource' => ['de' => 'Domain-based auto-association pflegen; Domain-Changes reviewen.', 'en' => 'Maintain domain-based auto-association; review domain changes.'],
                    'resolveInWarehouse' => ['de' => 'Canonical company id; SCD2 domain list.', 'en' => 'Canonical company id; SCD2 domain list.'],
                    'survivorship' => ['de' => 'Company mit meisten aktiven Contacts gewinnt.', 'en' => 'Company with the most active contacts wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'freshdesk-sla-policies-default',
                    'area' => ['de' => 'Admin → Workflows → SLA policies', 'en' => 'Admin → Workflows → SLA policies'],
                    'setting' => ['de' => 'Default/Fallback SLA Policy für alle Priority-Kombinationen', 'en' => 'Default/fallback SLA policy for all priority combinations'],
                    'why' => ['de' => 'Verhindert unassigned SLA und macht Breach-Rate-KPIs vollständig.', 'en' => 'Prevents unassigned SLA and keeps breach-rate KPIs complete.'],
                    'how' => ['de' => 'Configure catch-all policy; review priority-to-policy mapping quarterly.', 'en' => 'Configure a catch-all policy; review priority-to-policy mapping quarterly.'],
                ],
                [
                    'id' => 'freshdesk-agent-offboarding',
                    'area' => ['de' => 'Admin → Team → Agents', 'en' => 'Admin → Team → Agents'],
                    'setting' => ['de' => 'Offboarding-Checklist mit Ticket-Reassignment', 'en' => 'Offboarding checklist with ticket reassignment'],
                    'why' => ['de' => 'Workload-KPIs bleiben aktuell ohne Stale Ownership.', 'en' => 'Workload KPIs stay current without stale ownership.'],
                    'how' => ['de' => 'Bulk reassign open tickets; deactivate agent; audit orphaned ownership.', 'en' => 'Bulk-reassign open tickets; deactivate agent; audit orphaned ownership.'],
                ],
                [
                    'id' => 'freshdesk-contact-merge-policy',
                    'area' => ['de' => 'Contacts → Merge / deduplication', 'en' => 'Contacts → Merge / deduplication'],
                    'setting' => ['de' => 'Duplicate-Detection und Merge-Workflow aktiv halten', 'en' => 'Keep duplicate detection and the merge workflow active'],
                    'why' => ['de' => 'Reduziert Customer-Count-Verzerrung und verbessert Reach-KPIs.', 'en' => 'Reduces customer-count distortion and improves reach KPIs.'],
                    'how' => ['de' => 'Enable auto-merge suggestions; periodic manual review.', 'en' => 'Enable auto-merge suggestions; periodic manual review.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'freshdesk-rest-api-schema',
                    'kind' => ['de' => 'REST API schema', 'en' => 'REST API schema'],
                    'where' => ['de' => 'Freshdesk Developers → API Reference (Tickets, Contacts, Agents)', 'en' => 'Freshdesk Developers → API reference (Tickets, Contacts, Agents)'],
                    'how' => ['de' => 'Feld-Referenz inventarisieren; Select-Allowlist für Extract.', 'en' => 'Inventory the field reference; select allowlist for extract.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (ticket, contact, agent).', 'en' => 'Extract design, PII tags, join keys (ticket, contact, agent).'],
                    'watchouts' => ['de' => 'Conversations-Endpoint nie mit body-Feld selektieren.', 'en' => 'Never select the conversations endpoint with the body field.'],
                ],
                [
                    'id' => 'freshdesk-sla-policy-config',
                    'kind' => ['de' => 'SLA policy configuration', 'en' => 'SLA policy configuration'],
                    'where' => ['de' => 'Admin → Workflows → SLA policies', 'en' => 'Admin → Workflows → SLA policies'],
                    'how' => ['de' => 'Response/Resolution-Targets je Priority dokumentieren.', 'en' => 'Document response/resolution targets per priority.'],
                    'useFor' => ['de' => 'SLA breach KPIs, priority dims.', 'en' => 'SLA breach KPIs, priority dims.'],
                    'watchouts' => ['de' => 'Business-Hours-Kalender beeinflusst SLA-Berechnung.', 'en' => 'Business-hours calendar affects SLA calculation.'],
                ],
                [
                    'id' => 'freshdesk-custom-fields',
                    'kind' => ['de' => 'Ticket custom fields', 'en' => 'Ticket custom fields'],
                    'where' => ['de' => 'Admin → Ticket fields', 'en' => 'Admin → Ticket fields'],
                    'how' => ['de' => 'Custom-Field-Typen und PII-Risiko je Feld dokumentieren.', 'en' => 'Document custom field types and PII risk per field.'],
                    'useFor' => ['de' => 'Extract allowlist, additional dimensions, PII scan.', 'en' => 'Extract allowlist, additional dimensions, PII scan.'],
                    'watchouts' => ['de' => 'Freitext-Custom-Fields können Kunden-PII enthalten.', 'en' => 'Free-text custom fields can contain customer PII.'],
                ],
                [
                    'id' => 'freshdesk-satisfaction-survey-schema',
                    'kind' => ['de' => 'Satisfaction survey schema', 'en' => 'Satisfaction survey schema'],
                    'where' => ['de' => 'Admin → Customer satisfaction; Satisfaction ratings API', 'en' => 'Admin → Customer satisfaction; Satisfaction ratings API'],
                    'how' => ['de' => 'Rating-Skala und Frage-Set dokumentieren — Freitext-Feld ausschließen.', 'en' => 'Document the rating scale and question set — exclude the free-text field.'],
                    'useFor' => ['de' => 'CSAT score KPI, response-rate coverage.', 'en' => 'CSAT score KPI, response-rate coverage.'],
                    'watchouts' => ['de' => 'Freitext-Feedback nie extrahieren.', 'en' => 'Never extract free-text feedback.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'pega' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'pega-case-no-case-type',
                    'priority' => 'high',
                    'title' => ['de' => 'Case ohne Case Type', 'en' => 'Case without case type'],
                    'problem' => ['de' => 'Cases ohne gültigen pyClass brechen Case-Type-Rollups.', 'en' => 'Cases without a valid pyClass break case-type rollups.'],
                    'prevent' => ['de' => 'Case API extract: pyClass Pflichtfeld; Rule-Deployment vor Extract validieren.', 'en' => 'Case API extract: pyClass required; validate rule deployment before extract.'],
                    'staffNeedToKnow' => ['de' => 'Data: Case ohne Type ist Extract-/Deployment-Fehler.', 'en' => 'Data: Case without a type is an extract/deployment error.'],
                    'checks' => ['de' => 'case.pyClass IS NULL OR pyClass NOT IN dim_case_type', 'en' => 'case.pyClass IS NULL OR pyClass NOT IN dim_case_type'],
                    'fixInSource' => ['de' => 'Re-extract; verify case type rule deployment.', 'en' => 'Re-extract; verify case type rule deployment.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown case type dim.', 'en' => 'Quarantine; Unknown case type dim.'],
                ],
                [
                    'id' => 'pega-assignment-no-operator',
                    'priority' => 'high',
                    'title' => ['de' => 'Assignment ohne Operator', 'en' => 'Assignment without operator'],
                    'problem' => ['de' => 'Assignments ohne pyAssignedOperatorID brechen Workload-Joins.', 'en' => 'Assignments without pyAssignedOperatorID break workload joins.'],
                    'prevent' => ['de' => 'Workbasket-Routing-Regeln prüfen; unassigned Workbasket separat behandeln.', 'en' => 'Review workbasket routing rules; handle the unassigned workbasket separately.'],
                    'staffNeedToKnow' => ['de' => 'Ops: Workbasket-Assignments sind kein Fehler, aber getrennt zu zählen.', 'en' => 'Ops: Workbasket assignments are not an error but must be counted separately.'],
                    'checks' => ['de' => 'assignment.pyAssignedOperatorID IS NULL AND assignment.assignee_type = \'operator\'', 'en' => 'assignment.pyAssignedOperatorID IS NULL AND assignment.assignee_type = \'operator\''],
                    'fixInSource' => ['de' => 'Fix routing rule; reassign orphaned assignment.', 'en' => 'Fix routing rule; reassign orphaned assignment.'],
                    'fixInWarehouse' => ['de' => 'Flag unassigned_operator; exclude from per-operator workload.', 'en' => 'Flag unassigned_operator; exclude from per-operator workload.'],
                ],
                [
                    'id' => 'pega-resolved-before-created',
                    'priority' => 'high',
                    'title' => ['de' => 'pxResolvedTimestamp vor pxCreateDateTime', 'en' => 'pxResolvedTimestamp before pxCreateDateTime'],
                    'problem' => ['de' => 'Inkonsistente Timestamps verzerren Cycle-Time-Berechnungen.', 'en' => 'Inconsistent timestamps distort cycle-time calculations.'],
                    'prevent' => ['de' => 'Timezone-Handling im Extract validieren; Clock-Skew zwischen Nodes prüfen.', 'en' => 'Validate timezone handling in the extract; check clock skew between nodes.'],
                    'staffNeedToKnow' => ['de' => 'Data: Timestamp-Extraktion konsistent in UTC.', 'en' => 'Data: Extract timestamps consistently in UTC.'],
                    'checks' => ['de' => 'case.pxResolvedTimestamp < case.pxCreateDateTime', 'en' => 'case.pxResolvedTimestamp < case.pxCreateDateTime'],
                    'fixInSource' => ['de' => 'Fix timezone conversion; re-extract affected cases.', 'en' => 'Fix timezone conversion; re-extract affected cases.'],
                    'fixInWarehouse' => ['de' => 'Flag timestamp_anomaly; exclude from cycle-time average.', 'en' => 'Flag timestamp_anomaly; exclude from cycle-time average.'],
                ],
                [
                    'id' => 'pega-sla-event-orphan',
                    'priority' => 'medium',
                    'title' => ['de' => 'SLA Event ohne Case-Referenz', 'en' => 'SLA event without a case reference'],
                    'problem' => ['de' => 'SLA Events ohne case_id brechen Breach-Rate-Joins.', 'en' => 'SLA events without case_id break breach-rate joins.'],
                    'prevent' => ['de' => 'Agent/Service-Level-Extract: case context immer mitladen.', 'en' => 'Agent/service-level extract: always load case context.'],
                    'staffNeedToKnow' => ['de' => 'Data: SLA Event ohne Case ist Extract-Artefakt.', 'en' => 'Data: SLA event without a case is an extract artifact.'],
                    'checks' => ['de' => 'sla_event.case_id IS NULL', 'en' => 'sla_event.case_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-extract with case context.', 'en' => 'Re-extract with case context.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from breach-rate KPIs.', 'en' => 'Quarantine; exclude from breach-rate KPIs.'],
                ],
                [
                    'id' => 'pega-duplicate-case-pyid',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte pyID im Extract', 'en' => 'Duplicate pyID in extract'],
                    'problem' => ['de' => 'Doppelte pyID verzerren Cases-Created- und Resolution-Counts.', 'en' => 'Duplicate pyID distort cases-created and resolution counts.'],
                    'prevent' => ['de' => 'Idempotent load key auf pzInsKey; Report-Definition-Pagination prüfen.', 'en' => 'Idempotent load key on pzInsKey; check report-definition pagination.'],
                    'staffNeedToKnow' => ['de' => 'Data: pzInsKey als eindeutigen Natural Key nutzen, nicht pyID allein.', 'en' => 'Data: Use pzInsKey as the unique natural key, not pyID alone.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY pzInsKey HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY pzInsKey HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate report definition pagination.', 'en' => 'Re-extract; investigate report definition pagination.'],
                    'fixInWarehouse' => ['de' => 'Dedup by pzInsKey; keep latest _loaded_at.', 'en' => 'Dedup by pzInsKey; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'pega-operator-dup',
                    'entity' => 'Operator',
                    'title' => ['de' => 'Operator-Duplikate / Re-hire', 'en' => 'Operator duplicates / rehire'],
                    'matchKeys' => ['pyUserIdentifier', 'pzInsKey', 'pyEmailAddress'],
                    'preventInSource' => ['de' => 'Directory sync as source of truth; deactivate instead of recreate.', 'en' => 'Directory sync as source of truth; deactivate instead of recreating.'],
                    'resolveInWarehouse' => ['de' => 'Golden operator id; email-hash merge map.', 'en' => 'Golden operator id; email-hash merge map.'],
                    'survivorship' => ['de' => 'Aktiver Operator mit neuester Assignment-Activity gewinnt.', 'en' => 'Active operator with latest assignment activity wins.'],
                ],
                [
                    'id' => 'pega-case-type-taxonomy',
                    'entity' => 'Case type',
                    'title' => ['de' => 'Case Type Taxonomy Drift', 'en' => 'Case type taxonomy drift'],
                    'matchKeys' => ['className', 'ruleset', 'version'],
                    'preventInSource' => ['de' => 'Controlled case type versioning; ruleset governance.', 'en' => 'Controlled case type versioning; ruleset governance.'],
                    'resolveInWarehouse' => ['de' => 'Canonical case type key; SCD2 label.', 'en' => 'Canonical case type key; SCD2 label.'],
                    'survivorship' => ['de' => 'Aktuellste deployte Version gewinnt.', 'en' => 'Latest deployed version wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'pega-sla-configuration',
                    'area' => ['de' => 'Case designer → Service level agreements', 'en' => 'Case designer → Service level agreements'],
                    'setting' => ['de' => 'SLA Goal/Deadline konsequent je Stage/Assignment konfigurieren', 'en' => 'Configure SLA goal/deadline consistently per stage/assignment'],
                    'why' => ['de' => 'Breach-Rate-KPIs werden vollständig und vergleichbar.', 'en' => 'Breach-rate KPIs become complete and comparable.'],
                    'how' => ['de' => 'Define goal + deadline for every assignment type; review quarterly.', 'en' => 'Define a goal + deadline for every assignment type; review quarterly.'],
                ],
                [
                    'id' => 'pega-workbasket-routing',
                    'area' => ['de' => 'Case designer → Routing', 'en' => 'Case designer → Routing'],
                    'setting' => ['de' => 'Routing-Regeln für Workbasket vs. Operator-Assignment dokumentieren', 'en' => 'Document routing rules for workbasket vs operator assignment'],
                    'why' => ['de' => 'Verhindert Orphan-Assignments und macht Workload-KPIs verlässlich.', 'en' => 'Prevents orphan assignments and keeps workload KPIs reliable.'],
                    'how' => ['de' => 'Define default routing; review unrouted assignment queue.', 'en' => 'Define default routing; review the unrouted assignment queue.'],
                ],
                [
                    'id' => 'pega-attachment-category-governance',
                    'area' => ['de' => 'Case designer → Attachments', 'en' => 'Case designer → Attachments'],
                    'setting' => ['de' => 'Attachment-Kategorien standardisieren; keine Content-Extraktion ins Warehouse', 'en' => 'Standardize attachment categories; no content extraction into the warehouse'],
                    'why' => ['de' => 'Attachment-Coverage-KPIs ohne Content-Risiko.', 'en' => 'Attachment coverage KPIs without content risk.'],
                    'how' => ['de' => 'Use standard categories (File, URL, Correspondence); export meta only.', 'en' => 'Use standard categories (File, URL, correspondence); export meta only.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'pega-case-api-schema',
                    'kind' => ['de' => 'Case API schema', 'en' => 'Case API schema'],
                    'where' => ['de' => 'Pega Platform → Case Management API / Constellation DX API reference', 'en' => 'Pega Platform → Case Management API / Constellation DX API reference'],
                    'how' => ['de' => 'Case/Assignment/Operator-Felder inventarisieren; Select-Allowlist für Extract.', 'en' => 'Inventory case/assignment/operator fields; select allowlist for extract.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (case, assignment, operator).', 'en' => 'Extract design, PII tags, join keys (case, assignment, operator).'],
                    'watchouts' => ['de' => 'Attachment/Correspondence-Content nie mit dem Select laden.', 'en' => 'Never load attachment/correspondence content with the select.'],
                ],
                [
                    'id' => 'pega-report-definitions',
                    'kind' => ['de' => 'Report definitions', 'en' => 'Report definitions'],
                    'where' => ['de' => 'Dev Studio → Reports → Report Definition rules', 'en' => 'Dev Studio → Reports → Report Definition rules'],
                    'how' => ['de' => 'Bestehende Report-Definitionen als Feld-Referenz für Extract nutzen.', 'en' => 'Use existing report definitions as a field reference for extract.'],
                    'useFor' => ['de' => 'Case/assignment facts, operator dims, SLA facts.', 'en' => 'Case/assignment facts, operator dims, SLA facts.'],
                    'watchouts' => ['de' => 'Report Definitions können bereits PII-Felder joinen — vor Reuse prüfen.', 'en' => 'Report definitions may already join PII fields — review before reuse.'],
                ],
                [
                    'id' => 'pega-case-type-designer',
                    'kind' => ['de' => 'Case type designer', 'en' => 'Case type designer'],
                    'where' => ['de' => 'Dev Studio → Case Management → Case types', 'en' => 'Dev Studio → Case Management → Case types'],
                    'how' => ['de' => 'Stages, Processes und Views je Case Type dokumentieren.', 'en' => 'Document stages, processes and views per case type.'],
                    'useFor' => ['de' => 'Stage dim, case type dim, cycle-time bottleneck analysis.', 'en' => 'Stage dim, case type dim, cycle-time bottleneck analysis.'],
                    'watchouts' => ['de' => 'Stage-Namen können sich je Case-Type-Version unterscheiden — Mapping pflegen.', 'en' => 'Stage names can differ per case-type version — maintain a mapping.'],
                ],
                [
                    'id' => 'pega-sla-rule-schema',
                    'kind' => ['de' => 'Service level rule schema', 'en' => 'Service level rule schema'],
                    'where' => ['de' => 'Dev Studio → SLAs; Service Level rule form', 'en' => 'Dev Studio → SLAs; Service Level rule form'],
                    'how' => ['de' => 'Goal/Deadline/Escalation-Actions je Assignment-Typ dokumentieren.', 'en' => 'Document goal/deadline/escalation actions per assignment type.'],
                    'useFor' => ['de' => 'SLA breach facts, escalation coverage.', 'en' => 'SLA breach facts, escalation coverage.'],
                    'watchouts' => ['de' => 'Goal-Passed vs. Deadline-Passed nicht vermischen.', 'en' => 'Do not mix goal-passed vs deadline-passed.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'camunda' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'camunda-instance-no-definition',
                    'priority' => 'high',
                    'title' => ['de' => 'Process Instance ohne Process Definition', 'en' => 'Process instance without a process definition'],
                    'problem' => ['de' => 'Instances ohne processDefinitionId brechen Process-Key-Rollups.', 'en' => 'Instances without processDefinitionId break process-key rollups.'],
                    'prevent' => ['de' => 'REST History API: processDefinitionId Pflichtfeld im Select.', 'en' => 'REST History API: processDefinitionId required in the select.'],
                    'staffNeedToKnow' => ['de' => 'Data: Instance ohne Definition ist Extract-Fehler.', 'en' => 'Data: Instance without a definition is an extract error.'],
                    'checks' => ['de' => 'process_instance.process_definition_id IS NULL OR process_definition_id NOT IN dim_process_definition', 'en' => 'process_instance.process_definition_id IS NULL OR process_definition_id NOT IN dim_process_definition'],
                    'fixInSource' => ['de' => 'Re-extract; verify deployment/undeployment tombstones.', 'en' => 'Re-extract; verify deployment/undeployment tombstones.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; Unknown process definition dim.', 'en' => 'Quarantine; Unknown process definition dim.'],
                ],
                [
                    'id' => 'camunda-incident-no-instance',
                    'priority' => 'high',
                    'title' => ['de' => 'Incident ohne Process Instance', 'en' => 'Incident without a process instance'],
                    'problem' => ['de' => 'Incidents ohne processInstanceId brechen Root-Cause-Joins.', 'en' => 'Incidents without processInstanceId break root-cause joins.'],
                    'prevent' => ['de' => 'Incident query: processInstanceId immer mitladen.', 'en' => 'Incident query: always load processInstanceId.'],
                    'staffNeedToKnow' => ['de' => 'Data: Incident ohne Instance ist Extract-Artefakt.', 'en' => 'Data: Incident without an instance is an extract artifact.'],
                    'checks' => ['de' => 'incident.process_instance_id IS NULL', 'en' => 'incident.process_instance_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-extract incidents with instance context.', 'en' => 'Re-extract incidents with instance context.'],
                    'fixInWarehouse' => ['de' => 'Quarantine; exclude from per-process incident KPIs.', 'en' => 'Quarantine; exclude from per-process incident KPIs.'],
                ],
                [
                    'id' => 'camunda-task-overdue-no-escalation',
                    'priority' => 'medium',
                    'title' => ['de' => 'Overdue Task ohne Eskalation', 'en' => 'Overdue task without escalation'],
                    'problem' => ['de' => 'Tasks über due-Datum ohne Reminder/Escalation-Event verzerren SLA-Compliance.', 'en' => 'Tasks past their due date without a reminder/escalation event distort SLA compliance.'],
                    'prevent' => ['de' => 'BPMN Timer-Boundary-Events für Task-Escalation konfigurieren.', 'en' => 'Configure BPMN timer boundary events for task escalation.'],
                    'staffNeedToKnow' => ['de' => 'Process Owners: Escalation-Timer für kritische Tasks Pflicht.', 'en' => 'Process owners: Escalation timers are required for critical tasks.'],
                    'checks' => ['de' => "task.due < CURRENT_TIMESTAMP AND task.escalated = FALSE", 'en' => "task.due < CURRENT_TIMESTAMP AND task.escalated = FALSE"],
                    'fixInSource' => ['de' => 'Add escalation timer to BPMN model; redeploy.', 'en' => 'Add an escalation timer to the BPMN model; redeploy.'],
                    'fixInWarehouse' => ['de' => 'Flag overdue_no_escalation; separate SLA-risk KPI.', 'en' => 'Flag overdue_no_escalation; separate SLA-risk KPI.'],
                ],
                [
                    'id' => 'camunda-external-task-max-retries',
                    'priority' => 'medium',
                    'title' => ['de' => 'External Task mit erschöpften Retries', 'en' => 'External task with exhausted retries'],
                    'problem' => ['de' => 'retries=0 ohne aktives Incident-Handling blockiert Prozessfortschritt.', 'en' => 'retries=0 without active incident handling blocks process progress.'],
                    'prevent' => ['de' => 'Retry-Policy und Dead-Letter-Handling für External Tasks definieren.', 'en' => 'Define a retry policy and dead-letter handling for external tasks.'],
                    'staffNeedToKnow' => ['de' => 'Engineering: Service Worker Fehler zeitnah beheben.', 'en' => 'Engineering: Fix service-worker errors promptly.'],
                    'checks' => ['de' => 'external_task.retries = 0', 'en' => 'external_task.retries = 0'],
                    'fixInSource' => ['de' => 'Fix service worker; increment retries or resolve incident.', 'en' => 'Fix the service worker; increment retries or resolve the incident.'],
                    'fixInWarehouse' => ['de' => 'Flag exhausted_retries; feed into incidents-open KPI.', 'en' => 'Flag exhausted_retries; feed into the incidents-open KPI.'],
                ],
                [
                    'id' => 'camunda-duplicate-instance-id',
                    'priority' => 'medium',
                    'title' => ['de' => 'Doppelte Process Instance IDs im Extract', 'en' => 'Duplicate process instance ids in extract'],
                    'problem' => ['de' => 'Doppelte instance id verzerren Started/Completed-Counts.', 'en' => 'Duplicate instance ids distort started/completed counts.'],
                    'prevent' => ['de' => 'Idempotent load key; pagination overlap in History API prüfen.', 'en' => 'Idempotent load key; check pagination overlap in the history API.'],
                    'staffNeedToKnow' => ['de' => 'Data: instance id global eindeutig halten.', 'en' => 'Data: Keep instance id globally unique.'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY process_instance_id HAVING COUNT > 1', 'en' => 'COUNT(*) GROUP BY process_instance_id HAVING COUNT > 1'],
                    'fixInSource' => ['de' => 'Re-extract; investigate History API pagination.', 'en' => 'Re-extract; investigate history API pagination.'],
                    'fixInWarehouse' => ['de' => 'Dedup by process_instance_id; keep latest _loaded_at.', 'en' => 'Dedup by process_instance_id; keep latest _loaded_at.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'camunda-process-definition-version-map',
                    'entity' => 'Process definition',
                    'title' => ['de' => 'Process Definition Version Mapping', 'en' => 'Process definition version mapping'],
                    'matchKeys' => ['key', 'version', 'deployment id'],
                    'preventInSource' => ['de' => 'Controlled deployment pipeline; semantic versioning of BPMN models.', 'en' => 'Controlled deployment pipeline; semantic versioning of BPMN models.'],
                    'resolveInWarehouse' => ['de' => 'Canonical process key → version SCD2 map.', 'en' => 'Canonical process key → version SCD2 map.'],
                    'survivorship' => ['de' => 'Neueste deployte Version je Key gewinnt für Live-Dashboards.', 'en' => 'The latest deployed version per key wins for live dashboards.'],
                ],
                [
                    'id' => 'camunda-assignee-dup',
                    'entity' => 'Task assignee',
                    'title' => ['de' => 'Assignee-Duplikate / User-ID-Drift', 'en' => 'Assignee duplicates / user id drift'],
                    'matchKeys' => ['user id', 'email (hashed)'],
                    'preventInSource' => ['de' => 'Identity provider as source of truth for assignee ids.', 'en' => 'Identity provider as source of truth for assignee ids.'],
                    'resolveInWarehouse' => ['de' => 'Golden user id; email-hash merge map.', 'en' => 'Golden user id; email-hash merge map.'],
                    'survivorship' => ['de' => 'Aktiver User mit neuester Task-Activity gewinnt.', 'en' => 'Active user with latest task activity wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'camunda-escalation-timers',
                    'area' => ['de' => 'Modeler → Timer boundary events', 'en' => 'Modeler → Timer boundary events'],
                    'setting' => ['de' => 'Escalation-Timer für kritische User Tasks standardisieren', 'en' => 'Standardize escalation timers for critical user tasks'],
                    'why' => ['de' => 'SLA-Compliance wird messbar und Overdue-Tasks werden sichtbar.', 'en' => 'SLA compliance becomes measurable and overdue tasks become visible.'],
                    'how' => ['de' => 'Model timer boundary events; document escalation targets.', 'en' => 'Model timer boundary events; document escalation targets.'],
                ],
                [
                    'id' => 'camunda-retry-dead-letter',
                    'area' => ['de' => 'Operate → External tasks / Incidents', 'en' => 'Operate → External tasks / Incidents'],
                    'setting' => ['de' => 'Retry-Policy und Dead-Letter-Handling für External Tasks', 'en' => 'Retry policy and dead-letter handling for external tasks'],
                    'why' => ['de' => 'Verhindert stille Prozess-Blockaden bei erschöpften Retries.', 'en' => 'Prevents silent process blockages when retries are exhausted.'],
                    'how' => ['de' => 'Configure retry count/backoff; alert on retries=0.', 'en' => 'Configure retry count/backoff; alert on retries=0.'],
                ],
                [
                    'id' => 'camunda-variable-classification',
                    'area' => ['de' => 'Governance → Variable naming conventions', 'en' => 'Governance → Variable naming conventions'],
                    'setting' => ['de' => 'Naming-Konvention für PII-tragende Process-Variablen', 'en' => 'Naming convention for PII-carrying process variables'],
                    'why' => ['de' => 'Erlaubt automatisiertes PII-Scanning und Extract-Allowlisting.', 'en' => 'Enables automated PII scanning and extract allowlisting.'],
                    'how' => ['de' => 'Prefix/suffix convention (e.g. _pii); document in BPMN model metadata.', 'en' => 'Prefix/suffix convention (e.g. _pii); document in BPMN model metadata.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'camunda-rest-api-schema',
                    'kind' => ['de' => 'REST API schema', 'en' => 'REST API schema'],
                    'where' => ['de' => 'Camunda Platform Docs → REST API reference (process-instance, task, incident)', 'en' => 'Camunda Platform Docs → REST API reference (process-instance, task, incident)'],
                    'how' => ['de' => 'Endpoint-Felder inventarisieren; Select-Allowlist für History API.', 'en' => 'Inventory endpoint fields; select allowlist for the history API.'],
                    'useFor' => ['de' => 'Extract design, PII tags, Join-Keys (instance, task, incident).', 'en' => 'Extract design, PII tags, join keys (instance, task, incident).'],
                    'watchouts' => ['de' => 'Variable-Value-Felder nie ungeprüft in Bulk selektieren.', 'en' => 'Never select variable value fields in bulk without review.'],
                ],
                [
                    'id' => 'camunda-bpmn-model-repository',
                    'kind' => ['de' => 'BPMN model repository', 'en' => 'BPMN model repository'],
                    'where' => ['de' => 'Modeler / Deployment repository — BPMN XML files', 'en' => 'Modeler / deployment repository — BPMN XML files'],
                    'how' => ['de' => 'Task-Definition-Keys und Flow-Struktur je Process dokumentieren.', 'en' => 'Document task definition keys and flow structure per process.'],
                    'useFor' => ['de' => 'Task dim, bottleneck analysis, stage-like groupings.', 'en' => 'Task dim, bottleneck analysis, stage-like groupings.'],
                    'watchouts' => ['de' => 'Key-Renames zwischen Versionen können Historie brechen — Mapping pflegen.', 'en' => 'Key renames between versions can break history — maintain a mapping.'],
                ],
                [
                    'id' => 'camunda-dmn-schema',
                    'kind' => ['de' => 'DMN decision schema', 'en' => 'DMN decision schema'],
                    'where' => ['de' => 'Modeler → DMN tables; Decision Definition API', 'en' => 'Modeler → DMN tables; Decision Definition API'],
                    'how' => ['de' => 'Decision-Key und Output-Kategorien dokumentieren — Input/Output-Payload meiden.', 'en' => 'Document decision key and output categories — avoid input/output payload.'],
                    'useFor' => ['de' => 'Decision-outcome dims, rule-hit tracking.', 'en' => 'Decision-outcome dims, rule-hit tracking.'],
                    'watchouts' => ['de' => 'DMN Input/Output kann Geschäftsdaten enthalten — nur Outcome-Kategorie extrahieren.', 'en' => 'DMN input/output can contain business data — extract only the outcome category.'],
                ],
                [
                    'id' => 'camunda-optimize-metadata',
                    'kind' => ['de' => 'Optimize metadata', 'en' => 'Optimize metadata'],
                    'where' => ['de' => 'Camunda Optimize → Reports / process definitions', 'en' => 'Camunda Optimize → Reports / process definitions'],
                    'how' => ['de' => 'Vorhandene Optimize-Reports als Referenz für Standard-KPIs nutzen.', 'en' => 'Use existing Optimize reports as a reference for standard KPIs.'],
                    'useFor' => ['de' => 'Cycle-time benchmarks, bottleneck detection.', 'en' => 'Cycle-time benchmarks, bottleneck detection.'],
                    'watchouts' => ['de' => 'Optimize Exports können Variable-Values mitziehen — Feldwahl prüfen.', 'en' => 'Optimize exports can pull in variable values — review field selection.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],

    'epic' => [
        'quality' => [
            'dq' => [
                [
                    'id' => 'epic-encounter-no-patient',
                    'priority' => 'high',
                    'title' => ['de' => 'Encounter ohne Patient-Referenz', 'en' => 'Encounter without a patient reference'],
                    'problem' => ['de' => 'Encounters ohne (tokenisierte) patientId brechen alle Patient-Level-Aggregationen.', 'en' => 'Encounters without a (tokenized) patientId break all patient-level aggregations.'],
                    'prevent' => ['de' => 'FHIR extract: Patient-Reference Pflichtfeld; Tokenisierung vor Landing sicherstellen.', 'en' => 'FHIR extract: patient reference required; ensure tokenization before landing.'],
                    'staffNeedToKnow' => ['de' => 'Data: Encounter ohne Patient-Link ist Extract-Fehler — sofort melden.', 'en' => 'Data: Encounter without a patient link is an extract error — report immediately.'],
                    'checks' => ['de' => 'encounter.patient_id IS NULL', 'en' => 'encounter.patient_id IS NULL'],
                    'fixInSource' => ['de' => 'Re-extract with patient reference; verify tokenization service.', 'en' => 'Re-extract with patient reference; verify the tokenization service.'],
                    'fixInWarehouse' => ['de' => 'Quarantine in restricted PHI-review area; never expose to broad marts.', 'en' => 'Quarantine in a restricted PHI-review area; never expose to broad marts.'],
                ],
                [
                    'id' => 'epic-diagnosis-code-invalid',
                    'priority' => 'high',
                    'title' => ['de' => 'Ungültiger ICD-Code', 'en' => 'Invalid ICD code'],
                    'problem' => ['de' => 'Nicht in der ICD-Codetabelle vorhandene Codes verzerren Diagnosis-Frequency-Aggregate.', 'en' => 'Codes not present in the ICD code table distort diagnosis-frequency aggregates.'],
                    'prevent' => ['de' => 'Codeset-Validierung bei Diagnose-Erfassung im EHR.', 'en' => 'Code-set validation at diagnosis capture time in the EHR.'],
                    'staffNeedToKnow' => ['de' => 'HIM/Coding: Nur gültige, aktuelle ICD-10-Codes verwenden.', 'en' => 'HIM/coding: Use only valid, current ICD-10 codes.'],
                    'checks' => ['de' => 'diagnosis_code.icd_code NOT IN ref_icd_codeset', 'en' => 'diagnosis_code.icd_code NOT IN ref_icd_codeset'],
                    'fixInSource' => ['de' => 'Correct coding in source; re-extract.', 'en' => 'Correct coding in the source; re-extract.'],
                    'fixInWarehouse' => ['de' => 'Quarantine invalid codes; exclude from frequency aggregates.', 'en' => 'Quarantine invalid codes; exclude from frequency aggregates.'],
                ],
                [
                    'id' => 'epic-appointment-status-inconsistent',
                    'priority' => 'medium',
                    'title' => ['de' => 'Appointment Status inkonsistent mit Encounter', 'en' => 'Appointment status inconsistent with encounter'],
                    'problem' => ['de' => 'status=arrived ohne resultierenden Encounter verzerrt Completed- und No-Show-KPIs.', 'en' => 'status=arrived without a resulting encounter distorts completed and no-show KPIs.'],
                    'prevent' => ['de' => 'Check-in-zu-Encounter-Workflow im Scheduling-System validieren.', 'en' => 'Validate the check-in-to-encounter workflow in the scheduling system.'],
                    'staffNeedToKnow' => ['de' => 'Front Desk: Check-in muss konsistent zum Encounter-Create führen.', 'en' => 'Front desk: Check-in must consistently lead to encounter creation.'],
                    'checks' => ['de' => "appointment.status = 'arrived' AND appointment.id NOT IN (SELECT appointment_id FROM encounter)", 'en' => "appointment.status = 'arrived' AND appointment.id NOT IN (SELECT appointment_id FROM encounter)"],
                    'fixInSource' => ['de' => 'Investigate scheduling-to-encounter integration.', 'en' => 'Investigate the scheduling-to-encounter integration.'],
                    'fixInWarehouse' => ['de' => 'Flag status_inconsistency; exclude from completed-appointment KPI until resolved.', 'en' => 'Flag status_inconsistency; exclude from the completed-appointment KPI until resolved.'],
                ],
                [
                    'id' => 'epic-low-cell-diagnosis-aggregate',
                    'priority' => 'high',
                    'title' => ['de' => 'Diagnosis-Aggregat unter k-Anonymitäts-Schwelle', 'en' => 'Diagnosis aggregate below the k-anonymity threshold'],
                    'problem' => ['de' => 'Aggregate mit sehr kleiner Fallzahl ermöglichen Re-Identifikation einzelner Patienten.', 'en' => 'Aggregates with a very small case count enable re-identification of individual patients.'],
                    'prevent' => ['de' => 'k-Anonymity-Threshold in jeder Diagnosis/Procedure-Aggregation erzwingen.', 'en' => 'Enforce a k-anonymity threshold in every diagnosis/procedure aggregation.'],
                    'staffNeedToKnow' => ['de' => 'Privacy/Compliance: Kleine Zellen (< k) nie veröffentlichen.', 'en' => 'Privacy/compliance: Never publish small cells (< k).'],
                    'checks' => ['de' => 'COUNT(*) GROUP BY icd_code, department_id HAVING COUNT < :k_anonymity_threshold', 'en' => 'COUNT(*) GROUP BY icd_code, department_id HAVING COUNT < :k_anonymity_threshold'],
                    'fixInSource' => ['de' => 'n/a — Kontrolle liegt in der Aggregations-/Publishing-Logik.', 'en' => 'n/a — control lives in the aggregation/publishing logic.'],
                    'fixInWarehouse' => ['de' => 'Suppress or roll up small cells to a higher category level.', 'en' => 'Suppress or roll up small cells to a higher category level.'],
                ],
                [
                    'id' => 'epic-provider-npi-invalid',
                    'priority' => 'medium',
                    'title' => ['de' => 'Provider mit ungültiger NPI', 'en' => 'Provider with an invalid NPI'],
                    'problem' => ['de' => 'Ungültige/fehlende NPI bricht externe Provider-Referenz-Joins (z. B. NPPES).', 'en' => 'Invalid/missing NPI breaks external provider reference joins (e.g. NPPES).'],
                    'prevent' => ['de' => 'NPI-Validierung (Luhn-Check) bei Provider-Onboarding.', 'en' => 'NPI validation (Luhn check) at provider onboarding.'],
                    'staffNeedToKnow' => ['de' => 'Credentialing: NPI vor Go-live validieren.', 'en' => 'Credentialing: Validate NPI before go-live.'],
                    'checks' => ['de' => "provider.npi IS NULL OR LENGTH(provider.npi) <> 10", 'en' => "provider.npi IS NULL OR LENGTH(provider.npi) <> 10"],
                    'fixInSource' => ['de' => 'Correct/verify NPI in provider directory.', 'en' => 'Correct/verify the NPI in the provider directory.'],
                    'fixInWarehouse' => ['de' => 'Flag invalid_npi; exclude from external reference joins.', 'en' => 'Flag invalid_npi; exclude from external reference joins.'],
                ],
            ],
            'mdm' => [
                [
                    'id' => 'epic-patient-dup',
                    'entity' => 'Patient',
                    'title' => ['de' => 'Patient-Duplikate (Enterprise Master Patient Index)', 'en' => 'Patient duplicates (enterprise master patient index)'],
                    'matchKeys' => ['MRN (tokenized)', 'EMPI id', 'FHIR patient id'],
                    'preventInSource' => ['de' => 'EMPI/MPI als Source of Truth; strikte Registrierungs-Validierung.', 'en' => 'EMPI/MPI as source of truth; strict registration validation.'],
                    'resolveInWarehouse' => ['de' => 'Golden tokenized patient id über EMPI-Merge-Events.', 'en' => 'Golden tokenized patient id via EMPI merge events.'],
                    'survivorship' => ['de' => 'EMPI-Golden-Record gewinnt; lokale MRNs als Aliases (tokenisiert).', 'en' => 'EMPI golden record wins; local MRNs as aliases (tokenized).'],
                ],
                [
                    'id' => 'epic-provider-npi-map',
                    'entity' => 'Provider',
                    'title' => ['de' => 'Provider NPI Mapping Drift', 'en' => 'Provider NPI mapping drift'],
                    'matchKeys' => ['npi', 'provider id', 'department id'],
                    'preventInSource' => ['de' => 'Credentialing-Prozess als Source of Truth; NPI-Validierung erzwingen.', 'en' => 'Credentialing process as source of truth; enforce NPI validation.'],
                    'resolveInWarehouse' => ['de' => 'Canonical provider id → NPI SCD2 map.', 'en' => 'Canonical provider id → NPI SCD2 map.'],
                    'survivorship' => ['de' => 'Aktueller Credentialing-Stand gewinnt.', 'en' => 'Current credentialing record wins.'],
                ],
            ],
            'productSettings' => [
                [
                    'id' => 'epic-empi-governance',
                    'area' => ['de' => 'Identity → Enterprise Master Patient Index', 'en' => 'Identity → Enterprise master patient index'],
                    'setting' => ['de' => 'EMPI Merge/Unmerge Governance und Tokenisierungs-Service', 'en' => 'EMPI merge/unmerge governance and the tokenization service'],
                    'why' => ['de' => 'Grundlage für konsistente, PHI-sichere Patient-Identifiers im Warehouse.', 'en' => 'Foundation for consistent, PHI-safe patient identifiers in the warehouse.'],
                    'how' => ['de' => 'Document merge/unmerge process; propagate to tokenized id crosswalk.', 'en' => 'Document the merge/unmerge process; propagate to the tokenized id crosswalk.'],
                ],
                [
                    'id' => 'epic-k-anonymity-policy',
                    'area' => ['de' => 'Privacy/Compliance → Reporting policy', 'en' => 'Privacy/compliance → Reporting policy'],
                    'setting' => ['de' => 'k-Anonymity-Threshold für alle Diagnosis-/Procedure-Aggregate festlegen', 'en' => 'Set a k-anonymity threshold for all diagnosis/procedure aggregates'],
                    'why' => ['de' => 'Verhindert Re-Identifikation über kleine Zellen in Reports.', 'en' => 'Prevents re-identification via small cells in reports.'],
                    'how' => ['de' => 'Define threshold (e.g. k=11 per common standard); enforce in publishing layer.', 'en' => 'Define a threshold (e.g. k=11 per common standard); enforce in the publishing layer.'],
                ],
                [
                    'id' => 'epic-interface-retention',
                    'area' => ['de' => 'Interoperability → Interface engine retention', 'en' => 'Interoperability → Interface engine retention'],
                    'setting' => ['de' => 'Kurze Retention für HL7/FHIR Message Queues in der Interface Engine', 'en' => 'Short retention for HL7/FHIR message queues in the interface engine'],
                    'why' => ['de' => 'Reduziert das PHI-Exposure-Fenster außerhalb des EHR-Systems.', 'en' => 'Reduces the PHI exposure window outside the EHR system.'],
                    'how' => ['de' => 'Configure queue TTL; audit message store access.', 'en' => 'Configure queue TTL; audit message store access.'],
                ],
            ],
            'metadata' => [
                [
                    'id' => 'epic-fhir-us-core',
                    'kind' => ['de' => 'FHIR US Core profiles', 'en' => 'FHIR US Core profiles'],
                    'where' => ['de' => 'Epic on FHIR → US Core / Argonaut implementation guides', 'en' => 'Epic on FHIR → US Core / Argonaut implementation guides'],
                    'how' => ['de' => 'Resource-Felder (Patient, Encounter, Appointment) inventarisieren; Allowlist definieren.', 'en' => 'Inventory resource fields (Patient, Encounter, Appointment); define an allowlist.'],
                    'useFor' => ['de' => 'Extract design, PHI tags, Join-Keys (tokenized patient, encounter).', 'en' => 'Extract design, PHI tags, join keys (tokenized patient, encounter).'],
                    'watchouts' => ['de' => 'DocumentReference/Observation.note nie in den Select aufnehmen.', 'en' => 'Never include DocumentReference/Observation.note in the select.'],
                ],
                [
                    'id' => 'epic-clarity-caboodle-schema',
                    'kind' => ['de' => 'Clarity / Caboodle reporting schema', 'en' => 'Clarity / Caboodle reporting schema'],
                    'where' => ['de' => 'Epic UserWeb → Clarity data model / Caboodle dimensional model docs', 'en' => 'Epic UserWeb → Clarity data model / Caboodle dimensional model docs'],
                    'how' => ['de' => 'Bestehende Reporting-Tabellen als Feld-Referenz für Meta-Aggregate nutzen.', 'en' => 'Use existing reporting tables as a field reference for metadata aggregates.'],
                    'useFor' => ['de' => 'Encounter/appointment facts, department/provider dims.', 'en' => 'Encounter/appointment facts, department/provider dims.'],
                    'watchouts' => ['de' => 'Clarity-Tabellen enthalten volle PHI — nur Meta-Spalten für das Analytics-Warehouse selektieren.', 'en' => 'Clarity tables contain full PHI — select only meta columns for the analytics warehouse.'],
                ],
                [
                    'id' => 'epic-icd-cpt-codesets',
                    'kind' => ['de' => 'ICD-10 / CPT code sets', 'en' => 'ICD-10 / CPT code sets'],
                    'where' => ['de' => 'CMS ICD-10-CM/PCS files; AMA CPT code set (licensed)', 'en' => 'CMS ICD-10-CM/PCS files; AMA CPT code set (licensed)'],
                    'how' => ['de' => 'Referenz-Codesets für Validierung und Kategorie-Rollups pflegen.', 'en' => 'Maintain reference code sets for validation and category rollups.'],
                    'useFor' => ['de' => 'Diagnosis/procedure dims, code validation DQ, category-level aggregates.', 'en' => 'Diagnosis/procedure dims, code-validation DQ, category-level aggregates.'],
                    'watchouts' => ['de' => 'CPT ist lizenzpflichtig (AMA) — Nutzung im Warehouse rechtlich klären.', 'en' => 'CPT is licensed (AMA) — clarify legal use in the warehouse.'],
                ],
                [
                    'id' => 'epic-interconnect-interface-schema',
                    'kind' => ['de' => 'Interconnect / interface engine schema', 'en' => 'Interconnect / interface engine schema'],
                    'where' => ['de' => 'Epic Interconnect / HL7 interface engine (Rhapsody, Mirth) message specs', 'en' => 'Epic Interconnect / HL7 interface engine (Rhapsody, Mirth) message specs'],
                    'how' => ['de' => 'Message-Typen (ADT, SIU, ORU) und relevante Segmente für Meta-Extract dokumentieren.', 'en' => 'Document message types (ADT, SIU, ORU) and relevant segments for meta extraction.'],
                    'useFor' => ['de' => 'Near-real-time encounter/appointment facts.', 'en' => 'Near-real-time encounter/appointment facts.'],
                    'watchouts' => ['de' => 'HL7-Segmente bündeln oft volle PHI — nur Allowlist-Felder aus dem Message-Parsing extrahieren.', 'en' => 'HL7 segments often bundle full PHI — extract only allowlisted fields from message parsing.'],
                ],
            ],
        ],
        'tools' => [
            'dbt-dq-rules-generator',
            'dbt-dq-macro-generator',
            'dbt-dq-history-generator',
            'schema-yml-editor',
        ],
    ],
];
