import { getLocale } from '../../locale';

const labels = {
    de: {
        'lakehouseDq.fabric.pageTitle': 'Fabric DQ Pattern Generator',
        'lakehouseDq.fabric.lead': 'Erzeugt SQL- und Notebook-Patterns fuer Fabric Lakehouse/Warehouse: DQ-Regeln, Delta Loads, SCD2 und Pipeline-Gates.',
        'lakehouseDq.fabricPii.pageTitle': 'Fabric PII Governance Pattern Generator',
        'lakehouseDq.fabricPii.lead': 'Erzeugt Fabric-Patterns fuer PII-Klassifikation, Sensitive Labels, Rollen, Maskierung und Governance-Gates.',
        'lakehouseDq.fabricDqRule.pageTitle': 'Fabric DQ Rule Generator',
        'lakehouseDq.fabricDqRule.lead': 'Erzeugt konkrete Fabric SQL- und Notebook-Regeln fuer Pflichtfelder, Business Keys und Freshness.',
        'lakehouseDq.fabricNotebook.pageTitle': 'Fabric Notebook Snippet Generator',
        'lakehouseDq.fabricNotebook.lead': 'Erzeugt kopierbare Fabric Notebook-Snippets fuer DQ, Delta Loads, SCD2 und Governance Reviews.',
        'lakehouseDq.fabricPipeline.pageTitle': 'Fabric Pipeline Checklist Generator',
        'lakehouseDq.fabricPipeline.lead': 'Erzeugt eine Fabric Pipeline-Checkliste mit Gates fuer Incremental Load, Alerts, Owner und Semantic Refresh.',
        'lakehouseDq.fabricSemantic.pageTitle': 'Fabric Semantic Model Guardrails',
        'lakehouseDq.fabricSemantic.lead': 'Erzeugt Guardrails fuer Fabric Semantic Models: Felder verstecken, KPI-Owner, Export-Risiko und Publishing-Gate.',
        'lakehouseDq.databricks.pageTitle': 'Databricks DQ Pattern Generator',
        'lakehouseDq.databricks.lead': 'Erzeugt DLT Expectations, Delta MERGE/SCD2 und Unity-Catalog-Governance-Patterns fuer Databricks.',
        'lakehouseDq.databricksPii.pageTitle': 'Databricks PII Governance Pattern Generator',
        'lakehouseDq.databricksPii.lead': 'Erzeugt Unity-Catalog-Patterns fuer PII-Tags, Owner, Grants, Maskierung und Governance-Gates.',
        'lakehouseDq.databricksDqExpectation.pageTitle': 'Databricks DQ Expectation Generator',
        'lakehouseDq.databricksDqExpectation.lead': 'Erzeugt DLT Expectations und Notebook-Checks fuer Pflichtfelder, Keys und Freshness in Databricks.',
        'lakehouseDq.databricksDbt.pageTitle': 'Databricks dbt-on-Databricks Generator',
        'lakehouseDq.databricksDbt.lead': 'Erzeugt dbt-on-Databricks Starter-Snippets fuer Incremental Models, Tests, Jobs und Unity-Catalog-Handoff.',
        'lakehouseDq.unityCatalog.pageTitle': 'Unity Catalog Governance Generator',
        'lakehouseDq.unityCatalog.lead': 'Erzeugt Unity-Catalog-Governance-Snippets fuer Tags, Owner, Grants, PII-Spalten und Release-Gates.',
        'lakehouseDq.deltaScd.pageTitle': 'Delta Load / SCD Pattern Generator',
        'lakehouseDq.deltaScd.lead': 'Erzeugt Delta MERGE- und SCD2-Patterns fuer inkrementelle Lakehouse-Modelle.',
        'lakehouseDq.howto.summary': 'Hilfe',
        'lakehouseDq.fabric.howto.intro': 'Nutze den Generator, um aus wenigen Modelldaten ein kopierbares Fabric-Pattern zu erzeugen.',
        'lakehouseDq.fabricPii.howto.intro': 'Nutze den Generator, um aus PII-Feldern, Ownern und Schluesseln ein kopierbares Fabric-Governance-Pattern zu erzeugen.',
        'lakehouseDq.fabricDqRule.howto.intro': 'Nutze den Generator, um Fabric DQ-Regeln fuer Modell- oder App-Release-Gates vorzubereiten.',
        'lakehouseDq.fabricNotebook.howto.intro': 'Nutze den Generator, um schnell ein Fabric Notebook-Snippet fuer Checks, Loads oder Governance zu erzeugen.',
        'lakehouseDq.fabricPipeline.howto.intro': 'Nutze den Generator, um Pipeline-Gates, Owner, Retry- und Alert-Punkte fuer Fabric festzuhalten.',
        'lakehouseDq.fabricSemantic.howto.intro': 'Nutze den Generator, um Guardrails fuer das Semantic Model vor App-Publishing zu definieren.',
        'lakehouseDq.databricks.howto.intro': 'Nutze den Generator, um aus wenigen Modelldaten ein kopierbares Databricks-Pattern zu erzeugen.',
        'lakehouseDq.databricksPii.howto.intro': 'Nutze den Generator, um aus PII-Feldern, Ownern und Schluesseln ein kopierbares Unity-Catalog-Governance-Pattern zu erzeugen.',
        'lakehouseDq.databricksDqExpectation.howto.intro': 'Nutze den Generator, um DLT Expectations und Notebook-Checks fuer Databricks vorzubereiten.',
        'lakehouseDq.databricksDbt.howto.intro': 'Nutze den Generator, um dbt-on-Databricks Setup, Incremental Model und Job-Handoff vorzubereiten.',
        'lakehouseDq.unityCatalog.howto.intro': 'Nutze den Generator, um Unity-Catalog-Tags, Grants und Governance-Gates aus Modelldaten abzuleiten.',
        'lakehouseDq.deltaScd.howto.intro': 'Nutze den Generator, um Delta MERGE oder SCD2 als Startpattern fuer ein Lakehouse-Modell zu erzeugen.',
        'lakehouseDq.howto.step1': 'Trage Tabelle, Schluessel, Pflichtfelder, Freshness-Spalte und Owner ein.',
        'lakehouseDq.howto.step2': 'Waehle, ob du DQ, Delta Load, SCD2 oder Governance vorbereiten willst.',
        'lakehouseDq.howto.step3': 'Kopiere SQL, Notebook-Snippet oder Runbook in dein Projekt und passe Namen/Policies final an.',
        'lakehouseDq.fabric.howto.tip': 'Die Ausgabe ist bewusst ein Startpunkt fuer Fabric Pipelines, Notebooks und Warehouse Checks, kein Live-Deployment.',
        'lakehouseDq.fabricPii.howto.tip': 'Die Ausgabe ist bewusst ein Startpunkt fuer Fabric Sensitivity Labels, Rollenreviews und Pipeline-Gates, kein Live-Deployment.',
        'lakehouseDq.fabricDqRule.howto.tip': 'Die Ausgabe ist ein Startpunkt fuer Fabric Warehouse SQL, Lakehouse Checks und Review-Dokumentation.',
        'lakehouseDq.fabricNotebook.howto.tip': 'Die Notebook-Ausgabe ist fuer Copy-Paste und Review gedacht, nicht als fertiger produktiver Job.',
        'lakehouseDq.fabricPipeline.howto.tip': 'Die Runbook-Ausgabe eignet sich als Checkliste in Sprint-Aufgaben und Release-Reviews.',
        'lakehouseDq.fabricSemantic.howto.tip': 'Die Guardrails helfen, App-Publishing nicht ohne Owner-, Export- und KPI-Review freizugeben.',
        'lakehouseDq.databricks.howto.tip': 'Die Ausgabe ist bewusst ein Startpunkt fuer Databricks Jobs, DLT Pipelines und Unity Catalog, kein Live-Deployment.',
        'lakehouseDq.databricksPii.howto.tip': 'Die Ausgabe ist bewusst ein Startpunkt fuer Unity Catalog Tags, Grants und Governance-Reviews, kein Live-Deployment.',
        'lakehouseDq.databricksDqExpectation.howto.tip': 'Die Ausgabe ist ein Startpunkt fuer DLT, Jobs und technische DQ-Gates.',
        'lakehouseDq.databricksDbt.howto.tip': 'Die Ausgabe ersetzt kein dbt-Projekt, aber sie setzt die Struktur fuer Model, Tests und Job-Handoff.',
        'lakehouseDq.unityCatalog.howto.tip': 'Die Ausgabe hilft beim Review von Tags, Grants und Ownern vor breiter Freigabe.',
        'lakehouseDq.deltaScd.howto.tip': 'Waehle Delta MERGE fuer aktuelle Modelle oder SCD2 fuer historisierte Dimensionslogik.',
        'lakehouseDq.input.title': 'Pattern-Eingaben',
        'lakehouseDq.input.description': 'Diese Felder schneiden den generierten Code auf dein Modell zu.',
        'lakehouseDq.input.table': 'Zieltabelle',
        'lakehouseDq.input.keys': 'Key-Spalten',
        'lakehouseDq.input.required': 'Pflichtfelder',
        'lakehouseDq.input.freshness': 'Freshness-Spalte',
        'lakehouseDq.input.pii': 'PII/Sensitive Spalten',
        'lakehouseDq.input.owner': 'Owner / Gruppe',
        'lakehouseDq.input.pattern': 'Pattern',
        'lakehouseDq.fabric.output.sql': 'Fabric SQL Pattern',
        'lakehouseDq.fabric.output.notebook': 'Fabric Notebook Snippet',
        'lakehouseDq.databricks.output.sql': 'Databricks SQL / DLT Pattern',
        'lakehouseDq.databricks.output.notebook': 'Databricks Notebook Snippet',
        'lakehouseDq.output.runbook': 'Runbook / Checkliste',
        'lakehouseDq.copy': 'Kopieren',
        'shared.copied': 'Kopiert!',
    },
    en: {
        'lakehouseDq.fabric.pageTitle': 'Fabric DQ Pattern Generator',
        'lakehouseDq.fabric.lead': 'Generates SQL and notebook patterns for Fabric Lakehouse/Warehouse: DQ rules, Delta loads, SCD2, and pipeline gates.',
        'lakehouseDq.fabricPii.pageTitle': 'Fabric PII Governance Pattern Generator',
        'lakehouseDq.fabricPii.lead': 'Generates Fabric patterns for PII classification, sensitivity labels, roles, masking, and governance gates.',
        'lakehouseDq.fabricDqRule.pageTitle': 'Fabric DQ Rule Generator',
        'lakehouseDq.fabricDqRule.lead': 'Generates concrete Fabric SQL and notebook rules for required fields, business keys, and freshness.',
        'lakehouseDq.fabricNotebook.pageTitle': 'Fabric Notebook Snippet Generator',
        'lakehouseDq.fabricNotebook.lead': 'Generates copyable Fabric notebook snippets for DQ, Delta loads, SCD2, and governance reviews.',
        'lakehouseDq.fabricPipeline.pageTitle': 'Fabric Pipeline Checklist Generator',
        'lakehouseDq.fabricPipeline.lead': 'Generates a Fabric pipeline checklist with gates for incremental load, alerts, owners, and semantic refresh.',
        'lakehouseDq.fabricSemantic.pageTitle': 'Fabric Semantic Model Guardrails',
        'lakehouseDq.fabricSemantic.lead': 'Generates guardrails for Fabric semantic models: hidden fields, KPI owners, export risk, and publishing gates.',
        'lakehouseDq.databricks.pageTitle': 'Databricks DQ Pattern Generator',
        'lakehouseDq.databricks.lead': 'Generates DLT expectations, Delta MERGE/SCD2, and Unity Catalog governance patterns for Databricks.',
        'lakehouseDq.databricksPii.pageTitle': 'Databricks PII Governance Pattern Generator',
        'lakehouseDq.databricksPii.lead': 'Generates Unity Catalog patterns for PII tags, owners, grants, masking, and governance gates.',
        'lakehouseDq.databricksDqExpectation.pageTitle': 'Databricks DQ Expectation Generator',
        'lakehouseDq.databricksDqExpectation.lead': 'Generates DLT expectations and notebook checks for required fields, keys, and freshness in Databricks.',
        'lakehouseDq.databricksDbt.pageTitle': 'Databricks dbt-on-Databricks Generator',
        'lakehouseDq.databricksDbt.lead': 'Generates dbt-on-Databricks starter snippets for incremental models, tests, jobs, and Unity Catalog handoff.',
        'lakehouseDq.unityCatalog.pageTitle': 'Unity Catalog Governance Generator',
        'lakehouseDq.unityCatalog.lead': 'Generates Unity Catalog governance snippets for tags, owners, grants, PII columns, and release gates.',
        'lakehouseDq.deltaScd.pageTitle': 'Delta Load / SCD Pattern Generator',
        'lakehouseDq.deltaScd.lead': 'Generates Delta MERGE and SCD2 patterns for incremental lakehouse models.',
        'lakehouseDq.howto.summary': 'Help',
        'lakehouseDq.fabric.howto.intro': 'Use the generator to turn a few model inputs into a copyable Fabric pattern.',
        'lakehouseDq.fabricPii.howto.intro': 'Use the generator to turn PII fields, owners, and keys into a copyable Fabric governance pattern.',
        'lakehouseDq.fabricDqRule.howto.intro': 'Use the generator to prepare Fabric DQ rules for model or app release gates.',
        'lakehouseDq.fabricNotebook.howto.intro': 'Use the generator to quickly create a Fabric notebook snippet for checks, loads, or governance.',
        'lakehouseDq.fabricPipeline.howto.intro': 'Use the generator to capture pipeline gates, owners, retry, and alert points for Fabric.',
        'lakehouseDq.fabricSemantic.howto.intro': 'Use the generator to define semantic model guardrails before app publishing.',
        'lakehouseDq.databricks.howto.intro': 'Use the generator to turn a few model inputs into a copyable Databricks pattern.',
        'lakehouseDq.databricksPii.howto.intro': 'Use the generator to turn PII fields, owners, and keys into a copyable Unity Catalog governance pattern.',
        'lakehouseDq.databricksDqExpectation.howto.intro': 'Use the generator to prepare DLT expectations and notebook checks for Databricks.',
        'lakehouseDq.databricksDbt.howto.intro': 'Use the generator to prepare dbt-on-Databricks setup, incremental model, and job handoff.',
        'lakehouseDq.unityCatalog.howto.intro': 'Use the generator to derive Unity Catalog tags, grants, and governance gates from model inputs.',
        'lakehouseDq.deltaScd.howto.intro': 'Use the generator to create a Delta MERGE or SCD2 starter pattern for a lakehouse model.',
        'lakehouseDq.howto.step1': 'Enter table, keys, required fields, freshness column, and owner.',
        'lakehouseDq.howto.step2': 'Choose whether you want to prepare DQ, Delta load, SCD2, or governance.',
        'lakehouseDq.howto.step3': 'Copy SQL, notebook snippet, or runbook into your project and adjust names/policies before use.',
        'lakehouseDq.fabric.howto.tip': 'The output is a starting point for Fabric pipelines, notebooks, and warehouse checks, not a live deployment.',
        'lakehouseDq.fabricPii.howto.tip': 'The output is a starting point for Fabric sensitivity labels, role reviews, and pipeline gates, not a live deployment.',
        'lakehouseDq.fabricDqRule.howto.tip': 'The output is a starting point for Fabric warehouse SQL, lakehouse checks, and review documentation.',
        'lakehouseDq.fabricNotebook.howto.tip': 'The notebook output is designed for copy-paste and review, not as a finished production job.',
        'lakehouseDq.fabricPipeline.howto.tip': 'The runbook output works well as a checklist in sprint tasks and release reviews.',
        'lakehouseDq.fabricSemantic.howto.tip': 'The guardrails help avoid app publishing without owner, export, and KPI review.',
        'lakehouseDq.databricks.howto.tip': 'The output is a starting point for Databricks jobs, DLT pipelines, and Unity Catalog, not a live deployment.',
        'lakehouseDq.databricksPii.howto.tip': 'The output is a starting point for Unity Catalog tags, grants, and governance reviews, not a live deployment.',
        'lakehouseDq.databricksDqExpectation.howto.tip': 'The output is a starting point for DLT, jobs, and technical DQ gates.',
        'lakehouseDq.databricksDbt.howto.tip': 'The output does not replace a dbt project, but it sets up the structure for model, tests, and job handoff.',
        'lakehouseDq.unityCatalog.howto.tip': 'The output helps review tags, grants, and owners before broad release.',
        'lakehouseDq.deltaScd.howto.tip': 'Choose Delta MERGE for current-state models or SCD2 for historized dimension logic.',
        'lakehouseDq.input.title': 'Pattern inputs',
        'lakehouseDq.input.description': 'These fields tailor the generated code to your model.',
        'lakehouseDq.input.table': 'Target table',
        'lakehouseDq.input.keys': 'Key columns',
        'lakehouseDq.input.required': 'Required fields',
        'lakehouseDq.input.freshness': 'Freshness column',
        'lakehouseDq.input.pii': 'PII/sensitive columns',
        'lakehouseDq.input.owner': 'Owner / group',
        'lakehouseDq.input.pattern': 'Pattern',
        'lakehouseDq.fabric.output.sql': 'Fabric SQL pattern',
        'lakehouseDq.fabric.output.notebook': 'Fabric notebook snippet',
        'lakehouseDq.databricks.output.sql': 'Databricks SQL / DLT pattern',
        'lakehouseDq.databricks.output.notebook': 'Databricks notebook snippet',
        'lakehouseDq.output.runbook': 'Runbook / checklist',
        'lakehouseDq.copy': 'Copy',
        'shared.copied': 'Copied!',
    },
};

export function t(locale, key) {
    return labels[locale]?.[key] ?? labels.en[key] ?? key;
}

export function applyLakehouseDqLabels() {
    const locale = getLocale();
    document.querySelectorAll('[data-i18n]').forEach((el) => {
        const key = el.getAttribute('data-i18n');
        if (!key?.startsWith('lakehouseDq.') && !key?.startsWith('shared.')) return;
        el.textContent = t(locale, key);
    });
}
