/** @typedef {'de'|'en'} SpLocale */

/** @type {Record<SpLocale, Record<string, string>>} */
export const spLabels = {
    de: {
        'sp.pageTitle': 'Sprint Planner',
        'sp.pageLead': 'Lokale Sprint-Pläne aus Markdown-Vorlagen — Fortschritt bleibt im Browser.',
        'sp.pageLeadDemo': 'Demo-Seite: Pläne lokal ausprobieren — mit Session-Demo, optionalem Plan-Passwort oder Login zum Speichern auf dem Server.',
        'sp.pageLeadAccounts': 'Gespeicherte Pläne synchronisieren auf diesen Server. Demo-Pläne bleiben nur in der Session.',
        'sp.templatesTitle': 'Planvorlagen',
        'sp.templatesLead': 'Markdown-Vorlagen definieren wiederverwendbare Sprint-Strukturen. Beim Start entsteht eine lokale Instanz.',
        'sp.peopleTitle': 'Teams & Personen',
        'sp.peopleLead': 'Nur lokale Profile. Die aktive Person filtert „Meine Aufgaben“ — das ist keine Anmeldung.',
        'sp.peopleLeadAccounts': 'Personen und Teams kommen aus den Accounts. Verwaltung unter Konto, wenn du die Rechte hast.',
        'sp.settingsTitle': 'Plan-Einstellungen',
        'sp.nav.plans': 'Meine Pläne',
        'sp.nav.templates': 'Vorlagen',
        'sp.nav.people': 'Teams & Personen',
        'sp.localBanner': 'Lokaler Arbeitsbereich – keine Anmeldung, keine Zugriffskontrolle',
        'sp.demo.guestBanner': 'Demo-Modus — probiere einen Plan in dieser Browser-Session. Zum Speichern brauchst du lokale Login-Daten.',
        'sp.demo.signedInBanner': 'Gespeicherte Pläne synchronisieren auf diesen Server. Du kannst weiterhin einen Session-Demo-Plan starten.',
        'sp.demo.sessionBanner': 'Mögliche Wege: Session-Demo, Plan-Passwort ohne Login, oder Login zum Speichern auf dem Server.',
        'sp.demo.signIn': 'Anmelden',
        'sp.demo.badge': 'Demo (Session)',
        'sp.demo.planBanner': 'Demo-Plan — nur Session. Optional Plan-Passwort ohne Login (lokal). Zum Speichern auf dem Server brauchst du Login-Daten.',
        'sp.action.startDemo': 'Demo starten (nur Session)',
        'sp.action.startSave': 'Plan speichern',
        'sp.toast.demoStarted': 'Demo-Plan gestartet (nur Session)',
        'sp.section.activePlans': 'Aktive Pläne',
        'sp.section.templates': 'Vorlagen',
        'sp.section.archive': 'Archiv',
        'sp.overview.statusTitle': 'Aufgabenstatus',
        'sp.section.activePerson': 'Arbeiten als',
        'sp.section.people': 'Personen',
        'sp.section.teams': 'Teams',
        'sp.section.planActions': 'Plan-Aktionen',
        'sp.section.workspaceActions': 'Arbeitsbereich',
        'sp.section.password': 'Passwortschutz',
        'sp.section.sharing': 'Freigabe',
        'sp.section.template': 'Vorlage',
        'sp.template.switchNote': 'Wechsle zu einer kompatiblen Stack-Variante (gleiche Sprint-Struktur). Fortschritt bleibt erhalten.',
        'sp.field.templateVariant': 'Vorlagen-Variante',
        'sp.action.switchTemplate': 'Vorlage wechseln',
        'sp.confirm.switchTemplate': 'Vorlage wechseln? Fortschritt und Zuweisungen bleiben erhalten; Hilfe, Flows und Texte kommen aus der neuen Vorlage.',
        'sp.toast.templateSwitched': 'Vorlage gewechselt',
        'sp.error.templateMissing': 'Vorlage nicht gefunden.',
        'sp.error.templateIncompatible': 'Vorlage ist strukturell nicht kompatibel.',
        'sp.sharing.note': 'Teile diesen Plan mit Benutzern oder Teams auf dieser Instanz (Accounts-Modus).',
        'sp.sharing.users': 'Betrachter (Benutzer)',
        'sp.sharing.teams': 'Betrachter (Teams)',
        'sp.sharing.save': 'Freigabe speichern',
        'sp.sharing.saved': 'Freigabe gespeichert',
        'sp.sharing.localOnly': 'Freigaben brauchen den Accounts-Modus.',
        'sp.story.read': 'gelesen',
        'sp.story.unread': 'ungelesen',
        'sp.password.note': 'Lokaler Soft-Lock nur in diesem Browser — keine echte Zugriffskontrolle.',
        'sp.password.statusOn': 'Dieser Plan ist passwortgeschützt.',
        'sp.password.statusOff': 'Kein Passwort gesetzt.',
        'sp.password.new': 'Neues Passwort',
        'sp.password.confirm': 'Passwort bestätigen',
        'sp.password.current': 'Aktuelles Passwort',
        'sp.password.unlockTitle': 'Plan entsperren',
        'sp.password.unlockLead': 'Dieser Plan ist lokal geschützt. Bitte Passwort eingeben.',
        'sp.password.unlock': 'Entsperren',
        'sp.password.set': 'Passwort setzen',
        'sp.password.change': 'Passwort ändern',
        'sp.password.remove': 'Passwort entfernen',
        'sp.password.lockSession': 'Erneut sperren',
        'sp.password.mismatch': 'Passwörter stimmen nicht überein.',
        'sp.password.wrong': 'Falsches Passwort.',
        'sp.password.tooShort': 'Mindestens 4 Zeichen.',
        'sp.password.saved': 'Passwortschutz gespeichert',
        'sp.password.removed': 'Passwortschutz entfernt',
        'sp.password.lockedBadge': 'Geschützt',
        'sp.empty.activePlans': 'Noch keine aktiven Pläne. Starte einen unter Vorlagen.',
        'sp.empty.activePlansDemo': 'Noch kein Demo-Plan. Starte einen unter Vorlagen — er bleibt nur in diesem Browser.',
        'sp.empty.archive': 'Keine archivierten Pläne.',
        'sp.empty.templates': 'Keine Vorlagen verfügbar.',
        'sp.filter.label': 'Filter',
        'sp.filter.all': 'Alle',
        'sp.filter.mine': 'Meine Pläne',
        'sp.filter.team': 'Team-Pläne',
        'sp.filter.completed': 'Abgeschlossen',
        'sp.filter.archived': 'Archiviert',
        'sp.filter.currentWeek': 'Nur aktuelle Planwoche',
        'sp.filter.hideDone': 'Erledigte ausblenden',
        'sp.filter.openOnly': 'Nur offene Elemente',
        'sp.filter.blocked': 'Blockierte Elemente',
        'sp.filter.myTasks': 'Meine Aufgaben',
        'sp.filter.unassigned': 'Nicht zugewiesen',
        'sp.filter.assigneeGroup': 'Zuweisungsfilter',
        'sp.filter.assigneeAll': 'Alle Zuweisungen',
        'sp.filter.empty': 'Keine Aufgaben für diesen Filter.',
        'sp.filter.emptyMyAndUnassigned': '„Meine Aufgaben“ und „Nicht zugewiesen“ zusammen (UND) ergeben keine Treffer — eine Option abwählen.',
        'sp.filter.emptyMyOrUnassigned': 'Keine Treffer: Zuweisungen an andere Personen sind ausgeblendet. Filter „Meine Aufgaben“ / „Nicht zugewiesen“ abwählen.',
        'sp.filter.person': 'Person',
        'sp.filter.teamSelect': 'Team',
        'sp.filter.teamMembers': 'Teammitglieder',
        'sp.filter.status': 'Status',
        'sp.filter.priority': 'Priorität',
        'sp.filter.any': 'Beliebig',
        'sp.filter.logicLabel': 'Filter verknüpfen',
        'sp.filter.logicAnd': 'UND',
        'sp.filter.logicOr': 'ODER',
        'sp.filter.reset': 'Zurücksetzen',
        'sp.filter.activeHint': 'Filter aktiv',
        'sp.assign.personOnlyHint': 'Aufgaben gehören zu Personen. Teams hängen am Plan.',
        'sp.action.exportWorkspace': 'Workspace exportieren',
        'sp.action.import': 'Importieren',
        'sp.action.cancel': 'Abbrechen',
        'sp.action.start': 'Starten',
        'sp.action.save': 'Speichern',
        'sp.action.addPerson': 'Person hinzufügen',
        'sp.action.addTeam': 'Team hinzufügen',
        'sp.action.addSprint': 'Sprint hinzufügen',
        'sp.dialog.addSprintTitle': 'Sprint aus Vorlage',
        'sp.dialog.addSprintLead': 'Wähle zuerst eine Vorlage und den Sprint, den du übernehmen willst.',
        'sp.field.pickTemplate': 'Vorlage',
        'sp.field.pickSprint': 'Sprint aus Vorlage',
        'sp.error.pickTemplateRequired': 'Bitte Vorlage und Sprint wählen.',
        'sp.toast.sprintFromTemplate': 'Sprint aus Vorlage hinzugefügt',
        'sp.action.settings': 'Einstellungen',
        'sp.action.undo': 'Rückgängig',
        'sp.action.history': 'Verlauf',
        'sp.action.backToPlans': 'Zurück zu den Plänen',
        'sp.action.leavePlan': 'Plan verlassen',
        'sp.action.backToPlan': 'Zurück zum Plan',
        'sp.action.exportPlan': 'Plan exportieren',
        'sp.action.duplicatePlan': 'Plan duplizieren',
        'sp.action.archivePlan': 'Plan archivieren',
        'sp.action.resetPlan': 'Plan zurücksetzen',
        'sp.action.deletePlan': 'Plan löschen',
        'sp.action.clearWorkspace': 'Lokale Daten löschen',
        'sp.action.open': 'Öffnen',
        'sp.action.startPlan': 'Plan mit Vorlage starten',
        'sp.action.edit': 'Bearbeiten',
        'sp.action.duplicate': 'Duplizieren',
        'sp.action.moveUp': 'Nach oben',
        'sp.action.moveDown': 'Nach unten',
        'sp.action.delete': 'Löschen',
        'sp.action.reset': 'Zurücksetzen',
        'sp.action.archive': 'Archivieren',
        'sp.action.addTask': 'Aufgabe hinzufügen',
        'sp.action.addDeliverable': 'Deliverable hinzufügen',
        'sp.action.statusReport': 'Bericht',
        'sp.action.printReport': 'Drucken',
        'sp.action.readStories': 'Lesen',
        'sp.action.relatedStories': 'Passende Stories',
        'sp.action.pick': 'Übernehmen',
        'sp.action.pickHint': 'Diese Aufgabe für dich übernehmen',
        'sp.action.assign': 'Zuweisen',
        'sp.action.owner': 'Owner',
        'sp.action.ownerHint': 'Owner zuweisen',
        'sp.action.claimAll': 'Alle mir zuweisen',
        'sp.action.addAttachmentLink': 'Link hinzufügen',
        'sp.action.addAttachmentFile': 'Datei anhängen',
        'sp.action.removeAttachment': 'Entfernen',
        'sp.unassigned.banner': 'Alle Aufgaben sind unzugewiesen.',
        'sp.unassigned.bannerCount': '{{count}} von {{total}} Aufgaben sind unzugewiesen.',
        'sp.unassigned.needActivePerson': 'Wähle zuerst eine aktive Person unter Teams & Personen.',
        'sp.toast.claimed': 'Aufgabe übernommen',
        'sp.toast.claimedAll': 'Alle unzugewiesenen Aufgaben übernommen',
        'sp.toast.claimedAllCount': '{{count}} unzugewiesene Aufgaben übernommen',
        'sp.toast.claimedAllNone': 'Keine unzugewiesenen Aufgaben — bereits zugewiesene bleiben unverändert',
        'sp.toast.assigned': 'Zuweisung gespeichert',
        'sp.toast.assignedFilterAdjusted': 'Zuweisung gespeichert — Filter angepasst, damit die Aufgabe sichtbar bleibt',
        'sp.toast.attachmentAdded': 'Anhang hinzugefügt',
        'sp.error.activePersonMissing': 'Keine aktive Person ausgewählt.',
        'sp.error.labelRequired': 'Bitte ein Label eingeben.',
        'sp.error.attachmentTooLarge': 'Datei zu groß (max. 10 MB).',
        'sp.error.attachmentType': 'Dateityp nicht erlaubt (Bilder, PDF, Word, PowerPoint, Excel).',
        'sp.error.attachmentUpload': 'Upload fehlgeschlagen.',
        'sp.field.attachments': 'Anhänge',
        'sp.field.attachmentLinkLabel': 'Link-Bezeichnung',
        'sp.field.attachmentLinkUrl': 'URL',
        'sp.attachments.count': '{{count}} Anhang',
        'sp.attachments.countPlural': '{{count}} Anhänge',
        'sp.attachments.missingBlob': 'Datei lokal nicht verfügbar',
        'sp.dialog.startTitle': 'Plan starten',
        'sp.dialog.personTitle': 'Person',
        'sp.dialog.teamTitle': 'Team',
        'sp.dialog.sprintTitle': 'Sprint',
        'sp.dialog.itemTitle': 'Aufgabe bearbeiten',
        'sp.dialog.itemCreateTitle': 'Aufgabe hinzufügen',
        'sp.dialog.assignTitle': 'Schnell zuweisen',
        'sp.dialog.planOnlyNote': 'Nur Planfelder — Hilfetexte und Stories werden in der Vorlage gepflegt.',
        'sp.field.startDate': 'Startdatum',
        'sp.field.team': 'Team',
        'sp.field.owner': 'Besitzer',
        'sp.field.participants': 'Beteiligte',
        'sp.field.activePerson': 'Aktive Person',
        'sp.field.defaultTeam': 'Standard-Team',
        'sp.field.displayName': 'Anzeigename',
        'sp.field.shortName': 'Trigramm',
        'sp.field.color': 'Farbe',
        'sp.field.teams': 'Teams',
        'sp.field.emailOptional': 'E-Mail (optional)',
        'sp.field.role': 'Rolle',
        'sp.field.teamNameDe': 'Name (DE)',
        'sp.field.teamNameEn': 'Name (EN)',
        'sp.field.teamDescDe': 'Beschreibung (DE)',
        'sp.field.teamDescEn': 'Beschreibung (EN)',
        'sp.field.members': 'Mitglieder',
        'sp.field.currentSprint': 'Aktueller Sprint',
        'sp.field.status': 'Status',
        'sp.card.owner': 'Besitzer: {{name}}',
        'sp.card.ownerDemo': 'Demo — kein Besitzer (nur Session)',
        'sp.card.ownerLocal': 'Lokal in diesem Browser',
        'sp.card.ownerUnknown': 'Besitzer unbekannt',
        'sp.ownership.mine': 'Mein Plan',
        'sp.ownership.shared': 'Geteilt mit mir',
        'sp.ownership.demo': 'Demo (Session)',
        'sp.field.titleDe': 'Titel (DE)',
        'sp.field.titleEn': 'Titel (EN)',
        'sp.field.goalDe': 'Ziel (DE)',
        'sp.field.goalEn': 'Ziel (EN)',
        'sp.field.position': 'Position',
        'sp.field.enableNotes': 'Notizen aktivieren',
        'sp.field.labelDe': 'Bezeichnung (DE)',
        'sp.field.labelEn': 'Bezeichnung (EN)',
        'sp.field.assigneeType': 'Zuordnungstyp',
        'sp.field.assignee': 'Person',
        'sp.field.priority': 'Priorität',
        'sp.field.dueDate': 'Fällig am',
        'sp.field.plannedMinutes': 'Geplant',
        'sp.field.actualMinutes': 'Ist',
        'sp.field.customMinutes': 'Frei (Minuten)',
        'sp.field.note': 'Notiz',
        'sp.time.none': '—',
        'sp.time.custom': 'Frei…',
        'sp.time.minutes': '{{count}} Min.',
        'sp.time.hours': '{{count}} Std.',
        'sp.time.hoursDecimal': '{{count}} Std.',
        'sp.time.chipTitle': 'Geplant / Ist',
        'sp.time.varianceOver': 'Über Plan',
        'sp.time.varianceUnder': 'Unter Plan',
        'sp.time.varianceOnTrack': 'Im Plan',
        'sp.time.lastActual': 'Zuletzt: {{time}}',
        'sp.report.mode.time': 'Zeit',
        'sp.report.time': 'Zeitübersicht',
        'sp.report.timePlanned': 'Geplant gesamt',
        'sp.report.timeActual': 'Ist gesamt',
        'sp.report.timeOver': 'Über Plan',
        'sp.report.timeUnder': 'Unter Plan',
        'sp.report.colPlanned': 'Geplant',
        'sp.report.colActual': 'Ist',
        'sp.report.colDelta': 'Delta',
        'sp.report.colVariance': 'Abweichung',
        'sp.field.none': '— Keine —',
        'sp.field.sprintStories': 'Playbook-Stories (Slugs)',
        'sp.field.sprintStoriesHint': 'Ein Slug pro Zeile',
        'sp.field.sprintLinks': 'Links',
        'sp.field.linksHint': 'Label | https://… oder /tools/… (Community, Docs, Tools)',
        'sp.field.itemStories': 'Playbook-Stories (Slugs)',
        'sp.field.helpTextDe': 'Hilfetext (DE)',
        'sp.field.helpTextEn': 'Hilfetext (EN)',
        'sp.field.helpLinks': 'Hilfe-Links',
        'sp.toast.linksRejected': 'Story-/Playbook-Links entfernt — erlaubt: externe URLs und /tools/.',
        'sp.toast.toolTransferTable': 'Tool-Ergebnis in die Aufgaben-Tabelle übernommen',
        'sp.toast.toolTransferNote': 'Tool-Ergebnis in die Aufgaben-Notiz übernommen',
        'sp.toast.toolTransferMissing': 'Tool-Ergebnis konnte nicht zugeordnet werden (Aufgabe fehlt)',
        'sp.toast.toolTransferEmpty': 'Tool-Ergebnis war leer — nichts übernommen',
        'sp.field.table': 'Datentabelle',
        'sp.field.tableColumns': 'Spalten',
        'sp.field.tableColumnsHint': 'Source, Owner, Access, Consumed by',
        'sp.field.tableColumnsOnlyHint': 'Zeilen bearbeitest du unter der Aufgabe in der Planansicht.',
        'sp.field.tableInlineHint': 'Tabelle unter der Aufgabe in der Planansicht bearbeiten.',
        'sp.field.tableActions': 'Aktionen',
        'sp.filter.search': 'Suche',
        'sp.filter.searchPlaceholder': 'Aufgaben suchen…',
        'sp.filter.sidebarTitle': 'Filter',
        'sp.action.expandHeader': 'Header vergrößern',
        'sp.action.collapseHeader': 'Header verkleinern',
        'sp.flow.title': 'Ablauf',
        'sp.flow.steps': '{{count}} Schritte',
        'sp.action.expandAllSprints': 'Alle aufklappen',
        'sp.action.collapseAllSprints': 'Alle zuklappen',
        'sp.action.toggleFilters': 'Filter',
        'sp.action.showFilters': 'Filter zeigen',
        'sp.action.hideFilters': 'Filter ausblenden',
        'sp.action.expandTable': 'Liste bearbeiten',
        'sp.action.expandTableRows': 'Liste bearbeiten ({count})',
        'sp.action.collapseTable': 'Liste zuklappen',
        'sp.action.addTableRow': 'Zeile hinzufügen',
        'sp.action.exportTableCsv': 'CSV exportieren',
        'sp.action.importTableCsv': 'CSV importieren',
        'sp.table.csvImportReplaceConfirm':
            'Bestehende Tabellenzeilen durch die CSV ersetzen? (Spalten bleiben unverändert.)',
        'sp.table.csvError.empty': 'Die CSV-Datei ist leer.',
        'sp.table.csvError.no-columns': 'Diese Aufgabe hat keine Tabellenspalten.',
        'sp.table.csvError.no-matching-columns':
            'Keine passenden Spaltenköpfe gefunden — Header müssen zu den Tabellenspalten passen.',
        'sp.table.csvError.read': 'CSV-Datei konnte nicht gelesen werden.',
        'sp.report.mode.documentation': 'Dokumentation',
        'sp.field.demoCode': 'Demo-Code',
        'sp.field.blockerReason': 'Blockadegrund',
        'sp.field.dependsOn': 'Abhängig von',
        'sp.field.dependsOnHint': 'Leer = parallel; Auswahl = wartet auf Vorgänger (gleicher Sprint).',
        'sp.deps.waitingOn': 'Wartet auf: {{labels}}',
        'sp.deps.parallel': 'Parallel: keine Vorgänger in diesem Sprint',
        'sp.deps.chainWaiting': 'Kette: wartet auf Vorgänger',
        'sp.deps.chainPredecessor': 'Kette: Vorgänger für weitere Arbeit',
        'sp.deps.completePrereqs': 'Erst die Vorgänger erledigen.',
        'sp.deps.task': 'Aufgabe',
        'sp.deps.deliverable': 'Deliverable',
        'sp.error.depsCycle': 'Abhängigkeit würde einen Zyklus erzeugen.',
        'sp.error.depsInvalid': 'Ungültige Abhängigkeit.',
        'sp.help.title': 'Hilfe zur Aufgabe',
        'sp.help.open': 'Hilfe öffnen',
        'sp.help.close': 'Schließen',
        'sp.help.empty': 'Keine Hilfe hinterlegt.',
        'sp.help.story': 'Playbook',
        'sp.help.required': 'Pflicht',
        'sp.help.optional': 'Optional',
        'sp.help.requiredStories': 'Pflichtlektüre',
        'sp.help.optionalStories': 'Weiterführende Lektüre',
        'sp.help.links': 'Links',
        'sp.help.demo': 'Demo',
        'sp.help.flow': 'Ablauf',
        'sp.help.openStory': 'Playbook öffnen',
        'sp.help.markRead': 'Als gelesen markieren',
        'sp.help.requiredMustOpen': 'Pflichtlektüre: bitte die Story öffnen und durchlesen — nicht manuell abhaken.',
        'sp.notes.title': 'Notiz zur Aufgabe',
        'sp.notes.open': 'Notiz öffnen',
        'sp.notes.close': 'Schließen',
        'sp.notes.label': 'Notiz',
        'sp.notes.placeholder': 'Notiz oder Kommentar zur Aufgabe…',
        'sp.notes.hasNote': 'Notiz vorhanden',
        'sp.sprint.storiesTitle': 'Lesen zu diesem Sprint',
        'sp.blockers.title': 'Blockierte Elemente',
        'sp.blockers.titleCount': 'Blockiert ({{count}})',
        'sp.blockers.empty': 'Keine blockierten Elemente',
        'sp.blockers.noReason': 'Noch kein Blockadegrund hinterlegt.',
        'sp.blockers.addReason': 'Grund hinzufügen',
        'sp.blockers.editReason': 'Grund bearbeiten',
        'sp.blockers.addNote': 'Notiz hinzufügen',
        'sp.banner.openCount': 'Offen ({{count}})',
        'sp.banner.inProgressCount': 'In Arbeit ({{count}})',
        'sp.banner.onHoldCount': 'Pausiert ({{count}})',
        'sp.banner.blockedCount': 'Blockiert ({{count}})',
        'sp.banner.completedCount': 'Erledigt ({{count}})',
        'sp.banner.empty': 'Keine Elemente mit diesem Status',
        'sp.banner.showStatus': 'Liste anzeigen: {{status}}',
        'sp.report.title': 'Bericht',
        'sp.report.mode.executive': 'Executive (CEO)',
        'sp.report.mode.detailed': 'Detailed',
        'sp.report.progress': 'Gesamtfortschritt',
        'sp.report.currentSprint': 'Aktueller Sprint',
        'sp.report.currentGoal': 'Sprint-Ziel',
        'sp.report.blockers': 'Blockierte Elemente',
        'sp.report.topBlockers': 'Top-Blocker',
        'sp.report.thisSprint': 'Dieser Sprint — offen',
        'sp.report.unassignedCount': 'Unzugewiesen',
        'sp.report.kpiBlockers': 'Blocker',
        'sp.report.sprintProgress': 'Fortschritt je Sprint',
        'sp.report.requiredStories': 'Offene Pflichtlektüre',
        'sp.report.tasksByPerson': 'Aufgaben nach Person',
        'sp.report.itemDetails': 'Aufgaben & Deliverables',
        'sp.report.attachments': 'Anhänge',
        'sp.report.note': 'Notiz',
        'sp.report.empty': 'Keine Einträge',
        'sp.report.colSprint': 'Sprint',
        'sp.report.colItem': 'Element',
        'sp.report.colReason': 'Grund',
        'sp.report.colAssignee': 'Zugewiesen an',
        'sp.report.colStory': 'Story',
        'sp.report.colPerson': 'Person',
        'sp.report.colOpen': 'Offen',
        'sp.report.colBlocked': 'Blockiert',
        'sp.report.colCompleted': 'Erledigt',
        'sp.report.colTotal': 'Gesamt',
        'sp.report.colDue': 'Fällig',
        'sp.report.colStatus': 'Status',
        'sp.report.unassigned': 'Nicht zugewiesen',
        'sp.status.open': 'Offen',
        'sp.status.inProgress': 'In Arbeit',
        'sp.status.onHold': 'Pausiert',
        'sp.status.blocked': 'Blockiert',
        'sp.status.completed': 'Erledigt',
        'sp.status.active': 'Aktiv',
        'sp.status.archived': 'Archiviert',
        'sp.priority.low': 'Niedrig',
        'sp.priority.normal': 'Normal',
        'sp.priority.high': 'Hoch',
        'sp.priority.critical': 'Kritisch',
        'sp.assignee.person': 'Person',
        'sp.assignee.team': 'Team',
        'sp.error.planMissing': 'Dieser Plan wurde im lokalen Speicher nicht gefunden.',
        'sp.error.templateMissing': 'Vorlage „{{slug}}“ konnte nicht geladen werden.',
        'sp.recover.lead': 'Wähle die ursprüngliche Vorlage, um die Aufgaben wiederherzustellen. Fortschritt und Zuweisungen bleiben erhalten, wenn die Status-Keys noch passen.',
        'sp.recover.pickTemplate': 'Vorlage',
        'sp.recover.apply': 'Vorlage wiederherstellen',
        'sp.recover.done': 'Vorlage wiederhergestellt',
        'sp.error.storageUnavailable': 'localStorage ist nicht verfügbar.',
        'sp.error.storageFull': 'localStorage ist voll.',
        'sp.error.storageCorrupt': 'Gespeicherte Daten waren beschädigt und wurden zurückgesetzt.',
        'sp.error.importInvalid': 'Ungültige Importdatei.',
        'sp.error.importSchema': 'Nicht unterstützte Schema-Version.',
        'sp.toast.saved': 'Gespeichert',
        'sp.toast.imported': 'Import abgeschlossen',
        'sp.toast.exported': 'Export gestartet',
        'sp.toast.deleted': 'Gelöscht',
        'sp.toast.started': 'Plan gestartet',
        'sp.toast.undone': 'Änderung rückgängig gemacht',
        'sp.toast.restored': 'Plan wiederhergestellt',
        'sp.history.title': 'Planverlauf',
        'sp.history.lead': 'Letzte Änderungen mit Autor. Wiederherstellen setzt den Plan auf den Zustand vor dieser Änderung zurück.',
        'sp.history.loading': 'Verlauf wird geladen…',
        'sp.history.empty': 'Noch keine Änderungen gespeichert.',
        'sp.history.accountsOnly': 'Der Planverlauf ist im Accounts-Modus mit Login verfügbar.',
        'sp.history.loadFailed': 'Verlauf konnte nicht geladen werden.',
        'sp.history.forbidden': 'Kein Zugriff auf den Verlauf dieses Plans.',
        'sp.history.notFound': 'Plan auf dem Server nicht gefunden.',
        'sp.history.showDiff': 'Details',
        'sp.history.restore': 'Wiederherstellen',
        'sp.history.diffTitle': 'Unterschiede (aktuell vs. Snapshot)',
        'sp.history.diffEmpty': 'Keine relevanten Feldunterschiede.',
        'sp.history.diffSummary': '{{before}} → {{after}}',
        'sp.history.restoreFailed': 'Wiederherstellen fehlgeschlagen.',
        'sp.history.nothingToUndo': 'Nichts rückgängig zu machen.',
        'sp.confirm.restoreRevision': 'Plan wirklich auf diesen Stand zurücksetzen?',
        'sp.save.saving': 'Speichern…',
        'sp.save.saved': 'Gespeichert',
        'sp.save.error': 'Speichern fehlgeschlagen',
        'sp.card.duration': '{{count}} Wochen',
        'sp.card.progress': 'Fortschritt {{percent}}%',
        'sp.card.currentSprint': 'Sprint {{number}}',
        'sp.sprint.currentBadge': 'Aktuelle Planwoche',
        'sp.sprint.upcomingBadge': 'Startet bald',
        'sp.sprint.overdueBadge': 'Überfällig',
        'sp.sprint.blockedCount': 'Blockiert ({{count}})',
        'sp.sprint.inProgressCount': 'In Arbeit ({{count}})',
        'sp.sprint.onHoldCount': 'Pausiert ({{count}})',
        'sp.schedule.currentSprint': 'Sprint {{number}} · {{week}} ({{range}})',
        'sp.schedule.notStarted': 'Noch nicht gestartet · ab {{date}} ({{week}}, {{range}})',
        'sp.schedule.dueBy': 'Fällig {{date}}',
        'sp.schedule.behind': '{{weeks}} Wochen hinter Plan · {{count}} offen ({{sources}})',
        'sp.schedule.sourceSprint': 'Sprint {{number}}: {{count}}',
        'sp.schedule.onTrack': 'Im Plan',
        'sp.sprint.tasks': 'Aufgaben',
        'sp.sprint.deliverables': 'Deliverables',
        'sp.sprint.fields': 'Felder',
        'sp.sprint.notes': 'Notizen',
        'sp.confirm.deletePlan': 'Diesen Plan wirklich löschen? Das kann nicht rückgängig gemacht werden.',
        'sp.confirm.resetPlan': 'Fortschritt, Notizen und eigene Sprints dieses Plans zurücksetzen?',
        'sp.confirm.clearWorkspace': 'Alle lokalen Sprint-Planner-Daten löschen?',
        'sp.confirm.deleteSprint': 'Diesen Sprint löschen?',
        'sp.confirm.resetSprint': 'Diesen Sprint zurücksetzen?',
        'sp.confirm.deleteItem': 'Diese Aufgabe wirklich löschen? Das kann nicht rückgängig gemacht werden.',
        'sp.import.modePrompt': 'Import-Konflikt: replace = ersetzen, merge = zusammenführen, new-ids = neue IDs, cancel = abbrechen',
        'sp.unit.week': 'Woche',
        'sp.unit.weeks': 'Wochen',
        'sp.creator.title': 'Plan Creator',
        'sp.creator.lead': 'Baue einen Plan mit Sprints, Aufgaben, Hilfetext, externen Links und optionalen Tabellen.',
        'sp.creator.sprints': 'Sprints',
        'sp.creator.tasks': 'Aufgaben',
        'sp.creator.saveTemplate': 'Als Vorlage speichern',
        'sp.creator.startPlan': 'Plan starten',
        'sp.creator.new': 'Neuer Plan / Vorlage',
        'sp.creator.loginToCreate': 'Anmelden zum Erstellen',
        'sp.creator.loginRequired': 'Bitte anmelden, um Vorlagen zu speichern.',
        'sp.creator.needSprint': 'Mindestens einen Sprint anlegen.',
        'sp.creator.templateSaved': 'Vorlage gespeichert',
        'sp.creator.templateLocalOnly': 'Vorlagen speichern nur mit Login (Accounts).',
        'sp.creator.templateSaveFailed': 'Vorlage konnte nicht gespeichert werden.',
        'sp.creator.userTemplateBadge': 'Eigene Vorlage',
        'sp.creator.confirmDeleteTemplate': 'Diese Vorlage wirklich löschen?',
        'sp.field.descriptionDe': 'Beschreibung (DE)',
        'sp.field.descriptionEn': 'Beschreibung (EN)',
    },
    en: {
        'sp.pageTitle': 'Sprint Planner',
        'sp.pageLead': 'Run local sprint plans from Markdown templates — progress stays in your browser.',
        'sp.pageLeadDemo': 'Demo page: try plans locally — with a session demo, optional plan password, or sign-in to save on the server.',
        'sp.pageLeadAccounts': 'Saved plans sync to this server. Demo plans stay in the session only.',
        'sp.templatesTitle': 'Plan templates',
        'sp.templatesLead': 'Markdown templates define reusable sprint structures. Starting a plan creates a local instance.',
        'sp.peopleTitle': 'Teams & people',
        'sp.peopleLead': 'Local profiles only. Selecting an active person filters “My tasks” — it is not authentication.',
        'sp.peopleLeadAccounts': 'People and teams come from shared accounts. Manage them under Account when you have permission.',
        'sp.settingsTitle': 'Plan settings',
        'sp.nav.plans': 'My plans',
        'sp.nav.templates': 'Templates',
        'sp.nav.people': 'Teams & people',
        'sp.localBanner': 'Local workspace — no login, no access control',
        'sp.demo.guestBanner': 'Demo mode — try a plan in this browser session. Local login credentials are required to save.',
        'sp.demo.signedInBanner': 'Saved plans sync to this server. You can still start a session demo plan.',
        'sp.demo.sessionBanner': 'Options: session demo, plan password without login, or sign-in to save on the server.',
        'sp.demo.signIn': 'Sign in',
        'sp.demo.badge': 'Demo (session)',
        'sp.demo.planBanner': 'Demo plan — session only. Optional plan password without login (local). Sign in to save on the server.',
        'sp.action.startDemo': 'Start demo (session only)',
        'sp.action.startSave': 'Save plan',
        'sp.toast.demoStarted': 'Demo plan started (session only)',
        'sp.section.activePlans': 'Active plans',
        'sp.section.templates': 'Templates',
        'sp.section.archive': 'Archive',
        'sp.overview.statusTitle': 'Task status',
        'sp.section.activePerson': 'Working as',
        'sp.section.people': 'People',
        'sp.section.teams': 'Teams',
        'sp.section.planActions': 'Plan actions',
        'sp.section.workspaceActions': 'Workspace',
        'sp.section.password': 'Password protection',
        'sp.section.sharing': 'Sharing',
        'sp.section.template': 'Template',
        'sp.template.switchNote': 'Switch to a compatible stack variant (same sprint structure). Progress is kept.',
        'sp.field.templateVariant': 'Template variant',
        'sp.action.switchTemplate': 'Switch template',
        'sp.confirm.switchTemplate': 'Switch template? Progress and assignments are kept; help, flows and copy come from the new template.',
        'sp.toast.templateSwitched': 'Template switched',
        'sp.error.templateMissing': 'Template not found.',
        'sp.error.templateIncompatible': 'Template is not structurally compatible.',
        'sp.sharing.note': 'Share this plan with users or teams on this instance (accounts mode).',
        'sp.sharing.users': 'Viewer users',
        'sp.sharing.teams': 'Viewer teams',
        'sp.sharing.save': 'Save sharing',
        'sp.sharing.saved': 'Sharing saved',
        'sp.sharing.localOnly': 'Sharing requires accounts mode.',
        'sp.story.read': 'read',
        'sp.story.unread': 'unread',
        'sp.password.note': 'Local soft lock in this browser only — not real access control.',
        'sp.password.statusOn': 'This plan is password protected.',
        'sp.password.statusOff': 'No password set.',
        'sp.password.new': 'New password',
        'sp.password.confirm': 'Confirm password',
        'sp.password.current': 'Current password',
        'sp.password.unlockTitle': 'Unlock plan',
        'sp.password.unlockLead': 'This plan is locally protected. Enter the password.',
        'sp.password.unlock': 'Unlock',
        'sp.password.set': 'Set password',
        'sp.password.change': 'Change password',
        'sp.password.remove': 'Remove password',
        'sp.password.lockSession': 'Lock again',
        'sp.password.mismatch': 'Passwords do not match.',
        'sp.password.wrong': 'Wrong password.',
        'sp.password.tooShort': 'At least 4 characters.',
        'sp.password.saved': 'Password protection saved',
        'sp.password.removed': 'Password protection removed',
        'sp.password.lockedBadge': 'Protected',
        'sp.empty.activePlans': 'No active plans yet. Start one under Templates.',
        'sp.empty.activePlansDemo': 'No demo plan yet. Start one under Templates — it stays in this browser only.',
        'sp.empty.archive': 'No archived plans.',
        'sp.empty.templates': 'No templates available.',
        'sp.filter.label': 'Filter',
        'sp.filter.all': 'All',
        'sp.filter.mine': 'My plans',
        'sp.filter.team': 'Team plans',
        'sp.filter.completed': 'Completed',
        'sp.filter.archived': 'Archived',
        'sp.filter.currentWeek': 'Current plan week only',
        'sp.filter.hideDone': 'Hide completed',
        'sp.filter.openOnly': 'Open items only',
        'sp.filter.blocked': 'Blocked items',
        'sp.filter.myTasks': 'My tasks',
        'sp.filter.unassigned': 'Unassigned',
        'sp.filter.assigneeGroup': 'Assignee filter',
        'sp.filter.assigneeAll': 'All assignees',
        'sp.filter.empty': 'No tasks match these filters.',
        'sp.filter.emptyMyAndUnassigned': '“My tasks” and “Unassigned” together (AND) match nothing — turn one off.',
        'sp.filter.emptyMyOrUnassigned': 'No matches: assignments to other people are hidden. Turn off “My tasks” / “Unassigned”.',
        'sp.filter.person': 'Person',
        'sp.filter.teamSelect': 'Team',
        'sp.filter.teamMembers': 'Team members',
        'sp.filter.status': 'Status',
        'sp.filter.priority': 'Priority',
        'sp.filter.any': 'Any',
        'sp.filter.logicLabel': 'Combine filters',
        'sp.filter.logicAnd': 'AND',
        'sp.filter.logicOr': 'OR',
        'sp.filter.reset': 'Reset',
        'sp.filter.activeHint': 'Filters active',
        'sp.assign.personOnlyHint': 'Tasks are assigned to people. Teams belong on the plan.',
        'sp.action.exportWorkspace': 'Export workspace',
        'sp.action.import': 'Import',
        'sp.action.cancel': 'Cancel',
        'sp.action.start': 'Start',
        'sp.action.save': 'Save',
        'sp.action.addPerson': 'Add person',
        'sp.action.addTeam': 'Add team',
        'sp.action.addSprint': 'Add sprint',
        'sp.dialog.addSprintTitle': 'Sprint from template',
        'sp.dialog.addSprintLead': 'Choose a template first, then the sprint to copy into this plan.',
        'sp.field.pickTemplate': 'Template',
        'sp.field.pickSprint': 'Sprint from template',
        'sp.error.pickTemplateRequired': 'Please choose a template and sprint.',
        'sp.toast.sprintFromTemplate': 'Sprint added from template',
        'sp.action.settings': 'Settings',
        'sp.action.undo': 'Undo',
        'sp.action.history': 'History',
        'sp.action.backToPlans': 'Back to plans',
        'sp.action.leavePlan': 'Leave plan',
        'sp.action.backToPlan': 'Back to plan',
        'sp.action.exportPlan': 'Export plan',
        'sp.action.duplicatePlan': 'Duplicate plan',
        'sp.action.archivePlan': 'Archive plan',
        'sp.action.resetPlan': 'Reset plan',
        'sp.action.deletePlan': 'Delete plan',
        'sp.action.clearWorkspace': 'Clear local data',
        'sp.action.open': 'Open',
        'sp.action.startPlan': 'Start plan with template',
        'sp.action.edit': 'Edit',
        'sp.action.duplicate': 'Duplicate',
        'sp.action.moveUp': 'Move up',
        'sp.action.moveDown': 'Move down',
        'sp.action.delete': 'Delete',
        'sp.action.reset': 'Reset',
        'sp.action.archive': 'Archive',
        'sp.action.addTask': 'Add task',
        'sp.action.addDeliverable': 'Add deliverable',
        'sp.action.statusReport': 'Report',
        'sp.action.printReport': 'Print',
        'sp.action.readStories': 'Read',
        'sp.action.relatedStories': 'Related stories',
        'sp.action.pick': 'Pick up',
        'sp.action.pickHint': 'Claim this task for yourself',
        'sp.action.assign': 'Assign',
        'sp.action.owner': 'Owner',
        'sp.action.ownerHint': 'Assign owner',
        'sp.action.claimAll': 'Claim all as me',
        'sp.action.addAttachmentLink': 'Add link',
        'sp.action.addAttachmentFile': 'Attach file',
        'sp.action.removeAttachment': 'Remove',
        'sp.unassigned.banner': 'All tasks are unassigned.',
        'sp.unassigned.bannerCount': '{{count}} of {{total}} tasks are unassigned.',
        'sp.unassigned.needActivePerson': 'Select an active person under Teams & people first.',
        'sp.toast.claimed': 'Task claimed',
        'sp.toast.claimedAll': 'All unassigned tasks claimed',
        'sp.toast.claimedAllCount': 'Claimed {{count}} unassigned tasks',
        'sp.toast.claimedAllNone': 'No unassigned tasks — existing assignments left unchanged',
        'sp.toast.assigned': 'Assignment saved',
        'sp.toast.assignedFilterAdjusted': 'Assignment saved — filters adjusted so the task stays visible',
        'sp.toast.attachmentAdded': 'Attachment added',
        'sp.error.activePersonMissing': 'No active person selected.',
        'sp.error.labelRequired': 'Please enter a label.',
        'sp.error.attachmentTooLarge': 'File too large (max 10 MB).',
        'sp.error.attachmentType': 'File type not allowed (images, PDF, Word, PowerPoint, Excel).',
        'sp.error.attachmentUpload': 'Upload failed.',
        'sp.field.attachments': 'Attachments',
        'sp.field.attachmentLinkLabel': 'Link label',
        'sp.field.attachmentLinkUrl': 'URL',
        'sp.attachments.count': '{{count}} attachment',
        'sp.attachments.countPlural': '{{count}} attachments',
        'sp.attachments.missingBlob': 'File not available locally',
        'sp.dialog.startTitle': 'Start plan',
        'sp.dialog.personTitle': 'Person',
        'sp.dialog.teamTitle': 'Team',
        'sp.dialog.sprintTitle': 'Sprint',
        'sp.dialog.itemTitle': 'Edit task',
        'sp.dialog.itemCreateTitle': 'Add task',
        'sp.dialog.assignTitle': 'Quick assign',
        'sp.dialog.planOnlyNote': 'Plan fields only — help text and stories are edited in the template.',
        'sp.field.startDate': 'Start date',
        'sp.field.team': 'Team',
        'sp.field.owner': 'Owner',
        'sp.field.participants': 'Participants',
        'sp.field.activePerson': 'Active person',
        'sp.field.defaultTeam': 'Default team',
        'sp.field.displayName': 'Display name',
        'sp.field.shortName': 'Trigram',
        'sp.field.color': 'Color',
        'sp.field.teams': 'Teams',
        'sp.field.emailOptional': 'Email (optional)',
        'sp.field.role': 'Role',
        'sp.field.teamNameDe': 'Name (DE)',
        'sp.field.teamNameEn': 'Name (EN)',
        'sp.field.teamDescDe': 'Description (DE)',
        'sp.field.teamDescEn': 'Description (EN)',
        'sp.field.members': 'Members',
        'sp.field.currentSprint': 'Current sprint',
        'sp.field.status': 'Status',
        'sp.card.owner': 'Owner: {{name}}',
        'sp.card.ownerDemo': 'Demo — no owner (session only)',
        'sp.card.ownerLocal': 'Local to this browser',
        'sp.card.ownerUnknown': 'Owner unknown',
        'sp.ownership.mine': 'My plan',
        'sp.ownership.shared': 'Shared with me',
        'sp.ownership.demo': 'Demo (session)',
        'sp.field.titleDe': 'Title (DE)',
        'sp.field.titleEn': 'Title (EN)',
        'sp.field.goalDe': 'Goal (DE)',
        'sp.field.goalEn': 'Goal (EN)',
        'sp.field.position': 'Position',
        'sp.field.enableNotes': 'Enable notes',
        'sp.field.labelDe': 'Label (DE)',
        'sp.field.labelEn': 'Label (EN)',
        'sp.field.assigneeType': 'Assignee type',
        'sp.field.assignee': 'Person',
        'sp.field.priority': 'Priority',
        'sp.field.dueDate': 'Due date',
        'sp.field.plannedMinutes': 'Planned',
        'sp.field.actualMinutes': 'Actual',
        'sp.field.customMinutes': 'Custom (minutes)',
        'sp.field.note': 'Note',
        'sp.time.none': '—',
        'sp.time.custom': 'Custom…',
        'sp.time.minutes': '{{count}} min',
        'sp.time.hours': '{{count}} h',
        'sp.time.hoursDecimal': '{{count}} h',
        'sp.time.chipTitle': 'Planned / actual',
        'sp.time.varianceOver': 'Over plan',
        'sp.time.varianceUnder': 'Under plan',
        'sp.time.varianceOnTrack': 'On track',
        'sp.time.lastActual': 'Last time: {{time}}',
        'sp.report.mode.time': 'Time',
        'sp.report.time': 'Time overview',
        'sp.report.timePlanned': 'Planned total',
        'sp.report.timeActual': 'Actual total',
        'sp.report.timeOver': 'Over plan',
        'sp.report.timeUnder': 'Under plan',
        'sp.report.colPlanned': 'Planned',
        'sp.report.colActual': 'Actual',
        'sp.report.colDelta': 'Delta',
        'sp.report.colVariance': 'Variance',
        'sp.field.none': '— None —',
        'sp.field.sprintStories': 'Playbook stories (slugs)',
        'sp.field.sprintStoriesHint': 'One slug per line',
        'sp.field.sprintLinks': 'Links',
        'sp.field.linksHint': 'Label | https://… or /tools/… (community, docs, tools)',
        'sp.field.itemStories': 'Playbook stories (slugs)',
        'sp.field.helpTextDe': 'Help text (DE)',
        'sp.field.helpTextEn': 'Help text (EN)',
        'sp.field.helpLinks': 'Help links',
        'sp.toast.linksRejected': 'Story/playbook links removed — allowed: external URLs and /tools/.',
        'sp.toast.toolTransferTable': 'Tool result applied to the task table',
        'sp.toast.toolTransferNote': 'Tool result applied to the task note',
        'sp.toast.toolTransferMissing': 'Tool result could not be matched (task missing)',
        'sp.toast.toolTransferEmpty': 'Tool result was empty — nothing applied',
        'sp.field.table': 'Data table',
        'sp.field.tableColumns': 'Columns',
        'sp.field.tableColumnsHint': 'Source, Owner, Access, Consumed by',
        'sp.field.tableColumnsOnlyHint': 'Edit rows under the task in the plan view.',
        'sp.field.tableInlineHint': 'Edit the table under the task in the plan view.',
        'sp.field.tableActions': 'Actions',
        'sp.filter.search': 'Search',
        'sp.filter.searchPlaceholder': 'Search tasks…',
        'sp.filter.sidebarTitle': 'Filters',
        'sp.action.expandHeader': 'Expand header',
        'sp.action.collapseHeader': 'Collapse header',
        'sp.flow.title': 'Flow',
        'sp.flow.steps': '{{count}} steps',
        'sp.action.expandAllSprints': 'Expand all',
        'sp.action.collapseAllSprints': 'Collapse all',
        'sp.action.toggleFilters': 'Filters',
        'sp.action.showFilters': 'Show filters',
        'sp.action.hideFilters': 'Hide filters',
        'sp.action.expandTable': 'Edit list',
        'sp.action.expandTableRows': 'Edit list ({count})',
        'sp.action.collapseTable': 'Collapse list',
        'sp.action.addTableRow': 'Add row',
        'sp.action.exportTableCsv': 'Export CSV',
        'sp.action.importTableCsv': 'Import CSV',
        'sp.table.csvImportReplaceConfirm':
            'Replace existing table rows with this CSV? (Columns stay unchanged.)',
        'sp.table.csvError.empty': 'The CSV file is empty.',
        'sp.table.csvError.no-columns': 'This task has no table columns.',
        'sp.table.csvError.no-matching-columns':
            'No matching column headers found — headers must match the table columns.',
        'sp.table.csvError.read': 'Could not read the CSV file.',
        'sp.report.mode.documentation': 'Documentation',
        'sp.field.demoCode': 'Demo code',
        'sp.field.blockerReason': 'Blocker reason',
        'sp.field.dependsOn': 'Depends on',
        'sp.field.dependsOnHint': 'Empty = parallel; selection = waits on predecessors (same sprint).',
        'sp.deps.waitingOn': 'Waiting on: {{labels}}',
        'sp.deps.parallel': 'Parallel: no predecessors in this sprint',
        'sp.deps.chainWaiting': 'Chain: waits on predecessors',
        'sp.deps.chainPredecessor': 'Chain: predecessor for later work',
        'sp.deps.completePrereqs': 'Complete predecessors first.',
        'sp.deps.task': 'Task',
        'sp.deps.deliverable': 'Deliverable',
        'sp.error.depsCycle': 'Dependency would create a cycle.',
        'sp.error.depsInvalid': 'Invalid dependency.',
        'sp.help.title': 'Task help',
        'sp.help.open': 'Open help',
        'sp.help.close': 'Close',
        'sp.help.empty': 'No help available.',
        'sp.help.story': 'Playbook',
        'sp.help.required': 'Required',
        'sp.help.optional': 'Optional',
        'sp.help.requiredStories': 'Required reading',
        'sp.help.optionalStories': 'Further reading',
        'sp.help.links': 'Links',
        'sp.help.demo': 'Demo',
        'sp.help.flow': 'Flow',
        'sp.help.openStory': 'Open playbook',
        'sp.help.markRead': 'Mark as read',
        'sp.help.requiredMustOpen': 'Required reading: open and read the story — it cannot be checked off manually.',
        'sp.notes.title': 'Task note',
        'sp.notes.open': 'Open note',
        'sp.notes.close': 'Close',
        'sp.notes.label': 'Note',
        'sp.notes.placeholder': 'Note or comment for this task…',
        'sp.notes.hasNote': 'Note present',
        'sp.sprint.storiesTitle': 'Reading for this sprint',
        'sp.blockers.title': 'Blocked items',
        'sp.blockers.titleCount': 'Blocked ({{count}})',
        'sp.blockers.empty': 'No blocked items',
        'sp.blockers.noReason': 'No blocker reason yet.',
        'sp.blockers.addReason': 'Add reason',
        'sp.blockers.editReason': 'Edit reason',
        'sp.blockers.addNote': 'Add note',
        'sp.banner.openCount': 'Open ({{count}})',
        'sp.banner.inProgressCount': 'In progress ({{count}})',
        'sp.banner.onHoldCount': 'On hold ({{count}})',
        'sp.banner.blockedCount': 'Blocked ({{count}})',
        'sp.banner.completedCount': 'Completed ({{count}})',
        'sp.banner.empty': 'No items with this status',
        'sp.banner.showStatus': 'Show list: {{status}}',
        'sp.report.title': 'Report',
        'sp.report.mode.executive': 'Executive (CEO)',
        'sp.report.mode.detailed': 'Detailed',
        'sp.report.progress': 'Overall progress',
        'sp.report.currentSprint': 'Current sprint',
        'sp.report.currentGoal': 'Sprint goal',
        'sp.report.blockers': 'Blocked items',
        'sp.report.topBlockers': 'Top blockers',
        'sp.report.thisSprint': 'This sprint — open',
        'sp.report.unassignedCount': 'Unassigned',
        'sp.report.kpiBlockers': 'Blockers',
        'sp.report.sprintProgress': 'Progress per sprint',
        'sp.report.requiredStories': 'Outstanding required reading',
        'sp.report.tasksByPerson': 'Tasks by person',
        'sp.report.itemDetails': 'Tasks & deliverables',
        'sp.report.attachments': 'Attachments',
        'sp.report.note': 'Note',
        'sp.report.empty': 'No entries',
        'sp.report.colSprint': 'Sprint',
        'sp.report.colItem': 'Item',
        'sp.report.colReason': 'Reason',
        'sp.report.colAssignee': 'Assignee',
        'sp.report.colStory': 'Story',
        'sp.report.colPerson': 'Person',
        'sp.report.colOpen': 'Open',
        'sp.report.colBlocked': 'Blocked',
        'sp.report.colCompleted': 'Completed',
        'sp.report.colTotal': 'Total',
        'sp.report.colDue': 'Due',
        'sp.report.colStatus': 'Status',
        'sp.report.unassigned': 'Unassigned',
        'sp.status.open': 'Open',
        'sp.status.inProgress': 'In progress',
        'sp.status.onHold': 'On hold',
        'sp.status.blocked': 'Blocked',
        'sp.status.completed': 'Completed',
        'sp.status.active': 'Active',
        'sp.status.archived': 'Archived',
        'sp.priority.low': 'Low',
        'sp.priority.normal': 'Normal',
        'sp.priority.high': 'High',
        'sp.priority.critical': 'Critical',
        'sp.assignee.person': 'Person',
        'sp.assignee.team': 'Team',
        'sp.error.planMissing': 'This plan was not found in local storage.',
        'sp.error.templateMissing': 'Template “{{slug}}” could not be loaded.',
        'sp.recover.lead': 'Choose the original template to restore this plan’s tasks. Progress and assignments are kept when status keys still match.',
        'sp.recover.pickTemplate': 'Template',
        'sp.recover.apply': 'Restore template',
        'sp.recover.done': 'Template restored',
        'sp.error.storageUnavailable': 'localStorage is not available.',
        'sp.error.storageFull': 'localStorage is full.',
        'sp.error.storageCorrupt': 'Stored data was corrupt and was reset.',
        'sp.error.importInvalid': 'Invalid import file.',
        'sp.error.importSchema': 'Unsupported schema version.',
        'sp.toast.saved': 'Saved',
        'sp.toast.imported': 'Import complete',
        'sp.toast.exported': 'Export started',
        'sp.toast.deleted': 'Deleted',
        'sp.toast.started': 'Plan started',
        'sp.toast.undone': 'Change undone',
        'sp.toast.restored': 'Plan restored',
        'sp.history.title': 'Plan history',
        'sp.history.lead': 'Recent changes with actor. Restore replaces the current plan with the state before that change.',
        'sp.history.loading': 'Loading history…',
        'sp.history.empty': 'No changes recorded yet.',
        'sp.history.accountsOnly': 'Plan history is available in Accounts mode when signed in.',
        'sp.history.loadFailed': 'Could not load history.',
        'sp.history.forbidden': 'You do not have access to this plan’s history.',
        'sp.history.notFound': 'Plan not found on the server.',
        'sp.history.showDiff': 'Details',
        'sp.history.restore': 'Restore',
        'sp.history.diffTitle': 'Differences (current vs snapshot)',
        'sp.history.diffEmpty': 'No relevant field differences.',
        'sp.history.diffSummary': '{{before}} → {{after}}',
        'sp.history.restoreFailed': 'Restore failed.',
        'sp.history.nothingToUndo': 'Nothing to undo.',
        'sp.confirm.restoreRevision': 'Restore the plan to this revision?',
        'sp.save.saving': 'Saving…',
        'sp.save.saved': 'Saved',
        'sp.save.error': 'Save failed',
        'sp.card.duration': '{{count}} weeks',
        'sp.card.progress': 'Progress {{percent}}%',
        'sp.card.currentSprint': 'Sprint {{number}}',
        'sp.sprint.currentBadge': 'Current plan week',
        'sp.sprint.upcomingBadge': 'Starts soon',
        'sp.sprint.overdueBadge': 'Overdue',
        'sp.sprint.blockedCount': 'Blocked ({{count}})',
        'sp.sprint.inProgressCount': 'In progress ({{count}})',
        'sp.sprint.onHoldCount': 'On hold ({{count}})',
        'sp.schedule.currentSprint': 'Sprint {{number}} · {{week}} ({{range}})',
        'sp.schedule.notStarted': 'Not started yet · from {{date}} ({{week}}, {{range}})',
        'sp.schedule.dueBy': 'Due {{date}}',
        'sp.schedule.behind': '{{weeks}} weeks behind plan · {{count}} open ({{sources}})',
        'sp.schedule.sourceSprint': 'Sprint {{number}}: {{count}}',
        'sp.schedule.onTrack': 'On track',
        'sp.sprint.tasks': 'Tasks',
        'sp.sprint.deliverables': 'Deliverables',
        'sp.sprint.fields': 'Fields',
        'sp.sprint.notes': 'Notes',
        'sp.confirm.deletePlan': 'Delete this plan? This cannot be undone.',
        'sp.confirm.resetPlan': 'Reset progress, notes, and custom sprints for this plan?',
        'sp.confirm.clearWorkspace': 'Clear all local Sprint Planner data?',
        'sp.confirm.deleteSprint': 'Delete this sprint?',
        'sp.confirm.resetSprint': 'Reset this sprint?',
        'sp.confirm.deleteItem': 'Delete this task? This cannot be undone.',
        'sp.import.modePrompt': 'Import conflict: replace, merge, new-ids, or cancel',
        'sp.unit.week': 'week',
        'sp.unit.weeks': 'weeks',
        'sp.creator.title': 'Plan Creator',
        'sp.creator.lead': 'Build a plan with sprints, tasks, help text, external links and optional data tables.',
        'sp.creator.sprints': 'Sprints',
        'sp.creator.tasks': 'Tasks',
        'sp.creator.saveTemplate': 'Save as template',
        'sp.creator.startPlan': 'Start plan',
        'sp.creator.new': 'New plan / template',
        'sp.creator.loginToCreate': 'Sign in to create templates',
        'sp.creator.loginRequired': 'Sign in to save templates.',
        'sp.creator.needSprint': 'Add at least one sprint.',
        'sp.creator.templateSaved': 'Template saved',
        'sp.creator.templateLocalOnly': 'Saving templates requires Accounts login.',
        'sp.creator.templateSaveFailed': 'Could not save template.',
        'sp.creator.userTemplateBadge': 'Your template',
        'sp.creator.confirmDeleteTemplate': 'Delete this template?',
        'sp.field.descriptionDe': 'Description (DE)',
        'sp.field.descriptionEn': 'Description (EN)',
    },
};

/**
 * @param {string} key
 * @param {SpLocale} locale
 * @param {Record<string, string|number>} [vars]
 */
export function t(key, locale, vars = {}) {
    let text = spLabels[locale]?.[key] || spLabels.en[key] || key;
    for (const [name, value] of Object.entries(vars)) {
        text = text.replaceAll(`{{${name}}}`, String(value));
    }
    return text;
}
