/** @typedef {'de'|'en'} SpLocale */

/** @type {Record<SpLocale, Record<string, string>>} */
export const spLabels = {
    de: {
        'sp.pageTitle': 'Sprint Planner',
        'sp.pageLead': 'Lokale Sprint-Pläne aus Markdown-Vorlagen — Fortschritt bleibt im Browser.',
        'sp.pageLeadDemo': 'Demo-Seite: Pläne lokal ausprobieren — mit Session-Demo, optionalem Plan-Passwort oder Login zum Speichern auf dem Server.',
        'sp.pageLeadAccounts': 'Gespeicherte Pläne synchronisieren auf diesen Server. Demo-Pläne bleiben nur in der Session.',
        'sp.templatesTitle': 'Planvorlagen',
        'sp.templatesLead': 'Markdown-Vorlagen definieren wiederverwendbare Sprint-Strukturen. Beim Start entsteht eine lokale Instanz.',
        'sp.peopleTitle': 'Teams & Personen',
        'sp.peopleLead': 'Nur lokale Profile. Die aktive Person filtert „Meine Aufgaben“ — das ist keine Anmeldung.',
        'sp.peopleLeadAccounts': 'Personen und Teams kommen aus den Accounts. Verwaltung unter Konto, wenn du die Rechte hast.',
        'sp.settingsTitle': 'Plan-Einstellungen',
        'sp.nav.plans': 'Meine Pläne',
        'sp.nav.templates': 'Vorlagen',
        'sp.nav.people': 'Teams & Personen',
        'sp.localBanner': 'Lokaler Arbeitsbereich – keine Anmeldung, keine Zugriffskontrolle',
        'sp.demo.guestBanner': 'Demo-Modus — probiere einen Plan in dieser Browser-Session. Zum Speichern brauchst du lokale Login-Daten.',
        'sp.demo.signedInBanner': 'Gespeicherte Pläne synchronisieren auf diesen Server. Du kannst weiterhin einen Session-Demo-Plan starten.',
        'sp.demo.sessionBanner': 'Mögliche Wege: Session-Demo, Plan-Passwort ohne Login, oder Login zum Speichern auf dem Server.',
        'sp.demo.signIn': 'Anmelden',
        'sp.demo.badge': 'Demo (Session)',
        'sp.demo.planBanner': 'Demo-Plan — nur Session. Optional Plan-Passwort ohne Login (lokal). Zum Speichern auf dem Server brauchst du Login-Daten.',
        'sp.action.startDemo': 'Demo starten (nur Session)',
        'sp.action.startSave': 'Plan speichern',
        'sp.toast.demoStarted': 'Demo-Plan gestartet (nur Session)',
        'sp.section.activePlans': 'Aktive Pläne',
        'sp.section.templates': 'Vorlagen',
        'sp.section.archive': 'Archiv',
        'sp.section.activePerson': 'Arbeiten als',
        'sp.section.people': 'Personen',
        'sp.section.teams': 'Teams',
        'sp.section.planActions': 'Plan-Aktionen',
        'sp.section.workspaceActions': 'Arbeitsbereich',
        'sp.section.password': 'Passwortschutz',
        'sp.section.sharing': 'Freigabe',
        'sp.section.template': 'Vorlage',
        'sp.template.switchNote': 'Wechsle zu einer kompatiblen Stack-Variante (gleiche Sprint-Struktur). Fortschritt bleibt erhalten.',
        'sp.field.templateVariant': 'Vorlagen-Variante',
        'sp.action.switchTemplate': 'Vorlage wechseln',
        'sp.confirm.switchTemplate': 'Vorlage wechseln? Fortschritt und Zuweisungen bleiben erhalten; Hilfe, Flows und Texte kommen aus der neuen Vorlage.',
        'sp.toast.templateSwitched': 'Vorlage gewechselt',
        'sp.error.templateMissing': 'Vorlage nicht gefunden.',
        'sp.error.templateIncompatible': 'Vorlage ist strukturell nicht kompatibel.',
        'sp.sharing.note': 'Teile diesen Plan mit Benutzern oder Teams auf dieser Instanz (Accounts-Modus).',
        'sp.sharing.users': 'Betrachter (Benutzer)',
        'sp.sharing.teams': 'Betrachter (Teams)',
        'sp.sharing.save': 'Freigabe speichern',
        'sp.sharing.saved': 'Freigabe gespeichert',
        'sp.sharing.localOnly': 'Freigaben brauchen den Accounts-Modus.',
        'sp.story.read': 'gelesen',
        'sp.story.unread': 'ungelesen',
        'sp.password.note': 'Lokaler Soft-Lock nur in diesem Browser — keine echte Zugriffskontrolle.',
        'sp.password.statusOn': 'Dieser Plan ist passwortgeschützt.',
        'sp.password.statusOff': 'Kein Passwort gesetzt.',
        'sp.password.new': 'Neues Passwort',
        'sp.password.confirm': 'Passwort bestätigen',
        'sp.password.current': 'Aktuelles Passwort',
        'sp.password.unlockTitle': 'Plan entsperren',
        'sp.password.unlockLead': 'Dieser Plan ist lokal geschützt. Bitte Passwort eingeben.',
        'sp.password.unlock': 'Entsperren',
        'sp.password.set': 'Passwort setzen',
        'sp.password.change': 'Passwort ändern',
        'sp.password.remove': 'Passwort entfernen',
        'sp.password.lockSession': 'Erneut sperren',
        'sp.password.mismatch': 'Passwörter stimmen nicht überein.',
        'sp.password.wrong': 'Falsches Passwort.',
        'sp.password.tooShort': 'Mindestens 4 Zeichen.',
        'sp.password.saved': 'Passwortschutz gespeichert',
        'sp.password.removed': 'Passwortschutz entfernt',
        'sp.password.lockedBadge': 'Geschützt',
        'sp.empty.activePlans': 'Noch keine aktiven Pläne. Starte einen aus einer Vorlage.',
        'sp.empty.activePlansDemo': 'Noch kein Demo-Plan. Starte einen aus einer Vorlage — er bleibt nur in diesem Browser.',
        'sp.empty.archive': 'Keine archivierten Pläne.',
        'sp.empty.templates': 'Keine Vorlagen verfügbar.',
        'sp.filter.label': 'Filter',
        'sp.filter.all': 'Alle',
        'sp.filter.mine': 'Meine Pläne',
        'sp.filter.team': 'Team-Pläne',
        'sp.filter.completed': 'Abgeschlossen',
        'sp.filter.archived': 'Archiviert',
        'sp.filter.currentWeek': 'Nur aktuelle Woche',
        'sp.filter.hideDone': 'Erledigte ausblenden',
        'sp.filter.openOnly': 'Nur offene Elemente',
        'sp.filter.blocked': 'Blockierte Elemente',
        'sp.filter.myTasks': 'Meine Aufgaben',
        'sp.filter.unassigned': 'Nicht zugewiesen',
        'sp.filter.person': 'Person',
        'sp.filter.teamSelect': 'Team',
        'sp.filter.status': 'Status',
        'sp.filter.priority': 'Priorität',
        'sp.filter.any': 'Beliebig',
        'sp.action.exportWorkspace': 'Workspace exportieren',
        'sp.action.import': 'Importieren',
        'sp.action.cancel': 'Abbrechen',
        'sp.action.start': 'Starten',
        'sp.action.save': 'Speichern',
        'sp.action.addPerson': 'Person hinzufügen',
        'sp.action.addTeam': 'Team hinzufügen',
        'sp.action.addSprint': 'Sprint hinzufügen',
        'sp.action.settings': 'Einstellungen',
        'sp.action.backToPlans': 'Zurück zu den Plänen',
        'sp.action.backToPlan': 'Zurück zum Plan',
        'sp.action.exportPlan': 'Plan exportieren',
        'sp.action.duplicatePlan': 'Plan duplizieren',
        'sp.action.archivePlan': 'Plan archivieren',
        'sp.action.resetPlan': 'Plan zurücksetzen',
        'sp.action.deletePlan': 'Plan löschen',
        'sp.action.clearWorkspace': 'Lokale Daten löschen',
        'sp.action.open': 'Öffnen',
        'sp.action.startPlan': 'Plan starten',
        'sp.action.edit': 'Bearbeiten',
        'sp.action.duplicate': 'Duplizieren',
        'sp.action.moveUp': 'Nach oben',
        'sp.action.moveDown': 'Nach unten',
        'sp.action.delete': 'Löschen',
        'sp.action.reset': 'Zurücksetzen',
        'sp.action.archive': 'Archivieren',
        'sp.action.addTask': 'Aufgabe hinzufügen',
        'sp.action.addDeliverable': 'Deliverable hinzufügen',
        'sp.action.statusReport': 'Statusbericht',
        'sp.action.printReport': 'Drucken',
        'sp.action.readStories': 'Lesen',
        'sp.dialog.startTitle': 'Plan starten',
        'sp.dialog.personTitle': 'Person',
        'sp.dialog.teamTitle': 'Team',
        'sp.dialog.sprintTitle': 'Sprint',
        'sp.dialog.itemTitle': 'Element',
        'sp.field.startDate': 'Startdatum',
        'sp.field.team': 'Team',
        'sp.field.owner': 'Besitzer',
        'sp.field.participants': 'Beteiligte',
        'sp.field.activePerson': 'Aktive Person',
        'sp.field.defaultTeam': 'Standard-Team',
        'sp.field.displayName': 'Anzeigename',
        'sp.field.shortName': 'Kurzname',
        'sp.field.emailOptional': 'E-Mail (optional)',
        'sp.field.role': 'Rolle',
        'sp.field.teamNameDe': 'Name (DE)',
        'sp.field.teamNameEn': 'Name (EN)',
        'sp.field.teamDescDe': 'Beschreibung (DE)',
        'sp.field.teamDescEn': 'Beschreibung (EN)',
        'sp.field.members': 'Mitglieder',
        'sp.field.currentSprint': 'Aktueller Sprint',
        'sp.field.status': 'Status',
        'sp.card.owner': 'Besitzer: {{name}}',
        'sp.card.ownerDemo': 'Demo — kein Besitzer (nur Session)',
        'sp.card.ownerLocal': 'Lokal in diesem Browser',
        'sp.card.ownerUnknown': 'Besitzer unbekannt',
        'sp.ownership.mine': 'Mein Plan',
        'sp.ownership.shared': 'Geteilt mit mir',
        'sp.ownership.demo': 'Demo (Session)',
        'sp.field.titleDe': 'Titel (DE)',
        'sp.field.titleEn': 'Titel (EN)',
        'sp.field.goalDe': 'Ziel (DE)',
        'sp.field.goalEn': 'Ziel (EN)',
        'sp.field.position': 'Position',
        'sp.field.enableNotes': 'Notizen aktivieren',
        'sp.field.labelDe': 'Bezeichnung (DE)',
        'sp.field.labelEn': 'Bezeichnung (EN)',
        'sp.field.assigneeType': 'Zuordnungstyp',
        'sp.field.assignee': 'Zuordnung',
        'sp.field.priority': 'Priorität',
        'sp.field.dueDate': 'Fällig am',
        'sp.field.note': 'Notiz',
        'sp.field.none': '— Keine —',
        'sp.field.sprintStories': 'Playbook-Stories (Slugs)',
        'sp.field.sprintStoriesHint': 'Ein Slug pro Zeile',
        'sp.field.sprintLinks': 'Links',
        'sp.field.linksHint': 'Label | /pfad-oder-url',
        'sp.field.itemStories': 'Playbook-Stories (Slugs)',
        'sp.field.helpTextDe': 'Hilfetext (DE)',
        'sp.field.helpTextEn': 'Hilfetext (EN)',
        'sp.field.helpLinks': 'Hilfe-Links',
        'sp.field.demoCode': 'Demo-Code',
        'sp.field.blockerReason': 'Blockadegrund',
        'sp.help.title': 'Hilfe zur Aufgabe',
        'sp.help.open': 'Hilfe öffnen',
        'sp.help.close': 'Schließen',
        'sp.help.empty': 'Keine Hilfe hinterlegt.',
        'sp.help.story': 'Playbook',
        'sp.help.required': 'Pflicht',
        'sp.help.optional': 'Optional',
        'sp.help.requiredStories': 'Pflichtlektüre',
        'sp.help.optionalStories': 'Weiterführende Lektüre',
        'sp.help.links': 'Links',
        'sp.help.demo': 'Demo',
        'sp.help.flow': 'Ablauf',
        'sp.help.openStory': 'Playbook öffnen',
        'sp.help.markRead': 'Als gelesen markieren',
        'sp.sprint.storiesTitle': 'Lesen zu diesem Sprint',
        'sp.blockers.title': 'Blockierte Elemente',
        'sp.blockers.empty': 'Keine blockierten Elemente',
        'sp.report.title': 'Statusbericht',
        'sp.report.progress': 'Gesamtfortschritt',
        'sp.report.currentSprint': 'Aktueller Sprint',
        'sp.report.blockers': 'Blockierte Elemente',
        'sp.report.sprintProgress': 'Fortschritt je Sprint',
        'sp.report.requiredStories': 'Offene Pflichtlektüre',
        'sp.report.tasksByPerson': 'Aufgaben nach Person',
        'sp.report.empty': 'Keine Einträge',
        'sp.report.colSprint': 'Sprint',
        'sp.report.colItem': 'Element',
        'sp.report.colReason': 'Grund',
        'sp.report.colAssignee': 'Zugewiesen an',
        'sp.report.colStory': 'Story',
        'sp.report.colPerson': 'Person',
        'sp.report.colOpen': 'Offen',
        'sp.report.colBlocked': 'Blockiert',
        'sp.report.colCompleted': 'Erledigt',
        'sp.report.colTotal': 'Gesamt',
        'sp.report.unassigned': 'Nicht zugewiesen',
        'sp.status.open': 'Offen',
        'sp.status.inProgress': 'In Arbeit',
        'sp.status.blocked': 'Blockiert',
        'sp.status.completed': 'Erledigt',
        'sp.status.active': 'Aktiv',
        'sp.status.archived': 'Archiviert',
        'sp.priority.low': 'Niedrig',
        'sp.priority.normal': 'Normal',
        'sp.priority.high': 'Hoch',
        'sp.priority.critical': 'Kritisch',
        'sp.assignee.person': 'Person',
        'sp.assignee.team': 'Team',
        'sp.error.planMissing': 'Dieser Plan wurde im lokalen Speicher nicht gefunden.',
        'sp.error.storageUnavailable': 'localStorage ist nicht verfügbar.',
        'sp.error.storageFull': 'localStorage ist voll.',
        'sp.error.storageCorrupt': 'Gespeicherte Daten waren beschädigt und wurden zurückgesetzt.',
        'sp.error.importInvalid': 'Ungültige Importdatei.',
        'sp.error.importSchema': 'Nicht unterstützte Schema-Version.',
        'sp.toast.saved': 'Gespeichert',
        'sp.toast.imported': 'Import abgeschlossen',
        'sp.toast.exported': 'Export gestartet',
        'sp.toast.deleted': 'Gelöscht',
        'sp.toast.started': 'Plan gestartet',
        'sp.save.saving': 'Speichern…',
        'sp.save.saved': 'Gespeichert',
        'sp.save.error': 'Speichern fehlgeschlagen',
        'sp.card.duration': '{{count}} Wochen',
        'sp.card.progress': 'Fortschritt {{percent}}%',
        'sp.card.currentSprint': 'Sprint {{number}}',
        'sp.sprint.currentBadge': 'Aktuelle Woche',
        'sp.sprint.tasks': 'Aufgaben',
        'sp.sprint.deliverables': 'Deliverables',
        'sp.sprint.fields': 'Felder',
        'sp.sprint.notes': 'Notizen',
        'sp.confirm.deletePlan': 'Diesen Plan wirklich löschen? Das kann nicht rückgängig gemacht werden.',
        'sp.confirm.resetPlan': 'Fortschritt, Notizen und eigene Sprints dieses Plans zurücksetzen?',
        'sp.confirm.clearWorkspace': 'Alle lokalen Sprint-Planner-Daten löschen?',
        'sp.confirm.deleteSprint': 'Diesen Sprint löschen?',
        'sp.confirm.resetSprint': 'Diesen Sprint zurücksetzen?',
        'sp.import.modePrompt': 'Import-Konflikt: replace = ersetzen, merge = zusammenführen, new-ids = neue IDs, cancel = abbrechen',
        'sp.unit.week': 'Woche',
        'sp.unit.weeks': 'Wochen',
    },
    en: {
        'sp.pageTitle': 'Sprint Planner',
        'sp.pageLead': 'Run local sprint plans from Markdown templates — progress stays in your browser.',
        'sp.pageLeadDemo': 'Demo page: try plans locally — with a session demo, optional plan password, or sign-in to save on the server.',
        'sp.pageLeadAccounts': 'Saved plans sync to this server. Demo plans stay in the session only.',
        'sp.templatesTitle': 'Plan templates',
        'sp.templatesLead': 'Markdown templates define reusable sprint structures. Starting a plan creates a local instance.',
        'sp.peopleTitle': 'Teams & people',
        'sp.peopleLead': 'Local profiles only. Selecting an active person filters “My tasks” — it is not authentication.',
        'sp.peopleLeadAccounts': 'People and teams come from shared accounts. Manage them under Account when you have permission.',
        'sp.settingsTitle': 'Plan settings',
        'sp.nav.plans': 'My plans',
        'sp.nav.templates': 'Templates',
        'sp.nav.people': 'Teams & people',
        'sp.localBanner': 'Local workspace — no login, no access control',
        'sp.demo.guestBanner': 'Demo mode — try a plan in this browser session. Local login credentials are required to save.',
        'sp.demo.signedInBanner': 'Saved plans sync to this server. You can still start a session demo plan.',
        'sp.demo.sessionBanner': 'Options: session demo, plan password without login, or sign-in to save on the server.',
        'sp.demo.signIn': 'Sign in',
        'sp.demo.badge': 'Demo (session)',
        'sp.demo.planBanner': 'Demo plan — session only. Optional plan password without login (local). Sign in to save on the server.',
        'sp.action.startDemo': 'Start demo (session only)',
        'sp.action.startSave': 'Save plan',
        'sp.toast.demoStarted': 'Demo plan started (session only)',
        'sp.section.activePlans': 'Active plans',
        'sp.section.templates': 'Templates',
        'sp.section.archive': 'Archive',
        'sp.section.activePerson': 'Working as',
        'sp.section.people': 'People',
        'sp.section.teams': 'Teams',
        'sp.section.planActions': 'Plan actions',
        'sp.section.workspaceActions': 'Workspace',
        'sp.section.password': 'Password protection',
        'sp.section.sharing': 'Sharing',
        'sp.section.template': 'Template',
        'sp.template.switchNote': 'Switch to a compatible stack variant (same sprint structure). Progress is kept.',
        'sp.field.templateVariant': 'Template variant',
        'sp.action.switchTemplate': 'Switch template',
        'sp.confirm.switchTemplate': 'Switch template? Progress and assignments are kept; help, flows and copy come from the new template.',
        'sp.toast.templateSwitched': 'Template switched',
        'sp.error.templateMissing': 'Template not found.',
        'sp.error.templateIncompatible': 'Template is not structurally compatible.',
        'sp.sharing.note': 'Share this plan with users or teams on this instance (accounts mode).',
        'sp.sharing.users': 'Viewer users',
        'sp.sharing.teams': 'Viewer teams',
        'sp.sharing.save': 'Save sharing',
        'sp.sharing.saved': 'Sharing saved',
        'sp.sharing.localOnly': 'Sharing requires accounts mode.',
        'sp.story.read': 'read',
        'sp.story.unread': 'unread',
        'sp.password.note': 'Local soft lock in this browser only — not real access control.',
        'sp.password.statusOn': 'This plan is password protected.',
        'sp.password.statusOff': 'No password set.',
        'sp.password.new': 'New password',
        'sp.password.confirm': 'Confirm password',
        'sp.password.current': 'Current password',
        'sp.password.unlockTitle': 'Unlock plan',
        'sp.password.unlockLead': 'This plan is locally protected. Enter the password.',
        'sp.password.unlock': 'Unlock',
        'sp.password.set': 'Set password',
        'sp.password.change': 'Change password',
        'sp.password.remove': 'Remove password',
        'sp.password.lockSession': 'Lock again',
        'sp.password.mismatch': 'Passwords do not match.',
        'sp.password.wrong': 'Wrong password.',
        'sp.password.tooShort': 'At least 4 characters.',
        'sp.password.saved': 'Password protection saved',
        'sp.password.removed': 'Password protection removed',
        'sp.password.lockedBadge': 'Protected',
        'sp.empty.activePlans': 'No active plans yet. Start one from a template.',
        'sp.empty.activePlansDemo': 'No demo plan yet. Start one from a template — it stays in this browser only.',
        'sp.empty.archive': 'No archived plans.',
        'sp.empty.templates': 'No templates available.',
        'sp.filter.label': 'Filter',
        'sp.filter.all': 'All',
        'sp.filter.mine': 'My plans',
        'sp.filter.team': 'Team plans',
        'sp.filter.completed': 'Completed',
        'sp.filter.archived': 'Archived',
        'sp.filter.currentWeek': 'Current week only',
        'sp.filter.hideDone': 'Hide completed',
        'sp.filter.openOnly': 'Open items only',
        'sp.filter.blocked': 'Blocked items',
        'sp.filter.myTasks': 'My tasks',
        'sp.filter.unassigned': 'Unassigned',
        'sp.filter.person': 'Person',
        'sp.filter.teamSelect': 'Team',
        'sp.filter.status': 'Status',
        'sp.filter.priority': 'Priority',
        'sp.filter.any': 'Any',
        'sp.action.exportWorkspace': 'Export workspace',
        'sp.action.import': 'Import',
        'sp.action.cancel': 'Cancel',
        'sp.action.start': 'Start',
        'sp.action.save': 'Save',
        'sp.action.addPerson': 'Add person',
        'sp.action.addTeam': 'Add team',
        'sp.action.addSprint': 'Add sprint',
        'sp.action.settings': 'Settings',
        'sp.action.backToPlans': 'Back to plans',
        'sp.action.backToPlan': 'Back to plan',
        'sp.action.exportPlan': 'Export plan',
        'sp.action.duplicatePlan': 'Duplicate plan',
        'sp.action.archivePlan': 'Archive plan',
        'sp.action.resetPlan': 'Reset plan',
        'sp.action.deletePlan': 'Delete plan',
        'sp.action.clearWorkspace': 'Clear local data',
        'sp.action.open': 'Open',
        'sp.action.startPlan': 'Start plan',
        'sp.action.edit': 'Edit',
        'sp.action.duplicate': 'Duplicate',
        'sp.action.moveUp': 'Move up',
        'sp.action.moveDown': 'Move down',
        'sp.action.delete': 'Delete',
        'sp.action.reset': 'Reset',
        'sp.action.archive': 'Archive',
        'sp.action.addTask': 'Add task',
        'sp.action.addDeliverable': 'Add deliverable',
        'sp.action.statusReport': 'Status report',
        'sp.action.printReport': 'Print',
        'sp.action.readStories': 'Read',
        'sp.dialog.startTitle': 'Start plan',
        'sp.dialog.personTitle': 'Person',
        'sp.dialog.teamTitle': 'Team',
        'sp.dialog.sprintTitle': 'Sprint',
        'sp.dialog.itemTitle': 'Item',
        'sp.field.startDate': 'Start date',
        'sp.field.team': 'Team',
        'sp.field.owner': 'Owner',
        'sp.field.participants': 'Participants',
        'sp.field.activePerson': 'Active person',
        'sp.field.defaultTeam': 'Default team',
        'sp.field.displayName': 'Display name',
        'sp.field.shortName': 'Short name',
        'sp.field.emailOptional': 'Email (optional)',
        'sp.field.role': 'Role',
        'sp.field.teamNameDe': 'Name (DE)',
        'sp.field.teamNameEn': 'Name (EN)',
        'sp.field.teamDescDe': 'Description (DE)',
        'sp.field.teamDescEn': 'Description (EN)',
        'sp.field.members': 'Members',
        'sp.field.currentSprint': 'Current sprint',
        'sp.field.status': 'Status',
        'sp.card.owner': 'Owner: {{name}}',
        'sp.card.ownerDemo': 'Demo — no owner (session only)',
        'sp.card.ownerLocal': 'Local to this browser',
        'sp.card.ownerUnknown': 'Owner unknown',
        'sp.ownership.mine': 'My plan',
        'sp.ownership.shared': 'Shared with me',
        'sp.ownership.demo': 'Demo (session)',
        'sp.field.titleDe': 'Title (DE)',
        'sp.field.titleEn': 'Title (EN)',
        'sp.field.goalDe': 'Goal (DE)',
        'sp.field.goalEn': 'Goal (EN)',
        'sp.field.position': 'Position',
        'sp.field.enableNotes': 'Enable notes',
        'sp.field.labelDe': 'Label (DE)',
        'sp.field.labelEn': 'Label (EN)',
        'sp.field.assigneeType': 'Assignee type',
        'sp.field.assignee': 'Assignee',
        'sp.field.priority': 'Priority',
        'sp.field.dueDate': 'Due date',
        'sp.field.note': 'Note',
        'sp.field.none': '— None —',
        'sp.field.sprintStories': 'Playbook stories (slugs)',
        'sp.field.sprintStoriesHint': 'One slug per line',
        'sp.field.sprintLinks': 'Links',
        'sp.field.linksHint': 'Label | /path-or-url',
        'sp.field.itemStories': 'Playbook stories (slugs)',
        'sp.field.helpTextDe': 'Help text (DE)',
        'sp.field.helpTextEn': 'Help text (EN)',
        'sp.field.helpLinks': 'Help links',
        'sp.field.demoCode': 'Demo code',
        'sp.field.blockerReason': 'Blocker reason',
        'sp.help.title': 'Task help',
        'sp.help.open': 'Open help',
        'sp.help.close': 'Close',
        'sp.help.empty': 'No help available.',
        'sp.help.story': 'Playbook',
        'sp.help.required': 'Required',
        'sp.help.optional': 'Optional',
        'sp.help.requiredStories': 'Required reading',
        'sp.help.optionalStories': 'Further reading',
        'sp.help.links': 'Links',
        'sp.help.demo': 'Demo',
        'sp.help.flow': 'Flow',
        'sp.help.openStory': 'Open playbook',
        'sp.help.markRead': 'Mark as read',
        'sp.sprint.storiesTitle': 'Reading for this sprint',
        'sp.blockers.title': 'Blocked items',
        'sp.blockers.empty': 'No blocked items',
        'sp.report.title': 'Status report',
        'sp.report.progress': 'Overall progress',
        'sp.report.currentSprint': 'Current sprint',
        'sp.report.blockers': 'Blocked items',
        'sp.report.sprintProgress': 'Progress per sprint',
        'sp.report.requiredStories': 'Outstanding required reading',
        'sp.report.tasksByPerson': 'Tasks by person',
        'sp.report.empty': 'No entries',
        'sp.report.colSprint': 'Sprint',
        'sp.report.colItem': 'Item',
        'sp.report.colReason': 'Reason',
        'sp.report.colAssignee': 'Assignee',
        'sp.report.colStory': 'Story',
        'sp.report.colPerson': 'Person',
        'sp.report.colOpen': 'Open',
        'sp.report.colBlocked': 'Blocked',
        'sp.report.colCompleted': 'Completed',
        'sp.report.colTotal': 'Total',
        'sp.report.unassigned': 'Unassigned',
        'sp.status.open': 'Open',
        'sp.status.inProgress': 'In progress',
        'sp.status.blocked': 'Blocked',
        'sp.status.completed': 'Completed',
        'sp.status.active': 'Active',
        'sp.status.archived': 'Archived',
        'sp.priority.low': 'Low',
        'sp.priority.normal': 'Normal',
        'sp.priority.high': 'High',
        'sp.priority.critical': 'Critical',
        'sp.assignee.person': 'Person',
        'sp.assignee.team': 'Team',
        'sp.error.planMissing': 'This plan was not found in local storage.',
        'sp.error.storageUnavailable': 'localStorage is not available.',
        'sp.error.storageFull': 'localStorage is full.',
        'sp.error.storageCorrupt': 'Stored data was corrupt and was reset.',
        'sp.error.importInvalid': 'Invalid import file.',
        'sp.error.importSchema': 'Unsupported schema version.',
        'sp.toast.saved': 'Saved',
        'sp.toast.imported': 'Import complete',
        'sp.toast.exported': 'Export started',
        'sp.toast.deleted': 'Deleted',
        'sp.toast.started': 'Plan started',
        'sp.save.saving': 'Saving…',
        'sp.save.saved': 'Saved',
        'sp.save.error': 'Save failed',
        'sp.card.duration': '{{count}} weeks',
        'sp.card.progress': 'Progress {{percent}}%',
        'sp.card.currentSprint': 'Sprint {{number}}',
        'sp.sprint.currentBadge': 'Current week',
        'sp.sprint.tasks': 'Tasks',
        'sp.sprint.deliverables': 'Deliverables',
        'sp.sprint.fields': 'Fields',
        'sp.sprint.notes': 'Notes',
        'sp.confirm.deletePlan': 'Delete this plan? This cannot be undone.',
        'sp.confirm.resetPlan': 'Reset progress, notes, and custom sprints for this plan?',
        'sp.confirm.clearWorkspace': 'Clear all local Sprint Planner data?',
        'sp.confirm.deleteSprint': 'Delete this sprint?',
        'sp.confirm.resetSprint': 'Reset this sprint?',
        'sp.import.modePrompt': 'Import conflict: replace, merge, new-ids, or cancel',
        'sp.unit.week': 'week',
        'sp.unit.weeks': 'weeks',
    },
};

/**
 * @param {string} key
 * @param {SpLocale} locale
 * @param {Record<string, string|number>} [vars]
 */
export function t(key, locale, vars = {}) {
    let text = spLabels[locale]?.[key] || spLabels.en[key] || key;
    for (const [name, value] of Object.entries(vars)) {
        text = text.replaceAll(`{{${name}}}`, String(value));
    }
    return text;
}
