import { getLocale } from '../../locale.js';

export const labels = {
    de: {
        'powerbiDax.pageTitle': 'Power BI DAX Measure Generator',
        'powerbiDax.pageLead': 'Erzeuge DAX Measures, Time-Intelligence-Vorlagen, Hierarchie-Hinweise und Dokumentations-CSV aus Base Measures plus Definitionen.',
        'powerbiDax.help.title': 'Power BI DAX Hilfe',
        'powerbiDax.help.lead': 'Workflow-Hilfe für Katalog, Definitionen, Base Measures, Hierarchie und DAX Measures.',
        'powerbiDax.help.show': 'Hilfe anzeigen',
        'powerbiDax.help.hide': 'Hilfe ausblenden',
        'powerbiDax.help.productLink': 'Power BI Produktseite',
        'powerbiDax.help.productHelpLink': 'Power BI Hilfe-Portal',
        'powerbiDax.help.calculateLink': 'CALCULATE Dokumentation',
        'powerbiDax.help.measuresLink': 'Measures Dokumentation',
        'powerbiDax.help.summary': 'Kurzlogik',
        'powerbiDax.help.step1': 'Katalog pflegen: Tabellen, Spalten, Measures und Werte aus dem Power-BI-Modell eintragen.',
        'powerbiDax.help.step2': 'Definitionen bauen: Eine Definition wird zu einem DAX-Filter in CALCULATE.',
        'powerbiDax.help.step3': 'Base Measures sauber halten: Sales, Costs, Margin bleiben eigenständige Measures.',
        'powerbiDax.help.step4': 'Ausgabe kopieren: In Power BI Desktop ein neues Measure anlegen und DAX einfügen.',
        'powerbiDax.help.catalogTitle': '1. Katalog',
        'powerbiDax.help.definitionsTitle': '2. Definition',
        'powerbiDax.help.baseTitle': '3. Base Measures',
        'powerbiDax.help.outputTitle': '4. Ausgabe',
        'powerbiDax.help.whereTitle': 'Wo in Power BI?',
        'powerbiDax.help.whereBody': 'DAX Measures legst du in Power BI Desktop als neues Measure an. Hierarchien entstehen im Data Pane oder Model View, indem du Spalten unter eine Hierarchie ziehst.',
        'powerbiDax.apps.save': 'App speichern',
        'powerbiDax.apps.load': 'App laden',
        'powerbiDax.apps.delete': 'App löschen',
        'powerbiDax.apps.name': 'App-Name',
        'powerbiDax.apps.saved': 'Gespeicherte Apps',
        'powerbiDax.apps.none': 'Keine App gewählt',
        'powerbiDax.apps.missingName': 'Bitte einen App-Namen eingeben.',
        'powerbiDax.apps.missingSelection': 'Bitte eine gespeicherte App wählen.',
        'powerbiDax.apps.savedMessage': 'App „{name}“ gespeichert.',
        'powerbiDax.apps.deletedMessage': 'App „{name}“ gelöscht.',
        'powerbiDax.workbench.title': 'Formel-Workbench',
        'powerbiDax.workbench.description': 'Katalog, Base Measures und Definitionen sind getrennte Arbeitsbereiche. Die Ausgabe darunter bleibt separat kopier- und exportierbar.',
        'powerbiDax.workbench.controlTitle': 'Formel-Workbench',
        'powerbiDax.workbench.controlHint': 'App-Kontext, Katalog, Base-Formeln, Filter und Hierarchie bearbeiten.',
        'powerbiDax.workbench.hide': 'Workbench ausblenden',
        'powerbiDax.workbench.show': 'Workbench anzeigen',
        'powerbiDax.layout.catalog': 'Katalog',
        'powerbiDax.layout.formula': 'Formel',
        'powerbiDax.layout.builder': 'Filter & Baum',
        'powerbiDax.layout.focusFormula': 'Fokus Formel',
        'powerbiDax.layout.showAll': 'Alles anzeigen',
        'powerbiDax.tabs.definitions': 'Definitionen',
        'powerbiDax.tabs.hierarchy': 'Hierarchie',
        'powerbiDax.tabs.extras': 'Extras',
        'powerbiDax.catalog.title': 'Modell-Katalog',
        'powerbiDax.catalog.fields': 'Felder',
        'powerbiDax.catalog.values': 'Dim-Werte',
        'powerbiDax.catalog.rawData': 'Rohdaten bearbeiten',
        'powerbiDax.catalog.rawDataHint': 'Fields und Values als CSV pflegen oder Dateien hochladen.',
        'powerbiDax.catalog.fieldsUpload': 'Fields CSV laden',
        'powerbiDax.catalog.valuesUpload': 'Values CSV laden',
        'powerbiDax.catalog.tabs.dimensions': 'Dimensionen',
        'powerbiDax.catalog.tabs.measures': 'Measures',
        'powerbiDax.catalog.hint': 'Chips ziehen oder anklicken. Rohdaten öffnest du über den Button darunter.',
        'powerbiDax.modal.close': 'Schließen',
        'powerbiDax.definitions.title': 'Definitionen',
        'powerbiDax.definitions.hint': 'Spalte und Werte wählen, speichern und als CALCULATE-Filter nutzen.',
        'powerbiDax.definitions.column': 'Spalte',
        'powerbiDax.definitions.values': 'Werte',
        'powerbiDax.definitions.name': 'Name',
        'powerbiDax.definitions.add': 'Definition speichern',
        'powerbiDax.definitions.raw': 'Definitionen CSV',
        'powerbiDax.definitions.preview': 'DAX-Filter',
        'powerbiDax.definitions.dropTitle': 'Spalte hier ablegen',
        'powerbiDax.definitions.dropHint': 'Ziehe eine Dimension aus dem Katalog hierher, um daraus einen CALCULATE-Filter zu bauen.',
        'powerbiDax.definitions.remove': 'Entfernen',
        'powerbiDax.formula.title': 'Formel',
        'powerbiDax.formula.hint': 'Hier baust und bearbeitest du die aktive DAX Base Measure. Bausteine und Felder werden an der Cursor-Position eingefügt.',
        'powerbiDax.formula.current': 'Aktuelle Formel',
        'powerbiDax.formula.name': 'Measure Name',
        'powerbiDax.formula.field': 'Spalte',
        'powerbiDax.formula.apply': 'Base Measure setzen',
        'powerbiDax.history.undo': 'Rückgängig',
        'powerbiDax.history.redo': 'Wiederholen',
        'powerbiDax.functions.title': 'DAX-Funktionen',
        'powerbiDax.functions.hint': 'Baustein anklicken, um die Formel zu erweitern.',
        'powerbiDax.baseList.title': 'Base Measures',
        'powerbiDax.baseList.hint': 'Aktive Base laden, speichern oder neu anlegen.',
        'powerbiDax.baseList.show': 'Anzeigen',
        'powerbiDax.baseList.hide': 'Ausblenden',
        'powerbiDax.baseList.active': 'Aktive Base',
        'powerbiDax.baseList.load': 'Base laden',
        'powerbiDax.baseList.saveCurrent': 'Current speichern',
        'powerbiDax.baseList.newBase': 'Neue Base',
        'powerbiDax.baseList.csv': 'Base Measures CSV',
        'powerbiDax.baseList.rawHint': 'CSV bleibt die Quelle für gespeicherte Base Measures.',
        'powerbiDax.description.title': 'Beschreibung',
        'powerbiDax.description.hint': 'Beschreibungstemplates werden für die generierten Power BI Measures genutzt.',
        'powerbiDax.description.de': 'Template DE',
        'powerbiDax.description.en': 'Template EN',
        'powerbiDax.extras.title': 'Extras',
        'powerbiDax.extras.hint': 'Generierungsmodus und Date-Spalte für Time Intelligence.',
        'powerbiDax.extras.mode': 'Generierungsmodus',
        'powerbiDax.extras.modeSingle': 'Ein Child pro Dimensionswert',
        'powerbiDax.extras.modeCombined': 'Dimensionen zu Varianten kombinieren',
        'powerbiDax.extras.modeDimensionGroup': 'Ein Child pro Dimension mit allen Werten',
        'powerbiDax.extras.dateColumn': 'Date-Spalte (Time Intelligence)',
        'powerbiDax.extras.dateHint': "DAX-Spalte für YTD/PY/YoY, z.B. 'Date'[Date].",
        'powerbiDax.output.measures': 'Measures',
        'powerbiDax.output.time': 'Zeit',
        'powerbiDax.output.hierarchy': 'Hierarchie',
        'powerbiDax.output.defs': 'Definitionen',
        'powerbiDax.output.csv': 'CSV',
        'powerbiDax.copy': 'Kopieren',
        'powerbiDax.downloadCsv': 'CSV laden',
        'powerbiDax.downloadXlsx': 'Excel laden',
        'powerbiDax.saved': 'Definition gespeichert.',
        'powerbiDax.hierarchy.title': 'Hierarchie',
        'powerbiDax.hierarchy.hint': 'Dimensionen ablegen oder eingerückte Ebenen pflegen. Der Child-Baum zeigt die Base Measure als Wurzel.',
        'powerbiDax.hierarchy.dropTitle': 'Hierarchie-Ebene hier ablegen',
        'powerbiDax.hierarchy.dropHint': 'Ziehe Dimensionen hierher. Sie werden an die Hierarchie angehängt.',
        'powerbiDax.tree.title': 'Measure-Child-Baum',
        'powerbiDax.tree.hint': 'Dimensionen auf die Base oder einen Knoten legen, um verschachtelte Pfade zu bauen.',
        'powerbiDax.tree.base': 'Base Measure',
        'powerbiDax.tree.dropOnBase': 'Dimension auf erster Ebene ablegen',
        'powerbiDax.tree.dropOnNode': 'Unter {level} ablegen',
        'powerbiDax.tree.remove': 'Entfernen',
    },
    en: {
        'powerbiDax.pageTitle': 'Power BI DAX Measure Generator',
        'powerbiDax.pageLead': 'Generate DAX measures, time-intelligence snippets, hierarchy guidance and documentation CSV from base measures plus definitions.',
        'powerbiDax.help.title': 'Power BI DAX help',
        'powerbiDax.help.lead': 'Workflow help for catalog, definitions, base measures, hierarchy, and DAX measures.',
        'powerbiDax.help.show': 'Show help',
        'powerbiDax.help.hide': 'Hide help',
        'powerbiDax.help.productLink': 'Power BI product page',
        'powerbiDax.help.productHelpLink': 'Power BI help portal',
        'powerbiDax.help.calculateLink': 'CALCULATE documentation',
        'powerbiDax.help.measuresLink': 'Measures documentation',
        'powerbiDax.help.summary': 'Quick logic',
        'powerbiDax.help.step1': 'Maintain the catalog: add tables, columns, measures and values from your Power BI model.',
        'powerbiDax.help.step2': 'Build definitions: a definition becomes a DAX filter inside CALCULATE.',
        'powerbiDax.help.step3': 'Keep base measures clean: Sales, Costs, Margin stay independent measures.',
        'powerbiDax.help.step4': 'Copy output: create a new measure in Power BI Desktop and paste the DAX.',
        'powerbiDax.help.catalogTitle': '1. Catalog',
        'powerbiDax.help.definitionsTitle': '2. Definition',
        'powerbiDax.help.baseTitle': '3. Base measures',
        'powerbiDax.help.outputTitle': '4. Output',
        'powerbiDax.help.whereTitle': 'Where in Power BI?',
        'powerbiDax.help.whereBody': 'DAX measures are created as new measures in Power BI Desktop. Hierarchies are created in the Data pane or Model view by dragging columns into a hierarchy.',
        'powerbiDax.apps.save': 'Save app',
        'powerbiDax.apps.load': 'Load app',
        'powerbiDax.apps.delete': 'Delete app',
        'powerbiDax.apps.name': 'App name',
        'powerbiDax.apps.saved': 'Saved apps',
        'powerbiDax.apps.none': 'No app selected',
        'powerbiDax.apps.missingName': 'Please enter an app name.',
        'powerbiDax.apps.missingSelection': 'Please select a saved app.',
        'powerbiDax.apps.savedMessage': 'App “{name}” saved.',
        'powerbiDax.apps.deletedMessage': 'App “{name}” deleted.',
        'powerbiDax.workbench.title': 'Formula workbench',
        'powerbiDax.workbench.description': 'Catalog, base measures and definitions are separate work areas. The output below stays separate for copy and export.',
        'powerbiDax.workbench.controlTitle': 'Formula workbench',
        'powerbiDax.workbench.controlHint': 'Edit app context, catalog, base formulas, filters and hierarchy.',
        'powerbiDax.workbench.hide': 'Hide workbench',
        'powerbiDax.workbench.show': 'Show workbench',
        'powerbiDax.layout.catalog': 'Catalog',
        'powerbiDax.layout.formula': 'Formula',
        'powerbiDax.layout.builder': 'Filter & tree',
        'powerbiDax.layout.focusFormula': 'Focus formula',
        'powerbiDax.layout.showAll': 'Show all',
        'powerbiDax.tabs.definitions': 'Definitions',
        'powerbiDax.tabs.hierarchy': 'Hierarchy',
        'powerbiDax.tabs.extras': 'Extras',
        'powerbiDax.catalog.title': 'Model catalog',
        'powerbiDax.catalog.fields': 'Fields',
        'powerbiDax.catalog.values': 'Dim values',
        'powerbiDax.catalog.rawData': 'Edit raw data',
        'powerbiDax.catalog.rawDataHint': 'Maintain fields and values as CSV or upload files.',
        'powerbiDax.catalog.fieldsUpload': 'Upload fields CSV',
        'powerbiDax.catalog.valuesUpload': 'Upload values CSV',
        'powerbiDax.catalog.tabs.dimensions': 'Dimensions',
        'powerbiDax.catalog.tabs.measures': 'Measures',
        'powerbiDax.catalog.hint': 'Drag or click chips. Open raw data with the button below.',
        'powerbiDax.modal.close': 'Close',
        'powerbiDax.definitions.title': 'Definitions',
        'powerbiDax.definitions.hint': 'Pick a column and values, save, and reuse as a CALCULATE filter.',
        'powerbiDax.definitions.column': 'Column',
        'powerbiDax.definitions.values': 'Values',
        'powerbiDax.definitions.name': 'Name',
        'powerbiDax.definitions.add': 'Save definition',
        'powerbiDax.definitions.raw': 'Definitions CSV',
        'powerbiDax.definitions.preview': 'DAX filter',
        'powerbiDax.definitions.dropTitle': 'Drop column here',
        'powerbiDax.definitions.dropHint': 'Drag a dimension from the catalog here to build a CALCULATE filter.',
        'powerbiDax.definitions.remove': 'Remove',
        'powerbiDax.formula.title': 'Formula',
        'powerbiDax.formula.hint': 'Build and edit the active DAX base measure here. Blocks and fields are inserted at the cursor position.',
        'powerbiDax.formula.current': 'Current formula',
        'powerbiDax.formula.name': 'Measure name',
        'powerbiDax.formula.field': 'Column',
        'powerbiDax.formula.apply': 'Set base measure',
        'powerbiDax.history.undo': 'Undo',
        'powerbiDax.history.redo': 'Redo',
        'powerbiDax.functions.title': 'DAX functions',
        'powerbiDax.functions.hint': 'Click a block to extend the formula.',
        'powerbiDax.baseList.title': 'Base measures',
        'powerbiDax.baseList.hint': 'Load, save or create the active base measure.',
        'powerbiDax.baseList.show': 'Show',
        'powerbiDax.baseList.hide': 'Hide',
        'powerbiDax.baseList.active': 'Active base',
        'powerbiDax.baseList.load': 'Load base',
        'powerbiDax.baseList.saveCurrent': 'Save current',
        'powerbiDax.baseList.newBase': 'New base',
        'powerbiDax.baseList.csv': 'Base measures CSV',
        'powerbiDax.baseList.rawHint': 'CSV remains the source for saved base measures.',
        'powerbiDax.description.title': 'Description',
        'powerbiDax.description.hint': 'Description templates are used for the generated Power BI measures.',
        'powerbiDax.description.de': 'Template DE',
        'powerbiDax.description.en': 'Template EN',
        'powerbiDax.extras.title': 'Extras',
        'powerbiDax.extras.hint': 'Generation mode and date column for time intelligence.',
        'powerbiDax.extras.mode': 'Generation mode',
        'powerbiDax.extras.modeSingle': 'One child per dimension value',
        'powerbiDax.extras.modeCombined': 'Combine dimensions into variants',
        'powerbiDax.extras.modeDimensionGroup': 'One child per dimension with all values',
        'powerbiDax.extras.dateColumn': 'Date column (time intelligence)',
        'powerbiDax.extras.dateHint': "DAX column for YTD/PY/YoY, e.g. 'Date'[Date].",
        'powerbiDax.output.measures': 'Measures',
        'powerbiDax.output.time': 'Time',
        'powerbiDax.output.hierarchy': 'Hierarchy',
        'powerbiDax.output.defs': 'Definitions',
        'powerbiDax.output.csv': 'CSV',
        'powerbiDax.copy': 'Copy',
        'powerbiDax.downloadCsv': 'Download CSV',
        'powerbiDax.downloadXlsx': 'Download Excel',
        'powerbiDax.saved': 'Definition saved.',
        'powerbiDax.hierarchy.title': 'Hierarchy',
        'powerbiDax.hierarchy.hint': 'Drop dimensions or edit indented levels. The child tree shows the base measure as root.',
        'powerbiDax.hierarchy.dropTitle': 'Drop hierarchy level here',
        'powerbiDax.hierarchy.dropHint': 'Drag dimensions here. They are appended to the hierarchy.',
        'powerbiDax.tree.title': 'Measure child tree',
        'powerbiDax.tree.hint': 'Drop dimensions on the base or a node to build nested paths.',
        'powerbiDax.tree.base': 'Base measure',
        'powerbiDax.tree.dropOnBase': 'Drop dimension on first level',
        'powerbiDax.tree.dropOnNode': 'Drop under {level}',
        'powerbiDax.tree.remove': 'Remove',
    },
};

export function t(key) {
    const locale = getLocale() === 'en' ? 'en' : 'de';

    return labels[locale][key] ?? labels.de[key] ?? key;
}
