import { GOVERNANCE_AREAS, PRODUCT_FIELDS, MULTIPLE_ROW_FIELDS } from './model.js';

/**
 * Build DE/EN label maps for the tool.
 * @returns {Record<'de'|'en', Record<string, string>>}
 */
export function buildToolLabels() {
    const areaNames = {
        de: {
            ownership: 'Ownership',
            identityAccess: 'Identity and Access',
            classification: 'Classification',
            policies: 'Policies',
            lineage: 'Lineage',
            dataQuality: 'Data Quality',
            incidentOwnership: 'Incident Ownership',
            retention: 'Retention',
            environmentModel: 'Environment Model',
            costAccountability: 'Cost Accountability',
            semanticOwnership: 'Semantic Ownership',
        },
        en: {
            ownership: 'Ownership',
            identityAccess: 'Identity and Access',
            classification: 'Classification',
            policies: 'Policies',
            lineage: 'Lineage',
            dataQuality: 'Data Quality',
            incidentOwnership: 'Incident Ownership',
            retention: 'Retention',
            environmentModel: 'Environment Model',
            costAccountability: 'Cost Accountability',
            semanticOwnership: 'Semantic Ownership',
        },
    };

    const productFieldLabels = {
        de: {
            fabric: {
                tenantCapacity: 'Tenant und Capacity',
                domainsWorkspaces: 'Domains und Workspaces',
                purviewBoundary: 'Purview Boundary',
                semanticModelOwnership: 'Semantic Model Ownership',
                deploymentModel: 'Deployment Model',
            },
            databricks: {
                cloudRegion: 'Cloud und Region',
                accountMetastore: 'Account und Metastore',
                catalogSchemaBoundaries: 'Catalog und Schema Boundaries',
                workspacesCompute: 'Workspaces und Compute',
                unityCatalogPolicies: 'Unity Catalog Policies',
            },
            snowflake: {
                accountRegion: 'Account und Region',
                roleHierarchy: 'Role Hierarchy',
                tagsClassification: 'Tags und Classification',
                maskingRowAccess: 'Masking und Row Access Policies',
                sharingBoundary: 'Sharing Boundary',
            },
            bigquery: {
                organizationProjects: 'Organization und Projects',
                region: 'Region',
                datasetModel: 'Dataset Model',
                iamFineGrained: 'IAM und Fine-Grained Access',
                exportCostBoundary: 'Export und Cost Boundary',
            },
            dbt: {
                supportedPlatforms: 'Unterstützte Plattformen',
                sourceModelScope: 'Source und Model Scope',
                metadataSchema: 'Metadata Schema',
                contractsTests: 'Contracts und Tests',
                pullRequestApproval: 'Pull-Request Approval',
                deploymentEvidence: 'Deployment Evidence',
                catalogPolicyHandoff: 'Catalog und Policy Handoff',
            },
        },
        en: {
            fabric: {
                tenantCapacity: 'Tenant and Capacity',
                domainsWorkspaces: 'Domains and Workspaces',
                purviewBoundary: 'Purview Boundary',
                semanticModelOwnership: 'Semantic Model Ownership',
                deploymentModel: 'Deployment Model',
            },
            databricks: {
                cloudRegion: 'Cloud and Region',
                accountMetastore: 'Account and Metastore',
                catalogSchemaBoundaries: 'Catalog and Schema Boundaries',
                workspacesCompute: 'Workspaces and Compute',
                unityCatalogPolicies: 'Unity Catalog Policies',
            },
            snowflake: {
                accountRegion: 'Account and Region',
                roleHierarchy: 'Role Hierarchy',
                tagsClassification: 'Tags and Classification',
                maskingRowAccess: 'Masking and Row Access Policies',
                sharingBoundary: 'Sharing Boundary',
            },
            bigquery: {
                organizationProjects: 'Organization and Projects',
                region: 'Region',
                datasetModel: 'Dataset Model',
                iamFineGrained: 'IAM and Fine-Grained Access',
                exportCostBoundary: 'Export and Cost Boundary',
            },
            dbt: {
                supportedPlatforms: 'Supported platforms',
                sourceModelScope: 'Source and Model Scope',
                metadataSchema: 'Metadata Schema',
                contractsTests: 'Contracts and Tests',
                pullRequestApproval: 'Pull-Request Approval',
                deploymentEvidence: 'Deployment Evidence',
                catalogPolicyHandoff: 'Catalog and Policy Handoff',
            },
        },
    };

    const multipleLabels = {
        de: {
            platform: 'Plattform',
            workload: 'Workload',
            authoritativeMetadata: 'Authoritative metadata source',
            identityAuthority: 'Identity authority',
            classificationAuthority: 'Classification authority',
            enforcementPoint: 'Enforcement point',
            lineageHandoff: 'Lineage handoff',
            qualityEvidence: 'Quality evidence',
            semanticOwner: 'Semantic owner',
            incidentOwner: 'Incident owner',
            costOwner: 'Cost owner',
            consolidationTrigger: 'Consolidation trigger',
        },
        en: {
            platform: 'Platform',
            workload: 'Workload',
            authoritativeMetadata: 'Authoritative metadata source',
            identityAuthority: 'Identity authority',
            classificationAuthority: 'Classification authority',
            enforcementPoint: 'Enforcement point',
            lineageHandoff: 'Lineage handoff',
            qualityEvidence: 'Quality evidence',
            semanticOwner: 'Semantic owner',
            incidentOwner: 'Incident owner',
            costOwner: 'Cost owner',
            consolidationTrigger: 'Consolidation trigger',
        },
    };

    /** @type {Record<'de'|'en', Record<string, string>>} */
    const labels = {
        de: {
            'gspd.pageTitle': 'Governance Starting-Point Decision',
            'gspd.pageLead':
                'Dokumentiere den Governance-Plattform-Einstieg: Kontext, Design, produktspezifische Felder, Lücken und Entscheidung.',
            'gspd.howto.intro':
                'Standalone-Artefakt für die Plattform-Einstiegsentscheidung. Optional Kontext aus dem Custom Stack Builder; Ergebnis als Markdown für Doku oder Sprint Planner.',
            'gspd.howto.step1': 'Produkt wählen (URL ?product= oder Dropdown).',
            'gspd.howto.step2': 'Entscheidungskontext und Governance Design ausfüllen.',
            'gspd.howto.step3': 'Produktspezifische Felder, Lücken und Entscheidung erfassen.',
            'gspd.howto.step4': 'Entwurf speichern und Decision Record kopieren oder herunterladen.',
            'gspd.howto.tip':
                'Draft liegt lokal im Browser. Für Team-Arbeit Markdown in den Sprint Planner übernehmen — Persistenz liegt beim Plan.',
            'gspd.stackHint': 'Kontext aus Custom Stack Builder erkannt.',
            'gspd.stackHintLink': 'Stack Builder öffnen',
            'gspd.exportHint':
                'Decision Record kopieren/herunterladen oder Entwurf lokal speichern. Beim Verlassen ohne Export geht ungespeicherter Inhalt verloren.',
            'gspd.saveDraft': 'Entwurf speichern',
            'gspd.loadDraft': 'Entwurf laden',
            'gspd.draftSaved': 'Entwurf gespeichert',
            'gspd.draftLoaded': 'Entwurf geladen',
            'gspd.draftMissing': 'Kein gespeicherter Entwurf gefunden',
            'gspd.clearConfirm': 'Formular zurücksetzen? Der lokale Entwurf bleibt erhalten, bis du ihn überschreibst.',
            'gspd.product': 'Produkt',
            'gspd.product.placeholder': 'Produkt wählen',
            'gspd.product.fabric': 'Microsoft Fabric',
            'gspd.product.databricks': 'Databricks + Unity Catalog',
            'gspd.product.snowflake': 'Snowflake',
            'gspd.product.bigquery': 'BigQuery',
            'gspd.product.dbt': 'dbt Governance Control Layer',
            'gspd.product.multiple': 'Governance Across Multiple Platforms',
            'gspd.section.context': 'Entscheidungskontext',
            'gspd.section.design': 'Governance Design',
            'gspd.section.productFields': 'Produktspezifische Felder',
            'gspd.section.multiple': 'Mehrere Plattformen',
            'gspd.section.gaps': 'Lücken und Validierung',
            'gspd.section.decision': 'Entscheidung',
            'gspd.context.title': 'Titel der Entscheidung',
            'gspd.context.firstUseCase': 'Erster Governance-Use-Case',
            'gspd.context.existingContext': 'Bestehender Kontext',
            'gspd.context.decisionGoal': 'Ziel der Entscheidung',
            'gspd.context.decisionOwner': 'Decision Owner',
            'gspd.context.dataOwner': 'Data Owner',
            'gspd.context.dataSteward': 'Data Steward',
            'gspd.context.technicalOwner': 'Technical Owner',
            'gspd.context.reviewDate': 'Review-Datum',
            'gspd.area.status': 'Status',
            'gspd.area.description': 'Beschreibung',
            'gspd.area.owner': 'Verantwortlicher',
            'gspd.area.evidence': 'Evidenz',
            'gspd.area.gap': 'Offene Lücke',
            'gspd.areaStatus.notAssessed': 'Not Assessed',
            'gspd.areaStatus.missing': 'Missing',
            'gspd.areaStatus.partial': 'Partial',
            'gspd.areaStatus.defined': 'Defined',
            'gspd.areaStatus.validated': 'Validated',
            'gspd.areaStatus.approved': 'Approved',
            'gspd.list.knownGaps': 'Bekannte Governance-Lücken',
            'gspd.list.requiredTests': 'Notwendige Tests',
            'gspd.list.openQuestions': 'Offene Fragen',
            'gspd.list.blockers': 'Blocker',
            'gspd.list.exceptions': 'Ausnahmen',
            'gspd.list.evidenceLinks': 'Evidenz-Links',
            'gspd.list.add': 'Eintrag hinzufügen',
            'gspd.list.itemPlaceholder': 'Eintrag…',
            'gspd.exception.owner': 'Ausnahmeverantwortlicher',
            'gspd.exception.expiry': 'Ablaufdatum',
            'gspd.decision.status': 'Decision Status',
            'gspd.decision.preferredStartingPattern': 'Preferred Starting Pattern',
            'gspd.decision.conditionalAlternative': 'Conditional Alternative',
            'gspd.decision.noNewPlatformAlternative': 'No-New-Platform Alternative',
            'gspd.decision.blockers': 'Blockers',
            'gspd.decision.validationPlan': 'Validation Plan',
            'gspd.decision.noRegretNextStep': 'No-Regret Next Step',
            'gspd.decision.decisionRationale': 'Decision Rationale',
            'gspd.decision.implementationOwner': 'Implementation Owner',
            'gspd.decision.approvalOwner': 'Approval Owner',
            'gspd.decision.reviewDate': 'Review Date',
            'gspd.decisionStatus.draft': 'Draft',
            'gspd.decisionStatus.readyForReview': 'Ready for Review',
            'gspd.decisionStatus.readyForProofOfValue': 'Ready for Proof of Value',
            'gspd.decisionStatus.conditional': 'Conditional',
            'gspd.decisionStatus.approved': 'Approved',
            'gspd.decisionStatus.blocked': 'Blocked',
            'gspd.decisionStatus.rejected': 'Rejected',
            'gspd.multiple.row': 'Plattformzeile',
            'gspd.multiple.add': 'Plattformzeile hinzufügen',
            'gspd.multiple.empty': 'Noch keine Plattformzeilen',
            'gspd.md.title': 'Governance Starting-Point Decision Record',
            'gspd.md.generated': 'Erstellt am',
            'discovery.exportTitle': 'Governance Starting-Point Decision',
            'discovery.ephemeral':
                'Standalone nutzbar: Entwurf optional lokal speichern. Entscheidung als Markdown kopieren/herunterladen oder in den Sprint Planner übernehmen.',
            'discovery.warnTitle': 'Ergebnis übernehmen oder Entwurf speichern',
            'discovery.warnBody':
                'Ohne gespeicherten Entwurf gehen Eingaben beim Verlassen verloren. Speichere den Entwurf lokal und/oder kopiere den Decision Record.',
        },
        en: {
            'gspd.pageTitle': 'Governance Starting-Point Decision',
            'gspd.pageLead':
                'Record the governance platform starting point: context, design, product-specific fields, gaps, and decision.',
            'gspd.howto.intro':
                'Standalone artifact for the platform starting-point decision. Optional context from Custom Stack Builder; export Markdown for docs or the Sprint Planner.',
            'gspd.howto.step1': 'Choose a product (URL ?product= or dropdown).',
            'gspd.howto.step2': 'Fill decision context and governance design.',
            'gspd.howto.step3': 'Capture product-specific fields, gaps, and the decision.',
            'gspd.howto.step4': 'Save a draft and copy or download the decision record.',
            'gspd.howto.tip':
                'Drafts stay in the local browser. For team work, apply Markdown to the Sprint Planner — persistence lives with the plan.',
            'gspd.stackHint': 'Context detected from Custom Stack Builder.',
            'gspd.stackHintLink': 'Open Stack Builder',
            'gspd.exportHint':
                'Copy/download the decision record or save a local draft. Leaving without export discards unsaved input.',
            'gspd.saveDraft': 'Save draft',
            'gspd.loadDraft': 'Load draft',
            'gspd.draftSaved': 'Draft saved',
            'gspd.draftLoaded': 'Draft loaded',
            'gspd.draftMissing': 'No saved draft found',
            'gspd.clearConfirm': 'Reset the form? The local draft remains until you overwrite it.',
            'gspd.product': 'Product',
            'gspd.product.placeholder': 'Choose product',
            'gspd.product.fabric': 'Microsoft Fabric',
            'gspd.product.databricks': 'Databricks + Unity Catalog',
            'gspd.product.snowflake': 'Snowflake',
            'gspd.product.bigquery': 'BigQuery',
            'gspd.product.dbt': 'dbt Governance Control Layer',
            'gspd.product.multiple': 'Governance Across Multiple Platforms',
            'gspd.section.context': 'Decision context',
            'gspd.section.design': 'Governance design',
            'gspd.section.productFields': 'Product-specific fields',
            'gspd.section.multiple': 'Multiple platforms',
            'gspd.section.gaps': 'Gaps and validation',
            'gspd.section.decision': 'Decision',
            'gspd.context.title': 'Decision title',
            'gspd.context.firstUseCase': 'First governance use case',
            'gspd.context.existingContext': 'Existing context',
            'gspd.context.decisionGoal': 'Decision goal',
            'gspd.context.decisionOwner': 'Decision Owner',
            'gspd.context.dataOwner': 'Data Owner',
            'gspd.context.dataSteward': 'Data Steward',
            'gspd.context.technicalOwner': 'Technical Owner',
            'gspd.context.reviewDate': 'Review date',
            'gspd.area.status': 'Status',
            'gspd.area.description': 'Description',
            'gspd.area.owner': 'Owner',
            'gspd.area.evidence': 'Evidence',
            'gspd.area.gap': 'Open gap',
            'gspd.areaStatus.notAssessed': 'Not Assessed',
            'gspd.areaStatus.missing': 'Missing',
            'gspd.areaStatus.partial': 'Partial',
            'gspd.areaStatus.defined': 'Defined',
            'gspd.areaStatus.validated': 'Validated',
            'gspd.areaStatus.approved': 'Approved',
            'gspd.list.knownGaps': 'Known governance gaps',
            'gspd.list.requiredTests': 'Required tests',
            'gspd.list.openQuestions': 'Open questions',
            'gspd.list.blockers': 'Blockers',
            'gspd.list.exceptions': 'Exceptions',
            'gspd.list.evidenceLinks': 'Evidence links',
            'gspd.list.add': 'Add item',
            'gspd.list.itemPlaceholder': 'Item…',
            'gspd.exception.owner': 'Exception owner',
            'gspd.exception.expiry': 'Expiry date',
            'gspd.decision.status': 'Decision Status',
            'gspd.decision.preferredStartingPattern': 'Preferred Starting Pattern',
            'gspd.decision.conditionalAlternative': 'Conditional Alternative',
            'gspd.decision.noNewPlatformAlternative': 'No-New-Platform Alternative',
            'gspd.decision.blockers': 'Blockers',
            'gspd.decision.validationPlan': 'Validation Plan',
            'gspd.decision.noRegretNextStep': 'No-Regret Next Step',
            'gspd.decision.decisionRationale': 'Decision Rationale',
            'gspd.decision.implementationOwner': 'Implementation Owner',
            'gspd.decision.approvalOwner': 'Approval Owner',
            'gspd.decision.reviewDate': 'Review Date',
            'gspd.decisionStatus.draft': 'Draft',
            'gspd.decisionStatus.readyForReview': 'Ready for Review',
            'gspd.decisionStatus.readyForProofOfValue': 'Ready for Proof of Value',
            'gspd.decisionStatus.conditional': 'Conditional',
            'gspd.decisionStatus.approved': 'Approved',
            'gspd.decisionStatus.blocked': 'Blocked',
            'gspd.decisionStatus.rejected': 'Rejected',
            'gspd.multiple.row': 'Platform row',
            'gspd.multiple.add': 'Add platform row',
            'gspd.multiple.empty': 'No platform rows yet',
            'gspd.md.title': 'Governance Starting-Point Decision Record',
            'gspd.md.generated': 'Generated on',
            'discovery.exportTitle': 'Governance Starting-Point Decision',
            'discovery.ephemeral':
                'Works standalone: optionally save a local draft. Copy/download the decision as Markdown or apply it to the Sprint Planner.',
            'discovery.warnTitle': 'Transfer the result or save a draft',
            'discovery.warnBody':
                'Without a saved draft, leaving discards your input. Save the draft locally and/or copy the decision record.',
        },
    };

    for (const locale of /** @type {const} */ (['de', 'en'])) {
        for (const areaId of GOVERNANCE_AREAS) {
            labels[locale][`gspd.area.${areaId}`] = areaNames[locale][areaId];
        }
        for (const [productId, fields] of Object.entries(PRODUCT_FIELDS)) {
            for (const fieldId of fields) {
                labels[locale][`gspd.productField.${productId}.${fieldId}`] =
                    productFieldLabels[locale][productId][fieldId];
            }
        }
        for (const fieldId of MULTIPLE_ROW_FIELDS) {
            labels[locale][`gspd.multiple.${fieldId}`] = multipleLabels[locale][fieldId];
        }
    }

    return labels;
}
